### ISSUE TITLE
6.0.0 Peers will not connect

### ISSUE THREAD

**Issue by CryptoKilla** [vergecurrency/VERGE#1006]
I just got the new Leviosa wallet 6.0.0, I am stuck at connecting to peers from the very beginning. The application has not downloaded a single block. I have checked the firewall and the connection is allowed. I am running the qt wallet on a windows 10 64 bit system. I am running tor as well as i thought it might be an issue related to need to route through tor but that does not help as well. My previous wallet was 4.0.0 which also seemed to not have any connection as well. I tried deleting the peers.dat file as suggested in another post but still get nothing.

![image](https://user-images.githubusercontent.com/35278750/70400043-b4d0a800-19e5-11ea-97fa-d7de64e351ca.png)

**Comment by justinvforvendetta** [comment]
try going into the help/debug console, and typing this:
`addnode "amafdqgkmtbkld45kaal5cwwfbrsgnimw77gawwltsaklgxxlubjvhid.onion" add`

**Comment by CryptoKilla** [comment]
null

btw thank you for a quick reply, one of the biggest reasons i stand behind verge is the involvement of the devs and the wonderful community around this coin

**Comment by CryptoKilla** [comment]
PS while it didnt seem to at first this worked

**Comment by justinvforvendetta** [comment]
great, did it find more than 1 connection eventually as well? or just the one?
