### ISSUE TITLE
0 addresses found from DNS seeds , TOR is banned on Iran

### ISSUE THREAD

**Issue by m4hdi1995** [vergecurrency/VERGE#1007]
Hello, i'm trying to run a verge full node but verged is not able to sync with the network, server is located on Iran and tor is blocked here (it sometimes work on the desktop but it seems it's completely blocked on this data center i'm using),
I already grabbed some addresses from doc/peers.txt and added them into VERGE.conf but it doesn't work, ./verge-cli getblockchaininfo shows : 
"chain": "main",
  "blocks": 0,
  "headers": 0,
what can i do to sync my full node? thanks.
verge version : 6.0.0
Xeon server, Ubuntu 18.04, 64GB Ram, 1Gbps Connection.

**Comment by m4hdi1995** [comment]
Hello, i'm trying to run a verge full node but verged is not able to sync with the network, server is located on Iran and tor is blocked here (it sometimes work on the desktop but it seems it's completely blocked on this data center i'm using),
I already grabbed some addresses from doc/peers.txt and added them into VERGE.conf but it doesn't work, ./verge-cli getblockchaininfo shows : 
"chain": "main",
  "blocks": 0,
  "headers": 0,
what can i do to sync my full node? thanks.

**Comment by justinvforvendetta** [comment]
@m4hdi1995 you can install obs4proxy and try to run tor again, or you can start the daemon with --without-tor, like this:  `./verged --without-tor`

**Comment by m4hdi1995** [comment]
--without-tor flag worked, thanks.

**Comment by justinvforvendetta** [comment]
@m4hdi1995 look into obs4proxy if you would like to use verge with tor. glad it is working for you now.

**Comment by m4hdi1995** [comment]
@justinvforvendetta i will take a look into it thanks again, we are running our node for our Exchange actually https://parsxc.com .

**Comment by justinvforvendetta** [comment]
feel free to add it to our website exchange list by making a pull request. our website is in https://github.com/vergecurrency/vergecurrency.com

**Comment by m4hdi1995** [comment]
@justinvforvendetta wow thanks, i will.
