### ISSUE TITLE
Dynamic Network

### ISSUE THREAD

**Issue by marpme** [vergecurrency/verge#1009]
### Synopsis

We might face capacity shortages when it comes to bring nodes active on both sides (clearnet / tor network). That's why it would make sense to introduce dynamic nodes for them who have to use the clearnet mode since the node would now be shared between both networks by default. Which makes it easy to share blocks etc. throughout both networks.

Right now you have to solely build your tor proxy on top of a clearnet node in order to archieve this very approach. Which isn't quite easy for exchanges and/or miners to handle thus I would suggest to activate the dynamic network.

### Technical Idea

**Clearnet** vs **Tor-Net**

```
your node         <->     other clearnet nodes
proxy nodes       <->     all nodes
tor node          <->     tor nodes
```

**Dynamic Networking** 
_(keeps tor networking + removes the restrictions from clearnet routes)_

```
your dyn. node    <->     other clearnet nodes
    ↕
tor node          <->     tor nodes
```

**Comment by 2lazy2debug** [comment]
ACK

**Comment by justinvforvendetta** [comment]
![donkeykong](https://66.media.tumblr.com/93f9545d8edb5708a990995e36130f65/tumblr_ndlj77wuBw1s335jfo1_r2_500.gif)

**Comment by tpfuemp** [comment]
the main problem for using mining on tor-enabled nodes is the misbehaviour of timedrift-calculation leading to 'time-too-new' errors. fixing this + adding some reserved connection slots for clearnet-only would help to get connected to both worlds

**Comment by marpme** [comment]
Since the upgrade to V6 I haven't discovered any occurance of time-too-new errors. I assume that we got rid off it, since now all v6's are creating the blocks and thus it's not possible to create the "time-too-new" error as it would be quickly declined by the network.

but regarding the second point I have no good idea how to deal with this. I mean we could just devide connections slots by 50/50 so that you can't have only either clearnet nodes nor only tor nodes, but that will take some more efforts I think. Let's investigate :)

**Comment by tpfuemp** [comment]
there was no change of code in v6 on this, the issue is still there.
taken from current logfile:
`2019-12-28T21:12:54Z ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: aa5fb241e2a1488206de44060f6a396dd1e0dd90e23412d4376690343ea26721, time-too-new, block timestamp too far in the future (code 16)`

**Comment by marpme** [comment]
Too me this feels like we falsely calculate the max block drift in V6:

https://github.com/vergecurrency/VERGE/blob/349c3653416f58242be57bffdd1774fae86660af/src/validation.cpp#L3323-L3328

to me this should be `... * 1000` since timestamps are defined in ms, but well .. 🤔

**Comment by skinderis** [comment]
Getting this log error all the time:
`2020-01-07T12:43:07Z ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 65396b5bba56a6311e0b61c3ca3bc37d9404eed1147ebb12a699da860ebc70e7, time-too-new, block timestamp too far in the future (code 16)`

**Comment by marpme** [comment]
> Getting this log error all the time:
> `2020-01-07T12:43:07Z ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 65396b5bba56a6311e0b61c3ca3bc37d9404eed1147ebb12a699da860ebc70e7, time-too-new, block timestamp too far in the future (code 16)`

Seems like it is due to this piece of code: https://github.com/vergecurrency/VERGE/issues/1009#issuecomment-569456329
But I would have to investigate if timestamps are now in seconds rather than minutes, but yeah it's a known issue

**Comment by tpfuemp** [comment]
for mining nodes it would be an option to disable calculation of local timedrift (https://github.com/vergecurrency/VERGE/blob/1a49a2cfd01d12e1e3135905a922ee6c1c0da47e/src/net_processing.cpp#L1819). a accurate local time is essential for mining, so its better to trust on local time then timedrift from remote sources.

**Comment by marpme** [comment]
Partially released with a non-fixed count of clearnet nodes. Usually (never had the case) we never ran out of clearnet connection tho.

**Comment by marpme** [comment]
@tpfuemp @skinderis To me this feels like the max-time-drift is false rather than the time transmitted from the peers itself. I think we have to allow more drift. The V4 has the same function as in V6 but for some reason I _assume_ that the V4 calcuated everything is seconds and now everything is present in milliseconds. 

That's also why, raising the `max-drift * 1000`, is perfectly resolving this very issue. I'm clearly aware of the consequences of such an change, but anyhow. This needs investigation.

**Comment by justinvforvendetta** [comment]
a 10 minute drift time is pretty massive already -_-
