### ISSUE TITLE
RPC server not accessible no bind on 127.0.0.1:20102

### ISSUE THREAD

**Issue by lanaiscool** [vergecurrency/VERGE#101]
So im trying to et VERGEd to work but it wont bind on 20102 also .VERGEd gives me error: couldn't connect to server

**Comment by weemen** [comment]
I've this issue as well

**Comment by justinvforvendetta** [comment]
once you run ./VERGEd just wait a few and then try getinfo

**Comment by justinvforvendetta** [comment]
as long as you have the conf properly set up it will work

**Comment by weemen** [comment]
@justinvforvendetta 
Yeah the conf was my problem because if you use the docker ubuntu image then out of the box it won't work. I've added: rpcallowip option and now it works.

Thanks to this issue: https://github.com/vergecurrency/VERGE/issues/41 I could find these options.
