### ISSUE TITLE
Transition Help Needed

### ISSUE THREAD

**Issue by rmphilli** [vergecurrency/VERGE#1017]
Need a good samaritan to walk me through this. I've gone out to the Verge site directly to pull the most recent wallet for Windows. I have an old version of the wallet, on a different computer all together, and would like to transition over to an ios iphone wallet. Could someone reach out with steps about how to install the most updated wallet, then, how to get them on the ios wallet for iphone?

# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by jrsikors** [comment]
what 'old wallet' do you have?  The QT wallet or Electrum ?  Can you open it, go to Help -> Debug .. and post a screen shot of the information tab.

**Comment by justinvforvendetta** [comment]
> Need a good samaritan to walk me through this. I've gone out to the Verge site directly to pull the most recent wallet for Windows. I have an old version of the wallet, on a different computer all together, and would like to transition over to an ios iphone wallet.

why did you get the most recent wallet for windows, if you want to transition from the old qt on a different computer to the iOS?

> Could someone reach out with steps about how to install the most updated wallet, then, how to get them on the ios wallet for iphone?

open your old wallet, immediately send the coins on it to the ios wallet that you installed on your iphone from the itunes store.

**Comment by rmphilli** [comment]
Thank you for the advice. I'll fire up the old wallet and see if I can send over to my IOS wallet. I was avoiding doing so due to some language that I saw out on the main Verge site, that said, I'll still take a shot at it.

**Comment by justinvforvendetta** [comment]
not sure what you mean by that, but ok =]
