### ISSUE TITLE
xvg electrum sync

### ISSUE THREAD

**Issue by saawan77** [vergecurrency/VERGE#1018]
# Issue Template

## Context
I cannot acces my xvg electrum wallet anymore.
The wallet is not synchronizing. I have the 2.4.1 xvg wallet.
Some time ago i red about a attack on the electrum wallets that caused the problems.
can someone help me get acces to my coins ?
I have the xvg wallet on windows 10.
i am not very technical, so please reply in simple to understand solutions.
Willing to give a reward in xvg to anyone who would be able to help.

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by marpme** [comment]
@justinvforvendetta can you maybe share you latest electrum node?

**Comment by justinvforvendetta** [comment]
@saawan77 you need to switch to the tor electrum.

**Comment by saawan77** [comment]
Hi ,

can i fil in my seed in the torelectrum wallet ?
I have read some people were having problems doing so and i am a little nervous that i will mess it up

**Comment by justinvforvendetta** [comment]
you can use your seed, of course, that is how you restore the coins to it

**Comment by saawan77** [comment]
Hi Justinvforvendetta,
I was awfully occupied with other things and could not solve this problem.
I dont see the torelectrum on the verge website. is there any other way to restore my coins from the old electrum wallet ?
