### ISSUE TITLE
Incomplete support for mining with AMD GPU

### ISSUE THREAD

**Issue by Technophant** [vergecurrency/VERGE#102]
For Nvidia users, cgminer handles all algos well.  However, there's no one fork of sgminer that does the same.  X17 is in it's own fork and blake2s isn't supported at all.  I propose a bounty to develop a new fork of sgminer that call handle all algos.

**Comment by Cryptominer937** [comment]
Blake2s, Lyra2rev2, Groestl
https://github.com/nicehash/sgminer/releases/download/5.6.1/sgminer-5.6.1-nicehash-51-windows-amd64.zip

That fork would just need someone to add the x17 kernels and compile the miner as scrypt is 100% ASIC territory.

**Comment by EssKayz** [comment]
Not really sure how this is a problem with Verge in itself. Try posting this on SGMiner repo also, as there will probably be more people who could be interested in doing this.
