### ISSUE TITLE
Old clients

### ISSUE THREAD

**Issue by Coinomatron** [vergecurrency/VERGE#1020]
Hi, all but 1 connection out of the 15 on my node are 4.0 versions. Was the fork supposed to work like that? Cheers.

**Comment by justinvforvendetta** [comment]
you can pull the latest changes, and it will block v4 and v5 peers =]

**Comment by Coinomatron** [comment]
They're not showing anymore after a git pull and recompile, but now I only have 1 connection. I noticed the block explorer also has just 1 connection. We'll see, I hope the node count will increase over time.

**Comment by justinvforvendetta** [comment]
there are a ton of v6 peers.. if you are a mining pool, i suggest running verged --without-tor btw. less latency.

**Comment by Coinomatron** [comment]
Nope, no mining pool. But the --without-tor is a nice tip, thanks.

**Comment by Coinomatron** [comment]
So, version 6 connects fine without tor, but with tor, I get 0 connections. Tried the addnodes from Altilly: https://www.altilly.com/asset/XVG 
but no luck. Any ideas?

**Comment by justinvforvendetta** [comment]
thats because if you are not using tor, your peers.dat is filling up with clearnet peers. then, when you switch to tor, you dont have tor peers. try deleting your peers.dat each time if you are going to switch back and forth from clearnet to tor.

**Comment by Coinomatron** [comment]
That worked, thanks!
