### ISSUE TITLE
Unable to Remotely RPC Verge from Another Server

### ISSUE THREAD

**Issue by daygle** [vergecurrency/VERGE#1022]
I am after your assistance in relation to an issue I have encountered with Verge. I have setup a Verge wallet on a remote Debian server and wanted to remotely connect to the wallet from another Debian server.

On the Verge wallet server I have added the relevant rpcallowip=##IP Address## to the conf file and unfortunately the other server is unable to connect. I have other wallets that are able to connect the same way.

Has this functionality been removed? Has rpcallowip been setup to disallow remote connections from other servers? Do you have any other recommendations on how to make this work (to allow a remote server to connect to the Verge wallet server).

**Comment by justinvforvendetta** [comment]
@daygle the `rpcallowip` option can no longer be used to automatically listen on all network interfaces. Instead, the `rpcbind` parameter must be used to specify the IP addresses to listen on.
