### ISSUE TITLE
[Packaging] Make this wallet available as flatpak on FlatHub

### ISSUE THREAD

**Issue by Nokia808** [vergecurrency/verge#1028]
Hi. Can you, kindly, make your wallet available as flatpak package on FlatHub? This way, you will make your wallet available for almost all Linux distros & users. Flatpak is a universal generic Linux package & is secure & sandbox.

Flatpak is much better than AppImage formate, being more secure & more convenient & easier to packaged than AppImage.

**Comment by justinvforvendetta** [comment]
@Nokia808 looking into it right now. should be able to get it done tonight, looks pretty simple.

**Comment by Nokia808** [comment]
1) home page of FlatHub is:
    https://www.flathub.org/home
2) FlatHub repositories are at:
    https://github.com/flathub
3) when some one like to add package to FlatHub, she/he need to open PR at:
    https://github.com/flathub/flathub/pulls
4) FlatHub differ from snap by being allow any one to package not only developers of packages. So packages on FlatHub are of 2 kinds regarding this point: some are packaged by their developers like shotcut video editor, while other are packaged by person other than their developers. So,
5) developers of Veerge themselves can package their wallets by themselves. This will be ideal.
6) all packages on FlatHub are signed .....
7) even if person other than the original developer(s) maintain the package on FlatHub, FlatHub team try as much as possible to make developer(s) authorized to repositories at least to monitor & follow up the packaging ......
8) FlatHub allow both open & closed source packages. But regarding open source packages, the FlatHub team insisting on packager to make them deterministic (reproducible).

**Comment by Nokia808** [comment]
@justinvforvendetta 
Hi. I noticed your PR on FlatHub. Thank you very much ! I'm sure that you will complete it soon ....

Only one think: please do not to add lightweight wallet "electrum verge" also, not just the full node wallet ...... Many users prefer to use lightweight wallet rather than full node wallet because later need to download whole blockchain, which is something more secure & needed for those who miner (generate) the coins, but it is inconvenient for those who only like to send & receive coins ....

Best.

**Comment by justinvforvendetta** [comment]
I will add electrum once the new electrum is ready. thanks!

**Comment by justinvforvendetta** [comment]
ok, submitted a PR and it is building properly. hopefully it's approved. i'll work on electrum in the near future. 

https://github.com/flathub/flathub/pull/1420

**Comment by Nokia808** [comment]
@justinvforvendetta 
Many thanks! 
I posted a comment in request for electrum verge wallet. Please read it, it is useful.
