### ISSUE TITLE
Low quality wallet without digital signatures and certificates.

### ISSUE THREAD

**Issue by ls-milkyway** [vergecurrency/verge#1034]
Kaspersky detecting trojan UDS:Trojan.Win32.AgentB....It found no signature of the application...no popularity.....no domain certificates for secure connection???

![virus](https://user-images.githubusercontent.com/55090624/84088477-3c858680-aa0a-11ea-97d6-6024efc2378e.png)

## Context

Not able to use any wallet....even electrum wallet is not working ....posted issue there with pictures....no body responding.....they are misguiding the wallet users ...they even don't know the file name of the wallet for windows....

[https://github.com/vergecurrency/VERGE/issues/912](url)

* [ ] Are you running the latest version?

Yes

## Expected Behavior

Instead of wasting time on Logos and design......try to include certificates...signatures....whitelist the app on antivirus sites...build community in cloud to increase it's reputation.......don't suggest silly excuses that most Anti-Viruses detect crypto-wallet as virus.

There are many high quality wallets out there working with default Anti-virus settings.

## Current Behavior

Not working.

## Screenshots

Check screen shots
![no-signature](https://user-images.githubusercontent.com/55090624/84088616-88383000-aa0a-11ea-86fa-076f6b793774.png)

## Your Environment

* Verge Release: 6.0.2
* CPU: Fast enough
* GPU: Superb
* RAM: 8 GB
* OS: Windows 7 Ultimate 64 bit

## Any extra information that might be useful in the debugging process.

No, that's u are going to find out.
Kaspersky removed the trojan and allowed the wallet to load blockchain....but says "certificate chain is not complete" repeatedly causing connection to 0 peers.

![connection](https://user-images.githubusercontent.com/55090624/84088584-76568d00-aa0a-11ea-9435-7cd3a1956df7.png)

**Comment by justinvforvendetta** [comment]
maybe you are unaware that virus detectors also flag bitcoin-qt.exe as a virus. and every single miner.exe as well.

**Comment by ls-milkyway** [comment]
Yeah, Everyone except you is new to computers...that's why you are planting trojans with your shitty wallet and even Kaspersky have just started to learn from you......Others in the market like Raven, Litecoin, Cardano, Stellar blah blah ...are trailing behind you.......They are fools to get their Wallet clean in My Kaspersky scan or live protection...or may Kaspersky encountered  a qt-wallet for first time .......they are not as experienced as you are @ verge.....also others like Symantec, bitdefender are learning from you.

**Comment by justinvforvendetta** [comment]
youre a genius. im sure Max Hillebrand and Loshan are making up the issue on bitcoin and litecoin.
https://github.com/litecoin-project/litecoin/issues/623
https://github.com/bitcoin/bitcoin/issues/17779

**Comment by marpme** [comment]
![image](https://user-images.githubusercontent.com/7430964/84112358-e4aa4800-aa28-11ea-9d5c-679038294933.png)

* Where did you download our verge wallet from? 
* How can you be so sure that you didn't just downloaded a real virus? This URL above looks really scammy. 

Please make sure to download it only from github link here:  https://github.com/vergecurrency/verge/releases/download/v6.0.2/verge-6.0.2-win64-setup-unsigned.exe

**Comment by SwenVanZanten** [comment]
What a dick

**Comment by justinvforvendetta** [comment]
kfetbpz? is this guy even serious? lol
