### ISSUE TITLE
error: Your client produced a transaction that is not accepted by the Bitcoin network any more. Please upgrade to Electrum 2.5.1 or newer

### ISSUE THREAD

**Issue by JoopM** [vergecurrency/verge#1038]
My Electrum XVG Tor wallet on MAC keeps saying "error: Your client produced a transaction that is not accepted by the Bitcoin network any more. Please upgrade to Electrum 2.5.1 or newer" when sending out a transaction.

## Context

I'm trying to send out XVG to another XVG wallet. 

I'm using Electrum XVG Tor for years on this MAC. Never got this problem. 

* [-] Are you running the latest version? Yes, as in 2.4

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [-] support request YES!
  - [ ] translation request

I'm working with MAC.

![Snip20200616_1](https://user-images.githubusercontent.com/38051143/84819374-300bba00-b018-11ea-95ed-d112eb101a1f.png)

**Comment by marpme** [comment]
Move to QT-Wallet, we are working on a new electrum client in the meantime
