### ISSUE TITLE
Verge QT Wallet - Is there a way to extract the encrypted passphrase somewhere in the .dat file? 

### ISSUE THREAD

**Issue by Magri51** [vergecurrency/verge#1039]
# Issue Template

## Context

If I have my Verge-QT wallet.dat file, can I extract the encrypted passphrase so I can't send my Verge??

## Prerequisites

* [x ] Are you running the latest version? yes

## User Story: Last night, I was updating some of my passwords, and I updated the encrypted password on my Verge QT Windows 10 software. After trying to send some of my Verge to my mobile Verge wallet today, the passphrase that I entered did not work! For some reason, I wrote down the passphrase incorrectly and now I am LOCKED out of my account! 

I can see all my Verge on my home screen...but because the software has been encrypted, I cannot send the Verge unless I enter the correct password. Since I do not have the password, I cant send anything! 

I took my wife's computer and uploaded the Verge-QT windows 10 edition and then I added my 'wallet.dat' file to the verge folder. Once the blockchain synced, my Verge popped up, but the damn encryption button was still pressed keeping me from accessing the Verge. I also spent the last 4 hours randomly trying to repeat the passphrase...but I am out of luck. 

To lose more than 650K Verge is unacceptable simply due to a password change error! There HAS to be a way for me to find my encryption passphrase so I can send my currency! Please help as I am sick to my stomach on the possibility of losing this much money. God Bless

Chris

* "I'm submitting a ... "
  - [x ] support request 

## Possible Solution

Solution would be to somehow extract the private keys of my Verge and open them on another Verge wallet...will that work so I can by-pass the Verge-QT encryption?

## Your Environment

* Verge Release: 5.9.8
    - [x ] I'm using Windows 10

**Comment by justinvforvendetta** [comment]
you can not bypass the encryption, unless you already have your private key, in which case you can just import it into a new wallet.

**Comment by justinvforvendetta** [comment]
also what do you mean version 5.9.8? there is no such thing.

**Comment by Magri51** [comment]
Why can't I reset the encryption password if I have the wallet.dat in my hands? everything is inside the file...but you're telling me that I cant reset my own password? 

The version number came from the Verge Levoisa Wallet - About QT program. I attached the info below. I thought it could add value to my problem. 

Is there a way to open the file using RUBY and reset the encryption password...or to open it to get the private key? Is there a way to have a password cracker run a script to try to unlock the phrase? 

If not, then...that is a HUGE flaw in the Verge system. If making a common error of a password mistake loses ALL my Verge, then that is NOT fair. Almost all other blockchain providers have a backup to get your info if the passwords get lost! 

Is there ANY other options on what I can do...I'm desperate as I have a lot of money in Verge!! 

Thank you for your time. 

Chris
![qt](https://user-images.githubusercontent.com/67032860/84850703-406a6780-b00d-11ea-9265-cb2a8f055110.png)

**Comment by justinvforvendetta** [comment]
it would defeat the purpose of encryption if you could reset the password lol, this is the same for bitcoin and all cryptocurrencies. in cryptography, you do not just "reset a password". if you lose your privatekey or encryption password, it is lost. if it could be reset, crypto would have no value.

**Comment by Magri51** [comment]
If you lose your email, you can get a password link to reset it. Private keys are one thing..if you lose those, then I agree...that's on you....but losing a password??? Passwords should be recoverable if you can prove that you own the wallet.dat file. That is a HUGE flaw in the verge system that needs to be fixed.
 
Why cant the wallet.dat file be able to extract the info?? Is there a way to open the wallet.dat file to look at the contents? at least to find the private key?

**Comment by justinvforvendetta** [comment]
it is not a flaw in the verge system. it is the same for bitcoin as well. encryption passwords are not "recoverable". the wallet.dat is encrypted, that is why you can not extract the info (unless you have the password to extract it)

**Comment by justinvforvendetta** [comment]
are you sure you dont have the right password? keep trying it, maybe you'll get lucky.
