### ISSUE TITLE
Integration with RenProtocol for DeFi support

### ISSUE THREAD

**Issue by samadsajanlal** [vergecurrency/verge#1043]
# Issue Template

## Context

Verge's mission statement is to be a currency for the masses. One subject that comes up with regards to currency is the ability to lend, borrow, and earn interest (like a savings account) on XVG holdings. Today, Verge acts more like a basic cash alternative - it offers peer to peer payments in an arguably private setting and allows for transactions between parties. The concept of borrowing/lending/earning on Verge holdings is not considered, as the chain does not support such actions.

Enter DeFi. You've heard of it. Everyone is salivating over it. It's a movement to allow the ability to borrow/lend/earn on holdings by using smart contracts to offer that type of functionality in a trustless setting. But Verge cannot implement this on chain without significantly deviating from its roots and possibly requiring a chain swap, which may or may not be an option that developers are considering.

Enter RenProtocol. From what I understand, RenProtocol offers the ability to issue IOU's on a separate chain for a specific coin. So, for XVG, there would be an IOU issued called renXVG. The interaction between XVG and renXVG would be seamless, and users could transfer their XVG to renXVG at any given time - and transfer back at any given time as well. RenXVG would allow the ability to use smart contracts and other ethereum-native functionality that would be a massive chore to implement on top of XVG itself. The extra capability offered by integrating with such a system would enable XVG to truly realize its potential as a currency with the ability to offer lending/borrowing/earning and still maintain its core roots as a bitcoin-based cryptocurrency.

I opened this issue to highly suggest the XVG core team to look into RenProtocol or its alternatives as an option to extend the capability that verge has to offer in order to fully realize its mission of becoming a currency for the masses.

More info on Ren: https://renproject.io/

## Prerequisites

* [x ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [x ] feature request
  - [ ] support request 
  - [ ] translation request 

As a user wanting to transact with Verge, I want the ability to lend and borrow my holdings in a trustless fashion, allowing the ability to earn on my holdings as well.

## Expected Behavior

Feature request. Not a bug.

## Current Behavior

Feature request. Not a bug.

## Screenshots

Feature request. Not an issue with the GUI.

## Possible Solution

Integrate with RenProtocol to allow the capabilities of Ethereum to be used with Verge, such as smart contracts.

## Steps to Reproduce (for bugs)

* Steps :
1. Not a bug

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

## Any extra information that might be useful in the debugging process.

Digibyte, Dogecoin, Acalanetwork and others are integrating Ren Protocol. Verge should too. https://twitter.com/bzlwang/status/1287631874500640771

I am not affiliated with RenProtocol by any means and am simply suggesting this as a possible option to the Verge development team. I have experience working on bitcoin-based coins (which can be seen from my profile) and have a small holding of XVG.

**Comment by justinvforvendetta** [comment]
you are sure this is something we need to do to our code? i dont see any code changes to digibyte or dogecoin for ren protocol support.

**Comment by samadsajanlal** [comment]
It's not really a code change on XVG's part, it was more of a "hey this could be a good way to help Verge achieve it's mission". I've been talking to Alex (xvg ninja) on Telegram and he suggested opening a github issue to get this in front of the dev team for discussion.

**Comment by justinvforvendetta** [comment]
gotcha. i sent a message to bzlwang. we'll see what he says.
