### ISSUE TITLE
The problem with Verge Lumos wallet

### ISSUE THREAD

**Issue by JennySi** [vergecurrency/verge#1044]
Verge Lumos version v5.3.1.0

Doesn't open and stops at
![VL002](https://user-images.githubusercontent.com/69755580/90334644-d30c9000-dfd7-11ea-9908-90c56d121ce3.jpg)
How can this be fixed?
Thank you

**Comment by justinvforvendetta** [comment]
@JennySi hi, that wallet is very old. please use the 6.2

**Comment by JennySi** [comment]
> @JennySi привет, кошелек очень старый. пожалуйста, используйте 6.2

This will lead to the loss of Verga on the old purse?

**Comment by justinvforvendetta** [comment]
@JennySi no, of course not!

**Comment by JennySi** [comment]
Version updated to 6.2
But the problem remained
![VS6](https://user-images.githubusercontent.com/69755580/90340011-c1d67a00-dffd-11ea-8688-1adb4d18721d.jpg)

**Comment by justinvforvendetta** [comment]
@JennySi  try deleting the blockchain data (but not the wallet.dat file) (make a copy of the wallet.dat file somewhere)

**Comment by jrsikors** [comment]
https://verge.zendesk.com/hc/en-us/articles/360015942312-Syncing-is-slow-stuck-will-take-forever

**Comment by jrsikors** [comment]
actually it looks like your new problem might be 0 connections.  You might just need to wait a bit until you find peers.

Or you can go into your console and put in these 4 commands (1 at a time), and it should expedite finding peers:
addnode "wn6cugxlhk6a4t2b7o6muiiudve4voa64l2w6xke6vebgleh7l3naoad.onion" add
addnode "urtf7ovgjnxilnbxppmhvjebxcwk4ofo36mgz4kmwr7i4aqimdknf7ad.onion" add
addnode "7tlb223yvv76fwte4krz6gpop4j5nirulio3sfylp47ooze5f3glhjid.onion" add
addnode "q5hfxlthp6nkmfxf5wppijphyukplwo6dsqdr2cmvofodasrmirkeuqd.onion" add
