### ISSUE TITLE
Can not connect to Verge

### ISSUE THREAD

**Issue by mutobui** [vergecurrency/verge#1045]
# Socket hang up

I use verge-nodejs to connect to Verge in local and get message:

{ Error: socket hang up
    at createHangUpError (_http_client.js:332:15)
    at Socket.socketOnEnd (_http_client.js:435:23)
    at Socket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }

* Version:
- Latest

* OS:
    - I'm using Linux

**Comment by justinvforvendetta** [comment]
can you show how you are using it?

**Comment by mutobui** [comment]
Hi Sunerok,

Thank you for your email, follow is my steps:

1. Create an instance of Verge (image1, image2)
2. Create verge-nodejs and connect to Verge (image3)
3. Call api (image3)

- Configuration:
Verge config: (image5)
Nodejs-verge config: (image6)

Got: errors ''Client network socket disconnected before secure TLS
connection was established" (image7)

Expect: Client's information

Glad to hear from you soon.

Thank you

**Comment by justinvforvendetta** [comment]
no images came through, so i have no idea how you are using it, as in, the code you have created that uses the api.

also, you are using Verge 6.0.2?

**Comment by mutobui** [comment]
Yes, I use Verge Leviosa version v6.0.2.0 (64-bit), Ubuntu. Is there any
other way to call api to Verge?

**Comment by justinvforvendetta** [comment]
can you show me the code you are using with verge-nodejs?

**Comment by mutobui** [comment]
I tried with node-verge:

var verge = require('node-verge')()

verge.auth('vergerpcusername',
'85CpSuCNvDcYsdQU8w621mkQqJAimSQwCSJL5dPT9wQX')
verge.set("port", 21102)

verge.getDifficulty(function() {
console.log(arguments);
})

got: ' Error: socket hang up'

Also verge-node-typescript:

const { Client } = require('verge-node-typescript')
const clientSettings = require('./credentials.json')
const client = new Client(clientSettings)

client.getInfo().then(value => {
console.log(value)
}).catch(err => {
console.log(err)
})

credentials.json:
{
"rpcuser":"vergerpcusername",
"rpcpassword":"85CpSuCNvDcYsdQU8w621mkQqJAimSQwCSJL5dPT9wQX",
"rpcport":20102,
"port":21102,
"daemon":1,
"https": true,
"algo":"groestl"
}

got:  " Error: Client network socket disconnected before secure TLS
connection was established"

**Comment by justinvforvendetta** [comment]
```
var verge = require('node-verge')()

verge.auth('vergerpcusername',
'85CpSuCNvDcYsdQU8w621mkQqJAimSQwCSJL5dPT9wQX')
verge.set("port", 21102)
```

port 21102 is p2p port, not rpc

**Comment by justinvforvendetta** [comment]
closing this, but feel free to re open it on the verge nodejs repo if you need to.
