### ISSUE TITLE
Hash_genesis_block, genesis_block, bech32 

### ISSUE THREAD

**Issue by artem03** [vergecurrency/verge#1046]
I'm having trouble creating a network (OutOfRangeException for genesis_block) using the NBitcoin library, I'd like to know if my genesis_block, hash_genesis_block and bech32 are correct.
This is my file coinparams.json :
 "XVG": {
    "meta": {
      "symbol": "XVG",
      "name": "Verge",
      "supply": {
        "max": "16555000000"
      },
      "web": {
        "websites": [
          "http:\/\/vergecurrency.com\/"
        ],
        "announcement": "https:\/\/bitcointalk.org\/index.php?topic=1365894.0",
        "source_code": "https:\/\/github.com\/vergecurrency\/VERGE",
        "explorers": [
          "https:\/\/verge-blockchain.info\/"
        ],
        "coinmarketcap": "https:\/\/coinmarketcap.com\/currencies\/verge\/",
        "message_board": [],
        "chat": [
          "https:\/\/t.me\/VERGExvg",
          "https:\/\/discord.gg\/vergecurrency"
        ]
      },
      "original_codebase": "bitcoin"
    },
    "main": {
      "symbol": "XVG",
      "name": "Verge - Mainnet",
      "testnet": false,
      "port": 21102,
      "port_rpc": 20102,
      "protocol": {
        "magic": "0xf7a77eff"
      },
      "seeds_dns": [],
      "prefixes": {
        "public": 30,
        "scripthash": 33,
        "private": 158,
        "bech32": "vg",
        "bip44": 77,
        "extended": {
          "xpub": {
            "public": "0x0488b21e",
            "private": "0x0488ade4",
            "undefined_used_btc": true
          },
          "ypub": {
            "public": "0x049d7cb2",
            "private": "0x049d7878",
            "undefined_used_btc": true
          },
          "zpub": {
            "public": "0x04b24746",
            "private": "0x04b2430c",
            "undefined_used_btc": true
          },
          "Ypub": {
            "public": "0x0295b43f",
            "private": "0x0295b005",
            "undefined_used_btc": true
          },
          "Zpub": {
            "public": "0x02aa7ed3",
            "private": "0x02aa7a99",
            "undefined_used_btc": true
          }
        }
      },
      "hash_genesis_block": "00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278",
      "genesis_block": "01000000000000000000000000000000000000000000000000000000000000000000000000fd75e6dce5e8c50ed0df2b0b73c2c37c8329d837ec3aec1e7151915d27831c74d23654ffff0f1ea77a1600010100000074d23654010000000000000000000000000000000000000000000000000000000000000000ffffffff1b04ffff001d0104134e616d653a20446f6765636f696e204461726bffffffff010000000000000000000000000000",
      "message_magic": "\u0016VERGE Signed Message:\n",
      "decimals": 6
    }

**Comment by justinvforvendetta** [comment]
@artem03 my first guess would be that it isnt accounting for nTime, since verge was originally built on a PoS codebase

**Comment by justinvforvendetta** [comment]
not set lock time. transactions require nTime in them, like peercoin does.

**Comment by artem03** [comment]
NBitcoin library doesn't have nTime(

**Comment by justinvforvendetta** [comment]
you can add it to the transaction. block headers have ntime as well.

**Comment by artem03** [comment]
How is this possible to do in c#?

**Comment by justinvforvendetta** [comment]
@artem03 when creating the tx, just add the current time to it as an input.

**Comment by artem03** [comment]
Maybe it's a stupid question, but how can I add the current time to the inputs when creating a tx if the set of inputs in the NBitcoin library is
public class TxIn : IBitcoinSerializable
	{
		protected OutPoint prevout;
		protected Script scriptSig;
		protected uint nSequence;

		public TxIn();
		public TxIn(Script scriptSig);
		public TxIn(OutPoint prevout);
		public TxIn(OutPoint prevout, Script scriptSig);

		public Script ScriptSig { get; set; }
		public OutPoint PrevOut { get; set; }
		public Sequence Sequence { get; set; }
		public bool IsFinal { get; }
		//
		// Summary:
		//     The witness script (Witness script is not serialized and deserialized at the
		//     TxIn level, but at the Transaction level)
		public WitScript WitScript { get; set; }

		public static TxIn CreateCoinbase(int height);
		public virtual TxIn Clone();
		public virtual ConsensusFactory GetConsensusFactory();
		//
		// Summary:
		//     Try to get the expected scriptPubKey of this TxIn based on its scriptSig and
		//     witScript.
		//
		// Returns:
		//     Null if could not infer the scriptPubKey, else, the expected scriptPubKey
		public IDestination GetSigner();
		public bool IsFrom(PubKey pubKey);
		public virtual void ReadWrite(BitcoinStream stream);
	}

**Comment by justinvforvendetta** [comment]
you said the error was "OutOfRangeException for genesis_block" which means that the time was not correct. can you post the transaction you are trying to create so we can decode it and take a look at what is right/wrong?

**Comment by artem03** [comment]
@justinvforvendetta Yes
"01000000017e2eca0dd8895cd76a72d9a791cf7726af52597519d6eafa0616bb9bb3a7bcec010000006a47304402205693c1e1e0ca52d0bedfc1141c625ecfe60b608fe5bed365521d004d44d51a9802206038ac1e487800445dfdd6a0060e923d7f910dbe5b50b864edc7f0aaa4eb4f6e01210335853e8aad83c40a7e16768769176e09ef83abe000f3d97170fd597ecd5b29dcffffffff02400d0300000000001976a914b0b19e61f007659cd6c3b889dc400ad1e0ffd57388ac400d0300000000001976a914eb1a7947ba7b247b051e1ede0c09b41d25ae0ba388ac00000000"

**Comment by justinvforvendetta** [comment]
@artem03 

{
  "asm": "0 0 0 126 ca0dd8895cd76a72d9a791cf7726af52597519d6eafa0616bb9bb3a7bcec010000006a47304402205693c1e1e0ca 2 OP_UNKNOWN OP_UNKNOWN OP_UNKNOWN OP_UNKNOWN 1c625ecfe60b608fe5bed365521d004d44d51a98 24608 ac1e487800445dfdd6a0060e923d7f910dbe5b50b864edc7f0aaa4eb4f6e01210335853e8aad83c40a7e16768769176e09ef83abe000f3d9 OP_2ROT OP_2OVER OP_UNKNOWN 9 OP_CAT OP_UNKNOWN 11 dcffffffff02400d0300000000001976a914b0b19e61f007659cd6c3b889dc400ad1e0ffd57388ac40 0300000000001976a914eb1a79 [error]",
  "type": "nonstandard",
  "p2sh": "EPnW273pH66PZS1QAFGM9JmkikU5sDAv7Y",
  "segwit": {
    "asm": "0 351173eb40cca75207b9fe98c2bf63334747b463a91cfcbc9374cabd11c37784",
    "hex": "0020351173eb40cca75207b9fe98c2bf63334747b463a91cfcbc9374cabd11c37784",
    "reqSigs": 1,
    "type": "witness_v0_scripthash",
    "addresses": [
      "vg1qx5gh866qejn4ypael6vv90mrxdr50drr4yw0e0ynwn9t6ywrw7zqwq0tj8"
    ],
    "p2sh-segwit": "EdhyuevrUz4j9B1hrH1CyCXhu98KBaD4SC"
  }
}

**Comment by justinvforvendetta** [comment]
if you use the https://vergeexplorer.com/ site, and click any tx, and then "JSON" it will show the decoded tx =]

**Comment by justinvforvendetta** [comment]
btw we do not use segwit
