### ISSUE TITLE
Windows Defender reports that "verge-6.0.2-win64-setup-unsigned.exe" contains Win32/Ymacco.AAA0

### ISSUE THREAD

**Issue by tonyping** [vergecurrency/verge#1048]
# Issue Template

## Context

Windows Defender reports that "verge-6.0.2-win64-setup-unsigned.exe" contains Win32/Ymacco.AAA0. Classified as category: Potentially Unwanted Software. Defender prompted the user to either quarantine or ignore threat. It was however, not automatically quarantined by Defender, as it classified it as a Low Threat.

Providing context helps us come up with a solution that is most useful in the real world -->

## Prerequisites

* [ ] Are you running the latest version?
Yes, Windows 10 Defender has been updated with the latest definitions.

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Possible Solution
Manually file a report to the Microsoft Security team as False positive. 

https://www.microsoft.com/en-us/wdsi/filesubmission

However, the file is detected as malicious by so many other engines (28!), that this issue is not in the least limited to Microsoft. Triggering detection from such a wide variety of engines is severe.

Virustotal report:
https://www.virustotal.com/gui/file/a0b898eecd04751c4efe2c96ba49787c39178fc8e8bbe990f14ac7d284a41ac0/detection

## Steps to Reproduce (for bugs)

1. Download installer file verge-6.0.2-win64-setup-unsigned.exe. 
2. Defender shows user action prompt.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
@tonyping unfortunately, this is pretty normal for windows. none of the releases here on github contain any malware.
