### ISSUE TITLE
Electrum-XVG not opening with seed or wallet backup file

### ISSUE THREAD

**Issue by JVR553** [vergecurrency/verge#1049]
Hi, i am looking for some expert help, i have been all over the net for the last 2 weeks trying to figure this out.
So, in 2018 i was using electrum-xvg 2.4.1 to hold my 36k verge coins, all was good, made many transfers and so on.
Recently, Nov 2020, i attempted to fire backup my electrum 2.4.1 wallet, i then realized that i had wiped my drive and had not saved the %appdata% folders with my wallet info. So i got some recovery software and was able to recover then folders that held my wallet file. I started up a new electrum 2.4.1 wallet, then i replaced the created wallet file with my old backup. It says that it cannot read the file???? I then proceeded to use my 8 word seed phrase, which seemed to work after i put in my correct password, however, my balance shows up as zero. I have been looking through every available post out there with no luck. I appreciate any and all help.

**Comment by justinvforvendetta** [comment]
very simple. make a backup of the wallet recovery stuff you have. then, delete it all. then open electrum. itll ask if you want to make a new wallet or restore. choose 'restore' and put in your words. as long as you see the bottom right corner have a green light, it works. (also use the new electrum, 2.4x is old)
