### ISSUE TITLE
Leviosa wallet 

### ISSUE THREAD

**Issue by rakezh08** [vergecurrency/verge#1050]
I am trying to import my private key into the leviosa wallet. It shows the following error below. I have recovered my coins using the same private key into the electrum wallet successfully in the past.

￼
Error: Error parsing JSON:clemins

**Comment by justinvforvendetta** [comment]
@rakezh08 importing it should look something like this. lets say your private key is "123456789"

`importprivkey 123456789`

**Comment by rakezh08** [comment]
I tried the same way as you have mentioned but i am still getting the same error. 
![Untitled](https://user-images.githubusercontent.com/76707639/103249278-0e2eb080-4934-11eb-96b7-9c091c068bf0.jpg)

**Comment by justinvforvendetta** [comment]
there should be no (...), only a private key. also, you downloaded this wallet from where? i have never seen an A-A+ in the debug console before.  "clemins" is not even a word in our source code as far as i can tell.

**Comment by jrsikors** [comment]
Sounds like they are trying to import the seed phrase and not the private key

-Jeff

**Comment by rakezh08** [comment]
I downloaded it from the official verge website. I think its the seed phrase!! How do I do it? I appreciate you all for your quick responses...

**Comment by rakezh08** [comment]
if possible could you provide me a link for a reliable wallet. I am using windows 10 pro 64bit.

**Comment by justinvforvendetta** [comment]
ah yeah, you can not import the words, you would need to get the private key of each address that has coins and import them seperately

**Comment by justinvforvendetta** [comment]
great observation @jrsikors

**Comment by jrsikors** [comment]
You need to start with the Electrum wallet, put in your seed phrase to restore your wallet.

Then you should be able to export your private keys of your addresses from Electrum, and import them into the QT by private key.

You don’t need to import them all, just the ones that actually have coins on them.  There’s no harm in importing them all, it will just take time and not be beneficial!

-Jeff

**Comment by rakezh08** [comment]
I have my electrum wallet 2.4.1. which is working fine. However, I am not able to connect or sync even after changing the servers. Again, I appreciate you all for taking your precious time for helping me out to get back my coins. Are there any servers that are still active?

**Comment by rakezh08** [comment]
well, I found my priv keys and i am trying to import into leviosa wallet. still have the same problem. I checked on the verge explorer, it shows the stored xvg.
![xvg](https://user-images.githubusercontent.com/76707639/103303850-a7a9a100-49cc-11eb-9ba8-81871cea4512.jpg)

**Comment by jrsikors** [comment]
The private key should be like a 53 character string made up of numbers and capital/lowercase letters

If it starts with a D and is 34 characters, that’s probably your public key.

-Jeff

**Comment by justinvforvendetta** [comment]
most likely, your private key starts with a "Q" so it would look like this:
`importprivkey Qkj23h4gkj23h4k23j4h2k3j4hbn23kjh423kj`

**Comment by rakezh08** [comment]
Now i figured out yea i do have public keys and a seed phrase! but not the private key. Could you please tell me how do i connect to a server in electrum 2.4.1. I tried the servers found on the internet but none of them are working for me! Thank you All.

**Comment by justinvforvendetta** [comment]
@rakezh08 you should probably start by downloading the new electrum found here: https://github.com/vergecurrency/electrum/releases/download/v4.0.0-beta3/electrum-v4.0.0-beta3-6-g8717e963.exe

and restore it using your seed phrase. also, you will need to be running tor, so that you can connect.

**Comment by jrsikors** [comment]
Do you need to be connected to do the “export private keys” function?  Been a long time since I’ve used Electrum.

But if their wallet is always loaded, it should be as easy as doing the “export private keys” on one of the menus right?

-Jeff

**Comment by justinvforvendetta** [comment]
i dont believe they need to be connected to obtain private keys, because the addresses are generated before a connection ever takes place.

**Comment by rakezh08** [comment]
Thank you all for the help. I am connected and got my xvg.
