### ISSUE TITLE
Restore Electrum-XVG wallet into VergeQT

### ISSUE THREAD

**Issue by asalerni** [vergecurrency/verge#1052]
I have a ElectrumXVG wallet (2.4) with some xvg that I didn't use for a long time. At moment connection doesn't work, always red circle. I installed last version of VergeQT but How I can restore my wallet there? I have a 9 words seed but I'm not able to restore neither in ios app.

Mac OSX

**Comment by justinvforvendetta** [comment]
try using the latest electrum wallet: https://github.com/vergecurrency/electrum
