### ISSUE TITLE
0 connections verge wallet v6.0.2.0

### ISSUE THREAD

**Issue by VD1987** [vergecurrency/verge#1053]
Hi There, 

I just downloaded de QT wallet v6.0.2 and also installed the blockchain data, but my wallet get stuck on 99.72% with 0 connections. Does somebody know what to do? Want to transfer my verge to my exchange.

Used v4.0 before. This one i deinstalled and i removed the old blockchain data. Afterwards i installed the newer version (6.0.2) with the new blockchain data. What have i done wrong. Hope somebody can help me with this issue.

**Comment by justinvforvendetta** [comment]
when you installed the blockchain data, did you remove the peers.dat as well, after removing the old blockchain data?

**Comment by VD1987** [comment]
I deleted the whole old VERGE folder in appdata and installed the new version (version 6). Afterwards i installed the blockchain data and paste it in the new VERGE folder in appdata. So i thought it should work now, buy it stay stuck at 99,72%

**Comment by justinvforvendetta** [comment]
ok try leaving it open for an hour or two. if it synced that far, it should finish by itself. if you want, you can get on our discord, and ask for a peers.dat file in the #wallet-help channel. or close/shut down the wallet, delete your peers.dat file, and start/open the wallet again and wait.

**Comment by VD1987** [comment]
I believe that my first comment wasn't quite clearly defined. After installing the new wallet and the new blockchain data, I opened my wallet and it was immediately at 99.72%. my wallet never synced, but started directly at this percentage and did nothing else. I left it open all night and it's still the same, looking for connecties, but can't find any. I will try your last option with deleting the peers.dat file. If this doesn't work i would like to join the discord group and ask for a peers.dat file. Thanks for your help so far!

**Comment by Husso94** [comment]
I am in the exact same scenario but I'm stuck at 99.69%.

I followed this guide: https://verge-blockchain.com/howto/

Everything went well, took about 1 hour to load the initial block index upon first launch but after launching the wallet it was instantly on 99.69% but states '0 active connections to verge network' and it will not complete the sync.

Left for several hours, made a couple restarts but no avail. It does not want to connect to the verge network.

I have attached the debug for reference. 

Any guidance would be greatly appreciated.

Thank you :)

[debug.log](https://github.com/vergecurrency/verge/files/5791314/debug.log)

**Comment by Husso94** [comment]
Update: I've joined the discord channel and used the latest peers.dat file (V-47). Still will not connect to the verge network :(

**Comment by justinvforvendetta** [comment]
ok shut the wallet down. delete the debug.log, start the wallet back up. let it sit for 30 minutes. then, if it is not connected, please attach the new debug.log

**Comment by Husso94** [comment]
Thank you, I will try that right now

**Comment by jrsikors** [comment]
Do you have any other wallets or applications that also use Tor?  Or in a country where Tor is blocked?

I had issues sometimes finding the 1st peer and needed to go to the console and do the “peer add” function (can’t remember the exact syntax).  But someone in discord can probably help giving you the first peer details

-Jeff

**Comment by Husso94** [comment]
I live in the UK so Tor is not blocked I believe. 

I do have 7 other wallets but I'm not sure if they use Tor, is there a way I can find out?

**Comment by VD1987** [comment]
so i installed everything again, but still no connection. How do i join the discord group. I want to try the new peers.dat file.

**Comment by Husso94** [comment]
[peers.zip](https://github.com/vergecurrency/verge/files/5791475/peers.zip)

**Comment by Husso94** [comment]
if you want to join the discord:

https://discord.com/invite/vergecurrency

**Comment by VD1987** [comment]
Thanks! The ZIP file you sended is the latest peer.dat file?

**Comment by Husso94** [comment]
yep, this was posted on Friday 8th January 2021 (yesterday). I hope it fixes your issue!

**Comment by VD1987** [comment]
Thanks! Will overwrite the old one and start the wallet again. if it not works, i will do what @sunerok says (deleting the debug.log and start the wallet again and post the new log here in github.

**Comment by VD1987** [comment]
> ok shut the wallet down. delete the debug.log, start the wallet back up. let it sit for 30 minutes. then, if it is not connected, please attach the new debug.log

Hi @justinvforvendetta hereby my debug.log after restarting the wallet again. 
[debug.log](https://github.com/vergecurrency/verge/files/5791547/debug.log)

**Comment by Desolatorbtc** [comment]
Alternative solution is to place Verge.config file with "dynamic-network=1"in %APPDATA%/Verge. It will enable the clearnet connections. It is not suggested since you are not on tor network anymore but it will basically show you if your wallet has trouble connecting the tor nodes.


[Verge.zip](https://github.com/vergecurrency/verge/files/5791822/Verge.zip)

**Comment by Husso94** [comment]
Thanks Desol, I tried that too (Someone in the discord chat suggested it) and still no luck 👎

**Comment by Husso94** [comment]
If it helps, I've got my Ravencoin (RVN) wallet currently syncing (it has been for atleast 5 hours now). And there core is virtually the same as Verge Core with a tor network. So I think the issue lies somewhere in my setup. Somewhere there is something missing i think

**Comment by Husso94** [comment]
![image](https://user-images.githubusercontent.com/77201838/104109088-27cfe080-52c2-11eb-9871-edf1e4aad935.png)

Does this look correct?

**Comment by jrsikors** [comment]
Trying going to the debug console and putting these in:

addnode “51.254.44.206” add
addnode “203.198.146.232” add

You should get a “null” after each.  Wait a few mins and see if you start getting connections

-Jeff

**Comment by jrsikors** [comment]
I’m not sure if you can have 2 wallets with 2 tors running at same time.  You may want to try closing both.. then opening verge

-Jeff

**Comment by Husso94** [comment]
Haha someone in the discord literally just said the same thing! I've got about an hour left of syncing then I will be able to close the wallet. Will update soon!

Thanks for your help

**Comment by VD1987** [comment]
> Alternative solution is to place Verge.config file with "dynamic-network=1"in %APPDATA%/Verge. It will enable the clearnet connections. It is not suggested since you are not on tor network anymore but it will basically show you if your wallet has trouble connecting the tor nodes.
> 
> [Verge.zip](https://github.com/vergecurrency/verge/files/5791822/Verge.zip)

@Desolatorbtc  Is this a possible solution for me or is this reaction meant for Husso94?

**Comment by VD1987** [comment]
> Trying going to the debug console and putting these in: addnode “51.254.44.206” add addnode “203.198.146.232” add You should get a “null” after each. Wait a few mins and see if you start getting connections
> […](#)
> -Jeff
> On Jan 9, 2021, at 3:32 PM, Husso94 ***@***.***> wrote: ﻿ Does this look correct? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

I don't know where i can find the debug console. Is that the debug.log document?

**Comment by VD1987** [comment]
![Naamloos](https://user-images.githubusercontent.com/77172916/104109824-f828d480-52d1-11eb-9922-8945ca035a42.png)

This is how the map looks like at my computer, Is this correct or am i missing documents?

**Comment by jrsikors** [comment]
Help -> debug -> console 

Or something around that

-Jeff

**Comment by Husso94** [comment]
Ok so bad news. Other wallet finished syncing finally, restarted computer and opened verge wallet.. Still not connecting. Completely disabled firewall, still nothing. I even removed the whole VERGE folder in %APPDATA% with my firewall off too. Then tried it with the Verge.conf file to connect to clearnet nodes. Still no avail. Going to call it a day and get some rest. Been at this for over 12 hours now lol

**Comment by Husso94** [comment]
> Trying going to the debug console and putting these in: addnode “51.254.44.206” add addnode “203.198.146.232” add You should get a “null” after each. Wait a few mins and see if you start getting connections
> […](#)
> -Jeff
> On Jan 9, 2021, at 3:32 PM, Husso94 ***@***.***> wrote: ﻿ Does this look correct? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

Tried this also, did receive a null on each command. Waited 15 minutes and still no connection

**Comment by VD1987** [comment]
I did the same stuff. Adding the config file to my VERGE folder in Appdata and also added the nodes in the debug consule, but nothing helped. Thanks for the tips so far! Much appreciate the help. 

Can somebody make something up out of my Debug.log? 

Seems the wallet tries to make connections, but it failed every time, These are the messages i see in my debug.log:

- 2021-01-10T00:04:57Z Potential stale tip detected, will try using extra outbound peer (last tip update: 6796 seconds ago)
- 2021-01-10T00:09:27Z Socks5() connect to sdgqgkaf42fupu46p4mbah4rdmkadi5rfut4dmsebo277ljd245e7mad.onion:21102 failed: InterruptibleRecv() timeout or other failure

[debug.log](https://github.com/vergecurrency/verge/files/5792407/debug.log)

**Comment by VD1987** [comment]
You can ignore my previous message. Somehow a miracle happened i guess and i've 16 running connections now. Mayve adding the nodes and restarting the wallet and leave it for a while worked after all. Who knows! Maybe this works for you also @Husso94 
Thanks everybody for your help and patience. Much appreciate!

**Comment by Husso94** [comment]
Im all out of ideas, tried everything now. Removed everything and put my wallet.dat on USB. Re-downloaded all the files in case of corruption, added the most up to date blockchain bootstrap and V47 Peers.dat. Added Nodes also but still nothing. Completely disabled firewall for several hours, done the verge.conf to eliminate the tor connection issue.. It just doesn't want to connect to the network

**Comment by Desolatorbtc** [comment]
@Husso94 did you enter following nodes to your console after placing verge.conf file to the verge directory?

addnode “51.254.44.206” add
addnode “203.198.146.232” add

Because the nodes above are clearnet nodes. Wont connect to them if you dont have verge.conf file in the directory

**Comment by Husso94** [comment]
> @Husso94 did you enter following nodes to your console after placing verge.conf file to the verge directory?
> 
> addnode “51.254.44.206” add
> addnode “203.198.146.232” add
> 
> Because the nodes above are clearnet nodes. Wont connect to them if you dont have verge.conf file in the directory

Yep, added the config file before doing the nodes and just in case, I done it without the config file too

**Comment by Husso94** [comment]
The most puzzling thing is, I just synced my Ravencoin wallet yesterday (took at least 9 hours in total) which uses tor networks also. So I know I can definitely use tor networks

**Comment by Omerta666** [comment]
I have the same problem. Downloaded the latest blockchain and it says I am 2 weeks behind and 0 active connections to Verge Network.

**Comment by jrsikors** [comment]
if you aren't in a country that blocks tor, and you don't have another wallet running that uses tor, then it might be that some people have issues establishing the first peer connection..  go to help > debug window -> console and run these 3 commands separately to see if it gets you going:
addnode "4omta4xmldql2xqv5ji2rjplejqrd56yst6jlsork43ayb3rbhkpywyd.onion" add
addnode "tiltn732y4vziah2ycie2wwm5xgfpspmc26atln2abtybyhrptld44qd.onion" add
addnode "763co2copdnav2ik2jlq33wzj2rogt4wfexjvukx5tg3tiepm2ahbrid.onion" add

**Comment by Omerta666** [comment]
I followed all recommendations within this thread but nothing happens... Not really satisfying...

**Comment by justinvforvendetta** [comment]
@Omerta666 how about telling us what is going on? maybe paste debug.log or something? no one here is psychic buddy.

**Comment by Omerta666** [comment]
[debug.log](https://github.com/vergecurrency/verge/files/5894618/debug.log)
Is that the correct one?

**Comment by Omerta666** [comment]
Hi all, is there any update on the issue?

**Comment by justinvforvendetta** [comment]
@Omerta666 are you in a country that blocks tor? close the wallet down, and re run verge-qt.exe with --dynamic-network after. (like verge-qt --dynamic-network)

this issue is specific to you, as all of my nodes are showing a ton of connections, the blockchain explorers all show peers and exchanges that provide that information seem to have plenty of peers as well.

**Comment by Omerta666** [comment]
> 
> 
> @Omerta666 are you in a country that blocks tor? close the wallet down, and re run verge-qt.exe with --dynamic-network after. (like verge-qt --dynamic-network)
> 
> this issue is specific to you, as all of my nodes are showing a ton of connections, the blockchain explorers all show peers and exchanges that provide that information seem to have plenty of peers as well.

I am in Germany, therefore, I think Tor is not blocked. Starting the wallet with --dynamic-network after does not work either.
