### ISSUE TITLE
How to recover my Verge from Electrum wallet

### ISSUE THREAD

**Issue by chineseballer06** [vergecurrency/verge#1054]
Hi,

I have had my Verge stored on the electrum mac wallet, but now it doesn't open anymore, is there a way I can recover my verge or transfer them to the QT wallet?

Any help is greatly appreciated!

**Comment by justinvforvendetta** [comment]
download the new electrum and restore wallet using your seedphrase from the original wallet. (should be 12 words or something)

**Comment by chineseballer06** [comment]
I'm not seeing an updated Electrum wallet on https://vergecurrency.com

Is there a mac package that I can download?

**Comment by justinvforvendetta** [comment]
try to get this to work (with tor running of course, the non-tor version hasnt been supported for ~3 years now)

if that doesnt work, ill trigger a macos build of the newest one.

**Comment by chineseballer06** [comment]
<img width="475" alt="Screen Shot 2021-02-13 at 3 33 58 PM" src="https://user-images.githubusercontent.com/35030160/107863348-fc846800-6e10-11eb-9419-c44806ba971c.png">
I keep getting this error when trying to use the Mac Tor electrum wallet. I tried deleting my old Verge file (I have my wallet.dat file and keys saved on an external drive) but I am still getting this error.

**Comment by justinvforvendetta** [comment]
how are you opening it? by just double clicking, or dragging into applications?

**Comment by chineseballer06** [comment]
I've tried both ways

**Comment by justinvforvendetta** [comment]
and you already have tor running? try open console

**Comment by chineseballer06** [comment]
No that's what happens when I download the mac version and then try to open the app.

**Comment by justinvforvendetta** [comment]
but you already have tor running before the wallet starts? have you used this app before?

**Comment by chineseballer06** [comment]
No I guess I don't have tor running. Where do I go to get that? I'm trying to open the tor wallet. I've never used the tor wallet before.

**Comment by justinvforvendetta** [comment]
torproject.org

**Comment by chineseballer06** [comment]
I'm still getting the same error as I pasted above after downloading the Tor browser and downloading the tor electrum wallet from there.

**Comment by jrsikors** [comment]
Instead of spending time trying to diagnose why Electrum isn’t working on your Mac, another potential option is to go use another computer.  If you don’t have one, borrow a friend or family members.

When you said you have your keys, do you have your private keys?  If you have private key, you can try the QT wallet and just import the private keys.

Also you said you had wallet.dat.. that is for QT wallet as well.

For Electrum you will likely need your seed phrase , or the wallet files that Electrum uses, can’t remember it right now, are they .key ?

-Jeff

**Comment by jrsikors** [comment]
Another epiphany I had as soon as I hit reply, is that I wonder if the 'data directory' for his old Electrum is making his new Electrum crash right away ?

Could find the old 'data directory' on your Mac and (MAKE A COPY first, and dont even delete) just rename the folder

**Comment by chineseballer06** [comment]
Thanks for those tips, I will try the QT wallet (Verge Leviosa), although last time I didn't see any option to restore or import an existing wallet/private keys. If that doesn't work I'll try using a windows computer. Thanks for the help, been a while since I've used these wallets so still trying to get caught up.

**Comment by justinvforvendetta** [comment]
i dont believe your electrum wallet needs to connect to a server to retrieve your private keys, so once you get them and sync a qt wallet you can import then in the console

**Comment by chineseballer06** [comment]
My Electrum wallet won't even start the application. The only thing I have saved is the seed phrase and the wallet.dat file. Is that the file that I would need to import them to the QT wallet once it syncs?

**Comment by jrsikors** [comment]
if your wallet.dat contains the same addresses as your seed phrase, to be honest, that would be kind of weird... unless you some exporting/importing of private keys between the QT Wallet and the Electrum wallet.

With the QT Wallet.. you didn't necessarily import your wallet.dat.  You basically close down the QT Wallet, find the %DATADIR% , default is like C:\Users\You\AppData\Local .. or maybe Local .. then Verge .  You would replace the existing wallet.dat with your backup of wallet.dat.  Before you do that, i would rename the wallet.dat in the %DATADIR% to like walletold.dat , and then copy your backed up wallet.dat to that directory.

When your QT launches, it looks for the existence of wallet.dat there.  So it will use the wallet.dat that you have backed up externally

**Comment by jrsikors** [comment]
I believe your "datadir" for Macs is going to be under "~/Library/Application Support" somewhere... in "Electrum-xvg" or something like that.  I couldn't find any article on electrum for macs.
https://verge.zendesk.com/hc/en-us/categories/360000975931-Technical-Assistance

But your wallet files for electrum don't look like they are dat files.  it looks like it's just named default "default_wallet" or "wallet_1" or "wallet_2" with no extension

**Comment by chineseballer06** [comment]
Okay I was able to use my seed phrase to restore my electrum wallet on windows. It's not connecting but I see that I can export my private keys. Now on my mac I have the Leviosa qt wallet installed and synced but I can't see how to import them.

**Comment by chineseballer06** [comment]
Or is there a way to connect to the electrum wallet now that I can run it? The default servers I see are:
e1.verge-electrum.com
e2.verge-electrum.com
e3.1verge-electrum.com
electrum-verge.xyz
electrum-xvg.party
electrum-xvg.stream

**Comment by jrsikors** [comment]
on your QT wallet, if you go to Help -> Debug -> Console.  Type the command:
importprivkey YoURPrIVaTeKeYHere

if you just type importprivkey it will tell you the parameters

**Comment by jrsikors** [comment]
after you import your private keys and see your coins, close down the QT wallet and take a good backup of your wallet.dat file.  This is your wallet backup now.  You can keep the electrum ones around as well, no reason not to.

**Comment by justinvforvendetta** [comment]
ah that is the old clearnet electrum, you wont be able to get it to connect, unless u switch servers and run it on a proxy to tor. that wallet hasnt been supported in years.  but yes, you can import the privkeys like jeff has stated
