### ISSUE TITLE
unconfirmed transaction

### ISSUE THREAD

**Issue by Cr1pt0x** [vergecurrency/verge#1055]
I have sent all my coins from the MacOS Tor wallet to iOS Wallet, it's been more than a week and both wallets have zero confirmations.

Status: 0/unconfirmed
Date: 1/31/21 19:29
To: Verge Coins D6LYpEYbRe7LHnmDqiDzWq4kDvaZYL5hK6
Debit: -28,000.00 XVG
Transaction fee: -0.10 XVG
Net amount: -28,000.10 XVG
Transaction ID: da28e9b45e862fb1de2ec4d4ab6853ae4635060b501281b497fbeaa77515f3d4

What can I do??

**Comment by justinvforvendetta** [comment]
@Cr1pt0x that transaction does not exist: https://vergeexplorer.com/tx/da28e9b45e862fb1de2ec4d4ab6853ae4635060b501281b497fbeaa77515f3d4

how many connections does your MacOS Tor wallet have?

**Comment by Cr1pt0x** [comment]
16 active connections with verge network right now.

**Comment by Cr1pt0x** [comment]
<img width="976" alt="Screen Shot 2021-02-10 at 19 08 25" src="https://user-images.githubusercontent.com/78835332/107589386-d920a980-6bd3-11eb-9649-4cdfb73a116b.png">

**Comment by justinvforvendetta** [comment]
dude thats the 2017 wallet lol you havent updated it in 3+ years? try updating and then come back if you still have a problem.

**Comment by Cr1pt0x** [comment]
My bad, I bought the coins and kept it there since 2017. I will update it, just hope I can get my coins back. 

Thanks for your help.

**Comment by justinvforvendetta** [comment]
@Cr1pt0x your coins will be there when you sync a new wallet.

**Comment by Cr1pt0x** [comment]
Hi, 

I think I was able to update the wallet but I still can’t see the coins and transactions. Is there anything else I need to do?

I appreciate your help.

**Comment by justinvforvendetta** [comment]
@Cr1pt0x and you are certain the wallet is synced 100%?

**Comment by Cr1pt0x** [comment]
It says blocks of transaction history is up to date.

**Comment by Cr1pt0x** [comment]
See below a screen shot

**Comment by jrsikors** [comment]
Is the address with your coins one of receiving addresses?  Did you create a new wallet somehow?

-Jeff

**Comment by Cr1pt0x** [comment]
I will try to explain what I did.

All my coins where bought through Binance and most of then were transferred to on my Mac Os QT wallet in 2018. On 1/31/21, I transferred 28k coins to my iOs wallet (using an address from the iOs wallet) and left some there but did not realized I was using an old version and not synced. Then I transferred some coins that I still had left on Binance using the same address. Now I updated the wallet but I'm still not able to see the 28k coins and the balance is different from what I should have.

I appreciate your help.

Thanks.

**Comment by jrsikors** [comment]
What matters is:
1) What addresses are the coins at?  You can find out and follow transactions at https://verge-blockchain.info/   
2) Are those addresses in your wallet ? (as receiving addresses)

If you updated the wallet but you aren't seeing the 28k coins.. it's either:
 A)  The coins are in a different address than you think, and those addresses aren't in your wallet
 B)  You really aren't synced .. which might be resolved by running the verge-qt.exe with a -rescan to rescan all transactions

**Comment by justinvforvendetta** [comment]
also binance provides a transaction id for your withdraw. double check it on [](https://vergeexplorer.com/) or the one in the comment above.

**Comment by Cr1pt0x** [comment]
Hi,

I didn’t have any issue sending coins from Binance to my iOs wallet. The issue is from the desktop wallet to iOS wallet. I rescanned all transactions again but is still the same. I think i’m missing blocks data because from the old version QT wallet screen shot I see 8 transactions including the one unconfirmed transaction while in the updated version is only showing 5 transactions with a balance of 49.90 coins. Old version balance was 28,353.354 before sending out 28k to iOS wallet. 

Thanks.

**Comment by Cr1pt0x** [comment]
What would happen if i click the option "abandon transaction”? would that help in any way?

Thanks

**Comment by justinvforvendetta** [comment]
yes and you are using the newest wallet right? not the old one still? definitely abandon the tx, let the new wallet sync and then it should be fine to send from.

**Comment by Cr1pt0x** [comment]
Yes, I’m using the updated one. Let me try that then. 

Thanks,

**Comment by Cr1pt0x** [comment]
Awesome!!! Did work. 

Thank you so much.

**Comment by justinvforvendetta** [comment]
@Cr1pt0x i thought you already abandoned it. get the desktop wallet now (newest is here: https://github.com/vergecurrency/verge/releases/tag/v6.0.3)
