### ISSUE TITLE
Missing transaction status 0/unconfirmed - starting to panic

### ISSUE THREAD

**Issue by amaru96** [vergecurrency/verge#1056]
Hi guys, yesterday I transferred my coins to Bittrex but they have not arrived and the transaction status shows 0/unconfirmed.

I did 2 test transactions first and they both went through so I then tried to transfer the remainder of my wallet but it hasn't appeared and I'm starting to panic!

When I look at the VergeExplorer and enter the transaction ID it doesnt find it.

Here are the transaction details.
Status: 0/unconfirmed
Date: 12/02/2021 12:51
To: D6YehUf29igDduYWtHdkhuxw3kyvDcKcnE
Debit: -471,623.75691 XVG
Transaction fee: -0.10 XVG
Net amount: -471,623.85691 XVG
Transaction ID: 9151a8818b6c2aece97e61cf031125aff41bedffb434d24493bf0623a90bf5eb

I tried a rescan but didnt seem to do much.

I'm using a fairly old wallet but considering my test transfers went find I didn't think it would be an issue.
Client version = v4.0.1.0

Should I install the new version, will that help??

Not sure what to do now. Any help would be much appreciated.

**Comment by justinvforvendetta** [comment]
@amaru96  fairly old? that wallet is over 3 years old. there have been several wallet versions since then lol

what exchange did you send to? that's crazy that it worked at all, unless it was a scam exchange like yobit or something. close your wallet, delete all your blockchain data, and download the new one and start it. come back if you have any other problems, but you should be fine.

**Comment by amaru96** [comment]
Hi, I transferred it to Bittrex, not a scam exchange,

Should I move my wallet to a new version?

**Comment by jrsikors** [comment]
Your wallet file / directory won’t be changed and touched if you install the new client.  The new client will reference it.  But you should always have a copy of your wallet.dat file backed up just in case.

-Jeff

**Comment by justinvforvendetta** [comment]
if you have windows, check the %appdata% directory, for the VERGE folder, and delete everything but the wallet.dat file.  (wallet must be shut down when you do this.) download newest wallet and start it up, let it sync.

**Comment by amaru96** [comment]
I have the latest version on another machine, can I just copy over my wallet to that machine?

**Comment by justinvforvendetta** [comment]
@amaru96  you can shut that other machines new wallet down, rename the current wallet.dat file it was using, to wallet.backup, and copy the wallet.dat from the old wallet over to that new wallets data directory, and then start it back up. it'll take a few minutes as it rescans the blockchain data for associated tx's, but that would be ideal in this situation.

**Comment by amaru96** [comment]
OK thanks guys, will give it a shot...

**Comment by justinvforvendetta** [comment]
the most important thing to remember is never lose your wallet.dat files.

**Comment by amaru96** [comment]
OK, I've done that and can see the last transaction that has failed. Should I now "abandon transaction"?

**Comment by justinvforvendetta** [comment]
yep
