### ISSUE TITLE
Ban old peers

### ISSUE THREAD

**Issue by ocminer** [vergecurrency/verge#1060]
Even though you're continuing your ridiculous twitter campain I thought I'll give you a hand showing you how you can
disconnect old peers from your network:

Look at this file, you probably don't even know it exists:
https://github.com/vergecurrency/verge/blob/master/src/version.h#L23-L24

And look .. the comment in the code even says what it does.. So the magic number you insert there says
"hey, any node with a number SMALLER than this number won't I let connect".
So in order to "let the magic happen" - you'd simply bump your version to one currently active and ... voilà ... those old, nasty, bad nodes are now automagically thrown off the network. 

Did you imagine something like this was possible in 2021 ? :-)

And now go ahead and continue crying on twitter :)

**Comment by Desolatorbtc** [comment]
@ocminer please keep it professional. Show respect to get respect.

**Comment by ocminer** [comment]
@Desolatorbtc that's a good idea, who will start doing that ? :)

**Comment by Desolatorbtc** [comment]
@ocminer I think i am already doing it. Leave twitter on twitter. Lets focus only on solutions here.

**Comment by ocminer** [comment]
@Desolatorbtc Sure, the solution(s) are actually pretty easy, the code is widely available, it's just a matter of integrating it into your codebase.

**Comment by SwenVanZanten** [comment]
Next version will have a new protocol, it wasn't a wise idea to update the protocol in 6.0.3 for various reason.
