### ISSUE TITLE
Provide -version option for verge-cli

### ISSUE THREAD

**Issue by walkjivefly** [vergecurrency/verge#1063]
# Issue Template

## Context

I'm building automation tools for Blocknet servicenode operators. One of the tools needs to know the version of installed coin daemons. Other coins provide a 
`coin-cli -version`
option to report the version string. verge-cli soes not. It requires special case handling: get the information from the verged daemon instead.
 

## Prerequisites

* [x ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [x ] feature request
  - [ ] support request 
  - [ ] translation request 

## Possible Solution

PR incoming

* Verge Release: Verge Leviosa Daemon version v6.0.3
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [x ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
ACK/Tested/Merged.
