### ISSUE TITLE
Windows QT Wallet - Verge Septem version v7.0.0.0 (64-bit) - 0 Active Connections

### ISSUE THREAD

**Issue by cottonla** [vergecurrency/verge#1071]
I'm unable to get the latest version of the Windows QT Wallet to connect.
I'm using Verge Septem version v7.0.0.0 (64-bit)
I get the "0 active connections to the VERGE network." message when I hover over network icon in the bottom right of the client.
I've tried resetting the %appdata% directory multiple times and downloading the blockchain but it never connects.

Is there a way I can diagnose what is going wrong?

**Comment by justinvforvendetta** [comment]
@cottonla you were able to resolve this?
