### ISSUE TITLE
No peer connections via tor on Verge Septem 7.0.0 (OSX)

### ISSUE THREAD

**Issue by perspeculum** [vergecurrency/verge#1072]
Hi,

I appear to be having a similar issue to that described in #1053 but having tried a variety of resolution steps, Verge is still not connecting to any peers.

I have downloaded the latest version and tried following steps:

- Using -dynamic-network flag and -without-tor flag
- Importing latest peers.dat
- Adding clearnet nodes to the verge.conf file as described in #1053 

Would appreciate any further suggestions!

Debug attached, the last couple of lines continue to repeat.

[debug.txt](https://github.com/vergecurrency/verge/files/6200819/debug.txt)

UPDATE: Now working on clearnet with the --dynamic-network flag, still not connecting via tor.

**Comment by justinvforvendetta** [comment]
@perspeculum how long did you wait? also its `--dynamic-network`, with two -'s, and you **do not** need -without-tor

**Comment by perspeculum** [comment]
> @perspeculum how long did you wait? also its `--dynamic-network`, with two -'s, and you **do not** need -without-tor

I've tried with one dash and two dashes just to be sure, and waited several hours each time!

**Comment by justinvforvendetta** [comment]
do you have another app that uses tor open? you are sure the computer you are using has internet connectivity?

**Comment by jrsikors** [comment]
Adding nodes through the console to get me started was the only way I could ever get mine to work:
addnode "ONION ADDRESS" add

I would go to the discord and see if someone can get you a few active nodes to try to manually add.  I am unable to give you any myself.  Way back in the day one of the blockchain websites used to list some active nodes.  I used to go find the nodes there, but now I don't know if the peers on https://verge-blockchain.info/peers lists everything.  Some of those IPs might be clearnet as well?  Ideally you need to do the addnode to 3 different active tor nodes.. and hopefully one of them goes through.  Once you get 1, you are good to go.

~Jeff

**Comment by perspeculum** [comment]
> do you have another app that uses tor open? you are sure the computer you are using has internet connectivity?

@justinvforvendetta No other tor apps (although if I load Tor Browser, that does work, not currently running), and machine has internet connectivity.

**Comment by perspeculum** [comment]
> Adding nodes through the console to get me started was the only way I could ever get mine to work:
> addnode "ONION ADDRESS" add
> 
> I would go to the discord and see if someone can get you a few active nodes to try to manually add. I am unable to give you any myself, and not to mention it's very time sensitive. I could give you 3 right now, but if you don't check for another 4 hours, mine could be gone. Way back in the day one of the blockchain websites used to list some active nodes. I used to go find the nodes there, but now I don't know if the peers on https://verge-blockchain.info/peers lists everything. Some of those IPs might be clearnet as well? Ideally you need to do the addnode to 3 different active tor nodes.. and hopefully one of them goes through. Once you get 1, you are good to go.
> 
> ~Jeff

@jrsikors You're a genius. Managed to get one active connection from the peers list on the website you mentioned so at least it has now synchronised - still only working with clearnet addresses though, which is a bit bizarre. Still getting the connection errors when trying to connect to tor. I'll update the title.

**Comment by jrsikors** [comment]
I think you need to go to Discord and ask for multiple tor peers that you know are active and online in that exact moment.

The tor connections from the website I provided might not be valid.  "seen an hour ago" is a lifetime and pretty much means dead / never to be seen again.
