### ISSUE TITLE
transaction stuck in mempool

### ISSUE THREAD

**Issue by arnoldweerheim** [vergecurrency/verge#1073]
Hello, im having some trouble with the verge qt wallet. ive send some coins to my bittrex acc and it stays stuck in the memory pool. im not very good with computers so i was hoping someone from here could help me out. and explain what steps i should take in dummy language.

Status: 0/unconfirmed, in memory pool
Date: 29-3-2021 12:41
To: test... D6f8Lu2DauZT9nrGvQVSRViXvUetGh3uvZ
Debit: -333 332.900000 XVG
Transaction fee: -0.100000 XVG
Net amount: -333 333.000000 XVG
Transaction ID: 9f39cd8669f88fc3f8877ea7114371481d7bd362bff5e3b9477e6beb974a5009
Transaction total size: 229 bytes
Transaction virtual size: 229 bytes
Output index: 1

**Comment by jrsikors** [comment]
also , if you are on a lower version and upgrade , please make sure you have at least 1 connection in your QT client before you try to send the transaction.

**Comment by joulianet** [comment]
Hi same problem here!
I sent xvg from coinomi wallet and from atomic wallet (2 transactions). It got sucked in the mempool!!!

https://verge-blockchain.info/tx/dfa20fa59a122779458ec77c2e4f807917dfdf041db8d932e6da725a09f46110
https://verge-blockchain.info/tx/048d9d17856c6831d9569563e183815c493be54e74d36be0a7361b282c05d4d1

I contacted the support of the two wallets, they told me to contact verge team 
what I should do please ???

**Comment by justinvforvendetta** [comment]
> Hi same problem here!
> I sent xvg from coinomi wallet and from atomic wallet (2 transactions). It got sucked in the mempool!!!
> 
> https://verge-blockchain.info/tx/dfa20fa59a122779458ec77c2e4f807917dfdf041db8d932e6da725a09f46110
> https://verge-blockchain.info/tx/048d9d17856c6831d9569563e183815c493be54e74d36be0a7361b282c05d4d1
> 
> I contacted the support of the two wallets, they told me to contact verge team 
> what I should do please ???

they should provide a way to cancel transactions in their wallet like we do in ours

**Comment by joulianet** [comment]
there are no option to something like this and they said that a verge team problem and should see with verge team !

**Comment by joulianet** [comment]
I have this issue in two different wallets (coinomi and atomic). So it is verge network problem I think

**Comment by justinvforvendetta** [comment]
it is not though. like I said, our wallets provide an option to abandon the transaction.
