### ISSUE TITLE
Can not find my verge coins

### ISSUE THREAD

**Issue by javier431** [vergecurrency/verge#1074]
# Issue Template

## Context
Hi, I had a Electrum-XVG since 2017. I have the seed, password and roaming copy.
It did not syncro so that, I think I sent coins to coinomi wallet-XVG in 2020 through importing with seed.
Now, I have been days trying to set a XVG  no-tor wallet but none syncro and balance with old wallet.dat shows 0 and transactions history is empty. Coinomi wallet seems to syncro but XVG balance is 0 and history is empty. XVG wallet 7.0 syncro well but I don´t see option to restore my old wallet.

Please, may you tell me where the coins are?. My first address was D6BMSjis8LVFfXJLkKCcFSYp4uZZKQhcf1
Don´t know what to do. If any of you can help me I thanks it a lot and will donate 2000 verge if I can recover the coins.
Thanks

**Comment by justinvforvendetta** [comment]
when you sent the coins to coinomi, what did you do then? what happened to the coinomi wallet? the same coinomi wallet had your coins and now shows 0? or did you re install coinomi? that address shows ~6k coins.

**Comment by javier431** [comment]
Thank you for you reply,
Coinomi did nothing, I think it was unable of importing it.
Do you say the coins are in the old address and wallet yet?.

**Comment by javier431** [comment]
When I use the XVG explorer it seems the address has 0 balance because all coins have been sent to other address,
![explorer image](https://user-images.githubusercontent.com/82318865/114307240-0d82ea00-9adf-11eb-969f-9f0e4b35259f.jpg)
explorer image included.

**Comment by javier431** [comment]
I have fixed it importing to another generic wallet.
It´s a pity so many problems with verge wallets (no syncro, etc), it is not good for the coin. In fact, I have converted all my verges to another coin, don´t want more problems with verge...
Thank you for posting this question.

**Comment by jrsikors** [comment]
doge is moonin
