### ISSUE TITLE
Transaction stuck at Mempool // Failed to send // old version

### ISSUE THREAD

**Issue by RaspP** [vergecurrency/verge#1075]
# Issue Template

## Context

Hi there, 

was trying to send my Verge to Binance Wallet since i wanted to transfer to a online Wallet.
Well Story first had Version 4.0 Installed and tried to send - that didnt work since it was Out of Sync to fix that i tried to get the Blockchain updated and installed the newest Version.
SO now my Transaction is just unconfirmed/ Stuck at Mempool.

Status: im Speicherpool/unbestätigt
Datum: 17.04.2021 18:05
An: Binance Adress D9ixUSiGF7eLWne7zSMr9sekhNyP2EtUZC
Belastung: -115 023.267912 XVG
Transaktionsgebühr: -0.100000 XVG
Nettobetrag: -115 023.367912 XVG
Transaktionskennung: 52ababb3b393e2bbfa006e40615ce2841d46135703d057de39a4ee68981436ae
Gesamte Transaktionsgröße: 196 bytes
Transaction virtual size: 196 bytes
Ausgabeindex: 0

Thanks in advance.

## Prerequisites

* [ x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ x] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by jrsikors** [comment]
how many active connections do you have on the wallet ?

If you go to like Help -> Debug , you should see a place where it tells you how many peers or connections you have.  Do you have more than 0?  Or do you have 0 ?

**Comment by RaspP** [comment]
Hi there,
so this has now "Evolved" when starting the Verge Septem wallet it just show that its trying to update New Transaction and is doesn't change within the last 8 Hours....

Also thanks for you answer Jrsikors the first times I always had 1 Network connection to the Verge network - now I just have Zero.

**Comment by RaspP** [comment]
Just an update - didnt get it to work installed the wallet on another pc and dl blockchain andmoved wallet there - worked!

**Comment by justinvforvendetta** [comment]
glad to hear it worked. maybe the first computer is having an issue with tor? do you have other wallets running on it? tor already running perhaps?
