### ISSUE TITLE
Electrum wallet won't Connect

### ISSUE THREAD

**Issue by oliver-gomes** [vergecurrency/verge#1076]
So i bought XVG around 2017, recently was trying to retrieve my coins but failed in everything pretty much but came across this [https://github.com/vergecurrency/VERGE/issues/703] which almost fixed my issue. I got 9 seed keys and was able to find my mistaken word from non-tor word list BUT when i log in the wallet stays offline and not connected. Please any help is appreciated. FYI, I am running 2.4.1

**Comment by oliver-gomes** [comment]
@jrsikors Please help

**Comment by swat69** [comment]
Install and start 'Tor Browser'
Download the latest Electrum version and restore your wallet with your seed phrase.
https://github.com/vergecurrency/electrum/releases/tag/v4.0.3

**Comment by oliver-gomes** [comment]
@swat69 Thanks it worked, closing it out
