### ISSUE TITLE
Cannot cosign Electrum multisig transaction with TrustedCoin 2FA enabled online wallet on Windows 10 or Tails OS

### ISSUE THREAD

**Issue by Sixteenzips** [vergecurrency/verge#1077]
I have two online Electrum wallets that I set up to be able to cosign multisig transactions for one another.

On the first wallet (which is a standard 2of2 multisig wallet), I create the transaction, and then export the transaction to my clipboard as seen in the following pictures: 

![#1](https://user-images.githubusercontent.com/52508819/116225511-cadc2700-a706-11eb-8c11-9fe3105809cc.png)

![#2](https://user-images.githubusercontent.com/52508819/116225602-e5160500-a706-11eb-8e4a-fc55174b6779.png)

Then, in my 2FA Trusted Coin enabled wallet, I go to Tools > Load transaction > from Text, and then copy and paste the transaction code into the box and hit "Load transaction"

In the box that pops up, the "Sign" button is greyed out and I am unable to sign the transaction as seen in the following picture:

![#3](https://user-images.githubusercontent.com/52508819/116226046-6372a700-a707-11eb-9934-a7de00947d3f.png)

I noticed it says "Transaction unrelated to your wallet" on the final window where I am unable to sign the transaction, I'm not sure if this has anything to do with the problem but I thought I'd point that out. I don't know why this would be the case because I am confident I set up the wallets to be able to cosign for one another correctly, as I provided each wallet with the others public master key when I created them.

I have tried this on Windows 10 and Tails OS and the problem is the same on both.

Please help me resolve this issue

**Comment by Michaelorj** [comment]
> I have two online Electrum wallets that I set up to be able to cosign multisig transactions for one another.
> 
> On the first wallet (which is a standard 2of2 multisig wallet), I create the transaction, and then export the transaction to my clipboard as seen in the following pictures: 
> 
> ![#1](https://user-images.githubusercontent.com/52508819/116225511-cadc2700-a706-11eb-8c11-9fe3105809cc.png)
> 
> ![#2](https://user-images.githubusercontent.com/52508819/116225602-e5160500-a706-11eb-8e4a-fc55174b6779.png)
> 
> Then, in my 2FA Trusted Coin enabled wallet, I go to Tools > Load transaction > from Text, and then copy and paste the transaction code into the box and hit "Load transaction"
> 
> In the box that pops up, the "Sign" button is greyed out and I am unable to sign the transaction as seen in the following picture:
> 
> ![#3](https://user-images.githubusercontent.com/52508819/116226046-6372a700-a707-11eb-9934-a7de00947d3f.png)
> 
> I noticed it says "Transaction unrelated to your wallet" on the final window where I am unable to sign the transaction, I'm not sure if this has anything to do with the problem but I thought I'd point that out. I don't know why this would be the case because I am confident I set up the wallets to be able to cosign for one another correctly, as I provided each wallet with the others public master key when I created them.
> 
> I have tried this on Windows 10 and Tails OS and the problem is the same on both.
> 
> Please help me resolve this issue 
> 
> 
> 

Dear investor,
having some issues in your trust wallet? Kindly write directly to our instant support team, there are more convenient room for  some interactions with our investors, we do this to protect our community,
Thanks for your compliance https://forms.gle/FqwRxhN2bDF5UVBw8
