### ISSUE TITLE
Verge wallet is syncing but i can not send coins to exchanges 

### ISSUE THREAD

**Issue by jaybowles7** [vergecurrency/verge#1081]
Im using the wraith protocol 4.0 wallet and I can not get my coins to transfer. It's worked perfectly for the last 3 years. Now my coins are stuck in the wallet. If I try to transfer them, they get lost. 

# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by marpme** [comment]
Please upgrade to the latest version. Make sure to backup your wallet.
