### ISSUE TITLE
When regtest generatetoaddress return bad-blk-signature?

### ISSUE THREAD

**Issue by CaiJiJi** [vergecurrency/verge#1082]
![image](https://user-images.githubusercontent.com/10561685/118793225-fa77ec80-b8ca-11eb-808f-3dfe7ff99885.png)

**Comment by justinvforvendetta** [comment]
@undron what are you trying to build?

**Comment by undron** [comment]
@justinvforvendetta I am writing automation tests for an application, that works with different bitcoinlikes. Testnets are quite slow for some currencies, so I'm using regtest.
BTW, I found solution - `generate` method still works (but sometimes does not generate blocks at all), so I can get coins for my test wallet and then redistribute them.
