### ISSUE TITLE
Recovering XVG from old wallets

### ISSUE THREAD

**Issue by Axze-rgb** [vergecurrency/verge#1083]
Hello,

I had XVG at the time when the seed was 9 words. Now I see it's 12, how do I get back my XVG? Is it possible? I have the 9 words seed phrase.

Thanks a lot

**Comment by swat69** [comment]
Yes you can restore your wallet with 9 words from the old Electrum wallet with our latest Electrum v4.0.3

**Comment by Axze-rgb** [comment]
it worked, thanks
