### ISSUE TITLE
My wallet is empty

### ISSUE THREAD

**Issue by Ticocoin** [vergecurrency/VERGE#109]
Hello, I need to help.  I downloaded the wallet a few days ago, and deposited a large amount of coins, and today the wallet is showing zero balance.   I am not a very technical guy, so please help me.  My wallet is version 2.4.1.   I don't know if this is the lastest version of the wallet.  By the way, I am using windows 10.

**Comment by justinvforvendetta** [comment]
you deposited them to an address that was inside the 2.4.1 wallet?

**Comment by Ticocoin** [comment]
Yes, the address that was generated by the wallet.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by justinvforvendetta** [comment]
and you are connected to which server?

**Comment by Ticocoin** [comment]
I updated the wallet to 3.0.3, and still shows zero balance.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Ticocoin** [comment]
Server btc.smsy.me 995

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by justinvforvendetta** [comment]
you're confusing me. 2.4.1 is a verge electrum wallet version. 3.0 is a verge qt wallet. 3.0.3 is a bitcoin electrum wallet, and completely unrelated to verge.

**Comment by anhhq3k** [comment]
my Windows Electrum-XVG show offline status, my Android wallet show no connection too, dont know what problem is going on ?

**Comment by erhankaradeniz** [comment]
@anhhq3k make sure your electrum-xvg is fully synced. seems like your wallet is out of sync.

**Comment by justinvforvendetta** [comment]
@anhhq3k if you havent connected to the android wallet before, you followed the instructions for when it says "no connection" already?

**Comment by derekd123** [comment]
having the same problem my wallet wont sync the server is xvg.stream

**Comment by justinvforvendetta** [comment]
try a different server. they regularly fill up. there are several other servers to choose from, and we'll be adding more electrum servers today.
