### ISSUE TITLE
sh autogen.sh fails on debian/rolling-up on master also v7 branch

### ISSUE THREAD

**Issue by nnmfnwl7** [vergecurrency/verge#1095]
Hey guys, I am working on `decentralized atomic swap liquidity pools setup for BlockDX DEX for Debian`.
Details about project here https://github.com/nnmfnwl7/cc.setup.helper.debian/tree/experimental

As setup always builds and runs wallets from scratch in sandbox-ed(native kernel features) environment, Issue i am experiencing is in build process when trying to run `sh autogen.sh` command:

```
...
configure.ac:361: You should run autoupdate.
./lib/autoconf/c.m4:1659: AC_PROG_CC_C99 is expanded from...
configure.ac:361: the top level
autoreconf: error: /usr/bin/autoconf failed with exit status: 1

```

Which this could be caused by?

Thanks for any help.

**Comment by justinvforvendetta** [comment]
@nnmfnwl7 what version/flavor of linux? sorry i didnt see this or i would have gotten back to you sooner. 

please try this:
`sudo apt-get install git build-essential libtool autotools-dev automake pkg-config bsdmainutils python3 gcc-multilib g++-multilib`
