### ISSUE TITLE
ubuntu configure/compile issue

### ISSUE THREAD

**Issue by CryptoKaku** [vergecurrency/VERGE#110]
When running this command:

> ./autogen.sh && ./configure --with-incompatible-bdb && make

I get:

> Making all in src
> make[1]: Entering directory '/home/XXXXX/VERGE/src'
>   CXX      libbitcoin_server_a-addrman.o
>   CXX      libbitcoin_server_a-alert.o
> g++: internal compiler error: Killed (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
> Makefile:2370: recipe for target 'libbitcoin_server_a-alert.o' failed
> make[1]: *** [libbitcoin_server_a-alert.o] Error 4
> make[1]: Leaving directory '/home/XXXXX/VERGE/src'
> Makefile:524: recipe for target 'all-recursive' failed
> make: *** [all-recursive] Error 1

Any help would be appreciated, thanks.

~CK

**Comment by CryptoKaku** [comment]
Ahh nevermind, I rebooted and tryied again :)

**Comment by justinvforvendetta** [comment]
btw you should use 4.8 for bdb

**Comment by justinvforvendetta** [comment]
otherwise previous wallets won't be compatible. up to you though.
