### ISSUE TITLE
When will build binary 7.1.0 ?

### ISSUE THREAD

**Issue by manefesto** [vergecurrency/verge#1100]
Hi.
Previous release was binary for Linux,Macos and WIn.
What happened, where is binary for 7.1.0 ?

Thanks.

**Comment by justinvforvendetta** [comment]
@manefesto thats what the last commits have been for

**Comment by atomlab** [comment]
@justinvforvendetta previous releases have binaries. Is 7.1.0 non-mandatory update?

**Comment by justinvforvendetta** [comment]
@atomlab it is not mandatory. if u check the commit history, binaries are being worked on now

**Comment by justinvforvendetta** [comment]
@manefesto @atomlab windows 64 bit binaries are up for daemon and command line utils. working on qt gui, hopefully within the next day.

**Comment by manefesto** [comment]
@justinvforvendetta Thanks. But where binary for linux ?

**Comment by atomlab** [comment]
@justinvforvendetta we don't run blockchain nodes on Windows platform. Linux it's general server platform. We expect releases for Linux.

**Comment by justinvforvendetta** [comment]
@atomlab ill compile one now. generally linux users compile for themselves. ill also update our flathub.
