### ISSUE TITLE
Readme - Black Paper link is broken (404)

### ISSUE THREAD

**Issue by vmatresu** [vergecurrency/verge#1106]
# Issue Template

## Context

I wanted to see the Black Paper in the Readme and got a 404.

## Prerequisites

* [x ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

Regular browser, click link, get 404

## Expected Behavior

Click the Black Paper link, you get 404 broken link.

## Current Behavior

The link should be replaced with the correct link so it shows the Black Paper

## Screenshots
<img width="982" alt="Screenshot 2023-08-25 at 15 55 21" src="https://github.com/vergecurrency/verge/assets/31593649/3534470d-2fc9-4eb2-9825-f0c38e5f1475">

## Possible Solution

Replace the link
## Steps to Reproduce (for bugs)

* Steps :
1. Open the Readme on GitHub
2. Click the Black Paper link
3. Get 404 broken link
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by Shamir699** [comment]
Ok

**Comment by justinvforvendetta** [comment]
@Shamir699 whats up? this was fixed a while ago.
