### ISSUE TITLE
Ohh

### ISSUE THREAD

**Issue by Shamir699** [vergecurrency/verge#1108]
# Issue Template

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [x] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
@Shamir699 what is this?
