### ISSUE TITLE
Restoring wallet.dat old wallet backup

### ISSUE THREAD

**Issue by AghiathChbib** [vergecurrency/verge#1109]
Hi,
I downloaded the latest MAC OS MyVergies wallet.
I tried to recover my four years old wallet backup wallet.dat.
Every time I try to import the wallet, I get an error (unexpected token in JSON at position 0)
I don't have the paper key; at that time, the options with wallet backup, wallet.dat worked always with no issues.  
I appreciate your support 

* [ x ] Are you running the latest version?
Yes I am running MacBook M1 OS 13.5.2 
And wallet MyVergies  1.0.3

* "I'm submitting a ... "
  - [ x] support request 

I appreciate any help you can provide. Thank you

**Comment by justinvforvendetta** [comment]
myvergies is not the same wallet as the verge-qt wallet.

**Comment by AghiathChbib** [comment]
Where can I get Verge-qt wallet for MAC? The installation guide link for Mac on the website is invalid.
