### ISSUE TITLE
Windows Tor Electrum Wallet (v4.0.0-beta3)

### ISSUE THREAD

**Issue by Smufty** [vergecurrency/verge#1110]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:
Therefore I've installed Electrum Wallet (v4.0.0-beta3) and Tor Browser to be able to connect to the onion servers.    

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [x] support request 
  - [ ] translation request 

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Provide a general summary of the issue in the title of your issue -->

## Expected Behavior

 I would like to get my Electrum Wallet connected to servers.

## Current Behavior

My Electrum Wallet shows always disconnected. 

## Screenshots

![image](https://github.com/vergecurrency/verge/assets/147933819/786836c3-3432-42e1-93f3-27905935daaf)

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [x] I'm using Windows 10 22H2 

## Any extra information that might be useful in the debugging process.
Ive tried to use different server from Verge and Tor, have tried to use with Porxy 9050 & 9150, as we as wihtout Proxy.
I can not see any connect in TCPView.

**Comment by justinvforvendetta** [comment]
@smufty, are u pulling from the git/running this in pythong? ill put a new server in it right now. ill prob push a binary of this again soon too, after some updates.. been years since this thing has been touched but im sure it still works

7eagtn6nsmlyjhjv647ejj4j4orgb2cotoc5dl73qpamhvbvioao4zad.onion
