### ISSUE TITLE
Electrum Wallet-Received XVG In Wallet But "Unverified"

### ISSUE THREAD

**Issue by RonRizzo** [vergecurrency/VERGE#112]
I received my XVG  two days ago from Binance and Bittrex where both transactions have been confirmed. However, the Electrum wallet says "unverified" on all transactions.   Wallet version 2.4.1

Please advise

**Comment by justinvforvendetta** [comment]
they become spendable almost immediately, its just a cosmetic bug. hopefully its fixed in our next release of 2.6

**Comment by RonRizzo** [comment]
Thank you for the prompt reply. It's says a lot about the company and it's
prospect for future success.  Big things ahead for Verge! I'm all in:-)

**Comment by realquink** [comment]
Hmm I'm getting this but I can't spend. I have 0.9 XVG that I test sent to my wallet but its saying not enough funds when I try to send back to Binance.

**Comment by realquink** [comment]
I'm on 2.4.1 and I can't spend mine. It won't allow me to send. It keeps saying not enough funds. But I have 0.9 XVG and I'm trying to send it back to Binance to test.

**Comment by justinvforvendetta** [comment]
@realquink thats because our electrum wallets charge 1xvg to send, and you're trying to send less than the fee is.

**Comment by realquink** [comment]
Ohh, thanks for the fast response :+1:
