### ISSUE TITLE
ERC 20 and Verge coin?

### ISSUE THREAD

**Issue by Romeo01234** [vergecurrency/verge#1134]
I understand that this is not a proper place for this question, but the "Medium.com" article isn't very clear.

Will the holders of the Original Verge Coin eventually be forced to convert to the new ERC-20 coin standard?

Can there be a detail post with examples(screen shots if possible) on how to convert the Original Verge Coin to the ERC-20.
Please include best Wallet to use to get involved in the ERC-20 P.O.S option.

I forgot to add, what is the conversion ratio from Original Verge Coin to new ERC-20?

I may be leaving other questions out, not intentional. Work nights and running on fumes.

Thanks for reading. Please direct me to the proper locations if this information is already available.

Thanks,

**Comment by CBoisss** [comment]
Hello,

thanks for the questions. The answer is pretty simple; there will not be any conversion or migration between the coin and the token. 

For erc-20 compatible wallet you can use metamask, binance/okx web3 wallet, SWFT, Ellipal and in the future a Verge wallet.
