### ISSUE TITLE
Ubuntu 22 node doesn't sync

### ISSUE THREAD

**Issue by akrmn2021** [vergecurrency/verge#1135]
Compiling with the standard Ubuntu 22 libraries makes the lyra2 powhash incorrect and thus gives the high-hash error on blocks after 166767.

I am trying to compile with the depends dir. Will let you know how that works.

**Comment by justinvforvendetta** [comment]
yes we are aware, thanks for filing the issue, not sure where the issue lies, perhaps with gcc version

**Comment by justinvforvendetta** [comment]
yeah gcc was my suspect

**Comment by justinvforvendetta** [comment]
there is almost no difference when compiling between gcc 9 and gcc 11, except this:

gcc9:
crypto/pow/scrypt.cpp:119:38: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘class CHMAC_SHA256’; use assignment instead [-Wclass-memaccess]
  119 |  memset(&PSh, 0, sizeof(CHMAC_SHA256));

gcc11:
crypto/pow/scrypt.cpp:119:15: warning: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘class CHMAC_SHA256’; use assignment instead [-Wclass-memaccess]
  119 |         memset(&PSh, 0, sizeof(CHMAC_SHA256));

**Comment by akrmn2021** [comment]
Now I remember I fixed this with a "hack" in another branch I work on. In bmw.c:
#include <stdio.h>
In the bmw32_close method, add
fflush(stdout);
right after the #endif of SPH_64 (right before compress_small(buf,h,h2);)
I did this because it started working when I put printf statements in there...

Also I am trying another BMW implementation: https://github.com/floodyberry/supercop/tree/master/crypto_hash/bmw256/ref
and it seems to work, but not sure yet. Also I don't know how reputable this code is.

**Comment by justinvforvendetta** [comment]
im on a virtual machine with a high-hash build right now, ill implement this n see what happens and report back, and if it works ill label the commit so others dont have this issue in the future

**Comment by justinvforvendetta** [comment]
@akrmn2021 that worked 100%, we appreciate the insight!
