### ISSUE TITLE
ADDING NODES

### ISSUE THREAD

**Issue by kevintenda** [vergecurrency/verge#1142]
I am running verge v7.0.0 on both Windows and Mac and I noted I have no nodes running in both wallets.

In the past to solve this problem I used to go to HELP - DEBUG WINDOW - CONSOLE and I had a list of nodes to add, example (addnode xyz.onion add) This method no longer works for me. 

I went to https://verge-blockchain.info/peers and tried to add the addresses numeric and alpha-numeric  to the CONSOLE but it didn't work for me.

Is there a way to make that work?

P.S. If this is the wrong area to ask for this type of help kindly let me know where to ask.

Thanks in advance

**Comment by justinvforvendetta** [comment]
hi @kevintenda this is the proper place! firstly, adding nodes in the verge desktop wallet, is done by going into help, debug console, and then in the input bar at the bottom, typing "addnode nodename.onion add" (without quotes)

but 7.0.0 is outdated and nodes have been added since then. try 7.4!

https://github.com/vergecurrency/verge/releases

let us know if this works, and we will close the issue. i'll leave this open until you get it resolved =]

cheers

**Comment by kevintenda** [comment]
Hello @justinvforvendetta I'll let you know it in a couple of hours. 

Regards

**Comment by kevintenda** [comment]
Hello @justinvforvendetta I'll let you know in a few hours. 

Regards

**Comment by kevintenda** [comment]
Hello @justinvforvendetta  is this website   https://verge-blockchain.info/peers  where I get the nodes, right? Or there are others?  

Regards

**Comment by kevintenda** [comment]
So, I upgraded both desktop wallets in Windows & Mac to V.7.4... went to  https://verge-blockchain.info/peers to get some nodes but in both say null.  

Have a look at my screenshot. That is from mac desktop wallet. The other wallet gave me the same result.

<img width="707" alt="Schermata 2024-06-02 alle 12 50 59" src="https://github.com/vergecurrency/verge/assets/36020497/2cca6115-5e01-49ed-9869-62f19d1d6460">

**Comment by kevintenda** [comment]
Nevermind... Not sure what happened, other than keeping both wallets open for hours every thing is fine now.

**Comment by justinvforvendetta** [comment]
the new nodes you added were accepted. if your wallet hasn't been synced for a while, it may take hours for them to do so. glad you're all caught up now! try n open them once a week or so for an hour to keep them up to date =]

**Comment by kevintenda** [comment]
Alright.

Have a good Sunday.

**Comment by justinvforvendetta** [comment]
thanks! you as well!
