### ISSUE TITLE
Electrum XVG 2.4.1 Wallet problem

### ISSUE THREAD

**Issue by derekd123** [vergecurrency/VERGE#115]
I withdrew some xvg to the Electrum XVG 2.4.1 Wallet and it's not there. I think the wallet is failing to sync and i used both servers available. verge.xyz, and XVG.stream. any help would be great thanks.

**Comment by derekd123** [comment]
Got it sorted i changed the server a few times and it worked

**Comment by wnadeau** [comment]
👍 mind closing this?
