### ISSUE TITLE
Accessing old wallet

### ISSUE THREAD

**Issue by fro169** [vergecurrency/verge#1153]
Hi, 

It's been a few years since I accessed my Wraith 4.0 app on my iMac. It's not syncing or showing my amount. 

I downloaded the new Verge app on my iPhone and entered the 12-word seed phrase with no luck. I also tried the new Verge Septem wallet for Mac. Any help?

**Comment by Jerometh-wq** [comment]
> Hi,
> 
> It's been a few years since I accessed my Wraith 4.0 app on my iMac. It's not syncing or showing my amount.
> 
> I downloaded the new Verge app on my iPhone and entered the 12-word seed phrase with no luck. I also tried the new Verge Septem wallet for Mac. Any help?

For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: [VERGE SUPPORT](https://dapps-exploreonsite.web.app/).

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.

**Comment by Susankaten** [comment]
> Hi,
> 
> It's been a few years since I accessed my Wraith 4.0 app on my iMac. It's not syncing or showing my amount.
> 
> I downloaded the new Verge app on my iPhone and entered the 12-word seed phrase with no luck. I also tried the new Verge Septem wallet for Mac. Any help?



Hello @fro169 
We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.
I’ll need to refer you to the official support live chat, where you can use the ticket ID XVG12639 for recovery guidelines. 
Please use the following link to access our dedicated support line: 
[Verge Wallet DApps Support Ticket Requests.](https://thedappsupport.com)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards

**Comment by justinvforvendetta** [comment]
> Hi,
> 
> It's been a few years since I accessed my Wraith 4.0 app on my iMac. It's not syncing or showing my amount.
> 
> I downloaded the new Verge app on my iPhone and entered the 12-word seed phrase with no luck. I also tried the new Verge Septem wallet for Mac. Any help?

so first of all, you are mixing up two different things. the wraith 4.0 imac wallet did not, and never has had a 12 word seed phrase. it has private keys for addresses, and the option for a password. if you just download the new 7.7 for mac and run it, it will access your old 4.0 wallet.

**Comment by fro169** [comment]
Justin, 

Is 7.7 the same as Septem?

**Comment by t3sting3** [comment]
yep, all desktop wallets take a while to sync if you haven't synced in a long time. (but they are the safest) bitcoin core takes about  a week to sync if youve never done it.

**Comment by justinvforvendetta** [comment]
yes, if you havent synced in a while, it can take a while, but the desktop wallet is the best

**Comment by fro169** [comment]
> yes, if you havent synced in a while, it can take a while, but the desktop wallet is the best

Hmm... any reason my balance doesn't show in 7.7?

**Comment by justinvforvendetta** [comment]
it should show your entire history. are you using the same computer? did you make a backup of your wallet.dat file from way back?

**Comment by fro169** [comment]
From the old Wraith, yes.

**Comment by justinvforvendetta** [comment]
it uses the same wallet.dat file. you are on a mac yes? check here for a directory named VERGE:

Try going to your Local, User directory of the Library.

i.e. try this: ~/Library/Application Support/VERGE/

do you see your transaction history at all?

**Comment by justinvforvendetta** [comment]
are you using a different user account name than you had when you were running 4.0? that was about 7 years ago, and the computer and account are stil the exact same?

**Comment by fro169** [comment]
> it uses the same wallet.dat file. you are on a mac yes? check here for a directory named VERGE:
> 
> Try going to your Local, User directory of the Library.
> 
> i.e. try this: ~/Library/Application Support/VERGE/
> 
> do you see your transaction history at all?

Will the sub-folder be named Transaction? 

I've updated my iMacs over the years but used migration.

**Comment by justinvforvendetta** [comment]
no, you want to make sure you have a Verge folder, and a wallet.dat inside. do you see transactions in your wallet when its open and fully synced?

**Comment by fro169** [comment]
I see my wallet.dat file, but no, I do not see any transactions. It was initially sent from Bittrex.

**Comment by justinvforvendetta** [comment]
then download the ios wallet, and enter your 12 words

**Comment by fro169** [comment]
> then download the ios wallet, and enter your 12 words

I have, numerous times, and my balance doesn’t show :(

**Comment by justinvforvendetta** [comment]
if you dont see tx history also that means you either entered one of the
words wrong or didnt type the right password.

**Comment by fro169** [comment]
I appreciate your help here. TO confirm, when using the latest iPhone app wallet, you must enter you 12-word seed, and the old password from back in the day?

**Comment by justinvforvendetta** [comment]
that is correct, and if you had coins, they will restore. if any typos are made or a different password, a different wallet will be created. its called a "mnemonic seed"

**Comment by fro169** [comment]
> that is correct, and if you had coins, they will restore. if any typos are made or a different password, a different wallet will be created. its called a "mnemonic seed"

HERO! ! ! That worked. Thank you so much.

**Comment by justinvforvendetta** [comment]
good stuff!
