### ISSUE TITLE
Random auto-create address | Can't delete address | Renaming label issues

### ISSUE THREAD

**Issue by ciuccia** [vergecurrency/VERGE#118]
1)I just did my first transfer from Binance to QT wallet to an address (labelled "XY" for example), and the wallet created automatically another address without label.
2)If i rename the "XY" label, the automatically created address i wrote in point 1 get automatically renamed with the same name... (usually after 2 renames).
3)I can't see a way to remove/delete an address.

**Comment by howliam** [comment]
钱包经常提示病毒

**Comment by djdevin** [comment]
I confirmed issue 2 and 3 against e544296b (latest)

**Comment by jrsikors** [comment]
There were issues with the older versions of wallets , and according to #235  it was resolved.  @justinvforvendetta can close this .. or @ciuccia can close too please!
