### ISSUE TITLE
Out of Sync - Verge Wallet QT on Mac

### ISSUE THREAD

**Issue by londoncoingatherer** [vergecurrency/VERGE#120]
I've downloaded the QT Verge wallet on Mac, sent coins to my wallet but it says "out of sync".

When I first downloaded it there was a progress bar at the bottom, but it hasn't been there since. I've tried deleting the wallet and downloading again, restarting my computer etc and nothing works.

I'm now worried i've lost the coins I transferred fro Hitbtc.

**Comment by wnadeau** [comment]
Well you haven’t lost them if you kept your passphrase for that wallet.

What’s the chance you have a firewall blocking network access? Have you tried electrum-xvg?

**Comment by londoncoingatherer** [comment]
@wnadeau Thanks for the response, i've got the passphrase still. 

I haven't got a firewall on from what I can see. I've also tried electrum but it's said synchronising ever since I installed it..?

**Comment by wnadeau** [comment]
Also, I’m just lurking, am a verge rookie as well. I bet there’s a better place to surface this kind of question, or there will be soon if there isn’t already. Figured it was worth saying hello anyway.

**Comment by londoncoingatherer** [comment]
I've seen experts reply on some of these threads with potential explanations. There seems to be a lot of people with similar problems..

**Comment by justinvforvendetta** [comment]
how many connections do you have? if you dont have connections, you cant sync.

**Comment by londoncoingatherer** [comment]
@justinvforvendetta where do i find the connections?

**Comment by justinvforvendetta** [comment]
bottom right corner theres a connection bar. if you hover over it, it will tell you how many connections you have.

**Comment by londoncoingatherer** [comment]
It says 0 active connections.. How do I change that?

**Comment by londoncoingatherer** [comment]
I tried to add the latest blockchain but when i go to Library>application support on my mac, there is no Verge folder there..

**Comment by londoncoingatherer** [comment]
@justinvforvendetta - not sure if I need to tag you when responding, but my response is above.

**Comment by justinvforvendetta** [comment]
sounds like a firewall issue or something

**Comment by wnadeau** [comment]
+1 to firewall issue. Short of helping you troubleshoot your mac’s setup, I’m afraid there isn’t much I can do, but I can assure you that most users are connecting perfectly fine with both qt and electrum wallets, and that your coin isn’t going anywhere. I know it’s frustrating not being able to see your balance, but I feel confident you can investigate the firewall lead and eliminate the connection issues.  The fact that both wallets for you are having connection issues is very strong evidence that a firewall (either local to your machine or to your network) is a likely culprit.

**Comment by darbs** [comment]
just going to chime in on this, i too am having the issues with verge-qt and verge electrum. Firewall off/on(with verge-qt exception) and verge electrum doesn't even open on mac os high sierra.

**Comment by justinvforvendetta** [comment]
in osx, you have to drag it into applications.

**Comment by michaelandrewsai** [comment]
yes, i am not able to sync and not able to see any connections. i have macOS high sierra.

**Comment by justinvforvendetta** [comment]
well you can keep trying other electrum servers, but we'll have more launching soon. theyre syncing right now. also we're opening a website that will be open source, served from github, so users that run their own electrum servers can add themselves to the official list

**Comment by Rontiberos** [comment]
is there only 1 host gateway

**Comment by londoncoingatherer** [comment]
I've tried turning off the firewall on both my mac and my router and still no luck.. It seems other people running on OSX High sierra are having issues. I've tried the elec2.verge-blockchain.com network but it just says "synchronising" but nothing happens..

**Comment by waynep16** [comment]
Same issue on the latest using multiple networks. On mac High Sierra.  16 active connections but still says out of sync, but the sync bar is still at zero despite saying synchronizing with network... hope long should it take?
