### ISSUE TITLE
Don't work on Linux!

### ISSUE THREAD

**Issue by KKK00** [vergecurrency/VERGE#123]
VERGE-qt don't work on some distro of linux, because he i needed old libboost.

**Comment by justinvforvendetta** [comment]
can you paste the error you had?

**Comment by KKK00** [comment]
error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory

**Comment by justinvforvendetta** [comment]
linux users should always compile their own wallets

**Comment by justinvforvendetta** [comment]
t

**Comment by KKK00** [comment]
i follow the guide step by step but still not working...i need to build because i like to open a electrum server
