### ISSUE TITLE
Wallet install should prompt / bundle tor installation 

### ISSUE THREAD

**Issue by 1RedOne** [vergecurrency/VERGE#129]
Certain aspects of the marketing for Verge implies obfuscation which most may not properly utilize. The installation includes a configuration for tor but doesn't (to my knowledge) bundle tor in the process.

This is causing negative publicity as seen here (not my thread or tweet). 

https://www.reddit.com/r/CryptoCurrency/comments/7lpbo3/psa_verge_core_wallet_and_the_default_electrum/

A reasonable fix would involve bundling the nUget package for tor with the wallet installation. 

This is meant as a discussion thread, not a criticism.

**Comment by justinvforvendetta** [comment]
that's a good idea. for this core repository, tor is going directly into it, but your suggestion sounds like a great idea for the electrum wallet. our Android wallet includes tor (via orbot)

**Comment by jrsikors** [comment]
please post suggestion over on the electrum wallet forum:
https://github.com/vergecurrency/electrum-xvg-tor/issues
If you would like to pursue
