### ISSUE TITLE
XVG Core Wallet Ubuntu

### ISSUE THREAD

**Issue by Concorde89** [vergecurrency/VERGE#130]
After installing and syncing XVG core wallet on Ubuntu 16.04, actions from console do not update into the wallet. Wallet not updating balances from imported addresses or check balance for existing addresses.

**Comment by justinvforvendetta** [comment]
did you actually sync the chain or did you just download it? I can't reproduce this error after syncing the chain (not downloading it)

**Comment by Concorde89** [comment]
I did sync the blockchain. I imported a private key from an address with a balance also. The wallet does not show correct info.

**Comment by justinvforvendetta** [comment]
can u show me a screenshot and we can check it on all the blockchain explorers?

**Comment by Concorde89** [comment]
sure
![4](https://user-images.githubusercontent.com/33375316/34336240-2fd4ac3c-e95e-11e7-988f-806adb1d1a06.PNG)
![5](https://user-images.githubusercontent.com/33375316/34336241-2ff00ec8-e95e-11e7-8bf2-c5a816b333dc.PNG)
![7](https://user-images.githubusercontent.com/33375316/34336242-300c3d5a-e95e-11e7-80d3-81e12fd96ae7.PNG)
![verge1](https://user-images.githubusercontent.com/33375316/34336243-30285ddc-e95e-11e7-9c64-1c14a06d56dc.PNG)
![verge2](https://user-images.githubusercontent.com/33375316/34336244-3044c86e-e95e-11e7-8c76-af5d172fd5dc.PNG)
![verge3](https://user-images.githubusercontent.com/33375316/34336245-306051f6-e95e-11e7-867b-0ec2c1df05e6.PNG)

**Comment by justinvforvendetta** [comment]
your wallet is locked

**Comment by Concorde89** [comment]
I just printed you some screens. Ofc I unlocked the wallet when doing all I said I did. This issue is far from closed.
