### ISSUE TITLE
About wordlist source for 9-word recovery (mnemonic sentence) generated by Verge wallet

### ISSUE THREAD

**Issue by hatgit** [vergecurrency/VERGE#137]
I noticed the 9-word recovery backup generated by the Verge wallet doesn't seem to fit with the 2048 words used with the [BIP39 wordlist](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt#L1366) typically used by wallets, such as the 12 words generated by the [Electrum wallet](https://github.com/spesmilo/electrum). 

Can someone provide the following:

1) Source of the wordlist used by the verge wallet (i.e. link to all words in the list and their place or numerical index value in the list of words).
2) How each word is encoded to the initial entropy generated by the wallet (i.e. is it the same as BIP39 and just uses a different wordlist?)
3) Whether the words have any additional encryption as some of them look mixed with cipher text (i.e. words like "mslike" ,"positve" or "humdogc.")

Thanks,

**Comment by jrsikors** [comment]
doing some spring cleaning on old issues sorry -- please open up new issue (don't re-open this one or it will re-open on the 2nd page and no one will see it) :smile:
