### ISSUE TITLE
seed nodes

### ISSUE THREAD

**Issue by vashshawn** [vergecurrency/VERGE#139]
no current seed nodes in the wallet, and no dns seed server enabled

**Comment by vashshawn** [comment]
Also how come addnode was removed as a option in the debug command console? Only way to manually add nodes is with a conf file at the moment.

**Comment by adedommelin** [comment]
As mentioned here : https://twitter.com/adedommelin/status/945702401352388609 I've registered a domain name & setup a sub-zone with all the required mechanisms to load balance requests across healthy nodes.

@justinvforvendetta feel free to come back to me if you think it can help !

**Comment by Goranbol** [comment]
Nine out of ten wallets that I download is working with no probs. After sync is fine. Downloaded two verge wallets,none of them is working. Ahahahahahahahahaha

**Comment by jrsikors** [comment]
Care to elaborate on what your actual problem is @Goranbol ?  Or are you just trolling?  Verge-QT Wallet works fine if you download the latest version.

**Comment by jrsikors** [comment]
for verge-qt wallet .. to sync up blockchain faster, download the bootstrap;
https://verge-blockchain.com/

for electrum wallet:
After fork some of the old electrum servers are not so good.

https://www.reddit.com/r/vergecurrency/comments/7uelnl/electrum_wallet_offline_please_help/

There's a link to a youtube video that looks good

Nutshell instructions:
Step 1) Close down Electrum wallet
Step 2) Browse to where your Electrum 'installation' is
Step 3) Go into the Lib folder
Step 4) Open network.py in notepad or textpad , some kind of text editor
Step 5)
Replace this chunk of code:

DEFAULT_SERVERS = {
'electrum-verge.xyz':{'t':'50001', 's':'50002'},
'electrum-xvg.stream':{'t':'50001', 's':'50002'},
'electrum-xvg.party':{'t':'50001', 's':'50002'}
}
With this chunk of code:

DEFAULT_SERVERS = {
'electrum-verge.xyz':{'t':'50001', 's':'50002'},
'electrum-xvg.stream':{'t':'50001', 's':'50002'},
'electrum-xvg.party':{'t':'50001', 's':'50002'},
'e1.verge-electrum.com':{'t':'50001', 's':'50002'},
'e2.verge-electrum.com':{'t':'50001', 's':'50002'},
'e3.verge-electrum.com':{'t':'50001', 's':'50002'}
}
step 6) Open Electrum
step 7) Go to tools -> network
step 8) Make sure "Auto-connect" is checked, and the 3 electrum servers are listed:
e1.verge-electrum.com
e2.verge-electrum.com
e3.verge-electrum.com

**Comment by jrsikors** [comment]
Despite you being quite rude to the project, I took the time to figure out what your problem was, then researched to help you out.  

All you have to do is ask nicely.   Consider trying to be a nicer person in life and you might be happier.

**Comment by Goranbol** [comment]
Hi Jrsokors.
Trolling you say ? 
It did not work. 
Am I nice or not you cant be judge of that from a single post.
You are also three days late with answer. So work on the response time.
Post that explanation in the Verge ann group too. So people can find it easy when yhey download a wallet that doesent work.

Hope I helped.
Off to bed!
Good night !
