### ISSUE TITLE
Compile on ubuntu error

### ISSUE THREAD

**Issue by nkazier** [vergecurrency/VERGE#141]
When i compile on Ubuntu 16.04, the step at which i put in ./VERGEd i receive "No such file or directory"

**Comment by biendinh** [comment]
let try ~/.electrum-xvg or ~/.electrum-xvg-tor

**Comment by Innox-dev** [comment]
I thought the dir was ./VERGE  not VERGEd

**Comment by nkazier** [comment]
Ill try some things out, the ./VERGEd gets you the random wallet number, or at least thats how  the windows complied version works.  Thus why the readme file states to run the ./VERGEd command.  I will try it when i get back at the house and let y'all know.

**Comment by Innox-dev** [comment]
**i just got this trying to compile. will explore a bit now ans see whats happening. i think it may be the script error, not the actual compile.**

make[1]: *** No rule to make target `qt/res/icons/chat.png', needed by `qt/qrc_bitcoin.cpp'.  Stop.
make[1]: Leaving directory `/root/VERGE/src'
make: *** [all-recursive] Error 1
Compile fail not VERGE-qt present
cp: cannot stat ‘/root/.VERGE/VERGE.conf’: No such file or directory
Do you wish to download the complete VERGE Blockchain (y/n)?n
Blockchain will not be installed sync may be long
go.sh: 254: go.sh: VERGE-qt: not found
cp: cannot stat ‘/root/.VERGE/wallet.dat’: No such file or directory
root@node4-innoxd-usa-ubuntu16-04:~/VERGE#

**Comment by yodi94** [comment]
got same error today , by install it on vps ubuntu 14

**Comment by bshowket** [comment]
Same issue here, ubuntu 14.04 

```
make[1]: *** No rule to make target `qt/res/icons/chat.png', needed by `qt/qrc_bitcoin.cpp'. Stop.
make[1]: Leaving directory `/root/verge/src'
make: *** [all-recursive] Error 1
```

**Comment by hershman** [comment]
Try this branch: https://github.com/vergecurrency/VERGE/pull/144
