### ISSUE TITLE
Address changed, can't recover coins

### ISSUE THREAD

**Issue by HumphreyPloughjogger63** [vergecurrency/VERGE#145]
Hopefully somebody has some insight here, I downloaded QT and opened it, clicked receive to get my address, got on binance and sent 5000 xvg to that address. I didn't know anything about having to download the blockchain and syncing, I use a ledger nano S for my other coins, I've never encountered this before. I downloaded the newest blockchain and my wallet synced, but the original address I had is no longer listed when I click "receive," it's a different address now. My coins aren't in there (tx confirmed on the blockchain) and I don't know how I can access the old deposit address. I can't find my private key for the original address, and I'm hitting dead ends everywhere I turn. Any ideas?

**Comment by 240mamba** [comment]
Not sure but send me your address and I’ll send u 5000, I’m in the giving
mood lol

**Comment by HumphreyPloughjogger63** [comment]
lol that'd be great, DLxTkGnHCcSEkjWFX7AEjTXgPYE5TFZgzt

**Comment by edpark722** [comment]
Wow, what a great guy.  I wish I even had 5000 coins to lose :).  Props to u Mr. Mamba

**Comment by 240mamba** [comment]
sent! have a good night!  hopefully you can recover your lost coins

**Comment by HumphreyPloughjogger63** [comment]
Received! wow that is incredible thank you very much Mamba! Quite a community we've got here!

**Comment by edpark722** [comment]
@240mamba if your still in the giving mood, my wallets always available lol DNYTNhMDZMrqnrse9RGTXbxvH6fktH31WM

**Comment by lleksii** [comment]
Wow, 5000 coins just like that haha. I hope I can do that someday too 🚀

**Comment by HumphreyPloughjogger63** [comment]
I'll certainly pay it forward once we moon!

**Comment by CmplxStack** [comment]
This is what makes life beautiful.  Pay it forward!

**Comment by edpark722** [comment]
@HumphreyPloughjogger63 i'm really hoping wraith is released soon.  stop the drop!

**Comment by CmplxStack** [comment]
@240mamba Awesome move! I hope 2018 is amazing for you, and verge does well so I can help others when given the chance too. Cheers!

**Comment by Globetrotterger** [comment]
Hehe Mamba my verge adress is also open 😊DJEY7fY4qiBDPTE8wafx1QzcezuLg5Qgic  I Invested 1500 Dollar and lost the half in the last 2 days but i trust the verge team and hodl 
Greets from Germany and a Happy new Year

**Comment by rvrhee** [comment]
Hi mamba i also lost a $1000 big pocket with al this FUD mayby u can fix my problem too
i invested all of my last money in $xvg because i believed in the project, but i could not hodl
no longer because i cannot miss it for real,
 
DEMDyEE7vmV1hxjqmhxxx2ZSRsMNLovYFW

**Comment by HumphreyPloughjogger63** [comment]
When XVG reaches $1 I’m going to come back to this threat and pay it forward with the xvg equivalent of $1000. I’ll pick one of you at random that has commented before this comment. Hold me to it.

**Comment by HumphreyPloughjogger63** [comment]
($1000 was roughly the fair market value of the 5000 coins from mamba)

**Comment by CmplxStack** [comment]
@HumphreyPloughjogger63  Solid move man, must lead by example in a world of negativity. Pay it forward always!

**Comment by namKolo** [comment]
@240mamba  If your still in the giving mood, my wallet is always available lol  
`DGa4av3ZStmtiEbW65Ybb983jGAFtBSV4L`

**Comment by CryptoFutures** [comment]
You lucky guy! @240mamba if your are still on the moon spare me some little DMAwwRDznpK1MayJwxhqADV4NfQnNh7m8B. Sorry for the bagging. So much XVGLove!

**Comment by GStaxx** [comment]
I didn't know they were on GitHub, too.

![hobos](https://user-images.githubusercontent.com/34944191/34443599-3912fac0-ec96-11e7-83eb-be2209d1ddeb.png)

**Comment by Tommixoft** [comment]
Because wallet generates about 30 addresses and it changes to new one when you get money. You got your money!

**Comment by Triggman501** [comment]
I'm deployed to Iraq right now and my testosterone just dropped to dangerous levels.I think that was the most sweetest shit I think I have ever witnessed. I hope ISIS doesn't get the drop on me tonight😭

**Comment by richcrypto** [comment]
This is what they call generosity 
I am so so proud 
Hope I get some help someone 
I don’t want 5000 but anything you offer is cool

**Comment by besnikl** [comment]
Great Job Mamba! Wish you all a Happy New Year ...

**Comment by richcrypto** [comment]
any generous person or people can help me with ripples

**Comment by madpada** [comment]
Go get a job... earn some money... and buy your own. Thats what most people have done.

**Comment by jgalante1978** [comment]
hey guys, i downloaded an electrum wallet is was someting verion like 2.4 or something.  it always was connected to the network.  so i sent coins to it about 300 bucks and the address i s waiting for the coins, the software never was able to connect to the network again to recieve the coins, ive done everything, tried the latst version like 3. something all i got was i can see this info but i dont know how to get the address and coins back to me, i used a seed restore, master key nothing
check it thats my coins and address on the blockchain i guess? been at this for 5 days i need help, thanks 

https://verge-blockchain.info/tx/f2a6a7e907bc071546dc521745162d88f0bc7f16cb0be1d289527d5b59ebcc1f

DJ2dW7mMfmXycj2DQhQy4GSNtz5DcocjBC | 1018606.13586100
DCbLHa6TyKH8BaWmWmTFrjLUY7MuNQaahs | 1023.53766700
