### ISSUE TITLE
wallet has been syncing for 6 days!!

### ISSUE THREAD

**Issue by piphoto23** [vergecurrency/VERGE#146]
I started syncing last Friday night and my computer has been on non-stop, I'm at 76% synced and Ive already transferred my coins to the wallet from binance but obviously they wont show in my wallet until its synced and the fact its taken 5 days to sync and Im at 76% has got me worried.  I have the 3.0 wraith for iOS desktop.  Anyone else having this issue?

**Comment by ZarubinArtem** [comment]
Thank Good it is SYNCING, my one just can not connect to any XVG servers 2 weeks)

**Comment by peterlnewton** [comment]
Have you tried downloading the blockchain directly, and placing them in your folders? Instructions are located here.

https://verge-blockchain.com/howto

**Comment by piphoto23** [comment]
I don't have a verge folder under my library and application support to put the blockchain into.  i don't know why when i downloaded the wallet the Verge folder didnt appear

**Comment by piphoto23** [comment]
I just want to make sure that because I sent the coins from binance to my wallet before it was synced I didnt lose the coins because it was over 45,000 coins
