### ISSUE TITLE
Mining pool Idcray lost funds after updating

### ISSUE THREAD

**Issue by Technophant** [vergecurrency/VERGE#151]
From their announcement on homepage (http://xvg-mg.idcray.com/) dated yesterday, they claim to have lost 2.6M xvg from "wrong blockchain and wallet bug".  

From the screen shot of mining pool wallet config, version is 2.1.0.0-1c418be-beta.  1c418be is the last commit to master.  One or more transactions were made with no change address, so instead of 620xvg sent from a 1M of unspent outputs with 999.4k returned to a change address, the miner of the next block was awarded the balance as a transaction fee.

**Comment by justinvforvendetta** [comment]
that's a lot of coins. I wonder why they don't force users to mine with their address. pools that hold balances are just time bombs
