### ISSUE TITLE
Wallet Issues - With Recent Update

### ISSUE THREAD

**Issue by daygle** [vergecurrency/VERGE#153]
I am noticing some very bazaar issues with the linux wallet, funds seem to be disappearing. Are you able to advise how this is happening? This is now the second wallet that has experienced the same issue after the recent upgrade.

How do I recover the funds?

My other wallet has lost over 88,000 coins, could someone please urgently reply.

See below example of issue (the below is an example of the second wallet/new wallet I setup to see if a new address would correct this issue, but it didn't):-

You will notice that this wallet generated 4 blocks @ 1560 each and made three transfers totalling 1691.791947 but the balance is still 1560.97916400!!!!

How is this event possible?

###

VERGEd listtransactions ''
[
    {
        "account" : "",
        "category" : "orphan",
        "amount" : 1560.00000000,
        "confirmations" : 0,
        "generated" : true,
        "txid" : "3021a19ddf56e45e3b07e93c4069c2e8c585ae246483dbc2e700002a000c72f7",
        "time" : 1514468347,
        "timereceived" : 1514468352
    },
    {
        "account" : "",
        "category" : "generate",
        "amount" : 1561.31089200,
        "confirmations" : 1247,
        "generated" : true,
        "blockhash" : "0000000000002f5bf2e5ba61d58d0ef78a83da6fc54a8fef12ed36675c61a395",
        "blockindex" : 0,
        "blocktime" : 1514471808,
        "txid" : "f7e9be314e7db64c608c5670357bc3217e0dac848f0fc88b8983814bafc7fcc6",
        "time" : 1514471808,
        "timereceived" : 1514471842
    },
    {
        "account" : "",
        "category" : "generate",
        "amount" : 1563.20000000,
        "confirmations" : 1039,
        "generated" : true,
        "blockhash" : "00000000000037647305b5d66d0024d1d20f5204d3eaa61995218d4af6c1eca7",
        "blockindex" : 0,
        "blocktime" : 1514479505,
        "txid" : "6dc4754f187a62bc5d86aa388af07b724632843ab1a9fc18759f78ba4aa4bd8f",
        "time" : 1514479505,
        "timereceived" : 1514479526
    },
    {
        "account" : "",
        "category" : "generate",
        "amount" : 1561.80000000,
        "confirmations" : 603,
        "generated" : true,
        "blockhash" : "0000000000007097ec0d0f3ac3bda1ce41bc5aed5bc9001dc0704b9e9c9ac24f",
        "blockindex" : 0,
        "blocktime" : 1514494499,
        "txid" : "c344a7de6549a7e7a0f32f00e452bd5f4841ebd1d904a0b1e5f744eac1bd2d59",
        "time" : 1514494499,
        "timereceived" : 1514494522
    },
    {
        "account" : "",
        "address" : "DFn35JJCY3ZJ49TLMGhKiCWVPog9odmuL9",
        "category" : "send",
        "amount" : -305.17209500,
        "fee" : -1256.13879700,
        "confirmations" : 584,
        "blockhash" : "e51d430fa2e66b1ba0c840af04aa45b725265d47df29ec4d14496511274cdeda",
        "blockindex" : 5,
        "blocktime" : 1514495177,
        "txid" : "51696c1d6a7599b8819177121817efb8f3c5598810ae75daa48db3d86c86c1f5",
        "time" : 1514495102,
        "timereceived" : 1514495102
    },
    {
        "account" : "",
        "category" : "orphan",
        "amount" : 1560.60000000,
        "confirmations" : 0,
        "generated" : true,
        "txid" : "b66b865e313465ea72721efda7b537885986798ffaca0368ec69a853acf983ce",
        "time" : 1514497888,
        "timereceived" : 1514497909
    },
    {
        "account" : "",
        "category" : "generate",
        "amount" : 1560.97916400,
        "confirmations" : 490,
        "generated" : true,
        "blockhash" : "00000000000094f2e676990f7b08954a671949c8b60c0e34ab73b813e7dc6199",
        "blockindex" : 0,
        "blocktime" : 1514498055,
        "txid" : "778f36c7e55687617429e3ab708e6935fefd72617eced322d4d18fea69c9244c",
        "time" : 1514498055,
        "timereceived" : 1514498081
    },
    {
        "account" : "",
        "address" : "DAueyKezon2yvttW9jG69dySww3BHYUMPZ",
        "category" : "send",
        "amount" : -52.14300000,
        "fee" : -1509.65700000,
        "confirmations" : 457,
        "blockhash" : "b3cd0324a0dedb30f4a3429d75a21c98abfb07b71e1b25aa63337b1c2c2fb1a9",
        "blockindex" : 5,
        "blocktime" : 1514499332,
        "txid" : "941ae5e18d3c987ad89cdfa1b762da478173b34abc2f38f2f417be17a72c279f",
        "time" : 1514499301,
        "timereceived" : 1514499301
    },
    {
        "account" : "",
        "address" : "DKy5QmHqesbRS4fdNXEtNfQFSa31LkSNUH",
        "category" : "send",
        "amount" : -1334.48985200,
        "fee" : -228.71014800,
        "confirmations" : 457,
        "blockhash" : "b3cd0324a0dedb30f4a3429d75a21c98abfb07b71e1b25aa63337b1c2c2fb1a9",
        "blockindex" : 2,
        "blocktime" : 1514499332,
        "txid" : "c4012ae9b3ea22fc1d06576af3a78bfee154b04ac19dd66f0b94b92a0fea7d0a",
        "time" : 1514499301,
        "timereceived" : 1514499301
    }
]
VERGEd getbalance
1560.97916400
VERGEd getbalance ''
1560.97916400

**Comment by justinvforvendetta** [comment]
orphan blocks are blocks that were thrown away because that block was found elsewhere just before you found it

**Comment by daygle** [comment]
@justinvforvendetta I don't think you have understood the issue correctly. I am not raising a issue about the orphans.

Have a look at it again...

4 blocks @ 1560 = 6240 XVG
Withdrawals = 1691.791947 XVG

That should leave a balance of 4548.208053 XVG. But as you can see from the getbalance I only have a balance of 1560.97916400 XVG.

There seems to be a serious calculation issue with the wallet.

**Comment by Technophant** [comment]
What mining software are you using?  MPOS?  For some reason, the tx fee is too high.  When did you compile and from where?

**Comment by daygle** [comment]
It was compiled from GitHub (https://github.com/vergecurrency/VERGE). I never set the tx fee, the update must of changed this.

Are you serious, so I have lost over 88,000 xvg to tx to fees?

**Comment by daygle** [comment]
Will the coin developers credit me for this mistake? I feel this is a little unfair.

**Comment by justinvforvendetta** [comment]
solved in https://github.com/vergecurrency/VERGE/commit/060676554dcc1357fe8f855184f8da094cc0513f

**Comment by daygle** [comment]
What about all the funds I have lost?

**Comment by JeramyNS** [comment]
@daygle why did you have so much money in development version of the wallet?

**Comment by daygle** [comment]
I am a pool owner, this wasn't a development version.

I should be credited for this error!
