### ISSUE TITLE
Wraith Protocol 

### ISSUE THREAD

**Issue by MPI1977** [vergecurrency/VERGE#154]
I fucking love this coin.  Just bought myself my second classic car through the success of this coin. Just wanted to put it out there.  Good work JV! If we get to 2000sats by tonight Australian Eastern Standard Time, my wife drops an bomb and gets hardcore XXX as promised.  Drop Wraith JV for a brother in need.  It's 6.24pm here - hahahaha.

**Comment by JavierMendozaGomez** [comment]
Please this is not an issue

**Comment by KevinMcClintock** [comment]
Lol
