### ISSUE TITLE
Verge Tor Android wallet

### ISSUE THREAD

**Issue by JSBachForSoulCleansing101** [vergecurrency/VERGE#156]
Hi Justin....hi five to you and all ur developer comrades.... especially everyone who's contributing to the Verge project....can we call them "Justinions"?   "Minions".  "Justinions".   Get it?  Lol...🙄....ah. Yeah...anyways...been playing around with the wallet on my pixl...sending a few verge back and forth to bittrex and to a friend....generally ok experience....but having connection issues...even after toggling torbot...a couple transactions didn't go through...small amounts...nothing to cry about...but thought I'd mention it.  Also wallet reads 0 balance about half the time or more...a bit unnerving....not a very technical guy so maybe I'm doing something wrong...just a musician here...anyhow if u have a moment to advise...would appreciate...btw been a Verge fan for months....even when everyone around me said I was crazy....bought at 60 Satoshi....me so happy!  Final note...I bought in after I saw your interview with those two pivx MBA posers....first thoughts...this guy is some kind of good will hunting hacker genius mf....sitting in his bunker changing the world...final thought...when the world feels like it's crushing you down...take a deep breath....put on your headphones...the really good ones and listen to JS Bach art of fuge... especially grigory Sokolov edition...will take you to another dimension...no drugs necessary...peace out

**Comment by justinvforvendetta** [comment]
did you try the instructions for when theres no connection? (the orbot "app vpn mode" thing, where you select everything except verge?)

**Comment by JSBachForSoulCleansing101** [comment]
Hi Justin....thank u for the reply...yes I followed the instructions and checked the verge wallet box on and off several different times...still the wallet is a bit capricious.  Kinda had a mind of its own...

Sent from Yahoo Mail on Android 
 
  On Fri, Dec 29, 2017 at 5:21 PM, sunerok<notifications@github.com> wrote:   
did you try the instructions for when theres no connection? (the orbot "app vpn mode" thing, where you select everything except verge?)

**Comment by justinvforvendetta** [comment]
nooo, you have to select all the apps EXCEPT verge lol do you have a samsung?

**Comment by JSBachForSoulCleansing101** [comment]
Hello again....just redid everything again....weirdest thing...went from zero balance to an odd number...399 something...I don't think I ever made any transactions in that amount....then I refreshed and balance went back to 11000 something....only thing I did differently was switch from my home att wifi to attend wireless data...

**Comment by JSBachForSoulCleansing101** [comment]
Att

**Comment by JSBachForSoulCleansing101** [comment]
Yes selected everything except the verge wallet...and no...no Samsung wife got me the pixl last bday

**Comment by JSBachForSoulCleansing101** [comment]
Wish I could send u screen shots of what I did....to confirm or refute that I'm a dufus

**Comment by JSBachForSoulCleansing101** [comment]
Ok....progress...now connection happens....but for a few seconds Ballance shows an odd combination of deposits....in my case 399.60 verge...only way to get that would be to combine my first deposit with another one made a few days later...then that balance is replaced by the actual one....so that's the symptom now...but definitely am improvement on the chronic zero balance situation.

**Comment by JSBachForSoulCleansing101** [comment]
Quick question.  If the verge Tor Android wallet is unchecked on the orbot app....does that mean the transaction is no longer private on the tor network?...not sure I'm asking correctly...but u probably understand what I mean...

**Comment by justinvforvendetta** [comment]
nope. the android wallet connects to a hidden service, so there is no way to accidentally expose yourself to the network

**Comment by JSBachForSoulCleansing101** [comment]
👍👍

**Comment by sgohaness** [comment]
Happy holidays to Justin and Dev team thanks for all the hardwork and late hours.... 
Hope you can help with a problem...

Funds were first stored on verge android torr wallet. What I experienced was zero balance and transaction history with errors all the time. Last night I decided to try and isolate the problem. So I restored the wallet using coinomi and Im getting same errors on coinomi.
I followed directions and enabled vpn mode on all apps… I also tried No apps. I tried only verge on and off. I tried all apps except verge. I am facing the same problem.




I looked into this error in regards to coinomi and found out its something with microsoft azure dns servers thats the closest i got to the issue... because coinomi customers having the same issue. Some customers at coinomi customer support form say this problem is fixed.... Wallet does show proper block height currently for me but no funds. Basically wallets are still not functioning.
I opened a ticket with coinomi customer support. Hopefully we get past this problem soon. I will update you guys once I find a solution. that works. all the time.

**Comment by JSBachForSoulCleansing101** [comment]
Hi Justin...must feel like u are sitting inside an oven right now.....temp rising...blah blah blah.... don't fret...nobody died...the sun and moon still did their thing... remember all those  who came before you....all those upon whose work and invention you have built your technological child....none of them had it easy...they all struggled and dealt with setbacks... large and small....but they kept going...at the darkest hour the light shines through... everything will work out!

**Comment by JSBachForSoulCleansing101** [comment]
Oh yeah....take 3-4 minutes of your time to listen to JS Bach Goldberg variations.... recorded by Glenn Gould in the early 1980s....he played it like he was communicating directly with God if u believe in one....like he knew he was on borrowed time...he had a massive stroke not too long after that and died at a very young age 50...but give it a listen

**Comment by JSBachForSoulCleansing101** [comment]
Fuel upon the power sources great people left for us...don't allow urself to go on empty...u must refuel...but the fuel isn't the typical kind...think outside the box.

**Comment by gross85** [comment]
I have the same problem I tried everything still says no connection. Also if I had xvg sent to that address will it still go there even know I don't have a connection

**Comment by alin-nemet** [comment]
Pleas help, any way to fix the no connection issue!? I have Verge Tordroid on android galaxy S6, it worked fine for a transaction on 21 Dec 2017, and then all I get is no connection, I've exchanged 1.95 BCH for verge and feel like I lost my money :(( what can I do now? thanks for any help

**Comment by Caatje** [comment]
What worked for me was downloading coinomi and restoring my wallet in the app. I don't think it's verge, I think it's cause by issues with Orbot. If you can, download the latest version of the desktop wallet and store your funds on there, much saver.

**Comment by alin-nemet** [comment]
Thanks for the comment! But if I uninstall/reinstall the same wallet, or if I use a desktop wallet  will the address to which I sent from coinbase still be valid!? I did the exchange through changely. Not sure how things will work out :/

**Comment by gross85** [comment]
Thank you   but do you need orbot for coinomi also

**Comment by alin-nemet** [comment]
Finally completed :) I see the money in coinomi, nice wallet afterall...cheers guys!

**Comment by justinvforvendetta** [comment]
if you downloaded our android wallet from google store, it has instructions for if your wallet says "no connection"

**Comment by alin-nemet** [comment]
It somehow recovered, it took such a long time for the blockchain to confirm the transaction and I thought it was because the wallet wasn't online. I downloaded the coinomi wallet and restored the verge wallet which might have helped/sped up the tx, not sure...

**Comment by 2020-316** [comment]
Was having same  "no connection"  issues. Had downloaded app for Tor android from google play. So deleted and reinstalled from web site. VPN connect came right up. Check Verge in Orbot apps. Open from Orbot. Press balance bar. Received coin confirmation. https://www.torproject.org/docs/android.html

**Comment by DolfjeWolfje** [comment]
Had the same problems..

no connection, extremely frustrating....why those fools dont solve the connection problems.
Installed coinomi, restored the verge wallet and transfer to binance...

Thanx a lot Caatje!!!

**Comment by Matrix8081** [comment]
Having a problem with the android wallet not connecting again.  Please help I was trying to make a purchase with a vendor that accepts verge and I can't connect.  Tor is enabled I've had this wallet for a long time now so I've done all the troubleshooting

**Comment by Matrix8081** [comment]
Having a problem with the android wallet not connecting again.  Please help I was trying to make a purchase with a vendor that accepts verge and I can't connect.  Tor is enabled I've had this wallet for a long time now so I've done all the troubleshooting
