### ISSUE TITLE
Address changed, Sended coins but can't recover coins ;-(

### ISSUE THREAD

**Issue by JeroenAms** [vergecurrency/VERGE#159]
Goodmorning,,,,

I have a little Question,
I had some vergecoins ( 50000 ) at my litebit account and did send it to an wallet of verge..
now I can't get my coins.. I tried to get in but nothing helped.. 
addresses are right but no coins 
synced a lot of times but not working 

I already started a new but nothing helped !!

Can someone help me with this issue ???   :-(

**Comment by lionelrose** [comment]
first, have you set the good wallet address ?
second,,your wallet is connected ?

**Comment by JeroenAms** [comment]
Hello lionelrose,

I did use the right wallet address.
And the wallet first didn't connect but with the tor it is.. 

Still nothing in my account.. 

I will wait for it..

**Comment by pottink** [comment]
Can you see it on the http://verge-blockchain.info ?

**Comment by Hilobrain** [comment]
If the transaction is on the blockchain, it should be alright. If not... than you should contact Litebit I think

**Comment by Hilobrain** [comment]
Is it fixed?
