### ISSUE TITLE
Multi-algo is broken

### ISSUE THREAD

**Issue by MentalCollatz** [vergecurrency/VERGE#16]
Issue 1: 6-second block times.
You need to multiply nProofOfWorkTargetSpacing by NUM_ALGOS.

Issue 2: Work calculation is heavily biased toward certain algorithms
`GetBlockTrust()` has not been updated, which means that the algorithm with the highest difficulty can trivially undo blocks mined by other algorithms, and 51% attack the network with slightly more than 51% of a single algorithm.

There also might be a possibility of time-warp attacks against DGW.  I haven't looked at it very hard, but didn't see anything that prevents the style of attacks that occurred against DigiShield on DGB, MYR, and SFR. DGWv3 and DigiShield are quite similar.

**Comment by vergecurrency** [comment]
multi algo doesnt start until block 340,000. dgw implementation here is dgw3. so far i have not read of any timewarp attacks on dgw3

**Comment by vergecurrency** [comment]
where do you see 6 second block times?

**Comment by vergecurrency** [comment]
oh your saying because there are 5 algos the blocks will be produced every 6 seconds, one on each algo.. ?

**Comment by vergecurrency** [comment]
unsigned int nProofOfWorkTargetSpacing = 30*5 should cover it then

**Comment by vergecurrency** [comment]
actually ill need to make a new MultiAlgoTargetSpacing = 150

**Comment by vergecurrency** [comment]
@MentalCollatz are you still around?

**Comment by MentalCollatz** [comment]
Yeah that should fix the ultra-fast blocks.

**Comment by vergecurrency** [comment]
i dropped you an email if you have a minute. thank you for opening this issue and catching it ahead of time. i browsed your previous commits. well done. we will be tweaking after the fork within a week im sure to balance everything out once we see how it fairs.
