### ISSUE TITLE
README.md installation on OSX wrong

### ISSUE THREAD

**Issue by Arnauec** [vergecurrency/VERGE#166]
If you check the points you'll see the following one:

2. Download qt5.4.2 - https://download.qt.io/official_releases/qt/5.4/5.4.2/qt-opensource-mac-x64-clang-5.4.2.dmg

This link is dead, can't install it.

**Comment by fabiotnt** [comment]
You can download the 5.4.2 version from archive folder

https://download.qt.io/archive/qt/5.4/5.4.2/

**Comment by jhanink** [comment]
@justinvforvendetta  I have a fix for this 
* working download url
* update qt version to 5.5 to match the version in build.sh
* updates to readme qt install PATH
* removes some trailing white spaces

Can you make me a contributor and I'll push the branch?

**Comment by ekryski** [comment]
I'll post a PR shortly with updated build instructions.

**Comment by jhanink** [comment]
@ekryski is everything else ok with this - i.e. qt5.5? it seems the qt5.5 download installer gets stuck for some people. Is this a blocker?
