### ISSUE TITLE
Help! I put transferred 300 verge coin a week ago to Verge 3.0 and it's gone

### ISSUE THREAD

**Issue by jbutr8888** [vergecurrency/VERGE#175]
One week ago I transferred verge coin 1 week ago and verified it was there and now it's gone. It's fully synced and everything but it's gone... Help please
![verge 1](https://user-images.githubusercontent.com/34990924/34464537-6b1a3b48-ee51-11e7-911f-11558ad8cd0a.png)
![verge 2](https://user-images.githubusercontent.com/34990924/34464538-6b2be44c-ee51-11e7-80d0-7ef9e127bc0b.png)

**Comment by pierrederuelle** [comment]
I had the same problem today - on Linux. Became Crazy. After thinking about it, I realised my Wallet was in fact in another user folder : If I synced once with blochain localy, it's obviously somewhere. After a copy from user's folder to an other, wallet came back. Hope it helps.

**Comment by jbutr8888** [comment]
Ya I see what you mean. I do have another folder with a bunch of other stuff in it. Do I just move all that to the same folder with the Verge application in it?

**Comment by nkazier** [comment]
Yes, or if you made a backup you can just reload the backup file of your wallet

**Comment by jbutr8888** [comment]
I believe I did make the backup wallet and it's even showing 6:54 now last date modified so it's reading from that wallet. But it's still showing 0... I have no idea lol...

**Comment by nkazier** [comment]
Is your wallet synced?

**Comment by jbutr8888** [comment]
Yes. I even went to the website and downloaded the newest files or whatever to sync it faster... It's fully synced.

**Comment by jbutr8888** [comment]
I just moved all the files to one folder and dragged my wallet into the Verge app.. see what happens when it opens lol..

**Comment by nkazier** [comment]
Ok let us know, what build windows?

**Comment by jbutr8888** [comment]
Windows 10. It transferred fine last week, I thought nothing of it and then I just opened it yesterday and synced it and it's gone lol...

**Comment by jbutr8888** [comment]
It didn't work... I moved all the files into the verge folder, I started getting an error. So I moved it back out now it opens but still shows 0... I don't get what the hell happened... makes no sense.

**Comment by mikeuding** [comment]
It is in the chain so the transaction is not gone. It will popup someday

**Comment by jderwish** [comment]
@jbutr8888  You wallet is probably here C:\Users\[username]\AppData\Roaming\Verge\, go and backup the current wallet.dat and replace it with your backup wallet and restart the application.

**Comment by jbutr8888** [comment]
Ok so I see what you're talking about. I have the folder open and I see the Wallet.Dat file. It says date modified 1/4/18 because I downloaded the latest Verge.
So are you saying while my Verge application is open, Back up the wallet again and replace the one that is in that folder? Then re open the app?

**Comment by jderwish** [comment]
@jbutr8888  close your Verge application. Back up the wallet and replace the one with your wallet and re-open the wallet :-)

**Comment by jbutr8888** [comment]
I did what you said and it's still showing 0... what am I missssinggggggggg lol.. Like it's not even showing up in the transaction history anymore.. It's like it just disappeared I don't get it.

**Comment by jderwish** [comment]
sharing your screenshot ...your wallet is sync? can you confirm by issuing the getinfo command in the debug console

**Comment by jbutr8888** [comment]
"version" : "v2.1.0.0-unk-beta",
"protocolversion" : 90001,
"walletversion" : 60000,
"balance" : 0.00000000,
"newmint" : 0.00000000,
"stake" : 0.00000000,
"blocks" : 1775839,
"moneysupply" : 14431468839.99999619,
"connections" : 4,
"proxy" : "",
"ip" : "162.244.162.113",
"pow_algo_id" : 0,
"pow_algo" : "scrypt",
"difficulty" : 121976.13700264,
"difficulty_x17" : 10021.91515129,
"difficulty_scrypt" : 121976.13700264,
"difficulty_groestl" : 1433625.68902368,
"difficulty_lyra2re" : 95239.08461948,
"difficulty_blake" : 11871671.44155914,
"testnet" : false,
"keypoololdest" : 1513833271,
"keypoolsize" : 101,
"paytxfee" : 0.00000000,
"unlocked_until" : 0,
"errors" : ""
}

**Comment by jbutr8888** [comment]
Here's the link for when I transferred it

https://verge-blockchain.info/address/DSSqKQeqriRMra1WsLcU8iGQfnKK3rGcQf

**Comment by jbutr8888** [comment]
"version" : "v2.1.0.0-unk-beta",
"protocolversion" : 90001,
"walletversion" : 60000,
"balance" : 0.00000000,
"newmint" : 0.00000000,
"stake" : 0.00000000,
"blocks" : 1775839,
"moneysupply" : 14431468839.99999619,
"connections" : 4,
"proxy" : "",
"pow_algo_id" : 0,
"pow_algo" : "scrypt",
"difficulty" : 121976.13700264,
"difficulty_x17" : 10021.91515129,
"difficulty_scrypt" : 121976.13700264,
"difficulty_groestl" : 1433625.68902368,
"difficulty_lyra2re" : 95239.08461948,
"difficulty_blake" : 11871671.44155914,
"testnet" : false,
"keypoololdest" : 1513833271,
"keypoolsize" : 101,
"paytxfee" : 0.00000000,
"unlocked_until" : 0,
"errors" : ""
}

**Comment by jderwish** [comment]
Can you please confirm in the address tab that this is the correct wallet? Or you can type listaccounts in console and getbalance command

**Comment by jbutr8888** [comment]
They both come up 0000000... I know I transferred it here. I did it from Binance. I have the transaction info completed and everything and verified the address. I remember checking to even make sure it transferred. It wasnt until the following week when I opened up the wallet again and noticed it was gone...

**Comment by jderwish** [comment]
Is the wallet address same as the transactions goes?

**Comment by jderwish** [comment]
DSSqKQeqriRMra1WsLcU8iGQfnKK3rGcQf

**Comment by jbutr8888** [comment]
Address: DSSqKQeqriRMra1WsLcU8iGQfnKK3rGcQf

This is directly copied from Binance when I transferred it to the wallet.

**Comment by jderwish** [comment]
Check the wallet address by issue getaccounts or go to receiving address tab and confirm

**Comment by jbutr8888** [comment]
DSSqKQeqriRMra1WsLcU8iGQfnKK3rGcQf

Receiving address tab

**Comment by jderwish** [comment]
Ok how many connections to your wallet? It seems that perhaps not sync then. If you have the correct wallet then the coins are there

**Comment by jbutr8888** [comment]
right now it says 8. I watched it since from like 750 blocks earlier. I downloaded the newest update earlier so the interface is all blue now.

**Comment by jderwish** [comment]
Please go to go console and type getaccounts and getbalance

**Comment by jbutr8888** [comment]
getbalance

00:50:43
￼
0.00000000


00:50:56
￼
listaccounts


00:50:56
￼
{
"From Binance - Verge" : 0.00000000
}

**Comment by jderwish** [comment]
Can you share getaddresses

**Comment by jbutr8888** [comment]
It's not working. If you just want the address, this is it.. I am copying it directly from the receiving address tab.

DSSqKQeqriRMra1WsLcU8iGQfnKK3rGcQf

I'm telling you I am stumped lol

**Comment by jbutr8888** [comment]
super appreciate you even helping me try to figure this out btw. Thank you

**Comment by jderwish** [comment]
Ok I got to catch some sleep, I would suggest to leave it running for now, good news is that you have your wallet file and your coins are there, just matter of making sure that the program is sync and sees it.

**Comment by jderwish** [comment]
You can also send a test transfer of 1 coin to see if you receive it

**Comment by jderwish** [comment]
That's pushes blockchain db to update your wallet balance

**Comment by jbutr8888** [comment]
I will try that thank you!

**Comment by jbutr8888** [comment]
I sent more verge over, it transferred but the other 300 never came back... I'll leave it on see what happens.. thank you again for your help

**Comment by justinvforvendetta** [comment]
i would do a reindex, or just erase the blockchain data (except the wallet.dat) and sync it from scratch. should be fine. as long as you have the same receiving address in your receiving tab that you sent the coins to,  you should be fine.

**Comment by mike2lab** [comment]
i also send some XVG to the verge wallet and then i encrypted with a new passphrase.
My wallet isn't still synced. When you release the new wallet i'll be able to access my old receiveing address through that passphrase i have set?

**Comment by justinvforvendetta** [comment]
are you talking about an electrum wallet or something right now?

**Comment by Hakopako7** [comment]
dear dev team.
i have same issue.
at december 30th i transferred coins to my wallet, yesterday i sync my wallet and i see 0 balance.
i already try to replace wallet file and sent additional coins to my wallet. i see new coins, but i do not see coins which i send at 30th Dec.
Then i use electrum, i see both transfers and correct balance.
Please help.

**Comment by jbutr8888** [comment]
I've tried everything it still never came back. Verge can kiss it. I've tweeted them, DMed them, no help. They don't care.

**Comment by justinvforvendetta** [comment]
please stick with current wallet. pools will be updated by monday

**Comment by jbutr8888** [comment]
We'll see what happens... it's just weird how the whole transaction just disappeared completely.. I sent another one over a few days ago and that one shows but that's it... 

Happy SundayFundayyyyyyyyyyyyyyyy.

**Comment by justinvforvendetta** [comment]
you tried syncing from block 0 yourself like I suggested?

**Comment by jderwish** [comment]
@jbutr8888  try this steps - if you are using windows wallet -
1.  copy your wallet.dat over to another folder in case you delete it by mistake
2. Delete everything in C:\%Appdata%\VERGE folder except your wallet.dat
3. Open your Verge Wallet GUI
4. Let it sync from 0, it will take probably 2-3 days and you should be good to go.

**Comment by jbutr8888** [comment]
I will give it a shot and let you know. Thank you. Enjoy football!

**Comment by miladzol** [comment]
I'm having the same issue.....sent about 2000 verge to the wallet, but it isn't showing up.

**Comment by miladzol** [comment]
I sent it from electrum to the new verge wallet

**Comment by jbutr8888** [comment]
Yup I've tried everything.. It still never came back.. I tried everything. Every suggestion. It never came back.

**Comment by justinvforvendetta** [comment]
3.0 doesn't work anymore, but if you import the private key you sent it to, you can retrieve it easily.

**Comment by jbutr8888** [comment]
No you can't retrieve it easily.. I love how you closed this when there are multiple people in here with the same complaint I have.. Thanks for not helping. DON'T TRUST VERGE PEOPLE!

**Comment by justinvforvendetta** [comment]
if you can see coins on thr explorer on a public address and you have the private key to that address, yes, its easy.

**Comment by jbutr8888** [comment]
I've come to terms with it that it's long gone.. 

The transaction is even missing from the transaction log. It just disappeared shortly after I originally transferred it. No explanation. I never deleted the wallet I just reopened it a couple days later and it was gone.

I'm not the only one this has happened too.

**Comment by jderwish** [comment]
@justinvforvendetta Perhaps it is simple for you and other developers and perhaps technical people like myself. It would be beneficial to provide guidance or perhaps step by step instructions here and on your website so others with similar issues follow to fix it.

**Comment by justinvforvendetta** [comment]
sounds like you either got it back (if it was an unconfirmed tx) or it went thru.

**Comment by miladzol** [comment]
So my issue is a little different. I see it in verge exhange, the address it was sent to us correct. I just don’t see it on my verge wallet. It’s the latest version and block chain is all synced. I made the transaction on Jan 24th. Would the fork have anything to do with it? If so, is it just a wait and hopefully see it in my account eventually? Or is there something else I need to do. Thanks in advance for the help.

**Comment by jderwish** [comment]
@miladzol please read this thread and the answer is provided and I have provided instructions for you.

**Comment by miladzol** [comment]
@jderwish Thanks! So went into %appdata% then verge and deleted everything except the wallet.dat. Then opened verge qt and now it's syncing. I'll let you know how it goes. Cheers!
