### ISSUE TITLE
after transaction, remaining balance is pushed into txfee

### ISSUE THREAD

**Issue by justinvforvendetta** [vergecurrency/VERGE#178]

**Comment by adamdkiger** [comment]
It doesn't matter if you have the best software in the world. A man is nothing without his word. This is a matter of integrity...not money. You're about to learn a very valuable lesson. - Adam

**Comment by akramtariqkhan** [comment]
I am with you :) More power to you

**Comment by Innox-dev** [comment]
glad you found it!

**Comment by axeman50** [comment]
I just lost $1500 because I’m a noob trader, and I panic sold can I please have a tip, your richer enough. It’s change in your pocket really! 

D937HcC6c4E7RNeswA1cWCq3LXsGD5PZBS

**Comment by dnev1551** [comment]
just finish the damn thing, I don't judge, we all been late to the party.

**Comment by LouiseMensch** [comment]
this is the worst programming i've ever seen

**Comment by ignitioncoin** [comment]
Hi please check out ignition coin too 👯‍♂️

**Comment by amitshakya23** [comment]
take your time

**Comment by Sneakr** [comment]
Pump and dump incoming.

**Comment by jeffreylim17** [comment]
We'll support verge. We appreciate you working even though its new year's. 
We'd rather have this now than later. better foundation for such a great success.

**Comment by vjasterix** [comment]
Leave them alone guys. Theyve been pumping code hard all week and long hours.

**Comment by btk** [comment]
Remove this comment too.

**Comment by patient136667** [comment]
keep up the good work guys, i know bugs happen and best to fix it and be late than deliver on time with a prodect not 100% that people will only cry about anyways

**Comment by TheUltimateExplorer** [comment]
great efforts !!! we support you

**Comment by Sneakr** [comment]
What a coincidence , a whale pumps and dumps the same second this tweet and "bug" goes out :)

**Comment by ignitioncoin** [comment]
We are all watching the githoob for Ignition Coins https://ignitioncoin.org

**Comment by bmogali** [comment]
Appreciate all the effort ! Keep up the good work guys

**Comment by DomingoMontoya** [comment]
The problem with having a plan is that software doesn't care about your plans.

**Comment by daveAw** [comment]
Remember the Timezone difference plenty of time yet

Sent from my iPhone

On 1 Jan 2018, at 2:26 pm, Microchip™ <notifications@github.com<mailto:notifications@github.com>> wrote:


this is the worst programming i've ever seen

**Comment by CmplxStack** [comment]
Disregard these people, don't even waste your time. The product is amazing and everyone will be raving about it when released. Supporting all the way.

**Comment by Sneakr** [comment]
What a coincidence , a whale pumps and dumps the same second this tweet and "bug" goes out LOL

**Comment by FAME360** [comment]
Do your thing Justin.  Head down and focus; ignore the noise..

**Comment by akramtariqkhan** [comment]
Don't waste your time. Let trollers troll

**Comment by fr4ck** [comment]
Justin Let them be man!! Just focus!! You're the man! These guys have 0 respect for talented people like you! Bless you!

**Comment by fuckverge** [comment]
You just lost a lot of ppl a shitload of money. The whole team has been doxxed on 4chan. Expect us.

**Comment by LouiseMensch** [comment]
lol, every time the bounce happens, the Verge currency account Tweets, it's the best scam i've ever seen

**Comment by ignitioncoin** [comment]
We all love privacy coins with Master Node like Ignition <3 - https://bitcointalk.org/index.php?topic=2612608.0

**Comment by Sneakr** [comment]
What a coincidence , a whale pumps and dumps the same second this tweet and "bug" goes out LOL 💯

**Comment by LouiseMensch** [comment]
you don't see con artists this good very often, it's too good

**Comment by tlangdon123** [comment]
guys positivity only... let them finish the release rather than having to moderate the comments

**Comment by avneet-singh-ligo** [comment]
Babysitting comments now :D

**Comment by fuckverge** [comment]
Coming for you, justin

**Comment by FAME360** [comment]
Make me a moderator and I'll delete all of the garbage while you finish it up

**Comment by Sneakr** [comment]
What a coincidence , a whale pumps and dumps the same second this tweet and "bug" goes out LOL 💯

**Comment by ignitioncoin** [comment]
Very good project Verge new ANN dont miss!! https://bitcointalk.org/index.php?topic=2612608.0

**Comment by LouiseMensch** [comment]
we have a whole viewing party watching this train wreck from Gab.ai, and it's glorious

**Comment by daveAw** [comment]
Dude your forgetting about the time difference

Sent from my iPhone

On 1 Jan 2018, at 2:29 pm, fuckverge <notifications@github.com<mailto:notifications@github.com>> wrote:


Coming for you, justin

**Comment by anhdn** [comment]
Never give up. But fix it soon. We're waiting you! Good luck & happy new year!

**Comment by LouiseMensch** [comment]
i'm making you famous with the Trump campaign, Justin, it's perfect, the SEC will be all over you shortly, lmfao

**Comment by vozzurg** [comment]
Just do it!

**Comment by LouiseMensch** [comment]
this is the funniest thing i've ever seen in my entire life,

**Comment by Innox-dev** [comment]
STOP COMMENTING, LET THE JAMES FIX THE CODE. SO U CAN HAVE WHAT U WANT AND SHUT UP.

**Comment by RyanSellers1** [comment]
#TeamXVG I can't wait for Wraith!

**Comment by trismegistis** [comment]
We all love privacy coins with Master Node like Ignition <3 - https://bitcointalk.org/index.php?topic=2612608.0

**Comment by ivz23** [comment]
Agree, everyone needs to SHUT UP!!! STOP COMMENTING!

**Comment by TechniumUnlimited** [comment]
Best privacy coin is VERGE!!!  https://bitcointalk.org/index.php?topic=2612608.0 The future is coming WRAITH!!!

**Comment by tlangdon123** [comment]
close the issue then noone can comment on it

**Comment by zi-github** [comment]
You can do this!!! Just please keep reassuring us kindly from the verge currency tweets!

**Comment by andyreesecups** [comment]
You're killing me smalls.

**Comment by beasandeep** [comment]
It's not the matter of time. Elon Musk has missed his dead line for model 3 delivery by months. 
Will support verge no matter what.
All the haters get some life. Let the dev's fix the code

**Comment by huynhhb** [comment]
We're all behind you - good luck!

**Comment by YeshwanthS** [comment]
Finding the root cause is half fix done!!

**Comment by stolve** [comment]
When did people start using github like facebook?

**Comment by waqasrajab** [comment]
We are all behind you guys, keep going.... Any ideas on how complicated the fix is?

**Comment by LunarVerge** [comment]
I got everything in this coin, come on boys, behind you 100%

**Comment by patient136667** [comment]
id rather be late to a party than not arrive at all, take the time needed to get it right man

**Comment by RomHtK** [comment]
Take your time, ppl are crazy

**Comment by jaythree03** [comment]
don't focus on deleting the comments here. just finish everything.

**Comment by satrya-sabeni** [comment]
I truly believe in you guys. I know you guys will pull it off, I believe!

**Comment by WansonSwanson** [comment]
Deleting comments is more important than working on the project, brilliant.

**Comment by axeman50** [comment]
I’ve lost everything because of this!

**Comment by Foristkirito** [comment]
I'm ready for the party, come on guys!

**Comment by deke997** [comment]
I found something in main.cpp that may be pertinent:

if (!MoneyRange(nMinFee))
        nMinFee = MAX_MONEY;
    return nMinFee;

**Comment by daveAw** [comment]
Then hodl

Sent from my iPhone

On 1 Jan 2018, at 2:36 pm, axeman50 <notifications@github.com<mailto:notifications@github.com>> wrote:


I’ve lost everything because of this!

**Comment by rdvs** [comment]
You found it and I know you will fix it soon. 👍

**Comment by designcise** [comment]
i hope you've tried comparing to code from previous build where it worked fine.

**Comment by Nadim96** [comment]
happy new year everyone

**Comment by schanel10** [comment]
I am massive supporter of Verge. Every company has good and bad press, however deleting comments just makes it look like you have something to hide..

**Comment by justinvforvendetta** [comment]
{
"txid" : "c45966f8870756a1dfe934d1f3739ad8287d9ddc9900448e20b1e516784cfa02",
"version" : 1,
"time" : 1514787560,
"locktime" : 0,
"vin" : [
{
"txid" : "93957b6c0e5538e89e58d9f5a435d6bc521e252e3a8918437ae807c653d0b5e9",
"vout" : 0,
"scriptSig" : {
"asm" : "3045022100a0e1b7605429e12b89041e36208824e35cf1feb49a51d7f874e8c52eb3fda07f022005850e90d99784022665a2c0c2f0b1f36bee29aa911a860c7399a488cdcdc78601 024aa6014490d5a12ebab9801411e7b4190c4ad5f2f8568f74dea194845a84811d",
"hex" : "483045022100a0e1b7605429e12b89041e36208824e35cf1feb49a51d7f874e8c52eb3fda07f022005850e90d99784022665a2c0c2f0b1f36bee29aa911a860c7399a488cdcdc7860121024aa6014490d5a12ebab9801411e7b4190c4ad5f2f8568f74dea194845a84811d"
},
"sequence" : 4294967295
}
],
"vout" : [
{
"value" : 2.70000000,
"n" : 0,
"scriptPubKey" : {
"asm" : "OP_DUP OP_HASH160 5d08b68adf03974689b34282d8f237fa09780430 OP_EQUALVERIFY OP_CHECKSIG",
"hex" : "76a9145d08b68adf03974689b34282d8f237fa0978043088ac",
"reqSigs" : 1,
"type" : "pubkeyhash",
"addresses" : [
"DDd1pVWr8PPAw1z7DRwoUW6maWh5SsnCcp"
]
}
}
],
"amount" : -2.70000000,
"fee" : -2.30000000,
"confirmations" : 35,
"blockhash" : "4a6ff8b343eeaf04fd0ca1aad530d497b7fb2eca88c432e2dae5b3c4c0125cc8",
"blockindex" : 21,
"blocktime" : 1514787754,
"txid" : "c45966f8870756a1dfe934d1f3739ad8287d9ddc9900448e20b1e516784cfa02",
"time" : 1514787560,
"timereceived" : 1514787560,
"details" : [
{
"account" : "",
"address" : "DDd1pVWr8PPAw1z7DRwoUW6maWh5SsnCcp",
"category" : "send",
"amount" : -2.70000000,
"fee" : -2.30000000
}
]
}

**Comment by bonchien** [comment]
Omg get over yourself

**Comment by Aechie** [comment]
You can do it Justin we trust in you!

**Comment by easye85** [comment]
You got this Justin

**Comment by c0d3phined** [comment]
@schanel10 this is a place to comment on code.  not casual chitchat

**Comment by justinvforvendetta** [comment]
wallet balance of 5, sending 2.7, remaining 2.3 are swept into transaction fee.

**Comment by isimanovich** [comment]
is it still same fees .cpp that you guys were trying to fix before?

**Comment by justincredibleg** [comment]
That's not ideal

**Comment by designcise** [comment]
@justinvforvendetta txfee is being calculated in main.cpp?

**Comment by Sourpusss** [comment]
as @deke997 said:

if (!MoneyRange(nMinFee))
nMinFee = MAX_MONEY;
return nMinFee;

the logic seems like it would cause the issue

**Comment by OrwellWasRight** [comment]
Someone please tip me :) need moar verge to hodl before the wraith :) 
DU5LTJD74ZNsLt4QXKKxAQHFY8JkMqyH9b

**Comment by jaythree03** [comment]
post the code snippet that you are trying to fix. we will help you.

**Comment by Aechie** [comment]
Yeah let us help you if we can.

**Comment by chk-m8** [comment]
Send it on over...even the file.

**Comment by dracko22** [comment]
Why did you remove the use of nTransactionFee?

**Comment by Nadim96** [comment]
ye losing 50% verge isnt ideal haha send the file

**Comment by Innox-dev** [comment]
can we merge this snippet with the bitcoin code?

**Comment by Jdlammer** [comment]
Yikes these comments aren't lookin good. Good luck

**Comment by amxre** [comment]
Keep up the good work, we believe in you.

**Comment by nkazier** [comment]
Same issue as seen in #153

**Comment by donhortega** [comment]
please if you have an excess of philanthropy give me xvg :) (I am a student)
DEEFgry9VsXnF9hQ11d3mvLe9FEg3SU3QF

**Comment by cryptodoctor1** [comment]
https://github.com/justinvforvendetta can you fix this issue buddy?

**Comment by CryptoGiant** [comment]
Every second moderating haters (free speech) is a second you're distracted from your end goal.  Eyes on the prize.  Keep up the good work.

**Comment by samupra** [comment]
I love this coin but this is very unprofessional.

**Comment by blindndumb** [comment]
This has something to do with the issue. Please check @justinvforvendetta 
File: main.cpp

```
// Raise the price as the block approaches full
    if (nBlockSize != 1 && nNewBlockSize >= MAX_BLOCK_SIZE_GEN/2)
    {
        if (nNewBlockSize >= MAX_BLOCK_SIZE_GEN)
            return MAX_MONEY;
        nMinFee *= MAX_BLOCK_SIZE_GEN / (MAX_BLOCK_SIZE_GEN - nNewBlockSize);
    }

    if (!MoneyRange(nMinFee))
        nMinFee = MAX_MONEY;
    return nMinFee;
```

**Comment by RHoytDesign** [comment]
Glad to see all the positive words, but keep in mind, comments on Issues in GitHub are meant to be about the Issue at hand between those working on it.

**Comment by designcise** [comment]
in wallet.cpp: could this be it: ```nFee = nDebit - nValueOut;```

**Comment by sohum2002** [comment]
Better release a great product with a small delay rather than a crappy product on time. In the big scale of things, 2 hours doesn't mean anything

**Comment by samupra** [comment]
just updated his status! (Oh wait I thought this is FB!)

**Comment by justinvforvendetta** [comment]
no i dont believe that does. im looking more towards this:

https://github.com/vergecurrency/VERGE/blob/master/src/wallet.cpp#L1502

**Comment by describeme** [comment]
Great job u guys, as a c0der I know exactly what u just went through! Most Ppl don't know how much effort is being put into this, Happy new year!

**Comment by samupra** [comment]
@describeme what exactly is a c0der? C zero der?

**Comment by justinvforvendetta** [comment]
compute fee seems to be fine in wallet.cpp, im looking down further around 1502

**Comment by dracko22** [comment]
you do move that into nFeeRet += nMoveToFee;

**Comment by sohum2002** [comment]
@justinvforvendetta we believe in you

**Comment by sovietmah** [comment]
I just wonder if we can put unit test into cpp?

**Comment by akramtariqkhan** [comment]
@justinvforvendetta - Please don't delete comments. Wastage of time.

**Comment by deke997** [comment]
I also found this is wallet.cpp which may be pertinent

    // Compute fee:
    int64 nDebit = GetDebit();
    if (nDebit > 0) // debit>0 means we signed/sent this transaction
    {
        int64 nValueOut = GetValueOut();
        nFee = nDebit - nValueOut;
    }

**Comment by nidal2017** [comment]
"I've always found that anything worth achieving will always have obstacles in the way and you've got to have that drive and determination to overcome those obstacles on route to whatever it is that you want to accomplish." Chuck Norris

**Comment by designcise** [comment]
@justinvforvendetta so everything prior to `CreateTransaction()` method gives the correct fee? have you been able to narrow down the precise method that's miscalculating?

**Comment by sohum2002** [comment]
Hey @justinvforvendetta, please read this when you have time: https://stackify.com/unit-testing-basics-best-practices/

**Comment by CakeRepository** [comment]
Where are fees being applied?

**Comment by isimanovich** [comment]
@dracko22 i think, you are close. 
nFeeRet = 0.01*COIN;
...
nFeeRet += nMoveToFee;

**Comment by numsu** [comment]
Comparing to shadowcoin's implementation (where @ahmedbodi mostly copied the implementation) these are the lines that have been added and cant be found in their https://github.com/shadowproject/shadow/blob/master/src/wallet.cpp

```
                // ppcoin: sub-cent change is moved to fee
                if (nChange > 0 && nChange < MIN_TXOUT_AMOUNT)
                {
                    nFeeRet += nChange;
                    nChange = 0;
                }
```

**Comment by b3stn4me3ver** [comment]
Keep it up bro! Much love! Preciate your hard work!

**Comment by isimanovich** [comment]
@numsu these are to add leftovers in cents to transaction fee

**Comment by justinvforvendetta** [comment]
ha fixed.

**Comment by NorthropGuru** [comment]
// ppcoin: sub-cent change is moved to fee
                if (nChange > 0 && nChange < MIN_TXOUT_AMOUNT)
                {
                    nFeeRet += nMoveToFee;
                    nChange = 0;
                }

**Comment by lolverge** [comment]
Thought it was all ready to go? You fucking con artist. I should have listened to all the FUD #ScamCoin
