### ISSUE TITLE
Your fucker admin of telegram aka GrandPriest is banning people i showed that indian cunt that he was doing wrong.

### ISSUE THREAD

**Issue by h4rpreet** [vergecurrency/VERGE#180]
I am pretty  much sure i won't get unban but i just wanted to get this into your attention that that cunt motherfucker indian admin ( grandpriest) is banning cause i am an indian and i told him not to lure people wrong info. To him: I am an indian as well, motherfucker give me your number and i'll tell you who i am in real life. If i won't reach you at your mom and slap your mom for giving you birth, i am not my dad's son.

I am already in group with different id but fuck his mom and dad, i hope they die.

**Comment by Thundercock** [comment]
sxvge

**Comment by ernesthilvano** [comment]
lol. this. idieded.

**Comment by IndianSlapper** [comment]
h4rpreet - I'm your huckleberry....  Come slap me...

**Comment by tobiwin** [comment]
You are a best example that the admin makes his job very well. Do you want to talk about Mom's now?

**Comment by r7avi** [comment]
lol, clam down

**Comment by Adam-G-Harris** [comment]
im. dead.

**Comment by h4rpreet** [comment]
SOmeone asked should i invest my rent money into it, i told him you should not do it. That this cunt indian admin came (grandpriest) and told him something that if you will not do it you "xvz" i forgot. I told him you you are shittest person i have seen to suggest him to invest his rent money, we had a fight. By chance this indian cunt was an indian and moment from the very moment he kept on sayin "you wait, u will get ban" yea, sure you cunt, my life ended by you banning me. But i want to show how cant he is, i am already in group with different id, hold my dick and dance now.
