### ISSUE TITLE
Release Before 2018 ? & We are already in 2018 & Still waiting! Great 

### ISSUE THREAD

**Issue by r7avi** [vergecurrency/VERGE#182]
If you are planning to release something on date, you need to build it before telling the whole world that its comming,  
now it seems like now u r practicing swords to fight war,  which is about to start delayed due to practicing ?

**Comment by r7avi** [comment]
okay, for serious,
im using electrum XVG 2.4.1 but it never get connect and not showing balance 👎

**Comment by justinvforvendetta** [comment]
@r7avi and you tried other servers? like the ones we tweeted the other day on twitter.com/vergecurrency? everyone else's seems to be working fine. the default servers have been filling up with users and cant always handle new incoming connections

**Comment by Foristkirito** [comment]
when to release? are you still building it?

**Comment by Foristkirito** [comment]
It's waste of time

**Comment by nkazier** [comment]
See #12 in the electrum wallet, that will dove ur connection issue

**Comment by r7avi** [comment]
Thanks ,
e2.verge-electrum.com:50003 working for me 😊

**Comment by nkazier** [comment]
Awesome, yeah if u posted that question on the electrum wallet side the 12 would have brought you right there, sorry if my response was confusing, this can be closed @justinvforvendetta
