### ISSUE TITLE
VVraith Release 2 Mac OSX crashing on launch

### ISSUE THREAD

**Issue by jpnehring** [vergecurrency/VERGE#183]
Copied the error the application spits out, hopefully this helps

Process:               VERGE-Qt [59905]
Path:                  /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
Identifier:            com.vergecurrency.VERGE-Qt
Version:               2.1.0 (2.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VERGE-Qt [59905]
User ID:               501

Date/Time:             2018-01-01 02:41:44.785 -0500
OS Version:            Mac OS X 10.13.2 (17C88)
Report Version:        12
Anonymous UUID:        B90C3BDB-FF05-F2D0-D66E-86920B153E84

Sleep/Wake UUID:       556FE40D-B830-4A07-B473-9A12536022AC

Time Awake Since Boot: 470000 seconds
Time Since Wake:       300 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x10ea9d000 -        0x10f1caff7 +com.vergecurrency.VERGE-Qt (2.1.0 - 2.1.0) <5EBCFD6F-D5DC-3276-80F4-F8FA95BB8C17> /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
       0x10f26a000 -        0x10f26cff7 +libboost_system.dylib (0) <571C7888-D10F-3CB1-8DDB-460887DC314C> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x10f274000 -        0x10f281fff +libboost_filesystem.dylib (0) <A742D64A-E278-3C8E-954A-D7C836ED6B53> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x10f28d000 -        0x10f2bdfff +libboost_program_options-mt.dylib (0) <78525B93-6E1C-3BD8-89A4-2FADABACDD56> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x10f2df000 -        0x10f2edfff +libboost_thread-mt.dylib (0) <5BF9428B-F1C9-3CDE-B970-C17A41415A36> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x10f2fd000 -        0x10f2ffff7 +libboost_chrono-mt.dylib (0) <1BF07246-8624-3109-8030-F23357EA1F37> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x10f302000 -        0x10f80dfff +QtWidgets (5.5.1) <416CBC52-D42C-3996-B338-C848863E65B0> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10f946000 -        0x10fdcafff +QtGui (5.5.1) <217B896F-895F-3DEC-BF29-01E065492858> /Applications/VERGE-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10fea7000 -        0x1103aefff +QtCore (5.5.1) <201F9A70-4676-3BC5-8B59-82DA94559272> /Applications/VERGE-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x11043e000 -        0x11054bff7 +QtNetwork (5.5.1) <CC4ADD9F-E8C7-3618-9D83-7DBF9AC4267A> /Applications/VERGE-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x110585000 -        0x111fc7fff +QtWebKit (5.5.1) <693CF012-F937-3DB1-A6A9-05BB6DA6FE69> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWebKit.framework/Versions/5/QtWebKit
       0x11225f000 -        0x11228dff7 +QtWebKitWidgets (5.5.1) <84451F1E-1CE1-3A7D-9CB9-BD686BA98B92> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWebKitWidgets.framework/Versions/5/QtWebKitWidgets
       0x1122b2000 -        0x112315ff7 +QtDBus (5.5.1) <B0B9AE70-B993-3081-9336-E01BD1233823> /Applications/VERGE-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x11232e000 -        0x112334fff +libqrencode.4.dylib (0) <5B7DEE75-603E-351D-B14C-21663CD470BC> /Applications/VERGE-Qt.app/Contents/Frameworks/libqrencode.4.dylib
       0x11233f000 -        0x112471ff7 +libprotobuf.15.dylib (0) <6300475A-5FB2-39C0-AE54-644CFAC18091> /Applications/VERGE-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x112521000 -        0x112645ff7 +libdb_cxx-4.8.dylib (0) <893E0F96-1F8A-3073-B1CF-CC60610C3E90> /Applications/VERGE-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x11267f000 -        0x112687ff3 +libminiupnpc.16.dylib (0) <C103607F-F06C-34D6-A60A-27E9E344F015> /Applications/VERGE-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x11268b000 -        0x1126ccfff +libssl.1.0.0.dylib (0) <3C28C2A8-036B-34B3-82BB-5780DB7271B2> /Applications/VERGE-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x1126e9000 -        0x112859c87 +libcrypto.1.0.0.dylib (0) <1C6D06DA-0F88-37BA-80E9-52C4AC7E942C> /Applications/VERGE-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x11dfde000 -        0x11e02898f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
    0x7fff3252b000 -     0x7fff3252fffb  com.apple.agl (3.3.1 - AGL-3.3.1) <5A110DE6-3EE7-343B-95FE-9642517D1B64> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff3390b000 -     0x7fff34768fff  com.apple.AppKit (6.9 - 1561.20.106) <7A71ACCF-2DF5-3557-BB22-3A9FC9F71CCF> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff347ba000 -     0x7fff347bafff  com.apple.ApplicationServices (48 - 50) <7627DBD6-497B-3AB7-9B63-F0532EDF09B8> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff362e5000 -     0x7fff36785fff  com.apple.CoreFoundation (6.9 - 1450.16) <23F8373A-FA3F-37A2-BA5B-70061BFCCD21> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff37444000 -     0x7fff37444fff  com.apple.CoreServices (822.19 - 822.19) <0C60B639-4CC4-3F57-BC5E-DB71EB75F7F4> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff38263000 -     0x7fff38268fff  com.apple.DiskArbitration (2.7 - 2.7) <44836CE9-A9ED-3017-972A-7A0A3D6B472B> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff38429000 -     0x7fff387eefff  com.apple.Foundation (6.9 - 1450.16) <7FEC6610-70EA-3A8D-8EC4-7E99BAF1E312> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff38b03000 -     0x7fff38b9efff  com.apple.framework.IOKit (2.0.2 - 1445.31.1) <7556086A-EFAF-3262-9822-6F666CFC6655> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff405e8000 -     0x7fff405f6ffb  com.apple.opengl (16.4.2 - 16.4.2) <C8C31EF5-8DB4-336F-A87C-5D520C7EFDC5> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff5b4a3000 -     0x7fff5b4d6fff  libclosured.dylib (519.2.2) <48051216-5647-3643-B979-B77D0FD20011> /usr/lib/closure/libclosured.dylib
    0x7fff5b9b5000 -     0x7fff5b9b6ff3  libSystem.B.dylib (1252) <5EDEEA85-0387-31EE-9D9B-DA1B75E7AEF3> /usr/lib/libSystem.B.dylib
    0x7fff5bbe9000 -     0x7fff5bc3ffff  libc++.1.dylib (400.9) <FCF5E1F6-2B04-3545-8004-F3AB32FED172> /usr/lib/libc++.1.dylib
    0x7fff5bc40000 -     0x7fff5bc64ff7  libc++abi.dylib (400.7) <217656D5-BC40-37FF-B322-91CB2AAD4F34> /usr/lib/libc++abi.dylib
    0x7fff5cfb6000 -     0x7fff5d3a47e7  libobjc.A.dylib (723) <93A92316-DE1E-378C-8891-99720B50D075> /usr/lib/libobjc.A.dylib
    0x7fff5da51000 -     0x7fff5da55ff7  libcache.dylib (80) <354F3B7D-404E-3398-9EBF-65CA2CE65211> /usr/lib/system/libcache.dylib
    0x7fff5da56000 -     0x7fff5da60ff3  libcommonCrypto.dylib (60118.30.2) <674286D3-7744-36A3-9AAA-49DFCD97A986> /usr/lib/system/libcommonCrypto.dylib
    0x7fff5da61000 -     0x7fff5da68fff  libcompiler_rt.dylib (62) <4487CFBA-A5D7-3282-9E6B-94CAD7BE507E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff5da69000 -     0x7fff5da71ffb  libcopyfile.dylib (146.30.2) <2C7C67D7-562B-3FFA-973D-BACF4C10E1EC> /usr/lib/system/libcopyfile.dylib
    0x7fff5da72000 -     0x7fff5daf7fff  libcorecrypto.dylib (562.30.10) <8A53EFE1-AFCA-3676-BEE1-FA5ED9F0E222> /usr/lib/system/libcorecrypto.dylib
    0x7fff5db7f000 -     0x7fff5dbb8ff7  libdispatch.dylib (913.30.4) <7D0E3183-282B-3FEE-A734-2C0ADC092084> /usr/lib/system/libdispatch.dylib
    0x7fff5dbb9000 -     0x7fff5dbd6ff7  libdyld.dylib (519.2.2) <C50D02BC-A333-3313-B787-02F255A6783F> /usr/lib/system/libdyld.dylib
    0x7fff5dbd7000 -     0x7fff5dbd7ffb  libkeymgr.dylib (28) <6D84A96F-C65B-38EC-BDB5-21FD2C97E7B2> /usr/lib/system/libkeymgr.dylib
    0x7fff5dbe5000 -     0x7fff5dbe5ff7  liblaunch.dylib (1205.30.29) <E66F58ED-C15E-3DFB-BC22-A861E13918C6> /usr/lib/system/liblaunch.dylib
    0x7fff5dbe6000 -     0x7fff5dbeaffb  libmacho.dylib (900.0.1) <756F2553-07B6-3B42-ACEA-2F0F1A5E8D0F> /usr/lib/system/libmacho.dylib
    0x7fff5dbeb000 -     0x7fff5dbedff3  libquarantine.dylib (86) <6AC8773F-3817-3D82-99C2-01BABB9C3CBB> /usr/lib/system/libquarantine.dylib
    0x7fff5dbee000 -     0x7fff5dbefff3  libremovefile.dylib (45) <912FA211-DD8C-3C92-8424-21B89F8B10FD> /usr/lib/system/libremovefile.dylib
    0x7fff5dbf0000 -     0x7fff5dc07fff  libsystem_asl.dylib (356.1.1) <94972913-9DF0-3C78-847C-43E58919E3DA> /usr/lib/system/libsystem_asl.dylib
    0x7fff5dc08000 -     0x7fff5dc08fff  libsystem_blocks.dylib (67) <F2493BB5-B1C6-3C4D-9F1F-1B402E0F1DB7> /usr/lib/system/libsystem_blocks.dylib
    0x7fff5dc09000 -     0x7fff5dc92ff7  libsystem_c.dylib (1244.30.3) <E0136C71-0648-36F0-9F84-82EA2748A8D7> /usr/lib/system/libsystem_c.dylib
    0x7fff5dc93000 -     0x7fff5dc96ffb  libsystem_configuration.dylib (963.30.1) <0F8D0B76-4F7D-34EC-AB6C-50F9465809DA> /usr/lib/system/libsystem_configuration.dylib
    0x7fff5dc97000 -     0x7fff5dc9affb  libsystem_coreservices.dylib (51) <21A488D0-2D07-344E-8631-CC8B2A246F35> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff5dc9b000 -     0x7fff5dc9cfff  libsystem_darwin.dylib (1244.30.3) <2F750CB1-BC26-3FA3-AE59-553EE30D451B> /usr/lib/system/libsystem_darwin.dylib
    0x7fff5dc9d000 -     0x7fff5dca3ff7  libsystem_dnssd.dylib (878.30.4) <EB9BB165-45A4-367C-B33A-688D4F383A95> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff5dca4000 -     0x7fff5dcedff7  libsystem_info.dylib (517.30.1) <7D79E167-4B5C-3833-81EE-3AF3FB53616D> /usr/lib/system/libsystem_info.dylib
    0x7fff5dcee000 -     0x7fff5dd13ff7  libsystem_kernel.dylib (4570.31.3) <D2E842AA-3B8D-31BF-8234-8C1BE11CFE32> /usr/lib/system/libsystem_kernel.dylib
    0x7fff5dd14000 -     0x7fff5dd5ffcb  libsystem_m.dylib (3146) <ABB1B85F-9FFE-31B8-AD4F-E39A30794A93> /usr/lib/system/libsystem_m.dylib
    0x7fff5dd60000 -     0x7fff5dd7ffff  libsystem_malloc.dylib (140.1.1) <9F0745FF-B92F-330D-8812-BB74001D1D33> /usr/lib/system/libsystem_malloc.dylib
    0x7fff5dd80000 -     0x7fff5de24ff3  libsystem_network.dylib (1229.30.11) <40BAD301-8744-3AD8-A688-E7925C587B00> /usr/lib/system/libsystem_network.dylib
    0x7fff5de25000 -     0x7fff5de2fffb  libsystem_networkextension.dylib (767.30.7) <C5ED4BAB-2480-369D-8AB6-DFB37C15A1EE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff5de30000 -     0x7fff5de39ff3  libsystem_notify.dylib (172) <98EA3D62-7C86-30DE-8261-D020D2F1EFF3> /usr/lib/system/libsystem_notify.dylib
    0x7fff5de3a000 -     0x7fff5de41ff7  libsystem_platform.dylib (161.20.1) <C049250F-8C35-314D-810F-4E28AEAED983> /usr/lib/system/libsystem_platform.dylib
    0x7fff5de42000 -     0x7fff5de4dfff  libsystem_pthread.dylib (301.30.1) <ABA848E1-6978-3B42-A3A7-608B2C36FA93> /usr/lib/system/libsystem_pthread.dylib
    0x7fff5de4e000 -     0x7fff5de51ff3  libsystem_sandbox.dylib (765.30.4) <A51828BA-26D8-3205-AF3A-DF5C37269468> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff5de52000 -     0x7fff5de53ff3  libsystem_secinit.dylib (30) <F06ADB8F-9E94-34A7-B3C9-2C22FDD14BAD> /usr/lib/system/libsystem_secinit.dylib
    0x7fff5de54000 -     0x7fff5de5bff7  libsystem_symptoms.dylib (820.30.7) <DC3586C2-AA56-3419-88D3-FC0DBF08E3C0> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff5de5c000 -     0x7fff5de6fff7  libsystem_trace.dylib (829.30.14) <69EBF017-D40F-30D7-9B0B-BFC862D761A5> /usr/lib/system/libsystem_trace.dylib
    0x7fff5de71000 -     0x7fff5de76ff7  libunwind.dylib (35.3) <6D4FCD49-D2A9-3233-95C7-A7635CE265F2> /usr/lib/system/libunwind.dylib
    0x7fff5de77000 -     0x7fff5dea3ff7  libxpc.dylib (1205.30.29) <F7E5F1BC-614B-39CB-B6CE-92A9C7B7EC0B> /usr/lib/system/libxpc.dylib

Model: MacBookPro11,5, BootROM MBP114.0177.B00, 4 processors, Intel Core i7, 2.5 GHz, 16 GB, SMC 2.30f2
Graphics: AMD Radeon R9 M370X, AMD Radeon R9 M370X, PCIe, 2 GB
Graphics: Intel Iris Pro, Intel Iris Pro, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x802C, 0x31364B544631473634485A2D314736453120
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x152), Broadcom BCM43xx 1.0 (7.77.37.5.1a3)
Bluetooth: Version 6.0.2f2, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Ultra Fit
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

**Comment by Eye-Poker** [comment]
I'm sure you saw this was already posted.

**Comment by soonlar** [comment]
this is a dup of #181
https://github.com/vergecurrency/VERGE/issues/181

**Comment by sweetone1** [comment]
where is the windows version?

**Comment by jpnehring** [comment]
Whoops my mistake, did not see the other post.
