### ISSUE TITLE
move stealth transactions into GUI

### ISSUE THREAD

**Issue by justinvforvendetta** [vergecurrency/VERGE#184]
right now, users need to go into help/debug/console and type getnewstealthaddress to receive a new stealth address, and sendtostealthaddress to send out. lets move that into send/receive pages on the GUI asap and push another release.

**Comment by jrsikors** [comment]
@justinvforvendetta is this still open?

**Comment by Positivism** [comment]
No, you can close this.

**Comment by jrsikors** [comment]
thanks
