### ISSUE TITLE
Out of sync

### ISSUE THREAD

**Issue by akramtariqkhan** [vergecurrency/VERGE#185]
Network stuck at out of sync. Doesn't update. Sync. with network doesn't start. Some issue with blockchain syncing?

**Comment by akramtariqkhan** [comment]
![screen shot 2018-01-01 at 1 54 01 pm](https://user-images.githubusercontent.com/16581630/34466494-4c789b76-eefb-11e7-94f3-08b6e09bb2dd.png)

**Comment by justinvforvendetta** [comment]
just let it sync
