### ISSUE TITLE
Stealth Address Disappears from Wallet List after closing and reopening app

### ISSUE THREAD

**Issue by vvillait88** [vergecurrency/VERGE#186]
Not sure if it's supposed to do this @justinvforvendetta but wanted to make you aware either way.

Occurs on Mac OS X 10.13

**Comment by akramtariqkhan** [comment]
@vvillait88  - My wallet does not sync with network, are you facing the same issue?

**Comment by sciack76** [comment]
it syncs perfectly

**Comment by revtex** [comment]
I am seeing the same, stealth wallet disappears in Mac client

**Comment by vvillait88** [comment]
@akramtariqkhan can you delete your comment, this has nothing do with the issue this is open for

**Comment by pasrom** [comment]
Same behavior here.
Mac OS X 10.13.2 and Ubuntu 16.04.3 LTS xenial

**Comment by infopirate** [comment]
I got something even weirder. My stealth address changed & shortened. I also have video. https://youtu.be/eDpPSTUrmHU

**Comment by ananjaser1211** [comment]
Similar problem on Linux Wallet. Stealth address goes away. perhaps because it was generated through console getnewstealthaddress
Since Issue #184 problem where you cant generate Stealth address directly from UI

**Comment by ErvinSabic** [comment]
Super stealthy wallet it seems. lol

**Comment by justinvforvendetta** [comment]
this was fixed today.
