### ISSUE TITLE
Network out of sync

### ISSUE THREAD

**Issue by akramtariqkhan** [vergecurrency/VERGE#187]
Network does not sync. Issue with blockchain syncing. Answer me, deleting the issue is not professional.
![screen shot 2018-01-01 at 1 54 01 pm](https://user-images.githubusercontent.com/16581630/34466508-fc39c83c-eefb-11e7-8552-38e464c2f040.png)

**Comment by kitkat14** [comment]
it took me a while but I am now connected to one connection. So I think this one can be closed ?

**Comment by justinvforvendetta** [comment]
i did not delete the issue, you can still comment in it. i said "let it sync".

**Comment by nkazier** [comment]
Your screen shot shows “syncing with network” I would wait a few min and verify to see if it’s downloading. It synced for me no problem.

**Comment by kitkat14** [comment]
![snip20180101_4](https://user-images.githubusercontent.com/7466866/34466515-c15943a2-eed6-11e7-9779-ed932f6cc330.png)

just quick screenshot for OP
