### ISSUE TITLE
Network does not sync

### ISSUE THREAD

**Issue by akramtariqkhan** [vergecurrency/VERGE#188]
Network does not sync
![screen shot 2018-01-01 at 1 54 01 pm](https://user-images.githubusercontent.com/16581630/34466513-45223534-eefc-11e7-8a6f-3820c94b0062.png)

**Comment by nkazier** [comment]
See issue #185

**Comment by hestko** [comment]
Why do you keep posting the same non-issue. Justin answered you twice now: Let it sync :)

**Comment by satrya-sabeni** [comment]
lol

**Comment by justinvforvendetta** [comment]
can you please stop opening multiple issues for the same thing thats been solved? you can still comment in the previous issue also.
