### ISSUE TITLE
4.0 Wallet - Unlock with passphrase issue

### ISSUE THREAD

**Issue by dbriggsie** [vergecurrency/VERGE#189]
If Wallet is locked, and you try unlocking the wallet with passphrase, it won't unlock.
But if you click change passphrase and put in your passphrase to change it, it does work.

Note: Im not putting in the wrong passphrase, as it works when i paste the same Passphrase into "Change Passphrase" Fields

**Comment by Bdom25** [comment]
Can confirm this happens to me too.

**Comment by swiftaes** [comment]
this is also happening for me

**Comment by bmickov** [comment]
I can confirm this to. I also noticed that it shows an alert that the passphrase is wrong, but if you typed it right the wallet will unlock.

**Comment by sweetone1** [comment]
in 3.0 this happen to me.

**Comment by marpme** [comment]
I made a short video description about it:

https://streamable.com/qun2m

**Comment by Dani3lSun** [comment]
Same issue for me.
Unlocking the wallet fails, but changing the password works...

**Comment by Smiles4miles** [comment]
I had all of these same problems. Then yesterday when i went to make my 5th transaction it wouldn't unlock for me. If I enter the correct password it acts as though it is accepted, then if I press send it asks me again for my password. If I enter the wrong password it tells me so right away. I know the password is correct.

**Comment by Smiles4miles** [comment]
I am using the windows qt wallet 4.0

**Comment by bmickov** [comment]
I can confirm that this is resolved, I compiled a build with the latest updates. Expect an update from the developers and a new release very soon, or if you are in a hurry compile the newer version yourself.

**Comment by polyfonik** [comment]
This is happening to me on osx version

**Comment by alexkenley** [comment]
I had the problem in the windows 4.0 wallet so I left it hoping 4.0.1 would fix but I still cannot unlock my wallet. I had spaces between the words... would that make a difference?

**Comment by Influence2** [comment]
@dbriggsie @alexkenley Have you updated to the latest wallet and has this issue been resolved? If so please close this issue.

**Comment by jrsikors** [comment]
@justinvforvendetta  close this issue plz
