### ISSUE TITLE
Manually loading Blockchain on OSX causes App to hang on launch

### ISSUE THREAD

**Issue by dbtftw** [vergecurrency/VERGE#192]
Hi all, 

When trying to load the Blockchain manually i am seeing a aHang on launch of the latest vvraith build on 10.13.2

REPRO: 
1. QuitQT-Verge
2* Download blockchain from -- https://verge-blockchain.com/blockchain/Wallet_v3.0_Verge-Blockchain_2017-December-30.zip
3* Follow install guide to a copy into App support -- https://drive.google.com/file/d/1KxIfooNfgRIghWXvndeyQFkz6bD9yOVr/view
4* Launch QT Verge

I took a sample and captured Syslog
[Sample of VERGE-Qt.txt](https://github.com/vergecurrency/VERGE/files/1595814/Sample.of.VERGE-Qt.txt)
[Verge_syslog.txt](https://github.com/vergecurrency/VERGE/files/1595815/Verge_syslog.txt)
[Verge_syslog.txt](https://github.com/vergecurrency/VERGE/files/1595816/Verge_syslog.txt)

**Comment by dbtftw** [comment]
I verified that delating AppSupport contents and Relaunching QT allows the app to finish launching

**Comment by dbtftw** [comment]
[spindump.txt](https://github.com/vergecurrency/VERGE/files/1595822/spindump.txt)
spin dump attached

**Comment by soonlar** [comment]
I am running macOS High Sierra 10.13.2
I seem to be missing the /VERGE folder inside my /Application Support folder, yet I previously installed the 4.0 Wallet <Verge-Qt-4.0-OSX.dmg just fine.
I created the folder myself and copied the downloaded blockchain contents to see if that would help, but still waiting for peer connects after 45mins.  
Thoughts?

**Comment by ekryski** [comment]
@dbtftw I noticed that the first time I tried 2 days ago but I realized that it just takes a long time to index. I thought it was hung because it shows Apple's infamous spinning beachball but it actually wasn't. Any chance you are able to retry and see if it just spins up on it's own?

**Comment by dbtftw** [comment]
@ekryski Hiya, So yeah i tried again and left it overnight. It did eventually index and sync to the network. One issue is the UI disappeared (Loading screed) it wasn't until I secondary clicked on the icon and selected the wallet that the UI came back

**Comment by jpp1978** [comment]
Hey guys where can I find  the verge folder on Mac because I've got nothing in "Application support "
I've got the version 10.13.4 of sierra.

**Comment by wohljeff** [comment]
did you ever get the answer to this question @jpp1978 ?
