### ISSUE TITLE
Building on MacOS  High Sierra gives Boost errors

### ISSUE THREAD

**Issue by RualdOrdelman** [vergecurrency/VERGE#193]
When building on macOS I got error messages during the build proces.  Looks something with the Boost library or something. 

Qt 5.10 is installed(see other threads). That works ok after editing the build scripts. I've set the environment variables and the required brew packages. Then~:
./autogen.sh
./configure --with-gui=qt5
make -j4

That last step gives me the errors. 

bitcoinrpc.cpp:682:49: error: too many template arguments for class template 'basic_socket_acceptor'
  ...RPCAcceptHandler(boost::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > ...
                                         ^                               ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
bitcoinrpc.cpp:692:42: error: too many template arguments for class template 'basic_socket_acceptor'
static void RPCListen(boost::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > ac...
                                         ^                               ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
bitcoinrpc.cpp:714:49: error: too many template arguments for class template 'basic_socket_acceptor'
  ...RPCAcceptHandler(boost::shared_ptr< basic_socket_acceptor<Protocol, SocketAcceptorService> > ...
                                         ^                               ~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/basic_socket_acceptor.hpp:73:7: note: template is declared here
class basic_socket_acceptor
      ^
bitcoinrpc.cpp:789:18: error: no matching constructor for initialization of 'ssl::context'
    ssl::context context(io_service, ssl::context::sslv23);
                 ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/ssl/impl/context.ipp:63:10: note: candidate constructor not viable:
      requires single argument 'm', but 2 arguments were provided
context::context(context::method m)
         ^
/usr/local/include/boost/asio/ssl/context.hpp:36:7: note: candidate constructor
      (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class context
      ^
bitcoinrpc.cpp:1099:18: error: no matching constructor for initialization of 'ssl::context'
    ssl::context context(io_service, ssl::context::sslv23);
                 ^       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/boost/asio/ssl/impl/context.ipp:63:10: note: candidate constructor not viable:
      requires single argument 'm', but 2 arguments were provided
context::context(context::method m)
         ^
/usr/local/include/boost/asio/ssl/context.hpp:36:7: note: candidate constructor
      (the implicit copy constructor) not viable: requires 1 argument, but 2 were provided
class context
      ^
1 warning and 5 errors generated.
make[1]: *** [libbitcoin_server_a-bitcoinrpc.o] Error 1

**Comment by sciack76** [comment]
you have to install boost! brew install boost

**Comment by RualdOrdelman** [comment]
I installed Boost by using Brew.

**Comment by topcatx** [comment]
Running into the same issue, it looks like it's not playing well with `Boost 1.66`. Do we know which version of Boost the successful builds are running against ?

**Comment by topcatx** [comment]
Seems the builds are against `Boost 1.65.1` which is the latest version available on Mac ports (https://www.macports.org/install.php). 
Installing boost via `sudo port install boost` fixed this issue.

**Comment by nferruzzi** [comment]
@RualdOrdelman brew version may be too new (ie 1.66) you have to downgrade

ie this version works for me
```
brew uninstall boost
brew install boost@1.57
brew link boost@1.57 --force
```

**Comment by topcatx** [comment]
Getting this annoying error, can't seem to compile: 
```
 OBJCXXLD qt/VERGE-qt
clang: error: unknown argument: '-framework QtDBus'
clang: error: unknown argument: '-framework QtCore'
```

Wondering if any linking stuff changed when the move to Qt5.5 was made

**Comment by triamazikamno** [comment]
@topcatx I had the same issue and it turned out that my zsh replaced spaces with "\ " when I copy pasted the `export QT_LIBS=` line. So it ended up having `-framework\ QtDBus` in the Makefile. Make sure that you don't have same issue

**Comment by topcatx** [comment]
@triamazikamno I do see `-frameowrk\ QtDbus` for `QT_DBUS_LIBS` inside Makefile. However, I edited the `Makefile` and did a `make clean && make -j8` still same.

**Comment by triamazikamno** [comment]
@topcatx if you are editing Makefile, then make sure that you edit both of them (in the top directory and in `src`).
Also, there are 2 places you need to fix it: `QT_DBUS_LIBS` and `QT_TEST_LIBS`

**Comment by topcatx** [comment]
@triamazikamno awesome, was missing the the edit for the second Makefile inside src, thanks.

**Comment by RualdOrdelman** [comment]
This issue can be closed. With the last changes and the new build documentation, building from sources works charming. Good job boys.
