### ISSUE TITLE
Issue installing Verge 4.0 on Mac High Sierra ver. 10.13.2

### ISSUE THREAD

**Issue by anna99tran** [vergecurrency/VERGE#194]
Hi,

Not sure if anyone else having the same problem. I am totally new here so I might be doing something wrong.

Getting this error when trying to open Verge after installing.

<img width="1007" alt="screen shot 2018-01-01 at 9 13 24 pm" src="https://user-images.githubusercontent.com/27845183/34466964-bb1a9786-ef38-11e7-9504-3f2e79697924.png">

have tried uninstall and re-install.

**Comment by tnick55** [comment]
PLEASE  for the love of god read other requests before posting new ones people.
They know there is an issue on launch.

For those who don't have home brew installed open terminal and run following cmds in exact order:

xcode-select --install

ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew install boost

**Comment by pasrom** [comment]
see #181

**Comment by anna99tran** [comment]
sorry my bad

**Comment by corecrypto** [comment]
Your not the only one. It's a complete cluster fuck.

Bobby Clint Baldwin
CEO
Core CryptoCurrency

**Comment by corecrypto** [comment]
See how they treat investors.

Bobby Clint Baldwin
CEO
Core CryptoCurrency
