### ISSUE TITLE
Wont run in Macbook Sierra HD

### ISSUE THREAD

**Issue by koolbugs** [vergecurrency/VERGE#195]
Process:               VERGE-Qt [33514]
Path:                  /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
Identifier:            com.vergecurrency.VERGE-Qt
Version:               2.1.0 (2.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VERGE-Qt [33514]
User ID:               501

Date/Time:             2018-01-01 13:41:37.811 +0300
OS Version:            Mac OS X 10.13.2 (17C88)
Report Version:        12
Anonymous UUID:        A8323279-9872-3BB7-D3E5-97B3DAD962E9

Sleep/Wake UUID:       5B8ECC02-E9E8-4753-9679-08BA44F19277

Time Awake Since Boot: 710000 seconds
Time Since Wake:       530 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x10e726000 -        0x10ee53ff7 +com.vergecurrency.VERGE-Qt (2.1.0 - 2.1.0) <5EBCFD6F-D5DC-3276-80F4-F8FA95BB8C17> /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
       0x10eef1000 -        0x10eef3ff7 +libboost_system.dylib (0) <571C7888-D10F-3CB1-8DDB-460887DC314C> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x10eefb000 -        0x10ef08fff +libboost_filesystem.dylib (0) <A742D64A-E278-3C8E-954A-D7C836ED6B53> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x10ef17000 -        0x10ef47fff +libboost_program_options-mt.dylib (0) <78525B93-6E1C-3BD8-89A4-2FADABACDD56> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x10ef6a000 -        0x10ef78fff +libboost_thread-mt.dylib (0) <5BF9428B-F1C9-3CDE-B970-C17A41415A36> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x10ef85000 -        0x10ef87ff7 +libboost_chrono-mt.dylib (0) <1BF07246-8624-3109-8030-F23357EA1F37> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x10ef8b000 -        0x10f496fff +QtWidgets (5.5.1) <416CBC52-D42C-3996-B338-C848863E65B0> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10f5cb000 -        0x10fa4ffff +QtGui (5.5.1) <217B896F-895F-3DEC-BF29-01E065492858> /Applications/VERGE-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10fb2f000 -        0x110036fff +QtCore (5.5.1) <201F9A70-4676-3BC5-8B59-82DA94559272> /Applications/VERGE-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x1100c9000 -        0x1101d6ff7 +QtNetwork (5.5.1) <CC4ADD9F-E8C7-3618-9D83-7DBF9AC4267A> /Applications/VERGE-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x110213000 -        0x111c55fff +QtWebKit (5.5.1) <693CF012-F937-3DB1-A6A9-05BB6DA6FE69> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWebKit.framework/Versions/5/QtWebKit
       0x111ee8000 -        0x111f16ff7 +QtWebKitWidgets (5.5.1) <84451F1E-1CE1-3A7D-9CB9-BD686BA98B92> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWebKitWidgets.framework/Versions/5/QtWebKitWidgets
       0x111f3e000 -        0x111fa1ff7 +QtDBus (5.5.1) <B0B9AE70-B993-3081-9336-E01BD1233823> /Applications/VERGE-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x111fb9000 -        0x111fbffff +libqrencode.4.dylib (0) <5B7DEE75-603E-351D-B14C-21663CD470BC> /Applications/VERGE-Qt.app/Contents/Frameworks/libqrencode.4.dylib
       0x111fc3000 -        0x1120f5ff7 +libprotobuf.15.dylib (0) <6300475A-5FB2-39C0-AE54-644CFAC18091> /Applications/VERGE-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x1121a5000 -        0x1122c9ff7 +libdb_cxx-4.8.dylib (0) <893E0F96-1F8A-3073-B1CF-CC60610C3E90> /Applications/VERGE-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x112304000 -        0x11230cff3 +libminiupnpc.16.dylib (0) <C103607F-F06C-34D6-A60A-27E9E344F015> /Applications/VERGE-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x112315000 -        0x112356fff +libssl.1.0.0.dylib (0) <3C28C2A8-036B-34B3-82BB-5780DB7271B2> /Applications/VERGE-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x112376000 -        0x1124e6c87 +libcrypto.1.0.0.dylib (0) <1C6D06DA-0F88-37BA-80E9-52C4AC7E942C> /Applications/VERGE-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x115696000 -        0x1156e098f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
    0x7fff4bad2000 -     0x7fff4bad6ffb  com.apple.agl (3.3.1 - AGL-3.3.1) <5A110DE6-3EE7-343B-95FE-9642517D1B64> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff4d13b000 -     0x7fff4df98fff  com.apple.AppKit (6.9 - 1561.20.106) <7A71ACCF-2DF5-3557-BB22-3A9FC9F71CCF> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff4dfea000 -     0x7fff4dfeafff  com.apple.ApplicationServices (48 - 50) <7627DBD6-497B-3AB7-9B63-F0532EDF09B8> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff4fb23000 -     0x7fff4ffbcfff  com.apple.CoreFoundation (6.9 - 1450.16) <DD253147-5720-3B3B-B222-77FD1419C400> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff50c99000 -     0x7fff50c99fff  com.apple.CoreServices (822.19 - 822.19) <0C60B639-4CC4-3F57-BC5E-DB71EB75F7F4> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff51ab8000 -     0x7fff51abdfff  com.apple.DiskArbitration (2.7 - 2.7) <44836CE9-A9ED-3017-972A-7A0A3D6B472B> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff51c7e000 -     0x7fff52043fff  com.apple.Foundation (6.9 - 1450.16) <7FEC6610-70EA-3A8D-8EC4-7E99BAF1E312> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff52358000 -     0x7fff523f3fff  com.apple.framework.IOKit (2.0.2 - 1445.31.1) <7556086A-EFAF-3262-9822-6F666CFC6655> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff59e42000 -     0x7fff59e50ffb  com.apple.opengl (16.4.2 - 16.4.2) <C8C31EF5-8DB4-336F-A87C-5D520C7EFDC5> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff74cfd000 -     0x7fff74d30fff  libclosured.dylib (519.2.2) <48051216-5647-3643-B979-B77D0FD20011> /usr/lib/closure/libclosured.dylib
    0x7fff7520f000 -     0x7fff75210ff3  libSystem.B.dylib (1252) <5EDEEA85-0387-31EE-9D9B-DA1B75E7AEF3> /usr/lib/libSystem.B.dylib
    0x7fff754c5000 -     0x7fff7551bfff  libc++.1.dylib (400.9) <FCF5E1F6-2B04-3545-8004-F3AB32FED172> /usr/lib/libc++.1.dylib
    0x7fff7551c000 -     0x7fff75540ff7  libc++abi.dylib (400.7) <217656D5-BC40-37FF-B322-91CB2AAD4F34> /usr/lib/libc++abi.dylib
    0x7fff76892000 -     0x7fff76c833b7  libobjc.A.dylib (723) <37A7D77E-952C-3F5D-970B-3CDE349B2322> /usr/lib/libobjc.A.dylib
    0x7fff7732a000 -     0x7fff7732eff7  libcache.dylib (80) <354F3B7D-404E-3398-9EBF-65CA2CE65211> /usr/lib/system/libcache.dylib
    0x7fff7732f000 -     0x7fff77339ff3  libcommonCrypto.dylib (60118.30.2) <674286D3-7744-36A3-9AAA-49DFCD97A986> /usr/lib/system/libcommonCrypto.dylib
    0x7fff7733a000 -     0x7fff77341fff  libcompiler_rt.dylib (62) <4487CFBA-A5D7-3282-9E6B-94CAD7BE507E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff77342000 -     0x7fff7734affb  libcopyfile.dylib (146.30.2) <2C7C67D7-562B-3FFA-973D-BACF4C10E1EC> /usr/lib/system/libcopyfile.dylib
    0x7fff7734b000 -     0x7fff773d0fff  libcorecrypto.dylib (562.30.10) <8A53EFE1-AFCA-3676-BEE1-FA5ED9F0E222> /usr/lib/system/libcorecrypto.dylib
    0x7fff77458000 -     0x7fff77491ff7  libdispatch.dylib (913.30.4) <7D0E3183-282B-3FEE-A734-2C0ADC092084> /usr/lib/system/libdispatch.dylib
    0x7fff77492000 -     0x7fff774afff7  libdyld.dylib (519.2.2) <C50D02BC-A333-3313-B787-02F255A6783F> /usr/lib/system/libdyld.dylib
    0x7fff774b0000 -     0x7fff774b0ffb  libkeymgr.dylib (28) <6D84A96F-C65B-38EC-BDB5-21FD2C97E7B2> /usr/lib/system/libkeymgr.dylib
    0x7fff774be000 -     0x7fff774beff7  liblaunch.dylib (1205.30.29) <E66F58ED-C15E-3DFB-BC22-A861E13918C6> /usr/lib/system/liblaunch.dylib
    0x7fff774bf000 -     0x7fff774c3ffb  libmacho.dylib (900.0.1) <756F2553-07B6-3B42-ACEA-2F0F1A5E8D0F> /usr/lib/system/libmacho.dylib
    0x7fff774c4000 -     0x7fff774c6ff3  libquarantine.dylib (86) <6AC8773F-3817-3D82-99C2-01BABB9C3CBB> /usr/lib/system/libquarantine.dylib
    0x7fff774c7000 -     0x7fff774c8ff3  libremovefile.dylib (45) <912FA211-DD8C-3C92-8424-21B89F8B10FD> /usr/lib/system/libremovefile.dylib
    0x7fff774c9000 -     0x7fff774e0fff  libsystem_asl.dylib (356.1.1) <94972913-9DF0-3C78-847C-43E58919E3DA> /usr/lib/system/libsystem_asl.dylib
    0x7fff774e1000 -     0x7fff774e1fff  libsystem_blocks.dylib (67) <F2493BB5-B1C6-3C4D-9F1F-1B402E0F1DB7> /usr/lib/system/libsystem_blocks.dylib
    0x7fff774e2000 -     0x7fff7756bff7  libsystem_c.dylib (1244.30.3) <E0136C71-0648-36F0-9F84-82EA2748A8D7> /usr/lib/system/libsystem_c.dylib
    0x7fff7756c000 -     0x7fff7756fffb  libsystem_configuration.dylib (963.30.1) <0F8D0B76-4F7D-34EC-AB6C-50F9465809DA> /usr/lib/system/libsystem_configuration.dylib
    0x7fff77570000 -     0x7fff77573ffb  libsystem_coreservices.dylib (51) <21A488D0-2D07-344E-8631-CC8B2A246F35> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff77574000 -     0x7fff77575fff  libsystem_darwin.dylib (1244.30.3) <2F750CB1-BC26-3FA3-AE59-553EE30D451B> /usr/lib/system/libsystem_darwin.dylib
    0x7fff77576000 -     0x7fff7757cff7  libsystem_dnssd.dylib (878.30.4) <EB9BB165-45A4-367C-B33A-688D4F383A95> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff7757d000 -     0x7fff775c6ff7  libsystem_info.dylib (517.30.1) <7D79E167-4B5C-3833-81EE-3AF3FB53616D> /usr/lib/system/libsystem_info.dylib
    0x7fff775c7000 -     0x7fff775ecff7  libsystem_kernel.dylib (4570.31.3) <D2E842AA-3B8D-31BF-8234-8C1BE11CFE32> /usr/lib/system/libsystem_kernel.dylib
    0x7fff775ed000 -     0x7fff77638fcb  libsystem_m.dylib (3146) <ABB1B85F-9FFE-31B8-AD4F-E39A30794A93> /usr/lib/system/libsystem_m.dylib
    0x7fff77639000 -     0x7fff77658fff  libsystem_malloc.dylib (140.1.1) <9F0745FF-B92F-330D-8812-BB74001D1D33> /usr/lib/system/libsystem_malloc.dylib
    0x7fff77659000 -     0x7fff776fdff3  libsystem_network.dylib (1229.30.11) <40BAD301-8744-3AD8-A688-E7925C587B00> /usr/lib/system/libsystem_network.dylib
    0x7fff776fe000 -     0x7fff77708ffb  libsystem_networkextension.dylib (767.30.7) <C5ED4BAB-2480-369D-8AB6-DFB37C15A1EE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff77709000 -     0x7fff77712ff3  libsystem_notify.dylib (172) <98EA3D62-7C86-30DE-8261-D020D2F1EFF3> /usr/lib/system/libsystem_notify.dylib
    0x7fff77713000 -     0x7fff7771aff7  libsystem_platform.dylib (161.20.1) <C049250F-8C35-314D-810F-4E28AEAED983> /usr/lib/system/libsystem_platform.dylib
    0x7fff7771b000 -     0x7fff77726fff  libsystem_pthread.dylib (301.30.1) <ABA848E1-6978-3B42-A3A7-608B2C36FA93> /usr/lib/system/libsystem_pthread.dylib
    0x7fff77727000 -     0x7fff7772aff3  libsystem_sandbox.dylib (765.30.4) <A51828BA-26D8-3205-AF3A-DF5C37269468> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff7772b000 -     0x7fff7772cff3  libsystem_secinit.dylib (30) <F06ADB8F-9E94-34A7-B3C9-2C22FDD14BAD> /usr/lib/system/libsystem_secinit.dylib
    0x7fff7772d000 -     0x7fff77734ff7  libsystem_symptoms.dylib (820.30.7) <DC3586C2-AA56-3419-88D3-FC0DBF08E3C0> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff77735000 -     0x7fff77748ff7  libsystem_trace.dylib (829.30.14) <69EBF017-D40F-30D7-9B0B-BFC862D761A5> /usr/lib/system/libsystem_trace.dylib
    0x7fff7774a000 -     0x7fff7774fff7  libunwind.dylib (35.3) <6D4FCD49-D2A9-3233-95C7-A7635CE265F2> /usr/lib/system/libunwind.dylib
    0x7fff77750000 -     0x7fff7777cff7  libxpc.dylib (1205.30.29) <F7E5F1BC-614B-39CB-B6CE-92A9C7B7EC0B> /usr/lib/system/libxpc.dylib

Model: MacBookPro9,2, BootROM MBP91.00D7.B00, 2 processors, Intel Core i5, 2.5 GHz, 16 GB, SMC 2.2f44
Graphics: Intel HD Graphics 4000, Intel HD Graphics 4000, Built-In
Memory Module: BANK 0/DIMM0, 8 GB, DDR3, 1600 MHz, 0x066B, 0x39444831434F33482D544154532020202020
Memory Module: BANK 1/DIMM0, 8 GB, DDR3, 1600 MHz, 0x066B, 0x39444831434F33482D544154532020202020
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0xF5), Broadcom BCM43xx 1.0 (7.21.190.16.1a2)
Bluetooth: Version 6.0.2f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Samsung SSD 850 EVO 500GB, 500.11 GB
Serial ATA Device: HL-DT-ST DVDRW  GS41N
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: FaceTime HD Camera (Built-in)
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: Hub
USB Device: Apple Internal Keyboard / Trackpad
USB Device: IR Receiver
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB 3.0 Bus
USB Device: USB Receiver
Thunderbolt Bus: MacBook Pro, Apple Inc., 25.1

**Comment by DarthJahus** [comment]
I think this is same as #181, isn't it?

**Comment by tobiwin** [comment]
https://github.com/vergecurrency/VERGE/issues/183

**Comment by koolbugs** [comment]
yeah, I see it now.
