### ISSUE TITLE
High Sierra: Verge-Qt cannot be opened because of a problem (standard install from dmg)

### ISSUE THREAD

**Issue by namshub1** [vergecurrency/VERGE#197]
Process:               VERGE-Qt [4729]
Path:                  /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
Identifier:            com.vergecurrency.VERGE-Qt
Version:               2.1.0 (2.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VERGE-Qt [4729]
User ID:               501

Date/Time:             2018-01-01 12:25:21.438 +0100
OS Version:            Mac OS X 10.13.2 (17C88)
Report Version:        12
Bridge OS Version:     3.0 (14Y661)
Anonymous UUID:        953F77CA-E0A9-DC93-AFB0-2D7D5E675792

Sleep/Wake UUID:       D6270CB6-6B7D-4F94-B0F1-4398D982886A

Time Awake Since Boot: 88000 seconds
Time Since Wake:       69000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

**Comment by sasasavic82** [comment]
Dude...

https://github.com/vergecurrency/VERGE/issues/183

**Comment by tnick55** [comment]
See #181 not #183

**Comment by namshub1** [comment]
my fault. sorry for duplicate.

**Comment by namshub1** [comment]
see #181
