### ISSUE TITLE
Small Bug 

### ISSUE THREAD

**Issue by ddang1994** [vergecurrency/VERGE#199]
Bug when minimizing to menubar. The only way to maximize it back is by rightclicking into show/hide. Cannot click icon to maximize

**Comment by davecummins2000** [comment]
More bugs to come...

SELL SELL SELL run from this shitcoin before you are sorry like i was useless Dev and management of what could have been good.

**Comment by jrsikors** [comment]
super late response, can you confirm if this is still an issue in the latest releases?
