### ISSUE TITLE
sendtostealthaddress in command line causes error code -1

### ISSUE THREAD

**Issue by SachaSchlegel** [vergecurrency/VERGE#200]
sendtostealthaddress to stealth address in command line causes error

*********************
command with real stealthaddress: 
sendtostealthaddress smYhZjoCH1BfNGKbvjXJzjJJBS7UkaxErUFEFMmcNNV6shfadLwG5fTEN7xZzh4CQzDesfosRwAoUmeLvkQoDpwU2QpagoTq2bP5mj 3.0

error:
value is type str, expected real (code -1)

![bildschirmfoto vom 2018-01-01 12-25-45](https://user-images.githubusercontent.com/9555/34467503-7a76b2da-eef4-11e7-8876-643eb29cfed7.png)

**************************
git compile on ubuntu linux.

getinfo in comand line:
{
"version" : "v2.1.0.0-0606765-beta",
"protocolversion" : 90001,
"walletversion" : 60000,
"balance" : 171.70000000,
"newmint" : 0.00000000,
"stake" : 0.00000000,
"blocks" : 1766309,
"moneysupply" : 14416602039.99999619,
"connections" : 8,
"proxy" : "",
"ip" : "195.225.201.149",
"pow_algo_id" : 0,
"pow_algo" : "scrypt",
"difficulty" : 108102.23408004,
"difficulty_x17" : 6012.90214915,
"difficulty_scrypt" : 108102.23408004,
"difficulty_groestl" : 577869.74537347,
"difficulty_lyra2re" : 27572.60369655,
"difficulty_blake" : 2013007.90113421,
"testnet" : false,
"keypoololdest" : 1514801365,
"keypoolsize" : 101,
"paytxfee" : 0.00000000,
"errors" : ""
}

****************
sending coins via gui works.
sending coins via command line command "sendtoaddress" to regular xvg address works. 
sending cons via command line command "sendtostealthaddress" to stealht address returns error

**Comment by davecummins2000** [comment]
SELL SELL SELL run from this shitcoin before you are sorry like i was useless Dev and management of what could have been good.

**Comment by downfall109** [comment]
Can confirm I am getting the same issue on the following getinfo:

{
"version" : "v2.1.0.0-0606765-beta",
"protocolversion" : 90001,
"walletversion" : 60000,
"balance" : 0.00000000,
"newmint" : 0.00000000,
"stake" : 0.00000000,
"blocks" : 1766395,
"moneysupply" : 14416736199.99999619,
"connections" : 8,
"proxy" : "",
"ip" : "143.238.164.123",
"pow_algo_id" : 0,
"pow_algo" : "scrypt",
"difficulty" : 82664.21125568,
"difficulty_x17" : 11347.61419871,
"difficulty_scrypt" : 82664.21125568,
"difficulty_groestl" : 593967.40784278,
"difficulty_lyra2re" : 57409.26268513,
"difficulty_blake" : 2842790.86207164,
"testnet" : false,
"keypoololdest" : 1514621940,
"keypoolsize" : 101,
"paytxfee" : 0.00000000,
"errors" : ""
}

**Comment by corecrypto** [comment]
I agree. No faith in the world will bring this back to life. Fucking
service is shit.

Bobby Clint Baldwin
CEO
Core CryptoCurrency

**Comment by daveAw** [comment]
I’ll make sure people know core cryptocurrency is run by a tool and isn’t a expert and should clear be avoided

Sent from my iPhone

On 1 Jan 2018, at 9:02 pm, corecrypto <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree. No faith in the world will bring this back to life. Fucking
service is shit.

Bobby Clint Baldwin
CEO
Core CryptoCurrency

**Comment by davecummins2000** [comment]
@daveAw Verge is being run (into the ground) by a tool....

**Comment by daveAw** [comment]
This isn’t the place buddy

Sent from my iPhone

On 1 Jan 2018, at 9:18 pm, davecummins2000 <notifications@github.com<mailto:notifications@github.com>> wrote:


@daveAw<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdaveaw&data=02%7C01%7C%7C530b14a313784eb070e008d5511a2e63%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636504095251563486&sdata=NDqYJm2HkXDvTUEORUPsOPtKHZQj8DboKYAhxFIxTj0%3D&reserved=0> Verge is being run (into the ground) by a tool....

**Comment by davecummins2000** [comment]
@daveAw shruggs

**Comment by SachaSchlegel** [comment]
Problem lies in file rpcwallet.cpp, line 1967. AmountFromValue returns an int64 but an nAmount is of type int64_t:

    int64_t nAmount = AmountFromValue(params[1]);

receiving from stealth money might have a same issue but not checked yet.

**Comment by SachaSchlegel** [comment]
if (strMethod == "sendtostealthaddress"   && n > 1) ConvertTo<double>(params[1]);
needs to be added in RPCConvertValues in verge/src/bitcoinrpc.cpp

![bildschirmfoto vom 2018-01-01 16-25-15](https://user-images.githubusercontent.com/9555/34468779-61742c4c-ef10-11e7-8b31-ff180a1a7c14.png)

****

Hitting next error ...

**Comment by SachaSchlegel** [comment]
in my case the CreateTransaction returns false and hence the transaction cannot be created.

in wallet.cpp, line 1453:

bool CWallet::CreateTransaction(const vector<pair<CScript, int64> >& vecSend, CWalletTx& wtxNew, CReserveKey& reservekey, int64& nFeeRet)

**Comment by SachaSchlegel** [comment]
there have been recent changes in the CreateTransaction method:
https://github.com/vergecurrency/VERGE/commit/ccb9d95e56a57a41fd78a17462722a98f4a8e966
https://github.com/vergecurrency/VERGE/commit/b27ba11341ced1a02404f73e5bfe7e4055b6a6eb

in my case the CreateTransaction failed at one point where it returns false. is my transaction of 3xvgs to small? will try.

                BOOST_FOREACH (const PAIRTYPE(CScript, int64)& s, vecSend)
                    {
						CTxOut txout(s.second, s.first);
						if (txout.nValue <= MIN_RELAY_TX_FEE)
							return false;

						wtxNew.vout.push_back(txout);
					}

**Comment by SachaSchlegel** [comment]
CTxOut txout(s.second, s.first);
					if (txout.nValue <= MIN_RELAY_TX_FEE)
						return false;
txout.nValue is 0 and MIN_RELAY_TX_FEE is 100'00 so it returns false and no transaction is created.

**Comment by justinvforvendetta** [comment]
yea i think this happened last night when we were trying to fix the issue with leftover balance being pushed into fee

**Comment by justinvforvendetta** [comment]
looks like we did fix the leftover balance/fee issue, which in turn, possibly caused this issue.

**Comment by SachaSchlegel** [comment]
fix for the first problem, the data types problem of value send to sendtostealthaddress (initital issue: https://github.com/vergecurrency/VERGE/issues/200)

diff --git a/src/bitcoinrpc.cpp b/src/bitcoinrpc.cpp
index 1f11928..a1da270 100644
--- a/src/bitcoinrpc.cpp
+++ b/src/bitcoinrpc.cpp
@@ -1176,6 +1176,7 @@ Array RPCConvertValues(const std::string &strMethod, const std::vector<std::stri
     if (strMethod == "setgenerate"            && n > 0) ConvertTo<bool>(params[0]);
     if (strMethod == "setgenerate"            && n > 1) ConvertTo<boost::int64_t>(params[1]);
     if (strMethod == "sendtoaddress"          && n > 1) ConvertTo<double>(params[1]);
+    if (strMethod == "sendtostealthaddress"   && n > 1) ConvertTo<double>(params[1]);
     if (strMethod == "settxfee"               && n > 0) ConvertTo<double>(params[0]);
     if (strMethod == "getreceivedbyaddress"   && n > 1) ConvertTo<boost::int64_t>(params[1]);
     if (strMethod == "getreceivedbyaccount"   && n > 1) ConvertTo<boost::int64_t>(params[1]);

second problem: CreateTransaction I have not further investigated.

**Comment by swat69** [comment]
second problem still exists:
last commit:
https://github.com/vergecurrency/VERGE/commit/141fbe765386bf44ec962f8897a9b8f994458e15

Ubuntu 14
console:
sendtostealthaddress smYmq5BvX2B4VsP1gjddU5ZReugq2DbzJWJ9kWpPELkgDVHb5W7s3arWzf6hmZYD6S7q3dsFBTSaqfYvmxruhq56hFAAW6mTmwk1yJ 1.0
Error: Transaction creation failed (code -4)

debug.log:
SendStealthMoney() : Error: Transaction creation failed  connection timeout

**Comment by justinvforvendetta** [comment]
@swat69 is that the only piece in the debug that is related?

**Comment by jderwish** [comment]
This issue is still happening, how it is closed? did you identified the problem and will be fixed in next released?

**Comment by justinvforvendetta** [comment]
@jderwish because we fixed the "value is type str, expected real (code -1)" issue, and just have one more thing to do, somewhat related.  https://github.com/vergecurrency/VERGE/commit/ab84d904a1f8a4c66fb9858c38de33fd29610e7b

**Comment by madpada** [comment]
An issue can be fixed and closed bot not yet released. That is the case here.

**Comment by swat69** [comment]
yes connected and synced.
a sendtoaddress (without stealth) is sending instantly.
no more related in debug.log, this time not the 'timeout':

Flushed wallet.dat 2ms
getblocks 1768351 to 00000000000000000000 limit 500
getblocks -1 to 00000000000000000000 limit 500
getblocks 1768351 to 00000000000000000000 limit 500
SendStealthMoney() : Error: Transaction creation failed  received block d9ebcb00d93e128d5a00
ProcessBlock: ACCEPTED (groestl)
received block 3d92b7c76b2b00911e18

**Comment by jderwish** [comment]
Any update when new release with stealth mode fixed will be available for testing?

**Comment by jderwish** [comment]
I would like to see windows binary please..I am volunteering to assist in testing

**Comment by justinvforvendetta** [comment]
moved to a new issue
