### ISSUE TITLE
walletlock / unlock not working on cli

### ISSUE THREAD

**Issue by Himan2001** [vergecurrency/VERGE#202]
The walletpassphrase command on linux and the walletlock functions are broken.

walletpassphrase returns always "wrong password" and walletlock has no function.
at the moment there is a need for a daemon restart.

Using this commands in debug-window on qt, the functions works as expected.

**Comment by Technophant** [comment]
There's a warning that may be related: ```
wallet.cpp: In member function ‘bool CWallet::ChangeWalletPassphrase(const SecureString&, const SecureString&)’:
wallet.cpp:121:10: warning: unused variable ‘fWasLocked’ [-Wunused-variable]
     bool fWasLocked = IsLocked();

```

**Comment by jrsikors** [comment]
I believe this was resolved with the latest 4.0.1 for stealth release.  

Confirm please?

**Comment by Influence2** [comment]
@Himan2001 Was this resolve when you updated to the newest wallet as suggested above? Please close if so.
