### ISSUE TITLE
stakeminer is always started / protocol error

### ISSUE THREAD

**Issue by Himan2001** [vergecurrency/VERGE#204]
I noted in debug log, that the "stake-miner" is always started - which makes no sense,
when there is nothing to "stake".

usualy with staking=0 this part is disabled - but this isn´t work here.

Another warning shows always up on my server with a "port binding error". This warning is present
because of not available ipv6 stack on my box (i have disabled it completly)

**Comment by jrsikors** [comment]
super late response .. but are either of these still issues in the latest 4.0.1 ?

**Comment by justinvforvendetta** [comment]
should be gone now

**Comment by jrsikors** [comment]
@justinvforvendetta  if you can figure out how to give me some permissions on the Issues page it would be much appreciated, I got a lot of clean up here I want to get started on !  My OCD is hurting right now.  I even have a notepad of all the issues I want to get closed up for you :rofl:

**Comment by jrsikors** [comment]
If you can't limit my permissions to the issues and have to give me full access to the repository and you'd rather not -- that's fine too.  I assure you I won't be doing anything on the code side.  Issues only for me.

**Comment by jrsikors** [comment]
hit me up jeffsikorski@gmx.com if you need to discuss.
