### ISSUE TITLE
Address textbox only accept normal address length and truncates stealth address

### ISSUE THREAD

**Issue by topcatx** [vergecurrency/VERGE#205]
Generated stealth address by going to  Help -> Debug -> Console and typing in `getnewstealthaddress`. The address appears on the address list.

<img width="1060" alt="screen shot 2018-01-01 at 8 44 07 am" src="https://user-images.githubusercontent.com/34992411/34468122-32d488cc-eed0-11e7-8478-fbd364c7817f.png">

Right click -> copy or hit copy address and only partial address seems to be copied to the clipboard.
Looks like it's probably copying with a buffer size of old address and does not quite recognize the stealth address in the UI.

<img width="699" alt="screen shot 2018-01-01 at 8 44 51 am" src="https://user-images.githubusercontent.com/34992411/34468145-9f79cb36-eed0-11e7-9b81-d0b0a154ebc5.png">

**Comment by Naragato** [comment]
The copy functionality is fine (paste the value into note pad you will see), the issue is the field only accepts a certain string length.

**Comment by DarthJahus** [comment]
Would be good to rename the issue to "address textbox only accept normal address length and truncates stealth address" or something similar.

**Comment by chaman** [comment]
Yep, we should change the title totally. Don't think I can edit it due to permissions, if anyone can edit it, please do so.

**Comment by topcatx** [comment]
Updated the title for this :)

**Comment by triamazikamno** [comment]
https://github.com/vergecurrency/VERGE/blob/814784f2c9ad72e3752759835bbbdcfe45490b3f/src/qt/forms/sendcoinsentry.ui#L95-L97

Probably related to this

**Comment by justinvforvendetta** [comment]
just fixed this
