### ISSUE TITLE
Why havent got any support customer who can help we

### ISSUE THREAD

**Issue by okan0101** [vergecurrency/VERGE#208]
I downloaded the verge application i created a wallet(tor) and i sent  xvg i got no connection failed and i erased application and again dowland but erased wallet of informations now i lose  them i know my adress i know my unlock paassword i know some part phrese (this is problem) i have got the money that i sent documants????

**Comment by DarthJahus** [comment]
This is cryptocurrency. If you have erased your wallet file (wallet.dat), no one can recover the coins. Really sorry about that, but your coins aren't held by anyone (it's the concept of decentralization), only by yourself.

The words can derivate the private key, but you need them all and in order.

What you can try is check again if your wallet.dat file is in %AppData%\Verge folder or .config/verge.

**Comment by rvrhee** [comment]
do not use your computer anymore... boot with usb and recovery tools

**Comment by okan0101** [comment]
I checked it isnt there i use fingerprints is it usufel?

**Comment by okan0101** [comment]
varge wallet and tor orbot not working even now there are broken even on vpn mod

**Comment by okan0101** [comment]
I never use varge wallet in the future

**Comment by justinvforvendetta** [comment]
@okan0101 they are working for everyone else. not sure what you have done. you can delete the wallet, and download it again, and restore from the seedphrase. (make sure box under restore option is checked when entering seedphrase)
