### ISSUE TITLE
Stealth address doesn't work on windows?

### ISSUE THREAD

**Issue by Nadim96** [vergecurrency/VERGE#213]
added a new address and checked the 'stealth address button' and the address given to me is:

D7qAcpHM62mKpisdhevit8GhwaTHY91qms

**Comment by justinvforvendetta** [comment]
yeah stealth addresses have to be made in the help/debug/console and getnewstealthaddress

should have this fixed later today

**Comment by Nadim96** [comment]
worked now it's:

smYhS3WD2J9ZGxEErCcRUxRHScdLPQYrPCTV1UMNrCj1NdgahVcx9hx3mpgFQrXwyySd81uU5eNHi1SLb17i4VV1EygtZSf8wJHQ65


an option to delete addresses would be nice as well but low priority =)

**Comment by DarthJahus** [comment]
@Nadim96, I think it won't be feasible; because it would be too dangerous. Maybe an option to "hide" addresses (right click > hide) and an option to "show hidden addresses". And yeah, not high priority.

**Comment by kiennd** [comment]
@justinvforvendetta 
Hi justin,
I think you need attach the how to use wraith,Stealth address... document on the release page :).
