### ISSUE TITLE
Verge Wallet not syncronizing 

### ISSUE THREAD

**Issue by yona5324** [vergecurrency/VERGE#214]
Dear Devs,

The wallet is not synchronizing It is still displaying 0%. 

I hope you guys can fix this kindly regards.

**Comment by fabiotnt** [comment]
Download the blockchain here: https://verge-blockchain.com/
And follow these instructions: https://verge-blockchain.com/howto

**Comment by demir1988** [comment]
Does everyone have to do this?

**Comment by olanate** [comment]
Nope, just the ones that does not have the blockchain already on their computer

**Comment by demir1988** [comment]
which is me lol, I have just downloaded 4.0 and im downloading the block chain now also

**Comment by justinvforvendetta** [comment]
syncing yourself is the best idea. it only takes about one day (whereas bitcoin takes about 9 days)
