### ISSUE TITLE
"To Pay" text field is too short, cannot input stealth address with longer characters than normal address

### ISSUE THREAD

**Issue by ttkien** [vergecurrency/VERGE#215]
![screen shot 2018-01-01 at 11 56 55 pm](https://user-images.githubusercontent.com/1519521/34469347-7db49146-ef4f-11e7-9cb9-97981d75ee4a.png)

"To Pay" text field is too short, cannot input stealth address with longer characters than normal address on MacOS

**Comment by topcatx** [comment]
duplicate, see https://github.com/vergecurrency/VERGE/issues/205
