### ISSUE TITLE
Highly Suggestion: "depends" folder for all librarys & readme consolidation

### ISSUE THREAD

**Issue by Himan2001** [vergecurrency/VERGE#216]
I noted on all the different snippets, new subdirs, old contrib folder, that there is a massive chaos
for the versioning of things like qt5 and boost and some libs more.

Building a huge amount of .dll files and entire shared on windows is highly deprecated and VERGE is so far the only wallet which is using such huge amount of shared libs.

Between Linux und Windows are usualy great differences between the librarys, it starts by using the precompiled binarys from github, which has for windows an older qt5 version as stated in some scripts for linux-builds.

So i would suggest do asap a small fix:

a.) delete/fix/consolidate the different readme-files and scripts by using clearly documented and defined libs

b.) use only "depends" folder and define a configure-script which is using this entire static build versions
with this command:

./configure \
    --with-daemon \
    --disable-tests \
    --with-gui=qt5 \
    --prefix=`pwd`/depends/x86_64-pc-linux-gnu \
    LDFLAGS="-static-libstdc++"

c.) include a general advice how to use mxe for building 32 AND 64 Bit Versions for different platforms

There are good basic "depends" folder in dogecoin, litecoin, bitcoin and many more. Just edit the version-numbers for the libs at once. Using this method ensures the same libs on ALL platforms. Firther more, the many different mini-buildscripts from the subfolders can be removed.

There are finaly only 3 scripts nessassary for using mingw + depends folder.

Switching to depends means, you no longer needs specific versions on the building host system - the resulting binary files needs no longer specific versions of boost and qt5 libs - so they can by used on many linux-systems by only take care of a minimum libc6-version. The same happens for windows, because you no longer has any .dll files. Just one bigger static .exe file

**Comment by justinvforvendetta** [comment]
actually, have a massive amount of .dll files just means it is a dynamic build (not static, where everything is in one executable) but now that we've gotten rid of the radio feature, we can go back to static builds for windows.

**Comment by Himan2001** [comment]
@justinvforvendetta 

...but please consider using only depends folder and define here the correct working versions of any libs, so that first time win, linux and mac are in sync and we can get rid of all the shared libs on every platform ;-)

**Comment by justinvforvendetta** [comment]
next version will be static.
