### ISSUE TITLE
You guys ruined everything it's to late now !!!!!

### ISSUE THREAD

**Issue by OmarAberkan** [vergecurrency/VERGE#218]

**Comment by ChiefCeko** [comment]
lovely contribution OmarAberkan

**Comment by nkazier** [comment]
@justinvforvendetta please close. No issue.

**Comment by KnightOwl47** [comment]
where do these guys even come from!

**Comment by OmarAberkan** [comment]
Nobody cares about it anymore People had huge expectations People sold their car to buy verge ,everyone is very disappointed

**Comment by vorlonempire** [comment]
i care man. Thats why i'm here

**Comment by nkazier** [comment]
Please stop replying on this board. Please submit comments only that pertains to code. Thousands of subscribers are getting emailed every time. This is a non issue please take this to a social media site if you would like to complain.
