### ISSUE TITLE
Mac wallet's showing out of sync

### ISSUE THREAD

**Issue by vergedude2018** [vergecurrency/VERGE#219]
I got the wallet to install and launched successfully but it's showing "out of sync". How do I fix this issue? Thanks for all your hard work devs!

**Comment by techpoy** [comment]
1. Download block chain
https://verge-blockchain.com/blockchain/Wallet_v3.0_Verge-Blockchain_2017-December-30.zip
2. Follow instructions from here
https://verge-blockchain.com/howto.
btw this is not an issue. This is about not knowing howto.

**Comment by vorlonempire** [comment]
@techpoy as cryptos becoming more and more mainstream, the wallet should at least tell user that he need to download the blockchain, just sayin

**Comment by ChiefCeko** [comment]
I agree. Im pretty confident they will implement a much easier install setup in the coming days/weeks. Not user friendly right now :D But progress is progress!!!

**Comment by vergedude2018** [comment]
I appreciate the response. As as a new user of Verge, I recommend adding notification or message to guide user on where to download the blockchain and manually install the blockchain. Better yet it should download automatically for users without manual intervention. 
On my Mac wallet, I was never notified thus the opening of this issue. Thanks!

**Comment by nkazier** [comment]
@vorlonempire this is already stated inside the README.md file under “want to download the Blockchain instead of waiting/syncing? (Quicker)”
@justinvforvendetta this issue can be closed. Thanks
