### ISSUE TITLE
The wallet keep saying loading block index after downloading the blochain and fallowing the instructions :(

### ISSUE THREAD

**Issue by yona5324** [vergecurrency/VERGE#222]
![verge 2](https://user-images.githubusercontent.com/33532098/34470197-6e4b6e8c-ef2c-11e7-95ca-7a899b716c50.JPG)

**Comment by vorlonempire** [comment]
It takes a while, wait some more.

**Comment by ekryski** [comment]
Yeah it takes a while. Threw me off at first too. I'd love to improve the UX and add better loading progress indicators. Your synchronizing with the blockchain will likely take quite a while as well.

**Comment by dbriggsie** [comment]
@yona5324 generally means your internet connection isnt the best, it'll take a while.. sometimes 40mins to an hour

**Comment by yona5324** [comment]
oke, so lets wait and see if this is the case! Thank you for the comments guys!

**Comment by nferruzzi** [comment]
The problem with this old style QT ui is the lack of feedback, the splash screen disappears on my mac and the Activity Monitor reports the app as "not responding" which is not true .. I think the qt event loop doesn't run while indexing.. anyway it takes a bit also to get the first network connection but then it will complete the syncing; just wait :)

**Comment by justinvforvendetta** [comment]
it's recommended to fully sync the chain yourself. it only takes about 1 day (vs bitcoin core taking about 9 days)

**Comment by yona5324** [comment]
Oke after almost one hour still the same results debug file still trying to connect.
