### ISSUE TITLE
Export Address Book Button - UI Enhancement

### ISSUE THREAD

**Issue by techpoy** [vergecurrency/VERGE#224]
Windows x64.  Export Address book button allows to be resized and moved around. 
This button gets enabled only when the address book list grid is open.
Can we make this a simple push button and keep it after the button "Delete"? 
![verge](https://user-images.githubusercontent.com/34836326/34470507-9157ba58-ef58-11e7-8ecf-3e948bb697e8.png)

**Comment by CptForrest** [comment]
Unrelated, but how long did you wait for your wallet to sync after downloading the blockchain?I have patience, just been like 10 mins, and nothing yet, just wondering if I did something wrong!

**Comment by techpoy** [comment]
Something like this 

![image](https://user-images.githubusercontent.com/34836326/34470592-d1e9a688-ef5a-11e7-8e0d-5e5ad81454aa.png)

**Comment by techpoy** [comment]
Something like this 
![vergeuichange](https://user-images.githubusercontent.com/34836326/34470595-e4ba6c3e-ef5a-11e7-9680-3ee94ad62f5f.png)

**Comment by jrsikors** [comment]
Should be resolved, if not, let me know and ill post under #555
