### ISSUE TITLE
Bug in printing info about decoded transaction

### ISSUE THREAD

**Issue by vorlonempire** [vergecurrency/VERGE#226]
![decode](https://user-images.githubusercontent.com/7526868/34470622-d98efb4c-ef35-11e7-9488-8834a45a3439.png)
I tried to resize the windows, hitting button again, but it wont do any good.

Windows 10, gtx 970, latest drivers

**Comment by justinvforvendetta** [comment]
was already fixed in the source code earlier

**Comment by JSBachForSoulCleansing101** [comment]
Does that mean we have to download the wallet again, or is there an update or patch?...That is, should we just wait for most or all bugs to be ironed out or can the fixes be applied piecemeal to the wallets that we already have on our computers?

**Comment by justinvforvendetta** [comment]
if you are running directly from this repository then you can just update, otherwise we'll push a new set of binaries and up the minor version soon
