### ISSUE TITLE
GIVE THE COMMUNITY A REAL DEADLINE AND STOP YOUR BULLSHIT JUSTIN

### ISSUE THREAD

**Issue by MoonChild1234** [vergecurrency/VERGE#230]
you are an adult man, stop playing video games when you are holding 2 BILLION of peoples money in your hands.

**Comment by mybrainmelted** [comment]
dude you are an adult, and a completely ignorant one at that fact. get the fuck out of here with your bullshit comments this board is for legit dev purposes, twat

also understand that justin said the wraith PROTOCOL was complete and IT WAS and posted source IN TIME. all of your beliefs about deadlines and bullshit are complete speculation driven by twitter and reddit community and im sorry you bought in at alltime high and expected overnight lambo. 

this goes for everyone wanting to post BS and banter on this board: fuck off and let the devs work.

**Comment by MoonChild1234** [comment]
legit dev purposes? tell me 1 legit thing about this launch, just 1 please

**Comment by justinvforvendetta** [comment]
hey @MoonChild1234 go fuck yourself, thanks.
