### ISSUE TITLE
QT x64 Update after bug fixes?

### ISSUE THREAD

**Issue by d3v3agl3** [vergecurrency/VERGE#231]
Curious if i bring in the QT x64 wallet now, once all kinks have been worked out will i need to bring in a new config file or source code etc for it to correct current issues?

**Comment by pcp1985** [comment]
I am not a programmer, however, i wish to support the verge team. May I know if anyway I can help you guys.

**Comment by jderwish** [comment]
You don't need to bring new config file, if you are using windows. just run the new QT executable :-)

**Comment by ekryski** [comment]
Ya you shouldn't need to bring in any new config file. In general this is release is backwards compatible.

@justinvforvendetta you can close this I think.
