### ISSUE TITLE
Creating New Address and Stealth address in Ubuntu

### ISSUE THREAD

**Issue by nkazier** [vergecurrency/VERGE#232]
Issue with creating new address.  Creating receiving address functionality works, but not creating a new sending address.  See screen shot. Also no tools to encrypt or backup wallet, assumed this is due to creating address functionality.

![screenshot from 2018-01-01 15-37-24](https://user-images.githubusercontent.com/34865074/34470914-dd28c796-ef09-11e7-9770-3311bfd9a0c8.png)

**Comment by MoonChild1234** [comment]
Was this not suppose to be tested before the XVG team tweeting that it will be done on time? Or before you telling the world that you will be done on time? this is such fraud...

**Comment by nkazier** [comment]
Please @MoonChild1234 stop with your banter.  @justinvforvendetta please remove above, has no value to this issue.

**Comment by MoonChild1234** [comment]
I am asking a legitimate question, why should I stop? Why is it bad to ask a very legitimate question?

**Comment by MoonChild1234** [comment]
@nkazier we are forced to ask here, the marketing team is not responding to anything, they post promises on twitter they cannot keep so people are forced to ask on github. I know it's unprofessional to ask on github but unprofessionalism is met with unprofessionalism.

**Comment by justinvforvendetta** [comment]
i think i just fixed this, give me a minute as im testing it.

**Comment by nkazier** [comment]
@justinvforvendetta  Thanks! i knew the compile wasn't out, so i didn't know if you saw it

**Comment by justinvforvendetta** [comment]
look like this is fixed now.. had to make a few more changes

**Comment by nkazier** [comment]
@justinvforvendetta I am a idiot, you can close this out, I noticed you took away the Stealth Address button on the new pull. and i got it working.  Keep up the good work.  Still though nothing showing up for the encrypting or saving or backing up the wallet besides manually doing that in Linux.  is there supposed to be a menu bar like the Electrum wallet?

**Comment by justinvforvendetta** [comment]
yeah that part still needs a little work. just have one last fix for stealth and then ill move toward that.
