### ISSUE TITLE
new receiving address 

### ISSUE THREAD

**Issue by nferruzzi** [vergecurrency/VERGE#234]
When I try to create a new stealth address all I get is a "classic" address.

<img width="569" alt="screen shot 2018-01-01 at 21 23 19" src="https://user-images.githubusercontent.com/1319874/34471010-bf7bc30e-ef3d-11e7-836b-dc00923b1551.png">

<img width="972" alt="screen shot 2018-01-01 at 21 50 22" src="https://user-images.githubusercontent.com/1319874/34471016-d75afb2a-ef3d-11e7-91ab-934989316fbd.png">

Using the debug console I can generate a proper stealth address

**Comment by mybrainmelted** [comment]
there is already an open issue for this. please read before posting so as not to detract. ty

**Comment by nferruzzi** [comment]
@mybrainmelted well to be honest I did but I can't found it , can you point it to me please ? tnx

**Comment by nferruzzi** [comment]
works now with https://github.com/vergecurrency/VERGE/commit/141fbe765386bf44ec962f8897a9b8f994458e15 
you can close for me :) tnx
