### ISSUE TITLE
"Edit name" on secondary address also applies to primary address (in receiving address tab)

### ISSUE THREAD

**Issue by mybrainmelted** [vergecurrency/VERGE#235]
Under the receiving addresses tab, when performing name edit on a secondary address (right click + edit name) it also applies to the primary address as well.

Win 10 pro ver 1703 build 15063.786

VERGE-qt 4.0 v2.1.0.0-unk-beta

**Comment by djdevin** [comment]
Also reported in #118

**Comment by mybrainmelted** [comment]
also would like to note that enabling the checkbox "stealth address" for the secondary address will overwrite the existing primary receiving address name, and replace it with secondary.

**Comment by justinvforvendetta** [comment]
this stuff has been fixed already today
