### ISSUE TITLE
Translation to Portuguese (Brazil)

### ISSUE THREAD

**Issue by marianajo** [vergecurrency/VERGE#237]
I'd like to work on the Brazilian Portuguese translation of the wallet.
I just forked the project and I'm currently working on a file bitcoin_ptbr.ts, if that's ok.
If this feature is unwanted, just let me know asap @justinvforvendetta

**Comment by akramtariqkhan** [comment]
I vouch for you. Please paste your stealth address and i will send you 1500 XVG

**Comment by justinvforvendetta** [comment]
sure, go ahead =]

**Comment by x-warrior** [comment]
@marianajo may I help you on this? I can help translating and/or reviewing.

**Comment by marianajo** [comment]
sure, @x-warrior. I forked at https://github.com/marianajo/VERGE
I've just committed to the first chunk of translation. Feel free to review and modify and/or add more translations. You can do this at the same repository. Just let me know what piece you are working on so we don't translate the same lines twice ;)
Also, after everything is finished, I think it would be nice to squash the commits so we end up with one thing for the pull request. Is that ok?
Thanks for your interest.

**Comment by rafaeloliveiras** [comment]
Hi @marianajo I can help you too. I can review the translatons.

**Comment by rafaeloliveiras** [comment]
I finish the work and make a pull request.. Is that a problem? I not sleep for do this.

**Comment by rafaeloliveiras** [comment]
https://github.com/vergecurrency/VERGE/pull/303 - Done. I'm going to sleep now! Keep the evolution!

**Comment by x-warrior** [comment]
Hey @marianajo it seems @rafaeloliveiras did a lot of work already, do you mind to review his work too? I added a few suggestions on his PR.

**Comment by sohilparikh** [comment]
@marianajo  and @rafaeloliveiras, you both can use Atom "teletype" plugin which shares same file over the network, changes one's file when another is working and vice-versa. Sorry if you already know about this plug-in.

**Comment by x-warrior** [comment]
@justinvforvendetta what do we need to get this merged?

**Comment by jrsikors** [comment]
@justinvforvendetta will be merging translations soon.  closing.  reference pull #303
