### ISSUE TITLE
Wallet Unlock Code Error

### ISSUE THREAD

**Issue by LKfighter** [vergecurrency/VERGE#238]
Started with Verge-3.0 wallet, it was encrypted and locked. Upgraded to Verge-qt-4.0-win64 release. 

When sending a transaction, the application askes for unlock key. When provided, the application falsely says it’s the incorrect key. After pressing cancel, or the “X” in the corner, the application then proceeds to send the coins.

When purposefully using the wrong unlock key the wallet does not send the coins.

The unlock key is verified to be accurate, another pc which is running Verge-3.0 mirroring the same wallet does not have this issue.  Reverting to Verge-3.0 Wallet solves the issue.

**Comment by Fandussss** [comment]
Can confirm, Incorrect Passphrase message is given even when the correct passphrase is used.

**Comment by besnikl** [comment]
In that case just the Label in the form is the same for both cases and should be differentiated!

**Comment by vandercoin3d** [comment]
Confirmed. Is it supposed that, even with the error,  after opening the wallet, it should remain open even restarting the software or is it correct that the wallet is closed? Mine is closed after restarting.

**Comment by arranHarty123** [comment]
I believe this has happened for me on the mac version as well. unlock gives an error, but actually proceeds as expected after the error.

**Comment by germandude010** [comment]
I have wallet 3.0 and cant unlock it with my passphrase....tried changing passphrase and nothing worked. It still locked and can't send to another address.

**Comment by cmosse** [comment]
Created new wallet. Encrypted it and didnt accept my password after that. Can send coins however..

**Comment by LKfighter** [comment]
Fixed in latest release
