### ISSUE TITLE
Synchronizing with Network Error

### ISSUE THREAD

**Issue by ashamsinyc** [vergecurrency/VERGE#239]
Been logged into the wallet for about an hour now, and the synchronizing bar isn't moving at all despite having 1 gig internet speed and full bars. After 5 minutes it was 3.48% and now it's 2.17%. It's hovering around 40-50 thousand blocks downloaded. Would be good to know how long this should take or if this is an actual parsing error. 
<img width="778" alt="screen shot 2018-01-01 at 4 56 09 pm" src="https://user-images.githubusercontent.com/35013150/34471337-b5477172-ef14-11e7-8c65-1806990996ac.png">

**Comment by zze** [comment]
https://verge-blockchain.com/howto

**Comment by canselozcan** [comment]
Same issue on Windows version but downloading this blockchain file below link solved my problem
http://server2-qt-wallet_v3.0_verge-blockchain_2017-december-30.zip

**Comment by ashamsinyc** [comment]
thanks guys

**Comment by ashamsinyc** [comment]
also, isn't it smart to have the blockchain constantly updated by itself within the wallet, so that we don't have to keep manually adding new blocks

**Comment by justinvforvendetta** [comment]
i prefer letting it sync on its own. it only takes about a day. (vs bitcoin taking about 9 days)

**Comment by canselozcan** [comment]
cool

**Comment by canselozcan** [comment]
btw guys I know this is not exact place to ask you but, to be honestly lots of your supporter(even me :)  not sleeping as same as you last 3 days and wonder to know is there any light at the end of this tunnel.
We really believe in you, is there any official announcement till the end of this day to complete your Wraight release is done?

Thanks
Cansel
