### ISSUE TITLE
Unable to send from client.

### ISSUE THREAD

**Issue by zze** [vergecurrency/VERGE#240]
I received coin i sent to the client, its fully synced and has connections, but every time i try sending coin out says  "**Error transaction creation failed**" if i do sendtoaddress from debug window I get "**Error: Transaction creation failed (code -4)**"

if i do validateaddress from debug to the address it says 
 **{"isvalid" : true,"address" : "addressremoved","ismine" : false,"account" : "1"}**

**Comment by justinvforvendetta** [comment]
is your wallet locked/encrypted?

**Comment by zze** [comment]
unlocked and not encrypted

**Comment by zze** [comment]
![err1](https://user-images.githubusercontent.com/657191/34471502-61f6978c-ef19-11e7-8006-0b91c16429a9.jpg)

**Comment by justinvforvendetta** [comment]
can u try sending .5 to see if it does the same thing? this might be a leftover dust issue.

**Comment by zze** [comment]
ahah, alright that did it! thank you!
