### ISSUE TITLE
Passphrase error

### ISSUE THREAD

**Issue by vandercoin3d** [vergecurrency/VERGE#242]
After created, I can change the passphrase, but I can't use it to unlock my wallet or to send coins.
Windows 10.

**Comment by Fandussss** [comment]
I have noticed I get a Incorrect Passphrase error too, although it does in fact unlock my wallet. It is sending the Incorrect Passphrase message for both true and false.

**Comment by vandercoin3d** [comment]
Yes. You are correct. Tested here.

**Comment by vandercoin3d** [comment]
Error already reported in Wallet Unlock Code Error #238
