### ISSUE TITLE
VERGE COIN LEAKING IP's

### ISSUE THREAD

**Issue by cyberena** [vergecurrency/VERGE#243]
Hi JustForVendetta,

I came to check up on other thread that you semed to have locked out and deleted many of you original comments however luckily its all still saved in my email history logs.

Original thread here:
https://github.com/vergecurrency/VERGE/issues/147

You said this, which you deleted / edited:

![fraud](https://user-images.githubusercontent.com/55039/34472055-457fc1a8-ef93-11e7-8b0f-95bd48d8137d.jpg)

Then in the end of the tread you asked me to tell you whats wrong.. well  I cant tell you what you said seems false, either your a poor buggy developer who cant make deadline or this is a fraud
https://news.bitcoin.com/privacy-coin-verge-allegedly-leaking-users-ip-addresses/

I have the full conversation in email log in case anyone... or any lawyer, would like to review.

p.s. you want my time in reviewing and fixing your code , Im happy to do it.  My hourly rate is $200 / hour and Ill be needing a deposit of the full estimated quote.  Email me to get started.

**Comment by JazSingh** [comment]
Independent users have verified that the Wraith protocol does not leak IP-addresses. There is lots of (I hate to us this term) `fake news` floating around. If you found a leak, please provide an example (proof) and a way to reproduce this. If you are not a developer or have any relation to software development, simply go off GitHub.

**Comment by justinvforvendetta** [comment]
haha I've already fixed most of the bugs today actually, but thanks @cyberena

**Comment by lewis0001** [comment]
@cyberarena if you were in a job interview that paid $200/hr for coding, i think you should have been able to spot the comment section on that article which will tell you its fake.

**Comment by sciack76** [comment]
It grabs only the transaction ID's and add a random IP adress to it. FUD attempt.

**Comment by cyberena** [comment]
I can spot the code, however I dont work for free.  ;)

p.s. heres the leaks 

http://xvg.keff.org/

**Comment by sciack76** [comment]
we know that website. it is old fake news

**Comment by sasasavic82** [comment]
@cyberena ... I believe what you're doing is called extortion and blackmail :) ... and it carries more weight in the court... and your statements are now publicly accessible :)

$200/hr? that's pretty cheap for where I come from ....quite mediocre actually...

**Comment by leandrodeassis** [comment]
Reproduce the IP Leak, if you can

**Comment by jag959** [comment]
@cyberena your time should be spent fixing your shitty geocities looking website from the 90s.  Put your money where your mouth is and make a free contribution to this project and prove your good.  Pick any bug and give it a whirl... I DARE YOU!  Big props to the Dev team for busting ass during their holidays to make this project a success despite whiny bitches chasing a fast buck.

**Comment by CmplxStack** [comment]
@cyberena You again? haha calm yourself your intranet only crud query skills have no power here.

**Comment by tnick55** [comment]
John Mcafee get off here and stop dropping acid on a Monday. LOL

**Comment by justinvforvendetta** [comment]
obviously @cyberena hasnt seen the tor branch, or he'd know that the tor integration is 99% done XD

guessing he cant' code too well. also that "keff" site is HIGHLY inaccurate, since most of our users are on android, which is routed thru tor via a hidden service lol

**Comment by satrya-sabeni** [comment]
@cyberena Exactly who do you think you are? Are you still seriously not updated on that link? I don't mean to bash you but I haven't dived into on that deep and even I knew that.

**Comment by KevinMcClintock** [comment]
Gosh this guy is a faggot lol, he can't be worth much if he spends all his time writing this crap.
