### ISSUE TITLE
Windows wraith wallet issue when I try to decode a trasaction

### ISSUE THREAD

**Issue by JSBachForSoulCleansing101** [vergecurrency/VERGE#244]
Hi Verge Team.  Just downloaded the wraith windows wallet and wanted to decode a recent transaction that I made using my mobile tor android wallet.  I entered the transaction id in the correct box (btw had to drag it in, since there is not a paste option for the box).  Then I pushed the decode Icon and got some jumbled compressed information under the button.   I cant make it out because the letters and numbers are either compressed flat or cut off.  Please advise.

![image](https://user-images.githubusercontent.com/34946186/34472164-39191a32-ef10-11e7-8f88-f1c0eb707703.png)

**Comment by vorlonempire** [comment]
Already here under Bug in printing info about decoded transaction #226

**Comment by justinvforvendetta** [comment]
this has already been fixed today
