### ISSUE TITLE
Ubuntu Cosmetic issues thread - latest release

### ISSUE THREAD

**Issue by BlueManRising** [vergecurrency/VERGE#246]
Just a few cosmetic issues when you right click on Ubuntu. No functionality issues though. See attached screen shots.

![screenshot from 2018-01-01 19-59-06](https://user-images.githubusercontent.com/34865074/34472357-6b51722c-ef58-11e7-939c-60e1c2551b86.png)
![screenshot from 2018-01-01 19-59-38](https://user-images.githubusercontent.com/34865074/34472359-71340420-ef58-11e7-8514-89e6013b0c46.png)

**Comment by vorlonempire** [comment]
Windows version has the same issue

**Comment by mybrainmelted** [comment]
Can confirm issue when attempting to right click to paste when using "new address" button

Win 10 pro ver 1703 build 15063.786

VERGE-qt 4.0 v2.1.0.0-unk-beta

**Comment by canselozcan** [comment]
@nkazier  i faced this issue (not trying copy/paste scnario also click any dropdown menu ) all the time if i dont run as administrator user privilage VERGE-qt.exe.

**Comment by justinvforvendetta** [comment]
these are the only cosmetic issues left that i see

**Comment by revtex** [comment]
<img width="1011" alt="verge_-_wallet" src="https://user-images.githubusercontent.com/470146/34633740-22aca93c-f24c-11e7-9427-a7b1090571c2.png">
Can confirm its also an issue with v2.1.0.0-75fa380-beta running on Mac High Sierra

To add to it, adjusting column width in the wallet tab and address book tab does not work.
Moved from #381

**Comment by jrsikors** [comment]
Can anyone confirm of the cosmetic issues with Ubuntu are still there as of the latest release?

**Comment by jrsikors** [comment]
I just checked in the latest 4.0.2 ubuntu and couldn't duplicate .. feel free to re-open or comment if i'm incorrect  ... @positivism any thoughts ?

**Comment by Positivism** [comment]
My thoughts are you made me close it to test the quit error and now I have to reload the blockchain index. 🤔

**Comment by Positivism** [comment]
Give it a second and I'll screenshot. Single core loading.

**Comment by Positivism** [comment]
Oh this is ubuntu, close this.
