### ISSUE TITLE
OS X High Sierra Update Problem

### ISSUE THREAD

**Issue by burakim** [vergecurrency/VERGE#247]
Hey, I installed verge-wallet after installing boost library from brew package manager. It starts very well; however, my verge wallet is not syncing. I check my connection status, I have 0 alive connection. I gave permission to verge wallet from my os x firewall. Do you have suggestions?
![wraith_bug](https://user-images.githubusercontent.com/6698355/34472584-2ac0914a-ef33-11e7-9a0e-a398b4f65a03.png)

**Comment by vorlonempire** [comment]
https://verge-blockchain.com/howto
