### ISSUE TITLE
After copying blockchain, Verge is hanging, OSX High Sierra

### ISSUE THREAD

**Issue by burakim** [vergecurrency/VERGE#248]
I installed verge wallet to my os x high sierra, I was able to open application without any problem. I downloaded latest blockchain from https://verge-blockchain.com and then I followed macos instructions to copy new blockchain to my verge app.

When i click app icon, it starts with splash screen and then it comes to Loading Block Index, it hangs.
When I click verge icon in my lauchpad, it says application is not responding. I waited it like 20 min. 
I attached process detail view. What should I do?
![verge_hang_1](https://user-images.githubusercontent.com/6698355/34473104-85aac6ee-ef3c-11e7-9095-b793ba6cd5e1.png)

**Comment by burakim** [comment]
Solved. I am gladly able to connect VERGE network. Please mark this issue as solved.

**Comment by OChrome** [comment]
Mine is hanging on windows as well.  How did you solve the issue?

**Comment by burakim** [comment]
I waited for more than they suggested on the verge blockchain website and as soon as it finished, it started normally.

**Comment by OChrome** [comment]
Thanks for quick response.  I'll be more patient 👍

**Comment by ekryski** [comment]
Ya it takes a while and you don't get a lot of feedback. Going to go through some of these and start to create issues we can prioritize in the coming weeks.
