### ISSUE TITLE
Verge Blockchain installment Python Script

### ISSUE THREAD

**Issue by burakim** [vergecurrency/VERGE#252]
I had opened an issue about wallet sync problem for os x version. https://verge-blockchain.com/down address was suggested to me. I found that tutorial is more complicated and then I wrote a python script to make do steps automatically. Since I couldn't figure out where I should put python script in the repository, I didn't create a pull request. I hope it easy your installation work for os x.
Thanks.
[verge_blockchain_download.py.zip](https://github.com/vergecurrency/VERGE/files/1596849/verge_blockchain_download.py.zip)

**Comment by justinvforvendetta** [comment]
@burakim i made a repo just for it, feel free to make a pull request to https://github.com/vergecurrency/pychaindownload
