### ISSUE TITLE
Transaction fee dropdown is being cut off on OS X

### ISSUE THREAD

**Issue by ekryski** [vergecurrency/VERGE#259]
Minor UI defect.

![image](https://user-images.githubusercontent.com/599019/34479005-615e4412-ef61-11e7-83ba-1b3583e584d6.png)

**Comment by paradoxicalNL** [comment]
I can confirm this minor issue.

**Comment by mastergizmo** [comment]
Same on Windows
![strokesplus_2018-01-02_16-29-06](https://user-images.githubusercontent.com/961516/34488804-22aea8b4-efda-11e7-805c-44e8e3c6bca5.png)

**Comment by mike2lab** [comment]
ok just forked the branch in my local folder, can i fix this issue and pull it back ? sorry i  haven't use Github again

**Comment by justinvforvendetta** [comment]
fixed
