### ISSUE TITLE
Stealth addresses are being cut off in the UI

### ISSUE THREAD

**Issue by ekryski** [vergecurrency/VERGE#260]
They are being created properly but I'm not able to send to them through the UI on OS X because they are being truncated. Likely a minor issue with input params in Qt.

![image](https://user-images.githubusercontent.com/599019/34479067-c4183ad6-ef61-11e7-8ca7-299f0d5964a8.png)

**Comment by techpoy** [comment]
I think this is already taken care of.  The issue was field length and it has been increased to 80
https://github.com/vergecurrency/VERGE/blob/master/src/qt/forms/sendcoinsentry.ui

**Comment by dbtftw** [comment]
can't the addresses go up to 102? 
also i am seeing the same thing after compiling the latest commits

**Comment by djdevin** [comment]
compiled the very latest f756845fa  (on fedora 27, qt5) and this is still an issue

steath address is smYo9qAyzPhruMxYTUikM3jRyHWxDbR8m5ZyrLJ6nm6SWdMTRyW5o8Jmf89Gbs8PWL8Amaf9WXLb2MnzZJGPjF1ajjY2Vs7xXXBqzM

but I can only send to smYo9qAyzPhruMxYTUikM3jRyHWxDbR8m5Z (chopped off in Send UI)

**Comment by justinvforvendetta** [comment]
this was fixed in an upcoming pr
