### ISSUE TITLE
Translation to Ukrainian

### ISSUE THREAD

**Issue by Lildan** [vergecurrency/VERGE#261]
I've benefited from this project so much. Thank you verge family. 
This will be my small contribution to help Verge spread through the world.
If someone is willing to help me here is the fork https://github.com/Lildan/VERGE
First commits are in branch wallet-ua-localization

**Comment by jrsikors** [comment]
I think I just grabbed the file from you @lildan and did a pull request from my repository

In the future.. these are some good instructions for translation I found on another translation post:
You can use this steps:
1 - create a fork of the project
2 - when fork created, you go to src/qt/locale and create a file like bitcoin_gk.ts
3 - copy the original file in english into the bitcoin_gk.ts
4 - Translate the file in the tags 
5 - commit
6 - make a pull request

**Comment by Lildan** [comment]
I've already created a pull request for this back in January https://github.com/vergecurrency/VERGE/pull/313
Seems it just got lost.
But i don't mind if it is approved and merged with your PR.

**Comment by jrsikors** [comment]
nope my bad i missed it , was going through trying to match up issues to pull requests and i failed.

thanks !

**Comment by jrsikors** [comment]
closing issue, reference pull #313 , should be merged soon and hopefully released in next version.  Thank you again very much for your help !
