### ISSUE TITLE
Stealth transaction still failing on latest release 

### ISSUE THREAD

**Issue by dbtftw** [vergecurrency/VERGE#262]
When trying a to send a stealth payment via debug window i am seeing a new failure. this is a compile of the latest pull 

01:53:25  sendtostealthaddress smYiwwG7kThws5Mw9VNw6K4MbKmpeGs91dkgbrNRADEHRJh92Y4gNTCd7ttsqH2AAUcAsSwyxHZ2Dsr1DvmTo7iA5wwxukmeJtMVHj 2
-----
01:53:25
￼
Error: Transaction creation failed (code -4)
[debug.log.zip](https://github.com/vergecurrency/VERGE/files/1597293/debug.log.zip)

**Comment by Glibo** [comment]
Same issue, I also tried to do it over GUI but still 34. One more thing. When I went to char count, stealth address have 102 chars and when I looked at yours sendcoinsentry.ui it is 80. Regards

**Comment by modislaszlo** [comment]
12:08:36 sendtostealthaddress DSVLDDHcayNZwWDxaL3LqDKShwqGUkZfn5 0.3
12:08:36 value is type str, expected real (code -1)

Not sure how to test from GUI because there is no send as stealth button?(maybe I'm missing something)

**Comment by Glibo** [comment]
@modislaszlo it seems like you are using release version, to use new you need to build it on mac.

**Comment by pasrom** [comment]
please have a look at #200.

**Comment by justinvforvendetta** [comment]
The transaction is still rejected, its not being accepted into memory pool 
ERROR: CTxMemPool::accept() : nonstandard transaction type

**Comment by jderwish** [comment]
Is there an update on this issue?

**Comment by justinvforvendetta** [comment]
we're working on that right now, did you have something to contribute @jderwish ?

**Comment by SsPerfuse** [comment]
@justinvforvendetta, apologize in an advance for the grammatical error. I am not anywhere near able to help you with coding but, is anything I can help you? i.e. crack down on FUD screamers, PR, administrative... I really hate being an observer of the most underrated crypto project, I just want to contribute.  Please let me know

**Comment by jderwish** [comment]
@justinvforvendetta I am downloading the github desktop and QT, will try to see if I am able to compile the code and check the code... it has been a while that I have not coded...so very rusty... but this project is very interesting and would love to assist if I could.

**Comment by jderwish** [comment]
@justinvforvendetta  how can I clone your code repo on the GitHub Desktop?

**Comment by TarangKhanna** [comment]
@jderwish go to https://github.com/vergecurrency/VERGE (main repo) and click clone option (in green and top right)

**Comment by jderwish** [comment]
Thanks, I just cloned using the App and It works now - so let me see if I can open this project on QT and compile it. any help would be appreciated @TarangKhanna

**Comment by TarangKhanna** [comment]
@jderwish I am just getting started as well, 1) will look around the code and see how Stealth transactions are working 2) will definitely look at sendtostealthaddress method 3) try to replicate the "not being accepted into memory pool ERROR: CTxMemPool::accept()" error. Would be great if anyone else can give us pointers too.

**Comment by jderwish** [comment]
How do I compile this and open this project in QT?

**Comment by TarangKhanna** [comment]
@jderwish compilation instructions are in the readme of the repo.

**Comment by jderwish** [comment]
@TarangKhanna there is no instruction for windows, just mac and ubuntu or linux

**Comment by TarangKhanna** [comment]
@jderwish no idea about windows side, you are right there are no instructions.

**Comment by jderwish** [comment]
@TarangKhanna I have to install ubuntu and go that route... certainly wanted to compile windows and test it.

**Comment by justinvforvendetta** [comment]
just get a virtualbox on your windows and run linux, much easier. also on linux you can cross compile for windows

**Comment by paradoxicalNL** [comment]
windows 10 supports linux tools for windows, works flawlessly here. you can
install ubuntu 16.10 as app and run bash shell

2018-01-03 4:06 GMT+01:00 sunerok <notifications@github.com>:

**Comment by jderwish** [comment]
Thanks @justinvforvendetta and @paradoxicalNL , I found the article for windows 10 supports running Ubuntu and going that route for now, but I definitely agree with @justinvforvendetta will install linux and run windows as a VM :-)

**Comment by justinvforvendetta** [comment]
ah @paradoxicalNL that sounds pretty fun actually. going to check that out

**Comment by paradoxicalNL** [comment]
you can start cmd and even execute bash from there. it's been my dream for
years, i can play games and use all the cool cli stuff without rebooting or
using VM. check it out

cheers

2018-01-03 4:19 GMT+01:00 sunerok <notifications@github.com>:

**Comment by jderwish** [comment]
@justinvforvendetta simple article to follow - works like a charm
http://www.zdnet.com/article/how-to-run-run-the-native-ubuntu-desktop-on-windows-10/

**Comment by jderwish** [comment]
@TarangKhanna @paradoxicalNL @justinvforvendetta Ubuntu Installed, now going to follow instruction to compile wallet and will inform you all.

**Comment by techpoy** [comment]
@TarangKhanna @paradoxicalNL @justinvforvendetta Installed ubuntu on windows 10. I have never run a build on ubuntu before. How to build for windows from here? ..thanks in advance

**Comment by techpoy** [comment]
will these steps

Install the dependencies. Note: If you are on debian, you will also need to apt-get install libcanberra-gtk-module.

sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install \
    libdb4.8-dev libdb4.8++-dev build-essential \
    libtool autotools-dev automake pkg-config libssl-dev libevent-dev \
    bsdmainutils git libboost-all-dev libminiupnpc-dev libqt5gui5 \
    libqt5core5a libqt5webkit5-dev libqt5dbus5 qttools5-dev \
    qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev
Clone the git repository and compile the daemon and gui wallet:

git clone https://github.com/vergecurrency/verge && cd verge && ./autogen.sh && ./configure && make

give me the binaries for windows platform as well?

**Comment by jderwish** [comment]
Yupe

**Comment by jderwish** [comment]
That's what I am following now and going well so far

**Comment by jderwish** [comment]
Question is does the transactions goes thru with this error message ?

**Comment by justinvforvendetta** [comment]
@jderwish what error message are you getting

**Comment by jderwish** [comment]
@justinvforvendetta I have not reached there yet, but was reading about this error on old GitHub issues related to original Bitcoin wallet and that's why was asking.

**Comment by jderwish** [comment]
Possible issue with SSL

https://github.com/mastercoin-MSC/mastercore/issues/272

**Comment by justinvforvendetta** [comment]
that doesnt look related

**Comment by jderwish** [comment]
While compiling, few warning signs..possible typos?

**Comment by jderwish** [comment]
Smessage.cpp file and sendcoindialog.cpp

**Comment by jderwish** [comment]
smessage.cpp: In function ‘bool ScanChainForPublicKeys(CBlockIndex*)’:
smessage.cpp:2140:59: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
     printf("Took %"PRId64" ms\n", GetTimeMillis() - nStart);
                                                           ^
smessage.cpp: In function ‘bool SecureMsgScanBuckets()’:
smessage.cpp:2319:59: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
     printf("Took %"PRId64" ms\n", GetTimeMillis() - mStart);
                                                           ^
smessage.cpp: In function ‘int SecureMsgSetHash(unsigned char*, unsigned char*, uint32_t)’:
smessage.cpp:3295:111: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long in
’ [-Wformat=]
             printf("SecureMsgSetHash() failed, took %"PRId64" ms, nonse %u\n", GetTimeMillis() - nStart, nonse);
                                                                                                               ^
smessage.cpp:3303:99: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
         printf("SecureMsgSetHash() took %"PRId64" ms, nonse %u\n", GetTimeMillis() - nStart, nonse);
                                                                                                   ^

**Comment by jderwish** [comment]
smessage.cpp: In function ‘bool ScanChainForPublicKeys(CBlockIndex*)’:
smessage.cpp:2140:59: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
     printf("Took %"PRId64" ms\n", GetTimeMillis() - nStart);
                                                           ^
smessage.cpp: In function ‘bool SecureMsgScanBuckets()’:
smessage.cpp:2319:59: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
     printf("Took %"PRId64" ms\n", GetTimeMillis() - mStart);
                                                           ^
smessage.cpp: In function ‘int SecureMsgSetHash(unsigned char*, unsigned char*, uint32_t)’:
smessage.cpp:3295:111: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long in
’ [-Wformat=]
             printf("SecureMsgSetHash() failed, took %"PRId64" ms, nonse %u\n", GetTimeMillis() - nStart, nonse);
                                                                                                               ^
smessage.cpp:3303:99: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
         printf("SecureMsgSetHash() took %"PRId64" ms, nonse %u\n", GetTimeMillis() - nStart, nonse);
                                                                                                   ^

**Comment by jderwish** [comment]
wallet.cpp: In member function ‘bool CWallet::ChangeWalletPassphrase(const SecureString&, const SecureString&)’:
wallet.cpp:121:10: warning: unused variable ‘fWasLocked’ [-Wunused-variable]
     bool fWasLocked = IsLocked();

**Comment by jderwish** [comment]
db/memtable.cc: In member function ‘void leveldb::MemTable::Add(leveldb::SequenceNumber, leveldb::ValueType, const leveldb::Slice&, const leveldb::Slice&)’:
db/memtable.cc:104:31: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   assert((p + val_size) - buf == encoded_len);

**Comment by jderwish** [comment]
util/bloom.cc: In member function ‘virtual void leveldb::{anonymous}::BloomFilterPolicy::CreateFilter(const leveldb::Slice*, int, std::__cxx11::string*) const’:
util/bloom.cc:50:26: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (size_t i = 0; i < n; i++) {
                          ^

**Comment by jderwish** [comment]
util/logging.cc:58:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
           (v == kMaxUint64/10 && delta > kMaxUint64%10)) {
                                        ^

**Comment by jderwish** [comment]
qt/sendcoinsdialog.cpp: In member function ‘void SendCoinsDialog::on_sendButton_clicked()’:
qt/sendcoinsdialog.cpp:120:11: warning: enumeration value ‘NarrationTooLong’ not handled in switch [-Wswitch]
     switch(sendstatus.status)
           ^

**Comment by jderwish** [comment]
make[1]: Leaving directory '/root/VERGE'
go.sh: 187: go.sh: pactl: not found
go.sh: 187: go.sh: pactl: not found
go.sh: 187: go.sh: pactl: not found
go.sh: 187: go.sh: pactl: not found
go.sh: 187: go.sh: pactl: not found
go.sh: 191: go.sh: pactl: not found
go.sh: 192: go.sh: pactl: not found
go.sh: 193: go.sh: padsp: not found
go.sh: 195: go.sh: pactl: not found

**Comment by hankthornlee** [comment]
@jderwish I would suggest that you cat the logs to a file much more productive that way.

**Comment by hankthornlee** [comment]
@jderwish I would suggest you direct output of this to a file and submit that, more productive. 

https://askubuntu.com/questions/420981/how-do-i-save-terminal-output-to-a-file

**Comment by justinvforvendetta** [comment]
yeah this just turned into a huge mess quickly lol

**Comment by jderwish** [comment]
Update: You need Ubuntu GNOME as prerequisite for Verge wallet - since it is loading GUI Wallet.
