### ISSUE TITLE
Enhancement Request: Add timestamps to debug logs

### ISSUE THREAD

**Issue by dbtftw** [vergecurrency/VERGE#263]
it would be helpful in debugging to have timestamps int he debug logs.

**Comment by Max-Meldrum** [comment]
Very new to the code base, but seems like there is a flag for this from the bitcoin code? 

`./VERGEd -logtimestamps`

I Tested it and the rows gets timestamped.

**Comment by Max-Meldrum** [comment]
@dbtftw did you try it out? 
@justinvforvendetta  perhaps this issue could be closed?

**Comment by dbtftw** [comment]
Ive been launching from the UI lemme try.
