### ISSUE TITLE
Port mapping may be failing [error in debug logs]

### ISSUE THREAD

**Issue by dbtftw** [vergecurrency/VERGE#264]
noticed this in debug logs 

AddPortMapping(21102, 21102, 192.168.1.19) failed with code 402 (Invalid Args)

[debug.log.zip](https://github.com/vergecurrency/VERGE/files/1597342/debug.log.zip)

**Comment by canselozcan** [comment]
Hi,

Can u share me your NEtwork option screenshots which is given below 
![image](https://user-images.githubusercontent.com/35013322/34482287-0c66bfd6-efc8-11e7-9e7f-b965df0e2859.png)


Thanks

**Comment by willwhite1** [comment]
I'll investigate further, but found the following -

https://github.com/dogecoin/dogecoin/issues/16

This suggests that the extra argument seen at line 1055 in net.cpp is required in v1.5 of miniupnpc as well as v1.6.

https://github.com/miniupnp/miniupnp/blob/master/miniupnpc/apiversions.txt

The API notes for 1.5 do also mention this as being the case. Perhaps this clause is now redundant and constructor is consistent between 1.5 and 1.6

**Comment by dbtftw** [comment]
Here is my screenshot. 
<img width="660" alt="screen shot 2018-01-02 at 1 14 45 pm" src="https://user-images.githubusercontent.com/24704287/34500318-176df2fe-efbf-11e7-8e1f-12030001de33.png">

**Comment by jrsikors** [comment]
spring cleaning -- please re-open or open new issue if this is still a problem in the latest release.
