### ISSUE TITLE
BlockChain Explorer - Font Size

### ISSUE THREAD

**Issue by mastergizmo** [vergecurrency/VERGE#266]
The text in the BlockChain Explorer is too small to read and selecting&copy text is not working. So you have no chance to read the data.

![strokesplus_2018-01-02_16-33-13](https://user-images.githubusercontent.com/961516/34489102-1f2ac12c-efdb-11e7-87f1-f67eacd13d16.png)

**Comment by justinvforvendetta** [comment]
this has already been fixed
