### ISSUE TITLE
Translation to French

### ISSUE THREAD

**Issue by gukak** [vergecurrency/VERGE#268]
I'm willing to help,
I started working on a French translation.
Forked the project and started working in https://github.com/gukak/VERGE

in /src/qt/locale/bitcoin_fr.ts

Please let me know if any concern ;)

**Comment by gukak** [comment]
I will :)

Le 2 janv. 2018 6:35 PM, "davecummins2000" <notifications@github.com> a
écrit :

**Comment by gukak** [comment]
BTW, I will push the PR once ready.
Sorry not so familiar with github, even if I used to be a developer in the old times ;) always good to participate to something cool, which I'm sure will change (a bit) the world ;)

**Comment by fireeffects** [comment]
I already started translating to french, kinda forgot to create an issue. I'm new to github, is there a way we can both work on the same file ( it says I don't have writing permissions on yours ) ?

**Comment by gukak** [comment]
Let me push the pull request ;)

**Comment by IsmaElzem** [comment]
I'll try to help you guys =)

**Comment by gukak** [comment]
PR: https://github.com/vergecurrency/VERGE/pull/275
not totally sure on how to best collaborate on this file ?

2018-01-02 21:39 GMT+01:00 IsmaElzem <notifications@github.com>:

**Comment by IsmaElzem** [comment]
@justinvforvendetta hwo can we help to translate this ? :)

**Comment by mnott** [comment]
If needed, I'm a native speaker for French, too.

**Comment by gukak** [comment]
you can probably fork my repo on github, pull request on mine, and then
It'll reflect, right ?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-01-02 22:03 GMT+01:00 mnott <notifications@github.com>:

**Comment by fireeffects** [comment]
I don't think you can fork a fork.

**Comment by wertzuiop123** [comment]
Do you need other languages actually? could do german but dont know in which files
