### ISSUE TITLE
Translation to Portuguese (Portugal) pt_PT

### ISSUE THREAD

**Issue by joseluislopesdias** [vergecurrency/VERGE#269]
I'm working on the Portuguese (pt_PT) translation of the new wallet. Keep up the great work!

**Comment by joseluislopesdias** [comment]
Going good. Have a great day! In Verge we trust.

**Comment by jrsikors** [comment]
Did you ever have a chance to continue and finish this?  No rush, just curious and looking at old issues.

**Comment by joseluislopesdias** [comment]
Yes, slowly but almost complete. Maybe next week it will be done.

A sábado, 24/03/2018, 23:29, Jeff S <notifications@github.com> escreveu:

**Comment by jrsikors** [comment]
Awesome, again , no rush!  Take all the time you need :smile: 

Let us know if you have trouble with the pull request.  Here are the steps just in case you need:
instructions for translation
You can use this steps:
1 - create a fork of the project
2 - when fork created, you go to src/qt/locale and create a file like bitcoin_gk.ts
3 - copy the original file in english into the bitcoin_gk.ts
4 - Translate the file in the tags 
5 - commit
6 - make a pull request

Thanks for your help !

**Comment by joseluislopesdias** [comment]
Thank you!

Melhores cumprimentos,

José Luís Lopes Dias


2018-03-24 23:35 GMT+00:00 Jeff S <notifications@github.com>:

**Comment by jrsikors** [comment]
will go ahead and close this one out.  No worries !  Just do a pull request whenever you are ready !  Or post here if you have any further questions for me and I'll likely respond!
