### ISSUE TITLE
SOLO mining shows no results on OSX despite active hashrate

### ISSUE THREAD

**Issue by dbtftw** [vergecurrency/VERGE#277]
I starting mining by creating a VERGE.Conf. which included gen=1

-- Conf -- 
rpcpassword=85CpSuCNvDcYsdQU8w621mkQqJAimSQwCSJL5dPT9wQX
rpcport=20102
port=21102
daemon=1
algo=x17
gen=1

I entered debug console and verified that the getmininginfo had generate true and a hashrate. 

=> getmininginfo

13:07:21
{
"blocks" : 1769878,
"currentblocksize" : 1919,
"currentblocktx" : 4,
"pow_algo_id" : 1,
"pow_algo" : "x17",
"difficulty" : 6801.68210475,
"difficulty_x17" : 6801.68210475,
"difficulty_scrypt" : 50792.37635706,
"difficulty_groestl" : 542867.39534509,
"difficulty_lyra2re" : 71857.14840221,
"difficulty_blake" : 2515851.08142060,
"errors" : "",
"generate" : true,
"genproclimit" : -1,
"hashespersec" : 146102,
"pooledtx" : 9,
"testnet" : false
}

Let the Wallet open overnight, came back to the same balance. Maybe I don't know how this is expected to work, but it look likes it mines overnight, where did all the verge go?

**Comment by mnott** [comment]
Where exactly did you even create that VERGE.Conf? And what is rpcpassword etc.? I must have missed the exact description on how to do that mining. I just see the README.md which says to change the .conf file... (which ever that is).

**Comment by dbtftw** [comment]
on a mac its /Users/<USER>/Library/Application\ Support/VERGE/verge.conf

As for the values i do not know what they are, I couldn't find any documentation. So I was hoping a dev could share a spec or intended behaviors.

**Comment by mike2lab** [comment]
just creating the .conf file it'll "generate" : true ?

**Comment by aetherpirate** [comment]
My understanding is that the odds are vastly against solo-miners turning up much, even if you left it going for days, unless you have a bank of computers at home with powerful GPU's.

**Comment by dbtftw** [comment]
@mike2lab adding gen=1 to the conf is what turns on mining.

**Comment by mike2lab** [comment]
@dbtftw ok, and the rpcpassword=85CpSuCNvDcYsdQU8w621mkQqJAimSQwCSJL5dPT9wQX ?

**Comment by dbtftw** [comment]
@aetherpirate thats seems right. if we can get a dev confirmation its working as expected. Then im good to close. Seems like a silly feature then if not fruitful.

**Comment by mnott** [comment]
OK, created the file there, what are those rpcpassword options?

Also, looking at the log, I see lots of

trying connection 138.201.91.159:21102 lastseen=82,7hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=72,8hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=72,8hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=82,7hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=73,5hrs

**Comment by dbtftw** [comment]
@mnott that looks like #258 or #264 check that your ports are open

**Comment by mike2lab** [comment]
@dbtftw maybe it has first to sync before the mining can be set to true?
![screen shot 2018-01-03 at 00 05 11](https://user-images.githubusercontent.com/34998751/34501927-cd7fb51e-f019-11e7-858b-82870dac0246.png)

**Comment by mnott** [comment]
@dbtftw I don't know. I've set no specific firewall rule on my network; and also, if I just connect using tethering to my mobile phone, I can not telnet 98.5.123.15 21102 either. I can telnet 98.5.123.15 80 though. I've set no firewall rule on MacOS. How to specifically check where it breaks?

**Comment by justinvforvendetta** [comment]
there is no way you're going to find blocks solo mining with gen=1 as that uses the cpu
