### ISSUE TITLE
Dutch Translation

### ISSUE THREAD

**Issue by AhmetCann** [vergecurrency/VERGE#278]
Working on a Dutch translation

Link to Fork: https://github.com/AhmetCann/VERGE
Link to File: https://github.com/AhmetCann/VERGE/blob/master/src/qt/locale/bitcoin_nl.ts

**Comment by JohnJohnssonnl** [comment]
Hi Ahmet, Great to see a fellow dutchman working to help with the Verge translations. I made some comments in the file, use them as you see fit :)

**Comment by AhmetCann** [comment]
@JohnJohnssonnl Thanks for your comments I'll look in to them right now.

**Comment by JazSingh** [comment]
@AhmetCann Nice work! You can create a pull request from your fork to this repo.

**Comment by KevinMcClintock** [comment]
Waarom?  XD
