### ISSUE TITLE
Old logo icon on mac-os.

### ISSUE THREAD

**Issue by Vadim-Podlevsky** [vergecurrency/VERGE#281]
<img width="85" alt="2018-01-03 01 43 05" src="https://user-images.githubusercontent.com/1458033/34504542-d085ead6-f027-11e7-8e70-6431458d1429.png">

**Comment by justinvforvendetta** [comment]
want to submit a new .icns file? all of the graphics can be found https://github.com/vergecurrency/verge-graphics

**Comment by dbtftw** [comment]
Submitted a mac styled icon in the graphics repo 
<img width="604" alt="screen shot 2018-01-02 at 4 23 16 pm" src="https://user-images.githubusercontent.com/24704287/34505366-a83473de-efd9-11e7-8388-14d299329238.png">

**Comment by justinvforvendetta** [comment]
the .icns file here is what needs to be changed, it has a few sizes inside it @dbtftw

**Comment by dbtftw** [comment]
Yep. I wanted to kind of get community approval before making a .icns. I will put some together now

**Comment by dbtftw** [comment]
ICN and Full icons set attached. I have limited Git experience so i would prefer not to submit myself. 

[Wraith_Icons.zip](https://github.com/vergecurrency/VERGE/files/1599193/Wraith_Icons.zip)

**Comment by dbtftw** [comment]
Here are sample of what it looks like 
<img width="194" alt="screen shot 2018-01-02 at 5 39 32 pm" src="https://user-images.githubusercontent.com/24704287/34506694-eec417dc-efe3-11e7-8718-99bd32a5a324.png">
<img width="389" alt="screen shot 2018-01-02 at 5 39 22 pm" src="https://user-images.githubusercontent.com/24704287/34506695-f0ac4a2e-efe3-11e7-9e79-279dfd02b2d3.png">

**Comment by mjanveaux** [comment]
Awesome! I'll create the relevant PR's

**Comment by dbtftw** [comment]
@mjanveaux. No need I already submitted and it has been merged.

**Comment by ekryski** [comment]
This can be closed. It's in the next release and is looking sexy AF
