### ISSUE TITLE
No Comunication Plan 

### ISSUE THREAD

**Issue by jcodemad** [vergecurrency/VERGE#282]
Write code never make a company great, having go ideas and team in place do build them and communicate very clear is what makes the difference.

# ## **Steve Job never need to assemble Iphone pieces but he has a vision, Verge also but**

Investors (whales) don't care about github, they don't understand these things,
Hire a real PR team and make sure they work side by side with the DEV team.
Hire more developers, and post on twitter showing you're hiring and growing as a team.

Realize you are a project currently valued in over a BILLION DOLLARS, please give the impression you are one so that the investors from Korea and Japan are willing to dump some more Millions your way.

**Comment by joaomscosta1** [comment]
Thank you sir.

**Comment by justinvforvendetta** [comment]
not sure if you saw our tweets, but we made a release, and then another about how we are making updates. thanks.

**Comment by bitness247** [comment]
It's the community turn to push tweets , make youtube videos , **tutorials** etc. Why hire some one to talk about the product when everybody holding it can do it for free. Please , dont forget its not pre-mined and no ICO.  Are you going to pay someone to do it?! 

A solid project like this , man , its only a matter of time until Big names mentions it.

**Comment by fr4z3n** [comment]
@justinvforvendetta
I saw the tweets. It's not about hyping.
I had to read between the lines if wraith is released or not. 
There was no tweet like
'Wraith is released 4.0 version'
And I had to register on twitter to follow it.
It was not mentioned on facebook sadly

**Comment by bharadwaj003** [comment]
@justinvforvendetta
Please create one new teaser similar to the previous one :  
https://youtu.be/dMrk6rozbJg
That might bring back some lost confidence on this awesome project

**Comment by dangry** [comment]
@justinvforvendetta As @fr4z3n points out there was no clear information about it, I just came to know that V4 is actually released, actually, this release isn't even listed on the website.

**Comment by bitness247** [comment]
@bharadwaj003 or maybe ## **YOU** could translate this video in your language and share it to the community ? Might be a good idea to let the dev do the hard **coding** while normies like us do the easy pizzy stuff , dont you think?

**Comment by Cindawg** [comment]
@justinvforvendetta clear Comms from you guys like the proposed twitter update will provide clarity to the Verge community, plus act as a signal for 3rd parties to scrutinise and review the product. 

As the product is good and delivers on its stated goals the reviews will be good, this will lead to positive reviews by 3rd party's and widespread adoption of the coin.

You've done great work coding Wraith now communicate it effectively to current stakeholders (community) and future stakeholders (public). Please reconsider your position against releasing an official statement as it is currently not clear from the social media channels that a working Wraith Protocol is out and ready for public consumption.

A loyal Verge community member ✌️

**Comment by AceTech07** [comment]
Why are so many people telling a grown ass man how he should run his
business. I just don't get.  I'm a holder that literally have all my cash
in verge.  Am I the only one not panicking? I don't need to hear nothing.
I'm ol school.  Action speak louder then words.
