### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by wertzuiop123** [vergecurrency/VERGE#284]
Working on german translation. Will upload the file here then (im pretty new on github)

**Comment by benammann** [comment]
1. create a fork
2. clone the fork ( it would be wertzuiop123/VERGE )
3. translate
4. push
5. create a merge request

https://gist.github.com/MarcDiethelm/7303312

thanks for helping out ! 👍

**Comment by kyzrfranz** [comment]
@wertzuiop123 already on it - how far r u?
https://github.com/kyzrfranz/VERGE/commit/1bb3b86d5bc87d19263d4b57cf270a1b9999a889

**Comment by wertzuiop123** [comment]
Hey, had to sleep :) Have 80%

**Comment by kyzrfranz** [comment]
alright - then no sense merging with my stuff, i'll stop and let you finish - if u need help let me know

**Comment by wertzuiop123** [comment]
Thanks :)

Im finished. Made a Push request. Dont know if has worked
https://github.com/gukak/VERGE/pulls

**Comment by jrsikors** [comment]
https://github.com/vergecurrency/VERGE/pull/311

**Comment by jrsikors** [comment]
pull number: https://github.com/vergecurrency/VERGE/pull/311

closing issue -- should be merged soon ..  Thank you for the assistance everyone !
