### ISSUE TITLE
Message for DEV's

### ISSUE THREAD

**Issue by Crypdonate** [vergecurrency/VERGE#286]
I sent an email through your site. 

I have something that will Guarantee Verge through $10 by march. I am not looking for anything in return. It will partner with Wraith perfectly. Already complete and glitch free. coding available for review.

If you have ten minutes for a conference call, you can tell me to fuck off if you do not like what you hear, please email me at vergeto10@gmail.com. I just set this up awaiting your response.

**Comment by ksteigerwald** [comment]
You have no github commits, and your trying to do sales work with a blank resume?

**Comment by Crypdonate** [comment]
no. i am not a developer. I have a team of developers. i am reaching out as i believe in the vision XVG has.

**Comment by AceTech07** [comment]
Lol
