### ISSUE TITLE
mac wallet hangup

### ISSUE THREAD

**Issue by ChiefCeko** [vergecurrency/VERGE#291]
mac 10.13.1

loading window appears, "loading block index...", wheel of death, window disappears, nothing happens. app shows active in dock, need to kill

**Comment by dbtftw** [comment]
It takes 5-10 minutest to load currently 

this is a dupe of #192

**Comment by satrya-sabeni** [comment]
You just need wait. It really looks like the rainbow ball of death and that it crashed but it didn't.

**Comment by ChiefCeko** [comment]
thanks, worked out!

**Comment by techpoy** [comment]
@ChiefCeko  Please close this issue.
