### ISSUE TITLE
After a failed stealth transaction my Balance is incorrect. 

### ISSUE THREAD

**Issue by dbtftw** [vergecurrency/VERGE#296]
Tried to send myself a stealth transaction. Transaction failed and now my balance is off. I should only have like 3 XVG 
<img width="890" alt="screen shot 2018-01-02 at 9 34 21 pm" src="https://user-images.githubusercontent.com/24704287/34509978-e462079c-f004-11e7-8fa1-affcea9f1513.png">

<img width="894" alt="screen shot 2018-01-02 at 9 34 29 pm" src="https://user-images.githubusercontent.com/24704287/34509965-cd77d822-f004-11e7-9d43-76a306fbc67f.png">
[debug.log.zip](https://github.com/vergecurrency/VERGE/files/1599470/debug.log.zip)

**Comment by dbtftw** [comment]
I should mention this is the latest commits

**Comment by justinvforvendetta** [comment]
paste the snippet of debug log that is relevant

**Comment by dbtftw** [comment]
SetBestChain: new best=7d0d9ad6f3ea8d324ca8  height=1770724  trust=1770725  date=01/03/18 05:02:35
ProcessBlock: ACCEPTED (groestl)
NotifyAddressBookChanged smYkdvWf2z6RdM7BNrgJvtzyfJ52MpwBKREamGxKfp3WpHLBMHdqGfURFFMiNop2HSnSAJsgNP8QvfLW8kPx2ev29bSqge9AEJVw2x STEALTH TEST isMine=1 status=0
getblocks -1 to 00000000000000000000 limit 500
getblocks -1 to 00000000000000000000 limit 500
Flushing wallet.dat
Flushed wallet.dat 21ms
getblocks -1 to 00000000000000000000 limit 500
CTxMemPool::accept() : accepted d6515204c8 (poolsz 5)
received getdata for: tx d6515204c8c056295d07
getblocks 1623374 to 97cfeeb01464937ca979 limit 500
  getblocks stopping at limit 1623873 0000000000093205ce1b
received getdata for: tx d6515204c8c056295d07
received getdata for: tx d6515204c8c056295d07
SendStealthMoney() : Error: Transaction creation failed  CTxMemPool::accept() : accepted e9dcfc5722 (poolsz 6)

**Comment by dbtftw** [comment]
Will do. going forward. This issue is from commit a7a5c8440e6323a155b4767d38a0e81c9ee06b0f

**Comment by justinvforvendetta** [comment]
SendStealthMoney() : Error: Transaction creation failed CTxMemPool::accept() : accepted e9dcfc5722 (poolsz 6)

thats really odd. have you closed and re opened? or tried a reindex and see what happens?

**Comment by dbtftw** [comment]
Yes. closed and let it sync. Issue persists. 

VERGE version v2.1.0.0-a7a5c84-beta (2018-01-02 23:15:21 -0500)
Using OpenSSL version OpenSSL 1.0.2n  7 Dec 2017
Startup time: 01/03/18 07:17:42
Default data directory /Users/davidbt/Library/Application Support/VERGE
Default mining hash algorithm: scrypt
Used data directory /Users/davidbt/Library/Application Support/VERGE
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/Users/davidbt/Library/Application Support/VERGE/database ErrorFile=/Users/davidbt/Library/Application Support/VERGE/db.log
Bound to [::]:21102
Bound to 0.0.0.0:21102
Loading block index...
Opening LevelDB in /Users/davidbt/Library/Application Support/VERGE/txleveldb
Transaction index version is 70509
Opened LevelDB successfully
LoadBlockIndex(): hashBestChain=01ba28485478c7c67cd18a5f7bd52a5152a039c9d93cb5d7150a3c0ae37a0c5d  height=1770945  trust=1770946  date=01/03/18 07:17:03
LoadBlockIndex(): synchronized checkpoint 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
Verifying last 2500 blocks at level 1
 block index          302810ms
Loading wallet...
nFileVersion = 2010000
 wallet                  221ms
Loading addresses...
Loaded 14484 addresses from peers.dat  21ms
mapBlockIndex.size() = 1780554
nBestHeight = 1770945
setKeyPool.size() = 108
mapWallet.size() = 4
mapAddressBook.size() = 4
ThreadDNSAddressSeed started
ThreadMapPort started
Loading addresses from DNS seeds (could take a while)
ThreadSocketHandler started
ThreadOpenAddedConnections started
ThreadOpenConnections started
ThreadOpenAddedConnections exited
ThreadMessageHandler started
accepted connection 5.165.220.104:61847
Done loading
ThreadStakeMinter started
CPUMiner started for proof-of-stake
ERROR: CTxMemPool::accept() : nonstandard transaction type
Added 1 addresses from 192.241.187.222: 4096 tried, 10388 new
Added 1 addresses from 46.127.57.167: 4096 tried, 10389 new
5 addresses found from DNS seeds
ThreadDNSAddressSeed exited
accepted connection 95.90.217.209:9942
Flushed 14485 addresses to peers.dat  12ms
accepted connection 64.254.40.131:54499
socket closed
disconnecting node 5.165.220.104:61847
accepted connection 196.52.39.2:55869
socket closed
disconnecting node 95.90.217.209:9942
accepted connection 68.13.167.208:61126
socket closed
disconnecting node 196.52.39.2:55869
send version message: version 90001, blocks=1770945, us=0.0.0.0:0, them=64.254.40.131:54499, peer=64.254.40.131:54499
Added time data, samples 2, offset -221 (-3 minutes)
Added 64.254.40.131:21102 from 64.254.40.131: 4096 tried, 10389 new
Moving 64.254.40.131:21102 to tried
receive version message: version 90001, blocks=113060, us=71.202.185.147:21102, them=64.254.40.131:21102, peer=64.254.40.131:54499
send version message: version 90001, blocks=1770945, us=0.0.0.0:0, them=68.13.167.208:61126, peer=68.13.167.208:61126
Added time data, samples 3, offset -123 (-2 minutes)
receive version message: version 90001, blocks=51957, us=71.202.185.147:21102, them=68.13.167.208:21102, peer=68.13.167.208:61126
trying connection 46.246.117.13:21102 lastseen=8.3hrs
connect() failed after select(): Connection refused
GetMyExternalIP() received [71.202.185.147] 71.202.185.147:0
GetMyExternalIP() returned 71.202.185.147
AddLocal(71.202.185.147:21102,4)
refreshWallet
trying connection 98.122.18.198:21102 lastseen=13.5hrs
UPnP: ExternalIPAddress = 71.202.185.147
AddLocal(71.202.185.147:21102,3)
AddPortMapping(21102, 21102, 192.168.1.19) failed with code 402 (Invalid Args)
connection timeout
trying connection 172.114.248.173:21102 lastseen=3.1hrs
connected 172.114.248.173:21102
send version message: version 90001, blocks=1770945, us=71.202.185.147:21102, them=172.114.248.173:21102, peer=172.114.248.173:21102
Added time data, samples 4, offset +0 (+0 minutes)
trying connection 83.85.157.97:21102 lastseen=5.8hrs
receive version message: version 90001, blocks=1770957, us=71.202.185.147:53595, them=172.114.248.173:21102, peer=172.114.248.173:21102
received block 80d3f08d96d56e09dd27
SetBestChain: new best=80d3f08d96d56e09dd27  height=1770946  trust=1770947  date=01/03/18 07:18:13
ProcessBlock: ACCEPTED (groestl)


<img width="1284" alt="screen shot 2018-01-02 at 11 23 20 pm" src="https://user-images.githubusercontent.com/24704287/34511993-210410d2-f014-11e7-910a-c88714429f74.png">

**Comment by NERON** [comment]
@justinvforvendetta maybe we should insert printf before each "return false" in CreateTransaction function? It will help determine why error happen..

**Comment by dbtftw** [comment]
interesting i sent a payment NON stealth to myself. Log shows a correct balance 

CTransaction(hash=0b32e58c71, nTime=1514964352, ver=1, vin.size=1, vout.size=2, nLockTime=0)
    CTxIn(COutPoint(07ae17a349, 0), scriptSig=3045022100ded4b5b64d6704)
    CTxOut(nValue=3.70, scriptPubKey=OP_DUP OP_HASH160 f32fc5fb3d1adb8ec42b0a973313e14ac94a0d0d OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(nValue=1.00, scriptPubKey=OP_DUP OP_HASH160 bdf578992f9b4b0c295b93a0d4b0668003e83978 OP_EQUALVERIFY OP_CHECKSIG)
AddToWallet 0b32e58c71  new
**WalletUpdateSpent found spent coin 4.80 XVG** 07ae17a349012e06d70d3acba6728282d85d13f92d17db6bf89c4ccda58494ba
NotifyTransactionChanged 07ae17a349012e06d70d3acba6728282d85d13f92d17db6bf89c4ccda58494ba status=1
NotifyTransactionChanged 0b32e58c71fe34448c3e08d79fe14ce9aca4c47e4f77baf414b3a469eafa0773 status=0
NotifyTransactionChanged 07ae17a349012e06d70d3acba6728282d85d13f92d17db6bf89c4ccda58494ba status=1
CTxMemPool::accept() : accepted 0b32e58c71 (poolsz 10)

**Comment by pasrom** [comment]
i think its only working on the testnet:
https://github.com/vergecurrency/VERGE/blob/8d1bd624c47f3c1643b137d2579d6766e8eae2ff/src/main.cpp#L650

**Comment by techpoy** [comment]
Is  this probably the final issue we are looking at?

**Comment by techpoy** [comment]
Any update on this guys?

**Comment by fradelo** [comment]
@justinvforvendetta give a look on @pasrom comment i think he is on the spot

**Comment by dbtftw** [comment]
Same issue with latest commit b97f4dda4db7b3de6e6cca3de0c11be8d719e6b4

However the looks look different and contain more info-- Full log attached 
[debug.log.zip](https://github.com/vergecurrency/VERGE/files/1602556/debug.log.zip)


NotifyAddressBookChanged DDaQP2LJBWWWYgbFCs4zQzVuSL32G5uREW smYioHRhUKHxMN6CHvXAo8yTFtgCwhYUmwy4ZsQsy2RcAMhxHeWxu73AzmVCC6C3xmXxEP7qMKMSf2tyk4n46m4YV7qwUVJZ9rrrmd isMine=1 status=0
CommitTransaction:
CTransaction(hash=609482a8b0, nTime=1515045342, ver=1, vin.size=1, vout.size=3, nLockTime=0)
    CTxIn(COutPoint(0b32e58c71, 0), scriptSig=304402203800fb3006e8171f)
    CTxOut(nValue=2.60, scriptPubKey=OP_DUP OP_HASH160 4cb6cb2d815ebfb37e380834d645b05713108800 OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(nValue=1.00, scriptPubKey=OP_DUP OP_HASH160 5c8a4c4cfd1b654a7d4b77c48e1b027619cc675e OP_EQUALVERIFY OP_CHECKSIG)
    CTxOut(nValue=0.00, scriptPubKey=OP_RETURN 0254ce815ce0368abee041307ad8889eb518ecdcddabfac361fdbc40ee3de94c68)
AddToWallet 609482a8b0  new
WalletUpdateSpent found spent coin 4.70 XVG 0b32e58c71fe34448c3e08d79fe14ce9aca4c47e4f77baf414b3a469eafa0773
NotifyTransactionChanged 0b32e58c71fe34448c3e08d79fe14ce9aca4c47e4f77baf414b3a469eafa0773 status=1
NotifyTransactionChanged 609482a8b0ff024312b361326a0cc58fcaa4b8d4dd5ab0f99d59ab916f742ae4 status=0
NotifyTransactionChanged 0b32e58c71fe34448c3e08d79fe14ce9aca4c47e4f77baf414b3a469eafa0773 status=1
CTransaction::IsStandard() : Vout is non standard
ERROR: CTxMemPool::accept() : nonstandard transaction type
CommitTransaction() : Error: Transaction not validgetblocks 140656 to 0000000000003408d24b limit 500
  getblocks stopping at limit 141155 0000000001e373ddd8e5
received getdata (2 invsz)
updateWallet 0b32e58c71fe34448c3e08d79fe14ce9aca4c47e4f77baf414b3a469eafa0773 1
   inWallet=1 inModel=1 Index=1-2 showTransaction=1 derivedStatus=1
updateWallet 609482a8b0ff024312b361326a0cc58fcaa4b8d4dd5ab0f99d59ab916f742ae4 0
   inWallet=1 inModel=0 Index=3-3 showTransaction=1 derivedStatus=0
updateWallet 0b32e58c71fe34448c3e08d79fe14ce9aca4c47e4f77baf414b3a469eafa0773 1
   inWallet=1 inModel=1 Index=1-2 showTransaction=1 derivedStatus=1
CTxMemPool::accept() : accepted 60890b031d (poolsz 11)
received getdata (380 invsz)
Flushing wallet.dat

**Comment by jderwish** [comment]
@justinvforvendetta  are we suggesting to comment out those lines, I have same issue with latest commit

jderwish@instance-1:~/VERGE$ sudo git pull --commit
remote: Counting objects: 33, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 33 (delta 20), reused 29 (delta 19), pack-reused 0
Unpacking objects: 100% (33/33), done.
From https://github.com/vergecurrency/VERGE
   4664811..13d8f32  master     -> origin/master
   81cd517..0aa30fd  tor_integration -> origin/tor_integration
Updating 4664811..13d8f32


SendStealthMoney() : Error: Transaction creation failed  received block fc0ef05ff879d3c30e4c
SendStealthMoney() : Error: Transaction creation failed  CTxMemPool::accept() : accepted 9429341828 (poolsz 6)
SendStealthMoney() : Error: Transaction creation failed  SendStealthMoney() : Error: Transaction creation failed  CTxMemPool::accept() : accepted e6c9829cd9 (poolsz 7)
SendStealthMoney() : Error: Transaction creation failed  CTxMemPool::accept() : accepted 8302fedf74 (poolsz 12)
SendStealthMoney() : Error: Transaction creation failed  CTxMemPool::accept() : accepted 8d3d02123c (poolsz 15)
CommitTransaction() : Error: Transaction not validCTxMemPool::accept() : accepted 65b7070b2d (poolsz 10)
CommitTransaction() : Error: Transaction not validupdateWallet 2752beb48624315a25c8c63a00dfe73d5ce6642713b5a2e2a8e641d2c07e7c01 1

**Comment by jderwish** [comment]
@pasrom @justinvforvendetta  Just to add, restarted, rebuild and sync wallet for past 11 hours and nothing. No stealthtransaction successful. Other non-stealth transactions successful and quick.

**Comment by techpoy** [comment]
anybody successfully tested stealth send?

**Comment by dbtftw** [comment]
Not yet, still waiting for the pools to be up.

**Comment by dbtftw** [comment]
This is confirmed working on the latest OSX build  e075115cb00b47ad6d93ccd4fdf2fb3ed9d28e2a
