### ISSUE TITLE
Electrum Send Issues - Amount sent: 0. XVG

### ISSUE THREAD

**Issue by kgreenman21** [vergecurrency/VERGE#297]
Please see screenshots. Trying to send from Electrum 2.4.1 (Win 10 x64) wallet to Binance. Notice the -1 amount in the history tab. Notice the Transaction window.
Amount sent: 0. XVG

The actual transaction had 35 as the send amount. This has happened to me 6 times today.
![electrumissue](https://user-images.githubusercontent.com/35053996/34509980-102393dc-f01e-11e7-8323-d20ffd2b3541.JPG)
![capture](https://user-images.githubusercontent.com/35053996/34509981-141f7a46-f01e-11e7-8a07-e69348e2fbb5.JPG)

**Comment by justinvforvendetta** [comment]
an empty send to or from binance? i dont understand what you're saying here.

**Comment by kgreenman21** [comment]
Sending from Electrum to Binance.

**Comment by kgreenman21** [comment]
More specifically, I was sending 35 xvg from Electrum wallet to Binance wallet. I've had this problem all day long. Worked fine yesterday.

**Comment by justinvforvendetta** [comment]
did the transaction go thru? right click and show details of the transaction

**Comment by kgreenman21** [comment]
You can close this. Just went through. I backed up my wallet and wiped Roaming folder data. Restored and reattempted the transfer. Went through. Thanks for the help.

**Comment by someguyinla** [comment]
I'm having the same issue w/ transferring my XVG from my electrum wallet to binance. I get a transaction ID and all that but it isn't actually sending anything out. Any ideas?

![electrum](https://user-images.githubusercontent.com/35316056/34801623-8cac9a4c-f61e-11e7-9648-d7af4810aa74.jpg)
