### ISSUE TITLE
Update LevelDB to latest 1.20

### ISSUE THREAD

**Issue by mjanveaux** [vergecurrency/VERGE#298]
I'm interested in bringing the dependencies up to date where possible, eventually improving performance of the indexing process...

**Comment by mjanveaux** [comment]
I've already made the necessary changes, looking to be able to push a branch a start a pr

**Comment by justinvforvendetta** [comment]
you can create the branch and merge it into your local clone, and then create a pr

**Comment by mjanveaux** [comment]
Thank you Justin ... new to contributing.

**Comment by justinvforvendetta** [comment]
looks like it needs some work still

**Comment by Serverlag** [comment]
Thinking you might need to do the following:

cd src/leveldb
chmod +x build_detect_platform
make clean
make libmemenv.a libleveldb.a

Should at least resolve the issue for the linux build, not sure about Mac OS yet as I haven't taken a look.

**Comment by jrsikors** [comment]
closing, reference pull 299 if still pursuing

https://github.com/vergecurrency/VERGE/pull/299
