### ISSUE TITLE
Translation to Serbian

### ISSUE THREAD

**Issue by voyager** [vergecurrency/VERGE#300]
I'll be happy to contribute this way.

sr_RS

https://github.com/voyager/VERGE

**Comment by sasasavic82** [comment]
You beat me to it :)

**Comment by crypto4ce** [comment]
Dobri ste ;)

**Comment by sasasavic82** [comment]
samo napred majstore :)

**Comment by sasasavic82** [comment]
hoću reći, majstori :)

I'm happy to do a Bosnian interpretation, to add some flavour to it :)

**Comment by eskagithub** [comment]
odlichno! Jel svima funkcionise novi wallet? Meni ne sinkuje..

**Comment by eskagithub** [comment]
koji bi novchanik vi preporucili, posto je to do sada bio veliki izazov i da li se ochekuje suport za ledger nano i verge? Hvala unapred

**Comment by eskagithub** [comment]
pitanje za novcanik je ozbiljno, poshto se do sada nisam osecala sigurno da stavim sav Verge u eltrum wallet. Da li je mozhda najsigurniji paper wallet ili ovaj najnoviji wraith. Jako lepo izgleda ali je tek izashao. Molim vas savet od vas developera.  Pozdrav

**Comment by sasasavic82** [comment]
Verge wraith ti je mnogo sigurniji i obezbjesjeni ... šta piše console output što se tiče sync? ... sync treba bar 6-8 sati.

**Comment by eskagithub** [comment]
ne sincuje uopste, za sad. Nisam nishta radila sa blockchain. Nishta dodavala ni oduzimala :-)

**Comment by eskagithub** [comment]
v2.1.0.0-unk-beta OpenSSL 1.0.2l  25 May 2017 Jan  1 2018, 14:21:35 wo jan 3 10:47:27 2018 number of connections 0, bloks 1145029

**Comment by jrsikors** [comment]
Did this ever get done ?

I didn't see anything in https://github.com/voyager/VERGE/tree/master/src/qt/locale

**Comment by jrsikors** [comment]
instructions for translation
You can use this steps:
1 - create a fork of the project
2 - when fork created, you go to src/qt/locale and create a file like bitcoin_gk.ts
3 - copy the original file in english into the bitcoin_gk.ts
4 - Translate the file in the tags 
5 - commit
6 - make a pull request

**Comment by jrsikors** [comment]
@voyager  @sasasavic82  @crypto4ce  @eskagithub 

If you ever find some time, please follow instructions above to help with translations !  Feel free to open a new issue when you are close if you need more assistance.  We will be happy to help !
