### ISSUE TITLE
Cant send to stealth address, bulid c66b441

### ISSUE THREAD

**Issue by zze** [vergecurrency/VERGE#301]
alright bulit off https://github.com/vergecurrency/VERGE/commit/c66b4418be0578248a7f8230571d91c910d2008d
tried sendtostealthaddress addresshere 0.5, then 0.8 and it gave "Error:  Transaction creation failed (code -4)

![err3](https://user-images.githubusercontent.com/657191/34511039-ed40879a-f026-11e7-8aa7-ba4330da288f.jpg)

**Comment by hankthornlee** [comment]
@zze did you happen to try to merge the following fix locally and test, I believe this issue was just fixed via: https://github.com/vergecurrency/VERGE/issues/262

**Comment by techpoy** [comment]
What was the fix? I couldn't find any commit related to this fix?

**Comment by justinvforvendetta** [comment]
theres already a newer build/issue thread for this, closing
