### ISSUE TITLE
Can't build verge from source Mac High Sierra

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#305]
./building/mac/build.sh
~clutter saying I have boost etc etc~
checking for PROTOBUF... no
configure: error: libprotobuf not found
make: *** No targets specified and no makefile found.  Stop.

Did port install protobuf-cpp to no avail.
Makefile not being there is another concern.

**Comment by mnott** [comment]
See #306 - I had the same issue. Justin closed my report without a comment, but I was able to build using

sudo port install protobuf-cpp

In other words, I'm using protobuf from ports, the one from brew seems not to work.

With that, the compile went through.

**Comment by Positivism** [comment]
"Did port install protobuf-cpp to no avail."

**Comment by Positivism** [comment]
sudo port install protobuf-cpp
--->  Computing dependencies for protobuf-cpp
--->  Cleaning protobuf-cpp
--->  Scanning binaries for linking errors
--->  No broken files found.

Yields same error.

**Comment by mnott** [comment]
Hmm. I am not enough informed as to track this one down. But using

$ otool -L VERGE-qt

I see that I am using now the version from ports:

/opt/local/lib/libprotobuf.9.dylib (compatibility version 10.0.0, current version 10.1.0)

**Comment by Positivism** [comment]
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/objdump: 'VERGE-qt': No such file or directory

**Comment by mnott** [comment]
OK, I am using this from where I have done the compile (the VERGE git repository directory). Which you don't have, because you don't manage to compile so far.

**Comment by mnott** [comment]
Did you try to sudo port uninstall protobuf-cpp; sudo port install protobuf-cpp?

**Comment by Positivism** [comment]
sudo port uninstall protobuf-cpp
--->  Deactivating protobuf-cpp @2.6.1_0
--->  Cleaning protobuf-cpp
--->  Uninstalling protobuf-cpp @2.6.1_0
--->  Cleaning protobuf-cpp

sudo port install protobuf-cpp
--->  Computing dependencies for protobuf-cpp
--->  Fetching archive for protobuf-cpp
--->  Attempting to fetch protobuf-cpp-2.6.1_0.darwin_17.x86_64.tbz2
--->  Attempting to fetch protobuf-cpp-2.6.1_0.darwin_17.x86_64.tbz2.rmd160
--->  Installing protobuf-cpp @2.6.1_0
--->  Activating protobuf-cpp @2.6.1_0
--->  Cleaning protobuf-cpp
--->  Updating database of binaries
--->  Scanning binaries for linking errors
--->  No broken files found.

./building/mac/build.sh
checking for PROTOBUF... no
configure: error: libprotobuf not found
make: *** No targets specified and no makefile found.  Stop.

**Comment by mnott** [comment]
Hmm. Same here. Well, my port says it's outdated, so I'm going to run a selfupdate.

**Comment by mnott** [comment]
env | grep -i /opt/local/
MANPATH=/opt/local/share/man:/Users/mnott/perl5/perlbrew/perls/perl-5.24.0/man:/sw/share/man/de:/sw/share/man:/Library/Frameworks/Python.framework/Versions/2.6/share/man:/usr/local/texlive/2014/bin/x86_64-darwin/man:/usr/local/share/man/de:/usr/local/share/man:/usr/share/man:/usr/local/MacGPG2/share/man:/opt/X11/share/man:/Library/Frameworks/Mono.framework/Versions/Current/share/man:/Applications/Xcode.app/Contents/Developer/usr/share/man:/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/share/man
PATH=/pgm/scripts:/Users/mnott/perl5/perlbrew/bin:/Users/mnott/perl5/perlbrew/perls/perl-5.24.0/bin:/opt/local/bin:/opt/local/sbin:/sw/bin:/sw/sbin:/usr/local/opt/python/libexec/bin:/Library/Frameworks/Python.framework/Versions/2.6/bin:/usr/local/texlive/2014/bin/x86_64-darwin:/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/opt/oracle/ohome/bin:/opt/mongodb/bin:/opt/mongodb

**Comment by Positivism** [comment]
env | grep -i /opt/local/
PATH=/pgm/scripts:/Users/mnott/perl5/perlbrew/bin:/Users/mnott/perl5/perlbrew/perls/perl-5.24.0/bin:/opt/local/bin:/opt/local/sbin:/sw/bin:/sw/sbin:/usr/local/opt/python/libexec/bin:/Library/Frameworks/Python.framework/Versions/2.6/bin:/usr/local/texlive/2014/bin/x86_64-darwin:/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/usr/local/MacGPG2/bin:/opt/X11/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/opt/oracle/ohome/bin:/opt/mongodb/bin:/opt/mongodb

**Comment by Positivism** [comment]
Source of the problem was a permissions error.
Uninstall protobuf accordingly:
If you have both brew and ports, execute both.

```
sudo port uninstall protobuf-cpp
brew uninstall protobuf
```
Find your group name:
```
id -g
```

Alleviate permissions issues.
```
cd /usr/local
sudo chown -R <your-username>:<your-group-name> *
```

Reinstall protobuf using brew
```
brew install protobuf
brew link protobuf
```

If linking is unsuccessful, overwrite.
```
brew link --overwrite protobuf
```

**Comment by mnott** [comment]
Can't confirm.

checking for PROTOBUF... no
configure: error: libprotobuf not found
/bin/sh ./config.status --recheck

...

checking for PROTOBUF... no
configure: error: libprotobuf not found
make: *** [config.status] Error 1

Using ports version works.

**Comment by Positivism** [comment]
Did you install ports or brew first?

**Comment by mnott** [comment]
That I don't remember - I've used ports and brew forever. But in terms of protobuf, I've removed both, as you suggested, then installed and linked the brew version. That did not work. Then I installed protobuf-cpp from macports, and it started working.

**Comment by Positivism** [comment]
I installed brew first (put off ports for years), so I think it's some sort of conflict issue, when I followed the same procedure, uninstalled brew's version and install ports' version, the original error resurfaced.
