### ISSUE TITLE
Solved: configure: error: libprotobuf not found

### ISSUE THREAD

**Issue by mnott** [vergecurrency/VERGE#306]
# Confirming Error

$ ./building/common.sh
PWD:/Users/mnott/Desktop/VERGE
ME:Desktop

$ ./building/mac/requirements.sh
Error: No such keg: /usr/local/Cellar/qt
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (homebrew/core, caskroom/cask).
==> New Formulae
orocos-kdl
==> Updated Formulae
armadillo              davmail                gifski                 kobalt                 packmol
armor                  e2fsprogs              gmt                    nano                   pandoc-citeproc
bash-snippets          etcd                   gmt@4                  node@6                 pre-commit
chamber                fn                     heroku                 node@8                 xcenv

Warning: boost@1.60 1.60.0 is already installed
Warning: pkg-config 0.29.2 is already installed
Warning: automake 1.15.1 is already installed
Warning: qt@5.5 5.5.1_1 is already installed
Warning: protobuf 3.5.1 is already installed
Warning: miniupnpc 2.0.20171212 is already installed
Warning: openssl 1.0.2n is already installed
Warning: qrencode 4.0.0 is already installed
Warning: berkeley-db@4 4.8.30 is already installed
Warning: Already linked: /usr/local/Cellar/automake/1.15.1
To relink: brew unlink automake && brew link automake
Warning: Already linked: /usr/local/Cellar/autoconf/2.69
To relink: brew unlink autoconf && brew link autoconf

$ ./building/mac/build.sh
configure.ac:719: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
configure.ac:719: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
checking build system type... x86_64-apple-darwin17.3.0
...
checking for CRYPTO... yes
checking for PROTOBUF... no
configure: error: libprotobuf not found
make: *** No targets specified and no makefile found.  Stop.

# Solution

Following https://github.com/bitcoin/bitcoin/issues/7782, here is what needed to be done:

sudo port install protobuf-cpp

**Comment by rafaeloliveiras** [comment]
With the evolution, this problems will be solved, and with a single installation the user will can use 100% of the wallet without configure too much. The wallet have to be more simple as possible.

**Comment by dbtftw** [comment]
This should be closed
