### ISSUE TITLE
Translation to Arab?

### ISSUE THREAD

**Issue by xMoad** [vergecurrency/VERGE#307]
Hi Verge users, i just want to let you know that i will create a new ts file for arabic languange,

**Comment by aboussof** [comment]
I also planned to do that, but you were faster than me :)

**Comment by jrsikors** [comment]
Did either of you ever get  around to this ?

**Comment by jrsikors** [comment]
instructions for translation
You can use this steps:
1 - create a fork of the project
2 - when fork created, you go to src/qt/locale and create a file like bitcoin_gk.ts
3 - copy the original file in english into the bitcoin_gk.ts
4 - Translate the file in the tags 
5 - commit
6 - make a pull request

**Comment by jrsikors** [comment]
closing issue -- please follow instructions above if you are able to contribute the translations, and create a new issue if you need help when you get close !  Will be happy to assist !
