### ISSUE TITLE
build.h not found (High Sierra)

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#308]
Running: ./building/mac/build.sh

Results in:
_verbose checking and warnings_
../share/genbuild.sh: line 4: cd: 5/src/obj/build.h: No such file or directory
../share/genbuild.sh: line 48: /dir/VERGE-master: Is a directory
  CXX      libbitcoin_util_a-version.o
version.cpp:34:14: fatal error: 'build.h' file not found
\#    include "build.h"
             ^~~~~~~~~
1 error generated.
make[1]: *** [libbitcoin_util_a-version.o] Error 1
make: *** [all-recursive] Error 1

**Comment by mnott** [comment]
VERGE$ find . -iname build.h
./src/obj/build.h

Do you not have it?

**Comment by Positivism** [comment]
Affirmative, not in the directory.

https://github.com/vergecurrency/VERGE/tree/master/src/obj
Nor in the source directory.

**Comment by mnott** [comment]
Yes it is not. It is created as part of the build process.

**Comment by Positivism** [comment]
Odd, re-downloaded the source, executed all commands again to no avail. Same error.

**Comment by mnott** [comment]
share/genbuild.sh creates that file

**Comment by Positivism** [comment]
Found the issue, space in the directory name. I believe whatever is passing the directory argument isn't escaping it. Would have todo some testing to confirm.
