### ISSUE TITLE
Console window

### ISSUE THREAD

**Issue by Cryptosurfer69** [vergecurrency/VERGE#309]
When I open console, the window is bigger than my display.  When I try to resize window it disappears....
 Sorry, I'm on windows

**Comment by Positivism** [comment]
Which operating system?

**Comment by Positivism** [comment]
If you're on Mac, enlarging the console via the full screen button will allow you to see all of the console.

**Comment by Cryptosurfer69** [comment]
On windows it doesn't let you full screen on console...

**Comment by rvrhee** [comment]
i said so i also have this problem @justinvforvendetta
