### ISSUE TITLE
connection timeout

### ISSUE THREAD

**Issue by mnott** [vergecurrency/VERGE#310]
Having Connection Timeout. I don't have any intermediate Firewall. Trying with tethering through iPhone to exclude any local firewall, same result.

VERGE version v2.1.0.0-7d417ad-beta (2018-01-03 01:22:57 -0500)
Using OpenSSL version OpenSSL 1.0.2n  7 Dec 2017
Startup time: 03.01.2018 12:44:56
Default data directory /Users/mnott/Library/Application Support/VERGE
Default mining hash algorithm: x17
Used data directory /Users/mnott/Library/Application Support/VERGE
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/Users/mnott/Library/Application Support/VERGE/database ErrorFile=/Users/mnott/Library/Application Support/VERGE/db.log
Bound to [::]:21102
Bound to 0.0.0.0:21102
Loading block index...
Opening LevelDB in /Users/mnott/Library/Application Support/VERGE/txleveldb
Transaction index version is 70509
Opened LevelDB successfully
LoadBlockIndex(): hashBestChain=0000000001047115720f00f4f33409adbd4aa46606d89a357e182b425d099e8d  height=21988  trust=21989  date=27.10.2014 07:36:38
LoadBlockIndex(): synchronized checkpoint 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
Verifying last 2500 blocks at level 1
 block index            6477ms
Loading wallet...
nFileVersion = 2010000
 wallet                  231ms
Loading addresses...
Loaded 5 addresses from peers.dat  0ms
mapBlockIndex.size() = 21989
nBestHeight = 21988
setKeyPool.size() = 101
mapWallet.size() = 0
mapAddressBook.size() = 1
ThreadDNSAddressSeed started
ThreadSocketHandler started
Loading addresses from DNS seeds (could take a while)
ThreadOpenAddedConnections started
ThreadOpenConnections started
ThreadMessageHandler started
ThreadOpenAddedConnections exited
ThreadStakeMinter started
CPUMiner started for proof-of-stake
8 processors
Starting 8 VERGEMiner threads
CPUMiner started for proof-of-work
Flushed 5 addresses to peers.dat  0ms
Done loading
5 addresses found from DNS seeds
ThreadDNSAddressSeed exited
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
trying connection 138.201.91.159:21102 lastseen=97,7hrs
refreshWallet
connect() failed after select(): Connection refused
trying connection 77.67.46.100:21102 lastseen=0,7hrs
connected 77.67.46.100:21102
send version message: version 90001, blocks=21988, us=0.0.0.0:0, them=77.67.46.100:21102, peer=77.67.46.100:21102
socket closed
disconnecting node 77.67.46.100:21102
trying connection 138.201.91.159:21102 lastseen=97,7hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=97,7hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=88,5hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=88,5hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=87,8hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=97,7hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=88,5hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=87,9hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=97,7hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=88,5hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=87,9hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=87,9hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=97,7hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=88,5hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=87,9hrs
socket closed
GetMyExternalIP() received [192.168.1.223] 192.168.1.223:0
connection timeout
trying connection 138.201.91.159:21102 lastseen=97,7hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=97,7hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=88,5hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=88,5hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=87,9hrs

**Comment by mnott** [comment]
Any help on this? I just apparently get no network connection, and I don't see how to trace it.

I think that the general settings are right, since I can make one successful connection:

trying connection 77.67.46.100:21102 lastseen=0,7hrs
connected 77.67.46.100:21102
send version message: version 90001, blocks=21988, us=0.0.0.0:0, them=77.67.46.100:21102, peer=77.67.46.100:21102
socket closed
disconnecting node 77.67.46.100:21102

So the outbound port is open quite obviously, it then just fails to connect to all the others he is trying to use, and hence I get 0 connections.

**Comment by mnott** [comment]
I tried limiting to the one IP address to which I can make a connection:

./VERGE-Qt -connect=77.67.46.100

VERGE version v2.1.0.0-7d417ad-beta (2018-01-03 01:22:57 -0500)
Using OpenSSL version OpenSSL 1.0.2n  7 Dec 2017
Startup time: 03.01.2018 13:57:54
Default data directory /Users/mnott/Library/Application Support/VERGE
Default mining hash algorithm: x17
Used data directory /Users/mnott/Library/Application Support/VERGE
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/Users/mnott/Library/Application Support/VERGE/database ErrorFile=/Users/mnott/Library/Application Support/VERGE/db.log
AddLocal(213.221.150.68:21102,5)
Loading block index...
Opening LevelDB in /Users/mnott/Library/Application Support/VERGE/txleveldb
Transaction index version is 70509
Opened LevelDB successfully
LoadBlockIndex(): hashBestChain=0000000001047115720f00f4f33409adbd4aa46606d89a357e182b425d099e8d  height=21988  trust=21989  date=27.10.2014 07:36:38
LoadBlockIndex(): synchronized checkpoint 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
Verifying last 2500 blocks at level 1
 block index            6419ms
Loading wallet...
nFileVersion = 2010000
 wallet                  216ms
Loading addresses...
Loaded 5 addresses from peers.dat  0ms
mapBlockIndex.size() = 21989
nBestHeight = 21988
setKeyPool.size() = 101
mapWallet.size() = 0
mapAddressBook.size() = 1
DNS seeding disabled
ThreadMapPort started
ThreadSocketHandler started
ThreadOpenAddedConnections started
ThreadOpenConnections started
ThreadOpenAddedConnections exited
ThreadMessageHandler started
trying connection 77.67.46.100 lastseen=0,0hrs
ThreadStakeMinter started
8 processors
CPUMiner started for proof-of-stake
Starting 8 VERGEMiner threads
CPUMiner started for proof-of-work
Flushed 5 addresses to peers.dat  1ms
Done loading
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
CPUMiner started for proof-of-work
refreshWallet
No valid UPnP IGDs found
connection timeout
trying connection 77.67.46.100 lastseen=0,0hrs
connected 77.67.46.100
send version message: version 90001, blocks=21988, us=0.0.0.0:0, them=77.67.46.100:21102, peer=77.67.46.100:21102
socket no message in first 60 seconds, 0 1
disconnecting node 77.67.46.100
trying connection 77.67.46.100 lastseen=0,0hrs
connected 77.67.46.100
send version message: version 90001, blocks=21988, us=0.0.0.0:0, them=77.67.46.100:21102, peer=77.67.46.100:21102
Flushed 5 addresses to peers.dat  7ms
socket closed
disconnecting node 77.67.46.100
trying connection 77.67.46.100 lastseen=0,0hrs
connected 77.67.46.100
send version message: version 90001, blocks=21988, us=0.0.0.0:0, them=77.67.46.100:21102, peer=77.67.46.100:21102
socket closed
disconnecting node 77.67.46.100
trying connection 77.67.46.100 lastseen=0,0hrs
connected 77.67.46.100
send version message: version 90001, blocks=21988, us=0.0.0.0:0, them=77.67.46.100:21102, peer=77.67.46.100:21102
Flushed 5 addresses to peers.dat  7ms
socket closed
disconnecting node 77.67.46.100
trying connection 77.67.46.100 lastseen=0,0hrs
connected 77.67.46.100
send version message: version 90001, blocks=21988, us=0.0.0.0:0, them=77.67.46.100:21102, peer=77.67.46.100:21102
Flushed 5 addresses to peers.dat  7ms
socket no message in first 60 seconds, 0 1
disconnecting node 77.67.46.100

So I can see that somehow there is now one active connection, but I see the number of blocks in the status window are 21988, and it stays there.

**Comment by justinvforvendetta** [comment]
how long have you left it open to search for connections and sync?

**Comment by Thijsjuh92** [comment]
4 days still 360000 block remaining...

**Comment by AceTech07** [comment]
Does this mean I'm ready??

**Comment by AceTech07** [comment]
I get these messages when I hover over green connection sign and check mark
on wallet..

14 active connection(s) to Verge Network..

Up to date.
Downloaded  1771812 blocks of transaction history.  Last received block was
generated 1 minute(s) ago. Does this mean it's finished

**Comment by mnott** [comment]
Justin: I've left it open for a whole night and day. And now again since 2 hours, not connecting.

**Comment by mnott** [comment]
How can I read out peers.dat? I've removed it, it has recreated it, but that didn't help either.

**Comment by mnott** [comment]
I've also tried the development branch. Same problem. Basically I'm trying now since a whole day to understand and get to connect the client on MacOS High Sierra. It just times out. When I telnet into any of those IP addresses on port 80, it works, on port 21102, it does not work.

Is 21102 a back port that I should open incoming on the firewall? Doesn't appear to make sense.

$ git status
On branch development
Your branch is up-to-date with 'origin/development'.

$ ./VERGE-Qt  -externalip=213.221.150.68 -splash=0 -gen=0

VERGE version v2.1.0.0-7d417ad-beta (2018-01-03 01:22:57 -0500)
Using OpenSSL version OpenSSL 1.0.2n  7 Dec 2017
Startup time: 03.01.2018 17:21:43
Default data directory /Users/mnott/Library/Application Support/VERGE
Default mining hash algorithm: scrypt
Used data directory /Users/mnott/Library/Application Support/VERGE
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/Users/mnott/Library/Application Support/VERGE/database ErrorFile=/Users/mnott/Library/Application Support/VERGE/db.log
Bound to [::]:21102
Bound to 0.0.0.0:21102
AddLocal(213.221.150.68:21102,5)
Loading block index...
Opening LevelDB in /Users/mnott/Library/Application Support/VERGE/txleveldb
Transaction index version is 70509
Opened LevelDB successfully
LoadBlockIndex(): hashBestChain=0000000001047115720f00f4f33409adbd4aa46606d89a357e182b425d099e8d  height=21988  trust=21989  date=27.10.2014 07:36:38
LoadBlockIndex(): synchronized checkpoint 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
Verifying last 2500 blocks at level 1
 block index            6411ms
Loading wallet...
nFileVersion = 2010000
 wallet                  228ms
Loading addresses...
Loaded 5 addresses from peers.dat  0ms
mapBlockIndex.size() = 21989
nBestHeight = 21988
setKeyPool.size() = 101
mapWallet.size() = 0
mapAddressBook.size() = 1
Done loading
ThreadDNSAddressSeed started
Loading addresses from DNS seeds (could take a while)
ThreadMapPort started
ThreadSocketHandler started
ThreadOpenAddedConnections started
ThreadOpenConnections started
ThreadMessageHandler started
ThreadStakeMinter started
ThreadOpenAddedConnections exited
CPUMiner started for proof-of-stake
refreshWallet
Flushed 5 addresses to peers.dat  1ms
5 addresses found from DNS seeds
ThreadDNSAddressSeed exited
trying connection 98.5.123.15:21102 lastseen=132,4hrs
No valid UPnP IGDs found
connection timeout
trying connection 105.228.198.44:21102 lastseen=152,2hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=132,4hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=132,4hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=152,2hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=132,4hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=152,2hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=132,4hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=132,4hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=152,2hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=152,2hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=152,2hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=110,8hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=152,2hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=132,5hrs

**Comment by fradelo** [comment]
@mnott did you download blockchain and copy it to the application folder manually?

**Comment by mnott** [comment]
What do you mean by that, @fradelo?

I've now removed ~/Library/Application Support/VERGE and ~/.VERGE and have restarted:

./VERGE-Qt  -externalip=213.221.150.68 -splash=0 -gen=0

It still doesn't work. This is the log:






















VERGE version v2.1.0.0-7d417ad-beta (2018-01-03 01:22:57 -0500)
Using OpenSSL version OpenSSL 1.0.2n  7 Dec 2017
Startup time: 03.01.2018 17:28:18
Default data directory /Users/mnott/Library/Application Support/VERGE
Default mining hash algorithm: scrypt
Used data directory /Users/mnott/Library/Application Support/VERGE
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/Users/mnott/Library/Application Support/VERGE/database ErrorFile=/Users/mnott/Library/Application Support/VERGE/db.log
Bound to [::]:21102
Bound to 0.0.0.0:21102
AddLocal(213.221.150.68:21102,5)
Loading block index...
Opening LevelDB in /Users/mnott/Library/Application Support/VERGE/txleveldb
Opened LevelDB successfully
CBlock(hash=00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278, ver=1, algo=0, mined_hash=00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278, hashPrevBlock=0000000000000000000000000000000000000000000000000000000000000000, hashMerkleRoot=1c83275d9151711eec3aec37d829837cc3c2730b2bdfd00ec5e8e5dce675fd00, nTime=1412878964, nBits=1e0fffff, nNonce=1473191, vtx=1, vchBlockSig=)
  Coinbase(hash=1c83275d91, nTime=1412878964, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 04ffff001d0104134e616d653a20446f6765636f696e204461726b)
    CTxOut(empty)
  vMerkleTree: 1c83275d91 
block.GetHash() == 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
block.hashMerkleRoot == 1c83275d9151711eec3aec37d829837cc3c2730b2bdfd00ec5e8e5dce675fd00
block.nTime = 1412878964 
block.nNonce = 1473191 
SetBestChain: new best=00000fc63692467faeb2  height=0  trust=1  date=09.10.2014 18:22:44
ResetSyncCheckpoint: pending for sync-checkpoint 04def2ba205c1e5f4b33873bc9e5b0a54311370e823686aeb4d5aab0bf021899
ResetSyncCheckpoint: sync-checkpoint reset to 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
 block index              36ms
Loading wallet...
nFileVersion = 2010000
Performing wallet upgrade to 60000
keypool added key 1, size=1
keypool added key 2, size=2
keypool added key 3, size=3
keypool added key 4, size=4
keypool added key 5, size=5
keypool added key 6, size=6
keypool added key 7, size=7
keypool added key 8, size=8
keypool added key 9, size=9
keypool added key 10, size=10
keypool added key 11, size=11
keypool added key 12, size=12
keypool added key 13, size=13
keypool added key 14, size=14
keypool added key 15, size=15
keypool added key 16, size=16
keypool added key 17, size=17
keypool added key 18, size=18
keypool added key 19, size=19
keypool added key 20, size=20
keypool added key 21, size=21
keypool added key 22, size=22
keypool added key 23, size=23
keypool added key 24, size=24
keypool added key 25, size=25
keypool added key 26, size=26
keypool added key 27, size=27
keypool added key 28, size=28
keypool added key 29, size=29
keypool added key 30, size=30
keypool added key 31, size=31
keypool added key 32, size=32
keypool added key 33, size=33
keypool added key 34, size=34
keypool added key 35, size=35
keypool added key 36, size=36
keypool added key 37, size=37
keypool added key 38, size=38
keypool added key 39, size=39
keypool added key 40, size=40
keypool added key 41, size=41
keypool added key 42, size=42
keypool added key 43, size=43
keypool added key 44, size=44
keypool added key 45, size=45
keypool added key 46, size=46
keypool added key 47, size=47
keypool added key 48, size=48
keypool added key 49, size=49
keypool added key 50, size=50
keypool added key 51, size=51
keypool added key 52, size=52
keypool added key 53, size=53
keypool added key 54, size=54
keypool added key 55, size=55
keypool added key 56, size=56
keypool added key 57, size=57
keypool added key 58, size=58
keypool added key 59, size=59
keypool added key 60, size=60
keypool added key 61, size=61
keypool added key 62, size=62
keypool added key 63, size=63
keypool added key 64, size=64
keypool added key 65, size=65
keypool added key 66, size=66
keypool added key 67, size=67
keypool added key 68, size=68
keypool added key 69, size=69
keypool added key 70, size=70
keypool added key 71, size=71
keypool added key 72, size=72
keypool added key 73, size=73
keypool added key 74, size=74
keypool added key 75, size=75
keypool added key 76, size=76
keypool added key 77, size=77
keypool added key 78, size=78
keypool added key 79, size=79
keypool added key 80, size=80
keypool added key 81, size=81
keypool added key 82, size=82
keypool added key 83, size=83
keypool added key 84, size=84
keypool added key 85, size=85
keypool added key 86, size=86
keypool added key 87, size=87
keypool added key 88, size=88
keypool added key 89, size=89
keypool added key 90, size=90
keypool added key 91, size=91
keypool added key 92, size=92
keypool added key 93, size=93
keypool added key 94, size=94
keypool added key 95, size=95
keypool added key 96, size=96
keypool added key 97, size=97
keypool added key 98, size=98
keypool added key 99, size=99
keypool added key 100, size=100
keypool added key 101, size=101
 wallet                 2022ms
Loading addresses...
ERROR: CAddrman::Read() : open failed
Invalid or missing peers.dat; recreating
Loaded 0 addresses from peers.dat  0ms
mapBlockIndex.size() = 1
nBestHeight = 0
setKeyPool.size() = 100
mapWallet.size() = 0
mapAddressBook.size() = 1
Done loading
ThreadDNSAddressSeed started
Loading addresses from DNS seeds (could take a while)
ThreadMapPort started
ThreadSocketHandler started
ThreadOpenAddedConnections started
refreshWallet
ThreadOpenConnections started
ThreadOpenAddedConnections exited
ThreadMessageHandler started
ThreadStakeMinter started
CPUMiner started for proof-of-stake
Added 1 addresses from 185.162.9.97: 0 tried, 1 new
Added 1 addresses from 192.241.187.222: 0 tried, 2 new
Added 1 addresses from 46.127.57.167: 0 tried, 3 new
Flushed 3 addresses to peers.dat  1ms
Added 1 addresses from 81.147.68.236: 0 tried, 4 new
Added 1 addresses from 95.46.99.96: 0 tried, 5 new
5 addresses found from DNS seeds
ThreadDNSAddressSeed exited
trying connection 138.201.91.159:21102 lastseen=145,6hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=97,9hrs
Flushing wallet.dat
Flushed wallet.dat 18ms
No valid UPnP IGDs found
connection timeout
trying connection 104.131.144.82:21102 lastseen=149,2hrs
connected 104.131.144.82:21102
send version message: version 90001, blocks=0, us=213.221.150.68:21102, them=104.131.144.82:21102, peer=104.131.144.82:21102
socket recv error 54
disconnecting node 104.131.144.82:21102
trying connection 138.201.91.159:21102 lastseen=145,6hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=97,9hrs
connection timeout
trying connection 77.67.46.100:21102 lastseen=101,7hrs
connected 77.67.46.100:21102
send version message: version 90001, blocks=0, us=213.221.150.68:21102, them=77.67.46.100:21102, peer=77.67.46.100:21102
trying connection 138.201.91.159:21102 lastseen=145,6hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=97,9hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=97,9hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=97,9hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=97,9hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
socket closed
disconnecting node 77.67.46.100:21102
connection timeout
trying connection 138.201.91.159:21102 lastseen=145,6hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=97,9hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=145,6hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=97,9hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=97,9hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
Flushed 5 addresses to peers.dat  1ms
connection timeout
trying connection 138.201.91.159:21102 lastseen=145,6hrs
connect() failed after select(): Connection refused
trying connection 98.5.123.15:21102 lastseen=98,0hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=98,0hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=98,0hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=98,0hrs
connection timeout
trying connection 98.5.123.15:21102 lastseen=98,0hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=145,6hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 138.201.91.159:21102 lastseen=145,6hrs
connect() failed after select(): Connection refused
trying connection 105.228.198.44:21102 lastseen=156,2hrs
connection timeout
trying connection 105.228.198.44:21102 lastseen=156,2hrs

**Comment by mnott** [comment]
And if I remove the ~/Library/Application Support/VERGE directory and restart, without specifying the external IP, it detects it to be my laptop's LAN IP, which appears to be wrong, but anyway - leaving it out does not help either.





















VERGE version v2.1.0.0-7d417ad-beta (2018-01-03 01:22:57 -0500)
Using OpenSSL version OpenSSL 1.0.2n  7 Dec 2017
Startup time: 03.01.2018 17:32:54
Default data directory /Users/mnott/Library/Application Support/VERGE
Default mining hash algorithm: scrypt
Used data directory /Users/mnott/Library/Application Support/VERGE
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/Users/mnott/Library/Application Support/VERGE/database ErrorFile=/Users/mnott/Library/Application Support/VERGE/db.log
Bound to [::]:21102
Bound to 0.0.0.0:21102
Loading block index...
Opening LevelDB in /Users/mnott/Library/Application Support/VERGE/txleveldb
Opened LevelDB successfully
CBlock(hash=00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278, ver=1, algo=0, mined_hash=00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278, hashPrevBlock=0000000000000000000000000000000000000000000000000000000000000000, hashMerkleRoot=1c83275d9151711eec3aec37d829837cc3c2730b2bdfd00ec5e8e5dce675fd00, nTime=1412878964, nBits=1e0fffff, nNonce=1473191, vtx=1, vchBlockSig=)
  Coinbase(hash=1c83275d91, nTime=1412878964, ver=1, vin.size=1, vout.size=1, nLockTime=0)
    CTxIn(COutPoint(0000000000, 4294967295), coinbase 04ffff001d0104134e616d653a20446f6765636f696e204461726b)
    CTxOut(empty)
  vMerkleTree: 1c83275d91 
block.GetHash() == 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
block.hashMerkleRoot == 1c83275d9151711eec3aec37d829837cc3c2730b2bdfd00ec5e8e5dce675fd00
block.nTime = 1412878964 
block.nNonce = 1473191 
SetBestChain: new best=00000fc63692467faeb2  height=0  trust=1  date=09.10.2014 18:22:44
ResetSyncCheckpoint: pending for sync-checkpoint 04def2ba205c1e5f4b33873bc9e5b0a54311370e823686aeb4d5aab0bf021899
ResetSyncCheckpoint: sync-checkpoint reset to 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
 block index              39ms
Loading wallet...
nFileVersion = 2010000
Performing wallet upgrade to 60000
keypool added key 1, size=1
keypool added key 2, size=2
keypool added key 3, size=3
keypool added key 4, size=4
keypool added key 5, size=5
keypool added key 6, size=6
keypool added key 7, size=7
keypool added key 8, size=8
keypool added key 9, size=9
keypool added key 10, size=10
keypool added key 11, size=11
keypool added key 12, size=12
keypool added key 13, size=13
keypool added key 14, size=14
keypool added key 15, size=15
keypool added key 16, size=16
keypool added key 17, size=17
keypool added key 18, size=18
keypool added key 19, size=19
keypool added key 20, size=20
keypool added key 21, size=21
keypool added key 22, size=22
keypool added key 23, size=23
keypool added key 24, size=24
keypool added key 25, size=25
keypool added key 26, size=26
keypool added key 27, size=27
keypool added key 28, size=28
keypool added key 29, size=29
keypool added key 30, size=30
keypool added key 31, size=31
keypool added key 32, size=32
keypool added key 33, size=33
keypool added key 34, size=34
keypool added key 35, size=35
keypool added key 36, size=36
keypool added key 37, size=37
keypool added key 38, size=38
keypool added key 39, size=39
keypool added key 40, size=40
keypool added key 41, size=41
keypool added key 42, size=42
keypool added key 43, size=43
keypool added key 44, size=44
keypool added key 45, size=45
keypool added key 46, size=46
keypool added key 47, size=47
keypool added key 48, size=48
keypool added key 49, size=49
keypool added key 50, size=50
keypool added key 51, size=51
keypool added key 52, size=52
keypool added key 53, size=53
keypool added key 54, size=54
keypool added key 55, size=55
keypool added key 56, size=56
keypool added key 57, size=57
keypool added key 58, size=58
keypool added key 59, size=59
keypool added key 60, size=60
keypool added key 61, size=61
keypool added key 62, size=62
keypool added key 63, size=63
keypool added key 64, size=64
keypool added key 65, size=65
keypool added key 66, size=66
keypool added key 67, size=67
keypool added key 68, size=68
keypool added key 69, size=69
keypool added key 70, size=70
keypool added key 71, size=71
keypool added key 72, size=72
keypool added key 73, size=73
keypool added key 74, size=74
keypool added key 75, size=75
keypool added key 76, size=76
keypool added key 77, size=77
keypool added key 78, size=78
keypool added key 79, size=79
keypool added key 80, size=80
keypool added key 81, size=81
keypool added key 82, size=82
keypool added key 83, size=83
keypool added key 84, size=84
keypool added key 85, size=85
keypool added key 86, size=86
keypool added key 87, size=87
keypool added key 88, size=88
keypool added key 89, size=89
keypool added key 90, size=90
keypool added key 91, size=91
keypool added key 92, size=92
keypool added key 93, size=93
keypool added key 94, size=94
keypool added key 95, size=95
keypool added key 96, size=96
keypool added key 97, size=97
keypool added key 98, size=98
keypool added key 99, size=99
keypool added key 100, size=100
keypool added key 101, size=101
 wallet                 1939ms
Loading addresses...
ERROR: CAddrman::Read() : open failed
Invalid or missing peers.dat; recreating
Loaded 0 addresses from peers.dat  0ms
mapBlockIndex.size() = 1
nBestHeight = 0
setKeyPool.size() = 100
mapWallet.size() = 0
mapAddressBook.size() = 1
Done loading
refreshWallet
ThreadDNSAddressSeed started
ThreadMapPort started
Loading addresses from DNS seeds (could take a while)
ThreadSocketHandler started
ThreadOpenAddedConnections started
ThreadOpenConnections started
ThreadOpenAddedConnections exited
ThreadMessageHandler started
ThreadStakeMinter started
CPUMiner started for proof-of-stake
Added 1 addresses from 185.162.9.97: 0 tried, 1 new
Flushed 1 addresses to peers.dat  2ms
Added 1 addresses from 192.241.187.222: 0 tried, 2 new
Added 1 addresses from 46.127.57.167: 0 tried, 3 new
Added 1 addresses from 81.147.68.236: 0 tried, 4 new
Added 1 addresses from 95.46.99.96: 0 tried, 5 new
5 addresses found from DNS seeds
ThreadDNSAddressSeed exited
trying connection 98.5.123.15:21102 lastseen=72,5hrs
GetMyExternalIP() received [192.168.1.223] 192.168.1.223:0
Flushing wallet.dat
Flushed wallet.dat 21ms
connection timeout
GetMyExternalIP() received [192.168.1.223] 192.168.1.223:0
No valid UPnP IGDs found
trying connection 98.5.123.15:21102 lastseen=72,5hrs
connection timeout
trying connection 104.131.144.82:21102 lastseen=124,7hrs
connected 104.131.144.82:21102
send version message: version 90001, blocks=0, us=0.0.0.0:0, them=104.131.144.82:21102, peer=104.131.144.82:21102
trying connection 98.5.123.15:21102 lastseen=72,5hrs
socket recv error 54
disconnecting node 104.131.144.82:21102
connection timeout
trying connection 98.5.123.15:21102 lastseen=72,5hrs

**Comment by fradelo** [comment]
see #265

**Comment by mnott** [comment]
Thanks @fradelo, that was apparently it. For the record, I downloaded the blockchain from https://verge-blockchain.com, extracted the ZIP into ~/Library/Application Support/VERGE (the content of the Wallet_v3 directory in the ZIP, then I started VERGE-Qt. It took a couple minutes (less than 5), where it was compacting the blockchain (see 

tail -f ~/Library/Application Support/VERGE/txleveldb/LOG

then it started synchronizing, after the UI came up.

**Comment by justinvforvendetta** [comment]
21102 is the p2p port. you can not connect unless that port is accessible.

**Comment by fradelo** [comment]
@justinvforvendetta he didn't copy the blockchain first.

**Comment by mnott** [comment]
@justinvforvendetta Yes but that's an outgoing port, right? There's non need to port forward (NAT) to the local PC.
