### ISSUE TITLE
QT v4.0 wallet Unlock wallet fails with right passphrase.

### ISSUE THREAD

**Issue by Tommixoft** [vergecurrency/VERGE#316]
Wallet keeps telling me that wallet passphrase is bad and it's ok. 
I think i saw this bugfix already done in github. SO why no release?
  Why people allowed to download shitty full of bugs older wallet? how hard is to do release?? Takes 4 minutes.

**Comment by justinvforvendetta** [comment]
because we'd like to have more fixes in the next release push. you are more than welcome to compile the changes on your computer right now.

**Comment by Tommixoft** [comment]
@justinvforvendetta but you leave major bugs in current version. New version better so why let people using crappy wallet?? to make market cap even lower with all negativity? Also pls fire UI developer ui looks terrible! Background image is tooo dark and makes hard to see text, also white borders of panels are soo ugly and 1999 style. I would contribute but you have 3 branches of UI and impossible to tell wich one is good.
