### ISSUE TITLE
Rejected Transactions

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#317]
Error: The transaction was rejected. This might happen if some of the coins in your wallet were already spent, such as if you used a copy of wallet.dat and coins were spent in the copy but not marked as spent here.

Happens for both stealth and normal addresses.
I was previously using the release where I deposited xvg and sent/received transactions.
After compiling the 2.1.0.0-unk-beta I ran it out of the box, everything sync'd fine.
Went to make a transaction and the previously mentioned error above appeared.
Tried Normal->Stealth and Normal->Normal (assuming stealth address generation was previously dysfunctional in the release GUI)

Status of each transaction: 0/offline, has not been successfully broadcast yet
OS: Mac High Sierra

**Comment by justinvforvendetta** [comment]
which commit was this compiled from?

**Comment by AceTech07** [comment]
My first wraith protocol stealth transaction went thru without no problems.
Transferred from binance to wallet stealth address.  Now will try sending
to binance. I'm excited

**Comment by Positivism** [comment]
Downloaded the zip directly, I don't think to git unless I'm on linux.
Did the commit id happen to be logged somewhere?

**Comment by paradoxicalNL** [comment]
I'm compiling as well from latest, will also test!

2018-01-03 17:38 GMT+01:00 AceTech07 <notifications@github.com>:

> My first wraith protocol stealth transaction went thru without no problems.
> Transferred from binance to wallet stealth address. Now will try sending
> to binance. I'm excited
>

**Comment by jderwish** [comment]
@paradoxicalNL how much minimum memory and storage is required to run this wallet on ubuntu? do you know or any insight please..much appreciated.

**Comment by paradoxicalNL** [comment]
blockchain around 1.7gb only (checked folder size) and then enough size for
your environment and of course building, my compiled dir shows

paradoxical@Paradoxical-Win:~/git$ du -sh verge
898M    verge

I'd say you should be good with 15 GB and 1gb mem

2018-01-03 17:54 GMT+01:00 jderwish <notifications@github.com>:

**Comment by justinvforvendetta** [comment]
there is already an open thread for this, please only comment if you are running the latest code, not the latest binary

**Comment by jderwish** [comment]
I am running latest code, compiled on ubuntu.. :-)

**Comment by paradoxicalNL** [comment]
I compiled latest version in ubuntu 16.04 Verge > v2.1.0.0-7d417ad-beta
Testing funtionality, let me know if I can do something.


2018-01-03 20:33 GMT+01:00 jderwish <notifications@github.com>:

**Comment by jderwish** [comment]
![image](https://user-images.githubusercontent.com/32366979/34537881-19ac39d4-f098-11e7-96d2-6fc34b48ffe7.png)

**Comment by jderwish** [comment]
@paradoxicalNL sent a stealth transaction but shows offline and wallet is sync fully
Please see above screenshot and here is trx id#
e75Be33ec6baec745712a5f06b4eaeb571da4eaf7cd5f4b1042be45ee9589871

**Comment by paradoxicalNL** [comment]
Did i compile wrong version?

v2.1.0.0-7d417ad-beta

Cannot find / add stealth address. Normal transaction works just fine.

2018-01-03 21:17 GMT+01:00 jderwish <notifications@github.com>:

**Comment by jderwish** [comment]
https://github.com/vergecurrency/VERGE/blob/master/README.md

**Comment by jderwish** [comment]
@paradoxicalNL  thats the same version I have, when you create new address there is a check mark for stealthaddress

**Comment by paradoxicalNL** [comment]
@jderwish i messed up my copy paste, compiling now.

2018-01-03 21:39 GMT+01:00 jderwish <notifications@github.com>:

**Comment by jderwish** [comment]
@paradoxicalNL ok, sounds good - the transaction has no confirmation yet...

**Comment by jderwish** [comment]
@justinvforvendetta  any comment on my issue ?
