### ISSUE TITLE
WP: Add progress indicator on splash screen while loading blockchian 

### ISSUE THREAD

**Issue by ksteigerwald** [vergecurrency/VERGE#318]
The current splash screen only informs the user that the data is loading. As a user, I would like to see the progress of data as its being loaded.

**Comment by justinvforvendetta** [comment]
I agree that would be a good addition. progress indicator instead of just loading block index

**Comment by Tommixoft** [comment]
As i notice all QT wallets have the same stuff.. its open source project wallet and people just use the same wallet for every coin. Changes almost nothing in them. Also adding progress bar will slow import.

**Comment by justinvforvendetta** [comment]
no it would not slow the import

**Comment by Tommixoft** [comment]
Yes it would unless you create second thread for updating progress bar.

**Comment by ksteigerwald** [comment]
I am going to do a crash course on C++. Over the years I have done quite a bit of development, mostly with Swift/IOS as of late. I am hoping to get up to speed quickly to lend a hand with your UI. 

Should you have any good starting points as a recommendation, please share. Thanks! 
@justinvforvendetta @

**Comment by Max-Meldrum** [comment]
@justinvforvendetta @michpiatek this issue could probably be closed as the fix has been merged.
