### ISSUE TITLE
Wallet 4.0 Encryption Password

### ISSUE THREAD

**Issue by nhasanit** [vergecurrency/VERGE#321]
There is an issue with unlocking the wallet after encrypting it. I am able to change the password but not able to unlock it. Every time I try to unlock, I get the error saying the the encryption password is incorrect but I am able to change it in the change passphrase toggle. Even after changing, I am still unable to unlock the wallet. This is the case on both the Windows and Mac versions of the 4.0 wallet. I currently have some XVG stuck in one of the wallets.

**Comment by fr4z3n** [comment]
This bug is already fixed and will be in the bext release

**Comment by fr4z3n** [comment]
#316

**Comment by Tommixoft** [comment]
Yeah but too lazy to release. In whole day commiting amount of code that in 20minutes can be written EASY.
Can you SPEED UP release of more stable wallet?
