### ISSUE TITLE
esthetic issue on  http://vergeacceptingcompanies.com

### ISSUE THREAD

**Issue by bitness247** [vergecurrency/VERGE#322]
![capture d ecran 2018-01-03 a 12 34 16](https://user-images.githubusercontent.com/35049530/34532184-41b2b800-f083-11e7-90d6-6d83011f4629.png)
![capture d ecran 2018-01-03 a 12 34 26](https://user-images.githubusercontent.com/35049530/34532186-430a0ed8-f083-11e7-8202-a5138457d90d.png)

**Comment by fr4z3n** [comment]
This does not belong in this repository
