### ISSUE TITLE
Website hacked/ spelling mistake www.vergeacceptingcompanies.com

### ISSUE THREAD

**Issue by topdogshares** [vergecurrency/VERGE#323]
Showing pop up “Verge is a scam”

Spelling/ 
![a0a6b0f8-70da-4509-a566-de6c232a6821](https://user-images.githubusercontent.com/35075611/34533211-2efb1148-f0b1-11e7-87b2-8b46e9115b65.jpeg)
grammar error first paragraph 

spelling mistakes first paragraph starting Verge is a secure... at the end “knows where they can SPENT their coins”

**Comment by benammann** [comment]
the result of non '<' tag escaping forms

**Comment by justinvforvendetta** [comment]
this isn't the repo for that. I'm not even sure who runs it.

**Comment by topdogshares** [comment]
Ahh apologies Justin, not sure where to go then, not my field. Apologies if incorrect place.

**Comment by mikeuding** [comment]
Can I help with communication / marketing / infrastructure? Communication is going crisscross, which is causing damage. I am trying to get in contact for weeks now with other members, trying not to stress you with it, but unfortunately no response. Please DM twitter: @xverple, really willing to help.

**Comment by topdogshares** [comment]
Try @xvgmarketingeu on twitter that’s their marketing team.
