### ISSUE TITLE
Cannot verify verge-blockchain.com's certificate when downloading

### ISSUE THREAD

**Issue by paradoxicalNL** [vergecurrency/VERGE#324]
When compiling, there is option to download blockchain. Need to supply the certificate chain to correct this (minor) error, please see:

Do you wish to download the complete VERGE Blockchain (y/n)?y
rm: cannot remove 'go.sh-Verge-Blockchain.zip': No such file or directory
--2018-01-03 19:25:53--  https://verge-blockchain.com/blockchain/go.sh-Verge-Blockchain.zip
Resolving verge-blockchain.com (verge-blockchain.com)... 94.130.90.213, 2a01:4f8:10b:406a::2
Connecting to verge-blockchain.com (verge-blockchain.com)|94.130.90.213|:443... connected.
WARNING: cannot verify verge-blockchain.com's certificate, issued by ‘CN=Let's Encrypt Authority X3,O=Let's Encrypt,C=US’:
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 1380072385 (1,3G) [application/zip]

Not sure if this belongs here. Host lacks proper certificate chain, adding it should do the trick when using wget. If added wget can be executed without --no-check-certificate flag.

https://www.ssllabs.com/ssltest/analyze.html?d=verge%2dblockchain.com&s=94.130.90.213&hideResults=on

steps 
1. add proper chain https://verge-blockchain.com/
2. this will make --no-certificate flag obsolete

**Comment by nhanth87** [comment]
is it starting download the 1.3 GB?

**Comment by paradoxicalNL** [comment]
Yes it is. Just don't like certificate warnings.
File started correctly.

2018-01-03 20:46 GMT+01:00 Tran Huu Nhan <notifications@github.com>:

**Comment by jderwish** [comment]
@justinvforvendetta We need to make sure proper certificate with CA signed assigned to the url FQDN. Since we are promoting security, this is a must.

**Comment by jrsikors** [comment]
have relayed relevant information over to the admin of verge-blockchain.info and verge-blockchain.com to look into issue.  

doing some house cleaning and will close this issue here since it's not exactly QT related.
