### ISSUE TITLE
Issue and pull request templates

### ISSUE THREAD

**Issue by Sach97** [vergecurrency/VERGE#326]
To avoid flood from non dev (mainly fuders) people here is my contribution to Verge.
I've implemented  [Issue and pull request templates features](https://github.com/blog/2111-issue-and-pull-request-templates) for the repo

I hope it will help @justinvforvendetta 

You can find my contribution if you want to review it for the PR in my fork of the repo [Sach97/VERGE](https://github.com/Sach97/VERGE)
  
Edit : in my research for best practices issue templates etc I've found this [bot](https://probot.github.io/apps/sentiment-bot/)  it could be useful for moderating the issue workflow.

**Comment by rafaeloliveiras** [comment]
How about using the Mantis Bug Tracker ? Is a better way to report and track a bug!

**Comment by rafaeloliveiras** [comment]
We can move the Mantis and configure a free server for the project get a better way to track bugs

**Comment by justinvforvendetta** [comment]
much easier to keep the issues on github
