### ISSUE TITLE
Will current Electrum wallet be supported/compatible with new changes in blockchain?

### ISSUE THREAD

**Issue by Tommixoft** [vergecurrency/VERGE#328]
Im not very interested in Wraith features i do not own millions nor i buy cocaine with crypto. Im using Electrum  4.2.1 windows wallet can i be sure that this wallet will work after 1 year? or should i transfer my funds to QT wallet, when stable version comes, generated address?
Thanks.

**Comment by mikeuding** [comment]
This is not the correct channel for these kind of questions to be answered. Choose one of the channels at the community section on official Verge website. https://verge currency.com

**Comment by Tommixoft** [comment]
This is perfect place for such development and support questions. In other places verge team do no communicate. It's their fault that they do not provide ANY info whatsoever about new blockchain and wallets and people have to guess everything.

**Comment by ekryski** [comment]
I believe so but will need to confirm with @justinvforvendetta. I don't think any RPC signatures were changed so your normal transactions should work just fine. You won't have the ability to perform stealth transactions until there is a new Electrum wallet release.

**Comment by shyrwall** [comment]
Stealth can never be supported in Electrum but normal transactions should work as before.

**Comment by justinvforvendetta** [comment]
we do not have a 4.2.1 electrum, and neither does electrum for bitcoin. also, electrum can support stealth once we add it.

**Comment by shyrwall** [comment]
How can Electrum ever support stealth tx? You need to scan the blockchain to be able to see what transactions are ment for you. That cant happen with SPV unless you send your keys to the Electrum server which would break stealth.

**Comment by justinvforvendetta** [comment]
@shyrwall are you our friend running keff.org?

also, see here: (needs work, but absolutely possible.)

def parse_stealth(stealth):
    addr_bytes = DecodeBase58Check(stealth)
    version = int(addr_bytes[0].encode('hex'),16)
    option = int(addr_bytes[1].encode('hex'),16)
    scan_pubkey = addr_bytes[2:35]
    multi_n = int(addr_bytes[35:36].encode('hex'),16)
    spend_pubkeys = []
    for i in range(multi_n):
        spend_pubkeys.append(addr_bytes[36+(i*33):69+(i*33)])
    multi_m = int(addr_bytes[69+(i*33):70+(i*33)].encode('hex'),16)
    prefix_len = int(addr_bytes[70+(i*33):71+(i*33)].encode('hex'),16)
    prefix = addr_bytes[71+(i*33):]
    return version, option, scan_pubkey, multi_n, spend_pubkeys, multi_m, prefix_len, prefix

**Comment by shyrwall** [comment]
I don't see how it would work without sending the pubkeys to the server. But you are most likely better than me when it comes to this so good luck :) Would be great if it worked since full clients are a pain..

For keff.org no it's a hosting company. We sell anon VPSes under the domain. If you want a contact let me know.
