### ISSUE TITLE
Translation to greek language

### ISSUE THREAD

**Issue by johnbruno21** [vergecurrency/VERGE#330]
Hey verge users, im interested to translate the verge wallet and the website to greek but i dont know how because im new to this.Can someone teach me how to do this?Cheers

**Comment by rafaeloliveiras** [comment]
You can use this steps:
1 - create a fork of the project
2 - when fork created, you go to src/qt/locale and create a file like bitcoin_gk.ts
3 - copy the original file in english into the bitcoin_gk.ts
4 - Translate the file in the tags <translation> </translation>
5 - commit
6- make a pull request

**Comment by jrsikors** [comment]
https://github.com/vergecurrency/VERGE/pull/359  -- should be taken care of soon -- looks like someone already did it
