### ISSUE TITLE
Sending to Android wallet

### ISSUE THREAD

**Issue by bryanx86** [vergecurrency/VERGE#337]
Can anyone guide me on how to send my verge from binance to the verge Android wallet? Every time I try it says"withdrawal address error" I have a pixel XL, with the newest Android image on it. I have orbot installed and in VPN mode. I want to hold my Verge from binance. I do not want to leave it on an exchange. Please help! I know you guys are busy. Thank you.

**Comment by satrya-sabeni** [comment]
Hmm are you really copying the receive adress from the receive tab on the app? Withdraw from Binance has always worked for me.

**Comment by jderwish** [comment]
@bryanx86 definitely not a github question, but I will explain it and we can close this issue. You go to your binance withdrawal page and entered your Android Wallet Address and amount of XVG you want to transfer.

**Comment by bryanx86** [comment]
@jderwishyes I did that, didn't work. If not a GitHub?, Where should I ask?

**Comment by bryanx86** [comment]
Yes I copy from the verge app

**Comment by bryanx86** [comment]
I put in amount, binance comes back withdrawal address error

**Comment by bryanx86** [comment]
I'm just trying to hold my investment, any real help would be appreciated

**Comment by bryanx86** [comment]
You're basically telling me I'm not smart enough to follow directions, yes I did what it says to, that's why I'm here. But you want to make me out to just be stupid, thanks, glad I stayed with his coin

**Comment by bryanx86** [comment]
https://play.google.com/store/apps/details?id=com.vergeandroid.wallet

**Comment by bryanx86** [comment]
Wtf am I supposed to do?

**Comment by jderwish** [comment]
@bryanx86  It is the right wallet, when you open your account, are you able to see receive, balance and send? and it is sync?

**Comment by jderwish** [comment]
@bryanx86 you also downloaded Orbot? and in that App VPN mode is on and Verge App is checked?

**Comment by bryanx86** [comment]
Yes I have orbot installed and in VPN mode

**Comment by bryanx86** [comment]
And verge is checked

**Comment by satrya-sabeni** [comment]
Hmm have you when you're on the balance tab, have at least connected once succesfully? I don't think anyone is making you out to be stupid, sometimes mistakes come from something so simple you wouldn't expect, that's all.

**Comment by bryanx86** [comment]
I even had to give it permission in settings because it didn't prompt for it. Storage and phone permission

**Comment by jderwish** [comment]
ok share your wallet address let me send you a test transaction

**Comment by bryanx86** [comment]
The verge app, I've been trying for a couple of days but didn't want to bother anyone here because I know you're busy with a lot of other things, and I didn't want it to seem like fud, but I'm just trying to hold my verge

**Comment by bryanx86** [comment]
I'm on sdk 27, and I know the verge app Target is sdk 23, which is two versions older than mine

**Comment by bryanx86** [comment]
verge:DJnsSe6t5VtAD7hTwjHeSvviDyiwxMKMqC?amount=1

**Comment by jderwish** [comment]
@bryanx86 works fine - no issue with your address, you should see it in few seconds

Status: 0/unconfirmed, broadcast through 3 node(s)
Date: 2018-01-03 17:40
To: bryanx86 DJnsSe6t5VtAD7hTwjHeSvviDyiwxMKMqC
Debit: -1.00 XVG
Transaction fee: -0.10 XVG
Net amount: -1.10 XVG
Transaction ID: 47bbcd58ac617e1d3927dd5a53a7d68ecf4382edf22527f435c4ed46332f40ca

**Comment by bryanx86** [comment]
I pull down to refresh on the verge app, and there's colors moving at the top that shows it attempting to connect, and it says no connection. I have orbot installed properly, it's not new to me, but idk what else to do

**Comment by jderwish** [comment]
Going to Binance Funds - Deposits Widthrawals - click on Widthrawal

![image](https://user-images.githubusercontent.com/32366979/34543241-f3e19fb2-f0ad-11e7-9d50-970d3fc926be.png)
![image](https://user-images.githubusercontent.com/32366979/34543267-06759156-f0ae-11e7-8ad4-95469e0cb581.png)

**Comment by jderwish** [comment]
@bryanx86 https://verge-blockchain.info/address/DJnsSe6t5VtAD7hTwjHeSvviDyiwxMKMqC

**Comment by bryanx86** [comment]
I'm going to try to install on PC with Ubuntu

**Comment by jderwish** [comment]
@bryanx86  you don't need to wallet to be working on android.. Your Wallet address is most important, and your seed and secure phrase.  anyway wallet address works and you got 1 XVG from me.. once working please return the favor :-)

**Comment by bryanx86** [comment]
Thanks for your help. Didn't mean to be insulting, I'm just frustrated trying to get it working

**Comment by bryanx86** [comment]
I will return it to you, no worries. But I need it sync and work first, lol

**Comment by bryanx86** [comment]
I copied you address, and putting it in my contacts list. Hopefully it will be worth much much more when I send one back

**Comment by jderwish** [comment]
@bryanx86 Thank you - I would reboot the phone and toggle the Orbot VPN mode on and off and see, usually that fixes it.

**Comment by satrya-sabeni** [comment]
I've been having the same problem last 1-2 days with the wallet where it's hard to refresh the balance, it takes a couple times now but it's definitely there. Turning off and on Tor seems to help synch it

**Comment by bryanx86** [comment]
Turns out it's a problem with binance. I received the 1 that you sent and the Android wallet works great. Binance says withdrawal not available for this coin.@jderwish. also sent the 1 you sent back to the address you sent from

**Comment by jderwish** [comment]
@bryanx86  great! I have not received the transaction perhaps - still unconfirmed... will watch out for you. Thank you

**Comment by bryanx86** [comment]
@jderwish have you received the transaction yet?

**Comment by jderwish** [comment]
@bryanx86 Nope.. do you have a transaction # let's check the blockchain
