### ISSUE TITLE
User Interface Consistency

### ISSUE THREAD

**Issue by jlaureano** [vergecurrency/VERGE#342]
@justinvforvendetta 

One of the key factors for successful adoption of any application is its usability.

The VERGE wallet is built with the Qt interface which allows multi-platform builds. Benefit of this is the fact that the application will have a native look and feel.

Currently the VERGE wallet is not unified in User Experience and User Design.

I will like to collaborate to improve the UX / UI of the wallet so users have a top of the line product, and before dedicating time to this I would like to know if the core team has any plans in their timeline.

Attached are two screens, a before and an after. It was a simple change but it communicates trust to the user as the screen is displayed with the native OS UI.

<img width="705" alt="screen shot 2018-01-03 at 8 47 14 pm" src="https://user-images.githubusercontent.com/5193008/34547643-a6895f58-f0ca-11e7-84e5-9625579869f1.png">

<img width="705" alt="screen shot 2018-01-03 at 9 01 16 pm" src="https://user-images.githubusercontent.com/5193008/34547654-aef7b64e-f0ca-11e7-8ed7-d0ad1e327d94.png">

**Comment by jlaureano** [comment]
https://github.com/jlaureano/VERGE/commit/ea94a30174a63d06bde61b23b727ff4fb1cc3508

**Comment by justinvforvendetta** [comment]
@jlaureano looks nice, feel free to make a pull request. UI improvements are welcome

**Comment by jlaureano** [comment]
@justinvforvendetta deal, pushing this forward

**Comment by techpoy** [comment]
Hey @jilaureano can you take a look at #224 and see if you can take care of it? It doesn't look similar to Mac and it doesn't look good on Windows.

**Comment by jlaureano** [comment]
@techpoy that's on my list

**Comment by techpoy** [comment]
Excellent. Also pls see if you could resize the grid columns(50% each for Label and Address ?) so that address is fully visible. Thanks

**Comment by stefanoferi** [comment]
Hi @jlaureano 
we have to consolidate all the UI strings for translation purpose too, can we coordinate?

**Comment by jlaureano** [comment]
@stefanoferi i am on twitter (at) joselaureano
