### ISSUE TITLE
...

### ISSUE THREAD

**Issue by justinvforvendetta** [vergecurrency/VERGE#344]
not trolling. hello youtube chat.

**Comment by Positivism** [comment]
Proving your validity somewhere?

**Comment by Positivism** [comment]
Proving your authenticity somewhere?

**Comment by justinvforvendetta** [comment]
yeah i was

**Comment by jlaureano** [comment]
hey which channel are you in @justinvforvendetta

**Comment by justinvforvendetta** [comment]
this one: https://www.youtube.com/watch?v=mz5TmzvQHME

**Comment by jlaureano** [comment]
@justinvforvendetta this guy on the channel is legit and passionate.

**Comment by justinvforvendetta** [comment]
yeah seems like a nice guy, im sure we'll chit chat soon. i just closed out, gotta get back to work. nice to see so many people watching verge! ❤️

**Comment by paradoxicalNL** [comment]
A lot of people are stressed. Guess $ makes people like that.
I'm more focussend on that last bug :D

2018-01-04 5:17 GMT+01:00 sunerok <notifications@github.com>:
