### ISSUE TITLE
UI - unreadable hover due matching font color

### ISSUE THREAD

**Issue by paradoxicalNL** [vergecurrency/VERGE#346]
Linux - Ubuntu
Please note the hover which is (almost) unreadable. I might fix myself if I find time later on.

![img_20180104_052148340](https://user-images.githubusercontent.com/24474572/34550336-50d5d794-f110-11e7-9bb0-796d326393ff.jpg)

**Comment by topcatx** [comment]
Can we get a better screenshot, is that the tooltip for a stealth address ?

**Comment by paradoxicalNL** [comment]
Sorry, I was gonna apologize for the bad sceenshot, it's tooltip dissepears when taking it so used my phone.
Yes, that is the tooltip: 'Double-click to edit address or label'

**Comment by paradoxicalNL** [comment]
When you click the list of stored labels in the menu, that tooltip has the same background as well.

**Comment by paradoxicalNL** [comment]
I'm using this issue for a few more (search replace?)

Sign message TAB hovers for following items have the same 'issue':

> address input
> message input
> hover 'paste address from clipboard'
> Copy the current signature to the system clipboard
> Sign message button
> Clear All button

Verify message TAB

> address input
> message input
> view message button
> clear all button

**Comment by paradoxicalNL** [comment]
These files have the same 'issue'

Menu settings >

Main
Pay transaction fee box > hover

Network
Proxy > hover
Port > hover
SOCKS Version > hover

Display
User interface language > hover
Inits to show amounts in: > hover

**Comment by jrsikors** [comment]
doing some spring cleaning on old issues not responded to -- please re-open if having issues with the latest version of the wallet
