### ISSUE TITLE
UI - double option mining in list on transacation tab

### ISSUE THREAD

**Issue by paradoxicalNL** [vergecurrency/VERGE#349]
Transaction Tab

Drop down on top, contains double entry for mining, see screenshot.

![mining-double](https://user-images.githubusercontent.com/24474572/34551673-618c58c2-f11c-11e7-8c07-a1b9c0f77371.jpg)

**Comment by dbtftw** [comment]
VERGE/src/qt/transactionview.cpp

    typeWidget->addItem(tr("Mined"), TransactionFilterProxy::TYPE(TransactionRecord::StakeMint));
    typeWidget->addItem(tr("Mined"), TransactionFilterProxy::TYPE(TransactionRecord::Generated));

Maybe we just need to name the difference from StakeMint and Generated.

**Comment by justinvforvendetta** [comment]
we can remove stakemint

**Comment by Max-Meldrum** [comment]
@justinvforvendetta @michpiatek 
Looks like this one can be closed?
Cheers

**Comment by jrsikors** [comment]
closing issue.  if still an issue, please let us know
