### ISSUE TITLE
Verge Linux Wallet crashing

### ISSUE THREAD

**Issue by Felhamed** [vergecurrency/VERGE#351]
My VERGE-qt wallet keeps crashing even when doing basic things like generating a new address or clicking through the menus. Getting a segmentation fault. How do I generate a debug report to see whats causing it? Also how do I use VERGEd with the VERGE-qt wallet. As of now I cannot run both at the same time.

**Comment by paradoxicalNL** [comment]
Your debug log is in: ~/VERGE/debug.log

**Comment by dbtftw** [comment]
Please post a crash log if possible as well

**Comment by justinvforvendetta** [comment]
also post what commit you are on as well

**Comment by Felhamed** [comment]
`libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
[1]    20818 segmentation fault (core dumped)  ./VERGE-qt -conf=/home/user/.VERGE/VERGE.conf
`
debug.log doesn't show much
`received getdata for: tx be24f3ad9b5e7ae7e93d
getblocks 1773414 to 00000000000000000000 limit 500
accepted connection 24.89.46.43:61125
send version message: version 90001, blocks=1773414, us=104.255.12.173:21102, them=24.89.46.43:61125, peer=24.89.46.43:61125
Added time data, samples 18, offset +0 (+0 minutes)
Moving 24.89.46.43:21102 to tried
receive version message: version 90001, blocks=233876, us=104.255.12.173:21102, them=24.89.46.43:21102, peer=24.89.46.43:61125
`

commit b97f4dda4db7b3de6e6cca3de0c11be8d719e6b4 (HEAD -> master, origin/master, origin/HEAD)
Merge: 02afb16 2527e36
Author: sunerok <justinvforvendetta@users.noreply.github.com>
Date:   Wed Jan 3 23:20:51 2018 -0500

    Merge pull request #339 from Max-Meldrum/smallupdates
    
    Add initial dev notes and move build instructions to doc instead.

**Comment by justinvforvendetta** [comment]
try updating to the newest version and let us know if it happens again

**Comment by Felhamed** [comment]
Updated to `commit f4e2bb3f70fd30862c192e138c2466e3987037e5 (HEAD -> master, origin/master, origin/HEAD)`

I'm still getting:
`libpng warning: iCCP: known incorrect sRGB profile
[1]    30780 segmentation fault (core dumped)  ./VERGE-qt -conf=/home/firas/.VERGE/VERGE.conf
`
Btw, is it normal to take ~5min on wallet startup, it is stuck on this screen:
https://i.imgur.com/ce7rVMw.png

**Comment by techpoy** [comment]
Yes it takes time to load block index and it is normal. Devs are planning to add progress indicator to this screen in later releases.

**Comment by frontr-uk** [comment]
' screen in later releases.' should we set a label to "OnHold"

**Comment by paradoxicalNL** [comment]
About the libpng error
libpng warning: iCCP: known incorrect sRGB profile libpng warning

Verge uses libpng-1.6 (i checked).

_Some changes in libpng version 1.6+ cause it to issue a warning or even not work correctly with the original HP/MS sRGB profile, leading to the following stderr: libpng warning: iCCP: known incorrect sRGB profile The old profile uses a D50 whitepoint, where D65 is standard. This profile is not uncommon, being used by Adobe Photoshop, although it was not embedded into images by default._

_Error detection in some chunks has improved; in particular the iCCP chunk reader now does pretty complete validation of the basic format. Some bad profiles that were previously accepted are now rejected, in particular the very old broken Microsoft/HP sRGB profile. The PNG spec requirement that only grayscale profiles may appear in images with color type 0 or 4 and that even if the image only contains gray pixels, only RGB profiles may appear in images with color type 2, 3, or 6, is now enforced. The sRGB chunk is allowed to appear in images with any color type._

source: https://wiki.archlinux.org/index.php/Libpng_errors
source: https://forum.qt.io/topic/58638/solved-libpng-warning-iccp-known-incorrect-srgb-profile-drive-me-nuts/16

See: https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile
