### ISSUE TITLE
Encrypt wallet (windows QT 4.0) doesn't work properly

### ISSUE THREAD

**Issue by Bono76** [vergecurrency/VERGE#352]
When I encrypted my wallet with a passphrase, my wallet closed in a second. When I reopened the wallet I could'nt unlock the wallet. It was saying my passphrase was incorrect. But it wasn't. However I was able to change my passphrase to another passphrase. After that my wallet was unlocked also.

**Comment by justinvforvendetta** [comment]
is this running the latest code from the github? or the binary? this issue was fixed in the source code already.
