### ISSUE TITLE
Wallet crash (windows QT 4.0)

### ISSUE THREAD

**Issue by Bono76** [vergecurrency/VERGE#353]
My wallet crashed yesterday evening and I couldn't open it anymore. This morning I restarted my laptop and opened Verge-qt. At the same time my windows defender gave a message there was a virus "Trojan:Win32/Peals.F!cl. Windows Defender put some files in quarantaine. So I wasn't able to open my wallet. I shut off my windows defender and started Verge-qt again and the progamm was saying there are missing some files: QT5core.dll, QT5sensors.dll and QT5widgets.dll. I copied those files from another folder and I was able to restart the wallet again.

**Comment by justinvforvendetta** [comment]
sounds weird. cant reproduce.

**Comment by Bono76** [comment]
Yes it is ;), But my wallet is open now, after I shut down my windows defender. But when I scan my verge-b2 folder again, it still gives a message "threat found" "Trojan:Win32/Peals.F!c". I don't know at this moment whether it is a crash problem of I have a security problem. But I don't think it is a security problem. When I fix the virus, then windows put some dll files in quarantaine.

**Comment by paradoxicalNL** [comment]
Can you locate the files in question and run them on https://www.virustotal.com
This will pull them through multiple scanners and also check file hash for giving file (those files are likely in the database)

**Comment by Bono76** [comment]
I will do later. I think within 2 hours.

**Comment by Bono76** [comment]
Ok, I scanned the Qt5Core.dll file with virustotal.com and there were no engines detected in the file.
My windows defender is still claiming there is a virus when I enable windows defender.

Result virustotal.com:

0 / 66
No engines detected this file
SHA-256	475bcac9032e057376873b18acdb0d46c69d1007f962d0fc1a6cc09e7d67e1a0
File name	Qt5Core.dll
File size	4.86 MB
Last analysis	2018-01-01 16:15:31 UTC

**Comment by paradoxicalNL** [comment]
https://github.com/scudzey/UVROverlay/issues/3
https://github.com/fritzing/fritzing-app/issues/3267

Looks like this is happening more often. As workaround for now:

Workaround:
- whitelist verge folder containing QT files

FIX:
- submit false positive to windows

**Comment by TheOwlie** [comment]
Not happening on my windows 10 Machine.

**Comment by Bono76** [comment]
I have windows 10 also. There were no issues in the beginning. I have the wallet installed on Monday. But there was a windows update installed yesterday. The wallet crashed yesterday evening and since this morning I have this issue.

**Comment by paradoxicalNL** [comment]
So from your message I can make up that windows defender quarantines following files;

QT5core.dll
QT5sensors.dll
QT5widgets.dll

These are mandatory for operation

I have windows 10, can you share me link you downloaded / or which version so I can try to reproduce?
What are your windows defender settings? See: windows defender security center

**Comment by Bono76** [comment]
My windows version is:

Windows 10 Pro
Version 1709
Build operating system 16299.125

My Verge QT wallet was downloaded from 
https://github.com/vergecurrency/VERGE/releases/download/4.0/verge-qt-4.0-win64.zip

Windows defender settings:

'Windows defender antivirus notifications' is activated
'Real-time security' is acivated
'Cloud security' is acivated
Only 'controlled folder acces' is deactivated

'Windows defender firewall notifications' is activated with all the checkboxes active.

**Comment by Bono76** [comment]
![image](https://user-images.githubusercontent.com/35093511/34566335-710d2ab4-f15e-11e7-9522-84da77042418.png)

![image](https://user-images.githubusercontent.com/35093511/34566080-925cd260-f15d-11e7-87d0-a7731e9486b4.png)

![image](https://user-images.githubusercontent.com/35093511/34566133-c838f1c0-f15d-11e7-9e0d-fe506beb26d2.png)

![image](https://user-images.githubusercontent.com/35093511/34566153-dbc8e556-f15d-11e7-91cd-ae451deb4303.png)

**Comment by paradoxicalNL** [comment]
Hoi!

downloaded same version here.
set all settings to match yours, except for cloud-delivered protection

Cannot re-produce. Can you test with disabling cloud-delivered protection? I must have disabled it using doNotSpy and cant reboot now.

**Comment by Bono76** [comment]
Hoi ;),
When I disable cloud-deliverd protection, I still have the same problem. Only when I disable Real-time security I can open the wallet.

It was working without problems from monday until yesterday. Since this morning I have the virus problem. When it crashed I was starting the wallet while it was already open. After that, I closed the wallet and open the wallet again and then it stopped with loading (crashed). Then I shut down my computer and this morning I started the wallet again with the virus problem.

**Comment by paradoxicalNL** [comment]
Not sure what to do.

Cannot reproduce, and looks like a problem not with verge (QT) but with scanner.
My suggestion to just whitelist the folder so you do not have these problems.

**Comment by Bono76** [comment]
It is a strange problem ;). 
Latest windows updates, see:
![image](https://user-images.githubusercontent.com/35093511/34576839-8b3081f4-f17f-11e7-9d08-5e7b21350009.png)

I think I will wait for the 4.0.1 release. Maybe the problem is solved automatically after that.

**Comment by paradoxicalNL** [comment]
Sorry, that should be win defender virus definitions. I think it's self
explanatory that some pattern in those definitions is matching the QT
files, hence false positive.

If you want you can submit this to Microsoft, or send me the files and I'll
do that.

https://www.microsoft.com/en-us/wdsi/filesubmission


Op 4 jan. 2018 6:47 p.m. schreef "Bono76" <notifications@github.com>:

**Comment by Bono76** [comment]
I have whitelist the folder and submit the issue to Microsoft.

**Comment by paradoxicalNL** [comment]
Thanks!

Op 6 jan. 2018 10:34 a.m. schreef "Bono76" <notifications@github.com>:
