### ISSUE TITLE
Automatic Updates

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#355]
Hey there,

this might be more a enchancement but nevertheless I wanted to submit this, because I find it
very odd to check github.com etc. every day to check wether there is or not.
So feel free to add an update client feature, which backups the wallet automatically and replaces the client files with the update ones. 

Regards, Kyon

**Comment by justinvforvendetta** [comment]
that can be done by users as a cron job, but we should offer a solution for osx and windows. good idea.

**Comment by sovietmah** [comment]
Ya, i think is very good idea.
A lot of coins wallet doesn't have this feature too. it will be great advantage.

**Comment by Sach97** [comment]
Found this [Qt library](https://github.com/Skycoder42/QtAutoUpdater)

**Comment by EssKayz** [comment]
The GridCoin[GRC] QT wallet has a feature like this built-in to some extent, you can click "Update" and it will check for update and update if neccessary.

**Comment by marioathiel** [comment]
Great idea, should be added as a later feature as it doesn't seem vital at this stage in our evolution. Still mostly nerds involved in using the wallets rather the the general public. Maybe Q3-Q4 polished wallet mainstream release?  love ya @justinvforvendetta and the rest of the team!

**Comment by zsuerdieck** [comment]
Sorry for my ignorance, but how do I update my client with the latest from github?

**Comment by jderwish** [comment]
@justinvforvendetta  when are you going to update windows binary so others are able to download from the website?

**Comment by justinvforvendetta** [comment]
@jderwish when we finish updating in the other branch and push it to master. after that.

**Comment by jderwish** [comment]
@justinvforvendetta I would recommend that you or someone put forward a good announcement via your official channels. It is very important for community and others to see a product status to avoid any FUD and misinformation in the community.

**Comment by jrsikors** [comment]
Is anyone working on this ? No rush, just checking in for a status update !

Please re-open issue if you are actively working on it
