### ISSUE TITLE
Progress bar not displayed properly - Tool Box windows compatibility Issue

### ISSUE THREAD

**Issue by techpoy** [vergecurrency/VERGE#356]
Tool bar is not displayed properly on windows. I think it is rendering fine on Mac. This affects look and feel of export address button as well progress bar at the bottome 
![image](https://user-images.githubusercontent.com/34836326/34559498-140ca704-f168-11e7-9d6e-d89eac56f14e.png)

**Comment by jlaureano** [comment]
@techpoy 

I am putting together a design guide and fixing all UI issues

**Comment by techpoy** [comment]
That is great friend. . I have some idea that I would like to discuss with you. I got your twitter and I will connect with you on twitter.

**Comment by Influence2** [comment]
I believe this issue is resolved with the latest version of the wallet. @techpoy If so can you please close this issue?
