### ISSUE TITLE
Loading blockchain [unresponsive application]

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#357]
As I would like raise the  on the user experience, I had some heavy issues on both 
**MacOS and Win10**, while loading the database. 

It takes a lot of time to start up the application, maybe we should think about switching the database, which it's stored in to make it locally faster or we give our users some kind of feedback about the loading state, otherwise I would find odd to have the application loading for minutes without any response.

**Comment by techpoy** [comment]
It is already reported. Devs are planning to add progress bar. kindly see #318 . you can close this issue to avoid duplication of the same issue.
