### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by jjj092353** [vergecurrency/VERGE#36]
CXX      qt/qt_libbitcoinqt_a-radio.o
qt/radio.cpp:8:20: fatal error: QtWebKit: No such file or directory
 #include <QtWebKit>
                    ^
compilation terminated.
make[1]: *** [qt/qt_libbitcoinqt_a-radio.o] Error 1
make[1]: Leaving directory `/home/coins/VERGE/src'
make: *** [all-recursive] Error 1

**Comment by vergecurrency** [comment]
hmm, maybe you didnt install libqt5webkit5-dev? it's listed in the dependencies.

**Comment by jjj092353** [comment]
it's definitely installed. ubuntu 14.04

**Comment by jjj092353** [comment]
did find:

me@pools:/home/coins/VERGE# find / -name qt_libbitcoinqt_a-radio*
/home/coins/VERGE/src/qt/.deps/qt_libbitcoinqt_a-radio.Po

**Comment by vergecurrency** [comment]
qmake -v?
sounds like maybe you arent using qt5

**Comment by jjj092353** [comment]
Using Qt version 4.8.6 in /usr/lib/x86_64-linux-gnu

**Comment by vergecurrency** [comment]
sudo apt-get install qt5-default

our wallet uses qt5 ;]

**Comment by jjj092353** [comment]
stil fails:

  CXX      qt/qt_libbitcoinqt_a-radio.o
qt/radio.cpp:8:20: fatal error: QtWebKit: No such file or directory
 #include <QtWebKit>
                    ^
compilation terminated.
make[1]: *** [qt/qt_libbitcoinqt_a-radio.o] Error 1
make[1]: Leaving directory `/home/coins/VERGE/src'
make: *** [all-recursive] Error 1

###
me@pools:~# qmake -v
QMake version 3.0
Using Qt version 5.2.1 in /usr/lib/x86_64-linux-gnu

###
rme@pools:/home/coins/VERGE# apt-get install libqt5webkit5-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libqt5webkit5-dev is already the newest version.
0 to upgrade, 0 to newly install, 0 to remove and 224 not to upgrade.

**Comment by vergecurrency** [comment]
sudo apt-get update && sudo apt-get upgrade

that will get you to qt 5.3.2

also make sure you:

make clean && ./autogen.sh && ./configure && make

**Comment by vergecurrency** [comment]
i should actually add sudo apt-get update && sudo apt-get upgrade to the linux instructions. 

did that work @jjj092353 ?

**Comment by jjj092353** [comment]
after all that.

nope

  CXX      qt/qt_libbitcoinqt_a-radio.o
qt/radio.cpp:8:20: fatal error: QtWebKit: No such file or directory
 #include <QtWebKit>
                    ^
compilation terminated.
make[1]: *** [qt/qt_libbitcoinqt_a-radio.o] Error 1
make[1]: Leaving directory `/home/coins/VERGE/src'
make: *** [all-recursive] Error 1
me@pools:/home/coins/VERGE#

**Comment by vergecurrency** [comment]
you sure you did a make clean in the /verge/ directory first?

**Comment by vergecurrency** [comment]
what flavor of nix are you using?

**Comment by jjj092353** [comment]
Yes.did clean. Ubuntu 14.04

**Comment by mkinney** [comment]
Run this:
sudo apt-get install libdb4.8-dev libdb4.8++-dev build-essential libtool autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils git libboost-all-dev libminiupnpc-dev libqt5gui5 libqt5core5a libqt5webkit5-dev libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libqrencode-dev

Then:
make clean &&  ./autogen.sh && ./configure && make

**Comment by jjj092353** [comment]
did all that - no joy

  CXX      qt/qt_libbitcoinqt_a-radio.o
qt/radio.cpp:8:20: fatal error: QtWebKit: No such file or directory
 #include <QtWebKit>
                    ^
compilation terminated.
make[1]: *** [qt/qt_libbitcoinqt_a-radio.o] Error 1
make[1]: Leaving directory `/home/coins/VERGE/src'
make: *** [all-recursive] Error 1
me@pools:/home/coins/VERGE# ^C

can you compile a version for me - this is crazy - I have compiled over 200 wallets on this machine in the past 3 years and never a problem like this.

**Comment by jjj092353** [comment]
by the way - this is a headless server

**Comment by vergecurrency** [comment]
oh, then just ./autogen.sh && ./configure --without-gui && make

**Comment by vergecurrency** [comment]
you can skip all the qt stuff anyway then, since you dont need a gui wallet

**Comment by vergecurrency** [comment]
@jjj092353 what pool are you from btw?

**Comment by jjj092353** [comment]
thanks for your help - now the nomp server will not connect to the wallet (on a different server) and throw this error: 2016-05-10 09:46:23 [Pool]      [smhverge] (Thread 1) The address provided is not from the daemon wallet - this is required for POS coins.

**Comment by vergecurrency** [comment]
the algo= for the .conf is in the readme file, but i will add a section to explain how to compile the daemon without the qt gui. glad everything worked out! ill add your pool to our website and OP.

**Comment by jjj092353** [comment]
thanks for you help - much appreciated
