### ISSUE TITLE
Mining

### ISSUE THREAD

**Issue by mnott** [vergecurrency/VERGE#360]
Mining from within the Wallet (Mac) using -gen=1 seems to not yield a result (probably because it is using CPU Mining only?).

So what would be a useful setup to actually do Verge mining? Any /practical/ guidance? Like, what would you need to mine 1k Verge a day.

Thank you.

**Comment by TheOwlie** [comment]
It helps if you specify what version you are using.

**Comment by mnott** [comment]
v4.0.1.0-f4e2bb3-beta

**Comment by cryptophill** [comment]
'like what would you need to mine 1k verge a day'
A few mining rigs made up of 20+ x 1080s running at optimal performance. 
Best way to mine xvg at the moment is with nvidia cards using the x17 algo. A 1080 is between 12-14 MH/s, 1070 9-11 MH/S and a 1080ti 20+. 1 1080 running in the mid 20s in a day will net you roughly 40 some coins. So do the math.

**Comment by mnott** [comment]
Thanks for the guidance.
