### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Lois2901** [vergecurrency/VERGE#362]
OS X Sierra 10.12.6
The wallet 4.0 refused be to launch.

**Comment by paradoxicalNL** [comment]
Can you supply more information;

1. can you explain refused to launch (takes forever, crashes?)
2. any error output?
3. debug log

**Comment by Lois2901** [comment]
Process:               VERGE-Qt [13887]
Path:                  /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
Identifier:            com.vergecurrency.VERGE-Qt
Version:               2.1.0 (2.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VERGE-Qt [13887]
User ID:               501

Date/Time:             2018-01-04 15:38:58.086 +0100
OS Version:            Mac OS X 10.12.6 (16G29)
Report Version:        12
Anonymous UUID:        E8A18EDD-2150-7E6F-DE9A-387357159951

Sleep/Wake UUID:       78BA2F08-D387-4EF0-BFDA-1E44E80F9401

Time Awake Since Boot: 180000 seconds
Time Since Wake:       4400 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x101167000 -        0x101894ff7 +com.vergecurrency.VERGE-Qt (2.1.0 - 2.1.0) <5EBCFD6F-D5DC-3276-80F4-F8FA95BB8C17> /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
       0x101935000 -        0x101937ff7 +libboost_system.dylib (0) <571C7888-D10F-3CB1-8DDB-460887DC314C> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x10193a000 -        0x101947fff +libboost_filesystem.dylib (0) <A742D64A-E278-3C8E-954A-D7C836ED6B53> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x101957000 -        0x101987fff +libboost_program_options-mt.dylib (0) <78525B93-6E1C-3BD8-89A4-2FADABACDD56> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x1019a9000 -        0x1019b7fff +libboost_thread-mt.dylib (0) <5BF9428B-F1C9-3CDE-B970-C17A41415A36> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x1019c5000 -        0x1019c7ff7 +libboost_chrono-mt.dylib (0) <1BF07246-8624-3109-8030-F23357EA1F37> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x1019d1000 -        0x101edcfff +QtWidgets (5.5.1) <416CBC52-D42C-3996-B338-C848863E65B0> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x102012000 -        0x102496fff +QtGui (5.5.1) <217B896F-895F-3DEC-BF29-01E065492858> /Applications/VERGE-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x102579000 -        0x102a80fff +QtCore (5.5.1) <201F9A70-4676-3BC5-8B59-82DA94559272> /Applications/VERGE-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x102b11000 -        0x102c1eff7 +QtNetwork (5.5.1) <CC4ADD9F-E8C7-3618-9D83-7DBF9AC4267A> /Applications/VERGE-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x102c55000 -        0x104697fff +QtWebKit (5.5.1) <693CF012-F937-3DB1-A6A9-05BB6DA6FE69> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWebKit.framework/Versions/5/QtWebKit
       0x10492b000 -        0x104959ff7 +QtWebKitWidgets (5.5.1) <84451F1E-1CE1-3A7D-9CB9-BD686BA98B92> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWebKitWidgets.framework/Versions/5/QtWebKitWidgets
       0x104981000 -        0x1049e4ff7 +QtDBus (5.5.1) <B0B9AE70-B993-3081-9336-E01BD1233823> /Applications/VERGE-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x1049fe000 -        0x104a04fff +libqrencode.4.dylib (0) <5B7DEE75-603E-351D-B14C-21663CD470BC> /Applications/VERGE-Qt.app/Contents/Frameworks/libqrencode.4.dylib
       0x104a08000 -        0x104b3aff7 +libprotobuf.15.dylib (0) <6300475A-5FB2-39C0-AE54-644CFAC18091> /Applications/VERGE-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x104bea000 -        0x104d0eff7 +libdb_cxx-4.8.dylib (0) <893E0F96-1F8A-3073-B1CF-CC60610C3E90> /Applications/VERGE-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x104d4a000 -        0x104d52ff3 +libminiupnpc.16.dylib (0) <C103607F-F06C-34D6-A60A-27E9E344F015> /Applications/VERGE-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x104d5a000 -        0x104d9bfff +libssl.1.0.0.dylib (0) <3C28C2A8-036B-34B3-82BB-5780DB7271B2> /Applications/VERGE-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x104dbb000 -        0x104f2bc87 +libcrypto.1.0.0.dylib (0) <1C6D06DA-0F88-37BA-80E9-52C4AC7E942C> /Applications/VERGE-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x108b63000 -        0x108ba0dc7  dyld (433.5) <322C06B7-8878-311D-888C-C8FD2CA96FF3> /usr/lib/dyld
    0x7fff7b7a5000 -     0x7fff7b7a9ffb  com.apple.agl (3.3.1 - AGL-3.3.1) <752FDB92-EF67-3D04-BF40-A352BF1075CF> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff7cab7000 -     0x7fff7d890ff3  com.apple.AppKit (6.9 - 1504.83.101) <AE51ACB3-D501-3F91-B369-3D3711F24D0A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff7d8a2000 -     0x7fff7d8a2fff  com.apple.ApplicationServices (48 - 48) <DA687F9A-7B2D-342B-8796-16E45344F853> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff7ef7d000 -     0x7fff7f416ff7  com.apple.CoreFoundation (6.9 - 1349.8) <09ED473E-5DE8-307F-B55C-16F6419236D5> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff7fe42000 -     0x7fff7fe42fff  com.apple.CoreServices (775.19 - 775.19) <7255917D-EFBB-3BE2-A8FD-DAD631BC0949> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff8085e000 -     0x7fff80863fff  com.apple.DiskArbitration (2.7 - 2.7) <70F56042-EF04-3BAF-9E04-90F423FB2BCC> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff809f5000 -     0x7fff80d9bfff  com.apple.Foundation (6.9 - 1349.91) <A37CB4EC-0730-3DD6-9358-60491BF40EF2> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff80f5c000 -     0x7fff80ff2ff7  com.apple.framework.IOKit (2.0.2 - 1324.60.3) <7CE4C98B-107C-3AAA-B49A-F2ACFCBBF526> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff83fc2000 -     0x7fff83fd0fff  com.apple.opengl (14.0.16 - 14.0.16) <167C9883-A79E-3B7F-AFED-8CD6683B291D> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff931e2000 -     0x7fff931e3ffb  libSystem.B.dylib (1238.60.2) <F18AC1E7-C6F1-34B1-8069-BE571B3231D4> /usr/lib/libSystem.B.dylib
    0x7fff9331c000 -     0x7fff93372ff7  libc++.1.dylib (307.5) <0B43BB5D-E6EB-3464-8DE9-B41AC8ED9D1C> /usr/lib/libc++.1.dylib
    0x7fff93373000 -     0x7fff9339cff7  libc++abi.dylib (307.4) <BC271AD3-831B-362A-9DA7-E8C51F285FE4> /usr/lib/libc++abi.dylib
    0x7fff93e91000 -     0x7fff94263047  libobjc.A.dylib (709.1) <70614861-0340-32E2-85ED-FE65759CDFFA> /usr/lib/libobjc.A.dylib
    0x7fff946b0000 -     0x7fff946b4ff7  libcache.dylib (79) <093A4DAB-8385-3D47-A350-E20CB7CCF7BF> /usr/lib/system/libcache.dylib
    0x7fff946b5000 -     0x7fff946bffff  libcommonCrypto.dylib (60092.50.5) <8A64D1B0-C70E-385C-92F0-E669079FDA90> /usr/lib/system/libcommonCrypto.dylib
    0x7fff946c0000 -     0x7fff946c7fff  libcompiler_rt.dylib (62) <55D47421-772A-32AB-B529-1A46C2F43B4D> /usr/lib/system/libcompiler_rt.dylib
    0x7fff946c8000 -     0x7fff946d0fff  libcopyfile.dylib (138) <819BEA3C-DF11-3E3D-A1A1-5A51C5BF1961> /usr/lib/system/libcopyfile.dylib
    0x7fff946d1000 -     0x7fff94754fdf  libcorecrypto.dylib (442.50.19) <65D7165E-2E71-335D-A2D6-33F78E2DF0C1> /usr/lib/system/libcorecrypto.dylib
    0x7fff94755000 -     0x7fff94786fff  libdispatch.dylib (703.50.37) <6582BAD6-ED27-3B30-B620-90B1C5A4AE3C> /usr/lib/system/libdispatch.dylib
    0x7fff94787000 -     0x7fff9478cffb  libdyld.dylib (433.5) <9B2AC56D-107C-3541-A127-9094A751F2C9> /usr/lib/system/libdyld.dylib
    0x7fff9478d000 -     0x7fff9478dffb  libkeymgr.dylib (28) <7AA011A9-DC21-3488-BF73-3B5B14D1FDD6> /usr/lib/system/libkeymgr.dylib
    0x7fff9479b000 -     0x7fff9479bfff  liblaunch.dylib (972.70.1) <B856ABD2-896E-3DE0-B2C8-146A6AF8E2A7> /usr/lib/system/liblaunch.dylib
    0x7fff9479c000 -     0x7fff947a1ff3  libmacho.dylib (898) <17D5D855-F6C3-3B04-B680-E9BF02EF8AED> /usr/lib/system/libmacho.dylib
    0x7fff947a2000 -     0x7fff947a4ff3  libquarantine.dylib (85.50.1) <12448CC2-378E-35F3-BE33-9DC395A5B970> /usr/lib/system/libquarantine.dylib
    0x7fff947a5000 -     0x7fff947a6ffb  libremovefile.dylib (45) <38D4CB9C-10CD-30D3-8B7B-A515EC75FE85> /usr/lib/system/libremovefile.dylib
    0x7fff947a7000 -     0x7fff947bfff7  libsystem_asl.dylib (349.50.5) <096E4228-3B7C-30A6-8B13-EC909A64499A> /usr/lib/system/libsystem_asl.dylib
    0x7fff947c0000 -     0x7fff947c0ff7  libsystem_blocks.dylib (67) <10DC5404-73AB-35B3-A277-A8AFECB476EB> /usr/lib/system/libsystem_blocks.dylib
    0x7fff947c1000 -     0x7fff9484efef  libsystem_c.dylib (1158.50.2) <E5AE5244-7D0C-36AC-8BB6-C7AE7EA52A4B> /usr/lib/system/libsystem_c.dylib
    0x7fff9484f000 -     0x7fff94852ffb  libsystem_configuration.dylib (888.60.2) <BECC01A2-CA8D-31E6-BCDF-D452965FA976> /usr/lib/system/libsystem_configuration.dylib
    0x7fff94853000 -     0x7fff94856fff  libsystem_coreservices.dylib (41.4) <7D26DE79-B424-3450-85E1-F7FAB32714AB> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff94857000 -     0x7fff9486ffff  libsystem_coretls.dylib (121.50.4) <EC6FCF07-DCFB-3A03-9CC9-6DD3709974C6> /usr/lib/system/libsystem_coretls.dylib
    0x7fff94870000 -     0x7fff94876fff  libsystem_dnssd.dylib (765.50.9) <CC960215-0B1B-3822-A13A-3DDE96FA796F> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff94877000 -     0x7fff948a0ff7  libsystem_info.dylib (503.50.4) <611DB84C-BF70-3F92-8702-B9F28A900920> /usr/lib/system/libsystem_info.dylib
    0x7fff948a1000 -     0x7fff948c3ff7  libsystem_kernel.dylib (3789.70.16) <34B1F16C-BC9C-3C5F-9045-0CAE91CB5914> /usr/lib/system/libsystem_kernel.dylib
    0x7fff948c4000 -     0x7fff9490bfe7  libsystem_m.dylib (3121.6) <86D499B5-BBDC-3D3B-8A4E-97AE8E6672A4> /usr/lib/system/libsystem_m.dylib
    0x7fff9490c000 -     0x7fff9492aff7  libsystem_malloc.dylib (116.50.8) <A3D15F17-99A6-3367-8C7E-4280E8619C95> /usr/lib/system/libsystem_malloc.dylib
    0x7fff9492b000 -     0x7fff94984ffb  libsystem_network.dylib (856.60.1) <369D0221-56CA-3C3E-9EDE-94B41CAE77B7> /usr/lib/system/libsystem_network.dylib
    0x7fff94985000 -     0x7fff9498eff3  libsystem_networkextension.dylib (563.60.2) <B021F2B3-8A75-3633-ABB0-FC012B8E9B0C> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff9498f000 -     0x7fff94998ff3  libsystem_notify.dylib (165.20.1) <B8160190-A069-3B3A-BDF6-2AA408221FAE> /usr/lib/system/libsystem_notify.dylib
    0x7fff94999000 -     0x7fff949a1fe7  libsystem_platform.dylib (126.50.8) <897462FD-B318-321B-A554-E61982630F7E> /usr/lib/system/libsystem_platform.dylib
    0x7fff949a2000 -     0x7fff949acff7  libsystem_pthread.dylib (218.60.3) <B8FB5E20-3295-39E2-B5EB-B464D1D4B104> /usr/lib/system/libsystem_pthread.dylib
    0x7fff949ad000 -     0x7fff949b0ff7  libsystem_sandbox.dylib (592.70.1) <4B92EC49-ACD0-36AE-B07A-A2B8152EAF9D> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff949b1000 -     0x7fff949b2ff3  libsystem_secinit.dylib (24.50.4) <F78B847B-3565-3E4B-98A6-F7AD40392E2D> /usr/lib/system/libsystem_secinit.dylib
    0x7fff949b3000 -     0x7fff949baffb  libsystem_symptoms.dylib (532.50.47) <3390E07C-C1CE-348F-ADBD-2C5440B45EAA> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff949bb000 -     0x7fff949ceff7  libsystem_trace.dylib (518.70.1) <AC63A7FE-50D9-3A30-96E6-F6B7FF16E465> /usr/lib/system/libsystem_trace.dylib
    0x7fff949cf000 -     0x7fff949d4ffb  libunwind.dylib (35.3) <3D50D8A8-C460-334D-A519-2DA841102C6B> /usr/lib/system/libunwind.dylib
    0x7fff949d5000 -     0x7fff949feff7  libxpc.dylib (972.70.1) <BF896DF0-D8E9-31A8-A4B3-01120BFEEE52> /usr/lib/system/libxpc.dylib

Model: MacBookPro14,1, BootROM MBP141.0160.B02, 2 processors, Intel Core i5, 2,3 GHz, 8 GB, SMC 2.43f6
Graphics: kHW_IntelIrisGraphics640Item, Intel Iris Plus Graphics 640, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
Memory Module: BANK 1/DIMM0, 4 GB, LPDDR3, 2133 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3039
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x170), Broadcom BCM43xx 1.0 (7.21.171.130.1a1)
Bluetooth: Version 5.0.5f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.0 Bus
Thunderbolt Bus: MacBook Pro, Apple Inc., 22.2

**Comment by Lois2901** [comment]
I'm not sure if it's the right thing to post.

**Comment by paradoxicalNL** [comment]
Missing dep. Did you follow all steps?

Download the pre-compiled software.
Double click the DMG
Drag the Verge-Qt to your Applications folder
Install required boost dependency via homebrew

xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew install boost
Double click the Verge-Qt application to open it.
Go grab a ☕️ while it syncs with the blockchain

**Comment by Lois2901** [comment]
Yeah it works! 
Thank you for your precious help. 
I didn't know about Homebrew

**Comment by paradoxicalNL** [comment]
Your welcome. This can be closed.
