### ISSUE TITLE
Cannot unlock wallet Cannot send Verge

### ISSUE THREAD

**Issue by Smiles4miles** [vergecurrency/VERGE#365]
I'm using the windows qt wallet. I have made 4 successful transactions, and each time the wallet wouldn't unlock but it would still send.
On my 5 transaction yesterday I could not get pass the password prompt to send verge. 
The correct password acted like it was accepted but then when I press send I was prompted again for the password, like a loop.
The wrong password gives me a failed password window.
Please help

**Comment by vorlonempire** [comment]
Try to change password

**Comment by Smiles4miles** [comment]
Thank you, I did that too. Its still won't accept it.

**Comment by Smiles4miles** [comment]
I know the password is correct because I wrote it down and have used is successfully 4 times. Also if I enter a incorrect password it responds differently.

**Comment by vorlonempire** [comment]
This is known bug and fixed in newer version. Soon to be released

**Comment by Smiles4miles** [comment]
Thank you. Will I have to download the new version and reinstall the blockchain?

**Comment by justinvforvendetta** [comment]
you wont have to reinstall the blockchain, just replace the .exe
