### ISSUE TITLE
Can't sync blockchain

### ISSUE THREAD

**Issue by Infernoman** [vergecurrency/VERGE#37]
Blockchain keeps getting stuck around block number 384,196

> ERROR: Connect() : WriteBlockIndex for pindex failed
> ERROR: Reorganize() : ConnectBlock 3621cc6c5007ae9f3918 failed
> InvalidChainFound: invalid block=3da4c68aea5311981d4d  height=403137  trust=403138  date=05/19/16 09:18:21
> InvalidChainFound:  current best=00000000097e642aeca0  height=384196  trust=384197  date=05/20/16 02:10:08
> ERROR: SetBestChain() : Reorganize failed
> ERROR: AcceptBlock() : AddToBlockIndex failed
> ERROR: ProcessBlock() : AcceptBlock FAILED
> received block c0fea816a92d9d8b8869
> Postponing 18941 reconnects
> REORGANIZE
> REORGANIZE: Disconnect 4196 blocks; 000000000116693fda5e..00000000097e642aeca0
> REORGANIZE: Connect 4197 blocks; 000000000116693fda5e..67e7c61cd083ffed4834

**Comment by vergecurrency** [comment]
and this is from 2.1, or 2.0? we updated wallets since the last one you helped on..

**Comment by Infernoman** [comment]
I'm on version 2.1 on the server it was recently updated.

**Comment by vergecurrency** [comment]
thats really strange. do a getpeerinfo, and then use whichever peers are at the correct starting height (~413488) in the .conf as connect=peeripaddress so that you can only sync from peers that are at the correct height.
