### ISSUE TITLE
Stealth send still not working.

### ISSUE THREAD

**Issue by zze** [vergecurrency/VERGE#370]
![foto_no_exif](https://user-images.githubusercontent.com/657191/34578052-8cf88960-f151-11e7-918f-d1ea79158406.jpg)

**Comment by justinvforvendetta** [comment]
what build is this from? is it https://github.com/vergecurrency/VERGE/commit/889fb26f70591817e1e62fe042f9b57f3d63f621 or newer?

**Comment by justinvforvendetta** [comment]
closing this, as i think this isnt compiled from latest source
