### ISSUE TITLE
Where the hell did my Verge coin go? 

### ISSUE THREAD

**Issue by jbutr8888** [vergecurrency/VERGE#372]
I put it in the Verge 3.0 Wraith Wallet and it damn disappeared. It's fully synced and I've written to Verge on Twitter, Reddit and everywhere else and cannot get help. This is bull.

**Comment by justinvforvendetta** [comment]
what address did you send it to? did you follow it on the block explorer before coming here? you need to provide far more details than you have so far, because without knowing what the set up is, what you did, etc, your comment is bull.

**Comment by justinvforvendetta** [comment]
is your wallet locked? is the address you sent the coins to, still showing in your receiving tab?

**Comment by jbutr8888** [comment]
why did you close this?

**Comment by jbutr8888** [comment]
I sent it to Verge 3.0 a couple of weeks ago and then I open it and it says 0. 

https://verge-blockchain.info/address/DSSqKQeqriRMra1WsLcU8iGQfnKK3rGcQf

**Comment by kreidler1234** [comment]
![img_20180105_120539_818](https://user-images.githubusercontent.com/34182606/34606731-d2a71854-f210-11e7-941a-ea320ef78413.jpg)
When you have your mnemonic you could try another wallet. When it synced it should show your coins. Try coinomi.
