### ISSUE TITLE
Beta testing stealth, testnet

### ISSUE THREAD

**Issue by Technophant** [vergecurrency/VERGE#373]
I would like to be able to test the new code, but unsure of how to access the testnet.  

"VERGE-qt -testnet" from command line should work, but how do I specify a different data directory?  Which branch is the most current or relevant for testing stealth?  What at the git commands to specify and pull a different branch?

**Comment by paradoxicalNL** [comment]
Interested as well, as i'm burning coins now, such a waste :)

**Comment by Technophant** [comment]
I figured out some, "VERGE-qt -testnet -datadir="/home/user/folder"  works, however it starts a new folder in the data directory so it may not be needed to use a different folder.  You start with no coins, so either somebody would need to send you some or you can solo mine.  Difficulties for mining are at the lowest levels.

**Comment by justinvforvendetta** [comment]
when y ou run --testnet, it makes a directory called testnet in your current data directory

**Comment by justinvforvendetta** [comment]
and y es solo mining will earn you lots of coins quickly

**Comment by Technophant** [comment]
That would great, "gen=1 algo=[suggestion?]" would work yes?  I'm not getting any connections though.  Can I get some test coins sent to oYyVhH99dwpEt4CjXpMZCvcpixrCrGJXeR please?

**Comment by justinvforvendetta** [comment]
we will open a verge testnet coin faucet soon, i think that would be best

**Comment by justinvforvendetta** [comment]
we tested stealth already, just a few more tests and we're good to go.

**Comment by Technophant** [comment]
Is there something that needs to be done to get a connection to the test net?  Using virtualbox and did not have an issue connecting with the main net.  Unsure if upnp is working.

**Comment by justinvforvendetta** [comment]
not sure if the testnet nodes are up, but ill throw some up myself shortly and put them into the codebase

**Comment by Technophant** [comment]
Thank you Justin.  I'll check back later.  Please keep us updated as to which version/branch you would like people to test and what to look for.  We're here to help but need some directions on where to go and what to do.

**Comment by ekryski** [comment]
@justinvforvendetta are they going to be fairly fixed or ephemeral? If fixed I'll toss them in the README and add a section about running on testnet and improve the solo mining instructions.

**Comment by justinvforvendetta** [comment]
ill open two that are fixed, and post their onion addresses after this release, no point in setting up clearnet ones right now

**Comment by jderwish** [comment]
@justinvforvendetta Folks none of my stealthtransactions are completed - I only see confirmation but the other wallet doesnt receive it, any thoughts?

**Comment by justinvforvendetta** [comment]
yeah, itll get processed once the pools update

**Comment by jderwish** [comment]
@justinvforvendetta how far behind the pool is ? It has been two days and recent ones few hours

**Comment by jderwish** [comment]
@justinvforvendetta  Error from debug.log

Latest commit

jderwish@instance-1:~/VERGE$ sudo git pull --commit
remote: Counting objects: 33, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 33 (delta 20), reused 29 (delta 19), pack-reused 0
Unpacking objects: 100% (33/33), done.
From https://github.com/vergecurrency/VERGE
   4664811..13d8f32  master     -> origin/master
   81cd517..0aa30fd  tor_integration -> origin/tor_integration
Updating 4664811..13d8f32


SendStealthMoney() : Error: Transaction creation failed  received block fc0ef05ff879d3c30e4c
SendStealthMoney() : Error: Transaction creation failed  CTxMemPool::accept() : accepted 9429341828 (p                    oolsz 6)
SendStealthMoney() : Error: Transaction creation failed  SendStealthMoney() : Error: Transaction creat                    ion failed  CTxMemPool::accept() : accepted e6c9829cd9 (poolsz 7)
SendStealthMoney() : Error: Transaction creation failed  CTxMemPool::accept() : accepted 8302fedf74 (p                    oolsz 12)
SendStealthMoney() : Error: Transaction creation failed  CTxMemPool::accept() : accepted 8d3d02123c (p                    oolsz 15)
CommitTransaction() : Error: Transaction not validCTxMemPool::accept() : accepted 65b7070b2d (poolsz 1                    0)
CommitTransaction() : Error: Transaction not validupdateWallet 2752beb48624315a25c8c63a00dfe73d5ce6642                    713b5a2e2a8e641d2c07e7c01 1

**Comment by paradoxicalNL** [comment]
Let me know if I can do/test something.
My last tests yesterday did not work with latest source from that time.

**Comment by jderwish** [comment]
@justinvforvendetta @paradoxicalNL latest commit version  13d8f32 , no error when sending to stealthaddress however this is what I noticed, no peers using console peerinfo running Wraith version 4, all of them running 2.0, it is possible that in order to complete this type of transaction we need peers who understand this nonstandard transaction ? probably need to run few more updated nodes? any thoughts

**Comment by paradoxicalNL** [comment]
Any update on this?

**Comment by Technophant** [comment]
Here's some help with getting latest versions. I'm new with this so may be a better way. 
So once you have git installed, 'git clone https://github.com/vergecurrency/VERGE.git'  'cd VERGE'
'git branch -a' checks which branches are availble
'git checkout tor-integration' to change to a new branch
'git pull'  to update
'make clean"  gets you ready to compile a new commit

**Comment by justinvforvendetta** [comment]
thats exactly it @jderwish the next release, when mining pools update, those will be processed.

**Comment by justinvforvendetta** [comment]
we're going to merge the other branch into master, and then ill work on getting all the pending pull requests approved/declined

**Comment by Technophant** [comment]
What's the new testnet addresses and the command to connect to them?  Why close?  Not able to use testnet.

**Comment by justinvforvendetta** [comment]
because we're setting up the testnet on the new codebase, thats not in this branch yet ;]
