### ISSUE TITLE
Test Software Procedure

### ISSUE THREAD

**Issue by jcodemad** [vergecurrency/VERGE#376]
Hello, 
I would like to help test the software, where can I find a latest Build to download?
Is it Possible to publish with some regularity beta version for test?
Is there a function test Plan to Follow? Can it be provided? 

PS: On the released software, someone should post some comments saying that is very outdate relative to the last improves and eventually classified it as beta release.

João

**Comment by jderwish** [comment]
Please see readme file in code section

**Comment by jcodemad** [comment]
Thanks jderwisj , and !!! , where can we get today build or yesterday build?  or some build that is not from  4 days ago and  110 commits to master since this release.

Can't find also any  Function test Plan to Follow, 

Thanks 
João

**Comment by jderwish** [comment]
@jcodemad https://github.com/vergecurrency/VERGE/blob/master/doc/build-verge-linux.md

Once code is merged with master - you can git pull --commit in VERGE folder, rerun the sudo sh go.sh command

**Comment by justinvforvendetta** [comment]
we prefer beta testers who can pull from the repository, but thanks @jcodemad

**Comment by paradoxicalNL** [comment]
Just post once merged, and I'll test all functionality!
Exciting!

2018-01-07 1:19 GMT+01:00 sunerok <notifications@github.com>:
