### ISSUE TITLE
latest macOS VERGE-Qt.app crashes

### ISSUE THREAD

**Issue by salomoko** [vergecurrency/VERGE#378]
**Exception report...**

`
Process:               VERGE-Qt [2179]
Path:                  /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
Identifier:            com.vergecurrency.VERGE-Qt
Version:               2.1.0 (2.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VERGE-Qt [2179]
User ID:               501

Date/Time:             2018-01-04 17:14:14.243 -0700
OS Version:            Mac OS X 10.12.6 (16G1036)
Report Version:        12
Anonymous UUID:        5F8F9EA0-BA37-FD14-9084-69426B2854E3

Sleep/Wake UUID:       C5059124-CCEF-4378-8714-1844E9AA7DE2

Time Awake Since Boot: 15000 seconds
Time Since Wake:       12000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries
`

**Comment by justinvforvendetta** [comment]
this is not the latest and greatest, just wait, itll be shortly

**Comment by salomoko** [comment]
why you close this then?

**Comment by justinvforvendetta** [comment]
because its not an issue anymore, it was fixed, and there are already multiple closed issues that you could have checked that describe the issue and the solution.
