### ISSUE TITLE
Verge as a G2A Payment method.

### ISSUE THREAD

**Issue by AccidentalGeniuss** [vergecurrency/VERGE#379]
Hello there.

I got in contact with G2A today and told them about Verge and what it does (doing this for some other sites aswell). In a really simple form. I feel like Verge could be big on there and make bitcoin expendable. As Verge almost has instant transactions and really low fees. 

It would be great publicity since they have a great amount of customers which would all see the Verge logo on check-out at the payment methods section. It would also make the coin more mainstream and give it more purpose.

-AccidentalGenius

Attachments: Conversation with G2A. A simple promotion picture.
I censored the E-mail in the picture as I don't want to spread their E-mail across the web. If you want it please DM me on Twitter (https://twitter.com/Satoshi_nkmoto) or Discord(AccidentalGenius#8863). 
![capture](https://user-images.githubusercontent.com/35119624/34590372-97ef6054-f1b6-11e7-87e8-d27fab090cde.PNG)
![verge](https://user-images.githubusercontent.com/35119624/34590387-aaee834c-f1b6-11e7-8848-d28e9c22f53b.jpg)

**Comment by justinvforvendetta** [comment]
while thats awesome, this isnt an issue with the source code
