### ISSUE TITLE
Ubuntu 14.04 compile issue.

### ISSUE THREAD

**Issue by merlon74** [vergecurrency/VERGE#38]
problem as below:

  CXX      qt/qt_libbitcoinqt_a-radio.o
In file included from qt/radio.cpp:1:0:
./qt/forms/ui_radio.h:19:29: fatal error: QtWebKit/QWebView: No such file or directory
 #include <QtWebKit/QWebView>
                             ^
compilation terminated.
make[1]: *** [qt/qt_libbitcoinqt_a-radio.o] Error 1

**Comment by vergecurrency** [comment]
@merlon74 did you apt-get install libqt5webkit5-dev as per the listed dependencies?

**Comment by merlon74** [comment]
yes, I did the following: 

sudo apt-get install libdb4.8-dev libdb4.8++-dev build-essential libtool
autotools-dev automake pkg-config libssl-dev libevent-dev bsdmainutils
git libboost-all-dev libminiupnpc-dev libqt5gui5 libqt5core5a
libqt5webkit5-dev libqt5dbus5 qttools5-dev qttools5-dev-tools
libprotobuf-dev protobuf-compiler libqrencode-dev

All installed without issues. 

On 2016-05-23 13:29, vergecurrency wrote:

> @merlon74 [1] did you apt-get install libqt5webkit5-dev as per the listed dependencies? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub [2]
 

Links:
------
[1] https://github.com/merlon74
[2]
https://github.com/vergecurrency/VERGE/issues/38#issuecomment-221038717

**Comment by vergecurrency** [comment]
@merlon74 ?

**Comment by merlon74** [comment]
qmake version is  4.8.6.

How do I change the default to qt5.
Thanks.

**Comment by vergecurrency** [comment]
@merlon74 ah you're alive! try sudo apt-get install qt5-default

and of course, if you have any more trouble, just drop another comment here =]

**Comment by merlon74** [comment]
Thanks for reply, I work nights so my responses get delayed. That didn't
work, but what did work was me editing the
"/usr/lib/i386-linux-gnu/qt-default/qtchooser/default.conf". 

I initially installed and compiled the QT5.5.1 to my home directory and
modified the default.conf above to direct it to the Qt5.5.1
directory(see below). 

[directory_path]/Qt5.5.1/5.5/gcc/bin"
[directory_path]//Qt5.5.1/5.5/gcc"

so after executing the command qtchooser -print-env, I saw the
following: 

QT_SELECT="default"
QTTOOLDIR="/home/anothername/Qt5.5.1/5.5/gcc/bin"
QTLIBDIR="/home/anothername/Qt5.5.1/5.5/gcc" 

From there I went back to my "vergecoin-wallet" directory. 

issued : ./autogen.sh 

issued: ./compile --with-incompatible-bdb --with-gui=qt5
--enable-hardening 

issued: make 

From there everything worked out fine. So if anyone has an issue with
compiling, the above worked for me. 

Thanks for the response. 

On 2016-05-28 14:02, vergecurrency wrote:

> @merlon74 [1] ah you're alive! try sudo apt-get install qt5-default 
> 
> and of course, if you have any more trouble, just drop another comment here =] 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/merlon74
[2]
https://github.com/vergecurrency/VERGE/issues/38#issuecomment-222321458
[3]
https://github.com/notifications/unsubscribe/ASob4OEP-g9SWWedNnUJJ5bXV9ahU8RCks5qGINHgaJpZM4Ikr2V

**Comment by vergecurrency** [comment]
@merlon74 great, glad everything is working now
