### ISSUE TITLE
Display issues and QR Code not working - Mac - v2.1.0.0-75fa380-beta

### ISSUE THREAD

**Issue by revtex** [vergecurrency/VERGE#381]
<img width="1011" alt="verge_-_wallet" src="https://user-images.githubusercontent.com/470146/34592128-ec36a7fc-f18f-11e7-94ca-99ce34c954e8.png">
Above are display issues I found in the block explorer tab

Another display issue I found was adjusting column width in the wallet tab and address book tab does not work.

And last Show QR Code when right clicking on wallet address does not work

**Comment by Positivism** [comment]
Confirmed this, same issue. (High Sierra)

**Comment by Positivism** [comment]
Duly note, interface problems with dropdowns persist as well.

**Comment by Positivism** [comment]
<img width="541" alt="screen shot 2018-01-04 at 11 20 44 pm" src="https://user-images.githubusercontent.com/35063339/34595437-fa5b99da-f1a5-11e7-94d4-9274f4232d02.png">

**Comment by techpoy** [comment]
are these on latest build?

**Comment by revtex** [comment]
Yes, Just pulled lastest and still an issue

**Comment by justinvforvendetta** [comment]
qr codes wont show if you dont have libqrencode-dev installed, just an fyi

**Comment by marpme** [comment]
@justinvforvendetta note in wiki or so?

**Comment by revtex** [comment]
@justinvforvendetta That worked. I installed qrencode via brew but it wasnt being found by the compiler.  I installed it via port and it worked. Same thing happened with Protobuf

**Comment by justinvforvendetta** [comment]
ok so maybe make a pr for the osx build notes, thanks for reporting this, glad we got it resolved

ps: maybe try brew install libqrencode-dev --universal? just a guess

**Comment by justinvforvendetta** [comment]
feel free to continue commenting here btw, if a better solution arises or something

**Comment by revtex** [comment]
@justinvforvendetta Sorry for the miss understanding.  The only issue it fixed was QR Code.  UI display issues noted above are still an issue.

**Comment by justinvforvendetta** [comment]
oh ok lets make a seperate issue for that, or see if there already is one, there might be. i know theres a few duplicates right now, would be nice to reduce it a bit

**Comment by revtex** [comment]
Moved over to #246

**Comment by Positivism** [comment]
@justinvforvendetta the dropdown issue is still existing in the latest commit. 
<img width="688" alt="screen shot 2018-01-09 at 1 24 50 am" src="https://user-images.githubusercontent.com/35063339/34707509-ef1065b8-f4db-11e7-8def-fb36fd9cbd75.png">
