### ISSUE TITLE
Reinstalled Verge qt now coins are gone?

### ISSUE THREAD

**Issue by Smiles4miles** [vergecurrency/VERGE#383]
I had an issue unlocking my wallet yesterday and tried to reinstall the wallet. Now my coins are gone. How do i get them back? Can I get them back? I know everyone is working hard here, but this has been I nightmare, I want to believe in verge but this has cost me so much in missed profits and time.

**Comment by Smiles4miles** [comment]
I am not a coder at all. So please make it easy to understand.

**Comment by Noworize** [comment]
When you reinstalled the wallet did you modify the wallet.dat file? What
operating system are you using? (Linux, Mac OSX, Windows)

**Comment by Smiles4miles** [comment]
I am using Windows. I still have my original wallet.dat file that I saved, but I don't know what (modify the wallet.dat file) even means?

**Comment by Smiles4miles** [comment]
I may have correctly modified the wallet.dat (I removed the new one and replaced it with my saved one) but my password still doesn't work and my coins are gone. Did I lose them? If so I am over this and done with verge.

**Comment by alexkenley** [comment]
Dude this is not for verge support, it's for the development team to build and test. If you find the current releases to difficult to install and use then i suggest waiting until a more mature product and documentation has been released. In relation to your missing coins, you still need to wait for the wallet to sync with the verge blockchain as I did already tell you on twitter. Leave it to sync for a couple of days, as long as you have used the backed up wallet file from where you had your coins then they will be visible again when synced.

**Comment by juultje123** [comment]
Referring to @alexkenley it looks that your last transactions are not synced, so it looks like the wallet is empty, but it is not. If it is your password, something else is wrong. You can join the verge channel, I see these kinds of questions a lot there: https://t.me/VERGExvg

**Comment by Smiles4miles** [comment]
My wallet is synced. I was able to download the blockchain and do the fast sync. Still no luck.
As per alexkenley, it appears that Wraith is just to complicated for me and I'm fucked.

**Comment by juultje123** [comment]
Come to the telegram channel, we (community) can help. Github is for coding. And I think this is not related to that.

**Comment by Smiles4miles** [comment]
Okay thank you for your time, I will bring my smile.
