### ISSUE TITLE
Drop Downs

### ISSUE THREAD

**Issue by mnott** [vergecurrency/VERGE#387]
Hi Team,

v4.0.1.0-13d8f32-beta just built fine, I'm very happy with the consistency and reliability.

One question: Is there a plan to fix those dropdown boxes in the preferences window?

Thanks!

**Comment by marpme** [comment]
Already reported in issue #381, feel free to close your issue if there's nothing else to report.
And keep it related to development topics, thank you.

Regard Kyon.
