### ISSUE TITLE
Implement Seeds or Keys for wallet??

### ISSUE THREAD

**Issue by d3v3agl3** [vergecurrency/VERGE#388]
I'm just curious if there is or will be an option to set a seed or key to restore wallet vs encrypting a back up .dat and storing it somewhere, i ask this as i have a Mifare ultrlight NFC chip in my hand that iv'e adopted to storing an encrypted list of my private keys etc on this, knowing that i can never misplace or lose it.. Cheers

**Comment by marpme** [comment]
At the moment there's no option (at least no visual implementation of it). 
Well, but I still agree with you, that we could add such an option for further security.

**Comment by justinvforvendetta** [comment]
that would be great, if someone wants to start working on that

**Comment by besnikl** [comment]
Hi there,

I am willing to join your team that will work on this additional module. Let me know when you form a team so I can join them. 

Cheers!

**Comment by marpme** [comment]
@besnikl Just **fork** this repo and work on your forked one and as you finished with it, 
you can request a pull request to the original repository.

**Comment by besnikl** [comment]
Ok @marpme ! Will do so ...

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
