### ISSUE TITLE
Windows Wallet - Passphrase Error 

### ISSUE THREAD

**Issue by MilNoslen** [vergecurrency/VERGE#389]
When I enter my passphrase to unlock my wallet, I get "The passphrase entered for the wallet decryption was incorrect." BUT it unlocks the wallet still. So either I entered my passphrase right and the error is wrong. Or I entered the wrong passphrase and it still unlocks the wallet. Please check into this security.
![xvg](https://user-images.githubusercontent.com/35152528/34630804-a40aab70-f23b-11e7-9e3a-0140a0d3cdef.jpg)

**Comment by marpme** [comment]
Hey @MilNoslen,

first thank you for report that to us, but unforunetely it has been reported already under #189.
Please feel free to close your issue, if you don't have any other issue. 

Workaround: `Enter passphrase correctly and press okay and cancle afterwards.`

**Comment by MilNoslen** [comment]
Thank you!
