### ISSUE TITLE
Question: Why do binary names contain uppercase letters?

### ISSUE THREAD

**Issue by ShapeShifter499** [vergecurrency/VERGE#39]
Uppercase named binaries on Linux seem wrong, why do verge binaries contain uppercase letters?

**Comment by buzztiaan** [comment]
seem? wtf

**Comment by buzztiaan** [comment]
there isnt any issue with any case letters in any filename, do you have a actual problem or just a preference ? you can easily mod the code to poop out lowercase letters if you prefer, or just , dno , rename them?

**Comment by ShapeShifter499** [comment]
I'm trying to package this for Arch Linux. I'm just wondering why the decision for uppercase letters was made.  I'll make the package with uppercase letters if that's what the verge community decided on.

**Comment by buzztiaan** [comment]
imho, make the package lowercase, install uppercase binaries, so it at least follows the norm
that way, when git changes caps in future, the AUR would aswell?

**Comment by ShapeShifter499** [comment]
It should be fine either way, I'll just submit lowercase package name and edit the package as things change. Thanks @buzztiaan

**Comment by vergecurrency** [comment]
thanks @ShapeShifter499 and @buzztiaan i just woke up, i checked it out and its perfect
