### ISSUE TITLE
windows qt wallet error

### ISSUE THREAD

**Issue by stealthsolider9** [vergecurrency/VERGE#390]
![image](https://user-images.githubusercontent.com/34946332/34636837-cfd281b2-f266-11e7-8a25-f5fbc08ca978.png)

The wallet works fine when it is initially installed and run, but this error occurs after adding the downloaded block chain to the appdata/VERGE folder. It also occurs if the the block chain is downloaded through the wallet.

**Comment by vorlonempire** [comment]
This code would hint a possible error
https://github.com/vergecurrency/VERGE/blob/master/src/leveldb/db/dbformat.h

**Comment by justinvforvendetta** [comment]
is this from the latest code compiled?

**Comment by stealthsolider9** [comment]
I downloaded the .zip from Wraith Release 2.

**Comment by justinvforvendetta** [comment]
hmm, we can keep this open til we are sure its not in the next release.

**Comment by theterribletoo** [comment]
I had this issue also and fixed it by extracting the files and installing the wallet and blockchain properly. However there is a guy i talked to that has windows 10 but runs alternative programs on his computer. he had this issue as well but it seems his .dat files and log files couldn't run on his computer. It wasn't reading them. It seems to be an issue with individual computers and non related to the software. IMO

**Comment by stealthsolider9** [comment]
The issue seems to be related to my computer and extracting the downloaded blockchain. I got the wallet installed and synced up on a different machine, then copied the appdata/VERGE folder over to the computer that was having the issue. It works just fine now.
