### ISSUE TITLE
Mining with the new 4.0 Wallet

### ISSUE THREAD

**Issue by RualdOrdelman** [vergecurrency/VERGE#391]
Can someone tell me how to mine with the new 4.0 Wraith wallet?

I've created a conf file with the following content:
rpcuser=vergerpcusername
rpcpassword=PASSWORD
rpcport=20102
port=21102
algo=x17

The binary is running well and is using about 100% cpu load, but there is no GUI. So how does the mining proces know where to get the blocks and where to store the mined XVG? My local Wallet is encrypted and because there is no GUI, it can't be unlocked.

**Comment by vorlonempire** [comment]
https://www.reddit.com/r/vergecurrency/comments/7l0paf/idiot_ahead_solo_mining_help/drmg7jx/

Read this, maybe answer your question. 
Check this channel for more mining related issues
https://discordapp.com/channels/325024453065179137/328289816997527553
Since its not code related, you can close the issue as soon as you read this.
Good luck

**Comment by RualdOrdelman** [comment]
Thanks @vorlonempire that's working for me. 

I've created a local VERGE.conf with the following content:
rpcuser=vergerpcusername
rpcpassword=PASSWORD
rpcallowip=127.0.0.1
rpcport=20102
port=21102
server=1
daemon=1
algo=scrypt
gen=1

After that I started the Verge app and with that the mining pool and I've download macMiner run that with the setting from the conf file. Mining URL http://127.0.0.1 Protocoll SCRYPT and the chosen username/password.

Now I'm wondering where the mined coins will go to. :) I've never set a wallet adres or something. Not at the Verge.conf and not at the macMiner settings.

**Comment by justinvforvendetta** [comment]
you can use a gui if you want. also you just mine to the rpcport.

**Comment by RualdOrdelman** [comment]
@justinvforvendetta 
I'm using the local Verge Wallet to connect to with RPC user/pass/port. So the mined stuff should come into the local Verge wallet?

**Comment by vorlonempire** [comment]
Yes

**Comment by RualdOrdelman** [comment]
oke, wondering how long it takes when 1 xvg coin comes into the local Verge wallet.

**Comment by Himan2001** [comment]
depends on actual difficulty, mining with cou you can expect between 2 days - 6 months and more.

**Comment by Technophant** [comment]
How can a profitability calculator be built?   What is the equation to take a look at difficulty vs the different hash rates a gpu puts out to see which one is best for the moment similar to whattomine.com?

**Comment by justinvforvendetta** [comment]
@RualdOrdelman well it wont be 1 xvg that comes in. it will be 1560 coins, if you find a block. do you have alot of hashpower to solo mine?

**Comment by paradoxicalNL** [comment]
An AntMiner S9 will get really nice results on XVG nice, especially after the software release ;-)

CPU mining, that's over, CPU and even GPU mining days are behind us?

**Comment by metanamelukas** [comment]
Hi, hope you are well, how to mine XVG with 127.0.0.1?
I've created a local VERGE.conf with the following content:
rpcuser=vergerpcusername
rpcpassword=PASSWORD
rpcallowip=127.0.0.1
rpcport=20102
port=21102
server=1
daemon=1
algo=scrypt
gen=1
ccminer bat file: ccminer-x64 -a x17 -o stratum+tcp://127.0.0.1:20102 -u vergerpcusername -p PASSWORD -i22 c=xvg

on my ccminer cmd screen says:
Stratum connection failed: failed to connect to 127.0.0.1 port 20102: Connection refused
appreciate ya and the project 
kind regards
L.

**Comment by justinvforvendetta** [comment]
thats because you arent mining to a stratum. replace that line with this:

ccminer bat file: ccminer-x64 -a x17 -o http://127.0.0.1:20102 -u vergerpcusername -p PASSWORD -i22

**Comment by justinvforvendetta** [comment]
closing, as this isnt an issue related to verge, its a question about mining.
