### ISSUE TITLE
Issue recovering account

### ISSUE THREAD

**Issue by DynamicPimp** [vergecurrency/VERGE#395]
Im testing android wallet
 after sending funds to new wallet address I take note of the recovery phrase. I then try to restore wallet. Once it opens my funds are gone... I replicated this issue on my phone after a friend came to my house after losing a substantial amount more....
  Sorry if this is a known bug

**Comment by justinvforvendetta** [comment]
you need to check the box under where you are entering your seedphrase to restore. not a bug. just check the box when you enter the key.
