### ISSUE TITLE
after first stealth tx, sending non-stealth not working anymore

### ISSUE THREAD

**Issue by swat69** [vergecurrency/VERGE#396]
Ubuntu 17, commit https://github.com/vergecurrency/VERGE/commit/8a50617d2a0a15f2ced3f071d6ffdc148d8a0fa8

![screenshot from 2018-01-07 09-34-24](https://user-images.githubusercontent.com/28594828/34648107-51b35fec-f38b-11e7-8980-80994079eed5.png)

synced and connected, picture taken after 15 minutes:
0 - 09:14 inbound
1 - 09:15 non stealth OK
2 - 09:15 stealth
3 - 09:16 non stealth not ok, tx id not in blockchain

restart and rescan, sending non-stealth still not working

[debug.log](https://github.com/vergecurrency/VERGE/files/1609606/debug.log)

**Comment by justinvforvendetta** [comment]
any update on this @swat69 

stealth wont go thru because the pools arent running this version yet
