### ISSUE TITLE
QT 4.0 wallet Unlock error message

### ISSUE THREAD

**Issue by crashbdx** [vergecurrency/VERGE#398]
When i unlock the wallet, after entering my passphrase and clicking ok, it say that the passphrase was wrong, but still unlocked the wallet.
![xvg1](https://user-images.githubusercontent.com/517452/34653113-983468d8-f3e7-11e7-8400-f5c65b96609f.jpg)
![xvg2](https://user-images.githubusercontent.com/517452/34653114-985bbc1c-f3e7-11e7-866b-61267622b4cb.jpg)

**Comment by michpiatek** [comment]
That's already fixed and will be included in next release.
