### ISSUE TITLE
QA: Stealth Address, getAmounts return false transaction type, GUI issues

### ISSUE THREAD

**Issue by Glibo** [vergecurrency/VERGE#399]
Hey guys,

I did tests on master branch for stealth address and here is a small report.

Debug log:
 [debug 2.log](https://github.com/vergecurrency/VERGE/files/1610108/debug.2.log)

Notes:
[Testing Master.docx](https://github.com/vergecurrency/VERGE/files/1610109/Testing.Master.docx)

**Comment by justinvforvendetta** [comment]
what do you mean, return false transaction type? and what gui issues?

**Comment by justinvforvendetta** [comment]
oh, this is from the downloadable binary, not the most current code. closing.

**Comment by Glibo** [comment]
@justinvforvendetta can you please point me to the most current code and what that means ( i.e. commit, branch etc...) so I can test? I cloned master branch on this commit ( which is last on 7th Jan):

commit 8a50617d2a0a15f2ced3f071d6ffdc148d8a0fa8 (HEAD -> master, origin/master, origin/HEAD)
Merge: f856bd6 df338f0
Author: sunerok <justinvforvendetta@users.noreply.github.com>
Date:   Sat Jan 6 22:49:09 2018 -0500

    Merge pull request #393 from michpiatek/stealth_tx_filter
    
    hide additional part of stealth tx with 0 amount and no addr


GUI issue: transactions with stealth addresses are not shown in history.

P.S. I see new commits today, is that what you mean?
