### ISSUE TITLE
High CPU load on Windows

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#400]
![High CPU load](https://i.imgur.com/YyZIujN.png)

## Heavy CPU load on long run

Hey dear community,

I just wanted to report that after using the wallet for some days, I found that after some time the CPU load rushed into the 90% mark at any time, although I ain't doing anything. Maybe some background progress is running way too often. I can't see any obvious reason tho. I will append the [client log](https://github.com/vergecurrency/VERGE/files/1610134/debug-public.zip)!

Specs:

* Processor: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 CPUs), ~4.0GHz
* Memory: 20480MB RAM
* System Model: Z97-HD3
* Operating System: Windows 10 Pro 64-bit (10.0, Build 16299) (16299.rs3_release.170928-1534)
* Graphic Card name: NVIDIA GeForce GTX 970

---

Regards, Kyon

**Comment by metanamelukas** [comment]
Nah I got like 0.4% CPU on VERGE oss GUI.
where did you get 86%?

**Comment by mike2lab** [comment]
i had the same issue my CPU load was at 80-90% at any time without doint nothing but it was synchronising with the Network. 
these are my specs: 
![os](https://user-images.githubusercontent.com/34998751/34653586-a63471bc-f3f6-11e7-8f59-15103102cf27.png)

**Comment by metanamelukas** [comment]
I'm  got like 0.3% CPU for like 2h now, never had that issue

**Comment by metanamelukas** [comment]
I got like 0.3% CPU for like 2h now, never had that issue.

**Comment by justinvforvendetta** [comment]
keep us updated with the new release coming soon. I'll leave this open.

**Comment by simonerom** [comment]
Are there links to Windows latest builts to test it?


Il 07/01/2018 21:42, sunerok ha scritto:

**Comment by unv-annihilator** [comment]
If you go into the debug console and type `getgenerate` and it returns `true` then it means the wallet is configured to attempt to mine Verge (XVG) into your wallet. 

You can turn it off via the Debug Console with the command `setgenerate false`, but it will only stay in effect until the wallet is closed and reopened. To default it to off on load you can change the VERGE.conf line from `gen=1` to `gen=0`.

**Comment by marpme** [comment]
@justinvforvendetta This post above solved my problem, since I created the config for mining coins via RPC, but forgot to remove the `gen=1` parameter.
