### ISSUE TITLE
have wallet 3.0 for mac desktop and want to transfer to 4.0 wallet

### ISSUE THREAD

**Issue by piphoto23** [vergecurrency/VERGE#408]
I have the 3.0 wallet installed and working, Do I need to send the coins from 3.0 wallet to 4.0 wallet? will the 4.0 have a different address than my 3.0 wallet?

**Comment by alexkenley** [comment]
Backup your wallet.dat file from the 3.0. > Install 4.0 wallet. > replace the newly created wallet.dat in the 4.0 directory with the backed up one from 3.0. Do not ever lose your original wallet.dat file.

**Comment by justinvforvendetta** [comment]
yeah just keep a copy of your wallet.dat and youll be fine.
