### ISSUE TITLE
electrum wallet vulnerability

### ISSUE THREAD

**Issue by sasasavic82** [vergecurrency/VERGE#409]
team, apologies if it's a double-up ... have we picked up on this and addressed it?

https://bitcointalk.org/index.php?topic=2702103.0

**Comment by Tommixoft** [comment]
No, cause this is "private and secure" coin and they think critical bugs is cool. I saw someone made fix, but verge as always release update Dec 31

**Comment by Tommixoft** [comment]
@justinvforvendetta you are IDIOT! Damn you biggest noob ever.

**Comment by sasasavic82** [comment]
Excellent work @justinvforvendetta 

@Tommixoft - who the fuck still codes in C# and PHP? Bit of an old-timer ey? A little outdated - your portfolio is looking a little malnutritioned :)

**Comment by Tommixoft** [comment]
@sasasavic82  yeah yeah keep talking and licking balls. C# is present and future. PHP is most used web language so learn something before writing stupid nonsense. In my github there is public repos not mine, so you double failed. Noobie.
"Excellent work @justinvforvendetta" ? really? you call this failure excellent work? :D You nob just like he is.

**Comment by justinvforvendetta** [comment]
this was already patched in the electrum repo.
