### ISSUE TITLE
Desync Twitter to GitHub

### ISSUE THREAD

**Issue by JeramyNS** [vergecurrency/VERGE#410]
Hey guys,

Someone must have setup some sort of sync between twitter and GitHub.
Occasionally it just spams the twitter feed and it can be really annoying when your phone starts going nuts because a new branch is pushed or something.

I assumed you guys fixed it after the last two times it occurred but I figure since it keeps happening I should open some sort of issue to make sure you are aware of the issue.

See screenshot:
https://photos.app.goo.gl/5vty9DNLJRC1KzEz1

**Comment by JeramyNS** [comment]
Just saw you deleted the other ones and made a tweet regarding it.
my bad:
https://twitter.com/vergecurrency/status/950508830634446849

**Comment by justinvforvendetta** [comment]
yeah, we leave important commits on our twitter, since they are just as important as any other post (possibly more important)
