### ISSUE TITLE
MSG_NOSIGNAL High Sierra

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#416]
configure: error: libevent not found
'libqsqlmysql.dylib': No such file or directory

**Comment by Positivism** [comment]
brew install libevent was an easy fix, recompiling, will update what happens

**Comment by Positivism** [comment]
net.cpp:848:84: error: use of undeclared identifier 'MSG_NOSIGNAL'
  ...int nBytes = send(pnode->hSocket, &vSend[0], vSend.size(), MSG_NOSIGNAL ...
                                                                ^
1 warning and 1 error generated.
make[1]: *** [libbitcoin_server_a-net.o] Error 1
make: *** [all-recursive] Error 1

**Comment by justinvforvendetta** [comment]
https://github.com/vergecurrency/VERGE/pull/412

a few people have been testing this, if you want to take a peek at the pull request, and we'll keep this issue open until its resolved.

**Comment by Positivism** [comment]
Issue fixed, awesome job mich.
