### ISSUE TITLE
Failure to send Verge to Stealth Address on Windows v4.0.1

### ISSUE THREAD

**Issue by unv-annihilator** [vergecurrency/VERGE#417]
## Context

After latest update, attempted to test the stealth addresses. Created a test stealth account and attempted to send it verge. No transaction seemed to be made, there is no transaction added to the history, but the fee for the transaction is looks to have been taken (may have been 'found' later according to the logs).

## Prerequisites

* [x] Are you running the latest version? Windows v4.0.1

## User Story:

* "I'm submitting a ... "
  - [x] bug report

## Expected Behavior

I expect to receive a transaction ID or be able to see the transaction in my wallet transaction history and for the transaction to complete successfully. If it fails the fee should not be taken (if it was charged).

## Current Behavior

When sending to a stealth address it prompts for a fee but after confirming there is no confirmation message, and there is nothing new in the wallet transaction history. Additionally, it seems to create a NEW address for the wallet with a label of the stealth address (with no way to remove or delete those wallets).

## Screenshots

![capture](https://user-images.githubusercontent.com/665570/34704470-e544c67c-f4be-11e7-9c75-f4ff044e9b6c.png)

## Possible Solution

Haven't found anything yet. Will be 

## Steps to Reproduce (for bugs)

* Steps :
1. Create new stealth address.
2. Copy new address.
3. Navigate to the send tab and paste the stealth address copied in the previous step.
4. Put in an amount to send, and click send.
5. Confirm, put in passphrase, and accept fees.
6. Check Wallet address history to find no new entries.

## Your Environment

* Verge Release: v4.0.1 (Windows)
* CPU: Intel i7-3930k
* GPU: GTX 1080
* RAM: 32GB 
* OS:
    - [x] I'm using Windows

## Any extra information that might be useful in the debugging process.

Can provide a debug log upon request, but looking through it I didn't see any mention of errors or failed transactions. 

Also, the Issue template for github doesn't have Windows under '* OS:', it has Mac repeated twice.

**Comment by justinvforvendetta** [comment]
wait, you sent yourself a stealth tx? lol  well of course the fee is gone, and the transaction will make its way to you. and the new public keys are the stealth keys that were created from the 102 character stealth address. nothing is wrong here.

**Comment by unv-annihilator** [comment]
Confirmed sending and receiving worked across different people, apologies for the confusion on my part.
