### ISSUE TITLE
TODO: compatibility with boost 1.66+

### ISSUE THREAD

**Issue by justinvforvendetta** [vergecurrency/VERGE#418]
build will break on distro's with boost 1.66 (was released 3 weeks ago)

https://pastebin.com/1Z60gT25

**Comment by ebrinkster** [comment]
Would it be possible to include instructions on how to install a supported version via homebrew for the macOS users?  I see that you can install version 1.60 via `brew install boost@1.60` but I'm not overly familiar with the necessary symlinks to get the VERGE client to work after this.  If you install via `brew install boost` it will install 1.66.0 (info via `brew info boost` or `brew info boost@1.60`).  Even if 1.60 is installed it will not run as it appears to be needed to be symlinked.

**Comment by ktomov** [comment]
Any work towards this issue? I'm using Antergos, which as Manjaro are both in top 5 of distrowatch and are based upon Arch Linux. Probably you already know but those are rolling release and we have almost everything up to date, boost too. Sadly can't compile the wallet, cause of the boost 1.66.

Don't want to rush things as you already have enough things on your heads, but any update will be highly appreciated.

**Comment by NexAdn** [comment]
Workaround for Arch Linux: There is an AUR package `boost-65-compat` which installs boost 65 parallel to boost 66.

**Comment by justinvforvendetta** [comment]
@ktomov @NexAdn  updated this just now to work with boost 1.66, please let me know if theres any other issues, and if so, pastebin them here =]
