### ISSUE TITLE
Time out waiting for union hostname

### ISSUE THREAD

**Issue by yona5324** [vergecurrency/VERGE#419]
# Issue Template

## Context

![verge 4](https://user-images.githubusercontent.com/33532098/34706382-9c4ecf64-f507-11e7-8644-135cd0250796.JPG)

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by yona5324** [comment]
Im trying to get this wallet to work is does not work for me on windows 10 64 bit.

**Comment by justinvforvendetta** [comment]
do you already have tor running somewhere else?

**Comment by yona5324** [comment]
No, I do not have tor running somewhere else my first encounter with tor on this laptop is with Verge.

**Comment by fradelo** [comment]
This appeared also the first time i run the app on Win 10 64bit. I closed and open again and everything ok.
I noticed that after a while the progress bar indicating the blockchain sync disappears but but blockchain continues the sync operation (checked the folder and file size is increasing). 
So this is something related with the UI and not with the core.

**Comment by fradelo** [comment]
@justinvforvendetta if you need my log files let me know

**Comment by yona5324** [comment]
On the 4.0 version two days ago I tried to back up my wallet after the backup I tried to decrypt by entering my password, but it gave an error that the password was incorrect. I hope this is fixed after this update?

**Comment by yona5324** [comment]
Oke, I deleted the old files with the 4.0 version and closed the verge running UI. It worked, but there are still some minor issues. You can enter your wallet password but you can not encrypt the wallet. It seems that I can not click that option. 
![verge 5](https://user-images.githubusercontent.com/33532098/34706947-ceb33550-f50a-11e7-97fe-3f893d155570.png)

**Comment by justinvforvendetta** [comment]
I'm pretty sure that floating button is for exporting.
