### ISSUE TITLE
How to use the wraith protocol

### ISSUE THREAD

**Issue by themasquedpear** [vergecurrency/VERGE#421]
# Issue Template

## Context

I trying to use the wraith protocol of the latest windows QT version you released today.

## Prerequisites

* [ x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "

  - [ x] support request 

Hello,

Can you tell me how to use the wraith protocol exactly?
I've created a stealth address, but how to add fund on it?
I tried to withdraw some xvg for test from Yobit but yobit said that address is not right.
and of curse how to send fund stealthy from my wallet.
Thank you.
PS/ I use the lasted version.

**Comment by themasquedpear** [comment]
Same issue on binance, withdraw address incorect with stealth address

**Comment by hethie** [comment]
>I've created a stealth address, but how to add fund on it?
>and of curse how to send fund stealthy from my wallet.
Someone plz explain how this should work. As I understood, it is not how it operates. If you send coin, you allways visible, but receiver chooses if he get funds on stealth or not, right?

**Comment by justinvforvendetta** [comment]
exchanges would have to support the stealth address.

**Comment by justinvforvendetta** [comment]
also stay away from yobit!

**Comment by themasquedpear** [comment]
You don't answered the question.
You don't provide support.
You don't you don't communicate correctly.
You don't provide a wiki or a tutorial.
You are not a professional.
I starting to understand why your coin don't  "go to the moon".

Best regards.

**Comment by paradoxicalNL** [comment]
It's really not that hard. Exchanges need to implement it.

Op 9 jan. 2018 9:06 a.m. schreef "themasquedpear" <notifications@github.com

**Comment by marioathiel** [comment]
“I starting to understand why your coin don't "go to the moon".“

No that’s right, we are not going to the moon. We are going to GN-z11<https://en.wikipedia.org/wiki/GN-z11> !!!

**Comment by themasquedpear** [comment]
> No that’s right, we are not going to the moon. We are going to GN-z11<https://en.wikipedia.org/wiki/GN-z11> !!!

Yes, that's why your spaceship seems to be a rust roller coaster... Good luck in space

**Comment by justinvforvendetta** [comment]
lol

**Comment by pcp1985** [comment]
lol

**Comment by themasquedpear** [comment]
@justinvforvendetta why you laught? you are the first actor in the dead of your coin. Your "lol" show us an incredible immaturity. try to show more respect to your investors rather laught of YOUR mistakes. you are one the most awfull coder/business man i've seen in my whole live. your deserve only one thing: a punch on your ugly face.

**Comment by flmuel** [comment]
@justinvforvendetta do you know if binance will upgrade to stealth?

**Comment by AdamDenoon** [comment]
@justinvforvendetta Is stealth addressing the Wraith Protocol, or are they two separate things?
