### ISSUE TITLE
How to import the wallet from electrum XVG wallet to Verge-4.0.1? 

### ISSUE THREAD

**Issue by gummideepak** [vergecurrency/VERGE#422]
It would be good to have a standard guide for these questions in the offical website.I searched the GUI trying to import my old wallet and did not found anything related to that!

**Comment by themasquedpear** [comment]
Why you don't simply install the wallet you whant, take your new address from your new wallet then send your XVG from the old wallet for a 0.1 xvg fee?

**Comment by gummideepak** [comment]
Yeha just thinking there would be a alternative! Will do that then! Thnx! Closing the issue!
