### ISSUE TITLE
Public roadmap in trello

### ISSUE THREAD

**Issue by beogip** [vergecurrency/VERGE#425]
Maybe we could have a public roadmap in Trello like [siacoin](https://trello.com/b/Io1dDyuI/sia-public-roadmap) where we can give a user friendly way to see futures features, current implementations, etc. Also the community could vote for which features / enhancements are the most important. 
For an easy implementation we could use [Trello's Github power up](http://help.trello.com/article/1065-using-the-github-power-up) or [zappier](https://zapier.com) or 

I don't know if here is the right channel to do this suggest, if not please tell me where I can do it and feel free to close this issue

**Comment by justinvforvendetta** [comment]
suggested enhancements go here. use the appropriate repository though

**Comment by beogip** [comment]
@justinvforvendetta did you know where can I post this kind of ideas?
