### ISSUE TITLE
dumpprivkey

### ISSUE THREAD

**Issue by Cryptosurfer69** [vergecurrency/VERGE#426]
# Issue Template
Trying to get my private key, but tells me wallet is only unlocked for minting....When I unlock wallet through menu, it does not give me an option of anything....
## Context

Wallet is unlocked for minting only. (code -13)
## Prerequisites

* [x ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request

**Comment by rvrhee** [comment]
Get priv key in debug window enter following commands
walletlock
walletpassphrase yourpassword 900 false
dumpprivkey adress

**Comment by Cryptosurfer69** [comment]
I get an error, I've attached a screen shot

**Comment by justinvforvendetta** [comment]
you locked the wallet, unlock it for a number of minutes and dump the key after

**Comment by Cryptosurfer69** [comment]
I still get the error wallet is unlocked for minting only (code - 13)

**Comment by Nissemus** [comment]
Restart the wallet. Then use:

walletpassphrase <passphrase> 900 false
dumpprivkey <VERGEaddress>

**Comment by Nissemus** [comment]
Restart the wallet. Then use:

walletpassphrase \<passphrase> 900 false
dumpprivkey \<VERGEaddress>
