### ISSUE TITLE
[Verge OSX Electrum wallet] Empty message is shown, when wallet is created

### ISSUE THREAD

**Issue by Mrna1** [vergecurrency/VERGE#427]
1)Open the Verge Electrum wallet
2)Check Create new wallet and Standard wallet in Electrum - install Wizard
3)Click on Next

Expected result: Wallet is created.

Actual result: Empty warning message is shown and wallet is not created.

System version: 10.12.6
![screen shot 2018-01-09 at 19 31 59](https://user-images.githubusercontent.com/17550344/34736958-f685cc7c-f574-11e7-8612-1f760fcf942b.png)

It is the first time when I try the wallet. If you need a video or more data let me know.

**Comment by justinvforvendetta** [comment]
did you open it by dragging it into applications first? also these issues should go in the electrum issues, not core, thanks!

**Comment by Mrna1** [comment]
Ok, I could not even be opened from dmg. 
Yes, I copied it to Applications first. So, where could I get a help?

**Comment by Lildan** [comment]
@Mrna1 open an issue in this repo https://github.com/vergecurrency/electrum-xvg
