### ISSUE TITLE
Can't send Verge with Windows Electrum 2.4.1 anymore ("Invalid Fee" or nothing happens)

### ISSUE THREAD

**Issue by CodeBenson** [vergecurrency/VERGE#433]
## Context

I am trying to send 99 XVG (+ 1 fee) with Windows Electrum Wallet 2.4.1. I already did send 100 XVG a few times, but it stopped working some days ago.

## Prerequisites

Windows Electrum Wallet 2.4.1, balance 385, connected to 46.163.118.201, no SSL, no auto-connect.

## User Story:

Two scenarios:

1) The fee is set to 1 in the options, then I get the error "Invalid Fee". Even if I change the fee to 0.1 or 10 (see screen 1).
![screen1](https://user-images.githubusercontent.com/1536170/34761384-cad769fe-f5e3-11e7-8107-70c93eb4bdcc.png)

2) The fee is set manual, then either nothing happens at all when clicking on "send" or I get the popup asking "send X XVG to ADDRESS", but clicking "Yes" also results in nothing happens. (in screen 2 I tried to send 350, but also tried other amounts before)
![screen2](https://user-images.githubusercontent.com/1536170/34761408-f2d28d08-f5e3-11e7-86df-4a2722f6ec47.png)

I also tried to delete all wallet data and restore the wallet. Strange thing ist, that all transactions are verified until 2018-01-04 21:55. It always stops there, even if I restore the wallet or use another server. There are also transactions that only show "unknown". But in the block explorer, all transactions have more than a thousand confirmations.
![screen3](https://user-images.githubusercontent.com/1536170/34761494-60a1c43e-f5e4-11e7-9891-437fac5dcd04.png)

Don't know what else to do. I hope my coins are not stuck forever. I would like to send all my coins to another wallet. Is there any other way to do so?

**Comment by justinvforvendetta** [comment]
when you clicked send it didn't take you to another window to sign and then broadcast?

**Comment by justinvforvendetta** [comment]
what server were you connected to?

**Comment by CodeBenson** [comment]
No it didn't take me to another window like it used to before. I tried different servers:
46.163.118.201 (found that in a post)
e1.verge-electrum.com
electrum-xvg.stream

Maybe not all from the list. But I thought it should work with any server, right?

![screen](https://user-images.githubusercontent.com/1536170/34780454-7d765766-f623-11e7-86ff-fbbc2f266c88.png)

**Comment by justinvforvendetta** [comment]
should yes, but that's also why it can use multiple servers, as redundancies, since it's possible for a server to crash or lag, etc

**Comment by CodeBenson** [comment]
Ahhh shame on me, I still lack some fundamental understanding of the technology. I was mining together with some friends and everyone got his own adress. I probably was trying to send from an empty one. If I choose the adress to send from it's working. Does that make sense?

Sorry for bothering though. Great work guys, keep it on!

![screen](https://user-images.githubusercontent.com/1536170/34781638-a720a71c-f626-11e7-9bfb-8a10ade282d7.png)

**Comment by justinvforvendetta** [comment]
no worries, the important part is you got it working :)

**Comment by CodeBenson** [comment]
Still a little problem remains: I cannot send from the first and third adress (amounts 63 and 170). "Right click" ->"send from" does nothing. I still don't understand the big picture. What should I do to either get all coins in one adress or (better) send all coins from my wallet to my exchange wallet?

**Comment by CodeBenson** [comment]
can I see the logs of the wallet? Does it log debug info or just errors?

**Comment by CodeBenson** [comment]
@justinvforvendetta could you please tell what possible reason could prevent me from sending the coins from the mentioned addresses? I'm a software developer (but mostly mobile, some javascript stuff), you can throw technical stuff at me :)

**Comment by CodeBenson** [comment]
GOT IT!!!

I sweeped the "broken" adresses and now everything is fine again 👍
