### ISSUE TITLE
Win10, QT-4.0.1:No onion hostname yet, will retry in x seconds

### ISSUE THREAD

**Issue by swat69** [vergecurrency/VERGE#434]
* [y] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x] bug report

Win10 VERGE-QT 4.0.1:

Folder onion with files hostname and private_key is not being created,
VERGE-QT is not starting. -> debug.log: No onion hostname yet, will retry in x seconds

path AppData\Roaming\VERGE\tor\onion

I guess tor not working without hostname and key, workaround:
create folder onion within tor
create file hostname within folder onion
use a valid VERGE.conf:  https://verge-blockchain.com/trouble

**Comment by justinvforvendetta** [comment]
was this a result of already having tor running in a separate instance?

**Comment by swat69** [comment]
Not working even after reboot, so other tor not running.
Second win10 ok, I see a folder ROAMING\tor is being created but only on this win10.
(And VERGE-qt even working on second win10 with running tor-browser)
Several reports about this issue on Discord yesterday.

**Comment by swat69** [comment]
Local port 9089 blocked by 'VMware vCenter Converter Standalone Agent', -> TOR can not bind.
VMware Service stopped and VERGE-qt OK !

**Comment by justinvforvendetta** [comment]
ah good find. this will be useful in Google searches. I wonder why the vm needed that port

**Comment by pcp1985** [comment]
Converter 5.x | 9089 | TCP | Converter Standalone server | powered-on source machine | Required for system conversion. Remote agent deployment

**Comment by justinvforvendetta** [comment]
interesting. well make a tutorial on how to change from port 9089 soon. maybe in the wiki here

**Comment by pcp1985** [comment]
Also, one colleague in Verge telegram community suggested that it would be great if someone from Verge team can try out 3 transactions of 1 $ , 10 $ and 100$ on top 25 coins and have 2 columns (1 speed of transaction and 2 cost of the transaction) it would boost a lot Verge acceptance.  Once read, please delete this post of mine.
