### ISSUE TITLE
Not receiving XVG coins when sending XVG coins from Core Wallet 4.0.1 to Electrum XVG wallet 2.4.1

### ISSUE THREAD

**Issue by ralphMevision** [vergecurrency/VERGE#435]
# Issue Template

## Prerequisites

* [X] Are you running the latest version? 4.0.1

## User Story:

* "I'm submitting a ... "
  - [X] bug report

## Expected Behavior

Transferring from Core Wallet 4.0.1 4 $XVG to an Electrum-XVG Tor wallet should deduct Core Wallet balance by 4 $XVG with 0.10 $XVG and should receive 4$XVG in Electrum Tor wallet both connected to network (Core Wallet connected to 48 servers and Electrum Wallet connected to onion server)

## Current Behavior

When transferring 4 $XVG from core wallet 4.0.1 with 0.10 $XVG fee then transation gets confirmed by user and a new transaction id is created and amount is deducted from Core Wallet account and transaction logged in transaction history tab in core wallet but it always stays in status: 0 not confirmed/ broadcasting via 32 nodes. Transaction Id not able to be found on the blockchain explorer. When using the decode transaction feature in core wallet then I can see that the fee is not 0.10 but it is telling me 1.8 which then goes over my balance of my core wallet account 4+1.8 = 5.8 and only have 4.9. Would that be the issue? but how can I get my coins back? did it only wrote it to my local blockchain that is why the coins are gone from my account?

Transaction id is: 0e314260a4cbd1c094d7631c9bd10c6ab0302e9f1f60940d9086d788392b2be3

## Screenshots

![image](https://user-images.githubusercontent.com/24275187/34767394-3daf81dc-f5f8-11e7-9d1d-99c33d053f37.png)

## Your Environment

Win 10 - Core Wallet 4.0.1 - Electrum XVG Tor Wallet 2.4.1

**Comment by justinvforvendetta** [comment]
your transaction is in mempool waiting to be processed by miners

**Comment by ralphMevision** [comment]
Hi @justinvforvendetta it is still there after 4 hours now. Will it ever be picked up as the amounts are small? Is it possible to see the mempool somewhere? thanks.

**Comment by justinvforvendetta** [comment]
the larger pools are updating now

**Comment by ralphMevision** [comment]
@justinvforvendetta still not process and no confirmations at all for 3 days. Any idea why? would that be the same with other transactions? Do not really want to try before I know what is happening with this one. thanks.
![image](https://user-images.githubusercontent.com/24275187/34908924-83a92ccc-f898-11e7-8dbc-5cf08c0e86a4.png)
