### ISSUE TITLE
Cannot rename address label

### ISSUE THREAD

**Issue by joseluislopesdias** [vergecurrency/VERGE#437]
## Context

After labeling a **stealth address** for the first time, cannot rename it again.

## Current Behavior

Instead of renaming, it goes back to the previous label.

## Your Environment

* Verge Release: 4.0.1.0-unk-beta
* CPU: Intel i7 
* GPU: Nvidia Geforce 640m
* RAM: 16GB
* OS: Windows 10 64bit

**Comment by vorlonempire** [comment]
Cannot reproduce here. Works fine

**Comment by joseluislopesdias** [comment]
My mistake, it's a stealth address.

**Comment by ralphMevision** [comment]
I confirm same for me.

**Comment by justinvforvendetta** [comment]
ok minor issue but I'll look into it, thanks for reporting!

**Comment by fabiotnt** [comment]
Maybe duplicate Issue.

https://github.com/vergecurrency/VERGE/issues/447

**Comment by marpme** [comment]
@justinvforvendetta checked that for you, PR is also created

**Comment by justinvforvendetta** [comment]
you're on fire!

**Comment by Max-Meldrum** [comment]
@marpme @justinvforvendetta 
Did PR #462 fix this issue and #447? If so, then they can probably be closed?

**Comment by Influence2** [comment]
Following up to close open issues, can this be closed as the fix was committed? @marpme @justinvforvendetta @joseluislopesdias

**Comment by joseluislopesdias** [comment]
Yes, thanks. It's now working as it should.

Em 31/01/2018 21:27, "JRoy" <notifications@github.com> escreveu:
