### ISSUE TITLE
macOS High Sierra lunch error

### ISSUE THREAD

**Issue by codedevmk** [vergecurrency/VERGE#444]
Missing library below is the error log dump

Process:               VERGE-Qt [1628]
Path:                  /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
Identifier:            com.vergecurrency.VERGE-Qt
Version:               4.0.1 (4.0.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VERGE-Qt [1628]
User ID:               501

Date/Time:             2018-01-10 22:21:27.874 -0600
OS Version:            Mac OS X 10.13.2 (17C205)
Report Version:        12
Anonymous UUID:        E69D63A3-B6F0-0A2D-A2EF-A597E1C7B609

Sleep/Wake UUID:       0EDE26AD-7361-4F5C-B5AC-BD8C91A34FD0

Time Awake Since Boot: 5300 seconds
Time Since Wake:       1100 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x10f19f000 -        0x10faeaff7 +com.vergecurrency.VERGE-Qt (4.0.1 - 4.0.1) <017B48CF-6672-3D55-BE2B-7541F497D2D4> /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
       0x10fbc2000 -        0x10fbc4fff +libboost_system.dylib (0) <F3411558-02A6-3F5A-B040-E70EEB13F639> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x10fbca000 -        0x10fbd8ff7 +libboost_filesystem.dylib (0) <FADB85A3-B162-3CC3-9D21-5D4D0B452F4C> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x10fbe0000 -        0x10fc14fff +libboost_program_options-mt.dylib (0) <551B73D9-D5BA-3BDB-A497-AE17966D1B1F> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x10fc37000 -        0x10fc44ff7 +libboost_thread-mt.dylib (0) <43A32D2F-3381-32E7-A6A5-47B94F951AD6> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x10fc50000 -        0x10fc51ffb +libboost_chrono-mt.dylib (0) <F098AA6F-5272-3ACE-9305-6AB0ABAD6DE7> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x10fc54000 -        0x11015ffff +QtWidgets (5.5.1) <416CBC52-D42C-3996-B338-C848863E65B0> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x110294000 -        0x110718fff +QtGui (5.5.1) <217B896F-895F-3DEC-BF29-01E065492858> /Applications/VERGE-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x1107f7000 -        0x110cfefff +QtCore (5.5.1) <201F9A70-4676-3BC5-8B59-82DA94559272> /Applications/VERGE-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x110d91000 -        0x110e9eff7 +QtNetwork (5.5.1) <CC4ADD9F-E8C7-3618-9D83-7DBF9AC4267A> /Applications/VERGE-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x110ed6000 -        0x110f39ff7 +QtDBus (5.5.1) <B0B9AE70-B993-3081-9336-E01BD1233823> /Applications/VERGE-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x110f50000 -        0x110f56fff +libqrencode.4.dylib (0) <5B7DEE75-603E-351D-B14C-21663CD470BC> /Applications/VERGE-Qt.app/Contents/Frameworks/libqrencode.4.dylib
       0x110f5a000 -        0x11108cff7 +libprotobuf.15.dylib (0) <6300475A-5FB2-39C0-AE54-644CFAC18091> /Applications/VERGE-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x111142000 -        0x111266ff7 +libdb_cxx-4.8.dylib (0) <893E0F96-1F8A-3073-B1CF-CC60610C3E90> /Applications/VERGE-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x11129e000 -        0x1112aeff3 +libz.1.dylib (0) <C1AAED3F-5000-3D8F-BE16-37688A0D413A> /Applications/VERGE-Qt.app/Contents/Frameworks/libz.1.dylib
       0x1112b8000 -        0x1112e5fff +libevent-2.1.6.dylib (0) <891F379E-D5F9-39EB-BECA-2E24F943B7B3> /Applications/VERGE-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x1112f9000 -        0x111301ff3 +libminiupnpc.16.dylib (0) <C103607F-F06C-34D6-A60A-27E9E344F015> /Applications/VERGE-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x11130a000 -        0x11134bfff +libssl.1.0.0.dylib (0) <3C28C2A8-036B-34B3-82BB-5780DB7271B2> /Applications/VERGE-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x11136e000 -        0x1114dec87 +libcrypto.1.0.0.dylib (0) <1C6D06DA-0F88-37BA-80E9-52C4AC7E942C> /Applications/VERGE-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x11b6e4000 -        0x11b72e98f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
    0x7fff3862b000 -     0x7fff3862fffb  com.apple.agl (3.3.1 - AGL-3.3.1) <5A110DE6-3EE7-343B-95FE-9642517D1B64> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff39a0b000 -     0x7fff3a868fff  com.apple.AppKit (6.9 - 1561.20.106) <7A71ACCF-2DF5-3557-BB22-3A9FC9F71CCF> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff3a8ba000 -     0x7fff3a8bafff  com.apple.ApplicationServices (48 - 50) <7627DBD6-497B-3AB7-9B63-F0532EDF09B8> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff3c3e5000 -     0x7fff3c885fff  com.apple.CoreFoundation (6.9 - 1450.16) <23F8373A-FA3F-37A2-BA5B-70061BFCCD21> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff3d544000 -     0x7fff3d544fff  com.apple.CoreServices (822.19 - 822.19) <0C60B639-4CC4-3F57-BC5E-DB71EB75F7F4> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff3e363000 -     0x7fff3e368fff  com.apple.DiskArbitration (2.7 - 2.7) <44836CE9-A9ED-3017-972A-7A0A3D6B472B> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff3e529000 -     0x7fff3e8eefff  com.apple.Foundation (6.9 - 1450.16) <7FEC6610-70EA-3A8D-8EC4-7E99BAF1E312> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff3ec03000 -     0x7fff3ec9efff  com.apple.framework.IOKit (2.0.2 - 1445.31.1) <7556086A-EFAF-3262-9822-6F666CFC6655> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff4673d000 -     0x7fff4674bffb  com.apple.opengl (16.4.2 - 16.4.2) <C8C31EF5-8DB4-336F-A87C-5D520C7EFDC5> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff61652000 -     0x7fff61685fff  libclosured.dylib (519.2.2) <48051216-5647-3643-B979-B77D0FD20011> /usr/lib/closure/libclosured.dylib
    0x7fff61b64000 -     0x7fff61b65ff3  libSystem.B.dylib (1252) <5EDEEA85-0387-31EE-9D9B-DA1B75E7AEF3> /usr/lib/libSystem.B.dylib
    0x7fff61d98000 -     0x7fff61deefff  libc++.1.dylib (400.9) <FCF5E1F6-2B04-3545-8004-F3AB32FED172> /usr/lib/libc++.1.dylib
    0x7fff61def000 -     0x7fff61e13ff7  libc++abi.dylib (400.7) <217656D5-BC40-37FF-B322-91CB2AAD4F34> /usr/lib/libc++abi.dylib
    0x7fff63165000 -     0x7fff635537e7  libobjc.A.dylib (723) <93A92316-DE1E-378C-8891-99720B50D075> /usr/lib/libobjc.A.dylib
    0x7fff63c00000 -     0x7fff63c04ff7  libcache.dylib (80) <354F3B7D-404E-3398-9EBF-65CA2CE65211> /usr/lib/system/libcache.dylib
    0x7fff63c05000 -     0x7fff63c0fff3  libcommonCrypto.dylib (60118.30.2) <674286D3-7744-36A3-9AAA-49DFCD97A986> /usr/lib/system/libcommonCrypto.dylib
    0x7fff63c10000 -     0x7fff63c17fff  libcompiler_rt.dylib (62) <4487CFBA-A5D7-3282-9E6B-94CAD7BE507E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff63c18000 -     0x7fff63c20ffb  libcopyfile.dylib (146.30.2) <2C7C67D7-562B-3FFA-973D-BACF4C10E1EC> /usr/lib/system/libcopyfile.dylib
    0x7fff63c21000 -     0x7fff63ca6fff  libcorecrypto.dylib (562.30.10) <8A53EFE1-AFCA-3676-BEE1-FA5ED9F0E222> /usr/lib/system/libcorecrypto.dylib
    0x7fff63d2e000 -     0x7fff63d67ff7  libdispatch.dylib (913.30.4) <7D0E3183-282B-3FEE-A734-2C0ADC092084> /usr/lib/system/libdispatch.dylib
    0x7fff63d68000 -     0x7fff63d85ff7  libdyld.dylib (519.2.2) <C50D02BC-A333-3313-B787-02F255A6783F> /usr/lib/system/libdyld.dylib
    0x7fff63d86000 -     0x7fff63d86ffb  libkeymgr.dylib (28) <6D84A96F-C65B-38EC-BDB5-21FD2C97E7B2> /usr/lib/system/libkeymgr.dylib
    0x7fff63d94000 -     0x7fff63d94ff7  liblaunch.dylib (1205.30.29) <E66F58ED-C15E-3DFB-BC22-A861E13918C6> /usr/lib/system/liblaunch.dylib
    0x7fff63d95000 -     0x7fff63d99ffb  libmacho.dylib (900.0.1) <756F2553-07B6-3B42-ACEA-2F0F1A5E8D0F> /usr/lib/system/libmacho.dylib
    0x7fff63d9a000 -     0x7fff63d9cff3  libquarantine.dylib (86) <6AC8773F-3817-3D82-99C2-01BABB9C3CBB> /usr/lib/system/libquarantine.dylib
    0x7fff63d9d000 -     0x7fff63d9eff3  libremovefile.dylib (45) <912FA211-DD8C-3C92-8424-21B89F8B10FD> /usr/lib/system/libremovefile.dylib
    0x7fff63d9f000 -     0x7fff63db6fff  libsystem_asl.dylib (356.1.1) <94972913-9DF0-3C78-847C-43E58919E3DA> /usr/lib/system/libsystem_asl.dylib
    0x7fff63db7000 -     0x7fff63db7fff  libsystem_blocks.dylib (67) <F2493BB5-B1C6-3C4D-9F1F-1B402E0F1DB7> /usr/lib/system/libsystem_blocks.dylib
    0x7fff63db8000 -     0x7fff63e41ff7  libsystem_c.dylib (1244.30.3) <E0136C71-0648-36F0-9F84-82EA2748A8D7> /usr/lib/system/libsystem_c.dylib
    0x7fff63e42000 -     0x7fff63e45ffb  libsystem_configuration.dylib (963.30.1) <0F8D0B76-4F7D-34EC-AB6C-50F9465809DA> /usr/lib/system/libsystem_configuration.dylib
    0x7fff63e46000 -     0x7fff63e49ffb  libsystem_coreservices.dylib (51) <21A488D0-2D07-344E-8631-CC8B2A246F35> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff63e4a000 -     0x7fff63e4bfff  libsystem_darwin.dylib (1244.30.3) <2F750CB1-BC26-3FA3-AE59-553EE30D451B> /usr/lib/system/libsystem_darwin.dylib
    0x7fff63e4c000 -     0x7fff63e52ff7  libsystem_dnssd.dylib (878.30.4) <EB9BB165-45A4-367C-B33A-688D4F383A95> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff63e53000 -     0x7fff63e9cff7  libsystem_info.dylib (517.30.1) <7D79E167-4B5C-3833-81EE-3AF3FB53616D> /usr/lib/system/libsystem_info.dylib
    0x7fff63e9d000 -     0x7fff63ec2ff7  libsystem_kernel.dylib (4570.31.3) <D2E842AA-3B8D-31BF-8234-8C1BE11CFE32> /usr/lib/system/libsystem_kernel.dylib
    0x7fff63ec3000 -     0x7fff63f0efcb  libsystem_m.dylib (3146) <ABB1B85F-9FFE-31B8-AD4F-E39A30794A93> /usr/lib/system/libsystem_m.dylib
    0x7fff63f0f000 -     0x7fff63f2efff  libsystem_malloc.dylib (140.1.1) <9F0745FF-B92F-330D-8812-BB74001D1D33> /usr/lib/system/libsystem_malloc.dylib
    0x7fff63f2f000 -     0x7fff63fd3ff3  libsystem_network.dylib (1229.30.11) <40BAD301-8744-3AD8-A688-E7925C587B00> /usr/lib/system/libsystem_network.dylib
    0x7fff63fd4000 -     0x7fff63fdeffb  libsystem_networkextension.dylib (767.30.7) <C5ED4BAB-2480-369D-8AB6-DFB37C15A1EE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff63fdf000 -     0x7fff63fe8ff3  libsystem_notify.dylib (172) <98EA3D62-7C86-30DE-8261-D020D2F1EFF3> /usr/lib/system/libsystem_notify.dylib
    0x7fff63fe9000 -     0x7fff63ff0ff7  libsystem_platform.dylib (161.20.1) <C049250F-8C35-314D-810F-4E28AEAED983> /usr/lib/system/libsystem_platform.dylib
    0x7fff63ff1000 -     0x7fff63ffcfff  libsystem_pthread.dylib (301.30.1) <ABA848E1-6978-3B42-A3A7-608B2C36FA93> /usr/lib/system/libsystem_pthread.dylib
    0x7fff63ffd000 -     0x7fff64000ff3  libsystem_sandbox.dylib (765.30.4) <A51828BA-26D8-3205-AF3A-DF5C37269468> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff64001000 -     0x7fff64002ff3  libsystem_secinit.dylib (30) <F06ADB8F-9E94-34A7-B3C9-2C22FDD14BAD> /usr/lib/system/libsystem_secinit.dylib
    0x7fff64003000 -     0x7fff6400aff7  libsystem_symptoms.dylib (820.30.7) <DC3586C2-AA56-3419-88D3-FC0DBF08E3C0> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff6400b000 -     0x7fff6401eff7  libsystem_trace.dylib (829.30.14) <69EBF017-D40F-30D7-9B0B-BFC862D761A5> /usr/lib/system/libsystem_trace.dylib
    0x7fff64020000 -     0x7fff64025ff7  libunwind.dylib (35.3) <6D4FCD49-D2A9-3233-95C7-A7635CE265F2> /usr/lib/system/libunwind.dylib
    0x7fff64026000 -     0x7fff64052ff7  libxpc.dylib (1205.30.29) <F7E5F1BC-614B-39CB-B6CE-92A9C7B7EC0B> /usr/lib/system/libxpc.dylib

Model: MacBookAir7,2, BootROM MBA71.0171.B00, 2 processors, Intel Core i5, 1.6 GHz, 8 GB, SMC 2.27f2
Graphics: Intel HD Graphics 6000, Intel HD Graphics 6000, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5444
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5444
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.37.5.1a3)
Bluetooth: Version 6.0.2f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

**Comment by kyco16** [comment]
I am also getting the same message. I have homebrew installed and tried using `brew install boost` in the terminal because that worked with earlier versions of Wraith but not for this one. Plz help

**Comment by codedevmk** [comment]
Whoever oversees Travis build for OSX needs to include new High Sierra dependencies.

    On Wednesday, January 10, 2018 10:44 PM, Kyle Coleman <notifications@github.com> wrote:
 

 I am also getting the same message. I have homebrew installed and tried using brew install boost in the terminal because that worked with earlier versions of Wraith but not for this one. Plz help—

**Comment by justinvforvendetta** [comment]
this is already open in another thread

**Comment by codedevmk** [comment]
got it, thx 

    On Wednesday, January 10, 2018 11:29 PM, sunerok <notifications@github.com> wrote:
 

 this is already open in another thread—

**Comment by kyco16** [comment]
Might be in another thread but the solution in the other thread doesn’t even work sooooo 🤔

Kyle Coleman
