### ISSUE TITLE
Clarification on restoring from a back up

### ISSUE THREAD

**Issue by XVGMonk** [vergecurrency/VERGE#446]
Where do I place the (backup).dat file once I'm ready to restore? 

I've created a backup called backup1.0.dat and saved it on a flash drive, where do I place backup1.0.dat in order to restore the backup and update the wallet? 

(i've tried placing backup1.0.dat inside here library/ApplicationSupport/Verge and wallet.dat opened up when I launched the wallet.

Just need clarification on how to do this.

Thank you!

ps: do I replace the wallet.dat with backup1.0.dat? 

<!-- How has this issue affected you? What are you trying to accomplish?
I need to be confident about backing up my wallet in case somethings happens.

* [ ] Are you running the latest version?
Yes
## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ x ] support request 
  - [ ] translation request

**Comment by Revinand** [comment]
Check this #458
