### ISSUE TITLE
Cannot edit the label of stealth address on MacOS

### ISSUE THREAD

**Issue by ttkien** [vergecurrency/VERGE#447]
# Issue Template

## Context

I want to change the label of stealth address but I was not changed after editing
## Prerequisites

* [x] Are you running the latest version?
Yes, I am using 4.0.1 on macOS in 4th release

## User Story:
Step 1: I double clicked to edit the label of stealth address like the below image 
![screen shot 2018-01-11 at 3 17 20 pm](https://user-images.githubusercontent.com/1519521/34815176-faba90c4-f6e2-11e7-9a38-4ac1dc9beb99.png)

Step 2: I edited the label to new label as "Deleted"
![screen shot 2018-01-11 at 3 17 32 pm](https://user-images.githubusercontent.com/1519521/34815204-1bc21df0-f6e3-11e7-9365-41fb8e6786df.png)

Step 3: I pressed "enter" and the label was keeping the old value
![screen shot 2018-01-11 at 3 17 39 pm](https://user-images.githubusercontent.com/1519521/34815343-8d511714-f6e3-11e7-9bad-fe539f9d686d.png)

## Expected Behavior
It should show new label after editing label

**Comment by Vadim-Podlevsky** [comment]
Confirm the same issue. Also, Stealth address checkbox is unchecked when editing the stealth address.

**Comment by Joske2** [comment]
Confirmed. Also cannot delete the stealth address!

**Comment by fabiotnt** [comment]
Confirmed. Same issue on v4.0.1.
Another thing is that stealth checkbox is unchecked when you edit a stealth address.

**Comment by flmuel** [comment]
please add a rename and delete function

**Comment by Influence2** [comment]
@justinvforvendetta @ttkien  Can this issue be closed as fix was committed. #462 

Trying to close open issues.

**Comment by justinvforvendetta** [comment]
thanks @influence2
