### ISSUE TITLE
Wraith Windows 64-Bit Minor Cosmetic Issues

### ISSUE THREAD

**Issue by theterribletoo** [vergecurrency/VERGE#448]
This is for the Wraith Windows 64-Bit 4.0.1 Wallet. Here are three minor cosmetic issues.

When looking at the block explorer tab if minimized to the smallest size the "Jump to block" and "decode transaction" buttons are cut off. When making the window bigger this goes away. I suggest putting a limit on how small the window can be as an easy fix maybe. 

1. Minimized
![1](https://user-images.githubusercontent.com/31616002/34816900-54e23124-f684-11e7-91ed-abb253389885.JPG)

2. Not fully minimized
![2](https://user-images.githubusercontent.com/31616002/34817077-e4dfe564-f684-11e7-9811-d66064d941a9.JPG)

Next in the option menu the numbers are cut off for the transaction fee. 
![3](https://user-images.githubusercontent.com/31616002/34817212-5398aca2-f685-11e7-968b-c756003f2866.JPG)

Lastly the "Export Data" tab could use the same blue highlight as the rest of the tabs instead of the white on white. I also noticed that if you move this tab around, you can not get it to go back to its original form without closing out the program.

![4](https://user-images.githubusercontent.com/31616002/34817559-5ff4f658-f686-11e7-8826-a642b34a2558.JPG)

![5](https://user-images.githubusercontent.com/31616002/34817568-63b36c34-f686-11e7-850d-a3ec386454ba.JPG)

**Comment by jrsikors** [comment]
This was pre-4.0.1 funky beta release.  if still a problem with Windows UI issues -- please post under #555  to keep all the windows GUI issues together
