### ISSUE TITLE
Only Orphan blocks since upgrading to 4.0.1

### ISSUE THREAD

**Issue by ocminer** [vergecurrency/VERGE#449]
Since upgrading to 4.0.1 every block is orphaned.

Can I somehow disable Tor ?

**Comment by justinvforvendetta** [comment]
this is because each pool keeps starting 4.0.1 and then reverting back. we're going to delist pools that aren't running 4.0.1 from our website this weekend

**Comment by ocminer** [comment]
wat ? and what if a big solo miner, or an asic farm simply sticks to 2.0.1 and doesn't care ? you have to design 4.0.x the way that blocks are accepted by older clients as well.. Obviously :)

**Comment by tpruvot** [comment]
im almost "ready" to move to the 4.0 (which will cause a pool interuption) but no way i use tor here

**Comment by justinvforvendetta** [comment]
if u guys want to clone before we merged tor in, great, otherwise we will just make a new option for --clearnet to allow verge to run on clearnet nodes

**Comment by justinvforvendetta** [comment]
we're making a branch for a clearnet version of the master branch here: https://github.com/vergecurrency/VERGE/tree/4.0clearnet

**Comment by justinvforvendetta** [comment]
ok pool admins, you can clone from there, and youll be on our latest update, minus tor integration. @ocminer @tpruvot @ondalf

**Comment by justinvforvendetta** [comment]
since we couldnt get everyone on the same page at the same time, we made this branch. now you can mine without orphans until forking, which will occur at height 1807000. bittrex and binance will be updating tonight. @ocminer @tpruvot @ondalf

**Comment by michpiatek** [comment]
@tpruvot I updated 4.0clearnet branch as well.

**Comment by ocminer** [comment]
Hmm, I don't see that tor is disabled on that branch ?!

**Comment by michpiatek** [comment]
@ocminer tor is disabled on 4.0clearnet

**Comment by ocminer** [comment]
Why does @justinvforvendetta then link the "mining_tor" branch ?

**Comment by ocminer** [comment]
The mining_tor branch still only produces orphans, trying clearnet branch now...

**Comment by michpiatek** [comment]
After switching to clearnet version problem is solved. For some pools tor block broadcast might be too slow probably. We will need to do more testing around that issue and keep the clearnet version up to date for mining pools.

**Comment by ocminer** [comment]
confirmed, clearnet working fine here

**Comment by tpruvot** [comment]
i suggest to handle tor=0 flag in .conf to disable it, as it should be...

**Comment by michpiatek** [comment]
@tpruvot Currently tor and clearnet versions have too much differences in network code. I agree we should merge them and handle some flag to disable tor but that will take some time. For now use branch that works best for you.

**Comment by justinvforvendetta** [comment]
@tpruvot there's a clearnet branch with the changes. have you already compiled it?

**Comment by jaredthesovereign** [comment]
I am mining in a private pool (old version) and updated my wallet to new 4x version but I am not seeing my coin from the past day from that pool.  Please advise ...

**Comment by AZ-Ronin** [comment]
Solo mining help? I'm only getting orphan blocks using 4.0.1 funky beta (Interesting name) on Win64. The 4.0 release appears to be deleted here... can we get it back until 4.0.2 (I'm hoping it's fixed in the next release). Pretty Please?

**Comment by justinvforvendetta** [comment]
yeah orphan blocks make sense if you are solo mining, unless you have enough hashpower to compete with the pools.. @AZ-Ronin

**Comment by justinvforvendetta** [comment]
@jaredthesovereign because the "private pool" isnt updated lol its mining coins on an old chain that isnt compatible with verge now.

**Comment by AZ-Ronin** [comment]
It doesn't make sense when I've been on a pool where I was the only person mining and got valid blocks...

**Comment by justinvforvendetta** [comment]
are you sure you are using the newest wallet?

**Comment by AZ-Ronin** [comment]
I'll download it again and the blockchain and try again. I'm not at the computer now... I'll get the full version string later... it's 4.0.1 with some other numbers and says funky beta at the end of it...

**Comment by AZ-Ronin** [comment]
4.0.1.0-794660a-funky-beta is the full version id

**Comment by justinvforvendetta** [comment]
yeah that should work. only thing is you are competing against a lot of pools.

**Comment by AZ-Ronin** [comment]
Roger that, but out of 10+ blocks I've solved now not even one accepted is odd and the correlation from pools getting nothing but orphans seemed strange to me... especially considering that a week ago I had an accepted block as the only miner on a pool.

**Comment by justinvforvendetta** [comment]
so other pools with more hashpower are getting the blocks while you orphan? that sounds about right... let me know if any that have less hashpower keep blocks that you orphan

**Comment by AZ-Ronin** [comment]
Justin, really no need to be a smartass about it. Here's what I said: Pools are complaining about only getting orphans due to the new wallet. I was able to mine a block while on an empty pool. I then try solo mining using the new wallet and all I'm getting are orphans. The correlation I made was sound, even if you don't agree with it. 

All that was asked was can we have access to the old wallet while the issues with the new one are worked out.

Whether you believe I can solo mine a block is irrelevant.

**Comment by justinvforvendetta** [comment]
I was not being a smart ass in any way

**Comment by justinvforvendetta** [comment]
and the old wallet is not compat with the chain anymore since the protocol has changed. if you mine with the old wallet, the coins you mine will not be accepted anywhere

**Comment by AZ-Ronin** [comment]
Thanks for your time Justin. Have a great weekend.
