### ISSUE TITLE
Allow specific location for blockchain

### ISSUE THREAD

**Issue by thomasvt1** [vergecurrency/VERGE#45]
Hi,

It would be a good idea to allow the user to set the storage location of the blockchain.
This would be very handy for users with a (small) SSD and have a separate HDD.

Thanks for your time.

**Comment by vergecurrency** [comment]
@thomasvt1 you can do exactly that with the --datadir flag already ;]
for instance, say you want it in a folder called E:\vergedata\
verge-qt.exe --datadir=E:\vergedata\

**Comment by thomasvt1** [comment]
Ah neat, didn't know that. Thanks!

**Comment by vergecurrency** [comment]
@thomasvt1 no problem!  i will add it to the README so people are more aware of it. =]
