### ISSUE TITLE
Problem with stealth adress transfers

### ISSUE THREAD

**Issue by thiagomhk** [vergecurrency/VERGE#452]
Hello.

Tried to made a transfer via stealth adress to myself.
Tried it two times. 0,2XVG with 0,1XVG fee each.
Fees were collected, but no transaction apears in the history.

Any ideas?

![sem titulo](https://user-images.githubusercontent.com/35308938/34836036-cc0f4fda-f6dd-11e7-9013-64af66ffa916.png)

**Comment by mksmsrkn** [comment]
Please see: https://www.reddit.com/r/vergecurrency/comments/7pqcuk/mac_verge_qt_wraith_401_wallet_not_showing_latest/
