### ISSUE TITLE
Wallet wont sync, even after upgrading to 4.0.1

### ISSUE THREAD

**Issue by polyfonik** [vergecurrency/VERGE#453]
I had my 4.0 wallet open for about 10 days and it still hadn't finished the sync.  I recently upgraded to 4.0.1 thinking it would fix the issue but it hasn't.  It got stuck on 97% and has only gone backwards as more blocks are created.

I can't even export my private key as it is telling me that the wallet is only unlocked for minting, this is completely unacceptable - I should be able to access my coins whenever i like.

Im running MacOs Sierra 10.12.6 with Wraith version 4.0.1.  Please let me know what other info you require from me to get this fixed.

Thanks.

**Comment by mike2lab** [comment]
i have the same problems.  so many days open and still syncing...I have send some coins to that address but how is it supposed to see the coins if it doesn't sync ?

**Comment by vpistis** [comment]
try this: https://verge-blockchain.com/howto

**Comment by polyfonik** [comment]
Thanks.  Do i have to download all 3 server files or just the last one?

**Comment by vpistis** [comment]
@polyfonik only 1 file, are identical but served from different locations

**Comment by polyfonik** [comment]
Ok great.  I am following the mac instructions but there is no verge folder in my library folder...

**Comment by polyfonik** [comment]
All good i found it on google - thanks
