### ISSUE TITLE
where can you find private keys for 3.0 wallet? 

### ISSUE THREAD

**Issue by piphoto23** [vergecurrency/VERGE#454]
I have the OSX desktop wallet 3.0 and i dont see anywhere to generate a private key or to restore the wallet from the backup wallet file.

**Comment by justinvforvendetta** [comment]
private key is dumped thru dumpprivkey address in help debug console. to restore from a wallet.dat just replace existing wallet.dat with backup

**Comment by mike2lab** [comment]
when i do this  the console says : Wallet is unlocked for minting only. (code -13)

**Comment by piphoto23** [comment]
It would be great if people didnt have to be computer programmers to understand what youre saying.  I understand you get what youre saying but to a regular person this doesn't make any sense.  Also Ive asked twice about restoring the wallet and I get you have to restore it from the wallet.dat but you dont answer how to do that.  There is no options on the wallet such as "restore backup file" or to even choose the wallet.dat file from a backup
