### ISSUE TITLE
Get verge coins from electrum wallet to Qt wallet?

### ISSUE THREAD

**Issue by Pele51** [vergecurrency/VERGE#457]
Hi guys i have the latest electrum verge wallet and my coins shows up, but i want to move them into the new QT wallet, i allready downloaded it and its fully synched, i copy my wallet.data from the electrum wallet to the QT folder (appdata, roaming, verge ect...) and delete the exist wallet.data from the qt wallet, when i try to start the Qt wallet it shows zero balance, how can i get them there?

Thx in advanche!!

**Comment by justinvforvendetta** [comment]
just send it as a transaction, electrum doesn't use the same wallet.dat

**Comment by batigol82** [comment]
@justivforvendetta
My verge qt-wallet 4.0.1 for osx is work. But my problem is: I import the privatkey from xvg-electrum wallet 2.4, now i see the adresse in the qt-wallet 4.0.1 but the balance is 0! Who can help me?
