### ISSUE TITLE
restoring a wallet from wallet.dat file

### ISSUE THREAD

**Issue by piphoto23** [vergecurrency/VERGE#458]
I understand you have to restore a wallet from a wallet.dat backup file but what are the exact steps? When Im in wallet 3.0 for desktop mac osx, there is no option anywhere to choose a file to restore from a backup.  Can you list the steps for restoring a wallet.dat backup file in regular people terms not computer programer terms, you need to understand not everyone writes code and gets what youre saying in your responses.

**Comment by alexkenley** [comment]
replace the current wallet.dat with the one that has your coin in it... just rename the old one walletOLD.dat or something just in case. don't delete an wallet.dat files until you are sure you have the right one and it's all good

**Comment by piphoto23** [comment]
ok but what are the steps to doing that? how do you replace the current wallet.dat file? there are no options for that

**Comment by Revinand** [comment]
go to Verge directory (it should be somewhere in /Applications/VERGE-Qt.app/ folder, I guess).
Search for wallet.dat file.
Rename it to wallet_old.dat (for example).
Copy backuped wallet.dat (note: it should be called 'wallet.dat'. If it's not, then rename it) file beside the old file.
Run the client.

Like @alexkenley said DON'T delete the old wallet.dat file

**Comment by Jedonauta** [comment]
Hi There how are you? Thanks for your time first of all.

I ve sent 146 coins from an exchange to my Electrum-Xvg wallet that i downloaded online or mac osx running high sierra, as the other verge wallet wasn t working.

I also tried to install it following the steps on this link and doing everything correct:

https://github.com/vergecurrency/verge-core-installers/blob/master/README.md

Now the Electrum-Xvg seems to be offline , but it looks like the transaction went through at the correct address ﻿﻿:



I just would like to know what i can do, how can i send my  verges to an exchange? please let me know...it says it s not connected.

Cheers
I was also told to search for the wallet.dat file which isnt there thought are are 2 other dat files but not that one, seems like the coins are stucked in the blockchain.
can anyone help please??
