### ISSUE TITLE
Linux: libcap not found error

### ISSUE THREAD

**Issue by Revinand** [vergecurrency/VERGE#459]
Building from source with the latest updates on Linux (Ubuntu 16.04) produces this error on configuration step:

```
checking for LIBEVENT... yes
checking for ZLIB... yes
checking for LIBSECCOMP... yes
checking for LIBCAP... no
configure: error: libcap not found
```

Despite that checking says libcap is not required, it complains to lack of this package. Anyway it was solved by `libcap-dev` package installation. Not sure, but probably `libncap-dev` package should be replaced by this one on [documentation](https://github.com/vergecurrency/VERGE/blob/master/doc/build-verge-linux.md) page.

**Comment by michpiatek** [comment]
Thanks for the info, fixed.

**Comment by xieta** [comment]
This is solved on Ubuntu 16.04 LTS but still broken on Ubuntu 14.04 LTS.

**Comment by justinvforvendetta** [comment]
yeah I don't think there is a fix for 14.

**Comment by Jerthade** [comment]
export LIBCAP_LIBS=/usr/local/lib
export LIBCAP_CFLAGS=/usr/local/include

allowed configure to complete for me under 14.04

**Comment by justinvforvendetta** [comment]
@Jerthade thanks for posting that here =]
