### ISSUE TITLE
ReadME - Mac qt5.4.2 deprecated/EOL

### ISSUE THREAD

**Issue by cbake6807** [vergecurrency/VERGE#46]
The qt5.4.2 links toward the bottom of the ReadME are broken, due to 5.4.2's deprecation.

5.9.0 is out now.. will it still work?
https://download.qt.io/official_releases/qt/5.9/5.9.0/

**Comment by vergecurrency** [comment]
@cbake6807 yeah we're going to port webkit for 5.9

**Comment by justinvforvendetta** [comment]
yes, it will work if webkit is also compiled along side it.

**Comment by jhanink** [comment]
PR #171 updates the link and version to 5.5 to match the version specified in build.sh
