### ISSUE TITLE
error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by GeekBoxIT** [vergecurrency/VERGE#461]
error while loading shared libraries: libboost_system.so.1.55.0: cannot open shared object file: No such file or directory

Have installed libboost-all-dev which installs 1.58 how can I compile on Linux? I have tried both downloading the precompiled and making from GIT.

**Comment by justinvforvendetta** [comment]
our code doesn't require 1.55, I think it can handle up to 1.63

**Comment by GeekBoxIT** [comment]
What can I do to help assist in solving the issue, I tried it on another machine as well.

**Comment by justinvforvendetta** [comment]
can you paste the ssl errors you had during make?

**Comment by justinvforvendetta** [comment]
oh, those binaries are from a previous release and are outdated. I'll post Linux binaries tonight. usually Linux people compile it for themselves. instructions are in the docs folder
