### ISSUE TITLE
Stealth Transaction Not confirmed - Over two days now

### ISSUE THREAD

**Issue by jderwish** [vergecurrency/VERGE#463]
# Issue Template

## Context

Send several transactions to Stealthaddresses, the receiver receives the transaction however it never confirmed. It has been for several days now.

## Prerequisites

* [ ] Are you running the latest version? yes 4.0.1 win64

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior

The transaction should be successful and XVG coins amount to be confirm and available to recipient.

## Current Behavior

The transaction is sent and pending confirmation and the XVG coins are unconfirmed and not available to recipient.

## Screenshots
![image](https://user-images.githubusercontent.com/32366979/34896021-2f0fc2f8-f7b6-11e7-915a-9c4f80655589.png)

![image](https://user-images.githubusercontent.com/32366979/34896035-3cbc1186-f7b6-11e7-90e0-c1039381d4c9.png)

![image](https://user-images.githubusercontent.com/32366979/34896046-4767d318-f7b6-11e7-9deb-42afcc8d4b60.png)

![image](https://user-images.githubusercontent.com/32366979/34896060-53212902-f7b6-11e7-8363-f577f065d4ee.png)

## Possible Solution

Please confirm that the nodes are upgraded properly and indeed this new type of transactions are being confirmed.

## Steps to Reproduce (for bugs)

* Steps :
1. Send XVG coins to a stealthaddress
2. Check transaction Status on sender's wallet
3. Check transaction Status on recipient's wallet
4. No errors in the debug.log

## Your Environment

* Verge Release: 4.0.1 Win64
* CPU: 4
* GPU: 1
* RAM: 4GB
* OS: Windows 10 64bit

## Any extra information that might be useful in the debugging process.

Please see details about the transaction here

https://twitter.com/cooper_5e/status/951892184478994434

**Comment by justinvforvendetta** [comment]
yeah we're working on this with the pools already

**Comment by jderwish** [comment]
@justinvforvendetta  Thank you, let me know if you need any help from me.

**Comment by Pele51** [comment]
I have the same problem i just send all my coins from the electrum wallet to the QT Wallet, both wallets have zero confirmation, its 3 hours ago now and my balance still shows unconfirmed, one hour ago my balance was confirmed for about 10 sec. and then unconfirmed again

**Comment by jderwish** [comment]
@Pele51 Please confirm that we are talking about same problem. The issue here is that the stealth-transaction is successful but the recipient is not getting confirmed. If you have send coins from a wallet to another and the balances are showing 0, perhaps a sync issue or something else.

**Comment by jderwish** [comment]
@ronadair I hope your issue is that as a sender the stealth-transaction is successful but as recipient it is pending unconfirm? if so, you are correct - issue is the same irrelevant of the OS otherwise it could be a sync or something else.

**Comment by jderwish** [comment]
@justinvforvendetta  Could you please provide an update?

**Comment by Pele51** [comment]
Yes im very sorry i send from a wallet to another, coins shows up but not confirmed yet, both wallet are fully synched, i send from electrum to qt wallet

**Comment by Botislav** [comment]
@justinvforvendetta is it possible to estimate how fast pools will be updated.

**Comment by justinvforvendetta** [comment]
we're working on an update specifically for pools because right now they have been updating one at a time, get an orphan and then revert, so we're making an update for them that will let them get blocks and switch to stealth at the same time

**Comment by ronadair** [comment]
@jderwish Thank you, I received confirmation (screenshot) from a friend which shows the coins in his wallet, but they are unconfirmed. So it is the same as you describe (I was led to believe there was no change in the wallet after it finished updating the blockchain, but he must not have seen the unconfirmed txs).

**Comment by jderwish** [comment]
@ronadair Thx, so coins are not lost, just waiting for pools to be upgraded and it should get confirmed. 👍  standby

**Comment by timglenn123** [comment]
I have the same issue on OSX 4.0.1  stealth transaction unconfirmed.  but also seeing 1500 confirmations on the block explorer. but will wait until the pools are upgraded.

**Comment by justinvforvendetta** [comment]
yeah they are all set to switch to processing stealth sometime monday

**Comment by jderwish** [comment]
@justinvforvendetta  any update on the mining nodes upgrades? users still not seeing their transactions confirmed. I have started my wallet to sync from zero so it is still not fully sync.

**Comment by xtrc** [comment]
Looking forward to the latest update concerning this matter.

**Comment by xtrc** [comment]
Looking forward to the latest update concerning this issue.

**Comment by ronadair** [comment]
Thanks @deliriumv. I just checked again, and literally as I was looking over the status on both stealth transactions I sent a few days back, they both changed from 0 confirmations up to 5 confirmations, then finally 6. 

BUT — then when I went back to the "Show General Overview of Wallet" screen to see how that was all reflected there and double clicked on the transactions in the right column, it took me back to the "Browse Transaction History" screen and showed them as now fully unconfirmed again (0/unconfirmed). Then they went to 1 conf, then back to 0. 

An update after seeing the ? icon for days is promising, but we're still seeing strange behavior happening for sure....

**Comment by justinvforvendetta** [comment]
we need more hashpower on suprnova (myr groestl), idcray (myr-groestl) and zpool (x17) 

we're almost at enough hashpower for stealth tx's to complete.

**Comment by ronadair** [comment]
Thanks @justinvforvendetta, looks like they're confirmed again (for now). I have screenshots tracking the back and forth, but it sounds like the rocket is almost airborne. Let me know if I can test/share anything else, otherwise I'll check with the receiver in the morning to verify it all looks clean on their side as well.

**Comment by ronadair** [comment]
Very satisfying to see stealth/wraith tx's happening from beginning to end, though. Great work.

**Comment by alexkenley** [comment]
I just switched my rig from yiimpi X17 to Zpool X17 (ccminer-x64.exe -a x17 -i 18 -o stratum+tcp://mine.zpool.ca:3737 -u DNTbdwzDmspyQzA2Pa242i9FBCrJsqVt9L.-p c=XVG) and it's showing something aboout UNO coin - is this right??
![image](https://user-images.githubusercontent.com/17103215/35036498-ab1c1958-fbc8-11e7-9718-2f0a6edee6d4.png)

**Comment by alexkenley** [comment]
damn thank you. I ashamedly deleted my post. salute!

**Comment by xtrc** [comment]
This block is still showing unconfirmed:
https://verge-blockchain.info/block/6dfac3002cb0dce0618ff79755e7ac7433dbe5831e1c679c0a5be3109cf4863e

**Comment by jderwish** [comment]
@justinvforvendetta  any update? when stealth transactions are going to be processed?

**Comment by ronadair** [comment]
Also interested in an update.

**Comment by justinvforvendetta** [comment]
fork was successful

**Comment by timglenn123** [comment]
just an fyi..  my stealth transactions confirmed after the fork!
