### ISSUE TITLE
Verged compile issue on linux

### ISSUE THREAD

**Issue by Kiefff** [vergecurrency/VERGE#465]
Unable to compile VERGE on ubuntu server. 

:~/VERGE$ make
Making all in tor
make[1]: Entering directory '/home/skynet/VERGE/tor'
make  all-am
make[2]: Entering directory '/home/skynet/VERGE/tor'
make[2]: Leaving directory '/home/skynet/VERGE/tor'
make[1]: Leaving directory '/home/skynet/VERGE/tor'
Making all in src
make[1]: Entering directory '/home/skynet/VERGE/src'
  CXX      libbitcoin_server_a-bitcoinrpc.o
In file included from /usr/include/openssl/bn.h:33:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp: In constructor ‘boost::asio::ssl::detail::openssl_init_base::do_init::do_init()’:
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:43:23: error: expected id-expression before ‘(’ token
     mutexes_.resize(::CRYPTO_num_locks());
                       ^
In file included from /usr/include/boost/asio/ssl/detail/openssl_init.hpp:100:0,
                 from /usr/include/boost/asio/ssl/context.hpp:29,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:46:66: error: expected id-expression before ‘;’ token
     ::CRYPTO_set_locking_callback(&do_init::openssl_locking_func);
                                                                  ^
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:47:56: error: expected id-expression before ‘;’ token
     ::CRYPTO_set_id_callback(&do_init::openssl_id_func);
                                                        ^
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp: In destructor ‘boost::asio::ssl::detail::openssl_init_base::do_init::~do_init()’:
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:64:32: error: expected id-expression before ‘;’ token
     ::CRYPTO_set_id_callback(0);
                                ^
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:65:37: error: expected id-expression before ‘;’ token
     ::CRYPTO_set_locking_callback(0);
                                     ^
In file included from /usr/include/openssl/engine.h:30:0,
                 from /usr/include/boost/asio/ssl/detail/openssl_types.hpp:22,
                 from /usr/include/boost/asio/ssl/context_base.hpp:19,
                 from /usr/include/boost/asio/ssl/context.hpp:27,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:66:7: error: expected id-expression before ‘while’
     ::ERR_free_strings();
       ^
In file included from /usr/include/openssl/x509.h:23:0,
                 from /usr/include/openssl/ssl.h:50,
                 from /usr/include/boost/asio/ssl/detail/openssl_types.hpp:20,
                 from /usr/include/boost/asio/ssl/context_base.hpp:19,
                 from /usr/include/boost/asio/ssl/context.hpp:27,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:72:7: error: expected id-expression before ‘while’
     ::EVP_cleanup();
       ^
In file included from /usr/include/openssl/bn.h:33:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:73:7: error: expected id-expression before ‘while’
     ::CRYPTO_cleanup_all_ex_data();
       ^
In file included from /usr/include/boost/asio/ssl/detail/openssl_types.hpp:22:0,
                 from /usr/include/boost/asio/ssl/context_base.hpp:19,
                 from /usr/include/boost/asio/ssl/context.hpp:27,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/detail/impl/openssl_init.ipp:76:7: error: expected id-expression before ‘while’
     ::ENGINE_cleanup();
       ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp: In constructor ‘boost::asio::ssl::context::context(boost::asio::ssl::context_base::method)’:
/usr/include/boost/asio/ssl/impl/context.ipp:83:29: error: ‘::SSLv2_method’ has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp:86:29: error: ‘::SSLv2_client_method’ has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_client_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp:89:29: error: ‘::SSLv2_server_method’ has not been declared
     handle_ = ::SSL_CTX_new(::SSLv2_server_method());
                             ^
/usr/include/boost/asio/ssl/impl/context.ipp: In destructor ‘boost::asio::ssl::context::~context()’:
/usr/include/boost/asio/ssl/impl/context.ipp:208:16: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
     if (handle_->default_passwd_callback_userdata)
                ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:212:20: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
             handle_->default_passwd_callback_userdata);
                    ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:214:14: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
       handle_->default_passwd_callback_userdata = 0;
              ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp: In member function ‘boost::system::error_code boost::asio::ssl::context::use_certificate_chain(const boost::asio::const_buffer&, boost::system::error_code&)’:
/usr/include/boost/asio/ssl/impl/context.ipp:551:18: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
           handle_->default_passwd_callback,
                  ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:552:18: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
           handle_->default_passwd_callback_userdata) };
                  ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:569:16: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
     if (handle_->extra_certs)
                ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:571:33: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
       ::sk_X509_pop_free(handle_->extra_certs, X509_free);
                                 ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:572:14: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
       handle_->extra_certs = 0;
              ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:576:18: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
           handle_->default_passwd_callback,
                  ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:577:18: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
           handle_->default_passwd_callback_userdata))
                  ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp: In member function ‘boost::system::error_code boost::asio::ssl::context::use_private_key(const boost::asio::const_buffer&, boost::asio::ssl::context_base::file_format, boost::system::error_code&)’:
/usr/include/boost/asio/ssl/impl/context.ipp:653:28: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
           bio.p, 0, handle_->default_passwd_callback,
                            ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:654:18: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
           handle_->default_passwd_callback_userdata);
                  ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp: In member function ‘boost::system::error_code boost::asio::ssl::context::use_rsa_private_key(const boost::asio::const_buffer&, boost::asio::ssl::context_base::file_format, boost::system::error_code&)’:
/usr/include/boost/asio/ssl/impl/context.ipp:712:28: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
           bio.p, 0, handle_->default_passwd_callback,
                            ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:713:18: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
           handle_->default_passwd_callback_userdata);
                  ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp: In member function ‘boost::system::error_code boost::asio::ssl::context::do_set_password_callback(boost::asio::ssl::detail::password_callback_base*, boost::system::error_code&)’:
/usr/include/boost/asio/ssl/impl/context.ipp:932:14: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
   if (handle_->default_passwd_callback_userdata)
              ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:934:16: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
         handle_->default_passwd_callback_userdata);
                ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/boost/asio/ssl/context.hpp:786:0,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/impl/context.ipp:936:10: error: invalid use of incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
   handle_->default_passwd_callback_userdata = callback;
          ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:145:16: note: forward declaration of ‘SSL_CTX {aka struct ssl_ctx_st}’
 typedef struct ssl_ctx_st SSL_CTX;
                ^
In file included from /usr/include/openssl/engine.h:30:0,
                 from /usr/include/boost/asio/ssl/detail/openssl_types.hpp:22,
                 from /usr/include/boost/asio/ssl/context_base.hpp:19,
                 from /usr/include/boost/asio/ssl/context.hpp:27,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/detail/impl/engine.ipp: In member function ‘const boost::system::error_code& boost::asio::ssl::detail::engine::map_error_code(boost::system::error_code&) const’:
/usr/include/boost/asio/ssl/detail/impl/engine.ipp:207:9: error: ‘SSL_R_SHORT_READ’ was not declared in this scope
         ERR_PACK(ERR_LIB_SSL, 0, SSL_R_SHORT_READ),
         ^
In file included from /usr/include/boost/asio/ssl/detail/engine.hpp:163:0,
                 from /usr/include/boost/asio/ssl/detail/buffered_handshake_op.hpp:21,
                 from /usr/include/boost/asio/ssl/stream.hpp:29,
                 from /usr/include/boost/asio/ssl.hpp:24,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/detail/impl/engine.ipp:214:11: error: invalid use of incomplete type ‘SSL {aka struct ssl_st}’
   if (ssl_->version == SSL2_VERSION)
           ^
In file included from /usr/include/openssl/bn.h:32:0,
                 from bignum.h:10,
                 from main.h:8,
                 from coincontrol.h:4,
                 from wallet.h:13,
                 from init.h:8,
                 from bitcoinrpc.cpp:6:
/usr/include/openssl/ossl_typ.h:144:16: note: forward declaration of ‘SSL {aka struct ssl_st}’
 typedef struct ssl_st SSL;
                ^
In file included from /usr/include/openssl/engine.h:30:0,
                 from /usr/include/boost/asio/ssl/detail/openssl_types.hpp:22,
                 from /usr/include/boost/asio/ssl/context_base.hpp:19,
                 from /usr/include/boost/asio/ssl/context.hpp:27,
                 from /usr/include/boost/asio/ssl.hpp:19,
                 from bitcoinrpc.cpp:24:
/usr/include/boost/asio/ssl/detail/impl/engine.ipp:221:9: error: ‘SSL_R_SHORT_READ’ was not declared in this scope
         ERR_PACK(ERR_LIB_SSL, 0, SSL_R_SHORT_READ),
         ^
Makefile:2474: recipe for target 'libbitcoin_server_a-bitcoinrpc.o' failed

**Comment by justinvforvendetta** [comment]
can you tell us what version of boost and openssl you have?

**Comment by Max-Meldrum** [comment]
I get this issue when i run openssl 1.1.0g, so I went back to 1.0.2g and also updated libssl-dev to 1.0.2.

`apt-cache policy openssl`
`apt-cache policy libssl-dev`

And you will be able to find which other versions you can install etc..

**Comment by Kiefff** [comment]
`skynet@cyberdine:~/wallets/verge$ apt-cache policy openssl
openssl:
  Installed: 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.2g-1ubuntu4.10 500
        500 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     1.0.2g-1ubuntu4 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
skynet@cyberdine:~/wallets/verge$  apt-cache policy libssl-dev
libssl-dev:
  Installed: 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.2g-1ubuntu4.10 500
        500 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     1.0.2g-1ubuntu4 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages`

**Comment by Kiefff** [comment]
skynet@cyberdine:~/wallets/verge$ apt-cache policy openssl
openssl:
  Installed: 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.2g-1ubuntu4.10 500
        500 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     1.0.2g-1ubuntu4 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
skynet@cyberdine:~/wallets/verge$  apt-cache policy libssl-dev
libssl-dev:
  Installed: 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
  Candidate: 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1
  Version table:
 *** 1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.2g-1ubuntu4.10 500
        500 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
     1.0.2g-1ubuntu4 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

**Comment by Max-Meldrum** [comment]
@Kiefff 
I had some issues in start with boost and openssl versions. But after installing openssl 1.0.2g and boost 1.58.0, it worked fine. So if you still have problems, it might be worth trying it.

**Comment by michpiatek** [comment]
I think boost <1.62 doesn't compile with openssl1.1 (https://svn.boost.org/trac10/ticket/12238). On my Fedora with boost 1.64 and openssl1.1.0g everything compiles just fine. I'm closing, just use openssl 1.0.2 if boost below 1.62
