### ISSUE TITLE
I'm about to lose 1m VERGE

### ISSUE THREAD

**Issue by mo0vjke** [vergecurrency/VERGE#47]
Hi,
My wallet.dat is corrupted, I'm trying to retrieve it, but it fails!
Also I get this message VERGE: Error initializing database environment /root/.VERGE! To recover, BACKUP THAT DIRECTORY, then remove everything from it except for wallet.dat.

I've tried to delete all blockchain and then synced again, but got this message again.
And after starting with -salvagewallet, the client has deleted my wallet.dat file.

Are you guys planning to update the client to the latest version???

**Comment by vergecurrency** [comment]
im not sure what sort of update you think would help your situation. if salvage failed then im not sure what you can do. it sounds like the wallet was forced to quit at some point.

**Comment by vergecurrency** [comment]
are  you sure it didnt make a backup copy of the wallet.dat in your .VERGE data directory?

**Comment by mo0vjke** [comment]
Yes, it backup the wallet.dat when the wallet has been started without -salvagewallet flag.
Once I try to set this flag, it remove my wallet.dat file at all. I hope that I've backup the wallet to another device, but not sure( Will be able to check next week...

**Comment by vergecurrency** [comment]
@mo0vjke im sorry to hear your wallet.dat is corrupted, but there is no update to our code we can do to fix your issue. when salvaging does not work, it backs up the wallet.dat and creates a new one. usually the only thing that can do this is force stopping the client, or abruptly cutting off the power to the disk while the client is running. i hope you find another copy of it somewhere. always back up the wallet!
