### ISSUE TITLE
Don't responding

### ISSUE THREAD

**Issue by teodoradr** [vergecurrency/VERGE#470]
Hi,

I get stuck, I do not know why. I followed all the instructions with blockchain.py and brew boost .This wallet stay with loading index , then don't responding and I need to force quit .
![screenshot at jan 13 17-06-08](https://user-images.githubusercontent.com/35401833/34907409-b599845a-f886-11e7-89cd-4bcd89eb39ca.png)

**Comment by deliriumv** [comment]
You need to leave it for a while, it took 15-20 minutes on my first load and takes 5 minutes to load the index on subsequent loads. (I'm running on the Linux version)

**Comment by teodoradr** [comment]
I understand now , but this out of sync is normal ?

**Comment by teodoradr** [comment]
Ok , thank you !

**Comment by marpme** [comment]
Hey @teodoradr,

please consider closing your issue, since it seems that your problem has been solved already.
Thank you, 

marpme
