### ISSUE TITLE
Building / contributing docs need to be clearer.

### ISSUE THREAD

**Issue by AjkP** [vergecurrency/VERGE#471]
# Issue Template

## Context

I was trying to build Verge locally to see the product and possibly get involved in it's development. I found it extremely hard and have spent more than a few hrs trying to get it to work locally.

## User Story:

* "I'm submitting a ... "
  - [x] feature request

## Expected Behavior

I get a clean step by step basis on how to build the app and how to contribute.

## Current Behavior

There's no CONTRIBUTING.md and step by step explanations are harder to follow. 

For example under `Developer Notes` that are only specific to linux environments.
MAC OS X steps did not work flawlessly for me.

## Possible Solution

1. Rewrite the ReadMe to be easier to read, possibly re-arranging the `Building from source` part.
2. Create a CONTRIBUTING.md that clearly explains how to contribute and where the documentation is located. (Could take a look at other projects for how they're structured for this)

Im down to start working on this btw if I get some help for where things are located and how to get going with local development.

**Comment by Max-Meldrum** [comment]
Currently the main README has some outdated information which gets removed in #430 . So for compiling, check the links under "Building from source". But, yes, things can be improved.

Did you follow the OS X steps in "Building from source" or the one in the readme?
What issue did you encounter?

**Comment by AjkP** [comment]
I tried both (I think part of the ReadMe is the same as the `Building from source`.

`./building/mac/build.sh` part gives me at the end:

```
checking for dynamic linked boost test... yes
checking for LIBEVENT... no
configure: error: libevent not found
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by Max-Meldrum** [comment]
Yeah, seems that it needs some updating. Unfortunately, I don't have any access to an OS X system. 
But for the error you are seeing, try installing libevent with `brew install libevent`

**Comment by justinvforvendetta** [comment]
yeah libevent should have been installed during the process

**Comment by AjkP** [comment]
> Yeah, seems that it needs some updating. Unfortunately, I don't have any access to an OS X system. But for the error you are seeing, try installing libevent with brew install libevent

Yeah I suspected such. Alright, i'll take a look at why it wasn't installed by the previous commands and update.
