### ISSUE TITLE
Electrum XVG 2.4.1 Transaction pending, 0 confirmations

### ISSUE THREAD

**Issue by paizon217** [vergecurrency/VERGE#476]
I sent 3300XVG from my Electrum to my Cryptopia's balance. It has been "pending", unconfirmed for over 5hrs. https://verge-blockchain.info/tx/3c3aac6627733dbde10429f8f45ce6a76405165605687ac169c1be83cbcda0eb

**Comment by mcguire1968** [comment]
I am having the exact same problem. Sorry I don't have an answer but I didn't want to create a redundant thread.

**Comment by davodavo1232** [comment]
I am having the same problem, its been about 50 hours for 2 of the 3 transactions. Any help would be appreciated.

**Comment by davodavo1232** [comment]
XVG txid: 8dba209534402627dbe1e5b3f59b132576d0822cadf3c03513f059bfc4cca2c0

**Comment by abc2k17** [comment]
anyone making progress?
anyone tried recreating wallet?

same problem here, transactionid: 103af0ddff4599f00e7e92ccc7c18ae8fd28ad01a45375a3decab56ed98944fd

**Comment by benammann** [comment]
having this problem with 3 transactions

**Comment by daveobri** [comment]
Similar problem here, sent via Electrum to Binance on 12th Jan and 0 confirmations and still pending.
txid : 57497c058c440aa63feccc9e567e25ff4396e80a0ede1d5c630849e333bc9cf2

**Comment by davodavo1232** [comment]
no progress peeps, ive tried recovering, tried importing keys into core. Not having any luck. Let me know if any of you do.

**Comment by davodavo1232** [comment]
There is a post on twitter about upgrading electrum servers so i would just wait and see, have faith that it will be sorted.

**Comment by davodavo1232** [comment]
I think it has something to do with the transaction fees, i put through another transaction from electrum to verge core and it went through fine, although i put the trans fee to 2 xvg. I notice on everyone that has had the problem there trans fee is below 1 xvg.

**Comment by paizon217** [comment]
I guess it's about transaction fees, yeah. Still, do you guys know if the devs are working on it? it's crazy.

**Comment by EXAIYU** [comment]
Similar problem here...

 txid: 6c20024c4127d3d8bed7c19b2925176f063d50ffa4d6b0d916c02697d879bf5f

what should i do?

**Comment by satirio** [comment]
Same here:

https://verge-blockchain.info/tx/9391fae429af69be9f9496cc1948c7bb266f291e9e8bc8ced6389fa3204572e7

If you find a solution, let me know. I will do the same. =)

**Comment by benammann** [comment]
@satiro look in #490

i‘ve written a small tutorial how to fix this

**Comment by EXAIYU** [comment]
https://imgur.com/a/gca73

Invalid private key (code -5)

what should i do :(?

**Comment by MynxGithub** [comment]
I'm also getting this issue.

**Comment by jrsikors** [comment]
anyone still having issues with these after the hard fork?

**Comment by jrsikors** [comment]
@justinvforvendetta  close this one out plz

**Comment by Technophant** [comment]
@EXAIYU
> https://imgur.com/a/gca73 Invalid private key (code -5) what should i do :(?

That was smart of you to black out the key, but I can still see enough of it to tell that you inputed an address that started with D instead of a private key which is a longer hex addresses.

**Comment by jrsikors** [comment]
@justinvforvendetta nudge

**Comment by jrsikors** [comment]
closing issue -- please re-open or open new issue if this is still a problem with the latest release

**Comment by jrsikors** [comment]
check out the wiki and follow the steps for no connections..


If you are using the "Regular clearnet electrum":
https://github.com/vergecurrency/VERGE/wiki/Electrum-XVG-FAQ-%26-Common-Issues#no-connections--not-connected

If you are using the Tor based electrum:
https://github.com/vergecurrency/VERGE/wiki/Electrum-XVG-Tor-FAQ-%26-Common-Issues#no-connections--not-connected
