### ISSUE TITLE
Invalid Fee bug, Endless block header retrieval, and Potential Compromised Node Server

### ISSUE THREAD

**Issue by Nori-MD** [vergecurrency/VERGE#477]
I've been having issues with the Electrum-XVG wallet now for 7 days.  Been trying to move coins from that wallet to the verge-qt 4.0.1 wallet.  There are three issues pertaining to the "Invalid Fee" bug, endlessly stuck at "retrieving block headers", and potential malware.  Can't I please get some help here?

This is for Electrum-XVG 2.4.1 of Win 10 64 bit.  This is a bug report, and I will cover these three issues.

(1) The "invalid fee" bug.  Again, I am trying to move XVG coins from the Electrum-XVG wallet to the new Verge-QT 4.0.1 wallet.  I type in the addressee, the amount to be transferred, click send, then this popup shows up.  Somebody earlier a few months ago apparently found a way around that bug but the description wasn't clear.

![verge-invalid-fee2](https://user-images.githubusercontent.com/35430797/34919491-146e06f2-f933-11e7-84f5-acfe2430cc11.png)

(2) Also, the wallet is constantly stuck at "Getting block headers from X nodes" (X ranges from 1 to 5).  It's been stuck like this for a week now, with computer on 24/7.  I'm assuming the block headers need to be fully downloaded before I'm able to make any transactions, yes?  Or no?

![verge-servers](https://user-images.githubusercontent.com/35430797/34919284-2e1bb422-f92f-11e7-8919-ce3ded0cc51e.png)

(3) Lastly, Malwarebytes is flagging server electrum-xvg.stream as malicious.  I don't know if this is a false positive but we're talking about digital coins where security is of utmost importance.  I've blocked that site, assuming the others are mirrors of each other.  What concerns me is that I get the pop-up ONLY for that specific address, electrum-xvg.stream, and not with the others.  What is going on here?

![verge-malicious](https://user-images.githubusercontent.com/35430797/34919291-5acacfda-f92f-11e7-93fb-94c1617a31ea.png)

Mainly, I need help transferring coins out of Electrum-XVG and into the new verge-qt 4.0.1.  This has been very frustrating and time-consuming.

As someone else said, these are "confidence-killers" in the coin, and there are competitors to the coin (Monero, Zcash partnered up with JP Morgan).  If we want this coin to succeed over the others, these issues need to be addressed ASAP because competition moves fast.  No frustrations, no fears of compromised node servers, etc.

* Verge Release: Electrum-XVG 2.4.1
* CPU: Intel i7 6950X Extreme
* GPU: nVidia Titan X
* RAM: 128GB
* OS: Win10 Professional 64bit

The file log.txt is empty and so I am not attaching it.

**Comment by justinvforvendetta** [comment]
we aren't going to be supporting the non-tor electrum wallet anymore after this week (we will release one more binary)

**Comment by justinvforvendetta** [comment]
but try restoring your wallet in the electrum tor wallet using your seedphrase

**Comment by Nori-MD** [comment]
Thanks Justin

**Comment by radeksalomon** [comment]
Electrum wallet is still the main wallet on the website. If you want to limit its support, you should mention it on the web or pull it from the web. Now the web is misleading and pushing people to the electrum wallet.

**Comment by justinvforvendetta** [comment]
yeah we will this week. @nori-md what is the compromised thing you're talking about? that the site is flagged? definitely a false positive lol

**Comment by Nori-MD** [comment]
"Potentially compromised thing", meaning the popup window by Malwarebytes.  Was thinking of false positive but since it popped up only for the electrum-xvg.stream address/server (please look at screenshot above in my opening post) and not the others, I became concerned and wanted to ask about it here and see if anybody else had seen similar.  Something like that makes one suspect that specific box got hacked - network security professionals would agree.  Unfortunately, Malwarebytes did not give any more info for me to pass to you here.

Public confidence about the currency being secure will make or break the project.  Nobody wants to be "that guy" that got scammed with the hardware Ledger Nano S last week.

**Comment by Nori-MD** [comment]
Ok here's my report on your recommendations on using the Tor variant of Electrum XVG:

1.  Downloaded and installed Tor browser (needs to be running when Tor version of Electrum XVG wallet is running)
2.  Attempted to restore using seed, and entered a password to keep wallet encrypted
3.  Got "You are not connected" error, so then made following changes based on comments from https://github.com/vergecurrency/electrum-xvg-tor/issues/13
	a. Run Tor browser (because I used Tor)
	b. In the network setting, put t4c6rftkx673mlqv.onion into the server, the port is 50001
	c. Don't check Use SSL
	d. Proxy SOCK5 because of Tor browser, localhost, and 9150 for the port.
4. Once wallet software connected with new/current Tor server address, my wallet was restored within a minute and stayed connected.
5. Next step was to transfer coins from Electrum XVG (Tor) wallet to VERGE-qt - after inputting a wallet address from the QT wallet, I got "invalid address" error 
6. Created a new stealth address in VERGE-qt but when I entered that address into Electrum-XVG (Tor), I got a pop up saying "Invalid lines found"
7. Tried same address from two lines up:  got "Invalid Fee" error again.  Weird... different error.
Created new non-stealth address, and tried using:  "Invalid Fee" again.

So I'm still stuck.

This time there were Python error entries in the log that may or may not help (I've removed the redundant traceback errors):

Traceback (most recent call last):
  File "E:\verge\electrum-xvg-tor\gui\qt\main_window.py", line 990, in <lambda>
  File "E:\verge\electrum-xvg-tor\gui\qt\main_window.py", line 1062, in update_fee
  File "E:\verge\electrum-xvg-tor\gui\qt\main_window.py", line 1543, in get_coins
  File "C:\Program Files\electrum-xvg-tor-win-amd64\lib\wallet.py", line 610, in get_spendable_coins
    c = self.get_addr_utxo(addr)
  File "C:\Program Files\electrum-xvg-tor-win-amd64\lib\wallet.py", line 576, in get_addr_utxo
    coins.pop(txi)
KeyError: u'5de5a3cb18ec0c8f08d7dbdb4af3b59f4df15553b652b6f530e471d239820e38:218'
db4af3b59f4df15553b652b6f530e471d239820e38:218'

Traceback (most recent call last):
  File "E:\verge\electrum-xvg-tor\gui\qt\main_window.py", line 989, in <lambda>
  File "E:\verge\electrum-xvg-tor\gui\qt\main_window.py", line 1062, in update_fee
  File "E:\verge\electrum-xvg-tor\gui\qt\main_window.py", line 1543, in get_coins
  File "C:\Program Files\electrum-xvg-tor-win-amd64\lib\wallet.py", line 610, in get_spendable_coins
    c = self.get_addr_utxo(addr)
  File "C:\Program Files\electrum-xvg-tor-win-amd64\lib\wallet.py", line 576, in get_addr_utxo
    coins.pop(txi)
KeyError: u'5de5a3cb18ec0c8f08d7dbdb4af3b59f4df15553b652b6f530e471d239820e38:218'


Traceback (most recent call last):
  File "E:\verge\electrum-xvg-tor\gui\qt\main_window.py", line 77, in onPress
  File "E:\verge\electrum-xvg-tor\gui\qt\main_window.py", line 2657, in settings_dialog
ValueError: 'dvzs4zoxkg6z43dd.onion' is not in list
Traceback (most recent call last):
  File "E:\verge\electrum-xvg-tor\gui\qt\main_window.py", line 77, in onPress
  File "E:\verge\electrum-xvg-tor\gui\qt\main_window.py", line 2657, in settings_dialog
ValueError: 'dvzs4zoxkg6z43dd.onion' is not in list


I hope that helps.  Thanks again Justin.

**Comment by Nori-MD** [comment]
Forgot to include screenshot of "invalid line" screen when I tried using a stealth address generated by QT:

![electrum-xvg-tor-invalid](https://user-images.githubusercontent.com/35430797/34920816-2298f5ca-f947-11e7-8113-bcab6b03a7ea.png)

**Comment by Nori-MD** [comment]
Justin - I've done a little digging around for us all on the issue of the security alert by Malwarebytes (MWB).  Unless the machine at electrum-xvg.stream is truly hacked with malware sniffing all the traffic packets (worst case scenario, but low probability), things are ok.

It appears that server was flagged purely due its TLD (*.stream).  According to MWB at:
https://forums.malwarebytes.com/topic/200068-please-read-before-posting-fp/

**_"These gTLDs are blocked because the ratio of bad to good domains may be higher than average, indicating that the registry could do a better job of enforcing policies and shunning abusers.).   Currently we are blocking the following gTLDs -

.accountant
.bid
.download
.faith
.link
.loan
.men
.reisen
.review
.science
.stream
.study
.wang"_**

(The wang one is funny)

We don't know how many people have already seen similar warnings and stopped supporting XVG after deeming it unsafe.  Damage control can be nipped in the bud by something like this in an easily found part of the FAQ file:

"A couple new node servers were brought online in the lattter part of 2017 due to overwhelming, unprecedented numbers of network connections causing intermittent connection dropouts between the wallet client and servers.  The top level domain (TLD) of "stream" was picked because of its low cost, but later found to be blacklisted by various network security software such as Malwarebytes, thereby causing security alerts and pop-ups.  The server at electrum-xvg.stream is to the best of our knowledge, secured and safe."

So that takes care of one of three issues, and the block header issue was solved by your suggestion of using the TOR variant of the electrum-xvg wallet client.

**Comment by Nori-MD** [comment]
@justinvforvendetta That leaves the 3rd of 3 issues, which is being able to transfer coins between Electrum-XVG (TOR or no TOR) and elsewhere such as QT.  I still can't do that.  Any ideas what I could do based on my post, 2 posts back (the one with logfile and findings)?

**Comment by justinvforvendetta** [comment]
electrum servers on our end are updating. hopefully community members who run electrum servers are doing the same.

**Comment by Nori-MD** [comment]
Hi @justinvforvendetta, one of my boxes is an Ubuntu box that I can compile the server and run, if you'd think it'd help.  Disk space, RAM, CPU power, network bandwith won't be an issue.

I didn't mean this update to be this lengthy but wanted to be thorough (yet concise with each point), anticipating follow-up questions from you.

Update: I'm still trying to figure out how to migrate my coins on the soon-to-be-unsupported Electrum-XVG wallet, over to VERGE-qt.  Still no luck - still get "Invalid Fee".  I'm pretty sure I'm not the only person with this problem.  I'm including four screenshots with a bit of commentary for each, hopefully giving you ideas on what is going on:

First, this is a screenshot of overall history.  It's composed of quite a bit of little mining deposits.  I've since learned that the Electrum wallet (in general, not just the Verge fork - this isn't a problem created by Verge) isn't the best for mining deposits, which is another reason to migrate away from it.

![invalid fee 01](https://user-images.githubusercontent.com/35430797/35179333-3f8b57a4-fd66-11e7-975d-d114982e35b3.png)

Second screenshot.  There's basically four receiving addresses that have been used. If I try to send a smaller amount, whether just 10 XVG or 50, I still get "Invalid Fee".  Question: should I be able to do a single transfer of the wallet's contents, or does it need to be done by each of the four receiving addresses using the "send from" function - i.e. 1000 XVG for the topmost addresses, then ~500 for the next one, and so forth?

![invalid fee 02](https://user-images.githubusercontent.com/35430797/35179370-03917f2a-fd67-11e7-9938-886f51c9ef9a.png)

Third screenshot.  Just for review - basically same as above.  The "Invalid Fee" bug.  When I switch to manual fee setting, when I enter a fee, it's colored blue (but not the number for transfer amount).  I don't get the "Invalid Fee" bug when attempting to send XVG coins to the VERGE-qt wallet, but simply, nothing happens.  No popup asking for password, etc.

![verge-invalid-fee3](https://user-images.githubusercontent.com/35430797/35179402-b5b0168a-fd67-11e7-87a6-15b56e11d1ae.png)

Four and last screenshot.  The network window, to show you which servers are being used.  The servers by community people aren't there yet, I'm guessing they will start showing up in a few days if not sooner.  However, the intermittent connection dropouts are much, much less now.  Question:  Does the endless "Getting block headers from X nodes" have anything to do with "Invalid Fee"?  I'd think the block headers file should be completely synced before any attempts at transferring (just like if we were syncing with a full blockchain), but wanted to ask to make sure in case I'm wrong.  Then again, Electrum gives no indication whether it's finished downloading the block headers and simply standing by for new headers, so I never know if it's finished with the block headers or not.

![verge-invalid-fee4](https://user-images.githubusercontent.com/35430797/35179449-8d8942f2-fd68-11e7-974b-1cd1c718fa71.png)

Overall, what do you suspect could be going on?  I suspect the "many" transactions from mining could be a possible cause of the "Invalid Fee" bug from what I've been searching (again, just with the Electrum wallet, not the VERGE-qt wallet).  I've been finding so many different posts by people who appear to have solved the issue, whether by sweeping private keys, or sending messages to be verified, that it's confusing what to do now.

Occam's Razor would say that we simply need more working servers but you're in a better position to guess/suggest what's the next possible step.  I'm sure I'm not the only person with XVG coins stuck in the Electrum wallet.  I hope those with the same problem but less technically inclined have stayed strong and not given up on XVG!  Thanks again Justin!

**Comment by justinvforvendetta** [comment]
should be fine now.
