### ISSUE TITLE
XVG STUCK IN THE BLOCKCHAIN

### ISSUE THREAD

**Issue by pchamb1998** [vergecurrency/VERGE#478]
# Issue Template

## Prerequisites

* [ Yes] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ x] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [x ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
did you download the chain or sync it yourself from 0?

**Comment by pchamb1998** [comment]
I installed the chain but it still started the process from 0.. It took almost 3 days but It did sync fully. It’s up to sync. I can see coins in the block chain explorer but they won’t send to my wallet.

**Comment by justinvforvendetta** [comment]
send a link to the block explorer transaction. also, you didn't lock your wallet did you? where did you send them from?

**Comment by pchamb1998** [comment]
My wallet is not locked. My computer is updating but as soon as It is finished I will send you a link to the block transaction.

**Comment by pchamb1998** [comment]
I sent the funds from Bitterex to my Verge Wallet

**Comment by justinvforvendetta** [comment]
did you ever lock your wallet?

**Comment by pchamb1998** [comment]
No, I never locked it. So, I tried updating to 4.0 and I did.. It is saying contact my developer that my version may not be supported. My Mac is up to date? I can’t even access my wallet because of it..

**Comment by pchamb1998** [comment]
https://prohashing.com/explorer/Verge/DAzvWKYdXGWqRumKMRkPgkpbLXfXqDy6mp <https://prohashing.com/explorer/Verge/DAzvWKYdXGWqRumKMRkPgkpbLXfXqDy6mp>

**Comment by pchamb1998** [comment]
I fixed the update issue.. The only problem that I have now are the funds hung up in the Blockchain.

**Comment by justinvforvendetta** [comment]
and you see the address you sent to in your wallet receiving tab?

**Comment by pchamb1998** [comment]
Where can I go to verify that the wallet address in my receiving tab matches the wallet address that I sent the funds too.. I copy and pasted so I am almost positive I didn’t get the addresses wrong but I would like to be able to give you a definite yes or no on whether the addresses match.

**Comment by pchamb1998** [comment]
The addresses do not match up.. I have not done anything so I I have no clue why it changed addresses on me?

**Comment by justinvforvendetta** [comment]
ok then that is strange. can you go into the directory where your wallet.dat is and see if there are other wallet files? have you ever force quit the app?

**Comment by pchamb1998** [comment]
Yes, I have had to force quit the app before. Is there anyway to push the funds back into bittrex? That way I can try again with my wallet synced this time?

**Comment by pchamb1998** [comment]
I have tried everything.. Is there anything that can possibly be done?

**Comment by justinvforvendetta** [comment]
can you answer the rest of my questions first?

**Comment by pchamb1998** [comment]
Yes. I have had to force quit the app. No, there isn’t any other wallet.dat files on my computer.

**Comment by pchamb1998** [comment]
Is there anything else that you need to know? If so, I will be glad to provide you with any piece of information that you need. I apologize for worrying you, I am just stressing out about it. Will the transaction ever time out and be returned back? I literally have no trace of the wallet that I sent the funds too. It literally seems as if it disappeared without a trace and generated a new one.

**Comment by blackloaderz** [comment]
Did you try to open your wallet with -rescan option in the target field from the shortcut ?

**Comment by pchamb1998** [comment]
I tried to do that last night.

**Comment by justinvforvendetta** [comment]
and you dont have any wallet/bak files in your data directory?

**Comment by pchamb1998** [comment]
I was not aware that the wallet had to be synced when I first downloaded it.. I sent the funds and shortly after went and read the website. I realized what I had done and then proceeded to install the Blockchain afterwards. I never backed the wallet up because it didn’t have funds in it. I was not aware that it would change addresses on me.. So, I basically have funds sitting in the Blockchain waiting to be sent to an address that I do not have a trace of on my computer.

**Comment by justinvforvendetta** [comment]
it shouldnt change addresses, unless the app is force quit and the wallet becomes corrupted

**Comment by pchamb1998** [comment]
I have had to force quit the app.. The app got hung up on the loading dock and I had to force quit the app in order to try and reopen it.

**Comment by Hilobrain** [comment]
Do you have the private key of your public address you send it to?

**Comment by pchamb1998** [comment]
Does it generate a private key for you?

**Comment by justinvforvendetta** [comment]
it probably wasn't hung up, it was probably loading the block index. since we have a large chain it can take a while

**Comment by pchamb1998** [comment]
I am pretty much screwed huh? Lol..

**Comment by Hilobrain** [comment]
If your create your wallet you get a private key, NEVER lose that key...

**Comment by pchamb1998** [comment]
You get a private key even if the wallet was already created when you opened the app the first time?

**Comment by justinvforvendetta** [comment]
yes when the app first opens, you have a pubkey/privkey pair. if you force the app to quit, like any other application, the database can be corrupted.

**Comment by pchamb1998** [comment]
I obviously have nothing due to me force closing my app (lesson learned).. So, will my funds just sit in Blockchain forever?

**Comment by benammann** [comment]
@pchamb1998 in case you didn't backup your private keys: yes

**Comment by pchamb1998** [comment]
Is their any possibility that Bittrex could retrieve the funds and put them back into my XVG account on Bittrex? Is their anyway you guys could retrieve any of the information that I am missing on the corrupted wallet? I am not as technologically inclined as you guys.. I figured it wouldn’t hurt to ask. If there is anything you guys could do I will be willing to privatly verify any piece of personal information that you guys need in order to verify that I am who I say I am and that I am telling the truth regarding my situation. Thanks guys…...

**Comment by jrsikors** [comment]
It's a harsh / unfortunate lesson sometimes.  Never ever ever send funds to a wallet address that you aren't 100% confident that you:
   1)  Have the file backed up
   2)  Have it encrypted (and triple check you can unencrypt it, lock it, unlock it, lock it, unlock it)
   3)  Have sent a small 1 coin sample transaction to it first to validate it works fine.  The transaction fee, whatever the cost,  is well worth the peace of mind it gives you.
 
Backing up private keys is a lot more dangerous than just backing up an encrypted wallet file... but private keys can be a life saver if you do save them.

Some things I would try to do are serious deep-harddrive-dive recovery programs (I have no idea what's available on a Mac)... something that can recover old/deleted files.  You might get lucky and find the original wallet.dat

From what I've read in this topic -- you HAVE to find the old wallet.dat file , if your current wallet.dat file doesn't have the address listed as a 'receive address', and you don't have your private key.

Good luck and sorry!

**Comment by labson4** [comment]
I have a solution that worked for me.
You can get your fund back to your Bittrex by clicking on the restore wallet option,  
It will need your verge phrase words and your password

**Comment by labson4** [comment]
I have a solution that worked for me.
You can get your fund back to your Bittrex by clicking on the restore wallet option,
It will need your verge phrase words and your password

My own case: I sent fund from my verge through Coinomi wallet to my Verge App address and that is where the problem came,  I didn't see it in the verge app but only on verge - explorer. So I did restore wallet(verge) on my Coinomi and followed simple instructions and my funds is back to  where I want.
Try it out!

**Comment by Positivism** [comment]
Also having this problem. send help
