### ISSUE TITLE
Synchronizing with network... for more than a day.

### ISSUE THREAD

**Issue by AjkP** [vergecurrency/VERGE#480]
## Context

Trying to get started on running Verge wallet.

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x] bug report

## Expected Behavior

I get verge up and running and all synchronized in about a day. (Actually telling from [the size of the blockchain](https://verge-blockchain.com/) being less than 2GBs, I would expect the synching to be done in a few hrs)

## Current Behavior

Verge Client syncing for more than a day.

## Screenshots

<img width="969" alt="screen shot 2018-01-14 at 2 33 21 pm" src="https://user-images.githubusercontent.com/6978905/34921515-67cf1854-f938-11e7-80a8-022d8beed978.png">

## Possible Solution

It would be easier to debug if we had more info for the progress, similar to Bitcoin Core.
I feel like a lot of people will give up if the wallet doesn't sync in a day.

## Steps to Reproduce (for bugs)

* Steps :
1. Install Verge Wallet MacOS version (not electrum) from https://vergecurrency.com/
2. Wait for syncing 24 hrs.

## Your Environment

* Verge Release:
* CPU: 2.5 GHz Intel Core i7
* GPU: NVIDIA GeForce GT 750M 2048 MB
* RAM: 16 GB 1600 MHz DDR3
* OS:
    - [x] I'm using Mac

**Comment by Nori-MD** [comment]
@AjkP Hi, I'm not part of the team but have experienced your same issue when I installed the new QT wallet. 

Did you try the method of downloading the blockchain itself per FAQ at:
https://verge-blockchain.com/

and following the instructions tab (there are differences between Win and Mac)?  It worked well for me.  Once downloaded and installed, I launched the QT wallet, and it was stuck on the load screen for some time while it loaded all the blocks, and then afterwards, took a couple hours to fully complete syncing (network traffic is gridlocked, but you should be used to gridlock from where you live! j/k).

I hope that helps!

**Comment by AjkP** [comment]
@Nori-MD will give that a try. Unfortunately, I can't see that anywhere on the README so it feels hacky to me :/ 

I will give it a try and if it works will propose a change to the README to make that info easily available

**Comment by Nori-MD** [comment]
@AjkP Yeah it's a workaround that we can't expect less techie people to be able to do in the future.  It kinda kills the UX.  I don't envision my grandmother having to go through all these steps to figure things out.  I don't know if coding can be optimized or if there are some inherent limitations in the network protocols inherited from BTC, Doge, etc. (or wherever - unless it was written from scratch).

Nevertheless, making use of TOR, and being given the choice to use it or not is the big innovation here.

I didn't discover this information on the README to be honest - I found out about it on the FAQ itself.  Lots of documentation could be updated in both code and website to reflect current conditions and reduce frustration in getting things to work.  I'd volunteer in a heartbeat but don't know how to go about it...

**Comment by AjkP** [comment]
@Nori-MD I think you can just suggest a "feature" in an issue and make a pull request.

**Comment by Nissemus** [comment]
At the top of the Wallets section on the Verge website it says "If you are not installing an Electrum wallet, you can speed up your install by downloading the Verge blockchain from here." That seems pretty clear to me, but I agree it could be added to the README as well.

**Comment by Max-Meldrum** [comment]
It is already in the README file. Under the section wallets, there is information about it and a link to the site that describes how to do it for win/os X

**Comment by Nissemus** [comment]
Also, the Windows wallet link on the website should go to the installer program.

**Comment by justinvforvendetta** [comment]
we recommend people sync the chain from block 0 themselves, as that is the safest/most reliable method.

**Comment by Nissemus** [comment]
In that case, shouldn't the recommendation to download the blockchain zip file be removed from the website?
