### ISSUE TITLE
After upgrading to Wallet VERGE-QT 4.01 for Mac can't connect with below connection error

### ISSUE THREAD

**Issue by tito0o0o0o0o** [vergecurrency/VERGE#481]
i was using verge QT 4.0 with no problem and totally connected and synched but when i upgraded and replaced the file in my mac applications folder with verge QT 4.1. i stay with 0 network connection with the following errors. (i'm using high seira)

"trying connection kuo62qis2kcc5m7u.onion:21102 lastseen=12.5hrs
SOCKS5 connecting kuo62qis2kcc5m7u.onion
ERROR: Error reading proxy response
trying connection li2ojfszrdpxt3ot.onion:21102 lastseen=19.5hrs
SOCKS5 connecting li2ojfszrdpxt3ot.onion
ERROR: Error reading proxy response
trying connection 36ywkedk74kr7n2k.onion:21102 lastseen=24.2hrs
SOCKS5 connecting 36ywkedk74kr7n2k.onion
ERROR: Error reading proxy response
trying connection j5ddrd666appqfmo.onion:21102 lastseen=9.2hrs
SOCKS5 connecting j5ddrd666appqfmo.onion"

![screen shot 2018-01-13 at 8 04 32 pm](https://user-images.githubusercontent.com/35404978/34923786-a8fb5864-f9a7-11e7-8d1c-4a25a2674d62.png)

**Comment by marpme** [comment]
You probably have just to wait to get a connection. 
Can take some minutes to get some connections.

**Comment by tito0o0o0o0o** [comment]
Thanks marpme for your reply.
But i have been trying since 3 days now on 2 wifi networks and i'm still not able to connect over the 2 networks. and once i install the old wallet Verge QT-4.0 it works and start to sync.
tried to uninstall everything and install a fresh Wallet QT 4.1 with all steps in terminal and a new fresh downlaod for the blockchain and still the same, no connection to netork with the same above eror from debg log.

**Comment by tito0o0o0o0o** [comment]
@marpme @justinvforvendetta what i have noticed from debg.log that the new Wallet QT-4.1 has integrated with tor network and the connection through tor onion not like the previous version QT 4.0 which was working very well.
so now do i need to connect to any VPN first then launch the new QT wallet 4.1 to be able to connect to the network?

**Comment by Max-Meldrum** [comment]
@tito0o0o0o0o You shouldn't have to connect to any vpn's. Do you still have connection issues?  The connection problems might have just been temporary?

Feel free to close the issue if it is working now.

**Comment by tito0o0o0o0o** [comment]
@Max-Meldrum i tried without VPN and with VPN and still no connection. 0 connection to verge network. i don't know what to do, i don't know what else to do, this only happen with QT-4.1 wallet. please help me if u can.

**Comment by Max-Meldrum** [comment]
Have you tried on another network? e.g, another wifi
Not a Mac expert, but do you perhaps have some settings/firewall that could be interfering?

**Comment by XVGMonk** [comment]
@tito0o0o0o0o 

Hi, I'm usually assisting Mac users on Telegram. If you want you can DM me and I can ask you some questions in attempt troubleshoot your issue.

https://t.me/XVGMonk

Thank you.

**Comment by Technophant** [comment]
Threre's issues with the default onion servers being overloaded.  I can eventually connect to one which will give me more which are added to peers.dat.  when you install the data file it has a peers.dat that has more connections.  would need to see output of tor.log to see if it reaches 100% bootstrap

**Comment by justinvforvendetta** [comment]
we can add more fairly easily, but I don't see any that are overloaded

**Comment by jrsikors** [comment]
spring cleaning and closing.  please open new issue if still having problems with the latest
