### ISSUE TITLE
Unable to Sync

### ISSUE THREAD

**Issue by InemNgepel** [vergecurrency/VERGE#484]
I have done below steps:

- downloaded Verge 4.0
- delete all .dll in the verge folder 
- go to %app%, backup wallet.bat, 
- download the verge blocks up to 13/01/2018, unzip it, copy and replace to the verge folder in %app%, - wait the wallet until it updates the block. 

I did all of those and completed. Why the wallet still Out of Sync? Am I missing any step?

Thanks all for the help.

**Comment by justinvforvendetta** [comment]
you should sync yourself, from block 0. can you check your debug log and paste info here?

**Comment by InemNgepel** [comment]
Hi Justin, 

it's fine now. interestingly after block 0, it still out of sync for couple minutes and after that it syncs. Thanks a lot for your hard work and help. You are amazing !!!!
