### ISSUE TITLE
electrum wallet pending 

### ISSUE THREAD

**Issue by FakidiDuck** [vergecurrency/VERGE#485]
# Issue Template

## Context
Why my coins are not moving?.

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

## Any extra information that might be useful in the debugging process.
https://verge-blockchain.info/tx/d35edba8cbb75cd6ea166bab017026fe0c7fdee4710c992391f08b25a4227ae1

![vittusaatana](https://user-images.githubusercontent.com/35464913/34956010-d16c1bf2-fa2f-11e7-976d-356310d85195.png)

**Comment by justinvforvendetta** [comment]
did you change the fee at all? our electrum servers are updating right now, which one did you send from?

**Comment by FakidiDuck** [comment]
i send coins to binance. put verge addres and send. now i cant resend them or anything it shows no balance. sry my bad english :D
![vittusaatana](https://user-images.githubusercontent.com/35464913/34957315-c2be7b76-fa35-11e7-850d-5d120e9e9a0f.png)

**Comment by FakidiDuck** [comment]
changed servers too. nothing is working
