### ISSUE TITLE
Verge wallet does not accept my passphrase

### ISSUE THREAD

**Issue by VergeMonko** [vergecurrency/VERGE#486]
# Issue Template

## Context
Today my wallet does not accept my passphrase.

## Prerequisites

* [ x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior
That I should be able to change my passphrase, and to send coins.

## Current Behavior
My wallet suddenly does not allow me to do either of those things, as it does not recognize my passphrase as the correct passphrase. I was able to do this the last time I used my wallet, within the last 10 days.

## Steps to Reproduce (for bugs)

* Steps :
1. Run VERGE-qt
2. Attempt to send coins to an address
3. enter passphrase
4. click 'ok'

## Your Environment

* Verge Release:
* CPU: AMD
* GPU: ATI 
* RAM: 8 gig
* OS: Windows 10
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by VergeMonko** [comment]
I tried solutions in these threads, they were unsuccessful: 
https://github.com/vergecurrency/VERGE/issues/426
https://github.com/vergecurrency/VERGE/issues/238

**Comment by VergeMonko** [comment]
I receive this error in the debug window:
￼
Error: Error parsing JSON:(word from phrase)

**Comment by VergeMonko** [comment]
after trying: dumpprivkey **_(my verge address)_**
￼
I see this: Private key for address **_(my verge address)_** is not known (code -4)

**Comment by justinvforvendetta** [comment]
if you are not able to dump the private key, that means you dont own the address. do you see the address you are trying to get the private key to, in your receiving tab?

**Comment by VergeMonko** [comment]
Hello, yes I see my address in my receiving tab

**Comment by VergeMonko** [comment]
I also see all of my transactions, all correct addresses, coin volumes,  dates

**Comment by VergeMonko** [comment]
I don't know what else to try. I can't move my coins if my passphrase won't work, I've had no other trouble until today.

**Comment by VergeMonko** [comment]
I am entering the correct passphrase. I am trying everything suggested. How do I fix this? There has to be something very wrong with my wallet.
￼
Error: The wallet passphrase entered was incorrect. (code -14)

**Comment by davodavo1232** [comment]
does your password include a # symbol, check your keyboard hasnt switched to UK.

**Comment by alexkenley** [comment]
I am having exactly the same issue. encrypted the wallet in 3.0 and now cannot unlock in 3.0 or 4.0/.1

**Comment by VergeMonko** [comment]
@davodavo1232 I have typed my passphrase out carefully and pasted it into the field, I have even tried variations of it which I knew were wrong. I have performed transactions more recently than I have changed my passphrase. Something has gone wrong with my wallet, and I don't know how to fix this.

**Comment by VergeMonko** [comment]
@justinvforvendetta Hello, yes I see my address in my receiving tab. 
I also see all of my transactions, all correct addresses, coin volumes, dates. 
I have typed my passphrase out carefully and pasted it into the field, I have even tried variations of it which I knew were wrong. 
I have performed transactions more recently than I have changed my passphrase. Something has gone wrong with my wallet, and I don't know how to fix this.

**Comment by VergeMonko** [comment]
@alexkenley We likely have the same issue. I had been using 3.0 consistently, and then I used 4.0 for about 3 weeks until two days ago where I began using 4.0.1, and now this happens. I changed my passphrase back in December, and have since then performed transactions but now my wallet does not accept my passphrase.

Have you tried the solutions posted by others? I have linked to them further up. Unfortunately they have not worked for me. If something changes I will be sure to post in here about it.

**Comment by alexkenley** [comment]
yeah sounds the same. yeah I tried the other solutions, no dice. Its really strange, Ive run the wallet cracker over it for days which tried a ridiculous amount of variations of the passphrase on the wallet. Did your passphrase have spaces like a set of words of was it a single set of characters?

**Comment by VergeMonko** [comment]
@alexkenley mine is a series of words with spaces. So I have tried the thing in caps, with no spaces, a space at the beginning, a space at the end. Nothing is working. This is frustrating.

**Comment by alexkenley** [comment]
yes mine was a series of words with spaces also. there is something wrong here, I don't believe we have done anything wrong

**Comment by VergeMonko** [comment]
Other steps I have taken but haven't solved this problem.

Uninstalled Verge and removed everything from C: and the registry
Booted up 4.0.1, then logged off
Imported my backup from December 2017
Imported the latest blockchain into C:
booted 4.0.1 up which took 10 minutes, the wallet couldn't read the blk.dat and closed down automatically

I tried this, slight variation.
Uninstalled Verge and removed everything from C: and the registry
Booted up 4.0.1, then logged off
Imported the latest blockchain into C:
Booted up 4.0.1, then logged off
Imported my backup from December 2017
booted 4.0.1 up

I still can not change my passphrase, nor can I send coins.

**Comment by VergeMonko** [comment]
Some how it works again. I did this.

Uninstalled Verge and removed everything from C: and the registry
Booted up 4.0.1, then logged off
Imported the latest blockchain into C:
Booted up 4.0.1, then logged off
Imported my backup from December 2017
booted 4.0.1 up
changed my passphrase

I don't know how or why it works now, this is all sorts of frustrating.

**Comment by deliriumv** [comment]
@VergeMonko Might be worth scanning your HD for bad sectors.

**Comment by VergeMonko** [comment]
@deliriumv good idea

**Comment by alexkenley** [comment]
hmm interesting I might try a clean install and see if that makes a difference for me.

**Comment by Technophant** [comment]
You don't need to uninstall the exec or clean the registry. Just rename the VERGE folder and copy over wallet.dat. I suspect you had the Dec 31 release that did have this problem. It's too late now to confirm the version.

**Comment by Technophant** [comment]
Could use a firewall to block some ports and test this out. Not at my computer ATM

**Comment by jrsikors** [comment]
Anyone still having issues?  OP looks like he's good now , can probably close this @justinvforvendetta
