### ISSUE TITLE
Mining pools need a way to disable TOR

### ISSUE THREAD

**Issue by flound1129** [vergecurrency/VERGE#487]
TOR is too slow, we (Multipool.us) were encountering 40% orphans on 4.0.1 due to slow block propagation.

Please add a way to disable tor.

Thanks.

**Comment by deliriumv** [comment]
Already available here:
https://github.com/vergecurrency/VERGE/tree/4.0clearnet

**Comment by flound1129** [comment]
Does that branch have the tx fee fixes?

**Comment by justinvforvendetta** [comment]
that branch should work just fine, what was the issue  you experienced with master branch and fees?

**Comment by flound1129** [comment]
#178

**Comment by justinvforvendetta** [comment]
oh yeah that was fixed a long time ago @flound1129

**Comment by justinvforvendetta** [comment]
let us know when you've updated @flound1129 as I think you're the last on our list

**Comment by justinvforvendetta** [comment]
@flound1129 did you get updated over there? hope so. few hours left and the exchanges have updated as well.

**Comment by flound1129** [comment]
few hours left before what?  Is this a HF?

**Comment by justinvforvendetta** [comment]
@flound1129 https://github.com/vergecurrency/VERGE/commit/188c63a20fc153361c0a717c556a451822068600
