### ISSUE TITLE
I am having trouble opening wallet version 4.0.1. I have High Sierra 10.13.2. on all of my Mac computers.  Same issue every time.  Can someone please help?

### ISSUE THREAD

**Issue by DiamondDragon202** [vergecurrency/VERGE#488]
# Issue Template

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ x] I'm using Mac - 10.13.2 across all of my machines- same problem on every one
![screen shot 2018-01-15 at 3 45 58 pm](https://user-images.githubusercontent.com/35468828/34961128-fe89fd62-fa0b-11e7-97a9-f90577895bc2.png)
![screen shot 2018-01-15 at 3 46 14 pm](https://user-images.githubusercontent.com/35468828/34961129-fe991a5e-fa0b-11e7-82f4-d481bb5b1bb3.png)
![screen shot 2018-01-15 at 3 46 29 pm](https://user-images.githubusercontent.com/35468828/34961130-fea8bf4a-fa0b-11e7-90cf-50ab210c8fe4.png)
![screen shot 2018-01-15 at 3 46 44 pm](https://user-images.githubusercontent.com/35468828/34961131-feb1e688-fa0b-11e7-80e7-38a77254aee0.png)
![screen shot 2018-01-15 at 3 46 58 pm](https://user-images.githubusercontent.com/35468828/34961132-fec7f612-fa0b-11e7-87a1-11acb5f76d54.png)
![screen shot 2018-01-15 at 3 47 05 pm](https://user-images.githubusercontent.com/35468828/34961133-ff0e364a-fa0b-11e7-9ccd-9f32dcf04857.png)

    - [ ] I'm using Linux
    - [X ] I'm using Mac

**Comment by justinvforvendetta** [comment]
brew install boost@1.60 pkg-config automake

brew install protobuf miniupnpc openssl qrencode berkeley-db4 zlib libevent

**Comment by DiamondDragon202** [comment]
I apologize but I am not the most tech savvy.  Can you please tell me what
what I am supposed to do with what you have given me.  I really don’t mean
to be a pain.  Thank you.

**Comment by mimllr** [comment]
@DiamondDragon202 these are command line commands that need to be run (basically, you're installing some software on your computer that the wallet needs to run)

You can install them by opening "Terminal" on your Mac.
1. Click the magnifying glass in the top-right corner of your task bar
2. In the Spotlight search, type "Terminal" and open the program (looks like a black rectangle with a >_ on it)
3. In terminal, type the following commands, one at a time:
- `brew install boost@1.60 pkg-config automake`
- `brew install protobuf miniupnpc openssl qrencode berkeley-db4 zlib libevent`

If you see something like "command not found: brew", you may have an additional piece of software to install.
