### ISSUE TITLE
Pending send, unconfirmed amount not being sent.

### ISSUE THREAD

**Issue by Jakrell8** [vergecurrency/VERGE#490]
I'm having issues with the Verge electrum 2.4.1 wallet. I'm not really computer savvy and I'm having issues sending verge to an exchange, I sent the verge 3 days ago and its still saying pending? What could be the problem?

**Comment by justinvforvendetta** [comment]
which exchange? i know binance is updating right now. also, our electrum servers are in maintenance as they are now syncing from the new code update. hopefully the electrum servers ran by community members are also doing the same. have a transaction id? maybe we can take a look

**Comment by benammann** [comment]
i'm having the same issue with

cda39de579814bc664817c646b9df1c344b467e31f95e9b71b8fb535c3bb19bf
eb3198aa3401df28c84808acadc148a2793f71698fc9730b807bf0c132b9b204
08bf095c9b6307c3ef8ace89d75dd3c3f75e1a2b800cb6b4c860b79ef755c0fa

**Comment by justinvforvendetta** [comment]
@benammann those must be in mempool because i dont see them having any confirms. where did you make them from?

**Comment by Jakrell8** [comment]
@justinvforvendetta yeah it's the Binance exchange so maybe thats the issue? 

heres the transaction id 73ac623c346a34574287673af7a0ee8c2e315cd4023a4e4678754f1bbe786680

**Comment by benammann** [comment]
the first one was made with verge-qt 4.0.1, the other two made with electrum 2.4

already checked the inputs of those three transactions and they are totally fine

my last transaction ~ 1 hour ago ( made with electron ) went throw without any problems

**Comment by benammann** [comment]
@justinvforvendetta how long does it takes until the mempool expires ? Maybe i just have to shut down my wallet and prevent it from broadcasting this transaction.

thanks for your support 👍 🥇

**Comment by justinvforvendetta** [comment]
should bounce back within a few days.

**Comment by Jakrell8** [comment]
@justinvforvendetta did you see anything wrong with the transaction?

**Comment by davodavo1232** [comment]
https://verge-blockchain.info/tx/34a3f73278e15e59b1d51f9838446442cfdf9e60d3fbb22f8662d9a90504dc6e
https://verge-blockchain.info/tx/13a51fe30e39dc2aa484aa4f232fe881bc3afeb5e816f109891d26c477465fbb
Mine has been in there for 3 day (one of the transaction) 
https://verge-blockchain.info/tx/8dba209534402627dbe1e5b3f59b132576d0822cadf3c03513f059bfc4cca2c0

Hopefully the server update fixes?

**Comment by raidburn** [comment]
I'm having the same issue i have a withdrawal fro the electrum wallet request to send my xvg to binance and it's stuck pending for over 2 hours now. 


Transaction ID: 1f5b944796980442b590a5133692b45880a344386e526a3529225aeefdf2826b

**Comment by benammann** [comment]
@justinvforvendetta thanks for the mempool tip! <3 i've ended up doing a transaction via the cli using just one input.

Here it is https://verge-blockchain.info/tx/d53aa50def424ec3cd51db0f0fb849d1807993c724fad76faf5547da6f1e5df3

for the other people having the same issue:

- be sure to wait > 3 days
- export your private keys
- create a clean install of Verge 4.0.1
- start the wallet using the `-zapwallettxes` parameter

then select your input using `listunspent` in the cli

create a raw transaction using `createrawtransaction '''[{"txid": "yourinputtx", "vout": thevout}]''' '''{"receiveraddress": amount}'''`

be carefull with the fees!

lets say your input is 15000 xvg, and you send 14000 xvg the fee will be 1000xvg.

to prevent this add another output address

https://en.bitcoin.it/wiki/Raw_Transactions

**Comment by benammann** [comment]
was able to resolve all my stuck transactions 👍

**Comment by DonPedro1984** [comment]
i am still facing this problem...

benammann, i have the problem using electrum walllet any solution for that wallet ?
or can i just use the verge-qt version with the private keys of electrum walllet ??

**Comment by benammann** [comment]
just use an fresh install of verge-qt and than import the private keys from electrum using

`importprivkey <privatekey>`

after that your will be able to make your transactions

**Comment by Zibi007** [comment]
I have the same issue with pending transaction since yesterday:

https://verge-blockchain.info/tx/6d4721bd00b52a9c6dacfa8f9d754d992dc984770f0abaa78f5f8f4e8c1290d2

@benammann Does it mean you have increased the transaction in the way you described and this was solution to push it through blockchain?

**Comment by DonPedro1984** [comment]
@benammann thank you very much for your help ! i ll try and report if it has worked for me...

**Comment by DonPedro1984** [comment]
@benammann this is too hard stuff for me cant make it :/ 

i think i ll need a point & click guide.. nevertheless, the cryptomarket is about to die right now...
createrawtransaction '''[{"txid": "yourinputtx", "vout": thevout}]''' '''{"receiveraddress": amount}'''

i dont know what to fill in for the variables.

**Comment by davodavo1232** [comment]
I am having trouble importing private keys, can you please give me a link that explains how to do this? 
Any help would be great @benammann. Do i just put the key in its native format or do i have to do something with the key before hand? do i just export the key and paste it in?
Sorry to keep going with this i just want it resolved. Thanks

**Comment by benammann** [comment]
i can perform your transactions if you trust me. Already helped some people out

add me on telegram `benammann`

cheers :)

**Comment by benammann** [comment]
@davodavo1232 every wallet has its own private key, it looks like a wallet but just a littlebit longer. You can import it in Verge-QT navigating to Help -> Debug Window -> CLI. Than perform the command `importprivkey <privkey>` for each of your keys. Please keep in mind that every import of a private key can take up to 10-20 minutes because it rescans the whole blockchain by performing this command.

@DonPedro1984 try to google `bitcoin create raw transaction` maybe there is a tutorial available

@Zibi007 i've created a complete new transaction and broadcasted it

If someone needs more support you can add me on telegram `benammann`

**Comment by Zibi007** [comment]
I am trying to export priv key in electrum, Wallet-->private keys-->export, typing password correctly and... nothing happens... And I am connected...

**Comment by DonPedro1984** [comment]
@Zibi007 
i have followed the instruction of @benammann they have worked for me aswell

after --> export, typing in the password a new windows has to pop up

in this one you just pick csv and open the file

go for  https://verge-blockchain.info you and check for the wallet where your "stuck" funds are.

in verge qt use importprivkey <privatekey> and wait for some minutes. after that a balance has to show up. 

if you see the balance you can use the traditional "SEND" button. you dont new to do it with create raw transaction 

good look

**Comment by davodavo1232** [comment]
Thanks alot benammann, it all worked out just fine.
Your a life saver!!

**Comment by ryanprovofc** [comment]
@benammann for some reason my Mac won't let me let me download the latest version of Verge-QT.  I am downloading it from the Verge website.  I attached a screenshot of the message I'm getting, saying it can't be open because of a problem.  Do you have another website or link I can use to download QT?  All in all, your instructions seem straightforward for the solution, I just need to get QT downloaded now and I should be golden.  Hopefully..  Thanks man
![screen shot 2018-01-17 at 9 25 45 pm](https://user-images.githubusercontent.com/35438044/35077894-67366ca2-fbcd-11e7-86e3-edd9354e94b9.png)

**Comment by ss77ss** [comment]
@ryanprovofc Try going to Finder and hit Control +Click on the dmg file.  It will warn again but let you open.

**Comment by Jakrell8** [comment]
How do i import keys? I was using 2.4.1, and trying to import 2.4.1 into 4.0.1

**Comment by ryanprovofc** [comment]
@ss77ss no luck.  control + click for me is just a secondary/right click.

**Comment by johnrockson** [comment]
@benammann do you need to use the -zapwallettxes parameter if you are importing from electrum wallet to new verge qt wallet?  If so, can you explain how exactly we do this?  like provide an example of how to type this in, or images for us non-coders. 

Thanks

**Comment by EXAIYU** [comment]
@DonPedro1984 

Error adding key to wallet (code -4)..

what should i do :(?

**Comment by DonPedro1984** [comment]
@EXAIYU 
this seems to be your regular adress but not the private key
the privat KEY starts usally with a big Q not with ad D.

go export your private keys in electrum.
open the csv 
the privat key is the one directly posted next to your walllet adress

**Comment by DonPedro1984** [comment]
@ EXAIYU 
after that your wallet has to sync, this will take a long time... i suggest to download the blockchain directly to your computer, this fastens up the thing quite a lot.

you can download the blockchain here  -->
https://verge-blockchain.com/

**Comment by Zibi007** [comment]
I would like to thank you @benammann for all your instructions. With difficulties, but I managed to withdraw my money! Thank you!

Guys couple of advices:

As Benamman said your Verge qt needs to be clean, you should not open any other wallets on that before you import privkeys. Once you download that from the website, you need to replace the files with blockchain firstly as instructed before. Then importprivkey in console, it will turn into green once done correctly. You need to go key by key, upload them all from your previous wallet. Once you are done your wallet gets synchronised and you will seee your money out there :-)

**Comment by johnrockson** [comment]
UPDATE:  I got my coins back, I think. I just did what @justinvforvendetta said to do.  Close your wallet for a day or 2.  It should come back to it.  I'm still confirming things, but it looks like I got my coins back.  

Also @benammann is very helpful with the new verge qt wallet, seek him out if you still have issues.

**Comment by ryanprovofc** [comment]
@Zibi007 @johnrockson did you guys use homebrew to download the verge qt 4.0 wallet?  I'm still having some difficulty installing after going by @benammann instructions.  I'm using MacOS.  Looking at my electrum wallet now, it looks like the 'pending' message went away and now it just shows my balance as 'unverified'. If you guys have any advice to give on how you got 4.0 downloaded that would be a huge help.  Thanks all!

**Comment by EXAIYU** [comment]
@DonPedro1984 
You've been a big help！
I'm much obliged！

**Comment by xtrc** [comment]
@benammann This is not working for me. I guess we will have to wait for the hard fork?

**Comment by ryanprovofc** [comment]
hey guys finally got verge qt to install, in the end used the command '**brew install boost@1.66**' in the terminal.  Apologies for overlooking, saw in another thread.  Thanks for all your help!

Cheers
