### ISSUE TITLE
Confirmed stealth transaction is unconfirmed in the wallet

### ISSUE THREAD

**Issue by modislaszlo** [vergecurrency/VERGE#491]
# Issue Template

## Context

Stealth transaction was confirmed on the blockchain but the wallet still shows it as unconfirmed.

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior

Transaction confirmed in the wallet.

## Current Behavior

Transaction not confirmed in the wallet.

## Screenshots

![capture](https://user-images.githubusercontent.com/1011545/34980076-fb3b04e4-faab-11e7-966b-697c12cf1baf.JPG)
![capture2](https://user-images.githubusercontent.com/1011545/34980080-fe4422b0-faab-11e7-9895-4dc3ff447780.JPG)

## Your Environment

* Verge Release:
* CPU: 4
* GPU: 1
* RAM: 8 GB
* OS:
    - [x] I'm using Windows
    - [ ] I'm using Linux
    - [ ] I'm using Mac

## Any extra information that might be useful in the debugging process.

I already run the wallet with -rescan and it didn't fix the issue.

Transaction: https://verge-blockchain.info/tx/75309cf527b50f0cec45a462ff19ad76f02c700c9f79a461c72e8c3cbff1c7f0

**Comment by justinvforvendetta** [comment]
it is not confirmed on the blockchain, but should be sometime later tonight.

**Comment by modislaszlo** [comment]
@justinvforvendetta the transaction has over 1500 confirmations on the website but in the wallet still sits as  unconfirmed; not sure how is that possible.
