### ISSUE TITLE
Found Berkeley DB other than 4.8

### ISSUE THREAD

**Issue by salimamin2** [vergecurrency/VERGE#492]
##Error 

Error when i build & configure.

configure: error: Found Berkeley DB other than 4.8, required for portable wallets (--with-incompatible-bdb to ignore)

**Comment by Max-Meldrum** [comment]
Which system are you building on? OS X, Windows, Linux?
You need version 4.8. Which version do you currently have?

**Comment by justinvforvendetta** [comment]
this means you installed a different version of berkeleydb.

you can run ./autogen.sh && ./configure --with-incompatible-bdb && make 

in that case, or remove your current bdb and install the recommended one.
