### ISSUE TITLE
Verge wallet xvg 2.4.1 not syncronizing & my coins are unverified & stuck  :-( 

### ISSUE THREAD

**Issue by SuperNathoon** [vergecurrency/VERGE#493]
problem with verge wallet xvg 2.4.1

can anybody help me please on what i need to do to verifie my unverified transactions & syncronize the wallet.

the wallet has been open on my desk for more than a month & the my coins are in the wallet
( unverified ) the balance is there but doesn't sycronize. 
This is very frustating it keep switching on & off doesn't verifie the transaction and i can't move those coins... 

I've trying to change the severs / ssl / proxy / localhost .... and nothing does the job i can find the transaction on the blockchain but can't get it verified :-(

please i need a miracle to solve this issue please & acces my coins freely...

![img-5734](https://user-images.githubusercontent.com/35498021/34999795-fa415ee4-fae2-11e7-9307-564024aa4627.JPG)
![img-5736](https://user-images.githubusercontent.com/35498021/34999869-2c45e644-fae3-11e7-86f1-71a872e42a11.jpg)
![img-5741](https://user-images.githubusercontent.com/35498021/34999915-48aaf8d8-fae3-11e7-8756-a649ffac5497.JPG)

https://verge-blockchain.info/address/DCHT4PK1Ro3Mo1RipGnWmMs3PopJjaYXKm

https://verge-blockchain.info/address/D8o4n2TkdbJbkYELn5EXMbSKyP8JXqDohX

https://verge-blockchain.info/address/DNukwm7kcJmLBFK4qwFe2RqSsErakU2iDf

**Comment by vorlonempire** [comment]
You will always have "unverified", this electrum wallets have that. But issue with connection can be caused by firewall or antivirus blocking electrum?

**Comment by SEVCO** [comment]
@SuperNathoon 

My transactions are also unverified. But for syncing  the instructions below worked in my case.


Open Preferences -> 
Server = e2.verge-electrum.com:50002
uncheck use ssl -> ok ->
 Open Preferences check use ssl -> ok

**Comment by SuperNathoon** [comment]
thanks guys, 
but it still doesn't work.... :-(

**Comment by justinvforvendetta** [comment]
your transactions are fine. the date says unverified, but they are already spendable and in your wallet.

**Comment by SuperNathoon** [comment]
yes it works . so i send 100 back to bittrex and it works ;-) 
so could you tel me as well wich one i should put on my mac book pro please?
so this time it 's going to be fine and work perfectly?

thanks to all of you guys for the help and fast reply ;-)

**Comment by justinvforvendetta** [comment]
electrum is safe, our core wallet is safe, our paper wallets are safe
android wallets.. any official verge wallet is safe

**Comment by SuperNathoon** [comment]
@vorlonempire @justinvforvendetta @SEVCO 

thank to all of you guys 👍

**Comment by WDMi** [comment]
Hi, I cant get my 2.4 mac electrum wallet to sync since the SSL is set on 50002 instead of 3. Can anybody help me with some advice? I can manually change the SSL but as soon as I click ok I jumps back to 50002. Tried pretty much everything now in every order possible. Maybe another server newer than the e3 I can add? Cheers!

**Comment by WDMi** [comment]
Didnt use my wallet for a couple of weeks but it doesnt need to download blocks like the QT(?)

**Comment by jrsikors** [comment]
post under the open issue  #673 please
