### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by daehbew** [vergecurrency/VERGE#496]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by daehbew** [comment]
Submitted transaction of 1849.60 XVG from Electrum on PC to Android TOR wallet. Over 3 days pending. Zero confirmations.

TxID can be seen here:
https://verge-blockchain.info/tx/017d0cd30a2662c4d3fc90b793cc86458bf7297a768725e5d243a5a512918709

**Comment by benammann** [comment]
i've written a small tutorial how to fix those transactions in #490
