### ISSUE TITLE
Wallet Full Release 4.0.1 on Windows 10 does not lock after unlocking

### ISSUE THREAD

**Issue by trongod05** [vergecurrency/VERGE#497]
# Issue Template

## Context

Cannot lock the wallet after it has been unlocked.

## Prerequisites

* [X] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [X] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior

After using the walletpassphrase function to unlock the wallet, the walletlock function does not lock the wallet.

## Current Behavior

If you hover over the lock icon after the wallet is launched it will say it is encrypted and locked.  If you unlock the wallet and then try locking it again with the walletlock function, since there's no entry to do that on the Settings menu, it will not lock the wallet again. There needs to be an option on the Settings menu to lock the wallet again and the walletlock needs to actually work.

## Screenshots

![verge1](https://user-images.githubusercontent.com/2983459/35031550-0bae4ca0-fb29-11e7-8659-278a71842aea.png)
![verge2](https://user-images.githubusercontent.com/2983459/35031556-11544222-fb29-11e7-82c9-00d802d81372.png)
![verge3](https://user-images.githubusercontent.com/2983459/35031563-1571b8c6-fb29-11e7-8454-485a6acecfe3.png)

## Steps to Reproduce (for bugs)

* Steps :
1. Open Verge
2. Click Settings->Unlock Wallet
3. Enter Passphrase 
4. Click Settings again, notice there's no feature to lock it again.
5. Click Help->Debug Window->Console (Tab).
6. Type walletpassphrase <passphrase> <timeout> # This will tell you it's already unlocked
7. Type walletlock to lock the wallet
8. Type walletpassphrase <passphrase> <timeout> # Even though it was locked it will tell you it is already unlocked.

## Your Environment

* Verge Release: Wallet Full Release 4.0.1 
* CPU: Intel Core i7
* GPU: Nvidia Geforce GTX 1070
* RAM: 32G
* OS:
    - [X] I'm using Windows 10
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by Max-Meldrum** [comment]
I am currently looking into it.
