### ISSUE TITLE
Send coins from electrum wallet to Qt 4.0.1 (Passphrase not accepting, accepted but cant encrypted wallet)

### ISSUE THREAD

**Issue by Pele51** [vergecurrency/VERGE#498]
Hello. I was sending alot of coins from electrum wallet to the qt 4.0.1 wallet and the transaction still shows unconfirmed balance, sometimes i get 3confirmations and then back to 0, but i think that will get fixed...?
Both wallets were fully synched.

Another problem is that i locked my wallet with a 9word passphrase, i just try to get it unlocked but it doesnt work??? I was typing the 9words passphrase on an editor and on a white paper to get very sure i have the right one and i will not loose it, when i try to unlock the wallet i just go to my harddrive where i saved the passphrase and copy and paste it in my wallet and it keeps saying that its uncorrect, even i try to type it in it shows uncorrect, i also make a backup of my wallet on the usb drive, but i started my wallet from app/data/roaming/verge..ect.

Please help me i dont want to loose my coins

**Comment by Pele51** [comment]
![verge issue](https://user-images.githubusercontent.com/35359689/35036458-b564bd24-fb74-11e7-9cd7-3a7b374e2aa2.png)

**Comment by Pele51** [comment]
This is strange i just try it again and again and now the same passphrase works.... but i cant encrypted my wallet now, the buttom is grey....... i get really pissed off of xvg wallets issues now..... sorry to say that but other wallets like stellar lumens cardano or iota are much better, just download it send coins choose password whatever and finish.. but this get really pisses me off, every day another problem...

**Comment by jrsikors** [comment]
Have you downloaded the latest "4.0.1 fork for stealth" ?  I believe the locking / unlocking is now resolved.

**Comment by jrsikors** [comment]
Also -- I dont believe you were using the "walletpassphrase" command correctly.

Let's assume your passphrase is "Hello world".

To use the walletpassphrase command, you have to do this:
walletpassphrase "Hello world" 60

Notice the quotes... and the 60... that will unlock for 60 secs.

**Comment by Pele51** [comment]
Yes the problem is solved i tried it again yesterday, and i could unlock it and yes i put the walletpassphrase command incorrectly, you can close the issue, thx for the nice support and keep up the good work, i want to see xvg in top 10 soon;)
