### ISSUE TITLE
XVG 0 Confirmations

### ISSUE THREAD

**Issue by EXAIYU** [vergecurrency/VERGE#499]
Hello guys,can someone answer my question?
I sent 31385 XVG from my Electrum XVG 2.4.1 to my balance. It has been "pending", unconfirmed for over 24 hours,Did I lose my coins :(?

https://verge-blockchain.info/tx/6c20024c4127d3d8bed7c19b2925176f063d50ffa4d6b0d916c02697d879bf5f

Thanks for your attention!

**Comment by JoepW01** [comment]
I have the exact same problem. Tried to send XVG from electrum 2.4.1 to Binance, but is not confirmed after  >24 hours. 

https://verge-blockchain.info/tx/152ec13ea6f576361d51cbf8a722cfee3e82d271716b897509f6c72a56613bec

**Comment by benammann** [comment]
i've written a small tutorial how to fix those transactions in #490
