### ISSUE TITLE
Proof-of-stake instead Proof-of-work

### ISSUE THREAD

**Issue by digegold** [vergecurrency/VERGE#5]
Stratum detect verge daemon as POS not POW,
also errors in debug.log
ERROR: SetBestChain() : Reorganize failed
ERROR: AcceptBlock() : AddToBlockIndex failed
ERROR: ProcessBlock() : AcceptBlock FAILED
received block 000000034453b30898ca
Postponing 521 reconnects
REORGANIZE
REORGANIZE: Disconnect 367 blocks; 000000028f337f664cb5..00000000005943dc690d
REORGANIZE: Connect 6483 blocks; 000000028f337f664cb5..0000000003cee7f69cfc
ERROR: ConnectBlock() : UpdateTxIndex failed
ERROR: Reorganize() : ConnectBlock 00000003db4d9f497ae6 failed
InvalidChainFound: invalid block=000000034453b30898ca  height=291044  trust=97919604092  date=03/21/16 04:49:39
InvalidChainFound:  current best=00000000005943dc690d  height=284407  trust=97135061726  date=03/21/16 16:02:13
ERROR: SetBestChain() : Reorganize failed
ERROR: AcceptBlock() : AddToBlockIndex failed
ERROR: ProcessBlock() : AcceptBlock FAILED

**Comment by c-bit** [comment]
@digegold not sure why your stratum detected it as PoS, as the pools that we have currently arent having that issue. we are aware that there is a large reorg happening. this is happening to alot of scrypt coins right now. we have a large hashpower hitting our network and forking, then reorg. a new multi algo release will be available soon that should help us.

**Comment by vergecurrency** [comment]
yeah that is a reorg, but it failed.. we're switching to multi algo soon, shouldnt see any reorgs after that. not sure why your stratum is detecting it as PoS, maybe because nTime?

**Comment by digegold** [comment]
this is from debug.log:
ThreadRPCServer started
ThreadMessageHandler started
ThreadStakeMinter started
CPUMiner started for proof-of-stake
ThreadOpenConnections started
ThreadOpenAddedConnections started

**Comment by vergecurrency** [comment]
right, its disabled though, there is no stake reward. just nTime. what pool?

**Comment by digegold** [comment]
It is my local UNOMP pool with 13 coins, all detected as POW accept VERGE
Pool verge Thread 1 started for verge [XVG] {scrypt}
Network Connected:      Mainnet
Detected Reward Type:   POS
Current Block Height:   292852
Current Connect Peers:  12
Current Block Diff:     607229003.6380467
Network Difficulty:     1012047611.618263
Network Hash Rate:      481.45 GH
Stratum Port(s):        3018, 3048, 3268
Pool Fee Percent:       0%
Block polling every:    1000 ms
This output from getmininginfo:
    "blocks" : 292851,
    "currentblocksize" : 8373,
    "currentblocktx" : 11,
    "difficulty" : 15442.62102689,
    "errors" : "",
    "generate" : false,
    "genproclimit" : -1,
    "hashespersec" : 0,
    "networkhashps" : 516956759743,
    "pooledtx" : 11,
    "testnet" : false
This output from getinfo:
    "version" : "v1.2.0.0-beta",
    "protocolversion" : 60017,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "newmint" : 0.00000000,
    "stake" : 0.00000000,
    "blocks" : 292851,
    "timeoffset" : 53,
    "moneysupply" : 10135637499.99999619,
    "connections" : 12,
    "proxy" : "",
    "ip" : "X.X.X.X",
    "difficulty" : 15442.62102689,
    "testnet" : false,
    "keypoololdest" : 1458596773,
    "keypoolsize" : 102,
    "paytxfee" : 0.10000000,
    "errors" : ""

**Comment by vergecurrency** [comment]
right, i just said theres nTime, but no stake reward. are you not able to mine it?

**Comment by digegold** [comment]
No, stratum detect it as POS:
Detected Reward Type: POS
and verge daemon will reject solved blocks.
All other coins works fine

**Comment by vergecurrency** [comment]
try putting gen=0 and reservebalance=0 and staking=0 in the .conf?

**Comment by vergecurrency** [comment]
you have other pos/pow coins working on your pool?

**Comment by digegold** [comment]
Only POW, 12 other coins, all work fine

**Comment by digegold** [comment]
After change .conf still detect as POS. Look like blockchain stuck on block 284542

**Comment by digegold** [comment]
Sorry block=292,852

**Comment by digegold** [comment]
this is latest output from debug.log:
getblocks 287022 to 00000000000000000000 limit 500
  getblocks stopping at limit 287521 000000030320b39c9e58
getblocks 285522 to 00000000000000000000 limit 500
  getblocks stopping at limit 286021 000000044a074f688e5a
getblocks 284022 to 00000000003cd4d68adb limit 500
  getblocks stopping at limit 284521 000000002aab9095b2ac
getblocks 286022 to 00000000000000000000 limit 500
  getblocks stopping at limit 286521 000000067e1f004ce73e
getblocks 284022 to 000000000024b84fe40b limit 500
  getblocks stopping at limit 284521 000000002aab9095b2ac
getblocks 285522 to 00000000000000000000 limit 500
  getblocks stopping at limit 286021 000000044a074f688e5a
getblocks 284522 to 00000000000000000000 limit 500
  getblocks stopping at limit 285021 000000026316a6d291c7
getblocks 284522 to 00000000000000000000 limit 500
  getblocks stopping at limit 285021 000000026316a6d291c7
getblocks 286522 to 00000000000000000000 limit 500
  getblocks stopping at limit 287021 000000000254465c9bba
getblocks 285022 to 00000000000000000000 limit 500
  getblocks stopping at limit 285521 00000002eb42f13705af
getblocks 284522 to 00000000000000000000 limit 500
  getblocks stopping at limit 285021 000000026316a6d291c7
getblocks 284022 to 000000000024b84fe40b limit 500
  getblocks stopping at limit 284521 000000002aab9095b2ac
getblocks 286022 to 00000000000000000000 limit 500
  getblocks stopping at limit 286521 000000067e1f004ce73e
getblocks 285522 to 00000000000000000000 limit 500
  getblocks stopping at limit 286021 000000044a074f688e5a
getblocks 284522 to 00000000000000000000 limit 500
  getblocks stopping at limit 285021 000000026316a6d291c7
getblocks 285022 to 00000000000000000000 limit 500
  getblocks stopping at limit 285521 00000002eb42f13705af
getblocks 286022 to 00000000000000000000 limit 500
  getblocks stopping at limit 286521 000000067e1f004ce73e
getblocks 286522 to 00000000000000000000 limit 500
  getblocks stopping at limit 287021 000000000254465c9bba
getblocks 285022 to 00000000000000000000 limit 500
  getblocks stopping at limit 285521 00000002eb42f13705af
getblocks 286522 to 00000000000000000000 limit 500
  getblocks stopping at limit 287021 000000000254465c9bba
getblocks 285522 to 00000000000000000000 limit 500
  getblocks stopping at limit 286021 000000044a074f688e5a
getblocks 285022 to 00000000000000000000 limit 500
  getblocks stopping at limit 285521 00000002eb42f13705af
getblocks 285522 to 00000000000000000000 limit 500
  getblocks stopping at limit 286021 000000044a074f688e5a
getblocks 287022 to 00000000000000000000 limit 500
  getblocks stopping at limit 287521 000000030320b39c9e58
getblocks 284022 to 000000000024b84fe40b limit 500
  getblocks stopping at limit 284521 000000002aab9095b2ac
getblocks 286022 to 00000000000000000000 limit 500
  getblocks stopping at limit 286521 000000067e1f004ce73e
getblocks 286022 to 00000000000000000000 limit 500
  getblocks stopping at limit 286521 000000067e1f004ce73e
getblocks 284022 to 00000000003cd4d68adb limit 500
  getblocks stopping at limit 284521 000000002aab9095b2ac
getblocks 286522 to 00000000000000000000 limit 500
  getblocks stopping at limit 287021 000000000254465c9bba
getblocks 284522 to 00000000000000000000 limit 500
  getblocks stopping at limit 285021 000000026316a6d291c7
getblocks 286522 to 00000000000000000000 limit 500
  getblocks stopping at limit 287021 000000000254465c9bba
getblocks 284522 to 00000000000000000000 limit 500
  getblocks stopping at limit 285021 000000026316a6d291c7
getblocks 284022 to 000000000024b84fe40b limit 500
  getblocks stopping at limit 284521 000000002aab9095b2ac
getblocks 285522 to 00000000000000000000 limit 500
  getblocks stopping at limit 286021 000000044a074f688e5a
getblocks 285022 to 00000000000000000000 limit 500
  getblocks stopping at limit 285521 00000002eb42f13705af
getblocks 285022 to 00000000000000000000 limit 500
  getblocks stopping at limit 285521 00000002eb42f13705af
getblocks 284522 to 00000000000000000000 limit 500
  getblocks stopping at limit 285021 000000026316a6d291c7
getblocks 284022 to 000000000024b84fe40b limit 500
  getblocks stopping at limit 284521 000000002aab9095b2ac
getblocks 285522 to 00000000000000000000 limit 500
  getblocks stopping at limit 286021 000000044a074f688e5a
getblocks 285022 to 00000000000000000000 limit 500
  getblocks stopping at limit 285521 00000002eb42f13705af
^C

**Comment by vergecurrency** [comment]
yes the chain is stuck on 292853 right now. we are switching to multi algo in a week. not sure why you cant set it up, we are on about 10 different pools right now. and i set it up on a unomp pool as well. do you have the getblocktemplate rpc stuff set up correctly?

**Comment by digegold** [comment]
I'm not sure what are you mean by "getblocktemplate rpc stuff"
This is the RPC calls from stratum:
ThreadRPCServer method=getinfo
ThreadRPCServer method=validateaddress
ThreadRPCServer method=getdifficulty
ThreadRPCServer method=getinfo
ThreadRPCServer method=getmininginfo
ThreadRPCServer method=submitblock

**Comment by digegold** [comment]
Here is error from daemon:
ThreadRPCServer method=submitblock
ERROR: CTransaction::CheckTransaction() : txout.nValue below minimum
ERROR: CheckBlock() : CheckTransaction failed
ERROR: ProcessBlock() : CheckBlock FAILED

**Comment by vergecurrency** [comment]
oh, you'll have to code unomp to allow batch rpc requests, or use different pool software. unomp isnt compatible with ppc clones by default. you just need to write code to detect when a coin is missing batch rpc and implement a batch rpc shim into daemon.js
