### ISSUE TITLE
Confirmed transactions appear unconfirmed in wallet transaction history.

### ISSUE THREAD

**Issue by Vadim-Podlevsky** [vergecurrency/VERGE#501]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version? 
Yes, 4.0.1 Windows 10 64-bit.

## User Story:

* "I'm submitting a ... "
  - [ ] bug report

## Expected Behavior

New transactions do not alter old transactions data.

## Current Behavior
If the new unconfirmed transaction appears in wallet transaction history, old transactions appear unconfirmed. - Screenshot 1.
All wallet Balance also shifts to Unconfirmed - Screenshot 2.

## Screenshots
![verge 4 0 1 wallet transaction history](https://user-images.githubusercontent.com/1458033/35044259-5b7f0962-fb98-11e7-9786-4a8efb4a44fc.PNG)
![unconfirmed](https://user-images.githubusercontent.com/1458033/35044722-1ee3ba46-fb9a-11e7-973f-21892e47ebd9.PNG)

## Steps to Reproduce (for bugs)

* Steps :
1. Send stealth transaction to a wallet.
2. Old transactions in Transaction History appear unconfirmed.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Windows 10

**Comment by deliriumv** [comment]
The pools are still ramping up. It will confirm eventually. I did a couple
of stealth transactions last week and they confirmed sometime this morning.
You might notice the transactions flipping between confirmed/unconfirmed a
few times but this will settle down sometime today.

**Comment by deliriumv** [comment]
The pools are still ramping up. It will confirm eventually. I did a couple
of stealth transactions last week and they confirmed sometime this morning.
You might notice the transactions flipping between confirmed/unconfirmed a
few times but this will settle down sometime today.

**Comment by Vadim-Podlevsky** [comment]
Thaks for reply! Actually I'm aware of it. I tested 4 stealth transactions and eventually they all settled down as confirmed and balance fully usable. But I think this is a wallet issue, so reported it to let devs be aware of.

**Comment by deliriumv** [comment]
ah, sorry I misread your post. :+1:

**Comment by Positivism** [comment]
The only way to fix this as of is to delete the blockchain data and let it sync manually through the client, the client-syncing process however is much too slow.

**Comment by Vadim-Podlevsky** [comment]
Thanks for advice, @Positivism! Will have to try that, I downloaded blockchain, didn't want to wait days.

**Comment by ryanprovofc** [comment]
hey guys, do you happen to know whats going on with the verge electrum wallet 2.4.1?  It's happened to me and I've heard it has been happening to others as well.  But I tried sending coins from the electrum wallet over to binance last week and am still seeing the transaction as pending or unconfirmed, 0 confirmations.  People have been saying that they appear to be stuck on the blockchain or there is a bug happening.  No idea, but starting to get really worried my coins are lost.  If anybody knows anything about this please let me know.  Thanks

**Comment by Vadim-Podlevsky** [comment]
@ryanprovofc dm @justinvforvendetta the main dev he has all answers. Never used electrum for verge and never had any issues with verge blockchain. It may be connected with massive pool updates to latest protocol however.

**Comment by ryanprovofc** [comment]
Thanks, i'll try and contact him

**Comment by ryanprovofc** [comment]
@justinvforvendetta I know you've been probably getting a lot of messages about this.  But do you have step by step instructions on how to resolve this issue with the stuck transactions in the electrum wallet 2.4.1?  I read other threads and I tried installing homebrew through the terminal so I can in turn install Verge QT 4.0.1 but its still giving me trouble.  Thanks for all your help
