### ISSUE TITLE
Wraith 4.0 or 4.0.1 doesn't work on Mac OS High Sierra Version 10.13.2

### ISSUE THREAD

**Issue by CryptoSam85** [vergecurrency/VERGE#503]
# Issue Template

## Context
Dear best Verge Team,

I had downloaded the 4.0 file and do this in your way you tell us and it doesn’t work on High Sierra!
I had downloaded the 4.0.1. file and do this too in your way you tell us and it doesn’t work on High Sierra!

I repeat this a 100 times and I don’t get it the Issue comes again and again! Please help me.
My version on my Mac is 10.13.2

<img width="440" alt="bildschirmfoto 2018-01-17 um 19 48 37" src="https://user-images.githubusercontent.com/35539769/35060675-71905aae-fbbf-11e7-93b8-fe4785051439.png">

it means; Contact the developer to make sure that VERGE-Qt works with this version of macOS. You may need to reinstall the program. Be sure to install all available updates for the program and macOS.

ignore or report

## Prerequisites

* [ ] Are you running the latest version?
yes

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by Max-Meldrum** [comment]
Yes, seems like others are having similar issues. 
As mentioned in #482 , could you try entering the following in the mac terminal and try run it again.

xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew install boost
brew install boost@1.66

**Comment by CryptoSam85** [comment]
I did it, but I think its an other Problem.

**Comment by raidburn** [comment]
I was getting a similar issue until I reinstalled the blockchain files in my application support files  and also reinstalled wraith 4.0 and rebooted my computer. Now wraith 4.0 opens ( sometimes) and syncs but stop responding .

**Comment by justinvforvendetta** [comment]
use the new one that was released last night

**Comment by CryptoSam85** [comment]
Check! You are the best!!!
Reale nice!
