### ISSUE TITLE
Error 'getititem' when signing transaction, any help? Coins stuck in wallet

### ISSUE THREAD

**Issue by someguyinla** [vergecurrency/VERGE#504]
I've had problems sending xvg from my Electrum xvg 2.4.1 wallet to my Binance wallet. I send and save the transaction then load it into a new wallet to sign and send it, but then get this error.

Any ideas?

![electrum2](https://user-images.githubusercontent.com/35316056/35062499-587a5e52-fb79-11e7-998a-6d5371ac3742.jpg)
![error](https://user-images.githubusercontent.com/35316056/35062500-589925a8-fb79-11e7-90a7-7c17f42cb8d8.jpg)

**Comment by jrsikors** [comment]
Sorry for missing this one -- are you still having the same issue?  I noticed this was posted pre-hard fork... and perhaps there was a thought that the hard fork would clear up 90% of these issues.

Any updates?

Thanks and sorry  !

**Comment by justinvforvendetta** [comment]
why is the top picture from a "watch only" address?

**Comment by jrsikors** [comment]
Glad you chimed in.. I noticed that too and thought it was super odd , but not familiar enough with electrum to call that out.  Pretty sure that is the likely the issue.

If it’s watch only.. he doesn’t really own the addresses.. so an error while trying to send coins from an address that you don’t own will probably throw some kind of error.

**Comment by justinvforvendetta** [comment]
correct, you cant make a transaction from an address that you are watching, but do not own. thanks again @jrsikors for jumping all over issues. ill escalate your privs here shortly, i get back in town tomorrow.

**Comment by jrsikors** [comment]
@justinvforvendetta don't forget about me !   I got some cleanup to do !
