### ISSUE TITLE
Unconfirmed transactions

### ISSUE THREAD

**Issue by Syre1900** [vergecurrency/VERGE#506]
# Issue Template

## Context

Providing context helps us come up with a solution that is most useful in the real world -->

## Prerequisites

* [ ] Are you running the latest version?

Yes.

## User Story:

I'm submitting a support request .

I have the following issues:
- I have sent a transaction to myself using the new 4.0.1 core wallet on windows. It is showing up on blockchain.info under the /tx/ section, but when I search for the transaction id manually on blockchain.info it doesn't show up as a transaction.
- In the wallet itself, it shows the balance as confirmed, so I attempted to resend it to myself again (don't ask me why), I resent, and yet again I have the same issue. It's showing up under the /tx/ section, but isn't showing up when you try to search for the transactin ID. It's been quite a few hours and both transactions aren't showing as confirmed. Also after performing rescan on the wraith wallet, it's now showing unconfirmed balance, not confirmed.
- When I check the blockchain for the original address, it still shows the balance (I am transferring from one personal address to another)
- When I load that address into the electrum wallet (using the private key), it shows the transfer as pending. It appears that my transfers are effectively stuck at the moment

Also, something strange has happened in both the electrum wallet and the qt wallet it's showing the balance being at the old address, but when I check the blockchain explorer, it shows the balancing being at another address (both addresses are mine, but wallets aren't matching up to what's on the blockchain explorer)

I am using the following:
- Windows 7
- 4.0.1 windows wallet

**Comment by justinvforvendetta** [comment]
blockchain.info is a bitcoin explorer. electrum for verge, should say unverified even if it is verified. if it says pending that means the transaction is just stuck in mempool and will either get processed or bounce back.

**Comment by Syre1900** [comment]
Thanks, Justin!

**Comment by ryanprovofc** [comment]
@justinvforvendetta how long does that usually take? I'm going on 6 days pending..

**Comment by justinvforvendetta** [comment]
if you close the wallet it shouldn't take more than a day or two

**Comment by xtrc** [comment]
@justinvforvendetta  I'm waiting since the 13th of January along with many others for this one to be confirmed: https://verge-blockchain.info/block/0000000000006eb429a9f6d62525c9503df6bdb11d2c8f1f2a4c93c6741b5187

**Comment by Joske2** [comment]
Same here. Did a small test on 12 jan.
Block 1793444 still 0 confirms.

https://verge-blockchain.info/tx/710bd6cf4ce05e774224e520fce6a9297ebd7e35f9f8673ae9e22c0d1e20569a

**Comment by johnrockson** [comment]
yeh same problem I have.  Transaction showing confirmations but BLOCK has zero confirmations.
Block 1807816

https://verge-blockchain.info/block/000000000000a183412f6666f0c17ab7f07ba494cffc8f6d628c1ec8b88702c1

@justinvforvendetta said to wait a day or two.  I exited my wallet like he said to, I hope it works. 

Seems like a lot of people are having this issue.

**Comment by tycmxc** [comment]
Same issue, transaction confirmed, but 0 BLOCK confirmations. lets see what happens in a few days.:

https://verge-blockchain.info/tx/0952ebb54f42b91f491bd9c0740e7c87bedda7b99002a7c5fbf05f85a60b7f82

**Comment by johnrockson** [comment]
UPDATE:  I got my coins back, I think. I just did what @justinvforvendetta said to do.  Close your wallet for a day or 2.  It should come back to it.  I'm still confirming things, but it looks like I got my coins back.  

Also @benammann is very helpful with the new verge qt wallet, seek him out if you still have issues.

**Comment by justinvforvendetta** [comment]
update to wallets that were released last night please
