### ISSUE TITLE
Transaction (Entire block) unconfirmed since the 12th of January. 

### ISSUE THREAD

**Issue by xtrc** [vergecurrency/VERGE#509]
# Issue Template

## Context

I send a transaction from my electrum wallet to the Verge-qt wallet (4.0.1). I first did a transaction of 10 XVG but my 3000 XVG transaction has been stuck in a limbo for some time now :) Wallet is synced. 

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

Transaction details:

 **Status: 0/unconfirmed
 Date: 1/12/2018 21:51
 From: unknown
 To: DAtFETTHG2JmrWyN2NPBchJLYm2VZ6ZtNG (own address, label: My wallet)
 Credit: 3,758.00 XVG
 Net amount: +3,758.00 XVG
 Transaction ID: 5020d4a7439258d56065e5ee84f30f7c9bb7b9cf00b5c456f8a95c739e1d8876**

getrawmempool

`[
"004cb438a63d24b7a786958f256e627f16ba94ce8c94bbc601122006400eea94",
"18cd0f4f2904fb880b0006448af92e45be6c4b1b6dae51198719800977fd8978",
"2b27e3da8c9fd72124761c21038e8c868057c58c976aa665412ac72af1b2c677",
"5020d4a7439258d56065e5ee84f30f7c9bb7b9cf00b5c456f8a95c739e1d8876",
"63476637f63925da53f752980f513ca624964cbd01987f889bfebbd27235cae4",
"6bdc784f8c73f39079000edcb40c3c155566863be8e5460f4c34f64cd82f3ff6",
"6c74054b9d500718c1c91162c5d06e356ed61a873a87953ebfd7b6700a505837",
"77b442009762b2c8170b5aab5af8295a3dba5b942832d70a43345812c9d05fe6",
"922d5e0a2d9664517c00b56b2022319bd5ce51a7a3ce059317db7abbb0f38e68",
"9a5811f29cd3dc29554df29ec1c6ae65ce002af8bf26f43b12a297f89e4aa64f",
"c6c0045c1782c51359583a6d66275f0ac07f96b4286606c92adedaf7e4e1fde6",
"cbd5d9cad622bde4f34086623f9c36adf348b97da258b09a564d098837df4f7b",
"d5d9bab41e86629d6cfd30e5a201bde721530addbd426878a6d41f90b98f4d42",
"d6c4b8ddc9d65e136a4c9efd456116a1be58ffeff447f37c9141fc9946c8886a",
"ef5454ce8e7b370425a8c69846d6ab77a40b0f28cf28f5392a687bd290b56703",
"ffb0bffae754bdaecc0068c8929d1cd956f51f495fc99cbf236fe8bcb9861c0f"
]`

## Expected Behavior

For the transaction to be confirmed. 

## Current Behavior

Transaction stays unconfirmed. 

## Screenshots

n.a.

## Steps to Reproduce (for bugs)

* Steps :
1. Send XVG from Electrum wallet to Verge wallet.
2. Wallet is synced
3. The transaction is confirmed but the block is NOT. 
4. Wait?

## Your Environment

* Verge Release: 4.0.1
* CPU: Intel 2500K 
* GPU: MSI GTX 1080
* RAM: 16 GB RAM
* OS: Windows 10

**Comment by benammann** [comment]
#490

**Comment by xtrc** [comment]
@benammann Is that workaround been confirmed by @justinvforvendetta ? If not, I rather wait for him to see what the best approach is to this issue. Would waiting for the hard fork solve this issue?

**Comment by xtrc** [comment]
@benammann Your proposed solution is not working.

**Comment by justinvforvendetta** [comment]
not sure what you mean by a block being unconfirmed. transactions that arent confirmed during fork, will bounce back.

**Comment by xtrc** [comment]
Did you check the transaction details? It's still unconfirmed...
