### ISSUE TITLE
Wallet not syncing 

### ISSUE THREAD

**Issue by odysseymoney** [vergecurrency/VERGE#510]
Hello, I set up the new wallet completely but it still won’t sync for days now. Any idea how to fix this ? I’m on Mac sierra.

**Comment by gummideepak** [comment]
Try downloading the block chain from https://verge-blockchain.com/ and follow these ( https://verge-blockchain.com/howto ) instructions!

**Comment by odysseymoney** [comment]
How do I find that out ? Please help.

**Comment by ebrinkster** [comment]
What version of boost do you have installed?  Find out with `brew info boost`, if it is 1.66.0, then this version currently isn't supported yet.  This is outlined in issue #418

**Comment by odysseymoney** [comment]
The blue lights in the bottom right show up

**Comment by odysseymoney** [comment]
I’m not sure I have boost installed

**Comment by ebrinkster** [comment]
Refer to the instructions here (https://github.com/vergecurrency/VERGE#os-x-wallet) -- @justinvforvendetta I'm 90% sure there is an issue with the macOS wallet builds, I've tried to set up a clean one multiple times over the last 2 days without luck.  I have a Win client that is syncing just fine.  Even done blockchain download on macOS and install, still no luck...

**Comment by simon-onemob** [comment]
@justinvforvendetta We need to research a way to sync wallet faster. I'm two days in syncing and it's just half way. If Verge is for everyday user, then we should make the wallet UI and UX seamlessly for everyday user. My grandma has not much time left waiting for the wallet to sync up :D

**Comment by odysseymoney** [comment]
I totally agree. I think this is main problem with Verge. Why can’t we have a reliable wallet? Not everyone knows all the technological side of things. Easier it is the quicker it’s mainstream.

**Comment by ebrinkster** [comment]
@simon-onemob the sync process occurs over tor, so naturally it will be slow.  Additionally, this time is alleviated by downloading the blockchain from the web (not ideal, but won't go into that) and performing a sync from the latest version of the blockchain.  I've had no issues with the windows wallet, but plenty with the macOS wallet.

Side note, if possible I'd recommend keeping the topic of this specific issue to @odysseymoney 's issue of wallet not syncing.  Leverage other communication to discuss features of verge so @justinvforvendetta can focus on individual github issues for easy development.

**Comment by odysseymoney** [comment]
Wallet still won’t sink. I love Verge but it took a couple minutes on my Mac for COLX to sync

**Comment by justinvforvendetta** [comment]
bitcoins core wallet takes 11 days to sync. just fyi.

**Comment by odysseymoney** [comment]
Good to know. Thanks. I don't mind how long it takes to sync. Just want to be sure I'm doing everything right.
