### ISSUE TITLE
"No connection" - Android Tor Wallet (Verge TORdroid v1.1)

### ISSUE THREAD

**Issue by AdamDenoon** [vergecurrency/VERGE#511]
I downloaded the Android Tor Wallet on January 16, 2018, and have only been able to establish a single, momentary connection within hundreds of attempts.

I have a Samsung Galaxy Note 4, and have tried both the Google Play version and the APK downloaded directly from vergecurrency.com. I have Orbot installed, running, with VPN mode ON, and with Verge checked (I've also tried with all apps checked, all unchecked, only Verge checked, all but Verge checked, and with VPN mode OFF). No amount of refreshing or restarting the app or Orbot is resulting in a connection. My internet (WiFi) connection is working well for other apps.

Orbot is the newest version (16.0.0-RC-2-multi-SDK23 / Tor 0.3.1.9-openssl1.0.2k).

I've seen this exact complaint plaguing r/vergecurrency as recent as a week ago, so I'm a bit surprised to not see an open issue on this. I'm also glad to have opened it, and am looking forward to the fix so Verge can keep rockin' it!

**Comment by powerthinking** [comment]
I am in the same boat. I started to open an issue earlier today but got distracted. 

I have a Galaxy S8+ and v1. 1 of the Android Verge Wallet.

I get a connection about 1 out of every 20 attempts. I have tried every combination of restarting Orbit and the wallet, including rebooting my phone. 

It also shows my wallet balance as 0 for most of those attempts.

I hope this helps.

**Comment by AdamDenoon** [comment]
@powerthinking, this didn't work for me, but have you tried switching the "VPN Mode" to ON in the Orbot app, and making sure Verge is checked in the list of Tor-Enabled Apps, then restarting Verge?

**Comment by ceezbomb** [comment]
i have the same issue, on s8

**Comment by tasmannelson** [comment]
I spent a week receiving and sending 10 xvg worked perfectly.  Balance was up to date.   Since I put a big deposit in the issues started, it has not worked at all for about 5 days.

**Comment by tasmannelson** [comment]
I have been into Google play and there is a special note  regarding  balances showing "no connection" for the verge tor app.  I have followed this  yet still have a 0 balance.  It says go top left screen on orbit?  (nothing there on my menu)  it asks to re-toggle vpn in settings menu and everything should work.    Verge really need to pull their finger out.  A fantastic product is going to get wasted at this rate.  Any devs reading can you help or advise please.  I am confident my 1000s of verge  are safe but would feel better if the wallet showed my balance

**Comment by powerthinking** [comment]
@AdamDenoon, yeah I tried it, as well as enabling all apps in Orbot vs just Verge. I can only read my wallet with my coins and transactions about 5% of the time and I have yet been unable to send any coins due to the No Connection issue.

Also to note that I have the problems viewing my wallet with or without Orbot enabled

**Comment by powerthinking** [comment]
I'm taking a look at the code related to the Android wallet to see if I can find the problem.  Based upon some feedback from the pools on another thread, I'm wondering if it might be a timeout issue related to Tor???  I'll let you know if I find anything.

**Comment by Vadim-Podlevsky** [comment]
Joining to the club. My android Verge wallet worked nicely until Orbot App updated (I noticed by a slighrly changed interface). Since then I tried Anabling/Disabling VPN, toggling Verge checkbox, toggling Bridges - nothing helped. Infinitely trying to connect... and showind 0 balance. This is my mining wallet and funds are practically locked which is not fun. Any help from devs?

**Comment by zsuerdieck** [comment]
I have Google Pixel XL and Orbot installed. The latest Orbot did change some things with how the Verge android app worked, at least for me. With the latest Orbot app try this:
Ensure Verge is listed as Tor-Enabled App (in Orbot)
VPN Mode is enabled (in Orbot)
VPN -> Ensure Orbot is disabled (in Android Network settings)

Re-open Verge android app and try to refresh. These steps worked for me.

**Comment by justinvforvendetta** [comment]
it should be back up very soon, we had to update the code on the servers

**Comment by powerthinking** [comment]
I have a fix for the Android wallet that will display the wallet balance with "No connection", "Synchronizing" and "Synced" statuses.  

I think people would feel a lot better if they can see the balance even if the server connectivity has a problem.  Having the wallet show as blank when there is network issues is a bit of a freak-out.

@justinvforvendetta - Are you guys using anything special or just Android Studio to create your APK?  I'll create one and test out the changes on my phone and share with others to test on older phones.

**Comment by MeanAngryVeteran** [comment]
Anybody up?

**Comment by brobrojrod** [comment]
Good luck its so far in rhw cloud no one geta nothing you dig

**Comment by MeanAngryVeteran** [comment]
justinvforvendetta  
Said it should be back up very soon, we had to update the code on the servers

I'll go run some errands and check in later  Thanks

**Comment by justinvforvendetta** [comment]
yeah android servers are updating to the newest master branch, should be done very shortly. sorry, should have announced it. figured it wouldnt take more than an hour.

**Comment by FedericoCalz** [comment]
It does not work yet.
any suggestions?

**Comment by daehbew** [comment]
just joining the group. having the same issues... looking forward to a solution. a video would be nice.

**Comment by Tarmo1234** [comment]
This so frustrating, whats up with one hour job? when we gan get in the wallet?

**Comment by JSBachForSoulCleansing101** [comment]
Same issue here...have only seen zero balance for a couple of days now....any news?

**Comment by omar200329** [comment]
same I keep getting no connection

**Comment by tasmannelson** [comment]
I only see one difference since yesterday, my tor wallet can be accessed without a pincode?  hopefully part of a glitch but none the less worrying.  I can't see my precious so hopefully no one else can.   Come on devs we know you're busy but you are sat in front of a computer (well at least I picture you 24/7 in front of one) write us a few words of encouragement it doesn't take long and we we really like nice comforting coherent sentences that make us feel like we are on the right track.  Not that I'm doing anything with my verge but it's nice to look at it 15 times a day and remind myself what  a great idea it was buying many many months ago.

**Comment by Tarmo1234** [comment]
It's not funny, company has so much billions they don't give a fuck to
explaining the situation?

**Comment by deliriumv** [comment]
@Tarmo1234 Like many coins the Verge project is open source. There is no company, it's developed / maintained and supported by volunteers who give their time free.

**Comment by Tarmo1234** [comment]
So peoples money is gone because of volunteers and nobody knows when the
issue can be fixed because there is no responsibility?

**Comment by deliriumv** [comment]
Your money won't be gone because of connection issues. It's on the blockchain and will be there once you connect.

**Comment by ceezbomb** [comment]
noob question -  can we connect to a different wallet using passphrase...

**Comment by omar200329** [comment]
so when will the connection be bsack up

**Comment by omar200329** [comment]
back

**Comment by deliriumv** [comment]
Amongst a million other things, they're working on it. I don't use the Android wallet so cant really help with connection issues with it.  If i did use it and had connection issues I'd be happy to wait for them to get resolved as I don't need access to the coins immediately. It can take days to withdraw and deposit cryptos to an exchange sometimes.

Maybe I'll install the android wallet later this evening and mess around with it.

**Comment by MeanAngryVeteran** [comment]
Hard fork next week right?

**Comment by MeanAngryVeteran** [comment]
deliriumv
If you can get yours working that would be very encouraging.
Best of luck on this

**Comment by TheLendingCoin** [comment]
I found this writeup which may offer an explanation:

Orweb is broken on Android 4.4.x due to the fact that Google removed proxy setting support in their WebKit component.

**Comment by Tarmo1234** [comment]
I hate so say this, but once you have android wallet you cant restore it on window or IOS, I guess we have to hope that google gives proxy settings support back to Android

**Comment by Vadim-Podlevsky** [comment]
So all Android wallets are locked until Google decides to enable proxy settings support back to Android? Sounds like a huge issue. :( Got to switch mining to another wallet then.

**Comment by Tarmo1234** [comment]
major drop for XVG :(

**Comment by Vadim-Podlevsky** [comment]
@Tarmo1234 Will buy more if so ;)

**Comment by AdamDenoon** [comment]
Does the Google issue effect anything in Android >4? I have Android 6.0.1

I've heard of people using the Android Tor recovery phrase to recover their wallets into Coinomi, if you need to move coins to another Verge wallet in the meantime.

@Tarmo1234 If it's dropping, I hope it drops a lot so I can load up on a ton more XVG ;)

**Comment by Tarmo1234** [comment]
I have Android the latest, but nope not working. How that Coinomi works?

**Comment by AdamDenoon** [comment]
@Tarmo1234 http://lmgtfy.com/?q=Recover+wallet+using+coinomi

**Comment by AdamDenoon** [comment]
I've heard of serious security vulnerabilities with the Coinomi wallet, so DO YOUR OWN RESEARCH BEFORE DOING THIS.

**Comment by Tarmo1234** [comment]
I just wanna send them to Binance

**Comment by justinvforvendetta** [comment]
our wallet is different because it is using tor and connecting to hidden services, but yes we have the tool on our website that will let you convert a seedphrase into a private key. also the Android servers should be back up soon, had to update the verge code on them, and a new Android update will come out that has more servers as well

**Comment by justinvforvendetta** [comment]
vergecurrency.com/seedphrase

**Comment by Tarmo1234** [comment]
Thank You AdamDenoon for a professional help!

**Comment by AdamDenoon** [comment]
Ignore what I said about Coinomi! It may have serious security flaws, and I didn't know we had a seedphrase tool on our site. Thanks, @justinvforvendetta for the helpful info, and keep up the amazing work!

**Comment by fareszr** [comment]
I want to use the wallet in my computer how ?

**Comment by fareszr** [comment]
i want to convert my android wallet to verge 4.0 wraith protocol

**Comment by AdamDenoon** [comment]
@fareszr, are you wanting to recover an Android Tor wallet using a Verge desktop wallet? Keep in mind this is only necessary if you need to do something with your Verge coins before this issue is resolved.

**Comment by fareszr** [comment]
i want to switch to the desktop wallet because its more stable

**Comment by fareszr** [comment]
is there a way to import my mobile wallet into the desktop app ?

**Comment by AdamDenoon** [comment]
@fareszr, 

Like @justinvforvendetta said, use https://vergecurrency.com/seedphrase to convert your recovery phrase into a private key, which you can use to recover your wallet in the wraith version.

**Comment by fareszr** [comment]
how ?

**Comment by AdamDenoon** [comment]
@fareszr, You'll have to refer to the github documentation on the Wraith wallet. Please leave this particular thread for discussion of the relevant issue.

**Comment by justinvforvendetta** [comment]
just an fyi, android servers are coming back online right now.

**Comment by zsuerdieck** [comment]
Just confirmed my Android verge wallet is now connecting and showing balance.

**Comment by deliriumv** [comment]
new install of Android wallet is connected.

**Comment by justinvforvendetta** [comment]
great. the other android servers are still coming online. i had to make sure they had the latest pulls from here, so they didnt fork. not that anyone would lose their coins, would just be a pain in the butt.

**Comment by TheLendingCoin** [comment]
I have confirm that it is also working on my devices.

On Jan 19, 2018 6:24 PM, "Zach" <notifications@github.com> wrote:

Just confirmed my Android verge wallet is now connecting and showing
balance.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/vergecurrency/VERGE/issues/511#issuecomment-359133133>,
or mute the thread

**Comment by fareszr** [comment]
yay finally !!!!

**Comment by justinvforvendetta** [comment]
they wont need to be updated again anytime soon, and next time if i do update t hem for any reason, ill do them one at a time so theres always a connection.

**Comment by tasmannelson** [comment]
Nice work fellas.

**Comment by AdamDenoon** [comment]
Good to go! Keep on rockin it guys!

**Comment by ceezbomb** [comment]
Thank you for the support!

**Comment by MeanAngryVeteran** [comment]
This is Great! I just checked  mine and it stated working after I rebooted.. Thanks team Verg

**Comment by maestrus** [comment]
but someone can please  post a step -by step guide to convert  recovery phrase into a private key and import in qt wallet?thak you so much

**Comment by iMagicOne** [comment]
Yes please, i have the same problem.

**Comment by justinvforvendetta** [comment]
yeah we can make a video on how to convert a seedphrase into a privkey. you can also just send coins from Android to electrum though

**Comment by maestrus** [comment]
@justinvforvendetta  a video is great solution.Could help many people.
Thank you

**Comment by CryptoGuru1** [comment]
I'm still having issues. Android wallet simply won't connect. Any help would be appreciated.

**Comment by AdamDenoon** [comment]
@CryptoGuru1 Have you tried switching the "VPN Mode" to ON in the Orbot app, and making sure Verge is checked in the list of Tor-Enabled Apps, then restarting Verge?

**Comment by KbZaDqBtA** [comment]
I am having this same issue now just a month later.  @justinvforvendetta Is there maintenance being done on the android servers.  I have not been able to establish any type of connections for 2 days.  I have tried all suggestions to no avail including suggestions from #wallet-help in Discord

**Comment by CryptoGuru1** [comment]
Yup me 2. No connection woes. Again!

**Comment by AFarpa** [comment]
@fareszr 
Hello there .. I`m quite new on this  kind of things but a pretty find how to import ( get the private key ) from verge android wallet into a desktop  wallet..
I tried to many time  install the android app, orbot vpn  , installing in other devices ( Note 8 , S8+ ( all home are Samsung devices) I also had a shot on Bluestack android  and couldn`t connect ..
 Finally I got a pretty working solution..

First how to find  a private key from an address IF ONLY you have still the Mnemonic Code !! 
As you know ( as I think ) its not possible to see the  private key from app Verge wallet but if you have the Mnemonic Code  ..I can help you to get  yourself it ( no need me to do it )  and import it to another  windows wallet .
You just have to download the windows wallet ( Windows electrum wallet ( don`t need to wait to synchronize all block through ) .
if you want help on it please let me know as I will be  glad to help you further 

Any tips are welcome into 
Verge: DUTBCuKiwZekZjwvNPuw5e4RPdX26LBCHZ
Or BTC : 1AFSF15QJwahfvCYxZByJWQudouZHKmJhW

**Comment by soulrific** [comment]
I still can't open my Verge Tor Wallet.  Last time it was opened was 2 days ago to check funds.  Now, just like so many others, no connection.  Ive tried so many things to get it to connect, but to no avail.   Any resolution to this problem would be much appreciated.

**Comment by Vadim-Podlevsky** [comment]
I've moved my private key to electrum wallet from my android device because it's practically unusable, unfortunately.

**Comment by airmail2matt** [comment]
I am on Galaxy S9 and it doesn't work for me either. Anyone find a fix yet?

**Comment by TheLendingCoin** [comment]
Launch your Verge wallet from the Orbot app by clicking on your Verge
wallet from within the Orbot app and it should play nice.

**Comment by tasmannelson** [comment]
It's happened AGAIN?  why?  please verge let us know why I can't see our balances it's been 3 months of a perfectly working wallet now I have had 4 days with 0 balance and No Connection?  Can yku ollease advise on a 100% reliable wallet that I could use.  If my bank said 0 I would be straight in there.   I don't find this funny, not do I find it helpful in anyway.

**Comment by justinvforvendetta** [comment]
@tasmannelson can you check your connection on orbot? i can see activity, and mine is connecting.

**Comment by tasmannelson** [comment]
Hello thanks for getting in touch.  I am unable to try now as my wallet is gone? (I have no answer for that one).  The verge app is there but to create or restore a wallet.   My back up phrase is locked away so will be Sunday New Zealand time before I can restore my verge tor wallet.

**Comment by tasmannelson** [comment]
Hello again.   Sorry for the delay my private keys are kept extremely secure.   I have recovered my wallet and it's working fine in fact working faster than before.  I can only assume it was my phone.   I am moving to apple iphone/mac book so what would work better in your opinion.  Obviously ledger is king but until then..........

**Comment by iMilnb** [comment]
This is still happening. Tried on two different phones. Worked last week, and since yesterday the famous "no connection" yada yada is back.

**Comment by marpme** [comment]
@justinvforvendetta can you have a look ^

**Comment by justinvforvendetta** [comment]
still having this issue?

**Comment by iMilnb** [comment]
@justinvforvendetta now it's working perfectly on both devices

**Comment by anekdot** [comment]
hi everyone, i am having the same problem now, i've sent verge coins to my android wallet but my wallet's connection is off so i can't see by coins. I did all necessary things spoken in this page but it didn't work?
