### ISSUE TITLE
Verge Wallet OSX HIGH SIERRA issue 

### ISSUE THREAD

**Issue by Jedonauta** [vergecurrency/VERGE#513]
Hi There how are you? Thanks for your time first of all.

I ve sent 146 coins from an exchange to my Electrum-Xvg wallet that i downloaded online or mac osx running high sierra, as the other verge wallet wasn t working.

I also tried to install the other VERGE wallet  following the steps on this link and doing everything correct:

https://github.com/vergecurrency/verge-core-installers/blob/master/README.md

Now the Electrum-Xvg seems to be offline , but it looks like the transaction went through at the correct address ﻿﻿:

I just would like to know what i can do, how can i send my verges to an exchange? please let me know...it says it s not connected.

Cheers
I was also told to search for the wallet.dat file which isnt there thought are are 2 other dat files but not that one, seems like the coins are stucked in the blockchain.
can anyone help please??

**Comment by MeanAngryVeteran** [comment]
https://github.com/vergecurrency/VERGE/issues/511

Hold off until they fix it....Down for everyone
They're working on it ..

**Comment by MeanAngryVeteran** [comment]
Link is here
[https://github.com/vergecurrency/VERGE/issues/511](url)
