### ISSUE TITLE
Hello you

### ISSUE THREAD

**Issue by Mrtrung123** [vergecurrency/VERGE#514]
# Issue Template

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by Mrtrung123** [comment]
Dear support!
I’ve bought ?verge
 from vicuta in Viet Nam and they confirmed they’ve sent the coins to my wallet at the address:( DUT4kqetiSLostEiCjii9s6nt8mLtoncJK ) .They also sent me the link as an evidence:
https://verge-blockchain.info/address/DUT4kqetiSLostEiCjii9s6nt8mLtoncJK .However,up to now,the balance in my verge wallets show no coins. please help to verify and solve this problem. Thank you very much.

**Comment by Mrtrung123** [comment]
I'm using windows version electrum-xvg-win-amd64

**Comment by justinvforvendetta** [comment]
and you are connected to an electrum server? which one?

**Comment by justinvforvendetta** [comment]
uhm that top picture is the core wallet, the bottom link is a link to electrum, a different wallet. but in the first picture i can tell you arent synced

**Comment by Mrtrung123** [comment]
on page: https://verge-blockchain.info/address/DUT4kqetiSLostEiCjii9s6nt8mLtoncJK
still reported the number of coin in my wallet

**Comment by Mrtrung123** [comment]
So you help me how to synchronize, and I can get the coin number on my wallet

**Comment by justinvforvendetta** [comment]
let it sync. if it stops, close it and open it again.

**Comment by Mrtrung123** [comment]
![image](https://user-images.githubusercontent.com/35588468/35135325-1a3c680a-fd0f-11e7-95ad-cb6cd1b2ef5d.png)

**Comment by Mrtrung123** [comment]
ohh This I did then you, it has synchronized several times already, but when exits I open so one time it runs synchronously this way,
Is this my grandmother's problem?
I find complex for the user.

**Comment by Positivism** [comment]
Allow it to finish syncing first, you are several hundred thousand blocks behind, leave it open and wait.

**Comment by Mrtrung123** [comment]
But what if the sync finishes still does not receive the coin?
do you have any solution to help me. thanks you

**Comment by Positivism** [comment]
Close and reopen the application after the sync finishes.

**Comment by Mrtrung123** [comment]
Let it sync finish and finish it, then reopen,
But I'm not sure that the numbers are worth my wallet?

**Comment by Positivism** [comment]
If you're still having problems after the sync finishes come back here and we can redress the issue.

**Comment by Mrtrung123** [comment]
2 contrasted opinions.
Someone told me to close it and open it again
a person told him to finish it and finish it, then open it again
How do I do it?

**Comment by Positivism** [comment]
Leave the application open, if the sync stops, close the application, and reopen the application, otherwise allow the application to remain open.

**Comment by Mrtrung123** [comment]
I still have the application open, because there is no sign of application pause, it is still working synchronously

**Comment by Positivism** [comment]
Yes, allow it to sync and please close this issue. If the problem persists after synchronization completes, you may reopen the issue.

**Comment by Mrtrung123** [comment]
yes, i'm still waiting for it to finish sync, and if the problem is not resolved i will contact you to help me, thanks you

**Comment by Mrtrung123** [comment]
![image](https://user-images.githubusercontent.com/35588468/35135899-b2c44ef0-fd12-11e7-9eeb-c89c1025a0f4.png)

**Comment by Mrtrung123** [comment]
It has finished syncing

**Comment by Mrtrung123** [comment]
![image](https://user-images.githubusercontent.com/35588468/35135932-ec74492a-fd12-11e7-8297-a364d16df2ab.png)

**Comment by Mrtrung123** [comment]
and I closed and reopened it

**Comment by justinvforvendetta** [comment]
it says on the top "OUT OF SYNC" so no, it has not finished. let it finish completely. you still have several h ours left. the coins will show up.

**Comment by Mrtrung123** [comment]
ok you
