### ISSUE TITLE
Hello hep me

### ISSUE THREAD

**Issue by Mrtrung123** [vergecurrency/VERGE#515]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by Mrtrung123** [comment]
Hello, my wallet has finished sync, but still do not see coin on wallet?
I followed your instructions to let it sync, but still do not see the coin.

**Comment by Mrtrung123** [comment]
![image](https://user-images.githubusercontent.com/35588468/35143067-e42c53f0-fd32-11e7-9475-d7106c25bbf1.png)

**Comment by Max-Meldrum** [comment]
@Mrtrung123 No, it still says (out of sync)..

Let it be open for a while until you see that (out of sync) is removed.

**Comment by Mrtrung123** [comment]
But I have been running for a long time, from morning till now, sometimes it's out Sync
Do you know why? or software problems ?

**Comment by Max-Meldrum** [comment]
How is your internet speed? If it is slow, that might be why.

**Comment by Mrtrung123** [comment]
My internet speed is up to international standards,
it is not interrupted

**Comment by Max-Meldrum** [comment]
If you go to help -> Debug console window and enter: getinfo

and paste the output here.

**Comment by Max-Meldrum** [comment]
@Mrtrung123 In the Verge application, there is a help option, this is the one I meant. And from that point, there should be a way to get to the debug console window. Here you can enter commands, in this case "getinfo"

**Comment by Mrtrung123** [comment]
![image](https://user-images.githubusercontent.com/35588468/35147322-c2401cf0-fd40-11e7-8b79-a2fbaa30d8b3.png)

**Comment by Max-Meldrum** [comment]
In the wallet application. Not something else.

![getinfo](https://user-images.githubusercontent.com/11488530/35152422-ba7b9eea-fd22-11e7-8ae3-155db43cfb10.png)

**Comment by Mrtrung123** [comment]
you can provide me link download verge-debug windows ? thanks you

2018-01-19 20:14 GMT+07:00 Max Meldrum <notifications@github.com>:

**Comment by benammann** [comment]
:D you open the VERGE-QT wallet, than you click `Help` -> `Debug Window`

please screenshot what you see

but the most important question: **did you import your private keys ?**

**Comment by Mrtrung123** [comment]
you see verge -debug windows for me
[image: Hình ảnh nội tuyến 2]



2018-01-20 1:14 GMT+07:00 Ben Ammann <notifications@github.com>:

**Comment by Mrtrung123** [comment]
My problem has been resolved, I have received the coin number on my wallet,
thanks you!

2018-01-20 2:14 GMT+07:00 HT Quốc - Trung <quoctrunghg1986@gmail.com>:

**Comment by Max-Meldrum** [comment]
@Mrtrung123 Great to hear!

Feel free to close the issue.

**Comment by Mrtrung123** [comment]
*ITC - IoTchain *
Click link : https://dashboard.xriba.com/go?r=MTAxNDg1OA

Xriba là một giao thức mở tổng hợp có thể ghi lại mọi giao dịch tài chính
trong blockchain và cho phép phát triển các ứng dụng bên thứ ba. Xibra cũng
cung cấp một ứng dụng cho điện thoại thông minh, 2 ứng dụng sổ sách phục vụ
cho cả kinh doanh truyền thống và kinh doanh tiền mã hóa, và một cổng thanh
toán chuyển đổi từ tiền bảo chứng sang tiền mã hóa cho các giao dịch thương
mại.
*Update Announcement*

Airdrop đợt 1 kết thúc sau 2 ngày và phát Token về ví. Bắt đầu airdrop đợt
2: tham gia nhanh nhé mọi người.

Các bước thực hiện:
*1. *Tích vào “Nhận ngay” để đăng ký.
*2. *Check mail xác minh tài khoản
*3.* Làm nhiệm vụ kiếm điểm đổi token.

**Comment by Mrtrung123** [comment]
Xin chào,

Kênh của bạn [HT Quốc - Trung] đã bị chấm dứt do kênh có vẻ như được liên
kết với [Võ Thuật 365] là một kênh đã bị vô hiệu hóa do có từ ba Cảnh cáo
vi phạm bản quyền trở lên.

Có lẽ bạn đã nhận được thông báo về việc chấm dứt kênh gửi đến địa chỉ
email liên kết với kênh YouTube bị chấm dứt đó. Vui lòng kiểm tra hộp thư
đến của bạn (bao gồm cả thư mục thư rác) để tìm thông báo sau:
*Chúng tôi xin thông báo rằng tài khoản của bạn đã bị tạm ngưng do tài
khoản này có vẻ như được liên kết với một tài khoản khác đã bị vô hiệu hóa
do có từ ba Cảnh báo vi phạm bản quyền trở lên.*

Xin lưu ý rằng bạn bị cấm truy cập, sở hữu hoặc tạo bất kỳ kênh YouTube nào
khác nếu kênh đã liên kết không được khôi phục. Để biết thêm thông tin về
cảnh cáo vi phạm bản quyền và chấm dứt kênh, vui lòng truy cập vào Trung
tâm Trợ giúp <https://support.google.com/youtube/answer/2814000#strikes>
của chúng tôi.

Bạn đã thử sử dụng trình khắc phục sự cố về bản quyền
<https://support.google.com/youtube/troubleshooter/6401232> chưa? Lần sau,
bạn có thể tìm thấy cách khắc phục vấn đề nhanh hơn bằng cách làm theo quy
trình trợ giúp có hướng dẫn mà chúng tôi đã tạo cho các vấn đề về bản quyền.

Trân trọng!

Nhóm hỗ trợ pháp lý YouTube


On 05/13/18 15:10:57 quoctrunghg1986@gmail.com wrote:


*ITC - IoTchain *
Click link : https://dashboard.xriba.com/go?r=MTAxNDg1OA

Xriba là một giao thức mở tổng hợp có thể ghi lại mọi giao dịch tài chính
trong blockchain và cho phép phát triển các ứng dụng bên thứ ba. Xibra cũng
cung cấp một ứng dụng cho điện thoại thông minh, 2 ứng dụng sổ sách phục vụ
cho cả kinh doanh truyền thống và kinh doanh tiền mã hóa, và một cổng thanh
toán chuyển đổi từ tiền bảo chứng sang tiền mã hóa cho các giao dịch thương
mại.
*Update Announcement*

Airdrop đợt 1 kết thúc sau 2 ngày và phát Token về ví. Bắt đầu airdrop đợt
2: tham gia nhanh nhé mọi người.

Các bước thực hiện:
*1. *Tích vào “Nhận ngay” để đăng ký.
*2. *Check mail xác minh tài khoản
*3.* Làm nhiệm vụ kiếm điểm đổi token.
