### ISSUE TITLE
unconfirmed transaction in 4.0.1 wallet

### ISSUE THREAD

**Issue by acards** [vergecurrency/VERGE#518]
## Context
New here.. if this is a repeat feel free to point me towards previous issue though I haven't been able to resolve the issue with previous posts. 

Have an unconfirmed transaction that is in the blockchain, deposit was to binance address. amount is trivial but id like to understand what i can do to force confirmation on my wallet. test deposit was successful but i didnt realize my wallet was out of sync when i tried to send funds back to binance. transfer has left my wallet, this was from a week ago and i figured i would come back to it after resyncing . Have had no issue syncing by downloading blockchain, wallet is currently synced

## Prerequisites

* [x] Are you running the latest version?
yes 4.0.1

## User Story:

* "I'm submitting a ... "
  - [x ] support request 

## Your Environment

* Verge Release: 4.0.1
* OS:
    - [x ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

transaction id 
ef27f082bd7001f1c14668cfe0632eb86145b63350ab1aa576518ce8a9f85f15

thanks in advance

**Comment by EpicTMC** [comment]
same thing, im on osx 10.11.6, had a transaction stuck for 10 days (am sync'd with bc):
Transaction ID: c0e58eb8b73117502dbffbcd95b5ae4afcf78b9d0484b829e971e8e2ef715d61
To: smYkj1QLyrtitcLBHKWtpvRysXZFXoVwNtXryLa5A7p2mJLLLeWL4wQ1R7YUxVQKeg5JY2PFsaCia4gsCXZFgimmpXF6KQWanF95T5

![screen shot 2018-01-20 at 12 26 47](https://user-images.githubusercontent.com/16276082/35183395-36f6181e-fddd-11e7-981d-a90a680afe64.png)

public works fine.

**Comment by justinvforvendetta** [comment]
stealth tx's will process after the fork.

**Comment by acards** [comment]
@justinvforvendetta mine wasnt stealth but it bounced back today. keep up the good work! glad to see kinks being ironed out

**Comment by Aergon** [comment]
![image](https://user-images.githubusercontent.com/35868780/35473035-1d902624-037a-11e8-8718-443da8c5e7e0.png)

**Comment by Aergon** [comment]
![image](https://user-images.githubusercontent.com/35868780/35473047-4df45f60-037a-11e8-9de0-07011568ee7f.png)
