### ISSUE TITLE
How do I import tokens from my Electrum wallet to the new Verge qt wallet

### ISSUE THREAD

**Issue by peskyrabbit** [vergecurrency/VERGE#519]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

## Any extra information that might be useful in the debugging process.

I have XVG in an Electrum wallet and I would like to import the tokens into the new qt wallet. I can't just send them across because the Electrum wallet is password locked and I can't access it with the password, I think others have a similar issue. I have the addresses but how can I import them into the qt wallet?

**Comment by justinvforvendetta** [comment]
electrums password system works just fine. you need to export the private key for the addresses, and import them into the qt wallet.

**Comment by peskyrabbit** [comment]
How do I do that, I'm a newbie to all this

**Comment by peskyrabbit** [comment]
I can't export the private key without a password, but it won't accept any of the passwords I put in. I have tried every password I can think of. Is there a way to get around the password?
