### ISSUE TITLE
Please reopen #519

### ISSUE THREAD

**Issue by peskyrabbit** [vergecurrency/VERGE#520]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by Max-Meldrum** [comment]
I took a look at #519 and it is probably easier for you to setup the Qt wallet, then send your coins over to it instead of importing private key etc.. Sure, there will be a small fee of sending it but it will most likely save you time instead of trying to figure out how to deal with private keys and such.

**Comment by peskyrabbit** [comment]
But how can I send them from my Electrum wallet if it is password locked and I can not open it. I have tried every password I use but it will not unlock. This is the problem, how do I bypass the password lock?

**Comment by Max-Meldrum** [comment]
ah, sorry. early morning, missed that you had problem with password.

**Comment by peskyrabbit** [comment]
What can I do?

**Comment by Max-Meldrum** [comment]
If you have forgotten your password, you can restore your wallet using the seed phrase.

"If you lose both your password and your seed, there is no way to recover your money."
http://docs.electrum.org/en/latest/faq.html

**Comment by peskyrabbit** [comment]
I have restored my wallet with the seed. How do I now get my tokens into this new wallet?

**Comment by Max-Meldrum** [comment]
Just to make things simple, I would recommend just sending them to your new wallet. Always try a small test transfer to see that things work before sending the rest.

And feel free to close this issue as it is not really directly related to this repository. (note: I'm not part of the verge team, but i'm sure they would appreciate it if users close their issues)

**Comment by peskyrabbit** [comment]
The problem is I can't send them because I need a password to do this. the password is my problem.

I do thank you for your help, it is appreciated.

**Comment by Max-Meldrum** [comment]
But if you restored your wallet using the seed phrase, you should able to choose a new password?
"However, you can restore your wallet from its seed phrase, and choose a new password."
http://docs.electrum.org/en/latest/faq.html

You can import by using importprivkey in the qt-wallet, but as I said, it is probably easier for you to try to transfer them over.

**Comment by peskyrabbit** [comment]
Yes but I can't send from the old wallet to the new restored one because it asks for a password to send the tokens

**Comment by gummideepak** [comment]
@forget the old wallet once you have created a new wallet with the seed you should be able to send coins from that new wallet itself!

**Comment by peskyrabbit** [comment]
But the tokens are not showing in the new wallet, how do I get them to show in the new wallet so I can send them?

**Comment by gummideepak** [comment]
@peskyrabbit While creating a new wallet, did you select the type as ‘I already have a seed’ and proceeded to input your seed phrase!? By this way it allows you create a new password for that wallet

**Comment by peskyrabbit** [comment]
Yes I did that

**Comment by gummideepak** [comment]
Is the address of the old wallet in which you have 300k XVG and the address of the new recovered wallet is same? @peskyrabbit

**Comment by peskyrabbit** [comment]
Sorry I'm not sure what you mean.

**Comment by gummideepak** [comment]
@peskyrabbit Yeha the blockchain address. If you recovered the wallet using the same seed correctly those addresses should match both in the old wallet and new wallet!

**Comment by peskyrabbit** [comment]
No the addresses are all different

**Comment by gummideepak** [comment]
@peskyrabbit then the seed you used is different or wrong!? Try downloading the wallet to other location and try again with the seed phrase!

**Comment by peskyrabbit** [comment]
I will try again tomorrow, it is very late here now, tired now going to bed.

Thank you for your time and help.
I will speak with you again.
