### ISSUE TITLE
TX completed, blockchain explorer displaying the right balance but all wallets stays at 0.00

### ISSUE THREAD

**Issue by blackloaderz** [vergecurrency/VERGE#522]
# Issue Template

## Context

I initiated a transaction with Windows Wallet 4.0.1 on the 14th of January
TX: a9a1a6abf56e5dbfa50b53e3faab1b3da693937b13758e881f97bd0f81c768da

Originally, it was supposed to be a Stealth transaction.
Funds have been sent to a Stealth Address, but after that a regular address appeared on both sides.

Address: DAuchLmMZm8Sz2b6MbmgMMQdPWPFLYdUZA

1.4 XVG has been confirmed 3 days later to the address:
https://verge-blockchain.info/address/DAuchLmMZm8Sz2b6MbmgMMQdPWPFLYdUZA

On the wallet that has been used to send 1.4 XVG, the TX remains unconfirmed:
![capture 2018-01-20 a 14 08 49](https://user-images.githubusercontent.com/35048711/35183776-b36d6fd8-fdeb-11e7-84b1-404789a7bb2d.png)

On the wallet that own the destination address, the balance remains 0.00

I tried to export the private key, and import the key in others wallets:
- Electrum Windows (new wallet from existing private key)
![capture 2018-01-20 a 14 13 46](https://user-images.githubusercontent.com/35048711/35183805-2f0449d2-fdec-11e7-881e-61c13a8d5221.png)

- Synced some new full XVG Wallet (3.0 & 4.0.1) same issue, balance 0.00
- Used a bunch of -rescan command, same issue, balance 0.00
![capture 2018-01-20 a 14 44 36](https://user-images.githubusercontent.com/35048711/35184078-125bd386-fdf1-11e7-85a7-cbf3f5bf4b0c.png)
![capture 2018-01-20 a 14 44 51](https://user-images.githubusercontent.com/35048711/35184080-17bc76aa-fdf1-11e7-9549-b99a0f3e9e46.png)

## Prerequisites

* [x] Are you running the latest version?
I tried all versions. I also tried to import the private key into the Windows 3.0 Wallet.

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

I tried everything I could to import my private key, but it doesn't work at all.
It's like if my private key is incorrect but still import the right address anyway.

I've got 1.4 XVG, that's not a big deal but I want to prevent this from happening to other users.

Cheers.

**Comment by blackloaderz** [comment]
I guess I found a part of the problem:
https://verge-blockchain.info/address/DTamRKDRq6fkBNXBPHQ2grCTs21hc2fCLC

I was accidentally able to double spend the coins from this address.

I think that my previous address DAuchLmMZm8Sz2b6MbmgMMQdPWPFLYdUZA is like corrupted and the coins are lost.

I hope this is a temporary issue from early wraith apps and that it's not happening on a large scale.

**Comment by justinvforvendetta** [comment]
the first transaction was not done. also, that isnt the newest windows wallet.

**Comment by blackloaderz** [comment]
Indeed.

The address is not found here:
https://prohashing.com/explorer/Verge/

But is found on this one:
https://verge-blockchain.info/address/DAuchLmMZm8Sz2b6MbmgMMQdPWPFLYdUZA
With the TX
https://verge-blockchain.info/tx/a9a1a6abf56e5dbfa50b53e3faab1b3da693937b13758e881f97bd0f81c768da

There's a difference between the two explorers.
In a way, the TX has been proceeded ? partially ?
