### ISSUE TITLE
Help ME!!! Pending Transaction

### ISSUE THREAD

**Issue by CrispyBacon925** [vergecurrency/VERGE#523]
# Issue Template

## Context
I have been waiting for about 7 days for this transaction to go through I'm using The verge-qt version 4.0.1 wallet 

## Prerequisites

* [Yes] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [Yes] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac
    - [/] I'm using Windows

**Comment by jrsikors** [comment]
Need a lot more information to begin helping..

What's the TX number?  
What's the public address?  
Are you sending FROM your Verge client or TO your Verge client?

**Comment by jrsikors** [comment]
and check out:
https://github.com/vergecurrency/VERGE/issues/506

**Comment by justinvforvendetta** [comment]
also no link the explorer tx
