### ISSUE TITLE
Electrum wallet error!!  cx_freeze error when opening wallet

### ISSUE THREAD

**Issue by Fredz1** [vergecurrency/VERGE#524]
# Issue Template

## Context

My electrum XVG wallet will not open at all.  I have version 2.4.1  which I believe is the latest currently.
When I open the exe it gives me an error "cx_freeze :python error on main page. "

I cannot find any tangible solution to fixing the problem.  Thus far I have redownloaded the wallet and it gives me the same error.  This error only occures with this specific wallet as I can open my BTC electrum wallet just fine. 

If I can get a electrum wallet working I would like to move it to the verge wallet.

## Prerequisites

* [ ] Are you running the latest version? Yes

## User Story:

* "I'm submitting a ... "
  - [ ] bug report

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions. Provide a general summary
ible except for under certain conditions. Provide a general summary of the issue in the title of your issue -->

## Screenshots

![cx freeze](https://user-images.githubusercontent.com/29452659/35189309-76844636-fe50-11e7-904d-256eb9a08a93.PNG)

## Possible Solution

If I can open the wallet I would like to transfer the currency to the normal wallet

## Steps to Reproduce (for bugs)

It was spontaneous.  One moment it was working and the next time I tried opening it, it wouldnt open.  No changes were made to my PC either.

## Your Environment

* Verge Release:
* CPU: I5
* GPU:1070
* RAM:16
* OS:
    - [ ] I'm using Windows

**Comment by justinvforvendetta** [comment]
strange. try right clicking and running it as an admin

**Comment by Fredz1** [comment]
Appologies.
I tried running as admin but receive the same error message.  
Should I close this issue and repost to electrum?

**Comment by justinvforvendetta** [comment]
yes
