### ISSUE TITLE
Is the Verge QT 4.0 wallet okay for the hard fork 

### ISSUE THREAD

**Issue by dipstidz** [vergecurrency/VERGE#527]
# Issue Template

Is the Verge QT 4.0 wallet okay for the hard fork or do I have to upgrade to the 4.0.1? Having problems with the upgrade

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
what problem are you having with the update? its almost the same thing. and no, the 4.0 will not be compatible once the 4.01 one switches over.

**Comment by dipstidz** [comment]
As soon as I start up the 4.0.1 it doesn't run... It just disappears..

**Comment by justinvforvendetta** [comment]
what operating system? if you're on windows, do ctrl+alt+delete and make sure you see it running in processes

**Comment by dipstidz** [comment]
It's ios High sierra

**Comment by justinvforvendetta** [comment]
oh, we tested it on high sierra and so did several other people. you dragged it into applications?

**Comment by dipstidz** [comment]
Yes I did... I let me see if I can send a Screenshot

**Comment by dipstidz** [comment]
![screen shot 2018-01-21 at 18 47 34](https://user-images.githubusercontent.com/35659277/35197729-9356d360-fedb-11e7-9e1b-474723b32802.png)

This comes up and disappears, without loading up

**Comment by dipstidz** [comment]
it does not load up or open up, just comes on and disappears

**Comment by justinvforvendetta** [comment]
are you sure it's not still running though? did you click elsewhere for it to go into background?

**Comment by dipstidz** [comment]
![screen shot 2018-01-21 at 20 20 14](https://user-images.githubusercontent.com/35659277/35198595-f8b2a6d2-fee8-11e7-8fb0-efe6287c9806.png)


Thank you so much Sunerok for personally attending to my issue, I feel honoured.....Its all good now

Thank you so much
