### ISSUE TITLE
4.0.1. fork for stealth

### ISSUE THREAD

**Issue by Pele51** [vergecurrency/VERGE#528]
I have the Qt4.0.1 wallet after the hard fork i read i have 6 days to uptade my wallet, that means i just have to download the zip file? As i use win7 and but my wallet.dat there and i can delete the old qt4.0.1 wallet or i have to keep it? Also do i should keep the verge blockchain, sorry but i get confused im not so good as many others in computer stuff, thx in advanche!!

**Comment by justinvforvendetta** [comment]
just remove the old wallet and use the new .exe and you're fine
