### ISSUE TITLE
Brew

### ISSUE THREAD

**Issue by odysseymoney** [vergecurrency/VERGE#529]
xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew install boost

How do I execute this command on my mac sierra. Trying to figure out why my wallet wont sync

**Comment by justinvforvendetta** [comment]
in terminal

**Comment by odysseymoney** [comment]
Thanks everyone. I downloaded and installed the wallet on both mac and pc. just finished syncing on my mac. Very excited!
