### ISSUE TITLE
Lost Verge Currency 

### ISSUE THREAD

**Issue by mikel2005** [vergecurrency/VERGE#530]
Downloaded Wraith now all the currency from my electrum wallet has dissapeared what should i do?

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
this doesn't make sense. you must not be connected to an electrum server.

**Comment by mikel2005** [comment]
I have found it was in the wrong wallet. How do I transfer from electrum to
wallet 4.01 please.

Thanks

**Comment by justinvforvendetta** [comment]
just send it to the other wallets address

**Comment by mikel2005** [comment]
OK thanks

On 21 Jan 2018 21:22, "sunerok" <notifications@github.com> wrote:

just send it to the other wallets address

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/vergecurrency/VERGE/issues/530#issuecomment-359282132>,
or mute the thread
