### ISSUE TITLE
**HARD FORK** Which wallets need updated

### ISSUE THREAD

**Issue by theterribletoo** [vergecurrency/VERGE#531]
All wraith wallets need to be updated to the 4.0.1 fork update right?

4.0 needs to be updated
4.0.1 needs to be updated

What about electrum? Will they still work or do they need to switch to the Wraith wallet?<---Ok looks like electrum is all updated

Tor Android Wallet?<---nevermind you confirmed that the TOR is good

Coinomi?
Coinspot?
Cryptopia?

**Comment by mnott** [comment]
What about people holding their Verge on Binance?

**Comment by zsuerdieck** [comment]
Your balance on Binance is fine. Check out the tweet from CryptoRekt https://twitter.com/CryptoRekt/status/955544574025330688

**Comment by mikel2005** [comment]
Im on electrum 2.4.1 will this be effected?
