### ISSUE TITLE
Activate Sizing Handles In Transaction History

### ISSUE THREAD

**Issue by trongod05** [vergecurrency/VERGE#532]
# Issue Template

## Prerequisites

* [X] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [X] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior

You should be able to resize columns when looking at transaction history.

## Current Behavior

If you mouse over columns while looking at transaction history, the resizing handles are not activated.

## Screenshots

![handles](https://user-images.githubusercontent.com/2983459/35214663-8b23f244-ff27-11e7-98e9-f1ff7bdb6b94.png)

## Possible Solution

Allow sizing controls in the transaction history window or any window that has column views.

## Steps to Reproduce (for bugs)

* Steps :
1. Mouse over the column headings in transaction history.

## Your Environment

* Verge Release: Wallet 4.0.1. fork for stealth 
* CPU: Intel Core i7
* GPU: Nvidia Geforce GTX 1070
* RAM: 32G
* OS:
    - [X] I'm using Windows 10
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by Max-Meldrum** [comment]
For me on Linux (Ubuntu 16.04), the resizing handles are showing and working. But the amount one is acting bit strange, gotta go furthest to the right to be able to resize it.

**Comment by trongod05** [comment]
Yeah, I noticed I can resize within the window itself, but one would think the sizing handles would appear on the column headings.

**Comment by trongod05** [comment]
@justinvforvendetta Hey Justin!  Thanks for tagging the issue.  I also wanted to add on that I usually use my laptop with the QT wallet.  My laptop has a 4K screen.  The wallet doesn't seem to scale if you use 4K and set everything to 200% in Windows 10.  I would imagine it is because this is written with QT?  Any ideas on how to get it to look right? Or would this have to be coded as well?

**Comment by jrsikors** [comment]
sizing handles appear to function on 4.0.2, refer to #555 for any new cosmetic issues
