### ISSUE TITLE
please help me exporting my private key

### ISSUE THREAD

**Issue by lawnmowerrr** [vergecurrency/VERGE#535]
Hi Community,

it would be great if you could help me getting my private key out of my Verge Qt wallet on Mac. I synced the whole blockchain, and unlocked my wallet with my passphrase (although it still says "Encrypt Wallet"). I went to the console, entered listreceivedbyaddress 0 true to find out my addresses that are holding my balance. Afterwards I inserted dumpprivkey together with the specific address but the only thing it shows me is either "private key for address is not known" or it shows me "wallet is unlocked for minting only". Also my 2nd question is if I click on "File" and then "backup wallet" does the backup file (.dat) have all the necessary info to set up my wallet on a new computer for example? So lets say I am not able to export my private key, am I still safe as long as I have this backup file on a USB stick for example? Thank you in advance and best regards!

**Comment by justinvforvendetta** [comment]
yes it does, copy your wallet.dat and you can restore your wallet anytime using it.

**Comment by piphoto23** [comment]
how do you restore the wallet from the wallet.dat file because I dont see any options for that

**Comment by zsuerdieck** [comment]
Simply copy it to the wallet location, and start the Verge application.
