### ISSUE TITLE
new fork wallet cant be dowloaded

### ISSUE THREAD

**Issue by piphoto23** [vergecurrency/VERGE#536]
when I click on Verge.dmg this is what comes up

NoSuchKeyThe specified key does not exist.50223128/af5f8920-fe8c-11e7-8df6-653ae38ea5d6E21D91951A676919C7bYxFZXTX0WUZ/XO7ganC8YsfLXtmRir+3cTRDeWVtOXprvJw6Z4mDjr8R6MLtS/cGavaxGolM=

**Comment by justinvforvendetta** [comment]
https://github.com/vergecurrency/VERGE/releases/download/4.0stealth/VERGE-qt-stealth.zip

**Comment by maurodelazeri** [comment]
@justinvforvendetta we cant download the dmg, your link has only .exe

**Comment by maurodelazeri** [comment]
@piphoto23 https://github.com/vergecurrency/VERGE/releases

**Comment by justinvforvendetta** [comment]
its back up, i think there was a small github server issue momentarily. had a few reports of that. both links are up! they were actually rebuilt and posted again a couple of hours ago too =]
