### ISSUE TITLE
Help updating Wallet from 4.0 to 4.0.1?

### ISSUE THREAD

**Issue by Liza11111** [vergecurrency/VERGE#538]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

## Any extra information that might be useful in the debugging process.

Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
replace old wallet with new wallet. done.

**Comment by Liza11111** [comment]
Can someone please help with instructions?

I have the 4.0 wallet for Windows with our coins stored on it.  I have
backed up the wallet.  I have downloaded the updated wallet.

I need help on getting the new wallet installed.  Please can you help me?

Liza LaRosa

**Comment by justinvforvendetta** [comment]
just delete your old wallet .exe file and replace it with the new one =]

**Comment by Liza11111** [comment]
Ok, I’ve done that, thanks very much!  Does this look right?
