### ISSUE TITLE
syncronizing

### ISSUE THREAD

**Issue by Joppis** [vergecurrency/VERGE#541]
# Issue Template
Ive downloaded the new verge qt 4.0.1 but it have been syncronizing 3 days now and im only 11% done. 
is this normal ?

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [x] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by MrASquare** [comment]
Its best to download the blockchain manually. 
Check this https://verge-blockchain.com/howto

**Comment by MrASquare** [comment]
On this page is actually a pretty nice tutorial for this... i didnt know that.
Here is the direct link: https://drive.google.com/file/d/1KxIfooNfgRIghWXvndeyQFkz6bD9yOVr/view

**Comment by Max-Meldrum** [comment]
Most reliable way is to sync it from the start. But, you can as @MrASquare mentioned, download it manually if you want to speed it up. Hope it works out! Feel free to close the issue.
