### ISSUE TITLE
is this good for that fork ? my wallet  version shows  v4.0.1.0-unk-beta

### ISSUE THREAD

**Issue by sampkas** [vergecurrency/VERGE#543]
# Issue Template
is this good  for that new stealth fork??
or what it should show?
because i just install couple days ago that verge-4.0.1-win64 version  
## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by sampkas** [comment]
so i updated that  my verge_4.0.1_win64  that new stealth_zip release  , and now wallet version shows v4.0.1.0-794660a-funky-beta,  everything looks right balance and sync!  
so i think is the right one?  can somebody confirm , who is done this too
thx!

**Comment by deliriumv** [comment]
Yep, that's the latest released version.

**Comment by justinvforvendetta** [comment]
794660a is the most recent windows version. you're good.

**Comment by deliriumv** [comment]
@sampkas A new windows version has just gone up 20 or 30 minutes ago - You need to upgrade to this version. 

https://github.com/vergecurrency/VERGE/releases/download/4.0stealth/VERGE-windows.zip
