### ISSUE TITLE
VERGE-qt: error while loading shared libraries: libdb_cxx-5.3.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by CryptoKaku** [vergecurrency/VERGE#545]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version? Yes

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [X] support request 
  - [ ] translation request 

## Current Behavior

After overwriting the ~/VERGE folder with contents in VERGE4.0-stealth.tar.gz, I ran VERGE-qt.  The error I get is:

VERGE-qt: error while loading shared libraries: libdb_cxx-5.3.so: cannot open shared object file: No such file or directory

What library am I missing? Thanks.

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [X] I'm using Linux
    - [ ] I'm using Mac

**Comment by Max-Meldrum** [comment]
I believe you need libdb 4.8

**Comment by justinvforvendetta** [comment]
where is there a stealth tar.gz?
