### ISSUE TITLE
Mac dmg download file location

### ISSUE THREAD

**Issue by ss77ss** [vergecurrency/VERGE#546]
Hi, 
I'm not seeing the dmg for Mac in the latest release location. 
https://github.com/vergecurrency/VERGE/releases/tag/4.0stealth
Other users claim it was there yesterday but not seeing it anymore.

**Comment by MrASquare** [comment]
The link is here again.
https://github.com/vergecurrency/VERGE/releases/download/4.0stealth/VERGE-Qt.app.zip
But it to my surprise it now requires Mac OS 10.13...

**Comment by ss77ss** [comment]
Thanks.  Is there a reason it isn't a dmg file anymore?  Do we follow the same instruction/steps as if it was the dmg?

**Comment by ss77ss** [comment]
The link isn't valid and now there is something else posted on the releases tab except that it has some June date on it (assuming it is a date).  I'll hold off updating until an official update is provided via twitter in cases there are changes in progress.  
How would we know on GitHub if it is a safe to use version posted on the releases tab?

**Comment by CryptoRekt** [comment]
the new .dmg is now listed.

Closing issue.

**Comment by ss77ss** [comment]
Does this new version overwrite files in the Application Support / Verge folder?
Prior wallets when I updated always showed my balance even if it said out of sync but this one doesn't.  Just give it some time to sync?

**Comment by ss77ss** [comment]
Please disregard.  All set now.  Just had to be a bit patient.
