### ISSUE TITLE
Trying to sync new wallet but its been 5 hours and stuck 7.5 percent completed.

### ISSUE THREAD

**Issue by Cryptoveil** [vergecurrency/VERGE#547]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by CryptoRekt** [comment]
Go here:
https://verge-blockchain.info/
and follow the instructions for your appropriate OS.

**Comment by Cryptoveil** [comment]
I am sorry but I am not seeing anything relevant to my wallet issue . I see public key transactions. Please advise.

**Comment by Cryptoveil** [comment]
I misplaced my seed recovery phrases created a new wallet and new seed phase.
I recently found my orginal seed phrase .The question is how do I get back my coins from the blockchain?
