### ISSUE TITLE
Mac Wallet Sending and receiving but wallet reads 0 of 6 confirmations

### ISSUE THREAD

**Issue by richardvalenciano** [vergecurrency/VERGE#548]
My wallet is synced and transactions are going through. My sent transactions aren't reflecting they went through on my wallet; in other words the check mark. It shows the question mark and says 0 of 6 confirmations. I would really like to see the check mark so I don't have to confirm with the receiver.

**Comment by justinvforvendetta** [comment]
sounds like you didnt download the newest wallet. download it again, replace the one your using, let us know.

**Comment by richardvalenciano** [comment]
Download it from the wallets on vergecurrency.com? I downloaded it yesterday. 

If I pull it from there again and replace it will my coins disappear?

**Comment by ss77ss** [comment]
download from here: https://github.com/vergecurrency/VERGE/releases/tag/4.0stealth
You want the dmg file. 
Coins won't disappear as long as your /Users/<your user id>/Library/Application Support/VERGE folder has the correct wallet.dat file in there.
To be safe, take a backup of that file.
