### ISSUE TITLE
"Verge cannot open because of a problem" MacOS High Sierra

### ISSUE THREAD

**Issue by n3u120** [vergecurrency/VERGE#549]
# Issue Template

## Context

None of the Wraith wallets work on my computer. I have installed homebrew through terminal. The last version before Wraith works great. I recieve an error message that says, "Verge cannot open because of a problem" I've included the error report below. 

## Prerequisites

* [YES] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [X ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior
Start up and run

## Current Behavior
Doesn't start up or run

## Possible Solution

On my end, after 16 years it's time to stop using fApple products. However, until then I could just HODL Verge forever?

## Steps to Reproduce (for bugs)

* Steps :
1. Download any of the latest versions of Verge-Qt
2. Drag to Applications Folder
3. Double Click icon
4. Try again after reinstalling and restarting computer

## Your Environment

Non of the latest verge releases or any releases on the main Verge website work. An older Verge-Qt wallet works fine, however, after the hardfork I'm not sure I should use this wallet.

* Verge Release: Verge-Qt-23-06-2018, Verge-Qt-4.0.1, Verge-Qt 4.0 or any release on the Verge website
* CPU: 3.6GHz Intel Core i5
* GPU: ATI Radeon HD 5670 512 MB
* RAM: 8 GB 1333 MHz DDR3
* OS: High Sierra
    - [X ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

## Any extra information that might be useful in the debugging process.

Process:               VERGE-Qt [5439]
Path:                  /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
Identifier:            com.vergecurrency.VERGE-Qt
Version:               4.0.1 (4.0.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VERGE-Qt [5439]
User ID:               501

Date/Time:             2018-01-23 20:25:16.685 -0800
OS Version:            Mac OS X 10.13.2 (17C88)
Report Version:        12
Anonymous UUID:        12A10D2A-8C63-18F3-FC42-AE8CAFEFC2AA

Sleep/Wake UUID:       5D2A9733-2A3C-4890-8970-BAE5A30ED62F

Time Awake Since Boot: 57000 seconds
Time Since Wake:       11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x106948000 -        0x1072bbfff +com.vergecurrency.VERGE-Qt (4.0.1 - 4.0.1) <2B77BF2D-DFA9-3195-ADAD-BE31889C17F4> /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
       0x10738d000 -        0x10738ffff +libboost_system.dylib (0) <F3411558-02A6-3F5A-B040-E70EEB13F639> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_system.dylib
       0x107392000 -        0x1073a0ff7 +libboost_filesystem.dylib (0) <FADB85A3-B162-3CC3-9D21-5D4D0B452F4C> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
       0x1073af000 -        0x1073e3fff +libboost_program_options-mt.dylib (0) <551B73D9-D5BA-3BDB-A497-AE17966D1B1F> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
       0x107405000 -        0x107412ff7 +libboost_thread-mt.dylib (0) <43A32D2F-3381-32E7-A6A5-47B94F951AD6> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
       0x107421000 -        0x107422ffb +libboost_chrono-mt.dylib (0) <F098AA6F-5272-3ACE-9305-6AB0ABAD6DE7> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
       0x107425000 -        0x107930fff +QtWidgets (5.5.1) <416CBC52-D42C-3996-B338-C848863E65B0> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x107a68000 -        0x107eecfff +QtGui (5.5.1) <217B896F-895F-3DEC-BF29-01E065492858> /Applications/VERGE-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x107fcd000 -        0x1084d4fff +QtCore (5.5.1) <201F9A70-4676-3BC5-8B59-82DA94559272> /Applications/VERGE-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x108566000 -        0x108673ff7 +QtNetwork (5.5.1) <CC4ADD9F-E8C7-3618-9D83-7DBF9AC4267A> /Applications/VERGE-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x1086ab000 -        0x10870eff7 +QtDBus (5.5.1) <B0B9AE70-B993-3081-9336-E01BD1233823> /Applications/VERGE-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
       0x108727000 -        0x10872dfff +libqrencode.4.dylib (0) <5B7DEE75-603E-351D-B14C-21663CD470BC> /Applications/VERGE-Qt.app/Contents/Frameworks/libqrencode.4.dylib
       0x108732000 -        0x108864ff7 +libprotobuf.15.dylib (0) <6300475A-5FB2-39C0-AE54-644CFAC18091> /Applications/VERGE-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
       0x108918000 -        0x108a3cff7 +libdb_cxx-4.8.dylib (0) <893E0F96-1F8A-3073-B1CF-CC60610C3E90> /Applications/VERGE-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
       0x108a7b000 -        0x108a8bff3 +libz.1.dylib (0) <C1AAED3F-5000-3D8F-BE16-37688A0D413A> /Applications/VERGE-Qt.app/Contents/Frameworks/libz.1.dylib
       0x108a8f000 -        0x108abcfff +libevent-2.1.6.dylib (0) <891F379E-D5F9-39EB-BECA-2E24F943B7B3> /Applications/VERGE-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
       0x108ace000 -        0x108ad6ff3 +libminiupnpc.16.dylib (0) <C103607F-F06C-34D6-A60A-27E9E344F015> /Applications/VERGE-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
       0x108adf000 -        0x108b20fff +libssl.1.0.0.dylib (0) <3C28C2A8-036B-34B3-82BB-5780DB7271B2> /Applications/VERGE-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
       0x108b3e000 -        0x108caec87 +libcrypto.1.0.0.dylib (0) <1C6D06DA-0F88-37BA-80E9-52C4AC7E942C> /Applications/VERGE-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
       0x1166dd000 -        0x11672798f  dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
    0x7fff5383f000 -     0x7fff53843ffb  com.apple.agl (3.3.1 - AGL-3.3.1) <5A110DE6-3EE7-343B-95FE-9642517D1B64> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff54ea8000 -     0x7fff55d05fff  com.apple.AppKit (6.9 - 1561.20.106) <7A71ACCF-2DF5-3557-BB22-3A9FC9F71CCF> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff55d57000 -     0x7fff55d57fff  com.apple.ApplicationServices (48 - 50) <7627DBD6-497B-3AB7-9B63-F0532EDF09B8> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff57890000 -     0x7fff57d29fff  com.apple.CoreFoundation (6.9 - 1450.16) <DD253147-5720-3B3B-B222-77FD1419C400> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff58a06000 -     0x7fff58a06fff  com.apple.CoreServices (822.19 - 822.19) <0C60B639-4CC4-3F57-BC5E-DB71EB75F7F4> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff59825000 -     0x7fff5982afff  com.apple.DiskArbitration (2.7 - 2.7) <44836CE9-A9ED-3017-972A-7A0A3D6B472B> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff599eb000 -     0x7fff59db0fff  com.apple.Foundation (6.9 - 1450.16) <7FEC6610-70EA-3A8D-8EC4-7E99BAF1E312> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff5a0c5000 -     0x7fff5a160fff  com.apple.framework.IOKit (2.0.2 - 1445.31.1) <7556086A-EFAF-3262-9822-6F666CFC6655> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff61baf000 -     0x7fff61bbdffb  com.apple.opengl (16.4.2 - 16.4.2) <C8C31EF5-8DB4-336F-A87C-5D520C7EFDC5> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff7ca6a000 -     0x7fff7ca9dfff  libclosured.dylib (519.2.2) <48051216-5647-3643-B979-B77D0FD20011> /usr/lib/closure/libclosured.dylib
    0x7fff7cf7c000 -     0x7fff7cf7dff3  libSystem.B.dylib (1252) <5EDEEA85-0387-31EE-9D9B-DA1B75E7AEF3> /usr/lib/libSystem.B.dylib
    0x7fff7d232000 -     0x7fff7d288fff  libc++.1.dylib (400.9) <FCF5E1F6-2B04-3545-8004-F3AB32FED172> /usr/lib/libc++.1.dylib
    0x7fff7d289000 -     0x7fff7d2adff7  libc++abi.dylib (400.7) <217656D5-BC40-37FF-B322-91CB2AAD4F34> /usr/lib/libc++abi.dylib
    0x7fff7e5ff000 -     0x7fff7e9f03b7  libobjc.A.dylib (723) <37A7D77E-952C-3F5D-970B-3CDE349B2322> /usr/lib/libobjc.A.dylib
    0x7fff7f097000 -     0x7fff7f09bff7  libcache.dylib (80) <354F3B7D-404E-3398-9EBF-65CA2CE65211> /usr/lib/system/libcache.dylib
    0x7fff7f09c000 -     0x7fff7f0a6ff3  libcommonCrypto.dylib (60118.30.2) <674286D3-7744-36A3-9AAA-49DFCD97A986> /usr/lib/system/libcommonCrypto.dylib
    0x7fff7f0a7000 -     0x7fff7f0aefff  libcompiler_rt.dylib (62) <4487CFBA-A5D7-3282-9E6B-94CAD7BE507E> /usr/lib/system/libcompiler_rt.dylib
    0x7fff7f0af000 -     0x7fff7f0b7ffb  libcopyfile.dylib (146.30.2) <2C7C67D7-562B-3FFA-973D-BACF4C10E1EC> /usr/lib/system/libcopyfile.dylib
    0x7fff7f0b8000 -     0x7fff7f13dfff  libcorecrypto.dylib (562.30.10) <8A53EFE1-AFCA-3676-BEE1-FA5ED9F0E222> /usr/lib/system/libcorecrypto.dylib
    0x7fff7f1c5000 -     0x7fff7f1feff7  libdispatch.dylib (913.30.4) <7D0E3183-282B-3FEE-A734-2C0ADC092084> /usr/lib/system/libdispatch.dylib
    0x7fff7f1ff000 -     0x7fff7f21cff7  libdyld.dylib (519.2.2) <C50D02BC-A333-3313-B787-02F255A6783F> /usr/lib/system/libdyld.dylib
    0x7fff7f21d000 -     0x7fff7f21dffb  libkeymgr.dylib (28) <6D84A96F-C65B-38EC-BDB5-21FD2C97E7B2> /usr/lib/system/libkeymgr.dylib
    0x7fff7f22b000 -     0x7fff7f22bff7  liblaunch.dylib (1205.30.29) <E66F58ED-C15E-3DFB-BC22-A861E13918C6> /usr/lib/system/liblaunch.dylib
    0x7fff7f22c000 -     0x7fff7f230ffb  libmacho.dylib (900.0.1) <756F2553-07B6-3B42-ACEA-2F0F1A5E8D0F> /usr/lib/system/libmacho.dylib
    0x7fff7f231000 -     0x7fff7f233ff3  libquarantine.dylib (86) <6AC8773F-3817-3D82-99C2-01BABB9C3CBB> /usr/lib/system/libquarantine.dylib
    0x7fff7f234000 -     0x7fff7f235ff3  libremovefile.dylib (45) <912FA211-DD8C-3C92-8424-21B89F8B10FD> /usr/lib/system/libremovefile.dylib
    0x7fff7f236000 -     0x7fff7f24dfff  libsystem_asl.dylib (356.1.1) <94972913-9DF0-3C78-847C-43E58919E3DA> /usr/lib/system/libsystem_asl.dylib
    0x7fff7f24e000 -     0x7fff7f24efff  libsystem_blocks.dylib (67) <F2493BB5-B1C6-3C4D-9F1F-1B402E0F1DB7> /usr/lib/system/libsystem_blocks.dylib
    0x7fff7f24f000 -     0x7fff7f2d8ff7  libsystem_c.dylib (1244.30.3) <E0136C71-0648-36F0-9F84-82EA2748A8D7> /usr/lib/system/libsystem_c.dylib
    0x7fff7f2d9000 -     0x7fff7f2dcffb  libsystem_configuration.dylib (963.30.1) <0F8D0B76-4F7D-34EC-AB6C-50F9465809DA> /usr/lib/system/libsystem_configuration.dylib
    0x7fff7f2dd000 -     0x7fff7f2e0ffb  libsystem_coreservices.dylib (51) <21A488D0-2D07-344E-8631-CC8B2A246F35> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff7f2e1000 -     0x7fff7f2e2fff  libsystem_darwin.dylib (1244.30.3) <2F750CB1-BC26-3FA3-AE59-553EE30D451B> /usr/lib/system/libsystem_darwin.dylib
    0x7fff7f2e3000 -     0x7fff7f2e9ff7  libsystem_dnssd.dylib (878.30.4) <EB9BB165-45A4-367C-B33A-688D4F383A95> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff7f2ea000 -     0x7fff7f333ff7  libsystem_info.dylib (517.30.1) <7D79E167-4B5C-3833-81EE-3AF3FB53616D> /usr/lib/system/libsystem_info.dylib
    0x7fff7f334000 -     0x7fff7f359ff7  libsystem_kernel.dylib (4570.31.3) <D2E842AA-3B8D-31BF-8234-8C1BE11CFE32> /usr/lib/system/libsystem_kernel.dylib
    0x7fff7f35a000 -     0x7fff7f3a5fcb  libsystem_m.dylib (3146) <ABB1B85F-9FFE-31B8-AD4F-E39A30794A93> /usr/lib/system/libsystem_m.dylib
    0x7fff7f3a6000 -     0x7fff7f3c5fff  libsystem_malloc.dylib (140.1.1) <9F0745FF-B92F-330D-8812-BB74001D1D33> /usr/lib/system/libsystem_malloc.dylib
    0x7fff7f3c6000 -     0x7fff7f46aff3  libsystem_network.dylib (1229.30.11) <40BAD301-8744-3AD8-A688-E7925C587B00> /usr/lib/system/libsystem_network.dylib
    0x7fff7f46b000 -     0x7fff7f475ffb  libsystem_networkextension.dylib (767.30.7) <C5ED4BAB-2480-369D-8AB6-DFB37C15A1EE> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff7f476000 -     0x7fff7f47fff3  libsystem_notify.dylib (172) <98EA3D62-7C86-30DE-8261-D020D2F1EFF3> /usr/lib/system/libsystem_notify.dylib
    0x7fff7f480000 -     0x7fff7f487ff7  libsystem_platform.dylib (161.20.1) <C049250F-8C35-314D-810F-4E28AEAED983> /usr/lib/system/libsystem_platform.dylib
    0x7fff7f488000 -     0x7fff7f493fff  libsystem_pthread.dylib (301.30.1) <ABA848E1-6978-3B42-A3A7-608B2C36FA93> /usr/lib/system/libsystem_pthread.dylib
    0x7fff7f494000 -     0x7fff7f497ff3  libsystem_sandbox.dylib (765.30.4) <A51828BA-26D8-3205-AF3A-DF5C37269468> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff7f498000 -     0x7fff7f499ff3  libsystem_secinit.dylib (30) <F06ADB8F-9E94-34A7-B3C9-2C22FDD14BAD> /usr/lib/system/libsystem_secinit.dylib
    0x7fff7f49a000 -     0x7fff7f4a1ff7  libsystem_symptoms.dylib (820.30.7) <DC3586C2-AA56-3419-88D3-FC0DBF08E3C0> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff7f4a2000 -     0x7fff7f4b5ff7  libsystem_trace.dylib (829.30.14) <69EBF017-D40F-30D7-9B0B-BFC862D761A5> /usr/lib/system/libsystem_trace.dylib
    0x7fff7f4b7000 -     0x7fff7f4bcff7  libunwind.dylib (35.3) <6D4FCD49-D2A9-3233-95C7-A7635CE265F2> /usr/lib/system/libunwind.dylib
    0x7fff7f4bd000 -     0x7fff7f4e9ff7  libxpc.dylib (1205.30.29) <F7E5F1BC-614B-39CB-B6CE-92A9C7B7EC0B> /usr/lib/system/libxpc.dylib

**Comment by justinvforvendetta** [comment]
Library not loaded: @loader_path/libboost_system-mt.dylib
Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib

**Comment by Wolf202** [comment]
I have the same issue. I don't know how to fix it. I don't have skills to code. Could you explain more specific how can I do it?

**Comment by n3u120** [comment]
Wolf202- I think they are actively working on it. I think it involves installing boost. I tried it on two computers and it still isn't working, but try this maybe it will work for you.

Go to Applications -> Utilities -> Terminal and paste this in:

xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew install boost

They already know they need to take this step out for mass adoption, but in the meantime this might work. It helped me get an old wallet running, but not the newer releases.

**Comment by Wolf202** [comment]
Thank you n3u120. I've tried and it don't work for me. The same issue.

**Comment by Max-Meldrum** [comment]
You might have gotten boost 1.66 installed.
try: `brew install boost@1.60`
and if still not, then `brew link boost`

**Comment by Rmmymrtn82** [comment]
I am having the same issue.  i hope they fix this asap.

**Comment by dschutterop** [comment]
Installing boost 1.66 worked for me @Max-Meldrum.

**Comment by FabioPimenta** [comment]
@dschutterop : Installing boost 1.66 worked for me

$ brew install boost@1.66
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
==> Downloading https://homebrew.bintray.com/bottles/boost-1.66.0.high_sierra.bottle.tar.gz
######################################################################## 100.0%
==> Pouring boost-1.66.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/boost/1.66.0: 13,101 files, 435.2MB

I did this and Verge stoped to Crash but got another error while it tries to **Verify Database Integrity**
**Timed out waiting for onion hostname**

**Comment by Wolf202** [comment]
Thank you guys, but I don't know how to fix the code of downloading. I'm just a geologist:)

**Comment by n3u120** [comment]
Wolf202- I typed: 

brew install boost@1.66

into terminal and it finally works for me. I've read 'brew install boost@1.60' 'brew link boost' and script I posted last night. None of those worked, but after hours of reading and trying different things this did.

Definitely not a consumer ready product for apple users.

**Comment by Max-Meldrum** [comment]
Okay, so boost version 1.66 seems to be working for most it seems. it is being built with 1.60, but I guess it more of a linking problem than 1.60 vs 1.66.

Yes, there are definitely things that have to be fixed regarding the OS X wallet. Hopefully contributors who have an OS X system can look into this.

**Comment by n3u120** [comment]
I do appreciate the help and efforts. This issue is resolved- not sure if I can close it or not, new to all this. Thanks again for helping get this running.

**Comment by Max-Meldrum** [comment]
@n3u120 Great to hear that it is resolved. Yes, feel free to close the issue.

**Comment by Wolf202** [comment]
@n3u120 Thank you! It helped me!

**Comment by justinvforvendetta** [comment]
we can leave this open until we have a new binary posted

**Comment by utaztec** [comment]
Hi all, same prob. Not a coder but I'll give the boost a shot and see how it goes.  In the meantime, will the 3.0 wallet still sync with the network, or is the upgrade required?

**Comment by justinvforvendetta** [comment]
3.0 is no longer compatible

**Comment by utaztec** [comment]
I'm running 10.13.2 and ran this line: brew install boost@1.66 and it gave me: command not found
Before that I ran: xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew install boost 
It created a bunch of new directories and ==>The Xcode Command Line Tools will be installed
suggestions?

**Comment by justinvforvendetta** [comment]
@utaztec does "xcode-select --install" work? did any of those lines give you an error?
also, are you the only user of the computer, are you the admin?

**Comment by utaztec** [comment]
Thanks for the response!  Yes, I’m the only user. I just ran the xcode-select line and it wants me to install Xcode and command line developer tools from the App Store.  Do it, I assume?
Thanks!

**Comment by utaztec** [comment]
So, now it says the command line tools are installed but when I run: brew install boost@1.66 it says:
-bash: brew: command not found

**Comment by utaztec** [comment]
I attempted a send on my 3.0 wallet to Bittrex and it went through.

**Comment by billstam** [comment]
same problem none of the brew install boost work for me. how can I get the old qt wallet back to send coins to somewhere else? I have my backup but when trying to install new wallet the original one was replaced and I can't get into It.

**Comment by billstam** [comment]
after about 65,017 tries it worked thanks

**Comment by drtom15** [comment]
I'm still having issues, I'm getting prompted for a password in terminal when I copy and paste 
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

I also tried to emailing h.burakyesilyurt@gmail.com for support, and I got this response:

"Yeah for brew package manager you need password. It’s completely independent from us. Our software does not ask any password."

Anything else I can do?  Please let me know.

**Comment by Max-Meldrum** [comment]
@drtom15 is it not just asking the password that you login with? Did you try that?

**Comment by drtom15** [comment]
whoa!...thanks @Max-Meldrum! seems to be working now

**Comment by ebrinkster** [comment]
Try verge 4.0.1 fork for stealth.  No further issues with macOS for me after this release.

**Comment by mowland** [comment]
Verge-Qt 4.0.1 fork for stealth / Mac OS High Sierra / Instructions.

1.Backup your wallet.dat file to a safe place, found in: go,library,application support,Verge. 
Download: https://github.com/vergecurrency/VERGE/releases/tag/4.0stealth
Install & replace your other wallet, blockchain, addresses, transactions stay the same.
2.Now go to Finder bottom left corner, type terminal, open terminal. 
3.copy & paste: xcode-select —install 
4.press enter 
5.install this then back onto terminal 
6.copy & paste: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" 
7.press enter 
8.press enter again 
9.Type in password used for admin or to log in laptop, as you type you won’t see it. 
10.press enter 
11.copy & paste: brew doctor 
12.press enter 
13.copy & paste: brew install boost 
14.press enter 
15.now go to open the Verge-QT Wallet,  allow & open.
16. :)

**Comment by badsloth** [comment]
None of this worked for me. Any chance the mac wallet gets a fix that works for everyone?

**Comment by mowland** [comment]
Probably but not any time soon. Just have to experiment with what you’ve
got.
