### ISSUE TITLE
Use last version and recive alert "Timed out waiting for onion hostname" -_-

### ISSUE THREAD

**Issue by daigiavabagia** [vergecurrency/VERGE#552]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by Max-Meldrum** [comment]
Is this still happening? I don't have this issue while running (Linux). Might have been something temporary? Feel free to close the issue if it is working again.

**Comment by justinvforvendetta** [comment]
can not reproduce. try starting it again?

**Comment by Technophant** [comment]
This a know issue with latest win release. Try restarting the app few times, seems to work

**Comment by daigiavabagia** [comment]
Hi Team, i did use wallet verge ok after re install, perfect, thanks team for support
![image](https://user-images.githubusercontent.com/32443930/35490411-0f74c230-04d2-11e8-91d0-486aa5e1a651.png)

**Comment by randy1xxx** [comment]
Really? I happened to shut down wallet, now I cannot get back in. At first I received a "Timed out waiting for onion hostname." after trying to fix it, I cannot get that. This wallet seems extremely sensitive, don't thin Wraith is working. How can I get my coins back to an exchange where they are safer?

**Comment by justinvforvendetta** [comment]
@randy1xxx are you already running tor elsewhere? maybe try restarting if you are on a system like windows. this wallet is not extremely sensitive at all.
