### ISSUE TITLE
Just download 4.0.1 fork for stealth for win7

### ISSUE THREAD

**Issue by Pele51** [vergecurrency/VERGE#553]
I just download the 4.0.1 fork for stealth for win7 and delete the old one and get it fully synched after that i close the wallet, put my wallet.dat into the folder C.user/test/appdata/roaming/verge and start it again, my coins are still unconfirmed, why that?

**Comment by Pele51** [comment]
Finally its showing up, i just wait an hour!

**Comment by Pele51** [comment]
And now the passphrase still not unlock my wallet! Its the right one, coz i made a sreenshot before....

**Comment by Max-Meldrum** [comment]
I think that issue has been solved already.  #389 Or perhaps there is some bug regarding windows.
