### ISSUE TITLE
XVG coins in old blockchain

### ISSUE THREAD

**Issue by pchamb1998** [vergecurrency/VERGE#556]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by pchamb1998** [comment]
Seeked*

**Comment by justinvforvendetta** [comment]
yes if you are using the new wallet, everything is fine. old transactions made with stealth are either confirmed or came back

**Comment by pchamb1998** [comment]
Even if the transaction on the 8th was sent from the 3.0 version of Mac OS X QT?

**Comment by justinvforvendetta** [comment]
transaction will bounce back when u start the new wallet
