### ISSUE TITLE
Balance not showing on XVG wallet

### ISSUE THREAD

**Issue by MynxGithub** [vergecurrency/VERGE#558]
It's updated to the newest wallet and synced to the latest block

![image](https://user-images.githubusercontent.com/35780058/35355483-5857c384-0145-11e8-9745-889378750577.png)

![image](https://user-images.githubusercontent.com/35780058/35355961-f374361c-0146-11e8-8cd2-fe6a140e0ad7.png)

showing on blockchain.info confimed

![image](https://user-images.githubusercontent.com/35780058/35355565-934586b6-0145-11e8-9cab-43c919ce1436.png)

I have checked, it's the correct receiving address so I'm confused as to why it's not showing.

**Comment by jrsikors** [comment]
Where did you send from -> to?  
 Exchange -> Verge QT public address?  
 Exchange -> Verge QT Stealth address?
 Verge QT public -> Verge QT stealth?

Are there any confirmations?  

![ss1](https://user-images.githubusercontent.com/31370541/35359391-8953274c-011f-11e8-8f87-ead2b7191553.png)

**Comment by MynxGithub** [comment]
Cryptopia to Electrum wallet 2.4.1 
then sent to Verge QT public address
8541 confirmations. 

On Jan 24, 2018, at 01:59 PM, Jeff S <notifications@github.com> wrote:

Where did you send from -> to?
Exchange -> Verge QT public address?
Exchange -> Verge QT Stealth address?
Verge QT public -> Verge QT stealth?

Are there any confirmations?

**Comment by justinvforvendetta** [comment]
is cryptopia on the proper block number? did they update?

**Comment by jrsikors** [comment]
Go to Help -> Debug Window ...

1) what's your client version
2) what do the 3 things under block chain say ?

and you don't have TestNet checked I'm assuming.

You could also try the "scanforalltxns" command in the debug console .  Without knowing what your TX was .. I'd do like scanforalltxns 1700000 (1,700,000).

Make sure you got a backup copy of your wallet.dat before you go further.

**Comment by MynxGithub** [comment]
Client Version: v4.0.1.0-794660a-funky-beta
Current no. of Blocks 1826678
Est. total blocks 1825035
Last block time Thu Jan 25 00:34:49 2018

I'm not quite sure how to do the scanforalltxns but I've attempted this

On Jan 24, 2018, at 04:18 PM, Jeff S <notifications@github.com> wrote:

Go to Help -> Debug Window ...

what's your client version
what do the 3 things under block chain say ?
and you don't have TestNet checked I'm assuming.

You could also try the "scanforalltxns" command in the debug console . Without knowing what your TX was .. I'd do like scanforalltxns 1700000 (1,700,000).

Make sure you got a backup copy of your wallet.dat before you go further.

**Comment by jrsikors** [comment]
Help -> Debug Console -> Console tab
type:
scanforalltxns 1700000

That will re-scan for all transactions above 1,700,000 .. which in theory will pick up your transaction eventually.

It might take some time (hours and hours) to re-scan for all the transactions.

**Comment by MynxGithub** [comment]
My transaction was less than 10,000 XVG. Should I type scanforalltxns 5,000 to scan all transactions above 5,000?

**Comment by MynxGithub** [comment]
![image](https://user-images.githubusercontent.com/35780058/35364849-50a159ba-0169-11e8-925f-9f697015280a.png)
I don't know how, but it randomly came through after scanning for transactions! thank you very much

**Comment by jrsikors** [comment]
Glad to hear !

Just FYI in case you are wondering...
the number i had you put in was the block number, not the size of the transaction.  The latest verge "block" is 1,826,719.

I assumed your transaction was made after block 1,700,000 since it was a few days ago.

If you go look at your transaction on the verge-blockchain.info -- it should have a "block hash" string.  If you click on the "block hash string", there will be a field called "Height".  That's the "block" your transaction was done on.  So re-scanning that particular block would have done it, but there's no harm in just scanning everything past 1.7 million.
