### ISSUE TITLE
receiving "Error: Tranaction creation failed" when attempting to send txn

### ISSUE THREAD

**Issue by lannudan** [vergecurrency/VERGE#559]
## Context

I testing the stealth transactions to see how they work/what they do, etc.  I made a few transactions to my main wallet from two different stealth addresses.  I am getting this error message when attempting to send the coins from my main wallet to another wallet's non-stealth address. 

## Prerequisites
*  Are you running the latest version?
         yes
## User Story:

* "I'm submitting a ... "
  - [ x ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior

The transaction should be created and sent to the blockchain

## Current Behavior

When attempting to create a new transaction, to a normal address, the Error: Tranaction creation failed message appears. 

## Steps to Reproduce (for bugs)

* Steps :
1.  Send two transactions (from different wallets) to main wallet in fully synced, up to date Windows wallet. Two separate stealth addresses were used for the incoming transactions
2. Create outgoing transaction to a completely different wallet. Sending to non-stealth address. 
3. Click Send 
4. Enter passphrase if wallett is locked (this error happens when the wallet is locked and unlocked)
5. Get error. 

## Your Environment

* Verge Release: 4.0.1 fork for stealth using the (VERGE-windows.zip - Windows GUI and daemon wallets. (updated 1/23/2018 at 4:24pm EST)) update
* CPU: i5 6600k
* GPU: Gigabyte 1080ti
* RAM: 16GB
* OS: Windows 8.1

## Any extra information that might be useful in the debugging process.

This appears in the debug logs when the transaction fails

NotifyKeyStoreStatusChanged
    Error: Failed decrypting stealth key 
    stealth address here
    Error: Failed decrypting stealth key 
    second stealth addres here
    Error: No metadata found to add secret for ::non stealth address here::
    CreateTransaction() : Sign Signatue Failed 

*addresses removed*

**Comment by justinvforvendetta** [comment]
not sure what this scenario is. so you are sending yourself a stealth transaction from inside the same wallet?

**Comment by justinvforvendetta** [comment]
I can't reproduce

**Comment by justinvforvendetta** [comment]
sounds like one or more wallets isn't the most recent download. verify they are all at the same block number, and that it matches the block number on verge-blockchain.info

**Comment by acards** [comment]
@justinvforvendetta  
"not sure what this scenario is. so you are sending yourself a stealth transaction from inside the same wallet?"

i have been trying to do this, simply to confirm stealth works on my machine (iOS). transfer fee and amount is taken out of wallet, no transaction in history, no tx id to reference, sent amount is no longer in wallet. blocks match, it is updated version (did this yesterday)
anything i can try?

*aside--ignore telegram message about same subject, saw this and it was relevant to scenario, wanted to expand on it here.

**Comment by lannudan** [comment]
@justinvforvendetta 
The Windows wallets are all on the v4.0.1.0-794660a-funky-beta version of the wallet. The only thing that is a little weird is the build date is 2018-01-19 03:31:22 -0500. 

Wasn't there an update to the wallet more recently than that? 

https://github.com/vergecurrency/VERGE/releases/tag/4.0stealth This is where I downloaded it.

**Comment by justinvforvendetta** [comment]
yes. have you tried replacing the one you have with that one?

**Comment by acards** [comment]
mac wallet is eating stealth transactions

**Comment by justinvforvendetta** [comment]
@acards maybe you aren't on the newest one

**Comment by acards** [comment]
@justinvforvendetta i will back up and give it another go and get back. did update post release maybe i messed up

**Comment by acards** [comment]
Hey @justinvforvendetta re-downloaded, imported my wallet.dat, attempted to send a test .2 XVG transaction from within wallet to stealth address. Same results here.. have sent a transaction to my normal address fine today. No other issues from users on this? just not sure what if any troubleshooting i can do here... no error code, funds just disappear and no history of transaction listed

**Comment by justinvforvendetta** [comment]
did you make sure your wallet is on the same block number as verge-blockchain.info?

**Comment by acards** [comment]
Copy that matches up, 1829719

**Comment by Aergon** [comment]
Happens same to me, i did made a stealth address in my wallet, transfer some coins to it from another wallet with normal a regular address in another computer and when i try to spend the coins saved wallet give me this message: " Error. Fallo en la creacion de la transaccion." and don't let me move coins.

Wallet Version: Windows Verget Qt   Verge v4.0.1.0-794660a-funky-beta

Windows 10 64 bits
intel i7
32gb ram

**Comment by Aergon** [comment]
I need to add i did spent coins in another regular address in same wallet, but the 20 XVG i keep in stealth address can't be moved.

**Comment by justinvforvendetta** [comment]
what do you mean the 20 you keep in stealth? you can send all your coins but 20 of them?

**Comment by Aergon** [comment]
exactly

**Comment by Aergon** [comment]
i transfer 10 to regular address, and 20 to stealth addres, i did move 10, but can't move the other 20

**Comment by justinvforvendetta** [comment]
also @acards the transaction id never showed up on the explorer?

**Comment by Aergon** [comment]
i am not a expert, so not sure what are you asking, i didn't search in blockchain for transaction, i still have the 20 coins in wallet, seems to be there are no way to move it, i can send you the wallet.dat if you wish test it, only have 20 xvg

**Comment by Aergon** [comment]
![image](https://user-images.githubusercontent.com/35868780/35473057-8d3b71c2-037a-11e8-9e5c-c2b16ec29677.png)

**Comment by Aergon** [comment]
![image](https://user-images.githubusercontent.com/35868780/35473064-aa3cd6bc-037a-11e8-93f4-1c0b3d7ebdc3.png)

**Comment by Aergon** [comment]
![image](https://user-images.githubusercontent.com/35868780/35473086-f7fa9b1e-037a-11e8-8eb7-60cb765e4c0c.png)

**Comment by Aergon** [comment]
want help with this, so let me know if you need anything about this error, keep the good work, i know are too many things and fast. I will try check this issue for progress, thanks.

**Comment by acards** [comment]
@justinvforvendetta well it could have for all i know, but there is no history of the sent transactions within my wallet so i do not have a transaction id to look up. it was a couple of .20 xvg transfers, the .10 fee pulls successfully and the .1 xvg i was sending gets deducted with no record on the history of transactions

**Comment by justinvforvendetta** [comment]
@acards are you 100% sure you haven't locked/passworded your wallet?

**Comment by justinvforvendetta** [comment]
that's definitely @aergon issue, now that I see the locked icon in the bottom right corner

**Comment by Aergon** [comment]
I have my wallet encrypted, wallet ask for my password when did the transfer, i put it and give me that message, for do transactions with stealth accounts needs to be done something different?

**Comment by Aergon** [comment]
did unlock the wallet, get same error, another screenshot for the record

![image](https://user-images.githubusercontent.com/35868780/35474157-9dd46696-038a-11e8-8ee3-cd75a5afc77f.png)

**Comment by Aergon** [comment]
after try the failed transaction, my wallet go and eat all cpu resources and stay there until close wallet
![image](https://user-images.githubusercontent.com/35868780/35474459-cdcfbf0e-038e-11e8-849a-f262e55bfa94.png)

**Comment by acards** [comment]
![photo jan 27 5 19 46 pm](https://user-images.githubusercontent.com/35613467/35478012-2a40312c-0387-11e8-8737-b8dda0771bcd.jpg)

@justinvforvendetta yeah not locked here. maybe i start a new wallet altogether and see if different results?

**Comment by Aergon** [comment]
I even try get private key from that address and create a new wallet from it in Electrum, but i fail on get private key

![image](https://user-images.githubusercontent.com/35868780/35491739-b179c4ba-04a8-11e8-8093-c253ff78d7e3.png)

**Comment by ahilis** [comment]
@justinvforvendetta why did you close this issue? Is it possible to send coins from this wallet? Because I can't send any transaction... I've tried to use different fees but still error and there are few messages in log: "CreateTransaction() : Transaction too large". Why?
![image](https://user-images.githubusercontent.com/6560240/44956274-e69db980-aeda-11e8-82e0-630e144f944d.png)

**Comment by jrsikors** [comment]
Please post the address(es) you are trying to send from , and do a help -> debug .. and post a screenshot of that info tab details as well please.

Looking back on it -- previous people couldn't do a dumpprivkey on the address, which means that, for whatever reason, the QT's wallet.dat doesn't say they really own the address... which is most likely the problem.

**Comment by ahilis** [comment]
@jrsikors, thanks for reply! I've tried to remove wallet, import private key, and resync but the problem still exists.
Address: DHUWEKrDewLFjnJ3TNhK4LEd1VwyhAS6nR
Debug screen:
![image](https://user-images.githubusercontent.com/6560240/45174119-73ba7880-b223-11e8-8f5c-115d15b2457b.png)
And a little piece of log:
> ProcessMessages(61 bytes)
> ProcessMessages(61 bytes)
> ProcessMessages(61 bytes)
> CNode::AskFor block 35a8960866707f55d6e0   0 (00:00:00)
> ProcessMessages(61 bytes)
> CNode::AskFor block 35a8960866707f55d6e0   1536254147000000 (17:15:47)
> ProcessMessages(21364 bytes)
> ProcessMessages(29936 bytes)
> received block 35a8960866707f55d6e0
> SetBestChain: new best=35a8960866707f55d6e0  height=2482833  trust=2482834  date=09/06/18 17:09:38
> ProcessBlock: ACCEPTED (blake)
> ProcessMessages(61 bytes)
> Flushing wallet.dat
> Flushed wallet.dat 1594ms
> CreateTransaction() : Transaction too large 
> ProcessMessages(61 bytes)
> ProcessMessages(61 bytes)

By the way, address balance is 900+ xvg, but electrum wallet shows only 500.
Transaction with 10 xvg has been sent successfully/

**Comment by jrsikors** [comment]
It seems like you have a few different issues going on:
1) You are getting way too many small transactions too frequently, which is causing part of the problem.
Are you solo mining or part of a pool?  If you are part of a pool, I would suggest pushing back the "payout" to like once a day or week or so.  Right now you are getting payouts every 2 hours.

Transaction Fees are based on "per KB" rather than "per Transaction".  The more transactions you have coming into the account, the higher the "per KB" will be.

exact same scenario as you but for a different coin:
https://www.dash.org/forum/threads/transaction-too-large-error.4721/

What I would personally to do if I was in your position, just to get out of it:
Step 1) Make a new address ( you sent 10xvg to D6evqYZ1jomw4K5zH9GZ2KCtFyQNaTvqsB, use that if you own it)
Step 2)  Try to send a 100xvg transaction to address in step 1
Step 3)  Repeat step 2 until DHUWEKrDewLFjnJ3TNhK4LEd1VwyhAS6nR is empty
Step 4)  Make sure you change your "rewards payout" to be less frequent so you don't run into this problem in the future.

The TX Fees are calculated the way they are calculated.. so there's no tricking the system.

Here are more examples of same problem, different coin (since the core functionality is roughly the same for different cryptos, the solutions are usually the same as well):
https://bitcointalk.org/index.php?topic=1262920.msg16264319#msg16264319
https://bitcointalk.org/index.php?topic=1262920.msg16034048#msg16034048

**Comment by ahilis** [comment]
@jrsikors yes, you right! 2 transactions has gone away (100 and 200xvg). Thanks a lot for a help!

**Comment by bluimes** [comment]
I can reproduce on win10 with v4.0.2.0-c3a04c0-funky-beta. Same aspects as poster, I've multiple wallets with certain amounts, some of them are wraith wallets. When I send a bunch of Verge wallet freezes and gives the "error: transaction creation failed". 

My solution was like said by @jrsikors. I send really small bits of verge, like 1000 xvg per tx. That seems to work. But is really frustrating considering the amount I need to send.  Another option would be to send it directly from the wallet in debug? Did not try however.
