### ISSUE TITLE
Is XVG 100% POW?

### ISSUE THREAD

**Issue by shwuhk** [vergecurrency/VERGE#562]
I read from verge official FAQ and said that Verge is 100% POW. However, when I run "getdifficulty" in daemon, it response
```
{
    "proof-of-work" : 134809.38765231,
    "proof-of-work-next" : 119708.50549083,
    "proof-of-work-last-height" : 1828675,
    "proof-of-stake" : 0.00024414,
    "proof-of-stake-next" : 119708.50549083,
    "proof-of-stake-last-height" : 0,
    "search-interval" : 0
}
```
that make me curious if it is 100% POW.
If it is 100% POW, what is the use of the proof-of-stake* field use for? Thanks.

**Comment by justinvforvendetta** [comment]
it's disabled. we've never been pos. we could easily if we needed to after pow was over.
