### ISSUE TITLE
configure: error: libseccomp not found

### ISSUE THREAD

**Issue by tuaris** [vergecurrency/VERGE#564]
How do you build on platforms that do not have/support this library?
libseccomp

**Comment by tuaris** [comment]
Also seems libcap is Linux specific too.

**Comment by Max-Meldrum** [comment]
What platform are you on?

**Comment by dragononcrypto** [comment]
Likewise, I'm on 17.10.

**Comment by justinvforvendetta** [comment]
libseccomp-dev is in the required dependency list.

**Comment by tuaris** [comment]
This is on FreeBSD.

**Comment by justinvforvendetta** [comment]
https://github.com/seccomp/libseccomp/releases/download/v2.3.3/libseccomp-2.3.3.tar.gz

try downloading and compiling it maybe.

**Comment by tuaris** [comment]
How is VERGE getting built on MacOS X and windows?  Neither of those platform's have support for libseccomp and libcap.

**Comment by justinvforvendetta** [comment]
osx and win don't use libcap and libsec comp for compiling tor

**Comment by tuaris** [comment]
Can I remove this section in `configure.ac`?

```
      if test x$TARGET_OS = xlinux; then
        PKG_CHECK_MODULES(LIBSECCOMP, [libseccomp], [], [AC_MSG_ERROR([libseccomp not found])])
        PKG_CHECK_MODULES(LIBCAP, [libcap], [], [AC_MSG_ERROR([libcap not found])])
      fi
```

**Comment by tuaris** [comment]
Can I build using tor that I install as a separate package?

**Comment by tikaboo** [comment]
Don't remove that section of configure.ac. Download and install libseccomp from github and set the following environment variables, from the command line, before running configure:
export LIBSECCOMP_CFLAGS=/usr/local/include
export LIBSECCOMP_LIBS=/usr/local/lib
