### ISSUE TITLE
Binance transfer not arrive in wallet

### ISSUE THREAD

**Issue by christopht1981** [vergecurrency/VERGE#565]
Hey all. First of all sorry for my question, maybe it was asked before, bute I am noob and still hope  somebody can help.

I was running the Verge electrum wallet for windows and updated to the new Verge version 4.0.1.0
I had problems with importing the wallet.dat as it was not accepted and just got error message. 
So I synced the new wallet and transfered my coins from the old wallet to the new one and everything worked fine. I made a backup of my wallet. (By the way: there is no export possibility for private key / seed - how do i save private key in addition to wallet.dat?)

So after transfering coins from wallet to wallet I transfered some coins from Binance to wallet. On binance the transfer is shown as complete, but the coins did not arrive. I double checked the adress (correct) and the wallet is synced. Any idea how i can get my coins? 

Thanks for your help.
Chris

**Comment by justinvforvendetta** [comment]
you sent from binance to your new wallet? please post the tx id. also, this wallet you are using is the newest ? try downloading it again and replacing the one you are using.

**Comment by jrsikors** [comment]
in addition to that, try what I suggested here:
https://github.com/vergecurrency/VERGE/issues/558

**Comment by jrsikors** [comment]
& to get your private key -- you also need to go to the debug console and do a "dumpprivkey" on the address you want

**Comment by justinvforvendetta** [comment]
also make sure your block number you are synced to, matches what's on verge-blockchain.info

**Comment by jrsikors** [comment]
dont be a 1-upper sunerok

**Comment by jrsikors** [comment]
Really though -- I wonder if lots of people are going to need to be doing some:
scanforalltxns 1824149

**Comment by christopht1981** [comment]
I checked. It seems to be that the wallet is not fully synced. 
In the Block Explorer the highest block seems to be 1826475. My transfer from binance was at 1829326.
This i do not understand as I thought that the wallet syncs automatically, when startet. But it seems not. Can I check this anyhow? Can I start the sync manual?

**Comment by justinvforvendetta** [comment]
it sounds like you might not be on the right wallet then, try downloading the latest one and using it

**Comment by christopht1981** [comment]
If I type this in the console  I get following:
scanforalltxns 1826475

value is type str, expected int (code -1)

**Comment by justinvforvendetta** [comment]
sounds like you might have the old chain in your data dir, id try refreshing that as well
you can use this if you need it: electrum-xvg.stream/blockchaindata.zip

**Comment by jrsikors** [comment]
definitely issue seems to be syncing, and I would do what Justin says:
  ~Make sure you are on the "4.0.1 for stealth"
  ~delete the chain in your data dir (not your wallet.dat) , go download the blockchain.zip, unzip

Even though those things will most likely fix your problems, I'm curious why you got a "value type str" when running:
scanforalltxns 1826475

You did it JUST like that right?  No quotes, no commas?  IE:  
scanforalltxns "1826475"
scanforalltxns 1,826,475

Maybe it throws that error when you try to scan for a block higher than what your client thinks the max block is ?

**Comment by justinvforvendetta** [comment]
yes I don't think his client knows the blocks go that high

**Comment by justinvforvendetta** [comment]
closing this since he just needs to get on the right chain/synced

**Comment by christopht1981** [comment]
Unfortunately i still have problems with the sync. I downloaded the mentioned blockchaindata.zip, extracted to the folder and startet the wallet again. The the wallet startet to sync the last approx 24000 blocks. The problem is that it stopped while syncing. Now I am at an lower block than before. Any recommendations, how I can sync the rest of the blocks

**Comment by jrsikors** [comment]
It should be automatic -- are you sure you didn't set any firewalls / limit access on verge-qt.exe?

What operating system are you on?
In the bottom right corner of the QT wallet, there should be something that looks like a wifi/cell signal .. how many "connections" do you have?
After you start verge-qt .. are you giving it 10 minutes or so to start downloading blocks?
Are you 100% sure you are on the latest 4.0.1 for stealth?
Look at your <datadir> chain directory and see if any new files are coming in?  check the timestamp on the files to see if new blocks are being downloaded

**Comment by jrsikors** [comment]
and maybe try right clicking verge-qt.exe and 'running as administrator'
