### ISSUE TITLE
scanforalltxns and scanforstealthtxns [fromheight] - unable to pass int

### ISSUE THREAD

**Issue by jrsikors** [vergecurrency/VERGE#566]
## Context

In the console, attempting to run these 2 commands and passing an int always returns an error:
scanforalltxns
scanforstealthtxns
no matter what I try to put in, always get the "Value is type str, expected int (code -1)"

Have tried passing small numbers, using quotes, brackets, commas, etc... just doesn't like my input

## Prerequisites

* [yes] Are you running the latest version?
4.0.1 for stealth

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior

should be able to input a number to not have to scan entire blockchain

## Current Behavior

always get the "Value is type str, expected int (code -1)" when trying to pass an integer.  Without trying to pass a parameter, the commands seem to work

## Possible Solution
review code and validate the expected parameters is functioning as expected

## Steps to Reproduce (for bugs)

* Steps :
1. Help -> Debug Window -> Console
2. Type:  scanforalltxns 1500000
3. Type:  scanforstealthtxns 1500000

## Your Environment

windows 10

* Verge Release: 4.0.1 for stealth

Workaround:
just type those commands without trying to pass a value , which will scan entire blockchain and take a little longer

**Comment by michpiatek** [comment]
I will fix that quickly

**Comment by michpiatek** [comment]
Closing, I tested locally and works fine.

**Comment by peengo** [comment]
still happening to me:

Win7 64bit
v4.0.1.0-794660a-funky-beta
value is type str, expected int (code -1)
also for scanforstealthtxns its the same issue

**Comment by justinvforvendetta** [comment]
@peengo make sure you have the latest download. it works now, has worked since 1/26

**Comment by peengo** [comment]
@justinvforvendetta 
I have the latest one that comes in the zip. I've just download it and tried again. Its the same.
https://i.imgur.com/FBJVCWD.jpg

**Comment by jrsikors** [comment]
@justinvforvendetta i interpreted @michpiatek as saying he fixed the code, but it won't be included until the NEXT release... assuming you merge it ?  

Your last release was January 20th .. this was 'fixed' on the 26th.

**Comment by jrsikors** [comment]
Pardon my github language .. merge or commit, whichever, you get what I'm saying hopefully :smile:

**Comment by HamedAghaei** [comment]
I still have this problem. 
Anybody have a solution for this issue?

**Comment by jrsikors** [comment]
The 'workaround' is to just run plain **_scanforalltxns_**  ... dont use a number after it.

Whenever the next QT wallet is released, you will be able to put an integer after it.
