### ISSUE TITLE
Still problems with balance after binance transfer

### ISSUE THREAD

**Issue by christopht1981** [vergecurrency/VERGE#567]
# Issue Template

## Context

I still have problems to receive my binance transfer. Followed your instructions and downloaded latest blockchain, but still can not see my binance transfer. Additionally after trying with a wallet.dat backup I can see my balances (which i transfered first from my older electrum wallet) but now they are not confirmed!

## Prerequisites

* [x ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x ] bug report

* Steps :
1. Downloaded Wallet 4.0.1 for windows
2. Tried to load coins with wallet.dat backup from Electrum-Wallet ,but not workin
3. Transfered Coins from Electrum Wallet to Verge Qt 4.0.1 Wallet. --> Coins arrived and were confirmed
4. Tried to transfer coins from binance but did  not arrive yet (wallet.dat backup)
5. Thought that wallet was not fully synced. Closed wallet
6. Downloaded recommended Blockchain data
7. Copied (wallet.dat backup from Nr. 4) to verge folder
8.  Copied Blockain data to folder
9. Restartet Verge QT
10. Coins in wallet not confirmed now and transfered coins from binance not here

**Comment by michpiatek** [comment]
Did it sync completely? Just leave that wallet open for some time, downloaded chain is obviously not completely up to date as chain is growing constantly.

**Comment by jrsikors** [comment]
Go to help -> debug window ... and look underr "Block chain".. the 2 numbers and dates should be changing.  If they are not moving, you got bigger issues.

It should be automatic -- are you sure you didn't set any firewalls / limit access on verge-qt.exe?

What operating system are you on?

In the bottom right corner of the QT wallet, there should be something that looks like a wifi/cell signal .. how many "connections" do you have?

After you start verge-qt .. are you giving it 10 minutes or so to start downloading blocks?

Are you 100% sure you are on the latest 4.0.1 for stealth?

Look at your chain directory and see if any new files are coming in? check the timestamp on the files to see if new blocks are being downloaded

Try right clicking and running as administrator

**Comment by christopht1981** [comment]
Hy guys, okay I left the Verge Wallet syncing all the night. My old balances are back and confirmed. But the Binance transfer isn´t. I followed your instructions but it seems that the wallet is stopping syncing at 1826839. The wallet is trying to sync the rest of the blocks, but no progress. 
In the debug window, under Block Chain the 2 numbers are not changing really. Very slow. 
Hope to be able to upload the screenshot below.

![image](https://user-images.githubusercontent.com/35843736/35470377-dec4c1ce-0348-11e8-8ea4-7afc9e0109f8.png)

There are 17 connections, but the verge wallet shows its up to date. 

-) deactivated firewall - no change
-) tried running verge as administrator - no change
-) also tried to unlock wallet - no change
-) by the way... this "scanforalltxns" ist still not working. --> value is type str, expected int (code -1)


Is there anything i can do to get my wallet synced. I don´t wanna loose my coins :-/

**Comment by michpiatek** [comment]
Build date Jan 8? I think this is not the latest version of the wallet. Did you download it from this link:
https://github.com/vergecurrency/VERGE/releases/download/4.0stealth/VERGE-windows.zip

If that's not the latest wallet then it's clear why it it doesn't work.

**Comment by Alex3444** [comment]
Hello friends, 
Can any one help me pls with pretty same issues. 
Yesterday I done it 3 transfers from bittex.
 first 100 xvg  was add to my wallet after 3 minutes , after what I done it big amouth of xvg  which one I still din't received.
after that I done it another transfer  off 3 xvg, there are was added instant.
I checked https://verge-blockchain.info ,  all my 3 transfers shows there.
May be any one know why big amounts of xvg I still didn't receve on my wallet ?
I'm using macOS Sierra, 10.12.6. 
wallet version: v2.1.0.0.-9583c86-beta.

Trying to download and instal the latest version VERGE-Qt-23-06-2018.dmg
but this version doesn't work on my Mac.

Any one know how to resolve this problem ?

Thanks

**Comment by justinvforvendetta** [comment]
you have to use the newest wallet. the old one isn't compatible

**Comment by Alex3444** [comment]
But  the newest version VERGE-Qt-23-06-2018.dmg doesn't work on my Mac, its very strange.

on https://www.youtube.com/watch?v=R48e1mp_5qA&feature=youtu.be man explain how to instal but if you have problem to instal:

"Try opening the wallet, if error message appears try step 4:
Step 4 - https://twitter.com/vergecurrency/sta... " 

:(((


I it's not clerly understand  how to fix this error via terminal

Any one know how to resolve this problem please?

**Comment by christopht1981** [comment]
Okay just to be sure and not to loose my coins, please confirm that my next steps are correct:

-) I´ll make a backup of my wallet.dat
-) As I generated only one address at the moment (the one, where i transfered coins from binance) I exported this file to a CSV --> How do I import this address later on to the new wallet?
-) Delete Verge Wallet 4.0.1
-) Download the actual Verge Wallet from here: https://github.com/vergecurrency/verge-core-installers
-) Install VERGE Wallet
-) Copy blockchain data to the wallet
-) Replace wallet.dat
-) import private address to wallet (How do i do this??)

Correct? 
Thanks for your help
Chris

**Comment by justinvforvendetta** [comment]
no, just close your wallet, delete your old wallet .exe file, download the new one from here: https://github.com/vergecurrency/VERGE/releases/tag/4.0stealth  then, open it up and leave it for a few minutes.

**Comment by justinvforvendetta** [comment]
yes, you can back up your wallet.dat though, you should do that anyway, on a regular basis.

**Comment by christopht1981** [comment]
:-( Still the same problem.
Do you recommend to completely de-install the Wallet and re-install?

**Comment by jrsikors** [comment]
Did you use the link that justin provided?  Or did you use your link?

Yes -- uninstall Verge..
then go to 
https://github.com/vergecurrency/VERGE/releases/tag/4.0stealth
 download: VERGE-windows.zip

UNZIP the 2 files to like c:\verge\client,, thats it ,, there's no installation

run verge-qt.exe

**Comment by christopht1981** [comment]
I used Justins one.

Okay. I `ll do that. 
And it´s enough to save the address as csv before. Can i import later on?

**Comment by jrsikors** [comment]
just make sure you got a good copy of your wallet.dat safe on a jump drive far away from your computer.  We can bring that in later easily

Just follow those steps right now and get your client sync'd.  don't worry about the wallet right now.

**Comment by jrsikors** [comment]
and i'm not sure what you mean by "address as csv".  If it's only your public address, that's not enough.  You need your public address AND private key.

**Comment by christopht1981** [comment]
Where do I get the private key

**Comment by jrsikors** [comment]
open verge-qt.exe
unlock your wallet 
help -> debug window -> console tab.. type:
dumpprivkey "YOUR_WALLET_ADDRESS"

**Comment by justinvforvendetta** [comment]
you can retrieve your private key by doing dumpprivkey address in help/debug console

**Comment by christopht1981** [comment]
Jeff, I really have problems with that wallet and I am desperate. 
If I try to get the private key and enter the phrase above nothing happens. No private key, no message, no error. 
What should I do?

**Comment by christopht1981** [comment]
Is there any logfile in the Verge folder which can be checked oder something.

**Comment by jrsikors** [comment]
open Verge-qt ... do another screenshot and post of your Help -> Debug Window .. the information tab / screen.

**Comment by jrsikors** [comment]
Here is what I would do if I was you .. and you really need to follow **EXACTLY** step by step, no shortcuts or "Oh my way will be fine".

**0) make sure your current/good wallet.dat file is saved on a jump drive / somewhere on your computer (even create/copy it to something like c:\vergewallet\wallet.dat)**
1)  Create a new folder on your C:\ called C:\Verge
2)  download this https://github.com/vergecurrency/VERGE/releases/tag/4.0stealth   " VERGE-windows.zip"
3)  unzip it to C:\verge\client
4)  download one of the verge blockchains from https://verge-blockchain.com/down
*while you wait, go to step 5*
5)  delete **everything** under c:\users\<user>\AppData\Roaming\VERGE\
6)  unzip file from step 4 it to c:\users\<user>\AppData\Roaming\VERGE\  
7)  copy your wallet.dat from step 0 to c:\users\<user>\AppData\Roaming\VERGE\
8)  go to c:\verge\client ... and run verge-qt.exe as Administrator

If you did all these steps EXACTLY as I said -- your verge-qt.exe should take a while to load up.  After that -- it should begin syncing the latest blocks.

Once you are fully sync'd ... if you transaction still doesn't show ... go to:
Help -> Debug Window -> Console tab
type:  scanforalltxns
**wait until it's done** **(do NOT close down Verge-QT wallet, it will look like it's not responding, but it's fine, it will respond once it's done scanning)**

**Comment by christopht1981** [comment]
Yes Jeff, thank you, thank you, thank you. 
I followed your instructions and the wallet is working right now. 
My outstanding transactions showed up. A test transaction to binance worked fine.

What I tried was to get the private key in the console. I entered dumpprivkey address but got following message: Private key for address <address> is not known (code -4)

Do I have to enter the address for receiving payments? Or which address do i have to enter?

And at the older electrum wallet I got a seed? Does the Verge-QT wallet not have a seed?

**Comment by jrsikors** [comment]
If your receiving address is DCFNabcdefgh .. and you want the private key for it .. go to console and type:
dumpprivkey DCFNabcdefgh
Might have to do it with quotes, so:
dumpprivkey "DCFNabcdefgh"

You can only dumpprivkey addresses that are loaded in your wallet.   In the verge client .. the 3rd icon down that says "Shows the list of addresses for receiving payments".  Those addresses are the only ones you can dumpprivkey

**Comment by jrsikors** [comment]
and no -- you don't need a "seed" for Verge-QT wallet.  Just your public address and private key ... and you don't even really need those if you take excellent care of your wallet.dat file.  your public address and private key are definitely good to have for emergencies though.

**Comment by christopht1981** [comment]
Hmm I tried it with my loaded addresses: 
I tried a few times and got following messages: 

First attemp:
Private key for address XYZabc is not known (code -4)

Second attemp, I tried with quotes:
Wallet is unlocked for minting only. (code -13)

Third attemp, I tried without quotes:
Wallet is unlocked for minting only. (code -13)

?

**Comment by jrsikors** [comment]
Yeah sorry -- unlock your wallet first.  Settings -> Unlock wallet... put in your passphrase

**Comment by christopht1981** [comment]
I tried both. locked or unlocked. Both does not work. 
Same message. Is there a special code for non stealth adresses?

**Comment by jrsikors** [comment]
alright yeah that's either a bug or working as designed for your own protection.

So do this... lock your wallet again .. settings -> lock wallet

go to debug console again

Let's assume your passphrase is *Hi My Name Is Chris*

you need to type:
walletpassphrase "Hi My Name Is Chris" 300

this will unlock your wallet for 300 seconds

Then do the dumpprivkey XYZabc ... no quotes needed on the address , just tested it on mine

**Comment by christopht1981** [comment]
Jeff, yeah it was working. Thank you, you are great. How can I thank you? Do you accept donations as a thank you?

**Comment by jrsikors** [comment]
You are welcome, no worries !
