### ISSUE TITLE
Big amount of XVG doesn't shows on my wallet version: v2.1.0.0.-9583c86-beta. macOS Sierra,

### ISSUE THREAD

**Issue by Alex3444** [vergecurrency/VERGE#569]
Hello friends, 
Yesterday I done it 3 transfers from bittex.
 first 100 xvg  was added to my wallet after 3 minutes , after what I done it big amouth of xvg  which one I still din't received.
after that I done it another transfer  off 3 xvg, there are was added instant.
I checked https://verge-blockchain.info ,  all my 3 transfers shows there.
May be any one know why big amounts of xvg I still didn't receve on my wallet ?
I'm using macOS Sierra, 10.12.6. 
wallet version: v2.1.0.0.-9583c86-beta.

Trying to dowlod and instal the laytest version VERGE-Qt-23-06-2018.dmg to my another Mac 
but this version doesn't work :( 
shows me this:

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Can any one help me please to resolve this problem ? 

Thanks

**Comment by justinvforvendetta** [comment]
you have to use the newest wallet. the old one no longer works

**Comment by Alex3444** [comment]
Can you tell me pls what version is right for macOS Sierra, 10.12.6. ? 

Trying to dowlod and instal the newest wallet version VERGE-Qt-23-06-2018.dmg to my another Mac
but this version doesn't work :(
shows me this:

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
Library not loaded: @loader_path/libboost_system-mt.dylib
Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
Reason: image not found

**Comment by justinvforvendetta** [comment]
that is the one you need. there are other issues here that describe how to fix that problem.

xcode-select --install
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew install boost
brew install boost@1.66
