### ISSUE TITLE
Want to know the hashing algorithm of VERGE

### ISSUE THREAD

**Issue by shwuhk** [vergecurrency/VERGE#571]
I am a pool operator and is trying to support VERGE. However, I cannot get it done.
I don't find a regtest option in VERGE and the testnet was very slow. I can only use real money to buy hashrate and test in main net. I suspect the algo I am using was wrong and so cannot submit block successfully. This is what the debug.log of daemon shows.

I find ```submitblock``` in debug.log and find that there is two type of message
```
ThreadRPCServer method=submitblock


******* exception encountered *******
/var/pools/daemons/xvg-scrypt-4.0stealth/src/VERGEd(+0x22a92f)[0x55dcf11a292f]
/var/pools/daemons/xvg-scrypt-4.0stealth/src/VERGEd(+0x59eed)[0x55dcf0fd1eed]
/var/pools/daemons/xvg-scrypt-4.0stealth/src/VERGEd(+0x122b5f)[0x55dcf109ab5f]
/var/pools/daemons/xvg-scrypt-4.0stealth/src/VERGEd(+0x98f1e)[0x55dcf1010f1e]
/var/pools/daemons/xvg-scrypt-4.0stealth/src/VERGEd(+0x9cd39)[0x55dcf1014d39]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0(+0x115d5)[0x7f93590df5d5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f93579b96ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f93576ef41d]
```
or
```
ThreadRPCServer method=submitblock
Sign failed
```
May you know why would this happen?

One more thing, I am using these algorithm, is it correct(CoinBase(sha256D), Header(algorithm of daemons, scrypt/lyra2rev2 etc) and BlockHash(sha256D reverse)?

Any help would be very appreciated!

**Comment by justinvforvendetta** [comment]
scrypt, lyra2rev2, x17, myr-groestl, blake2s

**Comment by justinvforvendetta** [comment]
also your directory names are overly complicated, you could just name each by algorithm

**Comment by wijnandschouten** [comment]
Did you work this out?

" scrypt, lyra2rev2, x17, myr-groestl, blake2s "

It seems in the man it is not blake2s but blake (without 2s )
