### ISSUE TITLE
Unconfirmed transaction 

### ISSUE THREAD

**Issue by Cyber84** [vergecurrency/VERGE#572]
# Issue Template

## Context

2 transaction are still unconfirmed and  Also not visible in Blockchain

## Prerequisites

* [ yes] Are you running the latest version?

## User Story
I'm submitting a support request .

I have the following issues:

    I have sent a transaction to myself using the new 4.0.1 core wallet on windows and also recived one transaction which is unconfirmed as well. 
Tranaction are visible in wallet but not in blockchain.

Is there anyway to push the transaction or restore? 
    

I am using the following:

    Windows 10
    4.0.1 windows wallet

## Screenshots

![3](https://user-images.githubusercontent.com/10885338/35474018-ad193016-0388-11e8-8f6f-3a3c2848e4c8.png)
![1](https://user-images.githubusercontent.com/10885338/35474021-b1cd3454-0388-11e8-9b87-add3ff5e1c03.png)
![2](https://user-images.githubusercontent.com/10885338/35474023-b39909e8-0388-11e8-84b7-abf268986505.png)

**Comment by jrsikors** [comment]
you sure you are on "4.0.1 fork for stealth"?  There are 2 different 4.0.1 for windows floating around

**Comment by Cyber84** [comment]
![afbeelding](https://user-images.githubusercontent.com/10885338/35474144-77158b2a-038a-11e8-95ad-297873e70948.png)

**Comment by jrsikors** [comment]
Do a screenshot of your Help -> Debug Window too please.. the information tab.

**Comment by Cyber84** [comment]
As requested:

![afbeelding](https://user-images.githubusercontent.com/10885338/35474208-727c9c74-038b-11e8-8787-e593fc6d3ebc.png)

**Comment by jrsikors** [comment]
I was about to comment on the "estimated total blocks" , but then i looked at mine and it says the same thing.

If the transactions never hit the blockchain, they will eventually time out (sunerok can explain that better).

If it was ME in your position, and I had an older copy of wallet.dat from a week or month ago, I would just close out of verge, load the old wallet.dat backup, and re-open verge.  The stuck TX's should go away, and you can try to re-send.  

But someone smarter than me might have a better solution if you can wait.

**Comment by Cyber84** [comment]
I think I have on older wallet backup before stealth address! what will happens with my stealth address if I restore older wallet backup?

**Comment by jrsikors** [comment]
If you generated any new addresses and don't have a wallet.dat backup with those new addresses, dont do anything i suggested!

**Comment by Cyber84** [comment]
I'm afraid I did and made backup over my backup after stucked TX!!!

**Comment by jrsikors** [comment]
but definitely make a backup of that wallet.dat file NOW ... and always remember to make backups of your wallet.dat after:
  ~New transactions
  ~New addresses generated

You will still be fine, just hang out a bit and someone else will come along to help out with the stuck TX's

**Comment by jrsikors** [comment]
and possibly obvious suggestion --- but you've tried closing down verge-qt wallet and re-opening already right?

**Comment by jrsikors** [comment]
Worst case scenario.. what I've seen suggested before is:
Close out of verge-qt wallet
**Leave closed for 48 hours.**  
Then re-open verge-qt.
Stuck TX's should be gone.

**Comment by jrsikors** [comment]
never mind I see your startup time was recent from your screenshot.

**Comment by Cyber84** [comment]
Yeah I tried that already. Now I made backup of existing. putting the old backup to see what happens.
if it works I just need to reasign new stealth address.

I'll share the result afterwards.

Thanks for your help so far.

**Comment by Cyber84** [comment]
OK TX are restored but Indeed I lost my Stealth Address which means small adjustment.

Thanks for help.
