### ISSUE TITLE
Cannot start VergeQT 4.0.1 in MacOS 

### ISSUE THREAD

**Issue by assal01** [vergecurrency/VERGE#574]
I trying opening the new Verge QT app in my Mac with no success.
I just downloaded 4.0.1 and installed. I had sync'd the Blockchain before.
I expected the Verge QT app would open, and I got an error box.

[VergeError.txt](https://github.com/vergecurrency/VERGE/files/1670627/VergeError.txt)

* Verge Release: 4.0.1
  Model Identifier:	MacBookPro10,1
  Processor Name:	Intel Core i7
  Processor Speed:	2,7 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Memory:	16 GB
  Boot ROM Version:	MBP101.00F2.B00
  System Version:	macOS 10.13.3 (17D39a)
  Kernel Version:	Darwin 17.4.0

**Comment by ebrinkster** [comment]
Works fine with new release, 4.0.2.  Follow installation instructions on the main page as well.

**Comment by badsloth** [comment]
Thats great that its working for you but its not working for me either on High Sierra. Won't open at all. Seems like there are quite a few High Sierra users it won't open for. Hopefully this will get a fix.

**Comment by justinvforvendetta** [comment]
fixed in latest commit

**Comment by assal01** [comment]
@justinvforvendetta working perfectly now. Thank you!

**Comment by romik1970** [comment]
@ebrinkster. Could you please clarify where can I find those instructions? The main page of what? There are no instructions in the GitHub, nor on the vergecurrency.com.

 Thank you.
