### ISSUE TITLE
VERGE-QT not opening on my MAC

### ISSUE THREAD

**Issue by WestOz** [vergecurrency/VERGE#576]
My QT-2 wallet was running well until I tried to install the new update 4.0.1. Instead of replacing the wallet I opted to "keep both" (worrying to lost my tokens), and new wallet doesn't open.

Termination Reason:    DYLD, [0x1] Library missing

OS Version:            Mac OS X 10.13.1 (17B1003)

**Comment by batigol82** [comment]
My verge qt-wallet 4.0.1 for osx is work. But my problem is: I import the privatkey from xvg-electrum wallet 2.4, now i see the adresse in the qt-wallet 4.0.1 but the balance is 0! Who can help me?

**Comment by filimo** [comment]
I have same problem on my mac.

```

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

Binary Images:
       0x103d30000 -        0x1046a3fff +com.vergecurrency.VERGE-Qt (4.0.1 - 4.0.1) <2B77BF2D-DFA9-3195-ADAD-BE31889C17F4> /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
       0x104772000 -        0x104774fff +libboost_system.dylib (0) <F3411558-02A6-3F5A-B040-E70EEB13F639> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_system.dylib

```

**Comment by WestOz** [comment]
Process:               VERGE-Qt [1385]
Path:                  /Applications/VERGE-Qt 3.app/Contents/MacOS/VERGE-Qt
Identifier:            com.vergecurrency.VERGE-Qt
Version:               4.0.1 (4.0.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           VERGE-Qt [1385]
User ID:               501

Date/Time:             2018-01-29 20:13:08.826 +0800
OS Version:            Mac OS X 10.13.1 (17B1003)
Report Version:        12
Anonymous UUID:        262FF7FD-9DCB-0999-2D9A-2DF948713B03

Sleep/Wake UUID:       C38D67FF-6844-4AA3-946C-4F2EE7E14F42

Time Awake Since Boot: 18000 seconds
Time Since Wake:       67 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @loader_path/libboost_system-mt.dylib
  Referenced from: /Applications/VERGE-Qt 3.app/Contents/Frameworks/libboost_thread-mt.dylib
  Reason: image not found

**Comment by WestOz** [comment]
I tried the sequence below and worked for me.ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew doctor
brew install boost

Password is the same as your computer
