### ISSUE TITLE
Can´t get it to synch Wraith 4.0.1

### ISSUE THREAD

**Issue by Paapo** [vergecurrency/VERGE#581]
Hi, i really need help:-(

I don´t wonna bother you with the hole Story. My Issue is: I can do whatever i want, i can´t get my wallet to synch until the end.

What i have:
- My old Wallet.dat (Several Versions), with Encryption pw, seved from version 3,0.
- No private Keys. I always thought, wallet.dat is all i need.
What i have done:
- did all the steps, as described. Downloaded new version. Saved old wallet.dat. Removed all files from Vergefolder, except wallet dat. Unzip Blockchain to Verge Folder. Tried to overwrite, as well as remove the old files and copied over the new files. Then restarted the programm. It has stated to synch and next morning, both "out of synch signs were gone and i thought, wallet was synched and updated fine. the i have cerated a new address (Non Stealth) an and made 3 transactions from cryptopia. First one over 100 to the new cerated non stealt adress. Cryptopia has shown the transaction com´pleted, but i couldn´t found it. Neither in the block explorer, nor in my wallet. Block Explorer has shown an error message.
Then i made a second transaction to my old, always used address over 5 xvg. Also from Cryptopia. This transaction was shown instantly as unconfirmed balance, in my wallet. Then i made my 3. transaction, over 16K xvg, to my old address as well. But this has never shown up in my wallet. So, although both out of synch sighns were gone and no status bar was shown, my wallet wasn´t synched,
And now I´m struggling since days, to get my wallet back to work, but without success.. that really suxx..
Please can somebody help me, to get back my coins into my wallet.
Can it be, that there is no progress for more then a day, with only 2500 block left to synch??
Oh, I´m using windows 10. Necer had any issues with  version 3.0..

Ah, what i´ve tried also was: Once my wallet is opened, i tries to debug my private keys, from my both xvg adresses shown in the wallet. Wallet is unlocked. But after hitting enter I´m getting an error message: Wallet is unlocked for mining (code 013). Does my wallet needs to be synched, to read out my private keys?

Regards,
Marcus
![wraith](https://user-images.githubusercontent.com/27375501/35500746-c8320cec-04d7-11e8-9a3d-d14347ff4f00.JPG)

**Comment by Max-Meldrum** [comment]
Has the sync progress (the bar) finished? Even when that is done, the application has to sync in background and it will say out of sync even though the bar is done. If you go to the help option you can see info on connections and block numbers. Or if you hold over the blue signal thing, how many connections does it say you have?

**Comment by Paapo** [comment]
No, synch hasn´t finished yet. that is my problem. Statusbar is coming and going, but there is no progress, since more than 24 hours now. Right now, statusbar is gone again. Wallet is still showing "out of synch" and i have exactly 28 active connection shown in the buttom right corner.

Thank you verry much for your help.

REgards,
Marcus

**Comment by Max-Meldrum** [comment]
If you go to the debug console window through the help tab. and in this console write in the command getinfo. If you can take a screenshot of that or paste the result here, would be great.

**Comment by Paapo** [comment]
This is the outcpme..In the meanwhile, statusbar is still gone..
￼
{
"version" : "v4.0.1.0-unk-beta",
"protocolversion" : 90001,
"walletversion" : 60000,
"balance" : 29664.60782100,
"newmint" : 0.00000000,
"stake" : 0.00000000,
"blocks" : 1829214,
"moneysupply" : 14514733839.99999619,
"connections" : 42,
"proxy" : "",
"ip" : "qq5naq5m2urzr4ty.onion",
"pow_algo_id" : 0,
"pow_algo" : "scrypt",
"difficulty" : 97927.44219983,
"difficulty_x17" : 9825.13773808,
"difficulty_scrypt" : 97927.44219983,
"difficulty_groestl" : 624513.91946090,
"difficulty_lyra2re" : 5108.69671133,
"difficulty_blake" : 1787465.16996849,
"testnet" : false,
"keypoololdest" : 1516554119,
"keypoolsize" : 101,
"paytxfee" : 0.00000000,
"unlocked_until" : 0,
"errors" : ""
}

Thanks a lot,
Marcus

**Comment by Max-Meldrum** [comment]
If you run it again, has the blocks number changed at all?

**Comment by Paapo** [comment]
Yes, at least sometimes there are a bid more blocks left, than before. Statusbar is back now and i have 9564 blocks left. But I´m pretty sure, I´ve seen it decreasing also..

**Comment by Max-Meldrum** [comment]
Then the syncing seems to be working. You might just have to leave it be and let it process. How is your internet speed?

**Comment by deliriumv** [comment]
I don't recognise that version in your getinfo output - **"version" : "v4.0.1.0-unk-beta"**

The latest Windows version downloaded here shows **v4.0.1.0-794660a-funky-beta**

https://github.com/vergecurrency/VERGE/releases/download/4.0stealth/VERGE-windows.zip

**Comment by Paapo** [comment]
My Speed is good. I´ve 400MBit and it´s working fine. I´ll wait further.. The second pc is also working. It is downloading the hole blockchain right now. 1.2 Mio blocks left:-(

**Comment by Paapo** [comment]
Hm, OK. Then i´ll wait some more time and if it doesn´t work, i´ll try the other version. I´ll let you know my results.

Regards,
Marcus

**Comment by Technophant** [comment]
It's not an issue with his intenetspeed but rather the reliabilty of the tor network, which has been overloaded and unreliable in the past 6 months.  There needs to be configuration utility similar to the one used by the tor browser that also allows you to request a new tor circuit (a set of 3 relays).

**Comment by Paapo** [comment]
Yeaaaa Guys, I´m with you now. What the hell?? I´ve done everything as all the at least 20 times before. But now, with the Funky Version, it has connected. Downloaded the Blocks without issues and is fully synched now. All balances are shown.. Good, three days of panik;.)) thanks a lot.

Kind Regards,
Marcus

**Comment by Technophant** [comment]
Also keep in mind that after the splash screen is gone and the main screen shows up it's still doing indexing and can take a half hour before it starts connecting and downloading blocks.  There needs to be a status and progress message regarding this because it will seem as if it's frozen when you just need to be patient and give it time.

**Comment by Paapo** [comment]
Yes, there would might be a little bid less confusion, if there are more status shown, from the processes in the background. Good to see the percentage shown during the block index load, in this version:-)

**Comment by justinvforvendetta** [comment]
there is an status on the splash screen. if you don't see it you are not using the latest wallet

**Comment by Paapo** [comment]
Yes, i don´t know, were the previous version was from. I ´ve downloaded it, from a link from the verge homepage. The version i gad trouble with, didn´t had this status bar on the splash screen. The Version i´m using now, does have it. I just wanted to say, it is good to see these status:-) Thanks for all your great work..

Regards,
Marcus
