### ISSUE TITLE
yobit xvg

### ISSUE THREAD

**Issue by neo129** [vergecurrency/VERGE#582]
as you know yobit was not updated after January 24, but they made transfers to xvg, at the moment, many, more than a thousand people have money stuck. In Yobit the status of the transfer is fulfilled, but there is no money either on the blockchain or at the exchange where the transfer was made (in my case binance), is there any way to return these funds, or to enroll them?
txid ec933813373aa16235e0cefa1cc410c1a658b9009becc969479cc6b45bad512

**Comment by Tonybostonn** [comment]
+1 Exactly the same situation, help solve the problem.

**Comment by neo129** [comment]
2018-01-24 16:22:56 
1603.66822111 XVG 
c85197b80d59fb77944c1d39dfe13e76759b74f3932f1a24f839a97d3b274958
one more transaction

**Comment by GeminiRos** [comment]
Same problem. I sent xvg with binance.com The transaction is confirmed, but funds for Yobit.net are not reflected.  txid: da01db0a25c52cffbf351a7ebcb24109406919a7f6bce1b650335f598c33c517

**Comment by justinvforvendetta** [comment]
yobit is a scam exchange, that's why they aren't listed on our website. you can try writing their support but they never respond

**Comment by Technophant** [comment]
Hitbtc is a scam too. Check reddit.  People not able to move coins out or very high fees and minimums.

**Comment by justinvforvendetta** [comment]
we do not list yobit on our website, because they are a known scam exchange. hitbtc i wasnt aware of, i will look into it, thanks for reporting it @Technophant

**Comment by pratyush141** [comment]
2018-01-29 00:16:38 pratyushankit
currency_id: 89 (XVG), txid: 78db530835ce5a62028c86997cb0e9724f15b5f0cbab602405e62c45a7b74436
Send 429.9 XVG from binance not reflected to my yobit wallet. Transaction is completed

No response from yobit. Is there any way to recover... :-(

**Comment by Influence2** [comment]
@pratyush141 as said above, yobit is not listed on the verge website becuase they are a known scam exchange and have never updated the verge wallet (I believe). You need to contact yobit support, thats your only real option. Sounds like they are unfortunately ignoring you.

**Comment by Tonybostonn** [comment]
yobit update the wallet, but they say that the coins were sent to the old network, can you do something and return the coins from the old network?

**Comment by justinvforvendetta** [comment]
that doesn't make sense. if they were sent to the "old network" they exist on the new network and can be accessed by importing the wallet on the updated blockchain. this is another reason we don't list them on our website

**Comment by pratyush141** [comment]
Finally yobit updated wallet and credited my XVG after about 10 days but from now I will use yobit.

**Comment by eusvolk93** [comment]
I sent 220,750 XVG to Yobit. Never received it. I'm not really sure what to do... Any ideas?

Address:	DTrowZMKBh73zoes3Y682p2aeuYXDiDRaG
Txid:	cc0910638574007b842c2f9aeffe432bcf14df2b297d378b6d4176d1bb14fff1

**Comment by jrsikors** [comment]
DTrowZMKBh73zoes3Y682p2aeuYXDiDRaG = your wallet on yobit?

There is literally nothing anyone can do other than Yobit.  You gotta open a ticket on their exchange.  sorry and good luck :(

**Comment by eusvolk93** [comment]
Yes, as you can see my xvg arrived, but they havent credited me. I opened two tickets. Hopefully I receive a response and a credit before the 17th however looking at reddit forums it seems its lost forever.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by justinvforvendetta** [comment]
yobit has a very bad reputation for coin maintenance, but i wish you luck. they are so bad that we do not list them on our site as an exchange.

**Comment by eusvolk93** [comment]
Yeah, I've learned my lesson the hard way. I've had similar issues with them in the past and never received a response but was credited. I'm hoping for the same thing to happen but not holding my breathe. This was definitely my last time using them. I didn't know that they were such a shunned exchange until tonight.

Binance seems to be the only reliable exchange these days.

By the way, love the project. If i dont receive it ill be just dumping cash back into xvg. Keep up the great work.

I currently am liscensed by Apple and sell my own brand of Apple certified charging accessories on Amazon with 5 star reviews. Would love to be apart of your merchant program. Safewire is my brand.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by weslei00** [comment]
I sent it two days ago 32000 XVG, already been confirmed more than 4000 times and so far it does not appear in Yobit, I opened a ticket in the standby wait now, I would have them solve this problem :S

**Comment by akshitraheja** [comment]
I sent 6700 xvg yesterday. Didnt received the coins till yet. Please share the information if your coins get creditted. Really disappointed with the yobit

**Comment by weslei00** [comment]
I am following here, so I have news I will post here, the complicated value is rising and I can not negotiate the coins.

**Comment by weslei00** [comment]
when you have news post here, Sorry for the match errors, I'm using google translator, I'm Brazilian.

**Comment by weslei00** [comment]
I just received the following email from Yobit: Dear User!

Support answer:

We solve the problem.
We apologize for the inconvenience.

Please answer in tickets only, don't send any answers to email! Tickets: https://yobit.net/en/support/

Now I can only wait.

**Comment by akshitraheja** [comment]
No problem. I sent 6700 in that wallet and when i see the wallet address , the verge are transferred to somewhere else. Did it hapen with you too?

**Comment by weslei00** [comment]
I transferred from Bittrex to Yobit, in the blockchain the transaction is concluded, believe that Yobit is having a difficult time to credit the currencies in our accounts

**Comment by akshitraheja** [comment]
But i can see my verge xvg transferred to somewhere else from that wallet?? Like they steal it and transferred to their wallet

**Comment by weslei00** [comment]
In your case it has been transferred from your wallet to another?

**Comment by akshitraheja** [comment]
Yes bro. They have sent it to somewhere else.

**Comment by weslei00** [comment]
Wow, this can not be a good thing.

**Comment by akshitraheja** [comment]
You check it? Are your verge there only?

**Comment by weslei00** [comment]
look, the first 3 transactions were not for my wallet yet:

https://verge-blockchain.info/address/D81w3qrKrj4SWzD5WNgExTF7bNtJPvY73m

**Comment by weslei00** [comment]
they said they will solve it, now I'm waiting, and hoping to work out

**Comment by eusvolk93** [comment]
I got my xvg. Never using yobit again.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by akshitraheja** [comment]
I also received mine

**Comment by weslei00** [comment]
I also received my coins, what a relief :d

2018-04-02 10:07 GMT-04:00 akshitraheja <notifications@github.com>:

**Comment by Anna9735** [comment]
I’m a crypto/blockchain journalist and host of the Unchained and
Unconfirmed podcasts. I’m working on a book about the history of the
crypto yet I got scammed not knowing its very possible to recover your
stolen or lost crypto by private hackers via discuss, i’m a living
witness of this genuine recovery service. I learn a
lot from him and I’m also glad to review him right here. Freddictine At consultant dot com
