### ISSUE TITLE
Electrum invalid fee.

### ISSUE THREAD

**Issue by jimrecord** [vergecurrency/VERGE#583]
## Context

Hello i have a little problem my wallet electrum have the invalid fee message error when i want make a transaction. i have passed 10 hours on this problem and i can not to solve the problem. (sorry if i have a bad english)

## Prerequisites

* I run on electrum 2.4.1, windows 10 (64 bits), AMD FX 8350 OC (4,6 Ghz)

## User Story:

* it's literally 20 -25 days that i am not touching my wallet i comback recenlty on and i finds this problem, i have try to pass my xvg coins on the Electrum TOR wallet but the problem i'ts again here. i have try too the download the QT wallet for try a transaction on this but nothing too do. i have try to sweep my address on the menu wallet > private keys > sweep but nothing.. when i try this i have the message "TX rejected" and i cant finish the operation.

## Screenshots

![2018-01-29 2](https://user-images.githubusercontent.com/35922904/35512485-3ebf908c-0500-11e8-9654-8606a6008ac0.png)
![2018-01-29 3](https://user-images.githubusercontent.com/35922904/35512498-42896404-0500-11e8-9779-da7ba74a1e83.png)
![2018-01-29 4](https://user-images.githubusercontent.com/35922904/35512505-45ac8030-0500-11e8-836d-59ddb74efc26.png)
![2018-01-29 5](https://user-images.githubusercontent.com/35922904/35512511-497c8ae8-0500-11e8-85cf-ba896154a048.png)

## Your Environment

* Verge Release: Electrum 2.4.1
* CPU: AMD FX 8350 OC (4,6 Ghz)
* GPU: GTX 1080 + GTX 1060
* RAM: 16 Go DDR3 1800 Mhz
* OS: Windows 10 (64 bits)

**Comment by Technophant** [comment]
This should actually be written up as an Electrum issue.  I copied your text and started an issue there: https://github.com/vergecurrency/electrum-xvg-tor/issues/32

**Comment by Technophant** [comment]
This issue can be solved, or at least worked around by using an amount that's one less than total.  Can I please get promoted to a collaborator so I can close tickets?

**Comment by jimrecord** [comment]
you can send if you using not the totality of your wallet ? sorry 
I did'nt understand everything.. for me i cant send any amount

**Comment by Technophant** [comment]
Lets say you have 10 xvg.  If you send 9 with a 1 xvg tx fee then that's your whole balance.  The tx fees need to be fixed there, don't need to be so high.

**Comment by jimrecord** [comment]
ok but if i want send a transaction with a fee manual i have a bug and not broadcasting windows appears, i am very lost with all that.. i suppose even never find my xvg of my wallet

**Comment by Technophant** [comment]
The manual fee doesn't work either.  Have to use default.

**Comment by jimrecord** [comment]
you too ?

**Comment by jimrecord** [comment]
i have test with all payement verified by removing the file blockchain_headers on C:\Users\AppData\Roaming\Electrum-XVG but nothing again..

**Comment by underdarkskies** [comment]
I had this issue and resolved it by increasing the fee. the issue stems from the fact that your balance is split across many keys in your wallet, in order to generate the output, electrum has to combine the inputs of multiple keys to a single output. this is a larger sized (in KB) transaction and unfortunately XVG's electrum doesn't auto calculate the fee correctly. for me i had to test the transaction out multiple times and ultimately a fees of 5 verge led to a successful transaction. but this is unique to you and the number of input address you are using to generate the output of 540 xvg... good luck

**Comment by jimrecord** [comment]
I use 1 address for receive my xvg but i have a another address not used, i have tried a lot amount fee manual on "transaction fee per kb:" but even with 100 xvg in fee the transaction cant want send. you have enter the fee by checking "set transaction fees manually" or on "transaction fee per kb" ?

**Comment by jimrecord** [comment]
ok i have resolve this bug !!!! my god.. for info i have pass the "transaction fee per kb" at 2 on the preférence menu, i have then create an address for sweep the principal private key we need to go on the wallet menu > private keys > sweep and enter the private key of your address primary (address containing your XVG bugued) and you select the address where you want to send. (sorry i have not a good english but i hope this will help you.)
