### ISSUE TITLE
problems with wallet VERGE-qt.ehe on win

### ISSUE THREAD

**Issue by good777** [vergecurrency/VERGE#584]
Problems with the withdrawal from binary to the electronic wallet VERGE-qt.exe.
did not come coins from the exchange binance here this address D98tkYG2LsDiraSreQUwkXzTm96zqzkhqx synchronization was passed.
what to do?

**Comment by justinvforvendetta** [comment]
is your wallet at the same block height as verge-blockchain.info?

**Comment by justinvforvendetta** [comment]
that address has 29 coins. you didn't update your wallet.

**Comment by good777** [comment]
Purse verge is synchronized but the coins for some reason are not present. I was happy with this purse from this site https://vergecurrency.com/langs/ru/#walts is this your site?

**Comment by justinvforvendetta** [comment]
did you already make sure you are on the same block as verge-blockchain.info?

**Comment by good777** [comment]
My coins in the blockade are there and there is no way to understand it?

**Comment by justinvforvendetta** [comment]
im saying did you make sure your wallet, is on the same block number as the explorer?

**Comment by good777** [comment]
Pay attention to the video where I show my wallet and the address on which the coins were supposed to arrive.
https://photos.app.goo.gl/qAGuHbj98KNHncZ32

**Comment by justinvforvendetta** [comment]
you are not on the right blockchain, thats why your wallet says out of sync. please download the newest wallet, and delete your current blockchain data (except your wallet.dat) and you'll have your coins again.

**Comment by good777** [comment]
I would have instructions on how to do this? And then I have a hike from the hands of the ass grow.
