### ISSUE TITLE
Will verge be sustainable, scalable, reliable after 5 or 50 years with PoW?

### ISSUE THREAD

**Issue by islarky88** [vergecurrency/VERGE#585]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
yes, of course, and this is not a reason to open a github issue on the source code.

**Comment by Max-Meldrum** [comment]
It is a good question, but it would be more suited to ask this at Reddit/Discord. Issues in this repo are meant for bugs and enhancement proposals etc..

**Comment by justinvforvendetta** [comment]
we can edit the block size and fork to larger blocks in about 15 minutes if we needed to, but due to our block time, I'm not sure we would ever be in that position

**Comment by Technophant** [comment]
This is built on the bitcoin core, so it uses 1mb blocks also?  curious.  how did you modify to use 5 algos?
