### ISSUE TITLE
Qt-Wallet 4.0.1, import privatkey from electrum wallet 2.4, but the balance is 0 zero

### ISSUE THREAD

**Issue by batigol82** [vergecurrency/VERGE#586]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by batigol82** [comment]
I download the version 4.0.1 for osx from github, the newest blockchain...
The wallet works, sync. is finish....all good
My problem, now i import my privatkey from electrum wallet 2.4 on console, now i see my adresse from electrum wallet in the new qt-wallet 4.0.1 but the balance show me 0 zero??

**Comment by justinvforvendetta** [comment]
are you sure you imported the private key to the address in electrum that has a balance? electrum wallets have many addresses and keys

**Comment by jrsikors** [comment]
Go to help -> debug .  Please post a screenshot or copy/paste details from that screen.

Other thing to try is to go to help -> debug -> console and type:
scanforalltxns

Give it about 15 minutes.. it might look like your app is broke but don’t cancel out.. wait until it’s finished.

Make sure you backup your wallet.dat before you do any of this

**Comment by jrsikors** [comment]
And what Justin suggested.. go to www.verge-blockchain.info and search for your address.. make sure it has a balance

**Comment by batigol82** [comment]
I've just opened the wallet for the 5th time and synced it, now it shows me the right balance. How can that be?

**Comment by batigol82** [comment]
<img width="1280" alt="bildschirmfoto 2018-01-29 um 21 39 12" src="https://user-images.githubusercontent.com/35903136/35533207-1b1a16d8-053d-11e8-8db6-693084084671.png">

DP.....f7 is my electrum adresse

**Comment by batigol82** [comment]
I don`t send the coins from my electrum wallet to the new qt-wallet, i import the privatkey!

**Comment by Influence2** [comment]
@batigol82  Is this issue resolved now and you are able to see your balance? It seems like after you let the qt wallet finish syncing it shows your 38k Verge?

**Comment by batigol82** [comment]
now it shows me the balance right. it is normal that it starts with each qt-wallet until it sync. is and you can make transfers?

**Comment by Influence2** [comment]
Sorry its hard to understand what your saying due to language, but I believe what your asking is if you have to wait for wallet to sync before seeing balance or making transactions. That is correct, you should let the qt wallet sync FULLY before doing anything. This can take over a day sometimes. It took mine about 18 hours. 

If this resolved your issue you can close the issue.
