### ISSUE TITLE
problem with windows Qt wallets

### ISSUE THREAD

**Issue by RaRaLand** [vergecurrency/VERGE#587]
I have transaction 11009b1b646215218a51ac71d254e9f1bdf1cd84ca3218737b373eb05b5fc280
which in 
windows Qt wallet v4.0.1.0-unk-beta 

> {
> "version" : "v4.0.1.0-unk-beta",
> "protocolversion" : 90001,
> "walletversion" : 60000,
> "balance" : 1.29828300,
> "newmint" : 0.00000000,
> "stake" : 0.00000000,
> "blocks" : 1828482,
> "moneysupply" : 14513591919.99999619,
> "connections" : 24,
> "proxy" : "",
> "ip" : "xaydopnpztz7mwmc.onion",
> "pow_algo_id" : 0,
> "pow_algo" : "scrypt",
> "difficulty" : 52418.40190395,
> "difficulty_x17" : 1.66425415,
> "difficulty_scrypt" : 52418.40190395,
> "difficulty_groestl" : 18008.27586207,
> "difficulty_lyra2re" : 43.27829270,
> "difficulty_blake" : 1752993.17702205,
> "testnet" : false,
> "keypoololdest" : 1516117534,
> "keypoolsize" : 101,
> "paytxfee" : 0.00000000,
> "errors" : ""
> }
> 

Have 1584 confirmations

! [1584 confirmations] (https://image.ibb.co/eyS5R6/v4_0_1_0_unk_beta.jpg)

But 
windows Qt wallet v4.0.1.0-794660a-funky-beta

> {
> "version" : "v4.0.1.0-794660a-funky-beta",
> "protocolversion" : 90001,
> "walletversion" : 60000,
> "balance" : 38.93990800,
> "newmint" : 0.00000000,
> "stake" : 0.00000000,
> "blocks" : 1839069,
> "moneysupply" : 14530107639.99999619,
> "connections" : 15,
> "proxy" : "",
> "ip" : "xaydopnpztz7mwmc.onion",
> "pow_algo_id" : 0,
> "pow_algo" : "scrypt",
> "difficulty" : 84775.60617425,
> "difficulty_x17" : 7037.98428830,
> "difficulty_scrypt" : 84775.60617425,
> "difficulty_groestl" : 837090.43707060,
> "difficulty_lyra2re" : 25999.76850899,
> "difficulty_blake" : 2780033.35185855,
> "testnet" : false,
> "keypoololdest" : 1516117534,
> "keypoolsize" : 101,
> "paytxfee" : 0.00000000,
> "errors" : ""
> }

Have 0 confirmations

! [0 confirmations] (https://image.ibb.co/dZgzm6/v4_0_1_0_794660a_funky_beta.jpg)

And same situation with more important for me TX# 3df99aedfad3b54b3b66521e4ea204615fcb0ea76458b22d2b696884b9a009dd

1. We are on blockchain or what. Where i can find arbitrage block explorer ?
2. How to fix this? Sync last wallet but how and how to determine which transaction is good or bad?

**Comment by justinvforvendetta** [comment]
verge-blockchain.info is the most up to date

**Comment by Technophant** [comment]
The second transaction is not on the blockchain so it never got broadcasted.  Go to debug console and give us the outputs of listtrasactions and listunspent
