### ISSUE TITLE
Problem with embedded Block Explorer in Windows Qt wallet 

### ISSUE THREAD

**Issue by RaRaLand** [vergecurrency/VERGE#588]
Windows Qt wallet  v4.0.1.0-794660a-funky-beta

In embedded Block Explorer i check transaction 
11009b1b646215218a51ac71d254e9f1bdf1cd84ca3218737b373eb05b5fc280

https://preview.ibb.co/hY1tDm/Block_Explorer.jpg
It's look almost fine except no field 'confirmations'

But verge-blockchain.info dosent have this transaction at all.

Which  Block Explorer wrong ?

**Comment by jrsikors** [comment]
If you don’t have any confirmations.. and it’s not showing up on Verge-blockchain .. you probably have a stuck transaction

**Comment by jrsikors** [comment]
If you have an older copy of your wallet.dat with all your addresses ... I would consider closing down Verge-QT, replace wallet.dat with your old one .. and re-open verge-qt.  That should clear the stuck transaction.

If you don't have an older copy ... the TX will time out eventually (48 hours?).  

When did you attempt this transaction?  And can you copy/paste one or more of those input/output addresses in here so we can try to check on verge-blockchain.info?

**Comment by Technophant** [comment]
I was using it and thought there were too different numbers as well, however I was confusing the block number and tx id.

**Comment by justinvforvendetta** [comment]
make sure your wallet has the same block number as the explorer. if it doesnt, you might be on the wrong chain. otherwise, wait a few minutes and check the explorer, as it can take a bit for the transaction to propagate
