### ISSUE TITLE
Feature request: crash reports

### ISSUE THREAD

**Issue by Technophant** [vergecurrency/VERGE#589]
It would be nice to have a diagnostics tab, with network and connection info and an option to send things like listunspent report and debug logs into a zip file saved to the desktop. 

Of course, if you can't actually get into the main windows you can't use this, so a separate crash report log or a stand alone app like Mozilla Crash Reporter that gathers these things for submission.

**Comment by justinvforvendetta** [comment]
in the help tab/debug, there is a sort of diagnostic tab. the wallet can also be started with --debug and it will give a more verbose description of its processes in the debug.log
