### ISSUE TITLE
Unable to recover my Verge qt wallet

### ISSUE THREAD

**Issue by k998um** [vergecurrency/VERGE#591]
Yesterday I have installed Verge qt and sent to it some coins.
Transaction id: 3da5f25462fa028febc7343202697b6236017924c03c034204aea5bb0501aca1
Address: D8wmzdwXJbSQ3ScoGoC9qtigynVS9ny4tB

During the synchronization my space at small ssd disk was out. I started to clean computer. Unfortunately, the Verge directory in Appdata/...Roaming I have deleted too.

When I made a reinstallation of Verge qt - it shows me the new public address and of course no coins.

I have made a recovery of the folder Roaming without errors by Handyrecovery tool and try to put this old version of wallet.dat to Roaming folder.

But now when I launch the programm I get following message: wallet.dat corrupt, salvage failed.

Please, let me know if I have a chance to recover my wallet and coins balance.

I appreciate any recommendations and suggestions in advance!

Best regards,
Evgeny.

**Comment by Technophant** [comment]
You ran a utility that removed the folder? Which utlitiy was that.

I would stop using that harddrive immediately.  Put it into another computer and make an image or take it to data recovery person.  There's no way to recover you coins without the file.

**Comment by k998um** [comment]
The utility which I used was WinDirStat. Inside they have two options for delete files/folders: 1. to recycle bin 2. without possibility of recover! When I made cleaning I choose the second variant because of making more free space...

As I wrote in first message. The recovery of this folder was done completly by myself using Disk Drill (handyrecovery) without any errors and I saved these files on flash usb drive.

But the problem is when I put wallet.dat to this folder I get "wallet.dat corrupt, salvage failed."

Any variants?

**Comment by Technophant** [comment]
1. Use a different tool to see if you can correctly recover the file. 2. Use a tool to see if the seed can be recovered from the wallet.dat.  It's a berkely db format file and there's also bitcoin qt wallet tools that might work.  Our lead dev is the expert in this.

**Comment by k998um** [comment]
1st proposal - i will discover with other tools.
2nd proposal - where can i get such tool to try to recover seed phrase? Who is lead dev?
There was passward installed during installation of verge qt. But I have written it.

**Comment by k998um** [comment]
I tried to recover by: Recuva, EaseUS Data Recovery Wizard, Kvisoft Data Recovery.
All programms gave me almost the same variants of files to recover from Verge directory and file wallet.dat.
I use this files from different recovery programs but the problem is the same: "wallet.dat corrupt, salvage failed."

**Comment by Technophant** [comment]
It's @justinvforvendetta.  He's Doge Coin Dark's creator.  I've pm'd him.

**Comment by Technophant** [comment]
I don't know if there's a windows executible.  You may need to run something from command line that is compiled from source, either by using cygwin, ubuntu live cd, virtualbox etc.   

Quick search found this: 
https://bitcointalk.org/index.php?topic=25091.0

**Comment by Technophant** [comment]
I'm 90% sure you're seed is in there and can be found.  The way file recovery works it may have cut the end of the file off but you have the first part.

**Comment by k998um** [comment]
@Technophant I appreciate for your details and suggestions! Unfortunately I'm not prepared to go through such words as: cygwin, ubuntu, command line and etc. and seems that would be not able to manage this.
I have also found a file with name "private key". When I open it in electrum-xvg it shows the start of private key then a lot of figures number and in the end - end of private key. I could not understand the format but it cannot be imported to electrum. May this file also help me?
If there is somebody who can help - I can send this files for recovery. Please, help guys!

**Comment by justinvforvendetta** [comment]
I can try and help, send me an email justinvforvendetta@gmail.com

**Comment by k998um** [comment]
@justinvforvendetta Thanks for your reply and attention. I have sent all files by mail.

**Comment by k998um** [comment]
@justinvforvendetta Dear Sir, any news on my topic?

**Comment by justinvforvendetta** [comment]
I will check it sometime today

**Comment by k998um** [comment]
@justinvforvendetta thanks!

**Comment by Technophant** [comment]
Would "verge-qt -salvagewallet" from command line work?

**Comment by k998um** [comment]
@Technophant If a question for me - I'm not aware about it, unfortunately.
@justinvforvendetta Do you have any news for me?

**Comment by k998um** [comment]
@justinvforvendetta Dear Sirs, please let me know if have found a time for my issue!?

**Comment by k998um** [comment]
@justinvforvendetta Dear Sir, please, update the information.

**Comment by k998um** [comment]
how to get in touch with @justinvforvendetta ? somebody help.

**Comment by justinvforvendetta** [comment]
I did not get anywhere with it

**Comment by jrsikors** [comment]
closing issue here -- if @justinvforvendetta and @Technophant can't assist -- you might want to try somewhere more visible like reddit, discord, etc.  Sorry :disappointed:

**Comment by k998um** [comment]
thanks for try!
