### ISSUE TITLE
Problem: Transfer Mac Electrum-XVG Version 2.4 to Verge-Qt

### ISSUE THREAD

**Issue by povemail** [vergecurrency/VERGE#593]
1. I made a copy in Electrum-XVG Version 2.4 
a) Clicked File
b) Save Copy
c) Saved on my desktop

2. Installed the newest MacOS Verge QT
a) If I click on the new wallet File there is no import options. Only Backup wallet, export, sign message and verify
b) How do I import the wallet?

How do I import the existing file? where is that file located that I need to replace? Is it in the actual /Applications/VERGE-Qt.app or somewhere else? If somewhere else where then?

I am not a programmer. 
Thank you

**Comment by Max-Meldrum** [comment]
Just to keep things simple, I would recommend sending over the balance to the new wallet. Sure, there will be small fees but probably worth the struggle. Remember to always do a test transfer with a small transaction to see that everything works before transferring the rest.

Else you will have to use the commands dumpprivkey and importprivkey in the console. The former in electrum and latter in new QT wallet.

**Comment by Joske2** [comment]
You need to export the wallet.dat from your Electrum wallet. And place that .dat file into your Library/application support/Verge  folder. Restart the wallet.

That library folder is hidden. Just press ALT and go in the finder menu GO, you will see 'library' (keep pressing alt)

**Comment by justinvforvendetta** [comment]
it doesn't work like that.

**Comment by justinvforvendetta** [comment]
you can just import your private key for addresses that contain a balance in electrum, into your qt wallet.

use the command "importprivkey privatekeygoeshere"
