### ISSUE TITLE
Verge QT for Mac 10.10

### ISSUE THREAD

**Issue by shawnyuan** [vergecurrency/VERGE#594]
Will there be a wallet for those who have Apple computers with OS X 10.10?
Right now what one gets is a "You can't use this version of the application "Verge-Qt" with this version of OS X"
It is only made to use OS 10.13 or later :(

Currently, the only option for some users who may not be able to upgrade to newer OS X is having to buy new computers.

justinvforvendetta@ says verge qt was fixed but it is not. Still not working for Mac 10.10

**Comment by jalkjuyt** [comment]
Not working for Mac OSX 10.12.6 either.. 
Many older mac os users will have to buy new computers. Others will have to install weighty upgrades. Around block 1, 824,000 it hard forks.

What will users with older wallets do when they realise their Verge coins are unaccessible until they upgrade their tech. Why don't Verge seem to even be aware?

**Comment by jalkjuyt** [comment]
There is no Mac Os later than 10.13. It's newest and buggiest Os beta for developers. Can't believe these Dev's living in their own cloud...
