### ISSUE TITLE
WRAITH XVG WALLET CRASHES BEFORE OPENING on HIGH SIERRA

### ISSUE THREAD

**Issue by kevintenda** [vergecurrency/VERGE#595]
Process: VERGE-Qt [576]
Path: /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
Identifier: com.vergecurrency.VERGE-Qt
Version: 4.0.1 (4.0.1)
Code Type: X86-64 (Native)
Parent Process: ??? [1]
Responsible: VERGE-Qt [576]
User ID: 501

Date/Time: 2018-02-01 02:05:52.110 +0000
OS Version: Mac OS X 10.13.3 (17D47)
Report Version: 12
Anonymous UUID: 5E3E49CE-5301-007A-FC54-95B84B2FC0FC

Time Awake Since Boot: 1600 seconds

System Integrity Protection: enabled

Crashed Thread: 0

Exception Type: EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note: EXC_CORPSE_NOTIFY

Termination Reason: DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
Library not loaded: @loader_path/libboost_system-mt.dylib
Referenced from: /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
Reason: image not found

Binary Images:
0x10e2b2000 - 0x10ec25fff +com.vergecurrency.VERGE-Qt (4.0.1 - 4.0.1) <2B77BF2D-DFA9-3195-ADAD-BE31889C17F4> /Applications/VERGE-Qt.app/Contents/MacOS/VERGE-Qt
0x10ecfa000 - 0x10ecfcfff +libboost_system.dylib (0) /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_system.dylib
0x10ed01000 - 0x10ed0fff7 +libboost_filesystem.dylib (0) /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_filesystem.dylib
0x10ed18000 - 0x10ed4cfff +libboost_program_options-mt.dylib (0) <551B73D9-D5BA-3BDB-A497-AE17966D1B1F> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib
0x10ed69000 - 0x10ed76ff7 +libboost_thread-mt.dylib (0) <43A32D2F-3381-32E7-A6A5-47B94F951AD6> /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib
0x10ed86000 - 0x10ed87ffb +libboost_chrono-mt.dylib (0) /Applications/VERGE-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib
0x10ed8f000 - 0x10f29afff +QtWidgets (5.5.1) <416CBC52-D42C-3996-B338-C848863E65B0> /Applications/VERGE-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
0x10f3cf000 - 0x10f853fff +QtGui (5.5.1) <217B896F-895F-3DEC-BF29-01E065492858> /Applications/VERGE-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
0x10f930000 - 0x10fe37fff +QtCore (5.5.1) <201F9A70-4676-3BC5-8B59-82DA94559272> /Applications/VERGE-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
0x10fec6000 - 0x10ffd3ff7 +QtNetwork (5.5.1) /Applications/VERGE-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
0x11000b000 - 0x11006eff7 +QtDBus (5.5.1) /Applications/VERGE-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus
0x110083000 - 0x110089fff +libqrencode.4.dylib (0) <5B7DEE75-603E-351D-B14C-21663CD470BC> /Applications/VERGE-Qt.app/Contents/Frameworks/libqrencode.4.dylib
0x11008d000 - 0x1101bfff7 +libprotobuf.15.dylib (0) <6300475A-5FB2-39C0-AE54-644CFAC18091> /Applications/VERGE-Qt.app/Contents/Frameworks/libprotobuf.15.dylib
0x110271000 - 0x110395ff7 +libdb_cxx-4.8.dylib (0) <893E0F96-1F8A-3073-B1CF-CC60610C3E90> /Applications/VERGE-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib
0x1103cd000 - 0x1103ddff3 +libz.1.dylib (0) /Applications/VERGE-Qt.app/Contents/Frameworks/libz.1.dylib
0x1103e5000 - 0x110412fff +libevent-2.1.6.dylib (0) <891F379E-D5F9-39EB-BECA-2E24F943B7B3> /Applications/VERGE-Qt.app/Contents/Frameworks/libevent-2.1.6.dylib
0x110423000 - 0x11042bff3 +libminiupnpc.16.dylib (0) /Applications/VERGE-Qt.app/Contents/Frameworks/libminiupnpc.16.dylib
0x110431000 - 0x110472fff +libssl.1.0.0.dylib (0) <3C28C2A8-036B-34B3-82BB-5780DB7271B2> /Applications/VERGE-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib
0x11048e000 - 0x1105fec87 +libcrypto.1.0.0.dylib (0) <1C6D06DA-0F88-37BA-80E9-52C4AC7E942C> /Applications/VERGE-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib
0x117d8d000 - 0x117dd798f dyld (519.2.2) <6695F30B-4E88-3C0B-9867-7D738C44A3E6> /usr/lib/dyld
0x7fff29e11000 - 0x7fff29e15ffb com.apple.agl (3.3.1 - AGL-3.3.1) <5A110DE6-3EE7-343B-95FE-9642517D1B64> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
0x7fff2b1f1000 - 0x7fff2c04efff com.apple.AppKit (6.9 - 1561.20.106) /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
0x7fff2c0a0000 - 0x7fff2c0a0fff com.apple.ApplicationServices (48 - 50) <7627DBD6-497B-3AB7-9B63-F0532EDF09B8> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
0x7fff2dbcb000 - 0x7fff2e06bfe7 com.apple.CoreFoundation (6.9 - 1451) <7AFE9C8F-A562-3AFC-8402-117AA02F57E9> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
0x7fff2ed2b000 - 0x7fff2ed2bfff com.apple.CoreServices (822.19 - 822.19) <44456ED2-59E4-34CB-B41B-C6A82B269949> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
0x7fff2fb3b000 - 0x7fff2fb40fff com.apple.DiskArbitration (2.7 - 2.7) <44836CE9-A9ED-3017-972A-7A0A3D6B472B> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
0x7fff2fd01000 - 0x7fff300c6fff com.apple.Foundation (6.9 - 1451) /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
0x7fff303db000 - 0x7fff30476fff com.apple.framework.IOKit (2.0.2 - 1445.40.1) <9CFA07B9-BA6E-31E4-AD4F-C47071A8C522> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
0x7fff37f17000 - 0x7fff37f25ffb com.apple.opengl (16.4.2 - 16.4.2) /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
0x7fff52e50000 - 0x7fff52e83fff libclosured.dylib (519.2.2) <48051216-5647-3643-B979-B77D0FD20011> /usr/lib/closure/libclosured.dylib
0x7fff53362000 - 0x7fff53363ff3 libSystem.B.dylib (1252) <47329E26-DC23-3EBA-9461-37755368327D> /usr/lib/libSystem.B.dylib
0x7fff53596000 - 0x7fff535ecfff libc++.1.dylib (400.9) /usr/lib/libc++.1.dylib
0x7fff535ed000 - 0x7fff53611ff7 libc++abi.dylib (400.7) <217656D5-BC40-37FF-B322-91CB2AAD4F34> /usr/lib/libc++abi.dylib
0x7fff54963000 - 0x7fff54d517e7 libobjc.A.dylib (723) <93A92316-DE1E-378C-8891-99720B50D075> /usr/lib/libobjc.A.dylib
0x7fff553fe000 - 0x7fff55402ff7 libcache.dylib (80) <354F3B7D-404E-3398-9EBF-65CA2CE65211> /usr/lib/system/libcache.dylib
0x7fff55403000 - 0x7fff5540dff3 libcommonCrypto.dylib (60118.30.2) <674286D3-7744-36A3-9AAA-49DFCD97A986> /usr/lib/system/libcommonCrypto.dylib
0x7fff5540e000 - 0x7fff55415fff libcompiler_rt.dylib (62) <4487CFBA-A5D7-3282-9E6B-94CAD7BE507E> /usr/lib/system/libcompiler_rt.dylib
0x7fff55416000 - 0x7fff5541effb libcopyfile.dylib (146.30.2) <2C7C67D7-562B-3FFA-973D-BACF4C10E1EC> /usr/lib/system/libcopyfile.dylib
0x7fff5541f000 - 0x7fff554a4fff libcorecrypto.dylib (562.30.10) <8A53EFE1-AFCA-3676-BEE1-FA5ED9F0E222> /usr/lib/system/libcorecrypto.dylib
0x7fff5552c000 - 0x7fff55565ff7 libdispatch.dylib (913.30.4) <7D0E3183-282B-3FEE-A734-2C0ADC092084> /usr/lib/system/libdispatch.dylib
0x7fff55566000 - 0x7fff55583ff7 libdyld.dylib (519.2.2) /usr/lib/system/libdyld.dylib
0x7fff55584000 - 0x7fff55584ffb libkeymgr.dylib (28) <6D84A96F-C65B-38EC-BDB5-21FD2C97E7B2> /usr/lib/system/libkeymgr.dylib
0x7fff55592000 - 0x7fff55592ff7 liblaunch.dylib (1205.30.29) /usr/lib/system/liblaunch.dylib
0x7fff55593000 - 0x7fff55597ffb libmacho.dylib (900.0.1) <756F2553-07B6-3B42-ACEA-2F0F1A5E8D0F> /usr/lib/system/libmacho.dylib
0x7fff55598000 - 0x7fff5559aff3 libquarantine.dylib (86) <6AC8773F-3817-3D82-99C2-01BABB9C3CBB> /usr/lib/system/libquarantine.dylib
0x7fff5559b000 - 0x7fff5559cff3 libremovefile.dylib (45) <912FA211-DD8C-3C92-8424-21B89F8B10FD> /usr/lib/system/libremovefile.dylib
0x7fff5559d000 - 0x7fff555b4fff libsystem_asl.dylib (356.1.1) <94972913-9DF0-3C78-847C-43E58919E3DA> /usr/lib/system/libsystem_asl.dylib
0x7fff555b5000 - 0x7fff555b5fff libsystem_blocks.dylib (67) /usr/lib/system/libsystem_blocks.dylib
0x7fff555b6000 - 0x7fff5563fff7 libsystem_c.dylib (1244.30.3) /usr/lib/system/libsystem_c.dylib
0x7fff55640000 - 0x7fff55643ffb libsystem_configuration.dylib (963.30.1) <0F8D0B76-4F7D-34EC-AB6C-50F9465809DA> /usr/lib/system/libsystem_configuration.dylib
0x7fff55644000 - 0x7fff55647ffb libsystem_coreservices.dylib (51) <21A488D0-2D07-344E-8631-CC8B2A246F35> /usr/lib/system/libsystem_coreservices.dylib
0x7fff55648000 - 0x7fff55649fff libsystem_darwin.dylib (1244.30.3) <2F750CB1-BC26-3FA3-AE59-553EE30D451B> /usr/lib/system/libsystem_darwin.dylib
0x7fff5564a000 - 0x7fff55650ff7 libsystem_dnssd.dylib (878.30.4) /usr/lib/system/libsystem_dnssd.dylib
0x7fff55651000 - 0x7fff5569aff7 libsystem_info.dylib (517.30.1) <7D79E167-4B5C-3833-81EE-3AF3FB53616D> /usr/lib/system/libsystem_info.dylib
0x7fff5569b000 - 0x7fff556c0ff7 libsystem_kernel.dylib (4570.41.2) <5155A4C3-825B-3178-AC51-0D2D2F2A6618> /usr/lib/system/libsystem_kernel.dylib
0x7fff556c1000 - 0x7fff5570cfcb libsystem_m.dylib (3146) /usr/lib/system/libsystem_m.dylib
0x7fff5570d000 - 0x7fff5572cfff libsystem_malloc.dylib (140.40.1) <36B22C99-D772-3039-9A4C-AA31389965E1> /usr/lib/system/libsystem_malloc.dylib
0x7fff5572d000 - 0x7fff557d1ff3 libsystem_network.dylib (1229.30.11) <40BAD301-8744-3AD8-A688-E7925C587B00> /usr/lib/system/libsystem_network.dylib
0x7fff557d2000 - 0x7fff557dcffb libsystem_networkextension.dylib (767.40.1) /usr/lib/system/libsystem_networkextension.dylib
0x7fff557dd000 - 0x7fff557e6ff3 libsystem_notify.dylib (172) <98EA3D62-7C86-30DE-8261-D020D2F1EFF3> /usr/lib/system/libsystem_notify.dylib
0x7fff557e7000 - 0x7fff557eeff7 libsystem_platform.dylib (161.20.1) /usr/lib/system/libsystem_platform.dylib
0x7fff557ef000 - 0x7fff557fafff libsystem_pthread.dylib (301.30.1) /usr/lib/system/libsystem_pthread.dylib
0x7fff557fb000 - 0x7fff557feff3 libsystem_sandbox.dylib (765.40.2) <922D3D15-AB4C-3F1A-A94F-39214AF1ADB3> /usr/lib/system/libsystem_sandbox.dylib
0x7fff557ff000 - 0x7fff55800ff3 libsystem_secinit.dylib (30) /usr/lib/system/libsystem_secinit.dylib
0x7fff55801000 - 0x7fff55808ff7 libsystem_symptoms.dylib (820.30.7) /usr/lib/system/libsystem_symptoms.dylib
0x7fff55809000 - 0x7fff5581cff7 libsystem_trace.dylib (829.30.14) <69EBF017-D40F-30D7-9B0B-BFC862D761A5> /usr/lib/system/libsystem_trace.dylib
0x7fff5581e000 - 0x7fff55823ff7 libunwind.dylib (35.3) <6D4FCD49-D2A9-3233-95C7-A7635CE265F2> /usr/lib/system/libunwind.dylib
0x7fff55824000 - 0x7fff55850ff7 libxpc.dylib (1205.30.29) /usr/lib/system/libxpc.dylib

Model: MacBookPro12,1, BootROM MBP121.0171.B00, 2 processors, Intel Core i5, 2.9 GHz, 8 GB, SMC 2.28f7
Graphics: Intel Iris Graphics 6100, Intel Iris Graphics 6100, Built-In
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5544
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1867 MHz, 0x80AD, 0x483943434E4E4E424C54424C41522D4E5544
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x133), Broadcom BCM43xx 1.0 (7.77.37.5.1a3)
Bluetooth: Version 6.0.2f2, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0512G, 500.28 GB
USB Device: USB 3.0 Bus
USB Device: Bluetooth USB Host Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 27.1

I know some of the solutions suggested is to go to terminal and type xcode-select --install etc but nothing has solved. I decided to manually install Xcode 9.2 from apple store, with zero results. I downloaded boost 1.66 and boost-bottle bar but I don't know how to use them.

I don't have any sort of background to deal with this kind of problem, I am like the average Joe. Any suggestions or instructions should be very easy and clear to make me understand.

If the problem is that I miss a file, can it be solved by receiving that file from someone who has it?

Thanks

**Comment by Max-Meldrum** [comment]
This was fixed in #575 
Try download the new DMG file: VERGE-Qt-1-30-2018.dmg. It can be found either here on github (releases) and I believe the vergecurrency.com website links to it as well.  Try it and feel free to close the issue if there are no problems with starting it.

**Comment by kevintenda** [comment]
<img width="1280" alt="schermata 2018-02-01 alle 13 57 57" src="https://user-images.githubusercontent.com/36020497/35682731-a468c722-0759-11e8-9884-b5e263730895.png">

I don't know why I got this. I try to drag the wallet into Application, but it doesn't get in

**Comment by Max-Meldrum** [comment]
Not a mac user, but try to remove the previous Verge-Qt that exists in applications?

**Comment by kevintenda** [comment]
Ok. I finally open the wallet and it is sync... Finger cross everything will work. If any serious problem I will report it.

**Comment by justinvforvendetta** [comment]
also please post a crash report if it happens again

**Comment by kevintenda** [comment]
Sorry for the delay, but I've been busy. With the new wallet there is no record of any crash from my short experience. I've noted though that the sync bar located on the bottom, at one point disappears, then re-appear to then disappear.
