### ISSUE TITLE
XVG transferred from binance to yobit, above 1500 confirmations, still no deposit in yobit xvg wallet. 

### ISSUE THREAD

**Issue by HotIce1001** [vergecurrency/VERGE#596]
Hi, 
I transferred some xvg from binance to yobit, there is no deposit in yobit xvg wallet, i tried contacting yobit but didn't get any response yet. 
Here is link-https://verge-blockchain.info/address/DPhxvKDRyHjgx7FRMiNtu92tiyWJeE2YKM
can anyone please check and help ? Thank you.

**Comment by justinvforvendetta** [comment]
yobit is garbage. they never updated when we forked. my only suggestion is to keep writing tickets as I'm sure a lot of people are doing. this is one reason we don't list them on our website

**Comment by HotIce1001** [comment]
Thank you for quick response, already started a support ticket, hope to get back my xvg. 
I am new to blockchain, can u please answer this -
 when xvg is not in my wallet does that mean yobit stole it or it is stuck in block chain because they didn't update it when verge was forked? what do you think are chances of getting it back?

**Comment by justinvforvendetta** [comment]
its easy to update, if they did it on time, it would only have taken them 5-15 minutes, but at this point, they have been on the wrong chain for so long that they would need to update. yes they can get it back easily if they update.
