### ISSUE TITLE
XVG not receiving coins in my wallet

### ISSUE THREAD

**Issue by Lam4ro** [vergecurrency/VERGE#597]
Hallo,

I have tried making some test transactions to my XVG wallet before sending all of my XVG.
I have done 3 test transactions and all 3 have not reached my Wallet.
I have done 2 from Binance and 1 from Cryptopia.
I contacted both Binance and Cryptopia for explanation and Binance said that the transactions where OK and send to the address that whas given. Craptopia like always didn't even respond. 
I have 2 wallet addresses on my wallet, don't know why that is.

Wallet is synchronized.
Dates of transactions are: 25/26/30 - Januari 2018
Version: Windows.
Transaction was not a stealth transaction.
Version: v4.0.1.0-unk-beta.
Transaction-rf: 
323fe06b0523cce89e929abee14ccf99213109f2999b7cb30d83cbaaa9824fbf.   
f17ff6e092d7161afff2e6c33d0a07b48d3e6d85c89beaaad436fa05a6e3c0ed.
f454981b06d914b24bc54ba9f598e732b82f0ce0dfbf2da0bb7c10b1c9958d76.

**Comment by justinvforvendetta** [comment]
can you confirm your wallet is on the same block number as the explorer?

**Comment by Lam4ro** [comment]
Maybe stupid question but how do I check that?

**Comment by justinvforvendetta** [comment]
go to the bottom right and hover the mouse, or go to help, debug console and type getinfo

**Comment by bathangit** [comment]
Dear justinvforvendetta ,

I meet same issue, my wallet is synchronized, I follow your instruction and see my block explorer is 1831753, the block of my transaction id is 1850853
So how do I jump my wallet to above block?

**Comment by highfi5** [comment]
same for me - transferred coins from cryptopia 2 days ago and they never hit my wallet version 4.0.1. HELP!

**Comment by justinvforvendetta** [comment]
close the wallet, download the newest wallet, then delete the blockchain data and open it again

**Comment by bathangit** [comment]
thank you, I am downloading newest blockchain data

**Comment by jrsikors** [comment]
open your Verge client .. go to help -> debug ... on the first screen , please list the details... post screenshot if possible.

dead giveaway:  Version: v4.0.1.0-unk-beta is the **_wrong version_**

if you are on 4.0.1 funky-beta ... and still have problems, come post more information.

**Comment by jrsikors** [comment]
You can download almost the full blockchain from:
https://verge-blockchain.com/down
...if you want to speed up the sync.

**Comment by Lam4ro** [comment]
Can someone help me on how i must delete the blockchain data?

I think if we can put a DUMB PEOPLE GUIDE ON HOW TO UPDATE WALLET, it would help a lot of people.

First step is -close the wallet-.
Second step is -download the newest wallet from the official VERGE website.
Third step is -delete the blockchain data.
Forth step is -Dowload almost the full blockchain from https://verge-blockchain.com/down.

**Comment by jrsikors** [comment]
It's in your 'data directory'... i think default is:
C:\users\<you>\appdata\roaming\verge

dont delete wallet.dat ,, that's your wallet, lose that and you are done!

**Comment by jrsikors** [comment]
also there is a guide out there on the Vergecurrency.com / FAQ... takes you to:
https://verge-blockchain.com/howto

**Comment by Flyer600600** [comment]
I installed the most recent wallet (4.0.1-funky-beta) and blockchain, but my coins have still not yet appeared, and all blocks are installed. what should I do?

**Comment by jrsikors** [comment]
Help -> Debug Window -> Console
Type: 
**_scanforalltxns_**

It might make it look like your verge client is crashing -- but don't quit out -- it will finish.  It might take 15-30 mins.

**Comment by jrsikors** [comment]
if it's a stealth transaction, do this afterwards as well:
**_scanforstealthtxns_**

**Comment by Flyer600600** [comment]
Thanks for the help!

**Comment by justinvforvendetta** [comment]
also, verify your wallet is at the same block height as vergechain.org or verge-blockchain.info

**Comment by highfi5** [comment]
ok - i did have unk-beta and upgraded to funky-beta - now its stuck synchronizing network block 20238 remaining - I feel we are getting close - what next? 

![image](https://user-images.githubusercontent.com/4397777/35771324-f01a86e2-08f8-11e8-869d-e77636768502.png)

**Comment by jrsikors** [comment]
@highfi5  ... go to help -> debug window ... post a screenshot of that please.  

The 'blocks remaining' SHOULD be moving ... just give it time (couple hours maybe)

**Comment by highfi5** [comment]
![image](https://user-images.githubusercontent.com/4397777/35771586-55a1654a-08fd-11e8-8f2c-781b25da2d0f.png)

**Comment by jrsikors** [comment]
You got a good amount of "connections".. is it still stuck at 20,238?  I would try closing verge-qt and re-opening if it's still not moving.

**Comment by highfi5** [comment]
closed and reopen - now just says (out of sync) 2 active connections 
![image](https://user-images.githubusercontent.com/4397777/35772002-5ec151b0-0904-11e8-9ec4-6a4313aecae6.png)

**Comment by jrsikors** [comment]
That's fine -- give it some time, it will start syncing.

**Comment by highfi5** [comment]
YES! perfect AND my last withdraw is now in my wallet - THANK YOU!
