### ISSUE TITLE
Electrum-XVG wallet - unable to send coins

### ISSUE THREAD

**Issue by leonardhoek** [vergecurrency/VERGE#598]
# I cannot send coins from my Electrum-XVG wallet

## Context

I am connected and have >1000 coins, splitted on 2 wallet addresses. When I want to send coins to an other address, with the auto fee set, I receive a message "Invalid fee".
When setting the fee to manually, after clicking on the sent button and pressing yes (I am sure), nothing is happening. I do not get the sign screen or whatever. Tested with fees between 1 and 10. Aslo tested with sending 1090 coins till 90 in various values.

I have already tested on a seperate machine and also with the TOR wallet, but same issue.

## Prerequisites

* [x ] Are you running the latest version? (Electrum-XVG 2.4.1)

## User Story:

* "I'm submitting a ... "
  - [x ] bug report
  - [ ] feature request
  - [x ] support request 
  - [ ] translation request

**Comment by jimrecord** [comment]
Hello, i have resolve this problem identical at me, i have just pass the "transaction fee per kb:" in tools > preferences on 2 and i have sweep my address bugued in Wallet > private keys > sweep you post your private key and you select below the address at send, I hope it will help you.

**Comment by Technophant** [comment]
You're issue sound like the same one addressed in #583.

**Comment by Technophant** [comment]
I had an issue sweeping a paper wallet.  Set fee to 0.1 and it went through.  Does not need to be higher.

**Comment by jrsikors** [comment]
any update on this one ?

**Comment by leonardhoek** [comment]
We could not get it solved,even Sunerok had no idea. Finaly I exported the private key and imported into the Verge-qt wallet
