### ISSUE TITLE
Command "makekeypair" generates different private key.

### ISSUE THREAD

**Issue by ferhan1992** [vergecurrency/VERGE#601]
# Issue Template

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [x] support request 
  - [ ] translation request 

## Expected Behavior

I expected, that using the command "makekeypair" on console would create a private and public key for verge without having the address setup on my current wallet first.

## Current Behavior

The created private key using the command "makekeypair" is not in format of the usual ones we are able to get using the command "dumpprivkey < address >".
But using "validatepubkey" shows the public key as valid and also shows the attached verge address.
I sent some xvg to the address but not i am not able to import the private key to get access to those verges.

## Steps to Reproduce (for bugs)

* Steps :
1. Use command "makekeypair" on verge client console
2. Use command "validatepubkey" to check if the pubkey is valid and to obtain the verge address of this priv/pub pair.
3. Use command "importprivkey" to import the private key generated with "makekeypair" before
4. Get an error message :(

## Your Environment

* Verge Release: 4.0.1.0
* CPU: Intel Xeon E3-1245v3
* GPU: Nvidia GTX 970
* RAM: 16GB DDR3
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [x] I'm using Windows

## Any extra information that might be useful in the debugging process.

Since i already send some xvg to the generated key pair i am not able to access those anymore, due to the problem importing the private key...
Might there be a possibility to convert the private key from "makekeypair" to a "verge" private key?

U may ask me why i didnt used "dumpprivkey".
This command was the first one i used to get my private key of an old account i had.
I copied this private key into a text file.
I reinstalled my computer i wanted to import theprivate key. 
But the imported account showed me a balance of 0 eventhrough the correct address was imported. (checked it twice)
Luckily i had my wallet file so i was able to get back to my xvg's.

This time i wanted to directly generate a new verge address with private and public key instead of using
dumpprivkey.

**Comment by Technophant** [comment]
Try putting the private key into the paper wallet decoder.  It may be base64 while it is looking for wif.

**Comment by ferhan1992** [comment]
Okay thanks! It worked this way. For everyone else having this "problem".
Here is how its solved.

Using "makekeypair" generates a 130 character public key and a 558 character private key.
While the public key is shown properly, the generated private key looks like this (combination of priv + pub key)

308201130201010420**c4bbcb1fbec99d65bf59d85c8cb62ee2db963f0fe106f483d9afa73bd4e39a8a**a081a53081a2020101302c06072a8648ce3d0101022100fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f300604010004010704410479be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798483ada7726a3c4655da4fbfc0e1108a8fd17b448a68554199c47d08ffb10d4b8022100fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141020101a144034200**0478d430274f8c5ec1321338151e9f27f4c676a008bdf8638d07c0b6be9ab35c71a1518063243acd4dfe96b66e3f2ec8013c8e072cd09b3834a19f81f659cc3455**

There u need to take out the first bolded part. Taking this u can paste it into this https://vergecurrency.com/paper-wallet/ and get your Verge formatted private key. (You should download and run the paper wallet locally!)
The second bolded part is your public key.

Thanks to technophant and to this thread -> https://bitcointalk.org/index.php?topic=145080.5;imode
