### ISSUE TITLE
Multiple issue with daemon command line

### ISSUE THREAD

**Issue by Technophant** [vergecurrency/VERGE#602]
## Your Environment

* Verge Release: 4.0.1 fork for stealth
* CPU: AMD A-10
* GPU: Nvidia 1060
* RAM: 12 GB
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [x] I'm using Windows

I would like to start a master thread with all of the issues I've found so far.  There's multiple issue I've brought up in #563.  A working gui wallet needs to be built upon a working command line daemon.  Once the command line starts, passing useful status and error messages it will be easier to allow the gui to use them.  

1. You can set a socks port= in by command line, but how do you bind to a local ip so you can select an adapter to use?  Is there a way to connect to clearnet instead of tor from the command line?

2.  (qt-wallet) The last entry in debug.log that's made, unless there's a network issue is "No OBFS4 found, not using it."  This means that a normal connection is made without using bridges. Then the gui is non-responsive for about 20 minutes with no indication of what is happening. There needs to be more messages made to know the status.  Also, until connections are made I unable to close the wallet without force quitting it. 

3. Running the daemon starts with "which: no obfs4proxy ...."  Should say simply "starting daemon"   "starting tor service" "writing output to tor.log" etc.

4. Attemping to solo mine, I've not been successful.  I've followed the month old instructions at https://www.reddit.com/r/vergecurrency/comments/7l0paf/idiot_ahead_solo_mining_help/ but myself and others haven't been able to.  It must be possible because the pools are able to, but maybe the pool software knows the correct way to connect where ccminer doesn't.  No matter what I do it says it's starting scrypt.

5. The final message that shows in in terminal is "[notice] Opening Socks listener on 127.0.0.1:9089"  and I presume it's running properly.  Tor log has output.  What is going on here?  Needs more status messages, most importantly that the daemon is up and running.  Need to also know when it's connecting and to which servers.

6.  Debug level would be nice.  On a normal run there should just be status messages, and not these minor error messages. 

There's more and I may add some updates to this when I have time to write things up. 

Edit:  Another feature that's been requested is the ability to run the daemon on a remote server and access through the wallet gui.  Would need option -nodaemon and -walletconnect [ipaddress:port]

**Comment by clayrichardson** [comment]
I found adding `-printconsole` directs output to console:
https://github.com/vergecurrency/VERGE/blob/master/doc/dev-notes.md
