### ISSUE TITLE
Stop Daemon

### ISSUE THREAD

**Issue by Fungraphic** [vergecurrency/VERGE#603]
what's command line for stopped daemon?

Start daemon => VERGEd
Stop daemon => ?

**Comment by justinvforvendetta** [comment]
well technically to start, its VERGEd daemon, and to stop, VERGEd stop

**Comment by Fungraphic** [comment]
VERGEd stop = error
I'm trying to connect a cryptonote pool to the daemon.
But I still have the same error.
is it possible to conect this pool on the daemon?
![2018-02-05_033550](https://user-images.githubusercontent.com/26345101/35786267-51e0a5ea-0a26-11e8-8a5d-770c5a4b913b.jpg)
![2018-02-05_033641](https://user-images.githubusercontent.com/26345101/35786271-5a17f8da-0a26-11e8-8189-70dab3f6a061.jpg)

**Comment by justinvforvendetta** [comment]
verge isn't cryptonote
