### ISSUE TITLE
Confirmed XVG Transaction not visible in Verge-Qt 4.0.1 wallet

### ISSUE THREAD

**Issue by louloops** [vergecurrency/VERGE#609]
# Issue Template

## Context

Transaction from exchange to wallet not appearing in Wallet whereas it appears as complete in the blockchain. My Wallet is not showing the last reception of XVGs

## Prerequisites

* [x] Are you running the latest version? Yes 4.0.1 (mac)

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [x] support request 

- Main objective: to withdraw my XVG from Binance to my Verge-QT wallet 4.0.1 (mac version)

- 1st observations: withdrawal is marked as completed on Binance side (with a Txid), and by looking verge.blockchain.info related page, the amount of XVGs seems to be received (see screenshot below).
<img width="1129" alt="screenshot 1" src="https://user-images.githubusercontent.com/35570604/36056747-532b80de-0e07-11e8-8928-e46bc8d421ef.png">

- Issue observed: transaction doesn't appear in my wallet after update. 

## Expected Behavior

The transaction should appear in the wallet as it's appearing in the blockchain

## Current Behavior

The transaction doesn't appear even after update of the wallet (see screenshots 2, 3 and 4)

## Screenshots
<img width="965" alt="screenshot 2" src="https://user-images.githubusercontent.com/35570604/36056748-5350518e-0e07-11e8-8a26-71e22ed0eeef.png">
<img width="967" alt="screenshot 3" src="https://user-images.githubusercontent.com/35570604/36056749-53756dd4-0e07-11e8-9e97-27de6618d725.png">
<img width="1433" alt="screenshot 4" src="https://user-images.githubusercontent.com/35570604/36056883-99486554-0e08-11e8-9dfa-d624c9b1a312.png">

## Possible Solution

Not obligatory, but suggest a fix/reason for the bug or ideas how to implement the addition or change.

## Steps to Reproduce (for bugs)

https://verge-blockchain.info/address/DBnKxHx7SGtGGAUBxohwqSRAEJTi9KtgdK (confirmation that the XVGs where correctly received in the blockchain and related to my address)

* Steps :
1. 
2.
3.
4.

## Your Environment

* Verge Release: 4.0.1
* using WiFi
* OS:
    - [x] I'm using Mac

**Comment by justinvforvendetta** [comment]
sounds like you aren't on the newest wallet. did you confirm your wallet is on the same block height as the explorer?

**Comment by louloops** [comment]
This is the newest wallet (4.0.1) and the block height was up to date when transaction was made

**Comment by louloops** [comment]
I mean the block heigh was updated at 2.14am (see screenshot 4) as the tick was there

**Comment by justinvforvendetta** [comment]
the block number your wallet is on, is the same block number the explorer is on?

**Comment by justinvforvendetta** [comment]
it sounds like you aren't using the latest wallet/current blockchain. when did you download this wallet? try downloading the newest one again.

**Comment by jrsikors** [comment]
toss up a screenshot of the help -> Debug window .. the Information tab

**Comment by louloops** [comment]
I backed up my wallet and redownloaded the 4.0.1. After sync for 4h, the transaction appeared...
Ill wait a bit and check if the transaction remains there after few hours but really don’t understand what was the trick... wallet version was the same and blocks height almost identical (40-50 difference). I’ll update you by eod

**Comment by jrsikors** [comment]
Everything good?

**Comment by louloops** [comment]
Will check today, was abroad and didn't have access to my wallet. Will let you know. Cheers

**Comment by louloops** [comment]
All is good, transaction still in the wallet. Sorry for the inconvenience and thx for your replies/concerns. Cheers
