### ISSUE TITLE
Error loading blkindex.dat? 

### ISSUE THREAD

**Issue by nojeep** [vergecurrency/VERGE#610]
Operating on a Mac High Sierra, I've followed all the steps to a T, after transferring the unzipped files into the verge folder and then going about opening up the VERGE Qt app, it attempts uploading but this error message pops up "Error loading blkindex.dat"

-please say i didn't just waste 3 hours of my life messing w/ this... 

* [+ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [+ ] support request 
  - [ +] translation request 

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [+ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
which unzipped files?

**Comment by jrsikors** [comment]
Where did you download the zipped files from?  I just checked the download on verge-blockchain.com and it doesn't even come with a blkindex.dat.  It contains blk001.dat and some other files/folders... but not the blkindex.dat.

It's possible the file you downloaded was corrupted.  I would delete the **whole** **_datadirectory_** except your wallet.dat unless you already have that backed up.. unzip the files again.. and try to re-open.

If that doesn't work -- try to download from a different mirror if you used verge-blockchain.com

Keep in mind that method is just to try to speed things up.  You can always do the "real way" and let the UI download all the blocks from scratch.   Might take a day but it's not like you need to sit at your computer the whole time and watch it.

**Comment by jrsikors** [comment]
And if those don't work, you might want to keep the possibility open that your hard drive is failing / has bad sectors.

**Comment by jrsikors** [comment]
any update?

**Comment by jrsikors** [comment]
Anyone? Bueller?

**Comment by jrsikors** [comment]
beep beep
