### ISSUE TITLE
Hi i sent 999.80 verge from bittrex to my verge wallet on 02/05/2018. But the coin did not come to my wallet now it is on blockchain. I tried all of troubleshooting method from verge website. then i deleted all verge related application from my computer and again installed newly.then encrypted new wallet and imported privet key and it was successful. But wallet does not show those coin. could you help me to get those coin please. i am using windows core wallet. Below my address and transid Address: DN4QG3aqVNo7oX5sVju4kxeLtmXp133yb9 TxId: f578fdd2f39f1414a9f391f8fae885fc605304db23e4428c71d96e71df75c35e

### ISSUE THREAD

**Issue by vergecalling** [vergecurrency/VERGE#612]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
try doing a reindex

**Comment by vergecalling** [comment]
how

**Comment by jrsikors** [comment]
go to help -> debug window ... take a screenshot of the information tab and post that.  

Most likely you aren't sync'd fully

Your transaction occurred on block 1,857,449 , so your client needs to be sync'd to at least that block.

**Comment by vergecalling** [comment]
![screenshot 2](https://user-images.githubusercontent.com/36392616/36123416-86884c4a-101a-11e8-85db-542651975693.png)

**Comment by jrsikors** [comment]
Try going to (Help –> Debug –> Console) and type scanforalltxns

**Comment by vergecalling** [comment]
i typed nothing happened

**Comment by jrsikors** [comment]
:+1:
