### ISSUE TITLE
runCommand error: system

### ISSUE THREAD

**Issue by wijnandschouten** [vergecurrency/VERGE#614]
Hello,

I am trying to run the latest verged (Verge daemon ) on linux for a small yiimp mining pool, for blake2s verge.

In my debug.log i see messages like:

runCommand error: system(/var/stratum/blocknotify <mypoolname>:5766 561 < blockhashhere> ) returned -1 . 

When i process the command manually everything works ok.

My verge.conf is as follows:

>>
rpcuser=myuser
rpcpassword=mypass
rpcport=5610
rpcthreads=8
rpcallowip=127.0.0.1
maxconnections=256
algo=blake
daemon=1
gen=0

alertnotify=echo %s | mail -s "Verge-blake2s alert!" info@<mymail>
blocknotify=/var/stratum/blocknotify <mypoolname>:5766 561 %s
>>

2 questions:

Verged seems to have support for blake2s, however i cannot find it. Is algo=blake in the configuration and MAN pages to be meant as blake2s?

I Run Verged as root, so i wonder why it comes back with these run command errors?

**Comment by justinvforvendetta** [comment]
if you can do it manually then that means the software must be doing it slightly different than you are.

**Comment by nazarpechka** [comment]
Hi, have you fixed the problem?

**Comment by wijnandschouten** [comment]
[quote]
Hi, have you fixed the problem?
[/quote]

I wish i had ... :(  but no, it is not solved yet.

The first question is not solved. The second is not  a question but a remark, after trying i found out that the VERGd only accepts algo=blake and not algo=blake2s. .... So apparently algo=blake means blake2?

**Comment by nazarpechka** [comment]
So apparently algo=blake means blake2?
Yes it is
My pool is mining now but i dont will i ever find a block
Your pool shows right block reward and difficulty?

**Comment by wijnandschouten** [comment]
Yes it does show the right difficulty, however there are more bug's to look into as my pool does find blocks, but when writing them to the chain gives me a Sign error.

**Comment by goodthebest** [comment]
I chatted with VergeDev on Discord and I was told though in conf **algo=blake** but when mining it has to be **blake2s**. Hope it helps.

**Comment by justinvforvendetta** [comment]
@wijnandschouten im guessing you got this resolved since you pr'd your pool to the main website? feel free to make a new issue if there are any issues with verge.

**Comment by jrsikors** [comment]
Can you post your conf file plz?

**Comment by wijnandschouten** [comment]
This has nothing to do with Verge, but it has to do with Blocknotify / Yiimp.

**Comment by MovLab2** [comment]
rpcuser=yiimprpc
rpcpassword=e9N6hF3IwZgtYAjq4rV58g
rpcport=19090
rpcthreads=8
rpcallowip=127.0.0.1
# onlynet=ipv4
algo=blake
maxconnections=12
daemon=1
gen=0


alertnotify=echo %s | mail -s "Verge alert!" movlab@netscape.net
blocknotify=blocknotify 127.0.0.1:3433 1909 %s

note: I did try domain name and 192 ip as well... so it seems yiimp problem.

**Comment by justinvforvendetta** [comment]
back to the first post, its probably related to you manually changing the rpc port in the .conf?

**Comment by says112** [comment]
I also have such a problem, help me fix it!
![Снимок экрана (190)](https://user-images.githubusercontent.com/22127398/196517909-07f6c619-3c05-4215-b19f-dcd97f74ce1b.png)
![Снимок экрана (191)](https://user-images.githubusercontent.com/22127398/196517956-9fb53f3c-5767-4464-8118-5de7e92c611a.png)

**Comment by nitrocon** [comment]
@says112  you have to sert the correct powalgo on avian.
