### ISSUE TITLE
Lost Funds on wallet 1 day after Fork

### ISSUE THREAD

**Issue by wuzi86** [vergecurrency/VERGE#617]
https://www.reddit.com/r/vergecurrency/comments/7vw0oe/problem_with_vergeqt_wallet_lost_funds/

can someone please help me. is this a known bug after the fork?

**Comment by jrsikors** [comment]
So first we need to get the story straight, because what I'm reading (I know you are German so you don't speak English perfectly, that's fine... just want to make sure we are talking about the same thing) .  

_i have a problem with some disappeared funds. i have downloaded the verge-qt wallet and depostied 0,90xvg and 3,301.256XVG from my binance account on it.  after 4 minuten, i withdrawled 1,10xvg to binance to check the speed.
the first withdrawal of 1,10xvg i send to my binance wallet. in the same minute 3,300.156xvg was send to an unknown address. see picture: https://www.pic-upload.de/view-34800329/t1.jpg.html_

Did you send funds from BINANCE -> Verge QT or did you send from Verge-QT to Binance?

I believe we are talking BINANCE -> Verge QT... in that case...

You didn't seem to make 2 transactions from Binance to your Verge QT wallet.  You only made 1 transaction from Binance to your Verge-QT wallet of 1 XVG... right ?

When you sent your 1XVG from Binance ..
https://verge-blockchain.info/tx/857cba7a7e7c3c1a6216012126ebb73e878588c117e35d2f567e17de1349dbbf

Your 1 XVG was sent to: 
https://verge-blockchain.info/address/DLQA3g6HwP7HMyLWZr5KPnhm8mKCTUg5ex
Perfect right?  It did what you wanted it to do.

Enter problem...
All the other funds, at the same time, went to a different wallet address:
https://verge-blockchain.info/address/DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW
You can see this happened on the SAME transaction listed above:
https://verge-blockchain.info/tx/857cba7a7e7c3c1a6216012126ebb73e878588c117e35d2f567e17de1349dbbf

The only logical explanation I can think of is that Binance owns the wallet and sent the 'remainder' of funds from your wallet to this wallet:
https://verge-blockchain.info/address/DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW

So I would take it up with Binance support.

**Comment by jrsikors** [comment]
Also --  I saw on your reddit that you had it happen again on 

> it happend again.
> 
> https://verge-blockchain.info/tx/57e802f7870d4da5fadd2b6d70073ceb8f25609ec764f3a7282314c1b2c3b4c7
> 
> i tried to send 0.02xvg to my binance wallet. and again there is a second transaktion to an unknown wallet. WTF????
> 
> whats going on here?

this address got the .78 XVG on February 7th @ 17:37:
https://verge-blockchain.info/address/DDa7CWYh3Xg2sT68ynBDwMotiAEftSt1er

On February 9th @ 13:41, that address sent all .78 XVG it had via tx:
https://verge-blockchain.info/tx/82d05cf0dd6928cdbe1167353fc35b5ef982f5ffa6315505e0e46cf95723670b

and .001 xvg of that transaction ended back with the mystery address:
DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW

**Comment by wuzi86** [comment]
You wanted to send 1 XVG to your binance account, this is your binance address:
https://verge-blockchain.info/address/DLQA3g6HwP7HMyLWZr5KPnhm8mKCTUg5ex
Your 1 XVG made it to Binance address
**_Thats right. i send 1,10XVG. 0.10XVG were the fee_**

Problem:
3300.156 XVG was sent to
https://verge-blockchain.info/address/DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW
**_Thats right. it was send the same second as my that for my binance wallet. i dont type that amount in the withdrawal fee or something...i just wanted zu send 1XVG zu Binance to check the speed_**


Your .02 XVG made it to your Binance wallet:
https://verge-blockchain.info/address/DLQA3g6HwP7HMyLWZr5KPnhm8mKCTUg5ex
via TX:
https://verge-blockchain.info/tx/57e802f7870d4da5fadd2b6d70073ceb8f25609ec764f3a7282314c1b2c3b4c7
**_Thats right_**

this address got the .78 XVG on February 7th @ 17:37:
https://verge-blockchain.info/address/DDa7CWYh3Xg2sT68ynBDwMotiAEftSt1er
**_Thats right, but this time the 0,78XVG got back to my wallet. its not lost. i first checked the blockchain explorer, not my wallet on feb. 9th_**

On February 9th @ 13:41, almost 2 days later, that address sent all .78 XVG it had via tx:
https://verge-blockchain.info/tx/82d05cf0dd6928cdbe1167353fc35b5ef982f5ffa6315505e0e46cf95723670b
**_see above_**

and .001 xvg of that transaction ended back with the same mystery address from my previous post:
DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW
https://verge-blockchain.info/address/DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW
**_thats right. i checked if the address DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW were a normal adress. all went well. i saw the right balance on my wallet_**


so what went wrong in the first 1XVG transaction on January 21st at 21:09? 
i downloaded the wallet at http://vergecurrency.com/#wallets

**Comment by wuzi86** [comment]
could it be a change address failure? https://bitzuma.com/posts/five-ways-to-lose-money-with-bitcoin-change-addresses/

**Comment by jrsikors** [comment]
The change address is definitely what it feels like.  I moreso put that 'story' together so hopefully someone smarter than me can maybe figure out what happened.

But I've made partial transactions with verge-qt wallet and have never had the excess funds moved to a different address.  A new address gets created in my wallet.dat file, but no funds ever end up on the new address.

The hardfork occurred on:
6:48 PM - 23 Jan 2018

So..
Your first transaction that went weird occurred **_before_** the hard fork.  (January 21st)
Your second transaction that went weird occurred **_after_** the hard fork. (February 9th)

So it's hard to blame it on the hard fork here.  Maybe you didn't update the latest QT wallet on the 20th when it was released and the older wallet had some issues with 'change address' ?

**Comment by jrsikors** [comment]
And I hate to be a downer -- but the XVG funds are most likely gone.  It always comes down to 2 simple basic facts:
-There are XVG coins at https://verge-blockchain.info/address/DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW
-You do not have the private key for DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW or have it in your wallet.

That being said, there are 2 possibilities:
  1)  DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW is an address that no one has a private key for, meaning they will be stuck there for eternity.  Perhaps it was a bug in the QT wallet, perhaps it was something you did without knowing. 
  2)  Some random person owns/has private key for DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW, stumbles on the coins they didn't ask for, does some research, and sends them back to you.

That being said -- at this point, all you can hope for is to know if anyone has any insight on WHY it happened, so other people don't make the mistake, or the QT Devs can fix a bug.

Your situation doesn't seem possible to duplicate, which makes it even harder to troubleshoot :(

If I were in your situation, I wouldn't trust my wallet.dat at this point -- and I would create an entirely new wallet.dat, and send all my funds to the new wallet.dat... and get rid of your old wallet.dat in case it's corrupt and unable to generate new addresses when you make transactions.

**Comment by justinvforvendetta** [comment]
did you try seeing if DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW is an address in your electrum wallet?

**Comment by wuzi86** [comment]
no i did not see DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW im my electrum wallet. i did not know the private key of this address to import it. 

heres the transaction "change addresse" failure:

https://verge-blockchain.info/api/getrawtransaction?txid=857cba7a7e7c3c1a6216012126ebb73e878588c117e35d2f567e17de1349dbbf&decrypt=1

**Comment by jrsikors** [comment]
just for S&G -- go to verge qt wallet ... do help -> debug window -> console

unlock your wallet using:
walletpassphrase "YOUR PASS PHRASE HERE" 300

then do a:
dumpprivkey DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW

It's a long shot... but maybe that address is stuck in your wallet and you get lucky and get the private key for it.

**Comment by jrsikors** [comment]
Never mind -- I see in another reddit post you made that someone already suggested you try that

https://www.reddit.com/r/vergecurrency/comments/7x8u2c/still_problem_with_my_qtwallet_maybe_bugged_no/

**Comment by wuzi86** [comment]
I little help (or an explanation what really happend) from a dev, would be very nice. 
the 3300XVG where an invest and trust in their project....

**Comment by wuzi86** [comment]
So, no help from devs??

**Comment by justinvforvendetta** [comment]
really this issue makes no sense. what wallet did you use when this happened?

**Comment by justinvforvendetta** [comment]
seeing as how the 3300 coins are still sitting in that address, one has to assume it is a change address and you do indeed own it in your core wallet. you should not be able to see it in your receiving address list, but you can dump the private key to it.

**Comment by jrsikors** [comment]
If I had to take a guess ... I would say that you made a transfer, your coins went to the Change Address in your wallet ... then something happened and you restored an older copy of your wallet, which didn't contain the Change Address.

If there was a problem with the QT Client not handling Change Addresses ... @justinvforvendetta probably would have heard about it, and so many people would have lost coins, that he might have had to consider a potentially coin-destroying fork.

**Comment by jrsikors** [comment]
Do you have any backup copies of your wallet.dat file in between these dates:
January 21st at 21:09
February 9th @ 13:41

**Comment by jrsikors** [comment]
go to the debug console and run a:
**_listaddressgroupings_**

I see you posted this on the reddit thread a few days ago:

> 12:13:41 ￼ validateaddress DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW
> 12:13:41 ￼ { "isvalid" : true, "address" : "DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW", "ismine" : false, "account" : "unkown" }

**Comment by wuzi86** [comment]
i have done this with the backup wallets.

**Comment by wuzi86** [comment]
@justinvforvendetta please can you send me older versions of the verge-qt wallet?

**Comment by justinvforvendetta** [comment]
an older version won't solve this. was he right in saying you restored your wallet.dat after you made that transaction? if so, he Is also right about you restoring from a wallet dat that didn't have that change address in it

**Comment by wuzi86** [comment]
now a new problem:
i have reset all. i deleted all verge files. downloaded the newest version. imported the 2 privat key i own.
now the wallet is missing 2 transactions:
https://www.pic-upload.de/view-34874311/19.02.2018.jpg.html

here a pic from 14.02.2018. there i had 6 transactions, and still some verge in my wallet
https://www.pic-upload.de/view-34842053/14.02.0181.jpg.html

now it semms that i dont have any xvg. but i did not make any transactions since 07.02.2018

**Comment by jrsikors** [comment]
It wouldn't be weird for a new wallet with only 2 addresses to have 4 transactions instead of 6.  Your old wallet probably had more addresses that had transactions on them.. and you didn't import all of them.

**Comment by jrsikors** [comment]
You couldn't import this address:
https://verge-blockchain.info/address/DCYjjXsGC4PNeccc2jS5YAs1JppUmnSEoW

which probably had the +2 transactions you are now missing

**Comment by jrsikors** [comment]
Open your old wallet up, go to debug console, type this:
**_listaddressgroupings_**

It will show you the addresses that have funds in them

**Comment by jrsikors** [comment]
Before you create a new wallet ... you always need to go to debug console and do a:
**_listaddressgroupings_**
You also need to confirm on the verge blockchain which addresses ACTUALLY have the funds... quadruple check.  

Your wallet might have addresses with funds that you don't know about.  You need to do a "listaddressgroupings"  and confirm on the verge-blockchain.info.

Once you identify all the addresses that have funds, THOSE are the private keys you want.

You seem to be importing addresses that don't have any funds, and leaving your other addresses with the funds in older wallets.

**Comment by jrsikors** [comment]
You say there are "missing 0.5789xvg" ... what address has the 0.5789xvg on it?  You should be able to find the address in your older wallet by doing a "listaddressgroupings" and/or confirm on verge-blockchain.info.

**Comment by jrsikors** [comment]
Someone correct me if I'm off in this example:
Example -- you have this:
VergeWallet_A - 3000 coins
VergeWallet_B - 0 coins
VergeWalllet_Change - 0 coins

2500 XVG transaction made from A to B

New setup:
VergeWallet_A = 0 coins
VergeWallet_B = 2500 XVG
**VergeWallet_Change** = 500 coins


If you create a new wallet and only import A and B, your new wallet looks like this:
VergeWallet_A = 0 coins
VergeWallet_B = 2500 coins
So you lost 500 coins by not bringing over VergeWallet_Change

If you maintain the same wallet, you will be able to do a 'dumpprivkey' on A,B, and Change. 

Then if you create a new wallet, you can import A, B, and/or Change... so your new wallet will have:
VergeWallet_A = 0 coins
VergeWallet_B = 2500 XVG
VergeWallet_C = 500 coins

and the process repeats every time you make a transaction.  

This is why you always need to make a backup of your wallet.dat file every time you make a transaction .. and always make sure you know exactly every address with all your coins.
