### ISSUE TITLE
For few weeks already have been trying to update my old wallet to  VERGE-Qt-1-30-2018.dmg on Mac highSierra. After downloading the attachment to my computer and clicking on it, it opens, but shuts immediately. Does anyone else have the same issue and how can it be fixed? Cannot use the old wallet anymore. 

### ISSUE THREAD

**Issue by romik1970** [vergecurrency/VERGE#618]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by XVGMonk** [comment]
1- Do you have a back up?
2- Are you dragging the file VERGE-Qt-1-30-2018.dmg from download to desktop before opening?

**Comment by romik1970** [comment]
Thank you for your response.

 I can’t even get to the second point of your list. I did back up of my
wallet. The file downloads to my MacBook Pro without any issues. As soon as
I click on the download, the file tries to unzip and within couple of
seconds crushes. I can’t reopen that download anymore. It just doesn’t
respond. I downloaded again numerous times and the same issues.
 Do I have to completely delete the old 3.0 version?

Thanks for your time.

**Comment by XVGMonk** [comment]
okay. So you do have the file VERGE-Qt-1-30-2018.dmg in your download folder correct?

**Comment by jrsikors** [comment]
I'm not a "Mac person" ... but I find it weird that you can't click to **drag** it.  You can't figure out a way to drag a file ?  Sounds like a problem with the Mac moreso than verge wallet?

**Comment by jrsikors** [comment]
Also -- I would check Anti Virus on your computer.  Sometimes AntiVirus programs try to quarantine these QT Wallets.  They don't label them as Viruses, they classify them as 'potentials' and to be safe, they quarantine it.  Temporarily disabling AntiVirus is something you should try.

**Comment by romik1970** [comment]
Jeff.

 I don’t get it myself. The iOS is up to date using highSierra. If I was
able to download the 3.0 wreath, which was really hard for me as a guy that
has no clue about computers, this one should be a breeze. I will turn the
antivirus off to see if that helps.
 Thank you for your kindness to take your time and help me with this issue.

 Roman.

**Comment by jrsikors** [comment]
any update?

**Comment by romik1970** [comment]
Hi Jeff. No, haven’t done anything yet. I am studying for my upcoming FAA
exams and putting hold on crypto and Verge wallet for a moment. Will let
you know. It’s very kind of you for checking on my wallet update status.
Thank you Sir.

**Comment by justinvforvendetta** [comment]
@romik1970 if it doesn't work by dragging into applications, please feel free to open a new issue.
