### ISSUE TITLE
I can not synchronize a blockchain after reboot.

### ISSUE THREAD

**Issue by Sergsvar** [vergecurrency/VERGE#620]
Yesterday I started the daemon on ubuntu, the synchronization started, everything was fine, ~ 1500000 blocks were synchronized, but today after the server reboot, synchronization does not work.
### debug.log:
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/home/myuser/.VERGE/database ErrorFile=/home/myuser/.VERGE/db.log
Bound to 127.0.0.1:21102
TOR thread started.
AddLocal(usvy5gyehddzcbh3.onion:21102,4)
Loading block index...
Opening LevelDB in /home/myuser/.VERGE/txleveldb
No OBFS4 found, not using it.
Transaction index version is 70509
Opened LevelDB successfully

Then I tried to download the chain of blocks from here https://verge-blockchain.com/ but this did not help, the same problem remained. If I start doing synchronization from scratch then everything works. How can I start a daemon with a downloaded chain of blocks?

**Comment by justinvforvendetta** [comment]
the debug info you posted here looks fine. how long are you letting it try to sync?
