### ISSUE TITLE
VERGE Wallet does NOT accept my Passphrase

### ISSUE THREAD

**Issue by motoToxin** [vergecurrency/VERGE#623]
Latest Verge Wallet for MAC does NOT accept my passphrase :( 

I cannot change it and I cannot send funds out .... PLEASE HELP

It was working all this time and without reason, it has decided to NOT work - I have reinstalled the Wallet to the latest version and still NO luck - My funds are showing up in the Wallet BUT I can't do anything with them.

I am running the latest MAC OS High Sierra 10.13.3.

Really panicking - If anyone can help would be hugely appreciated ....

**Comment by justinvforvendetta** [comment]
have you tried from the debug console?

**Comment by motoToxin** [comment]
So sorry for my ignorance but how do I access debug console and what do I do when I’m there ? 
Gosh, I feel so stupid !!!

**Comment by justinvforvendetta** [comment]
in help, then debug, then console and try
walletpassphrase 'passwordhere' 600

**Comment by motoToxin** [comment]
Thank you so much for your time. Let's figure this out and 1 ETH will be heading your way ;)

I tried entering my wallet Password and it comes back with: **Error: The wallet passphrase entered was incorrect. (code -14)**

I tried entering the wallet PassPhrase and it comes back with: **Method not found (code -32601)**

I have got these symbols at the end of my passphrase: !!@

Could that be causing the problem ?

**Comment by motoToxin** [comment]
I just want to send my XVG out to an Exchange :(

**Comment by motoToxin** [comment]
**1 ETH** given to anyone who helps me Send my XVG out of my Verge-QT v4.0.1.0-9344a75-funky-beta Wallet !!!

**Comment by jrsikors** [comment]
**_walletpassphrase "your pass phrase here" 300_**  

... with double quotes i think?  Method not found seems like you typed it wrong

**Comment by jrsikors** [comment]
and are you copy/pasting your wallet pass phrase?  Or are you typing it out?  I would recommend typing it on a notepad (dunno what equivalent of Mac is) , and then copy/paste , to make sure you are doing it right

But either way -- doing the:
**_walletpassphrase "your pass phrase here" 300_**

Will take care of it, as you will be able to see it in plain text and make sure you are typing it in right, or copy/pasting right (make sure there's no extra spaces at the end / make sure your keyboard isn't doing anything funky while typing it in)

**Comment by justinvforvendetta** [comment]
@mototoxin did you get this solved?

**Comment by motoToxin** [comment]
NO :( 
Still can't figure it out !!! Tried everything suggested to no avail :(((

**Comment by jrsikors** [comment]
Did you try anything I suggested a few comments ago?  What was the result?

You could also try installing the older version of the QT Wallets.   They wont sync to the blockchain, but your only goal right now is to get the wallet unlocked and dumpprivkey , and you can do this on a QT wallet that is older / not synced.

**Comment by jrsikors** [comment]
You shouldn't be seeing this error:
> I tried entering the wallet PassPhrase and it comes back with: Method not found (code -32601)

Please do what I suggested earlier and provide us with the results.  If you get "Method not found" , you aren't putting in the command properly.

**Comment by motoToxin** [comment]
All good mate - I was storing the pass phrase on word so I just could ied it into txt editor and then copied it again from txt editor into the passphrase and voila :))))
Thanks so much for ur time !!!!

**Comment by justinvforvendetta** [comment]
good to hear!
