### ISSUE TITLE
Verge wallet.dat corrupt, crashes on open - can I dump the keys?

### ISSUE THREAD

**Issue by DavidVeksler** [vergecurrency/VERGE#624]
I have a Verge wallet with half a million XVG. Somehow, it became corrupt and is now crashing on open. I can dump it with pywallet, so I know it's not too badly damaged, but pywallet does not have the correct derivation paths.

-salvagewallet modifies the file, but it still crashes on open.

Is there any tool to extract my private keys from the wallet?

**Comment by DavidVeksler** [comment]
> ******* exception encountered *******
> 0   VERGE-Qt                            0x0000000106193468 _ZN5boost4asio6detail16service_registry6createINS0_22deadline_timer_serviceINS_10posix_time5ptimeENS0_11time_traitsIS6_EEEEEEPNS0_10io_service7serviceERSA_ + 1693512
> 1   VERGE-Qt                            0x0000000105fa9be8 _ZN5boost9date_time6c_time6gmtimeEPKlP2tm + 46488
> 2   VERGE-Qt                            0x0000000105f0c32f _ZN17QtMetaTypePrivate23QMetaTypeFunctionHelperI16FreedesktopImageLb1EE9ConstructEPvPKv + 52463
> 3   VERGE-Qt                            0x000000010602c691 _ZN5boost4asio6detail16service_registry6createINS0_22deadline_timer_serviceINS_10posix_time5ptimeENS0_11time_traitsIS6_EEEEEEPNS0_10io_service7serviceERSA_ + 223601
> 4   VERGE-Qt                            0x000000010602e07b _ZN5boost4asio6detail16service_registry6createINS0_22deadline_timer_serviceINS_10posix_time5ptimeENS0_11time_traitsIS6_EEEEEEPNS0_10io_service7serviceERSA_ + 230235
> 5   VERGE-Qt                            0x000000010602df36 _ZN5boost4asio6detail16service_registry6createINS0_22deadline_timer_serviceINS_10posix_time5ptimeENS0_11time_traitsIS6_EEEEEEPNS0_10io_service7serviceERSA_ + 229910
> 6   VERGE-Qt                            0x000000010602dd0e _ZN5boost4asio6detail16service_registry6createINS0_22deadline_timer_serviceINS_10posix_time5ptimeENS0_11time_traitsIS6_EEEEEEPNS0_10io_service7serviceERSA_ + 229358
> 7   VERGE-Qt                            0x000000010602eb6d _ZN5boost4asio6detail16service_registry6createINS0_22deadline_timer_serviceINS_10posix_time5ptimeENS0_11time_traitsIS6_EEEEEEPNS0_10io_service7serviceERSA_ + 233037
> 8   VERGE-Qt                            0x000000010602e3f5 _ZN5boost4asio6detail16service_registry6createINS0_22deadline_timer_serviceINS_10posix_time5ptimeENS0_11time_traitsIS6_EEEEEEPNS0_10io_service7serviceERSA_ + 231125
> 9   VERGE-Qt                            0x00000001060f7a91 _ZN5boost4asio6detail16service_registry6createINS0_22deadline_timer_serviceINS_10posix_time5ptimeENS0_11time_traitsIS6_EEEEEEPNS0_10io_service7serviceERSA_ + 1056113
> 10  VERGE-Qt                            0x00000001060fb489 _ZN5boost4asio6detail16service_registry6createINS0_22deadline_timer_serviceINS_10posix_time5ptimeENS0_11time_traitsIS6_EEEEEEPNS0_10io_service7serviceERSA_ + 1070953
> 11  VERGE-Qt                            0x0000000105f8fcec _ZN17QtMetaTypePrivate23QMetaTypeFunctionHelperIP14SendCoinsEntryLb1EE9ConstructEPvPKv + 110924
> 12  VERGE-Qt                            0x0000000105ec2e61 VERGE-Qt + 11873
> 13  libdyld.dylib                       0x00007fff78800115 start + 1
> 14  ???                                 0x0000000000000002 0x0 + 2
>

**Comment by DavidVeksler** [comment]
Here's the crash when I run ./VERGE-Qt -salvagewallet -debug -salvagewallet:

```
Feb 19 16:35:21.051 [notice] Tor 0.3.2.8-rc-dev running on Darwin with Libevent 2.1.8-stable, OpenSSL 1.0.2n, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Feb 19 16:35:21.051 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Feb 19 16:35:21.051 [notice] Configuration file "/Users/davidv/Library/Application Support/VERGE/tor/torrc" not present, using reasonable defaults.
Feb 19 16:35:21.054 [notice] Scheduler type KISTLite has been enabled.
Feb 19 16:35:21.055 [notice] Opening Socks listener on 127.0.0.1:9089
Assertion failed: (!pthread_mutex_destroy(&m)), function ~recursive_mutex, file /usr/local/opt/boost@1.60/include/boost/thread/pthread/recursive_mutex.hpp, line 104.
Abort trap: 6

```

**Comment by justinvforvendetta** [comment]
did you compile this wallet yourself? if so, what version of bdb did you use?
