### ISSUE TITLE
VERGEd crashing when doing getinfo

### ISSUE THREAD

**Issue by tradesatoshi** [vergecurrency/VERGE#626]
# Issue Template

## Context

VERGEd crashing after doing getinfo on ubuntu  1.6   
all other commands works fine, getblockhash, help, etc.

./VERGEd getinfo

============================================================ T= 1519193738
Tor 0.3.2.8-rc-dev died: Caught signal 11
./VERGEd(+0x3f74a7)[0x564da4d5d4a7]
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x4)[0x7f78a3511d44]
/lib/x86_64-linux-gnu/libpthread.so.0(pthread_mutex_lock+0x4)[0x7f78a3511d44]
./VERGEd(+0x78715)[0x564da49de715]
./VERGEd(+0x28b7c6)[0x564da4bf17c6]
./VERGEd(+0x2844ab)[0x564da4bea4ab]
./VERGEd(+0x2ad9f1)[0x564da4c139f1]
./VERGEd(+0x29363c)[0x564da4bf963c]
./VERGEd(+0x270dd9)[0x564da4bd6dd9]
./VERGEd(+0x98f1e)[0x564da49fef1e]
./VERGEd(+0x9cd39)[0x564da4a02d39]
/usr/lib/x86_64-linux-gnu/libboost_thread.so.1.58.0(+0x115d5)[0x7f78a4c355d5]
/lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba)[0x7f78a350f6ba]
/lib/x86_64-linux-gnu/libc.so.6(clone+0x6d)[0x7f78a324541d]
error: no response from server

## Prerequisites

* [ x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Your Environment

* Verge Release:

    - [ ] I'm using Mac
    - [x ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
can you try using boost 1.62?

(also im assuming you meant ubuntu 16, not 1.6)
