### ISSUE TITLE
Withdrew XVG from Binance before Verge wallet finished syncing rhe blockchain. I ran out of hardrive space so installed Electrum, now they are stuck on the blockchain. How do I get them to my wallet? 

### ISSUE THREAD

**Issue by rickthevegan** [vergecurrency/VERGE#628]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release: Electrum Win
* CPU:
* GPU:
* RAM:
* OS: Win 8.1
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by jrsikors** [comment]
sync'd or not .. open up QT wallet and get your private key for the address.. then go to electrum and import private key.

Go to help -> debug console in QT wallet ...  dumpprivkey "YOURADDRESS"  

you might need to unlock wallet first with
walletpassphrase "YOUR PASSPHRASE HERE" 300

**Comment by rickthevegan** [comment]
Hey thanks for response.  I did that, successfully imported public/private keys into Electrum using the same steps below.  I can see the transfer was successful via the Txid.  My Electrum is connected no problems there.


________________________________

**Comment by jrsikors** [comment]
Are you good to go?  I couldn't tell by your message whether or not that was a "I already did all that and am still having problems" or "I'm good to go now!" :smile:

**Comment by rickthevegan** [comment]
sorry, I meant "yes" I already dumped my key and imported it into Electrum.  I can see my public and private key on Electrum


________________________________

**Comment by justinvforvendetta** [comment]
excellent!

**Comment by rickthevegan** [comment]
No!!! wait lol.  They arent showing in my Electrum, 0.00 balance


________________________________

**Comment by jrsikors** [comment]
So go to verge-blockchain.info.  Search for the address that has the coins.

Are you 100000% sure that's the address you imported to Electrum?  There is no grey area in this.

Either the wallet address you imported has coins , and verge-blockchain.info says it has the coins .. or it doesnt :smile:

**Comment by jrsikors** [comment]
If you posted the wallet address in question, and/or the TX .. we could probably be a little more specific in the help.

**Comment by rickthevegan** [comment]
I withdrew my XVG from Binance on 1/13/2018 Tx ID 71b6b8b6c9a1a0350477ff7566bc2a8117d5985be3ad4a7ca3aacddedc42ba5f


My Public address is DEjYc7C4VB3xsFRbrcuN55cpXVePcSzQbR


________________________________

**Comment by jrsikors** [comment]
The address DEjYc7C4VB3xsFRbrcuN55cpXVePcSzQbR doesn't exist on the blockchain... nor is it part of that TX.  I would check with Binance.

**Comment by jrsikors** [comment]
These are the addresses that received funds from that TX:

Address | Amount (XVG)
-- | --
D7MSbMjjvBvqo322JnppMS7qfsWeP17q48 | 69613.40190000
DGHCDA1nQzziSG64KB86VBScFjFcWXxFTm | 908.99000000
D6gPjRiKEyZufo6wDbWvYrJji2JNUxRjJW | 368.53100000
D8BtVMCiN84NqZaZNHuUhjLzvwYk3cJRXD | 99.90000000
DF7EACxBtZkxhoGzfYefoQhit3o45t2D9J | 214699.29836200
DFC66zkZSszWNVsTzGTpnZUREjjXtwTDRZ | 21.92800000
D8by7NbUS5j6QX2H6Zms4nqBYwTqta3xhz | 3190.53056500
DTCw5vp2mdapeDS9egZnFyhCajCj1ACEyF | 326.90000000
D9aH69CnDfeo6sCnHbjHxAqfNrtVgD6UM7 | 527.00000000
DJZPjUEHRxV2jycupwBgzJuKcy6493N7dL | 3125.90000000
D75W58K72TZq4iSYXo7vhi5iHHxvyMbNzi | 174635.60076000
DSwToP8RGJ91EXTpJwTACDGAz6PtEGoV8B | 668.12300000
D9aDZTQ9nPrvnHUUYsfgaPKyc2QsshhjQh | 179.90000000
DKnripz1DD2CdkEKb8i5dzGMygv6vGFQjV | 785.90000000
DEQZsCKNVMNwkFtWif9JnVGKvUGkQURBNv | 1057.84100000
DC2T5yXPHHuSPUfDMcehc1QGVasQTQ2oE6 | 98.30100000
DNy4Djwk2hrgeLVdPfhSSEPgdrmixjAGgL | 3626.27000000
DFKQkpq8CQtofPBkhacr8jgw8DZ5fVWvff | 0.90000000
DN3rw27S2kgSUF5q5MUgaevJXJnnjnKtNm | 1001.89700000
DDyv4dgWLUckMgWLQiLv32YzTZJAqUPEKK | 77.90000000

**Comment by jrsikors** [comment]
so which address of those is yours?  you need the private key for THAT address and import that one into your electrum wallet.

**Comment by rickthevegan** [comment]
It's this one that's how many tokens I sent
DNy4Djwk2hrgeLVdPfhSSEPgdrmixjAGgL      3626.27000000


Why is Electrum showing a different address?


I only have one Private key which is what I imported into Electrum


________________________________

**Comment by jrsikors** [comment]
If you sent it to DNy4Djwk2hrgeLVdPfhSSEPgdrmixjAGgL .. it's because that's the address that was in your QT wallet right?  So go back to your QT wallet and dumpprivkey for DNy4Djwk2hrgeLVdPfhSSEPgdrmixjAGgL

If DNy4Djwk2hrgeLVdPfhSSEPgdrmixjAGgL isn't in your QT wallet ... then you must have goofed somewhere and lost the wallet.dat that has DNy4Djwk2hrgeLVdPfhSSEPgdrmixjAGgL ?

**Comment by jrsikors** [comment]
Unfortunately it's pretty simple and straightforward... either you can find the private key for DNy4Djwk2hrgeLVdPfhSSEPgdrmixjAGgL  .. or you can't and they are stuck forever :frowning_face: .  Check older copies of your wallet.dat if you have any.

**Comment by rickthevegan** [comment]
I have the wallet.dat file.  what do I do now?  what do I open it with?


________________________________

**Comment by jrsikors** [comment]
Verge-QT client.  You might need to download it again, unzip it, run it, close it, copy the wallet.dat over to the datadirectory (C:\users\YOU\appdata\roaming\verge\)  and replace the wallet.dat that it created.

like I said in my initial post:

sync'd or not .. open up QT wallet and get your private key for the address.. then go to electrum and import private key.

Go to help -> debug console in QT wallet ... dumpprivkey "YOURADDRESS"

you might need to unlock wallet first with
walletpassphrase "YOUR PASSPHRASE HERE" 300

**Comment by rickthevegan** [comment]
ok I will try do that.  I think what happened is I didnt dump it correctly the first time I really dont remember.  Thank you for your time and help, I will follow up


________________________________

**Comment by jrsikors** [comment]
NP good luck !

**Comment by rickthevegan** [comment]
ok so I re-installed it, replaced wallet.dat with my old wallet.dat, re-opened it, typed dumprivkey DNy4Djwk2hrgeLVdPfhSSEPgdrmixjAGgL and it didn't display the priv key.  Tried it a second time and it popped up an error and closed out



________________________________

**Comment by jrsikors** [comment]
did you unlock wallet first?  What was the error message?

go to help -> Debug -> console ... type:
**_listaddressgroupings_**

is DNy4Djwk2hrgeLVdPfhSSEPgdrmixjAGgL  listed?  If it's not, then you probably can't dumpprivkey on it, since you don't "own" the address

If wallet is locked, type:
**_walletpassphrase "YOUR PASS PHRASE HERE INSIDE QUOTES" 300_**

then type:
**_dumpprivkey DNy4Djwk2hrgeLVdPfhSSEPgdrmixjAGgL_**

**Comment by rickthevegan** [comment]
Yea it's not listed.  I don't know what I did.  Obviously I made a major goof somewhere! I give up, gonna chalk this up to my first and, hopefully, only newb mistake.  Thanks again for your time.  At least I can get some more XVG while it is on sale.


________________________________
