### ISSUE TITLE
0 active connection(s) to VERGE network

### ISSUE THREAD

**Issue by adarz0625** [vergecurrency/VERGE#629]
Hey everyone
I have had the wallet for quite some time.
It was synced properly.
Send some more XVG to the wallet and its not syncing "Says out of sync" and 0 active connections.
I left it open for like 1-2 hours but stays the same. I tried downloading the new block and restarted everything but still same issue

**Comment by justinvforvendetta** [comment]
the new wallet? what version

**Comment by adarz0625** [comment]
I don't know. Before the fork I remember changing it. I think 4.0 it says on the bottom right. I left the wallet open the whole night and nothing changed. I am trying to download the new wallet from verge website and launching it that way.
Any other suggestions?

**Comment by adarz0625** [comment]
I downloaded the new version and its working and synced. Does that make sense? Because of the new version...?

**Comment by jrsikors** [comment]
Go to help -> debug window -- post a screenshot ideally or copy/paste or type the version.

But yeah -- ANY version of QT Wallet other than:
https://github.com/vergecurrency/VERGE/releases/tag/4.0stealth
aka "Funky beta" version in help -> debug console

will not sync... Verge was hardforked and older versions will not sync past the fork

**Comment by givu** [comment]
can someone help, please.
my verge qt 4.0 wallet is not synced and no active connection
downloaded the latest blockchain and replaced the old one, replaced the wallet.dat
restart the wallet and it shows the balance but Out of sync and no connection.
I checked debug.log and can see a lot of lines saying connection refuse, I heard someone say about the port 21101 but I don t know how. please help

**Comment by jrsikors** [comment]
what country are you in?  some countries block Tor... we have this guide if you are in one of those:
https://verge.zendesk.com/hc/en-us/articles/360015942452-Tor-blocked-by-Country-ISP

There's also some other programs that have been known to cause conflicts with the QT Wallet .. like:
 -TokenPay Wallet
 -VMWare

Can also check for tips here:
https://verge.zendesk.com/hc/en-us/articles/360015942312-Syncing-is-slow-stuck-will-take-forever

**Comment by givu** [comment]
Hi
Thanks for your quick reply
I am in England, and I will try your tip to see if it work. Thankyou

Kind regards,

**Comment by givu** [comment]
Hi jrsikors
After many times trying with no luck, I deleted everything regarding Verge v4.0
now I have installed a brand new Verge Lumos v5.1.2, did not work at first, then I had to download the lastest blockchain which I copied and pasted chainstate and blocks files (after extracted them), I replaced those files into the same folders in Verge, also I replaced the wallet.dat file as well, the Lumos this time seemed to work and showed  Connecting to peer "2 weeks behind" and all the details like this screenshot:
![image](https://user-images.githubusercontent.com/50139376/59024808-99c08800-884a-11e9-8043-82cea2d456c1.png)
At the bottom right corner showed "0 active connections to verge network"
Here another screenshot showing the wallet overview, showing my balance (I did try to send 58 XVG to my ios wallet, still not there yet which I understand as the wallet still not 100% synced)
![image](https://user-images.githubusercontent.com/50139376/59025039-28350980-884b-11e9-9f6b-a6e56364f7a3.png)

Can you please look into this problem and give me some advice! as I let the wallet open for all night and still at the exact same %.
Thank you

**Comment by jrsikors** [comment]
see https://github.com/vergecurrency/VERGE/issues/938

I think Marvin is working on a connectivity issue and hopefully has a new version to try out shortly.

Are you in a country that blocks Tor?

**Comment by givu** [comment]
Hi
Thanks for your quick reply. After few trying to click to disconnect and re connect again, the wallet synced and all the coins has now been transfer to my mobile wallet! Even the Lumos seem to work fine and fast now, I prefer the mobile wallet. Thanks

Kind regards,
