### ISSUE TITLE
Hashrate showing 0.00

### ISSUE THREAD

**Issue by Virtuworks** [vergecurrency/VERGE#63]
We cannot seem to get network hashrate from Console. On most coins we use getnetworkhashps is there some other way to get it?

**Comment by justinvforvendetta** [comment]
getinfo will display all 5 altos difficulties. Setting algo= in your conf will set the daemon for whatever algo you choose

**Comment by Virtuworks** [comment]
@justinvforvendetta Thx!

**Comment by Virtuworks** [comment]
@justinvforvendetta this gives me the Difficulty, but not the Network Hashrate. Is there a way to get the network hashrate? All other coins have implemented getnetworkhashp.

**Comment by Virtuworks** [comment]
![image](https://user-images.githubusercontent.com/12708326/29500257-17d5e83c-85ed-11e7-883a-c9857c0d16cb.png)

**Comment by znjRoLS** [comment]
Any progress on this?

**Comment by paintballrefjosh** [comment]
Agree this is still broken.  Always shows 0 for network hashrate using the 'getmininginfo' command.
