### ISSUE TITLE
Hi, after some weeks of trying today I finally synced my Verge Wallet to the blockchain. However, on the 6th of February I sent XVG from my exchange wallet to my verge wallet address (this is evidenced on the verge-blockchain.info). And this transaction is not displaying in my wallet address. Is there anything that I can do to have this balance updated? Or does it just take some time? Please advise. Thanks 

### ISSUE THREAD

**Issue by Cryptopianideal** [vergecurrency/VERGE#630]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by Cryptopianideal** [comment]
My Wallet is VERGE-QT 4.0

**Comment by Cryptopianideal** [comment]
Below is the timestamp of the tranaction.
Timestamp Hash Amount (XVG)
6th Feb 2018 04:00:08 b656091dd60dc515fbd435d29d29979f3b359cf900f5a866257fc1be65ebbccb + 316.00000000

**Comment by justinvforvendetta** [comment]
and you see this address in your receiving tab? and your wallet is not locked?

**Comment by Cryptopianideal** [comment]
Hi Justin, thanks for getting back to me. I just opened & synced my wallet again & opened it yet it's still not showing. The history is this. I downloaded the wallet & then sent my coins from my coinspot account to the wallet address. So I sent them to the address that is stated in my wallet before the wallet was synced to the blockchain. Is it safe to send you a screenshot of this that includes my wallet address? Thanks

**Comment by Cryptopianideal** [comment]
Also, I just unlocked the wallet yet its still showing o balance.
![screenshot 2018-02-24 21 27 34](https://user-images.githubusercontent.com/36782503/36629984-5f6a628a-19aa-11e8-806e-37d794c0a86e.png)

**Comment by Cryptopianideal** [comment]
Here's a screenshot of the transaction without my personal wallet address that can be found in the verge-blockchain.info
![screenshot 2018-02-24 21 34 26](https://user-images.githubusercontent.com/36782503/36630000-bafb4c0e-19aa-11e8-875e-4f7d0bf6ddf7.png)

**Comment by Cryptopianideal** [comment]
This is a screenshot of the transaction from my coinspot account to my verge wallet. Note: I erased my wallet address. This will correlate with the above verge-blockchain.info transaction. Also, I'm in Australia in another time zone, so apologies in advance if our communications are spread over a time period, though I really appreciate your help. If you need any further information for verification please let me know. Thanks Shaun
![screenshot 2018-02-24 21 47 42](https://user-images.githubusercontent.com/36782503/36630115-0d8e4eb0-19ad-11e8-8230-0a785d14f18e.png)

**Comment by jrsikors** [comment]
Why would you think that:
> no this does not show in my receiving address. Nothing shows in my receiving address.

But then in your screenshot -- you seem to have that address :smile: 

couple things:
  1)  Please post a screenshot of help -> debug window ... the information tab
  2)  Try going to help -> debug window -> console  and do 2 things:
     a)  type **_listaddressgroupings_**
     b)  type **_scanforalltxns_**  ... this will take a while,, maybe 10-30 mins, dont close out, let it finish, it will finish

**Comment by Cryptopianideal** [comment]
Hi Justin, I just started it. I will let you know the result when the debug finishes. Thanks
![screenshot 2018-02-25 08 22 43](https://user-images.githubusercontent.com/36782503/36635728-1525b146-1a06-11e8-958e-37622fe24227.png)
![screenshot 2018-02-25 08 25 07](https://user-images.githubusercontent.com/36782503/36635731-1da72cb4-1a06-11e8-85a5-593b1e087401.png)

**Comment by Cryptopianideal** [comment]
Dear jrsikors & Justin, thanks so much for your help! Debugging completed and my coins showed up! I really appreciate the work that you do & I'm looking forward to an exciting future with Verge! Thanks again & have a great day/night! 

![screenshot 2018-02-25 08 44 17](https://user-images.githubusercontent.com/36782503/36635875-393622b2-1a08-11e8-9d84-b4ea3d679709.png)

**Comment by jrsikors** [comment]
No prob -- for the love of god back up of your wallet.dat file .. and/or private key ... please :smile:

**Comment by justinvforvendetta** [comment]
@jrsikors thanks for jumping on issues!
