### ISSUE TITLE
How can I build android wallet from source on my linux machine?

### ISSUE THREAD

**Issue by nosferatu500** [vergecurrency/VERGE#631]
Hi. I found instruction for build android version of Verge (wallet) but it deprecated, right? How can I build android version myself? I know that Google Play already delivery Verge wallet, but I want build it myself :) because version of Google Play just crash on my device. Maybe I can debug this issue and upload fix for this :)

**Comment by justinvforvendetta** [comment]
what kind of crash? we haven't gotten any crash reports

**Comment by nosferatu500** [comment]
Hi, I implemented updates from original electrum wallet for your wallet project (based on Tor) and build mobile app from source. This issue not relevant more :)
