### ISSUE TITLE
Verge 5.9.2 QT Wallet  is NOT acceppting my Passphrase

### ISSUE THREAD

**Issue by portela21** [vergecurrency/VERGE#632]
Can someone give me some help? I'm panicking. 

I already tried with console and .walletpassphrase 'passwordhere' 600 and 300 and nothing. Always says wrong password. But i'm sure that isnt wrong beacause i wrote it on a notepad and create it from copy/paste.

 I got more than 300xvg there :(. Dont know if the problem is because my passphrase starts with ". PLEASE HELP.

**Comment by jrsikors** [comment]
Has it ever worked?  I know this might be too late, but you should always try to unlock your wallet after you set an encryption on it.. just to make sure you can unlock it.

Does your passphrase start with a quote or period or both ?  **_quote + period + TheRestOfIt_**

**Comment by portela21** [comment]
Hello, yes it worked. Just with the quote + TheRestOfIt. I already changed wallet. I'm afraid i will not see my 300 verge again :(.

**Comment by jrsikors** [comment]
https://bitcoin.stackexchange.com/questions/59521/bitcoin-core-command-line-walletpassphrase-incorrect-but-works-for-the-main-syst

> If your passphrase contains spaces or special characters, you will need to wrap it with single quotes (') so that the debug console can properly parse your passphrase. For example, if your passphrase were This is my passphrase, then your command should be
> 
> walletpassphrase 'This is my passphrase'

so in your case it would be:
walletpassphrase '"hello this passphrase starts with a quote' 300
in words:
walletpassphrase + single quote + your passphrase including double quotes + single quote at the end + 300 for timer

What do you mean you already changed wallets?

**Comment by portela21** [comment]
I will try it . Thank you. I created another wallet to mine to another address. Because afraid of losing more

**Comment by jrsikors** [comment]
Maybe someone else has some other insight about whether or not the quotes are an issue.

Passphrases don't just stop working.  It always ends up being a case of the person forgetting it, or them not writing it down cleanly :blush: , them copy/pasting it wrong (getting additional blank spaces or line breaks), or some other user-error type situation.

You should consider doing a dumpprivkey on your wallet addresses as well for additional backup security.  If you had the private key for this address, it wouldn't matter if your passphrase was forgotten / was magically changed / stopped being accepted.

Good luck, hopefully someone else has theories.

**Comment by justinvforvendetta** [comment]
just needs quote
