### ISSUE TITLE
Addnode from commandline not working?

### ISSUE THREAD

**Issue by cryptowhizzard** [vergecurrency/VERGE#633]
Hello,

Am i correct that VERGEd does not support addnode from command line?

I tried VERGEd addnode ip-address ad , but got error in return. I don't want to restart daemon for every node to add?

Is there another way?

**Comment by justinvforvendetta** [comment]
why would you need to keep adding nodes? if you just let the daemon run, you will continue to get more automatically..

**Comment by wijnandschouten** [comment]
Well, some nodes you get to know about, you want a permanent connection with.... it happens when you speak to other pool operators ;) To do that i don't want to restart the daemon, but just add it + put it in config file?

**Comment by justinvforvendetta** [comment]
fair enough, we can add addnode as an rpc command.

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
