### ISSUE TITLE
Using 4.0clearnet and blocks are orphaned.

### ISSUE THREAD

**Issue by shwuhk** [vergecurrency/VERGE#635]
I am building 4.0clearnet from source and for the blocks it mined were turned to orphan. What's the problem?

**Comment by justinvforvendetta** [comment]
not sure. how many blocks did you find

**Comment by justinvforvendetta** [comment]
did you have alot of hashpower

**Comment by justinvforvendetta** [comment]
who got the blocks instead of you

**Comment by shwuhk** [comment]
I solo mined and mine more than 10 blocks. Half of them got orphaned.

**Comment by shwuhk** [comment]
At first I mined with master branch, ~50% of blocks orphaned then I tried again with 4.0clearnet. However, it seems doesn't help and still ~50% of blocks orphaned

**Comment by shtse8** [comment]
I have the same issue.

**Comment by wijnandschouten** [comment]
what is the output of getinfo and getpeerinfo 

Do you use addnode(s) in config?

If your machine is not connected well enough then your found block doesn't get propagated fast enough through the network and chances are bigger someone else finds the same block

**Comment by shwuhk** [comment]
getinfo:
```
{
    "version" : "v4.0.1.0-48d65b4-beta",
    "protocolversion" : 90001,
    "walletversion" : 60000,
    "balance" : 2193.64996300,
    "newmint" : 0.00000000,
    "stake" : 0.00000000,
    "blocks" : 1928875,
    "moneysupply" : 14670204999.99999619,
    "connections" : 8,
    "proxy" : "",
    "ip" : "35.201.226.216",
    "pow_algo_id" : 0,
    "pow_algo" : "scrypt",
    "difficulty" : 74962.50497434,
    "difficulty_x17" : 7362.07452407,
    "difficulty_scrypt" : 74962.50497434,
    "difficulty_groestl" : 585487.95181031,
    "difficulty_lyra2re" : 21025.61198414,
    "difficulty_blake" : 4516603.47593187,
    "testnet" : false,
    "keypoololdest" : 1516878005,
    "keypoolsize" : 101,
    "paytxfee" : 0.10000000,
    "errors" : ""
}
```

getpeerinfo
```
[
    {
        "addr" : "47.91.164.236:21102",
        "services" : "00000003",
        "lastsend" : 1520237652,
        "lastrecv" : 1520237657,
        "conntime" : 1520011467,
        "version" : 90001,
        "subver" : "/VVraith:4.0.1/",
        "inbound" : false,
        "releasetime" : 0,
        "startingheight" : 1922068,
        "banscore" : 0
    },
    {
        "addr" : "138.197.69.53:21102",
        "services" : "00000003",
        "lastsend" : 1520237656,
        "lastrecv" : 1520237656,
        "conntime" : 1520011468,
        "version" : 90001,
        "subver" : "/VVraith:4.0.1/",
        "inbound" : false,
        "releasetime" : 0,
        "startingheight" : 1838890,
        "banscore" : 0
    },
    {
        "addr" : "47.89.29.36:21102",
        "services" : "00000003",
        "lastsend" : 1520237649,
        "lastrecv" : 1520237651,
        "conntime" : 1520011470,
        "version" : 90001,
        "subver" : "/VVraith:4.0.1/",
        "inbound" : false,
        "releasetime" : 0,
        "startingheight" : 1922068,
        "banscore" : 0
    },
    {
        "addr" : "188.40.78.31:21102",
        "services" : "00000003",
        "lastsend" : 1520237651,
        "lastrecv" : 1520237651,
        "conntime" : 1520011628,
        "version" : 90001,
        "subver" : "/VVraith:4.0.1/",
        "inbound" : false,
        "releasetime" : 0,
        "startingheight" : 1922074,
        "banscore" : 0
    },
    {
        "addr" : "145.239.0.122:21102",
        "services" : "00000003",
        "lastsend" : 1520237652,
        "lastrecv" : 1520237654,
        "conntime" : 1520011889,
        "version" : 90001,
        "subver" : "/VVraith:4.0.1/",
        "inbound" : false,
        "releasetime" : 0,
        "startingheight" : 1922084,
        "banscore" : 0
    },
    {
        "addr" : "118.190.75.66:21102",
        "services" : "00000003",
        "lastsend" : 1520237652,
        "lastrecv" : 1520237648,
        "conntime" : 1520012245,
        "version" : 90001,
        "subver" : "/VVraith:4.0.1/",
        "inbound" : false,
        "releasetime" : 0,
        "startingheight" : 1838890,
        "banscore" : 0
    },
    {
        "addr" : "176.9.78.10:21102",
        "services" : "00000003",
        "lastsend" : 1520237649,
        "lastrecv" : 1520237651,
        "conntime" : 1520012934,
        "version" : 90001,
        "subver" : "/VVraith:4.0.1/",
        "inbound" : false,
        "releasetime" : 0,
        "startingheight" : 1922125,
        "banscore" : 0
    },
    {
        "addr" : "219.145.240.74:21102",
        "services" : "00000003",
        "lastsend" : 1520237653,
        "lastrecv" : 1520237653,
        "conntime" : 1520014867,
        "version" : 90001,
        "subver" : "/VVraith:4.0.1/",
        "inbound" : false,
        "releasetime" : 0,
        "startingheight" : 1838890,
        "banscore" : 0
    }
]
```

I didn't use addnode in my config. I don't add it in other coins' daemons too. Did XVG need to addnode by myself(because the node list is not propagated well?)?

**Comment by wijnandschouten** [comment]
I guess the number of peers ( just 8 ) is the problem. I have been busy asking VergeDev why the addnode functionality is non-working in the latest versions, but don't get a reply.

**Comment by justinvforvendetta** [comment]
addnode functionality is working, in the .conf file.

also, make sure your peers are on the current block, (same block as the explorers)

looks like you are connecting to a fork that is invalid.

**Comment by wijnandschouten** [comment]
Well, addnode is nog working here, and i talked to other people where it is not working also.

Ain't to difficult to put addnode=ipaddress in VERGE.conf , but the nodes do not show up as connected peers.

**Comment by wijnandschouten** [comment]
root@daemons:/pool#  ./VERGEd addnode 136.144.xxxcensored add
error: {"code":-32601,"message":"Method not found"}
root@daemons:/pool#

**Comment by justinvforvendetta** [comment]
you're adding a clearnet node in the .conf of the clearnet branch compile?

**Comment by wijnandschouten** [comment]
It doesn't work in both clearnet and in master branche

**Comment by liang55** [comment]
I also encountered the same problem.bulid  the clearnet branch,and adding some node in the .conf.i live beijing.

tail -f .VERGE/debug.log
trying connection 104.131.144.82:21102 lastseen=131.7hrs
connect() failed after select(): Connection refused
trying connection 114.145.237.35:21102 lastseen=145.9hrs
connection timeout

**Comment by jrsikors** [comment]
@liang55 you should stop posting all over the place on different closed issues :smile:  .. it's very hard to help you out.  You should create a new issue, and reference other issues by using URLs like:
https://github.com/vergecurrency/VERGE/issues/778

or just keep posting on the same issue and reference other issues by using URLs

I want to help but I have a difficult time finding you :smile:

**Comment by liang55** [comment]
sorry for bothering you. I also want to solve this problem quickly.
