### ISSUE TITLE
Bug: Electrum-Verge Ignores Proxy Settings For DNS

### ISSUE THREAD

**Issue by protonioneutron** [vergecurrency/VERGE#637]
# Issue Template

## Prerequisites

* [X ] Are you running the latest version?

2.4.1 win32

## User Story:

* "I'm submitting a ... "
  - [ X] bug report

## Expected Behavior

DNS Resolution via proxy when proxy is set.

## Current Behavior
Name resolution ignores proxy settings and directly connects to first google then system nameservers.

## Possible Solution

Temporary: Block non-proxy requests with firewall,  Use raw IP address in electrum settings.

## Steps to Reproduce (for bugs)

* Steps :
1. Set Proxy Settings
2. Start Electrum-verge
3. Observe direct outbound UDP attempts to nameservers

**Comment by justinvforvendetta** [comment]
sounds like you dont have administrator access/permission on your system. have you tried editing the proxy in the electrum .conf file instead of doing this through the GUI?

**Comment by protonioneutron** [comment]
The proxy settings were/are set in the electrum-xvg gui.
The config file properly reflects the proxy settings.
"proxy": "socks5:127.0.0.1:9050",

The GUI has proper write access and is writing to the config file.  The user-level is not the issue.

When started, electrum-xvg sends UDP requests on port 53 directly from electrum-xvg to Google's 8.8.8.8 DNS.

Mainline Electrum 2.9 branch doesn't send any non-proxied requests like this.


I beleive the problem lies in gui/qt/version_getter.py

The requests module looks to be sending a GET to http://electrum-verge.xyz/version without using the proxies parameter.


https://github.com/vergecurrency/electrum-xvg/blob/master/gui/qt/version_getter.py


    def run(self):
        try:
            res = requests.request("GET", "http://electrum-verge.xyz/version")
        except:
            print_error("Could not retrieve version information")
            return
			

			
			
should be 

    def run(self):
        proxies = {'http': 'http://127.0.0.1:9050', 'https': 'http://127.0.0.1:9050'}
        try:
            res = requests.request("GET", "http://electrum-verge.xyz/version", proxies=proxies)
        except:
            print_error("Could not retrieve version information")
            return

**Comment by protonioneutron** [comment]
http://docs.python-requests.org/en/master/user/advanced/


>SOCKS
>
>New in version 2.10.0.
>
>In addition to basic HTTP proxies, Requests also supports proxies using the SOCKS protocol. This is an optional feature that requires that additional third-party libraries be installed before use.
>
>You can get the dependencies for this feature from pip:
>
>$ pip install requests[socks]
>
>Once you've installed those dependencies, using a SOCKS proxy is just as easy as using a HTTP one:
>
>proxies = {
>    'http': 'socks5://user:pass@host:port',
>    'https': 'socks5://user:pass@host:port'
>}
>
>Using the scheme socks5 causes the DNS resolution to happen on the client, rather than on the proxy >server. This is in line with curl, which uses the scheme to decide whether to do the DNS resolution on the >client or proxy. If you want to resolve the domains on the proxy server, use socks5h as the scheme.

Assuming this GET is the source of the DNS request, 
the fix is probably something like:

    def run(self):
        try:
            proxystr = self.config.get('proxy').split(':')
            proxyproto = proxystr[0]
            proxyport = proxystr[-1]
            proxyip = proxystr[-2]
            _proxy = proxyip + ':' + proxyport
            if 'socks5' in proxyproto:
                proxies = {'http': 'socks5h://' + _proxy, 'https': 'socks5h://' + _proxy}
            elif 'http' in proxyproto:
                proxies = {'http': 'http://'+_proxy, 'https': 'http://'+_proxy}
            elif 'socks4' in proxyproto:
                #requests doesn't do socks4
                proxies = None
            res = requests.get("http://electrum-verge.xyz/version", proxies=proxies)
        except:
            print_error("Could not retrieve version information")
            return

**Comment by justinvforvendetta** [comment]
well, we arent going to be supporting the clearnet electrum wallet/servers much longer, and i find it strange, that the electrum tor wallet doesnt have this issue. maybe its because it isn't getting a version..  (however community members may or may not run their own)

**Comment by jrsikors** [comment]
spring cleaning and closing issues -- please re-open if you feel it is important and maybe someone else can assist. As @justinvforvendetta  said, this specific wallet won't be available much longer.
