### ISSUE TITLE
Get listunspent - misunderstanding

### ISSUE THREAD

**Issue by nosferatu500** [vergecurrency/VERGE#638]
Hi, again. I started experimental with your node (I like it :) ) and I misunderstanding one thing. I start my node  as unique node for start mine my  blocks myself. And I start send RPC resuests to it. When I send `listunspent` command with address parameter (private  key imported to this node), I  get list of my transactions, but  when I start second  node and sync it  with first node,  I start send `listunspent` request for second node with old address  parameter (same as for first node)  I get empty array, but if I import private key of first address  for second node and send request again, I get my transactions correctly. It's correct behavior? Why I don't see any unspent transaction while don't import private  key for this address? Bitcoin & Ethereum network  can give me this  information without  import private key, for  example.

**Comment by justinvforvendetta** [comment]
stop copying our software to make scam coins.
