### ISSUE TITLE
can not open verge core wallet

### ISSUE THREAD

**Issue by vergecalling** [vergecurrency/VERGE#639]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by vergecalling** [comment]
![screenshot 3](https://user-images.githubusercontent.com/36392616/37063602-dd691a22-2167-11e8-8e35-e46776794423.png)

**Comment by justinvforvendetta** [comment]
where did you Download it from?also, how much ram do you have and what kind of cpu?

**Comment by vergecalling** [comment]
I downloaded from vergecurrency website I have 8 gb ram and intel core i7
4700mq

**Comment by vergecalling** [comment]
I have downloaded wallet with 1000 coin today I don’t see my wallet on
computer then I downloaded and it shows error that I screenshot to you

**Comment by justinvforvendetta** [comment]
try right clicking it, and "run as administrator"?

**Comment by vergecalling** [comment]
I tired

**Comment by vergecalling** [comment]
Doesn’t work

**Comment by jrsikors** [comment]
Hate to ask the obvious -- but did you reboot :cry: 

Anything in your Event Viewer logs when you try to run it?

Have you tried temporarily disabling Anti Virus and then running it?  Anti Virus applications really don't like QT wallets and cause lots of weird issues.

Before you disable Anti Virus -- let's make sure you got the safe/real QT in case you got phished.

Try deleting what you got and download it from here:
https://github.com/vergecurrency/VERGE/releases/tag/4.0stealth

Only other thing I can think of is that the download/file is corrupt.. and maybe re-downloading it will be fine.

Another thing to try -- don't run the QT right from the C:\users\<you\Downloads folder ... try making a new directory called like:
C:\CryptoWallets\VergeQT ... and unzip it / run it from there.

**Comment by vergecalling** [comment]
Finally I run the wallet and import private key it was successful but my
coin doesn’t show on new wallet please tell me how do I get my coin. Thank
you

**Comment by jrsikors** [comment]
You are probably not sync'd up yet.  You will need to leave your verge-qt wallet running for a long time (hours and hours) to get fully sync'd.

If you go to help -> debug window -- can you post a screenshot of that here?  You can see sync information on that tab.  Current/latest verge block as of me writing this is 1,940,080 .. so you will need to get sync'd close to that block

**Comment by vergecalling** [comment]
hi this is screenshoot of my wallet. i did only first transaction 100 xvg
to bittrex. but i did not do second one which is 899 xvg. how is it happen
and i do not know that sent address where does my coin go and who sent it.
after sending first 100 coin i do not see my wallet on my computer. now i
download and see these happen. please help me get those coin.

**Comment by jrsikors** [comment]
Dont see a screenshot :frowning_face:

**Comment by jrsikors** [comment]
And if you couldn't get Verge-QT to open -- how did you know what address to send it to ?

need to check in C:\Users\YOU\AppData\Roaming\Verge for your wallet.dat , or older versions

**Comment by vergecalling** [comment]
look for previous comment that i told i got verge qt and now i sending again screenshoot with my current issue
![screenshot 5](https://user-images.githubusercontent.com/36392616/37228226-e38c5250-23ad-11e8-8e2c-ef0b12f9f92e.png)

**Comment by jrsikors** [comment]
All I can say is that your 899 coins are at this address:
https://verge-blockchain.info/address/DHXJyg2RcaagUCreH9xfFrJhp13Y1oM1Zi

Based on this transaction:
https://verge-blockchain.info/tx/93ddbee71f0030620a15d6bbfcc49e92d9631bc469d35ceaa63115ed7dc92700

It looks like 100 XVG went to https://verge-blockchain.info/address/DPqUscMqhyDo8yG1DN5mmBCf4D8ujKRiae

and the other 899.7 went to https://verge-blockchain.info/address/DHXJyg2RcaagUCreH9xfFrJhp13Y1oM1Zi

This could be a "Change Address" in an old wallet.

When you send "Partial transactions", your coins get sent to a "Change Address" .. go to google and search for "Bitcoin change address" to learn about it.

If you don't have the private key for DHXJyg2RcaagUCreH9xfFrJhp13Y1oM1Zi ... or if you don't have an old wallet.dat file with DHXJyg2RcaagUCreH9xfFrJhp13Y1oM1Zi address ... your coins are probably disappeared.

**Comment by vergecalling** [comment]
Finally my coins are disappreared. Thank you

**Comment by jrsikors** [comment]
After *EVERY* transaction in QT wallets, any crypto QT wallet, you ALWAYS need to do 2 things:
  1)  Immediately make a backup copy of your wallet.dat (keep renaming it to like wallet-xvg-2018-03-9.dat).
  2)  Make sure you know where your coins went via the blockchain explorer like verge-blockchain.info .. and get the private key of the new address if it will make you more comfortable , but doing number 1 will take care of it

Doing those 2 things mean you will never be surprised and lose coins.

**Comment by justinvforvendetta** [comment]
also in that picture, it looks like the wallet is locked (lower right corner)

**Comment by Steve48376** [comment]
i,m running ubuntu and i downloaded the verge-ubuntu24-appimages.zip and extracted the file. 

<img width="514" height="606" alt="Image" src="https://github.com/user-attachments/assets/f39dc9b0-4993-4903-a033-b9a5fd35ac31" />

But i can,t run any of the files because i receive a error message that verge core is already running. If you execute the Verge-Qt-x86_64.Appimage ofter a restart, the file opens shortly but you only see "Launching Verge Core" v26.5.0

**Comment by swat69** [comment]
Yes not working, I tested it just an hour ago:

May 12 10:01:08.735 [notice] Opening Control listener on 127.0.0.1:9051
May 12 10:01:08.735 [notice] Opened Control listener connection (ready) on 127.0.0.1:9051

============================================================ T= 1778572898
Tor 0.4.9.5 (git-1442ca4852283d66) died: Caught signal 11
..
/tmp/.mount_Verge-aBloeB/usr/bin/verge-qt(+0x259555)[0x55b3f707a555]
Aborted (core dumped)

**Comment by justinvforvendetta** [comment]
@swat69 @Steve48376 i think i just fixed it, was a path issue between github runner and users. ill tag a new release in a minute, 26.5.1 (i also cleaned up macOS sizing as it was opening at about 60% the width it should have been, so might as well tag it) thanks guys.. build is running right now

**Comment by justinvforvendetta** [comment]
@swat69 @Steve48376 confirmed that it works now on a fresh ubuntu install. thank you both for the report and crash info. 

also @Steve48376 just to clarify, the verge-qt appimage is the gui wallet, verged, verge-tx, and verge-cli are headless and only used in terminal. ./verged will stay running in processes until stopped with ./verge-cli stop, and if it is running, verge-qt cannot be launched. that part is normal behavior. appreciate you guys testing and leaving feedback. new binaries are now in the 26.5.1 releases tab. 

https://github.com/vergecurrency/verge/releases/tag/v26.5.1
