### ISSUE TITLE
XVG coins in limbo 

### ISSUE THREAD

**Issue by fireman50** [vergecurrency/VERGE#64]
ok, so i downloaded the QT wallet & generated an address & i sent some coins to it. during this it was lost in syncing. I read up & i downloaded the blockchain to the QT wallet & it synced. then I encrypted it. so now, my initial transaction i made has not arrived or is not showing. even though there are over 4k confirmations on it. i sent another transaction to it as a test, & my coins arrived. I've reinstall the blockchain into verge. I've backed my wallet up,  I can see the transaction on the https://verge-blockchain.info/tx/cc263cc0f2ff7f88449e020241a06fc55f626d987869db27a3d5887190a28c70 , it says it went. it ought to be in my wallet, however, it is not. I've checked the receiving address multiple times & it is correct. how do i get this to resolve. & get them to a different wallet if they're not showing in the verge qt wallet?  why is this happening also. there must be a reason. right? & there must be a solution too. any input & advice will be greatly appreciated. thanks

**Comment by justinvforvendetta** [comment]
@fireman50 so are we talking about DLjXf7Micsi5EeQ8DFHKNTxQoSeK98yCCg ?

https://verge-blockchain.info/address/DLjXf7Micsi5EeQ8DFHKNTxQoSeK98yCCg

so out of the three incoming transactions, you only received one? or two? you don't currently have 

50001.04752400 coins in that wallet?

**Comment by fireman50** [comment]
no i don't have the 50001. i only received the last one for 99.80

**Comment by fireman50** [comment]
![screen shot 2017-08-21 at 12 09 06 am](https://user-images.githubusercontent.com/31201016/29507473-1c6f2ecc-8605-11e7-813d-a8f8d691dbbc.png)

**Comment by fireman50** [comment]
![screen shot 2017-08-21 at 12 13 04 am](https://user-images.githubusercontent.com/31201016/29507574-9e55f6c8-8605-11e7-9cae-f546529e0e7e.png)
![screen shot 2017-08-21 at 12 13 30 am](https://user-images.githubusercontent.com/31201016/29507583-a2bb8f3e-8605-11e7-8763-1d96795d68ad.png)

**Comment by fireman50** [comment]
so bottom line is that although my wallet was backed up. it looks like the transaction is not going to load because it wasn't synced when the transaction was taking place. so it doesn't know to show in the wallet. i suppose. i thought that when the blockchain loads the wallet would recognize its receive address within the block & say, hey, thats mine. however, it's not doing that. instead it's saying, well it didn't happen when i was all synced up & ready to receive so i'm not going to grab it. i know this sounds strange. though, i haven't gotten any other ideas about why its not showing itself. i would love to figure it out any remedy it. though it just sitting on the blockchain. it cant be transfer, it cant be sold, its stuck. any ideas or feedback?

**Comment by fireman50** [comment]
the transaction is in the blockchain. though not in the wallet. the wallet receiving address doesn't pull it from the block. oh well. i guess. I still think this is a good wallet, however I'm a little more cautious & think there's technology of the blockchain I do not understand fully & that ok. All I can suggest is only send funds when the wallet is synced. for me, that is the only way any transactions have come through.

**Comment by justinvforvendetta** [comment]
@fireman50 transactions do not appear in any wallet before it is synced! that's not how blockchains work.

**Comment by fireman50** [comment]
ok. though it will generate an address & before its synced.

**Comment by justinvforvendetta** [comment]
Yes of course. It doesn't even need to be online to generate an address since the pubkey and scriptkey are hardcoded

**Comment by fireman50** [comment]
You see, The first two transactions have never been in this wallet. It's a mystery that's for sure.

![screen shot 2017-08-23 at 6 14 11 pm](https://user-images.githubusercontent.com/31201016/29652783-eef78c24-885b-11e7-9412-d97ddb241108.png)
