### ISSUE TITLE
submitblock RPC rejections 

### ISSUE THREAD

**Issue by oliverw** [vergecurrency/VERGE#641]
We are getting roughly 40% of our mined blocks rejected by the daemon (see log below) using 6.16.1 Beta compiled on Debian 9.3. I'm not sure if there's an issue with our pool software's handling of Verge's PoW/Pos hybrid nature:

https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinJob.cs

ThreadRPCServer method=submitblock
InvalidChainFound: invalid block=1392a5e4216dafa52d7b height=1950683 trust=1950684 date=03/13/18 17:00:43
InvalidChainFound: current best=6e5ad73c3d1d076a9054 height=1950682 trust=1950683 date=03/13/18 16:59:38
ERROR: SetBestChain() : SetBestChainInner failed
ERROR: AcceptBlock() : AddToBlockIndex failed
ERROR: ProcessBlock() : AcceptBlock FAILED

**Comment by justinvforvendetta** [comment]
closing, since this is being discussed directly on the pool stratum repository
