### ISSUE TITLE
Why my wallet is out of sync about 10 days ago !

### ISSUE THREAD

**Issue by teodoradr** [vergecurrency/VERGE#642]
Hello,

My wallet is out of sync about 10 days ago. I running the wallet 6-7 hours per day and it blocked at 94.17% . It don't moves.

**Comment by jrsikors** [comment]
go to help -> debug window ... please post a screenshot of the information tab... which shows your version and block information

**Comment by teodoradr** [comment]
![screenshot at mar 15 17-19-52](https://user-images.githubusercontent.com/35401833/37472591-20031af4-2875-11e8-8c04-7d96a2dedce2.png)

**Comment by jrsikors** [comment]
Thanks --- weird -- your total blocks look good.  But yeah your "Last BLock Time" means you haven't sync'd past Sunday March 4th block...

Is that block number moving up?  The "Last Block Time" ?  Or stuck?

**Comment by teodoradr** [comment]
Is stuck.

**Comment by jrsikors** [comment]
there's a couple things we can try right off the bat:
  1)  Close down verge-qt ... delete the peers.dat file in your data directory ... re-open and see what happens
  2)  Close down verge-qt ... i'm not sure how to explain to do this on a Mac... but essentially you need to run verge-qt wallet with an argument: **_verge-qt -rescan_**

**Comment by jrsikors** [comment]
the nuclear option is to:
download the latest bootstrap from https://verge-blockchain.com/
 step 1) close down verge-qt
 step 2) rename the whole data directory to like "vergeolddata"
 step 3) fire up verge-qt
 step 4) close down verge-qt
 step 5) unzip the bootstrap into the new data directory
 step 6) copy your wallet.dat back from your vergeolddata directory in step 2

You sound like you are smart, make sure you safely backup your current wallet.dat before trying anything.. if you havent :smile:

**Comment by jrsikors** [comment]
and actually my verge-qt -rescan might have been a bad suggestion.  Nothing harmful about running it -- won't hurt -- but I  think it just re-scans your blocks and won't really help your syncing issue.

**Comment by teodoradr** [comment]
HighSierra don't has VERGE in application support , so i can't apply this actions .

**Comment by jrsikors** [comment]
your data files / wallet.dat file have to be somewhere ... where are they? :D

**Comment by teodoradr** [comment]
Unfortunately, I really don't know where they are. I try to find out.

**Comment by jrsikors** [comment]
do a full search for like "wallet.dat" ... it's gotta be somewhere !

**Comment by jrsikors** [comment]
i saw this post for a bitcoin QT wallet

> On the new Mac OS X you can't see the Bitcoin folder in the library under /application support/. You have to use Finder and in the menu look for GO and then GO TO type ~/Library in the box. After that you can see the Bitcoin folder under /application support/.

**Comment by jrsikors** [comment]
> On the new Mac OS X you can't see the Bitcoin folder in the library under /application support/. You have to use Finder and in the menu look for GO and then GO TO type ~/Library in the box. After that you can see the Bitcoin folder under /application support/.
> 
> Or you can hold down the Option key while selecting the Go menu and Library will become an option.
> 
> >

**Comment by teodoradr** [comment]
Yuhu ! I find it . I will try the first option , with peers.dat. Thanks for your help !

**Comment by jrsikors** [comment]
Just to re-cap my suggestions --
1)  Close down verge-qt ... delete peers.dat from the datadirectory (if you find it) ... re-open verge-qt
I dont think this will help ... i think the problem is worse than that though .. but it's definitely the easiest path to trying to fix

**Comment by jrsikors** [comment]
if that doesn't work -- (Give it at least 30 minutes after opening) -- something must have gotten corrupt in your datadirectory and you need to go nuclear and basically get rid of your current data directory ~~~~ **_(MAKE A COPY OF YOUR WALLET.DAT FIRST)_** ~~~~

So you can either let it re-sync from block 0 ... which will take a long time ... or do what i suggested earlier and go download the bootstrap from verge-blockchain.com ... unzip in your new directory .. and go from there.

**Comment by justinvforvendetta** [comment]
any update @teodoradr

**Comment by teodoradr** [comment]
Today I maked it to work. I got blockchain from the verge-blockchain.com and I replaced the old files.Thanks jrsikors !

**Comment by justinvforvendetta** [comment]
great to hear!
