### ISSUE TITLE
I can't open my XVG-electrum wallet anymore. 

### ISSUE THREAD

**Issue by rickert93** [vergecurrency/VERGE#644]
In December i have downloaded an amount of XVG and stored this in the electrum XVG-win-amd64 wallet. In December this wallet was synced and working well, in January i have opened it too while it was still working.
Yesterday i tried to open this wallet again, but i get this error so i can’t open it. 
![2018-03-12](https://user-images.githubusercontent.com/37479982/37557490-8aac0366-2a05-11e8-817f-449fde30772a.png)

How can i get this wallet working again?
Can somebody help me to get this wallet working again, or get my adress in the new XVG Wallet?
BTW, i have 0 experience with programming/software or what so ever.
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by jrsikors** [comment]
you try running it as Administrator?

**Comment by rickert93** [comment]
Yes, i only have one account on my laptop so that is the Administrator account.

**Comment by jrsikors** [comment]
but actually right click on the .exe and "Run as Administrator"

**Comment by rickert93** [comment]
Good point, but unfortunately i get the same error.

**Comment by jrsikors** [comment]
in the directory as the .exe , there is a log.txt .. is there anything in it?

**Comment by rickert93** [comment]
I actually have two logs, one empty en one with some errors.

**Comment by rickert93** [comment]
![2018-03-17](https://user-images.githubusercontent.com/37479982/37557958-9baf81ea-2a0c-11e8-8041-e9e6522251fe.png)

**Comment by rickert93** [comment]
The log says this a few times:

Traceback (most recent call last):
  File "C:\Users\Beheerder\Documents\school\electrum-xvg-win-amd64\lib\interface.py", line 190, in get_socket
    do_handshake_on_connect=True)
  File "C:\Anaconda3\envs\pyqtexe27\lib\ssl.py", line 943, in wrap_socket
  File "C:\Anaconda3\envs\pyqtexe27\lib\ssl.py", line 611, in __init__
  File "C:\Anaconda3\envs\pyqtexe27\lib\ssl.py", line 840, in do_handshake
error: [Errno 10054] De externe host heeft een verbinding verbroken
Traceback (most recent call last):

**Comment by jrsikors** [comment]
Are those log entries from today/just now ?  I noticed the file dates are back from December.

Couple other things I would try:
 1)  Go re-download https://github.com/vergecurrency/electrum-xvg/releases/latest  ... unzip it to a **_DIFFERENT_** directory ... and try to run it again.
 2)  temporarily disable anti virus if you can , sometimes wallets get flagged as false positives

**Comment by jrsikors** [comment]
Also saw this old issue:

#524 

which referred him to the electrum repository issues:
https://github.com/vergecurrency/electrum-xvg-tor/issues

But i didn't see him re-post the issue there from his account.  will try to dig something up for you.

This repository is more for Verge-QT wallet issues, you might find some more electrum experts over there

**Comment by rickert93** [comment]
The thanks man, i apreciate this. When i downloaded a new wallet it worked again. Do you know which network settings i have to use to get it online?

**Comment by rickert93** [comment]
Oh haha autoconnect worked.

**Comment by rickert93** [comment]
Can i delete the previous downloaden wallet?

**Comment by jrsikors** [comment]
should be safe --- your important files should be in c:\users\XXXYOUXXX\AppData\Roaming\Electrum or somewhere around there

You might want to consider doing this as well
https://www.reddit.com/r/vergecurrency/comments/7uelnl/electrum_wallet_offline_please_help/

There's a link to a youtube video that looks good

Nutshell instructions:
Step 1) Close down Electrum wallet
Step 2) Browse to where your Electrum 'installation' is
Step 3) Go into the Lib folder
Step 4) Open network.py in notepad or textpad , some kind of text editor
Step 5)
Replace this chunk of code:

DEFAULT_SERVERS = {
'electrum-verge.xyz':{'t':'50001', 's':'50002'},
'electrum-xvg.stream':{'t':'50001', 's':'50002'},
'electrum-xvg.party':{'t':'50001', 's':'50002'}
}
With this chunk of code:

DEFAULT_SERVERS = {
'electrum-verge.xyz':{'t':'50001', 's':'50002'},
'electrum-xvg.stream':{'t':'50001', 's':'50002'},
'electrum-xvg.party':{'t':'50001', 's':'50002'},
'e1.verge-electrum.com':{'t':'50001', 's':'50002'},
'e2.verge-electrum.com':{'t':'50001', 's':'50002'},
'e3.verge-electrum.com':{'t':'50001', 's':'50002'}
}
step 6) Open Electrum
step 7) Go to tools -> network
step 8) Make sure "Auto-connect" is checked, and the 3 electrum servers are listed:
e1.verge-electrum.com
e2.verge-electrum.com
e3.verge-electrum.com

**Comment by jrsikors** [comment]
But i wouldn't do that if you are working and functioning fine -- just keep those instructions handy in case your client stops being connected

**Comment by rickert93** [comment]
At the moment is functioning fine, so i'll keep it this way, but i'll save these instructions in case i'm going to need it. Thanks!
