### ISSUE TITLE
Verge Unable to sign block, wallet locked [wallet is actually not locked]

### ISSUE THREAD

**Issue by goodthebest** [vergecurrency/VERGE#646]
@VERGEDev 
I keep getting rejected blocks even though have tried to install wallet on ubuntu 16.04 headless wallet to run with my pool. Wallet is not locked or encrypted, any clue?

algo=blake

>2:16:31: ERROR: rpc_do_call: 159.89.186.76:15550 500
12:16:31: ERROR Verge Unable to sign block, wallet locked?
12:16:31: *** REJECTED :frowning: Verge block 1968847 1 txs

**Comment by justinvforvendetta** [comment]
you'd want to ask a yiimp admin... I've only set up verge on a nomp and unomp

**Comment by goodthebest** [comment]
well it has nothing to do with yiimp, rather core issue at Verge. @justinvforvendetta are you Verge,  Dev?

**Comment by justinvforvendetta** [comment]
yes, and no other yiimp pools seem to have this issue, which is why I suggested you contact one. the blake algo has a very high diff right now so I don't think that's an issue

**Comment by goodthebest** [comment]
ok thanks I'll look into it further. In case, I need to bring any bug into your notice, what log should I submit?

**Comment by justinvforvendetta** [comment]
definitely the daemons debug log

**Comment by justinvforvendetta** [comment]
http://yiimp.eu/explorer/XVG

they find blake blocks pretty often
