### ISSUE TITLE
error: couldn't connect to server

### ISSUE THREAD

**Issue by peengo** [vergecurrency/VERGE#647]
# Issue Template

## Context

I am trying to access Verge daemon and use its commands eaither via CLI or RPC.
It worked before with qt wallet 3.0.0.0 Now i am on latest and I downloaded the blockchain.
The wallet is opened and synced. (getinfo) is working inside qt wallet but from "VERGEd.exe getinfo" it stopped working. I am using the default verge.conf (all lowercase) file from this github on a Windows 7 system.

## Prerequisites

* [X] Are you running the latest version?
Yes + 3.0.0.0 which I used previously

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [X] support request 
  - [ ] translation request 

## Expected Behavior

should connect to the daemon and return data (getinfo, getblockcount...)

## Current Behavior

error: couldn't connect to server

## Screenshots

Log from runninga a standalone "VERGEd.exe" without any args.

'which' is not recognized as an internal or external command,
operable program or batch file.
Mar 21 14:26:44.954 [notice] Tor 0.3.2.8-rc-dev running on Windows 7 with Libeve
nt 2.0.22-stable, OpenSSL 1.0.2k, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Mar 21 14:26:44.954 [notice] Tor can't help you if you use it wrong! Learn how t
o be safe at https://www.torproject.org/download/download#warning
Mar 21 14:26:44.954 [notice] Configuration file "C:\Users\pingo\AppData\Roaming\
VERGE\tor\torrc" not present, using reasonable defaults.
Mar 21 14:26:44.954 [warn] Path for GeoIPFile (<default>) is relative and will r
esolve to D:\Crypto\NewVergeWallet\<default>. Is this what you wanted?
Mar 21 14:26:44.954 [warn] Path for GeoIPv6File (<default>) is relative and will
 resolve to D:\Crypto\NewVergeWallet\<default>. Is this what you wanted?
Mar 21 14:26:44.969 [notice] Scheduler type KISTLite has been enabled.
Mar 21 14:26:44.969 [notice] Opening Socks listener on 127.0.0.1:9089

## Steps to Reproduce (for bugs)

* Steps :
1. Download latest Verge qt windows wallet
2. Download and copy blockchain
3. Open and wait till it syncs
4. Execute "VERGEd.exe getinfo" via CLI or RPC.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [X] I'm using Windows 7 64
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
it sounds like you aren't giving the daemon enough time to load the block index, or you're trying to run it while the qt is running

**Comment by peengo** [comment]
I run either the qt wallet or the daemon and wait till it sync so I can execute "getinfo" in the qt wallet's debug console. Then I run "VERGEd.exe getinfo". It used to work for me like this. Is it possible that the verge.conf file is ignored?

**Comment by peengo** [comment]
Hmm maybe you're right. It just started working with the daemon. I'll test the qt soon and close the ticket if it will work.

**Comment by jrsikors** [comment]
you have a chance to try it out ?

**Comment by peengo** [comment]
It only works for me by leaving the daemon running and not the qt wallet.

**Comment by jrsikors** [comment]
From what I'm reading about daemons, running this command **_Verged.exe getinfo_** and getting an error should be normal.  "getinfo" is not a valid option to run with **_verged_**

**Comment by justinvforvendetta** [comment]
getinfo should work

**Comment by jrsikors** [comment]
but opening a command prompt and running straight:
**_verged.exe getinfo_**

That isn't a valid argument to run with verged.exe

running verge-cli getinfo is legit
running verged -conf="c:\verge.conf" is legit

running verged getinfo is not legit

right? :smile:

**Comment by peengo** [comment]
They way verge handles this goes like this:
1. You firstly run VERGEd.exe or just VERGEd on linux/mac
2. Wait till it syncs (Its usually around 30 minutes for me if the qt walled is synced)
3. Then you execute the same "VERGEd.exe getinfo" in parallel while the first VERGEd.exe without parameters is running in the background

**Comment by jrsikors** [comment]
I don't need them but it wouldn't hurt for  @justinvforvendetta to see what you are talking about. with running verged getinfo

Running verged getinfo "too soon" definitely does give you the "unable to connect to server" message

**Comment by peengo** [comment]
Yeah I managed to get it working but it used to work with qt opened as a daemon.
