### ISSUE TITLE
UseBridges: Cannot start Version 4.0.1 - Debian Stretch / Tor config issues

### ISSUE THREAD

**Issue by SJablonska** [vergecurrency/VERGE#648]
My platform: Debian Stretch, latest updates (including tor).

I am using tor with multiple other applications.

Verge 4.0.1 following build-verge-linux.md (both ways).

Either way,I keep getting the same error: "Failed to parse/validate config: If you set
UseBridges, you must specify at least one bridge."
Which results in: "Timed out waiting for onion hostname"

Changed UseBridges settings in torrc, etc.

Nothing works. It looks like the UseBriges request is hard coded to 1.

I added the following settings to ~/.VERGE/tor/torrc:
UpdateBridgesFromAuthority 0
UseBridges 0
UseEntryGuards 0

Now the warning says: Failed to parse/validate config: Setting UseBridges requires also setting UseEntryGuards.

**Comment by jrsikors** [comment]
Just as a troubleshooting step ... did you try closing down your other applications that use Tor, and then run verge solo as the only app using Tor?  (revert settings in ~/.VERGE/tor/torrc: back to default) ?

**Comment by jrsikors** [comment]
Total shot in the dark based on reading the error messages here
https://github.com/torproject/tor/blob/9ef97a268b06fed7b07908823600911a2a6eadc1/src/test/test_options.c

and 
https://www.torproject.org/docs/tor-manual.html.en

UseEntryGuards needs to be 1  ?

**Comment by SJablonska** [comment]
Thanks for the help, saw both pages and but I tried all settings, even including the /etc/tor/torrc file, because I thought that file might somehow take precedence over the verge torrc file.
Nothing works.

**Comment by jrsikors** [comment]
Yeah sorry I'm not up a unix/tor expert.

Couple things that aren't helpful:
  -You are like 2nd person to ever post an issue about Debian Stretch on this verge issues page, and the other one just had compiling problems
  -From the instructions -- it doesn't seem like you are supposed to do anything additional to get Tor to work, like create a verge torrc file.

When I run Verge on my windows box... and look through the tor.log ... it looks for a verge\tor\torrc, can't find it, and uses "Reasonable defaults".  When you do the Debian Stretch version -- does it create you a verge\tor\torrc ?

I would do this:
  ~get rid of your verge\tor\torrc  (if you had to create it)
  ~get rid of tor.log
  ~run it again
  ~post the full tor.log in case there's something else

If you'd rather not potentially waste your time with my thoughts, no offense will be taken :smile: 

@justinvforvendetta or someone else who might have an idea will hopefully be along shortly

**Comment by SJablonska** [comment]
Normal install does NOT create a verge\tor\torrc.

I will test the other suggestions.

**Comment by jrsikors** [comment]
verge\tor\torrc NOT being created is completely fine.  Like I said --on my windows box I don't have any Tor installed anywhere, and Verge doesn't care... it just uses defaults.

In your case -- I think obviously what's happening -- since you have Tor installed a couple places, and an /etc/tor/torrc ... Verge is probably trying to use those settings and doesn't like them.

I know in the past @justinvforvendetta has suggested to other people to "close down other tor applications" before opening Verge wallet .. just as a test.

**Comment by jrsikors** [comment]
so I'm assuming we can close this since you posted #669  .. you finally got past this and loaded the QT successfully ?
