### ISSUE TITLE
Trojan:Script/Cloxer.A!cl in latest Windows wallet

### ISSUE THREAD

**Issue by insekticid** [vergecurrency/VERGE#649]
Trojan:Script/Cloxer.A!cl in https://github.com/vergecurrency/VERGE/releases/download/4.0stealth/VERGE-windows.zip

![image](https://user-images.githubusercontent.com/177340/37793190-2cfa03dc-2e0e-11e8-96e9-31af8277dd59.png)

**Comment by jrsikors** [comment]
almost all anti virus programs label QT wallets as false positives for viruses.  

It's worth a double check by Justin, but I doubt it's an issue.

https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Script/Cloxer.A!cl

**Comment by justinvforvendetta** [comment]
this is just detecting the mining capability of the wallet, if gen=1 in configuration. false positive.
