### ISSUE TITLE
Hashrate showing 0.00

### ISSUE THREAD

**Issue by Virtuworks** [vergecurrency/VERGE#65]
Hashrate for Network is at 0.00 on all console commands. Seems something is wrong since moving multi-algo.

**Comment by Virtuworks** [comment]
Any help with this?

**Comment by justinvforvendetta** [comment]
ah yes i see. we need to implement the hashrate per algorithm. thanks for bringing that up.

**Comment by Virtuworks** [comment]
Thx for response let me know when we can download new version or beta of new candidate happy to test

**Comment by jrsikors** [comment]
I'm assuming this was taken care of?  if not, feel free to re-open.
