### ISSUE TITLE
[Feature Request] - sendmanystealth

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#651]
Currently we can do:
sendmany <account> {address:amount,...}

However sendmany is unable to generate typical addresses from stealth addresses.

sendmanystealth <account> {stealth_address:amount,...}
// Would send amount to stealth addresses in array
// Useful for when sending to multiple stealth addresses or a combination of stealth and normal

Support for sending mass stealth & normal address in the same transaction sendmany combo would be ideal but a simple sendmany stealth support would be sufficient.

**Comment by justinvforvendetta** [comment]
thats a great idea

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
