### ISSUE TITLE
BLKINDEX.DAT

### ISSUE THREAD

**Issue by jetpippo** [vergecurrency/VERGE#658]
Hi my name is Alessandro, I've been having the same BLKINDEX problem I've been reading all these MAC users are having but with windows 10.

Im really new to all this but this is what happened:
I downloaded the wallet 4.0.1 from the Verge website, when I opened it it was out of sync and had so many blocks to load (at this point i still didn't know i could download the blockchain) anyways i waited nearly 2 days for all the blocks to download. Everytime it was getting close to finishing it went back to around 70%. 

While this was happening I tried to send all my XVG to this unsynced wallet to an address i generated from there (not sure whether this is ok or not ...)

I got fed up with waiting cuz I didn't know whether sending those coins was a mistake.
I started searching online and saw i could download the blockchain, so i downloaded "Wallet_v4.x_Verge-Blockchain_2018-March-25" (copied my wallet to safe location because i thought there should be the coins i previously sent) unzipped it in the APPDATA then i try to open the Wallet APP but once it finished loading the blockchain index it gives me "error loading blkindex.dat".

I tried doing this various times,I also tried deleting the Verge folder in the APPDATA and tried again with the 26 March Blockchain.
 I tried to unzip the blockchain inside the folder and overwrite the files already there and also tried deleting all the files in the folder and just unzipping the blockchain in there. I tried to disable my antivirus. Attached below the log:

debug.log

I wanted to try to download the 4.0.1 again but my computer doesnt want to download it cuz it says it could contain a trojan, so i didnt wanna download it again (even though it doesnt make sense why it did allow me to download it 5 days ago).
As i've said im very new to all this and not very good with computers so I might have done something stupid along the way, but i looked at multiple videos of people doing this operation and everything went all right

**Comment by jetpippo** [comment]
![verge ex](https://user-images.githubusercontent.com/37868930/38027341-e457de34-32c1-11e8-9531-2551cc79c9fc.png)

Just wanted to show what it looks like and to confirm the version is correct

**Comment by jetpippo** [comment]
![verge ex 2](https://user-images.githubusercontent.com/37868930/38027420-2525ee4c-32c2-11e8-9677-ecb82b0457b2.png)

I dont know how to get to the debug window the guy before me posted, I assume you can only access it once the Wallet App actually opens

**Comment by jetpippo** [comment]
[tor.log](https://github.com/vergecurrency/VERGE/files/1855850/tor.log)

not sure if this can help either ...

**Comment by jrsikors** [comment]
if multiple people are having the problem, it might be an  issue with the bootstrap.  Best thing to do is to get rid of the bootstrap and sync manually from 0.  I'm unsure if the problem will be fixed by the time you sync normally... so if you don't want to waste time .. start over with a new data directory (make sure you backup wallet.dat) , and start syncing from 0 without the bootstrap

You can always dumpprivkey from your verge address through the debug console .. and you can then go download the electrum wallet or another verge wallet.. and import your private key there.. if you can't wait a few days to sync.

If you do what I said initially.. and start syncing from 0... you don't need to be sync'd to get your private key

**Comment by jrsikors** [comment]
there's a new version of the blockchain you can try out -- no promises it works but i'm testing it now:
https://verge-blockchain.com/blockchain/Wallet_v4.x_Verge-Blockchain_2018-March-28.zip

there might have been a problem with the MArch 26th copy

**Comment by jrsikors** [comment]
closing since this is duplicate, please follow #656 for updates

**Comment by swat69** [comment]
26, 27, 28 is broken.
analyzing...
