### ISSUE TITLE
Not all transactions visible in Wallet

### ISSUE THREAD

**Issue by jovana** [vergecurrency/VERGE#66]
I have a strange problem on the Verge wallet. I have made two transactions (to the same address) only one is showing up. Blockchain gives the correct information.

Is this a know bug in the wallet? Please let me know if you need any information from my side.

**Comment by justinvforvendetta** [comment]
no this isn't a known bug. do you have your wallet locked? it sounds like you've locked the wallet.

**Comment by jovana** [comment]
Thanks for your update. No wallet is not locked. Buy why is only one transaction visable (100xvg) and not two? https://verge-blockchain.info/address/DPoSh9cYxFaXVAYugZuSMCMdbTeSb5kXSG

**Comment by fireman50** [comment]
Did you figure this out?

**Comment by jovana** [comment]
Yes I have find it! wallet.dat seems to be corrupted. I have deleted and import private keys using command line. After entering the command it takes forever (and your computer is taking off on the cpu load). But the most important I can access my balance againe.
