### ISSUE TITLE
Debian9/Ubuntu17: Wallet not compiling

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#660]
checking for exit in -lboost_system... no
checking for exit in -lboost_system... (cached) no
checking for exit in -lboost_system... (cached) no

configure: error: Could not link against boost_system !
Using Berkeley Generic...
make: *** No targets specified and no makefile found.  Stop.
Compile fail not VERGE-qt present

*** after it downloads the blockchain & inflates ***

go.sh: 263: go.sh: VERGE-qt: not found

Not a desktop version of linux so VERGEd is all I care about.

I've tried both methods listed here.
https://github.com/vergecurrency/VERGE/blob/master/doc/build-verge-linux.md

Operating System: Debian 9 Stretch 64bit

**Comment by justinvforvendetta** [comment]
hmm, what version of boost do you have?

**Comment by Positivism** [comment]
No.

**Comment by justinvforvendetta** [comment]
so the script needs work. from the root verge dir, you should be able to just ./autogen.sh && ./configure && make

**Comment by Positivism** [comment]
I have also tried that, I received the same error. (configure: error: Could not link against boost_system)
I've even tried specifying the boost dir manually.

**Comment by Positivism** [comment]
./configure --with-boost-libdir=/usr/lib/x86_64-linux-gnu

Ref to manually specifying the boost dir ^
Tried this to no avail.
Checked the directory myself and boost IS there, all 8 billion files.

**Comment by Positivism** [comment]
Also not working on Ubuntu 17 x64
Ubuntu error: configure: error: No working boost sleep implementation found.

**Comment by Positivism** [comment]
Libcap issues with Fedora 27.
configure: error: libcap not found

# yum install libpcap-devel
Last metadata expiration check: 0:12:05 ago on Fri 30 Mar 2018 12:40:10 AM UTC.
Package libpcap-devel-14:1.8.1-6.fc27.x86_64 is already installed, skipping.

Verge really hates anything linux

**Comment by justinvforvendetta** [comment]
weird, i have 0 issues compiling on fedora27, ubuntu 16 and 17... 

try

`sudo apt-get install libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev`

**Comment by Positivism** [comment]
Ubuntu 16 it's compiling right now without issue as of yet and I'm rather excited! I already killed my Ubuntu 17 instance and I can't stand Fedora so killed it as well.

**Comment by justinvforvendetta** [comment]
i just tried compiling on zesty and it went thru just fine

**Comment by justinvforvendetta** [comment]
yeah i used to prefer mint and arch, but since ubuntu 16 and 17 ive actually started growing fond of ubuntu.

**Comment by Positivism** [comment]
<img width="393" alt="screen shot 2018-03-29 at 9 09 46 pm" src="https://user-images.githubusercontent.com/35063339/38120260-94564d92-3395-11e8-8bc7-76a9091875ac.png">
Could it be... Ubuntu 16 the magic distro.

**Comment by Positivism** [comment]
Arch and debian fan myself, Ubuntu just isn't my cup of coffee but it's better than fedora by eons, was going to test it with cent but ubuntu is being flawless still, why ruin a good thing.

**Comment by justinvforvendetta** [comment]
dude, i hate centos. its so picky. i feel like the only people that like it are the 65+ grump old school unix guys... lol

**Comment by Positivism** [comment]
Every-time I type yum I wonder what is even tasty.
<img width="678" alt="screen shot 2018-03-29 at 9 16 30 pm" src="https://user-images.githubusercontent.com/35063339/38120426-c904bb2c-3396-11e8-831b-2b33e1f8677a.png">
Where art thee checksums!

**Comment by justinvforvendetta** [comment]
blockchain data needs twerk. compiled though right?

**Comment by Positivism** [comment]
<img width="633" alt="screen shot 2018-03-29 at 9 43 14 pm" src="https://user-images.githubusercontent.com/35063339/38120952-38c3142e-339a-11e8-9ab0-d92083664c4e.png">
Yep, waiting for the blockchain to load up!

**Comment by Positivism** [comment]
<img width="319" alt="screen shot 2018-03-29 at 9 44 17 pm" src="https://user-images.githubusercontent.com/35063339/38120977-5d7e1b9c-339a-11e8-84eb-5951f0e5ee6a.png">
Did get this just fyi. Seems fine though.

**Comment by Positivism** [comment]
Getting RPC commands through, working great, thanks justin!

**Comment by justinvforvendetta** [comment]
hmm im still wondering what the issue you had on fedora27 is from though..

**Comment by Positivism** [comment]
I'll throw up a fedora instance in a few hours and try again; tons of deps were missing even before I ran into the error.

**Comment by Positivism** [comment]
Someone figure out why boost is acting like x86 on a mips toaster for debian. Thanks.

**Comment by jrsikors** [comment]
I'm kicking @swat69 over here to this thread.  reposting his info and log attachment.

> Debian 8, 9:
> 
> checking whether the Boost::System library is available... yes
> checking for exit in -lboost_system... no
> checking for exit in -lboost_system... (cached) no
> checking for exit in -lboost_system... (cached) no
> configure: error: Could not link against boost_system !
[config.log](https://github.com/vergecurrency/VERGE/files/1865530/config.log)

**Comment by jrsikors** [comment]
moving comment from @SJablonska on another issue over here.

> Indeed, installing on Stretch takes a bit of tinkering. Try this:
> 
> ~$: wget -O boost_1_58_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz/download
> ~$: tar xzvf boost_1_58_0.tar.gz
> ~$: cd boost_1_58_0/
> ~$: ./bootstrap.sh --prefix=/usr/
> ~$: ./b2
> ~$: sudo ./b2 install

**Comment by swat69** [comment]
I tried boost 1.5.8, same error

**Comment by Positivism** [comment]
Did you manually tarball it?

**Comment by swat69** [comment]
yes ./configure --with-boost-libdir=
or what do you mean?

**Comment by swat69** [comment]
manually wget&tar boost.
I just replaced configure with a version from 23th Jan, working, compiled with default boost 1.62!
new VERGEd is up and running.

**Comment by swat69** [comment]
Debian 9.4

**Comment by Positivism** [comment]
86 or 64

**Comment by swat69** [comment]
64

**Comment by Positivism** [comment]
Just have to throw back the old config for debian and put the manual tar commands in the compilation processes, I'll throw up a pull request probably later today. Thanks @swat69 for confirming.

**Comment by Serpent6877** [comment]
Ubuntu: 17.10

configure: error: No working boost sleep implementation found.

ii  libboost1.62-dev:amd64                 1.62.0+dfsg-4build3                      amd64        Boost C++ Libraries development files
ii  libboost1.62-tools-dev                 1.62.0+dfsg-4build3                      amd64        Boost C++ Libraries development tools

**Comment by Positivism** [comment]
Also had that error when I attempted to compile with the previous release on Ubuntu 17.10

**Comment by Serpent6877** [comment]
@swat69 This looks to be the fix on my Ubuntu 17.10. 

Thanks!

**Comment by swat69** [comment]
@jrsikors 
shouldn't this be ?
* renamed to: Debian9/Ubuntu17: Wallet not compiling
* flagged as a bug

**Comment by michpiatek** [comment]
Fixed with latest push. Tested on Ubuntu 17.10 with boost 1.62.0.1.

@swat69 reading your comment would save me a lot of time digging through configure.ac lol
