### ISSUE TITLE
[Feature Request] exportstealthaddress

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#662]
importstealthaddress <scan_secret> <spend_secret> [label]
Apparently we have import, yet we can't export?

We need.
exportstealthaddress <stealth address>
returns {"scan_secret":"xxx", "spend_secret":"xxx"}

**Comment by justinvforvendetta** [comment]
thats a solid idea. alot of solid ideas coming from you past few days =]

**Comment by Positivism** [comment]
Thanks <3, tearing through the RPC endlessly.

**Comment by justinvforvendetta** [comment]
i see that lol

**Comment by marpme** [comment]
Also implemented a new RPC command for exporting single stealth addresses with the following standard:

```
{ "scan_secret":"xxx", "spend_secret":"xxx", "label": "xxx" }
```

**Comment by jrsikors** [comment]
merged in
