### ISSUE TITLE
[Feature Request] VERGEd Progress

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#663]
Block index loading progress for VERGEd.
RPC connections can't be made to VERGEd until the blockchain is loaded, simple cout of the block index progress like we have for the qt version would be great.

**Comment by justinvforvendetta** [comment]
yeah agreed, i was thinking about that a couple weeks ago.

**Comment by marpme** [comment]
Pushed a quick PR for this as I had some time for this. Would be great if someone could have a quick view over it.

**Comment by jrsikors** [comment]
thanks @marpme !

**Comment by Positivism** [comment]
Much love.
