### ISSUE TITLE
VERGEd: configure: error: Could not link against boost_system

### ISSUE THREAD

**Issue by swat69** [vergecurrency/VERGE#665]
Debian 8, 9:

checking whether the Boost::System library is available... yes
checking for exit in -lboost_system... no
checking for exit in -lboost_system... (cached) no
checking for exit in -lboost_system... (cached) no
configure: error: Could not link against boost_system !

[config.log](https://github.com/vergecurrency/VERGE/files/1864257/config.log)

**Comment by jrsikors** [comment]
@justinvforvendetta is working with @Positivism  on #660 , similar probs

**Comment by jrsikors** [comment]
kicking you over to #660 , feel free to re-open if this is separate and I'm wrong :heart: 

I reposted your info over there tho
