### ISSUE TITLE
[Semantical Question] Stealth

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#667]
It's impossible to create an account with multiple stealth addresses.

Can anyone confirm this?

**Comment by justinvforvendetta** [comment]
clarify "account"..

**Comment by Positivism** [comment]
getaddressesbyaccount | <account> | Returns the list of addresses for the given account.

Example.

**Comment by Positivism** [comment]
A single account can have multiple addresses.
For example assuming there was no stealth, one would typically create a separate account for something like donations, they would generate an address for each donator under a single account, that way you can keep track of the funds in an account with multiple addresses, and send from just those addresses. sendfromaccount <account>

**Comment by justinvforvendetta** [comment]
you can generate several stealth addresses within the wallet. for instance, "stealth 1" is incoming funds from mining, "stealth 2" is donations, etc... i hope that answers your question. personally i'd never rely on the account portion, as pulling from each address directly is the best way to get the most accuracy

**Comment by justinvforvendetta** [comment]
ah, i think you're basically wondering if we can make a getstealthaddressesbyaccount and have it return all known children of that stealth address?

**Comment by Positivism** [comment]
Essentially.

**Comment by Positivism** [comment]
Yey hierarchical data structures and recursive calls ;>

**Comment by Positivism** [comment]
Now that I think about it I could probably code something that does that with multiple RPC calls, it would probably result in more fees with things like sending though.

**Comment by justinvforvendetta** [comment]
well internal movement doesn't have a fee, like transactions account to account

**Comment by Positivism** [comment]
Right but using move gets messy very quickly, especially since each stealth address is an account.

**Comment by Positivism** [comment]
Guess looping through each account and internally moving it as needed could work for fee issues.
Looks like I'll be implementing surface layer calls for this one.

**Comment by justinvforvendetta** [comment]
lets keep this open

**Comment by Positivism** [comment]
Ah, since you reopened it.
move will only affect the balance of the account.

Lets say.
Account1: 10 XVG
Account2: 10 XVG

Then you preform:
move account1 account2 5

getbalance account1
// returns Account1: 15 XVG

getbalance account2
// returns Account2: 5 XVG

So you would THINK the following would work.
sendfrom account1 <justin's address> 15

But negative, it would result in not enough funds when you attempted the transfer.
The only possible way todo this is to reassign the addresses per account.

I've confirmed all this.

**Comment by justinvforvendetta** [comment]
bitcoin removed its internal accounting, because of these exact reasons, but i think we should keep ours and just revamp it.. would be alot easier for platform integration, like the discord bot/etc..

**Comment by Positivism** [comment]
If you implement this

**Comment by Positivism** [comment]
If you wanted to completely revamp it, you would need to create a new hierarchy and reimplement move to automatically setaccount recursively.

Even if you did this, the probably is the amount of each address.
If you wanted to send 100 XVG but you account had 99.9 and your other had 99.9 each having one address (singularity plays no factor, multiple address per account would still result in this issue to a lesser scale), the only way you can send from acc1 would be to:
 transfer the entirety to one account by setaccount (since there is only that address you would be forced  to move the entirety)
 send the transaction
then either:
have the sendback to account2
OR
reassign the address to the former account via setacc after transacting

The only (and preferred if possible) alternative would be to somehow allow sending from multiple accounts. aka sendfrommany

**Comment by marpme** [comment]
As this seems to be a lot of work to revamp this part of accounting internals. I would like to ask, if this would really be a use case. 

As I understood, you would split your incomes onto multiple accounts with multiple address. So that you have some kind of overview of what incomes you have. And afterwards you still want to spend your money from the given accounts with the certain addresses. 

To me, honestly, it seems to be a bit off the real world use case. As you are splitting the money for their certain usage. Like holding money, daily spents to control yourself and your accounting environment. And moving around the money internally is part of the daily accounting management.

Please correct me, if I have a completely broken vision on this. :D

**Comment by Positivism** [comment]
@marpme You cannot use move with the current accounting system without some unintended side-effects.

Move only changes the reply from getbalance, not much else.
Each account still has the addresses tethered to it with the same amounts of coin in each and when rpc command sendfrom is used on an account whose funds were move'd, the amount specified will still go through regardless of the current balance of the account set internally causing the balance todo things such as go negative for that account.

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
