### ISSUE TITLE
walletpassphrase unlock not working

### ISSUE THREAD

**Issue by SJablonska** [vergecurrency/VERGE#669]
Hi,
System: Debian Stretch, latest updates
Verge: v4.0.1.0-2610206-funky-beta

I am trying to unlock the wallet in the console with a password similar as this one, 9HeSb-CA*\(k$'Re?Q4@]{.,}2j"c{mBL6g2t6o8)<n.

The password works as I can unlock the wallet 'for minting only' in the GUI. However, for a dumpprivkey, the console does not accept:
- walletpassphrase '9HeSb-CA*\(k$'Re?Q4@]{.,}2j"c{mBL6g2t6o8)<n' 900 false;
- walletpassphrase "9HeSb-CA*\(k$'Re?Q4@]{.,}2j"c{mBL6g2t6o8)<n" 900 false;

or other combinations ("'; '", etc.), 

The standard linux bash escaping:
-walletpassphrase "\\"9HeSb-CA*\(k$'Re?Q4@]{.,}2j"c{mBL6g2t6o8)<n\\"" 900 false;

returns error 14: the password is incorrect (, but the password works as I can unlock the wallet 'for minting only' in the GUI).

What is strange is that typing " or ' in the console results in a space, but does NOT show the double or single quote character.

**Comment by jrsikors** [comment]
When did you initially create the wallet.dat .. in an older version of QT?  There have been some people who experience these issues.

The workaround is to change your passphrase in the GUI .. and then it will work fine in walletpassphrase.  Didn't happen to many people, but did to some.

Your passphrase contains a single quote ?  I saw this:
https://bitcointalk.org/index.php?topic=2060858.0

> If you password contains double quotes, then surrounding your password with double quotes is not going to help as the string parse will only read the string surrounded by the first double quote. To have such special characters in your passphrase, you will need to surround your entire passphrase string with single quotes. However if you have single quotes in your password, you will need to escape those single quotes with \'

**Comment by jrsikors** [comment]
So i would try:
  1)  use Single Quotes to wrap the walletpassphrase .. not double
  2)  try escaping the single quote in the passphrase using above method

If that doesn't work -- might recommend what i initially suggested, and changing your passphrase in the GUI.

You seem pretty intelligent so I feel weird saying this , but don't want to assume -- but make sure you got good backups before messing with all this :smile:

**Comment by SJablonska** [comment]
Wallet was created WITH the new version.
Hi, tried everything already.

Thanks for the help and for the extra warning :-)

**Comment by Positivism** [comment]
I can't even get verge to compile on debian 9, you didn't get a boost linking error @SJablonska ?

**Comment by Positivism** [comment]
Also did you try changing the password in the GUI to something without quotes?

**Comment by jrsikors** [comment]
Yeah -- if it unlocks in the GUI -- you should be able to change it in the GUI.

You would expect it to work in the console as well... but hasn't been the case for some lucky people
If your passsphrase is:
9HeSb-CA*(k$'Re?Q4@]{.,}2j"c{mBL6g2t6o8)<n

in the debug console the command would be exactly
walletpassphrase '9HeSb-CA*(k$\'Re?Q4@]{.,}2j"c{mBL6g2t6o8)<n' 600

~notice the \ in front of the '  after the $
~i couldnt find if you need to escape the double quotes .. would try with both
~notice ending with 600 and don't include false or ;

Just see what happens without the extra "false" and ";' at the end.  I've found some commands in the debug console don't work EXACTLY like they advertise they should... so let's keep it as simple as possible

**Comment by SJablonska** [comment]
Indeed, installing on Stretch takes a bit of tinkering. Try this:

wget -O boost_1_58_0.tar.gz http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz/download
tar xzvf boost_1_58_0.tar.gz
cd boost_1_58_0/
./bootstrap.sh --prefix=/usr/
./b2
sudo ./b2 install

**Comment by SJablonska** [comment]
KISS probably means I end up changing the passwords :-)

**Comment by SJablonska** [comment]
https://github.com/Positivism

**Comment by SJablonska** [comment]
> Positivism commented 40 minutes ago
> Also did you try changing the password in the GUI to something without quotes?

**Comment by SJablonska** [comment]
> Positivism an hour ago 
> I can't even get verge to compile on debian 9, you didn't get a boost linking error @SJablonska ?

How do you add the @SJablonska?

**Comment by jrsikors** [comment]
Just type @ and then their username like you did

once you type @ and a few letters, it should let you select the username

**Comment by SJablonska** [comment]
Thx @jrsikors

**Comment by jrsikors** [comment]
No prob.. well try to change your password in the GUI, then go try to do the walletpassphrase in the console, and let us know the results please !

I'm assuming your other issue about TOR is fixed now ? #648  ?  Sorry I tried to post on Discord for people to come help, no one did :(

**Comment by SJablonska** [comment]
Already did. That works (no special characters). Still strange with Verge stressing privacy.

Sorry, that issue can be closed.

**Comment by SJablonska** [comment]
@Positivism, let me know if the installation works

**Comment by jrsikors** [comment]
I'll try to play around with a passphrase using all kinds of special characters and see if i can duplicate it.  I agree it should work in theory.

I also wonder if you just had one of those weird "needed to change your password in the GUI first" problems... and now you could go back to your char with special characters.

**Comment by SJablonska** [comment]
From what I am seeing now I have a feeling it has to with the fact that I am having multiple repetitions of multiple special characters.
So, I am guessing that the escape sequence should also be repeated. Tried a bit, but did not succeed yet.

Typically, my passwords are 500 characters long :-)

I will do some more testing tomorrow.

"I also wonder if you just had one of those weird "needed to change your password in the GUI first" problems... and now you could go back to your char with special characters.": 
Interesting one. Will test that also.

Got to go. Enjoy!

**Comment by jrsikors** [comment]
:v:

**Comment by Positivism** [comment]
@SJablonska I'll take a look at your debian boost fix, I really tried to avoid manually tarballing but of course it's the answer. Glad your problem is fixed though, you can close the issue.
