### ISSUE TITLE
Arch Linux wallet's boost lib is too low

### ISSUE THREAD

**Issue by frostRed** [vergecurrency/VERGE#67]
After download the wallet and run it, I get this ERROR.
```
./VERGE-qt: error while loading shared libraries: libboost_system.so.1.60.0: cannot open shared object file: No such file or directory
```

I find boost I installed was 1.64.0

**Comment by justinvforvendetta** [comment]
ah for the binary. so purge your 1.64 and install 1.60 or compile it fresh. the go bash script should work.
