### ISSUE TITLE
[Question] Blockchain Index

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#670]
Is blockchain loading restricted to a single core?
<img width="452" alt="screen shot 2018-04-01 at 2 16 24 pm" src="https://user-images.githubusercontent.com/35063339/38176135-7cea6eee-35b7-11e8-9d66-75eefa3aedb5.png">

If so we should fix this.

**Comment by Positivism** [comment]
These labels are quite annoying, we need action not labels.

**Comment by justinvforvendetta** [comment]
did you make a pull request? lol

**Comment by Positivism** [comment]
Nou

**Comment by jrsikors** [comment]
is this resolved now after pull #706  ?

**Comment by Positivism** [comment]
@jrsikors That merge adds a printf for the load progress, not multi-thread/core support.

**Comment by justinvforvendetta** [comment]
we're working on a total rebase in another repository right now, and it will have multi core/thread support, as well as a slew of new rpc commands ;]

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
