### ISSUE TITLE
Stealth Transactions not sending properly

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#671]
I've been tearing through my code for hours when I decided todo it manually and get the same issue.

When I run:
getinfo() ["paytxfee"]=> float(0.1)
getbalance() [""] => float(0.3)

sendtostealthaddress('#stealth address here#', 0.2); // error, does not send

So I thought maybe it's something todo with fees, even though they're set at 0.1.

sendtostealthaddress('# stealth address here#', 0.1); // sends, hooray ! Why? No idea.

Then I do:
getbalance() [""] => float(0)

https://verge-blockchain.info/tx/38d905396a69f4b6d3512a145709618503b24c707a8ac8e82d09d9e92e83a915

If someone could explain this, that would be awesome.

**Comment by Positivism** [comment]
I deleted my wallet.dat and let it generate a new wallet and was still able to replicate this.

**Comment by justinvforvendetta** [comment]
Transaction hash | 38d905396a69f4b6d3512a145709618503b24c707a8ac8e82d09d9e92e83a915
-- | --
Block | 2,000,361
Block hash | b164eca7e367aeeed0f88dfcdf746c377c429f981fd8a12b51881cd1f425efba
Time | Sunday, April 1, 2018 2:54:42 PM
Total sent | 0.20000000 / $0.009
Fee | 0.10000000 / $0.004
Confirmations | 39
 
Inputs

 DUH3NfGQNnEPXtiWiBt7doz3a1brBz1ybe (0.30000000 / $0.013)
 
Outputs

 Non-standard transactions (0.10000000 / $0.004)
 D6mCkGVGaZcaBLh3y2e1oibnBhvUvqT7gW (0.10000000 / $0.004)

**Comment by Positivism** [comment]
.3 Input
Two .1 Outputs

Is one not the miners fee?

**Comment by Positivism** [comment]
Total sent | 0.20000000 / $0.009
-- | --

Never got the other .1 anywhere so it could not have been the sendback.
I only sent .1

**Comment by justinvforvendetta** [comment]
what was the balance when you started? the remaining balance should have moved to a change address, then fee, then the address you sent to..

**Comment by Positivism** [comment]
.3 When I started.

**Comment by justinvforvendetta** [comment]
in just a single input?

**Comment by Positivism** [comment]
I did listaccounts and all were 0 balance, and yes, single input.

**Comment by Positivism** [comment]
array(1) {
  [""]=>
  float(0.3)
}

Just tried sending .2 to a stealth address and it errors (nothing helpful).
I tried sending .2 to a normal account, ( right after it errors attempting to send to a stealth ), and it sent fine.

**Comment by Positivism** [comment]
RPC->__call('sendtostealthad...', Array)
Is whats thrown as the error.

**Comment by justinvforvendetta** [comment]
ill make this a bug issue, and try to reproduce it tmrw

**Comment by Positivism** [comment]
Alright, incredibly odd this started happening out of nowhere.

**Comment by Positivism** [comment]
I'm going to throw up another server and see if something simply got corrupted in the blockchain or something.

**Comment by justinvforvendetta** [comment]
ok. also the proshashing verge explorer has a bit more detail for transactions
https://prohashing.com/explorer/Verge/

**Comment by Positivism** [comment]
New server is still syncing.

Old server the problem originated on: error: {"code":-4,"message":"Error: Transaction creation failed  "}

**Comment by Positivism** [comment]
Brand new server

```
root@ubuntu:~# VERGEd getbalance
0.30000000

root@ubuntu:~# VERGEd sendtostealthaddress #snipped address# 0.2
error: {"code":-4,"message":"Error: Transaction creation failed  "}

```

**Comment by Positivism** [comment]
[https://verge-blockchain.info/api/getrawtransaction?txid=5a3a5d5b995fb23b88131aa70ff7f17923e4e01468b3ff60a36f6d5e641497d8&decrypt=1](url)
`"value": 0.1,
      "n": 0,
      "scriptPubKey": {
        "asm": "OP_RETURN 033dded0f33d9f6d2a513888a8ca6cd7e76e1b9526599e1817faba7ae1284e0d00",
        "hex": "6a21033dded0f33d9f6d2a513888a8ca6cd7e76e1b9526599e1817faba7ae1284e0d00",
        "type": "nonstandard"
      }`

0.1 Keeps going to a non-standard for some apparent reason.
If I send an amount that's the entire wallet (excluding .1 miner fee) then the transaction fails.
If I send an amount that's a portion of the wallet then the transaction goes through but .1 goes to nonstandard for some reason or another.

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
