### ISSUE TITLE
Verge wallet TORdroid I can't send my #XVG, lost account

### ISSUE THREAD

**Issue by cbrexx** [vergecurrency/VERGE#672]
## Verge wallet TORdroid v.1.1. I can't send my #XVG, wrong password, lost account

Hi everyone
In January I sent my #XVG on the mobile wallet TORdroid - I created my account. I did not have any other wallet.
Now, when I tried to send my money to another address, I could not do it, reason: wrong password. The password is certainly correct but it does not work. I made the account restoration and never went back to the previous address, I do not have access to the funds. I did not backup because the wallet does not have this option. I do not have a private key

I am looking for a possible solution
Are files stored in the android development system in which passwords can be saved?
Is there any way to regain access to my account?

Please help
![screenshot_2018-03-31-22-54-45](https://user-images.githubusercontent.com/38040890/38252838-6ebc6f80-3755-11e8-8b6b-b7e744a7f6ad.png)
![screenshot_2018-03-31-22-54-54](https://user-images.githubusercontent.com/38040890/38252840-6ef99c66-3755-11e8-9d1e-f7f7c7428d5d.png)
![screenshot_2018-04-01-10-12-14](https://user-images.githubusercontent.com/38040890/38252841-6f1a5064-3755-11e8-8643-c6d994539ebe.png)

**Comment by jrsikors** [comment]
We can leave this issue open for a few days in case anyone happens to come by it and have any ideas -- but this 'issues page' is primarily for the Verge-QT wallet.

I think you'd have better success / bigger audience on Reddit or the Discord/Telegram channels.  If you haven't already, I would highly recommend posting there as well.

**Comment by justinvforvendetta** [comment]
when you do a restore, you need to check the box as well.

**Comment by vyoufinder** [comment]
As far as I can tell.. XVG Verge is working as developed.  I recorded the entire process when I signed up and was never issued nor asked to create a password.  So I don't have one.  When I go to send coins to someone, I am asked for a password and then the Verge app sugggests that "if the problem persists, try restoring your wallet." I could restore my wallet, but so far every single forum post that I see from everyone having the exact same problem who don't have a password becaue they never got one restored their wallet only to lose their coins.  I have not seen anyone ever able to send any XVG coins or restore their wallet or do anything other than give money to XVG Verge "developers" in the form of "lost" password that they never had.  It's a huge scam as far as I can tell.  A good reason not to let your friends buy XVG Verge.

If I can't find a way to get a password issued, then I will lose my coind by restoring my wallet, record the whole thing, then combine it with the video I made while signing up, and expose the fraud that is XVG Verge.

**Comment by justinvforvendetta** [comment]
@vyoufinder you must be very confused. the ios app gives you a password option. this repository let's you create one if you wish, and its simply not possible for it to create one by itself lol

**Comment by vyoufinder** [comment]
Can you explain what happened using the old app, where users were not
required to create a password, such as in this video:
https://www.youtube.com/watch?v=Ts9CXFYXu0c

I also recorded the entire process when I created my wallet, and is the
same as in that video.  I have made no mention of ios, though I do
understand that it is much easier to just send a snotty response to  a
question that  nobody has asked.

**Comment by vyoufinder** [comment]
No; I am not confused, but it seems that you are.  I am not using ios.
Yes, it is not possible now, but at the time I installed, creating a
password was an option.  It seems like you don't want to help.  Rather, you
want ot try and feel suyperior by assuming I am an idiot, so you can just
ignore me instead.I don't need ot waste any more time with someone who
doesn't even understand my request.

**Comment by justinvforvendetta** [comment]
what I'm saying is the wallet can not create or ask for a password by itself without being instructed to, the mechanism just doesn't exist.
