### ISSUE TITLE
Electrum 2.4 wallet keeps syncing on MacOS high sierra (tried several servers already)

### ISSUE THREAD

**Issue by JoopM** [vergecurrency/VERGE#673]
Hi,

Tried several servers but wallet doesn't connect and keeps on syncing. Never had this problem before. Thoughts on this problem anyone?

**Comment by jrsikors** [comment]
What servers are in your list under network?

**Comment by JoopM** [comment]
The following servers are on the list:

46.163.118.201
46.163.119.40
83.169.38.218
e1.verge-electrum.com
e2.verge-electrum.com
e3.verge-electrum.com
elec2.verge-blockchain.com
electrum-verge.xyz
electrum-xvg.party
electrum-xvg.stream

**Comment by Max7788** [comment]
Hello, I have a problem with the server too. Help.

**Comment by justinvforvendetta** [comment]
I use the tor electrum, working fine

**Comment by jrsikors** [comment]
Is "Auto Connect" checked or unchecked?

I dont know what all the good electrum servers are @justinvforvendetta ,, i've just been telling people to only use:
e1.verge-electrum.com
e2.verge-electrum.com
e3.verge-electrum.com

and get rid of everything else ?

**Comment by Max7788** [comment]
No connection.

**Comment by jrsikors** [comment]
Step 1) Close down Electrum wallet
Step 2) Browse to where your Electrum 'installation' is
Step 3) Go into the Lib folder
Step 4) Open network.py in notepad or textpad , some kind of text editor
Step 5)
Replace this chunk of code:

DEFAULT_SERVERS = {
'electrum-verge.xyz':{'t':'50001', 's':'50002'},
'electrum-xvg.stream':{'t':'50001', 's':'50002'},
'electrum-xvg.party':{'t':'50001', 's':'50002'}
}
With this chunk of code:

DEFAULT_SERVERS = {
'e1.verge-electrum.com':{'t':'50001', 's':'50002'},
'e2.verge-electrum.com':{'t':'50001', 's':'50002'},
'e3.verge-electrum.com':{'t':'50001', 's':'50002'}
}
step 6) Open Electrum
step 7) Go to tools -> network
step 8) Make sure "Auto-connect" is checked, and the 3 electrum servers are listed:
e1.verge-electrum.com
e2.verge-electrum.com
e3.verge-electrum.com

**Comment by jrsikors** [comment]
But actually now that I try those 3 servers, I'm not getting a good connection either.  They might just be overwhelmed at the moment.  I'll keep looking into it.

**Comment by jrsikors** [comment]
In the meantime -- you might want to consider using the Electrum XVG Tor wallet.. which is better supported.  Regular Electrum XVG wallet is going to be removed completely soon:

https://github.com/vergecurrency/electrum-xvg-tor/releases

**Comment by jrsikors** [comment]
slight correction to my steps above.  Leave "Auto Connect' UNchecked... don't check it.

I'mm getting a decent connection now on regular electrum XVG with those 3 servers

**Comment by WDMi** [comment]
Thanks. Not getting any respons though. I use the Mac 2.4 electrum and I am pretty sure I have always used SSL 50003 icw the servers you mention. It just seems like I can not change the SSL, every time I click ok it jumps back to 50002. It is not a new wallet I have always been using it without any troubles.

**Comment by jrsikors** [comment]
is your Proxy set to NONE if you are trying port 50003?

**Comment by jrsikors** [comment]
another fix i saw for Macs:
Click on Network -> use this server -> e3.verge-electrum.com, Port 5001, uncheck SSL

**Comment by WDMi** [comment]
F*ck yes man! :) You are the man!! Thanks a lot!

**Comment by jrsikors** [comment]
which one worked, so I know why I am the man.. was it the proxy or the uncheck SSL? :smile: 

you are welcome, enjoy !

**Comment by kijuy** [comment]
should I set fee to 2, or just default 1?

**Comment by jrsikors** [comment]
saw this one @kijuy ... regarding fees
https://github.com/vergecurrency/electrum-xvg-tor/issues/20

**Comment by kijuy** [comment]
finally, sent 1000 xvg with 4 xvg fees... 1,2,3 not working, RX rejected

**Comment by teti2347** [comment]
@kijuy did you get charged the attempts with the 1st, 2nd, and 3rd attempt?  Im having 'TX error' issues and dont want to start playing a guessing game and be charged for it.

**Comment by jrsikors** [comment]
The TXs get rejected if you don’t put a valid fee.. so you should be fine

**Comment by teti2347** [comment]
So is it really a guesiing game of starting at 1 and just increasing?  Anyone have any specifics on other transaction amounts so I dont have to guess? LOL! Thanks!
