### ISSUE TITLE
Wallet still says "our of sync" even though its finished syncing with the network

### ISSUE THREAD

**Issue by piphoto23** [vergecurrency/VERGE#674]
When I open my wallet I'll see the "synchronizing with network" bar at the bottom, after that's done synching and the bar goes away my wallet still says "out of sync"  I have the verge desktop wallet for OSx version 4.0.1.0

**Comment by jrsikors** [comment]
Can you go to help -> debug ... please post a screenshot of the information tab

**Comment by piphoto23** [comment]
<img width="719" alt="screen shot 2018-04-03 at 6 01 05 pm" src="https://user-images.githubusercontent.com/34901790/38278198-099714fc-3769-11e8-948d-25f2e1660be9.png">

**Comment by jrsikors** [comment]
Is the “last block time” moving forward?

**Comment by jrsikors** [comment]
you good to go?
