### ISSUE TITLE
[Bug] Transaction fees

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#675]
<img width="503" alt="screen shot 2018-04-03 at 5 00 33 pm" src="https://user-images.githubusercontent.com/35063339/38275854-3597d3aa-3761-11e8-8044-fab9965527b2.png">

Even when setting fees manually I'll get the occasional one of these.

**Comment by Positivism** [comment]
Sent and the transaction fee indeed was .1, however the flag for that prompt is raised and you have to change the amount sent appropriately.

**Comment by 7urboPitt** [comment]
exact same bug here when i send the minimum robery is 0.1 verge , when i alter the transaction fee in any way from options it raise the fee to 0.3 like the mafia or a ordinary bank service. WTF is this now again. and it loads up like shit.

**Comment by 7urboPitt** [comment]
How does this suspicious charging system work ? Its playing around with my KW/hours bug or whats going on here, no ways investments is secure with this epic fail of fund security. Why is the fee system so unclear to the user ?

**Comment by jrsikors** [comment]
Might be for bitcoin, but same concepts apply for Verge.

https://en.bitcoin.it/wiki/Transaction_fees:

Also this is another good one:
https://news.bitcoin.com/how-to-calculate-bitcoin-transaction-fees-when-youre-in-a-hurry/

**Comment by Positivism** [comment]
Nothing todo with bitcoin @jrsikors, for some reason we cannot set fees below the threshold set by the client (not the 0.1 threshold), and occasionally, the change on certain addresses will be added to the transaction fee whilst we have the inability to change it.

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
