### ISSUE TITLE
4.0clearnet branch compatible with Stealth transactions?

### ISSUE THREAD

**Issue by oliverw** [vergecurrency/verge#677]
Is the 4.0clearnet branch compatible with Stealth transactions or 4.01 in general? Our pool has begun to produce nothing but orphans: https://coinfoundry.org/pool/xvg2

**Comment by justinvforvendetta** [comment]
@oliverw please pull the latest changes, we had a small timewarp attack, but we've patched it for now, and are working on a more sophisticated new block check.

**Comment by oliverw** [comment]
Already one.

**Comment by justinvforvendetta** [comment]
excellent, thanks. which pool are you, so i can let people know you've updated?

**Comment by oliverw** [comment]
Coinfoundry - https://coinfoundry.org/pool/xvg2, https://coinfoundry.org/pool/xvg1
