### ISSUE TITLE
Twitter bot to automatically ban scammers

### ISSUE THREAD

**Issue by Sach97** [vergecurrency/VERGE#678]
Hi guys I know this is not the appropriate repo but the official Twitter 
have scammers in response messages and we should make a bot to automatically ban them. And by the way make some communication about it. Please @justinvforvendetta open a repo for it, I'm willing to help.

![capture](https://user-images.githubusercontent.com/18029834/38323944-13d50a6a-383f-11e8-856c-9215b18ee5ea.PNG)

**Comment by justinvforvendetta** [comment]
we do auto ban them already. they just make new accounts. we have about 450+ of them blocked right now. if you can come up with a better solution, im all ears. right now all i can think of is twitter having some sort of human verification for new accounts.
