### ISSUE TITLE
VERGEd has no output to paste it into VERGE.conf

### ISSUE THREAD

**Issue by itinance** [vergecurrency/VERGE#68]
The README has following lines:

```
Paste the output from the VERGEd command into the VERGE.conf like this: (It is recommended to change the password to something unique.)

rpcuser=vergerpcusername
rpcpassword=85CpSuCNvDcYsdQU8w621mkQqJAimSQwCSJL5dPT9wQX
```

I'm wondering that launching the command VERGEd nothing prints out. It  is running without any output.

I've setup Verge on Ubuntu 16.04 and want to mine.

What have i missed?

**Comment by justinvforvendetta** [comment]
if you ran the go script, you already have a .conf file

also, verged does not have output unless you send it rpc commands once it is running. ./VERGEd getinfo (returns network info) ./VERGEd getbalance (returns wallet balance)
