### ISSUE TITLE
not finish the message "Sychronizing with network"

### ISSUE THREAD

**Issue by lsbforever** [vergecurrency/VERGE#681]
# Issue Template

## Context
Whenever I open my osX tor wallet I see the message "Synchronizing with network" which is located bottom of the wallet page.
It is not finished even though I turn on my macbook pro for a day.

I am uploading the screen shot regarding to this issues.

## Prerequisites

* [ ] Are you running the latest version?
yes. 4.0.1.0
## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:v4.0.1.0-e075115-funky-beta
* CPU:2.8 GHz Intel Core i7
![2018-04-05 1 59 51](https://user-images.githubusercontent.com/38093626/38347968-d94eb80a-38d9-11e8-8737-f2af6576ef2c.png)
![2018-04-05 2 00 02](https://user-images.githubusercontent.com/38093626/38347969-d98a0608-38d9-11e8-9bdc-9735fdec9fb1.png)
![2018-04-05 2 01 01](https://user-images.githubusercontent.com/38093626/38347970-d9ae5008-38d9-11e8-880c-7e93510cd156.png)

* GPU:NVIDIA GeForce GT 750M 2 GB
* RAM:16GB 1600 MHz DDR3
* OS:
    - [O ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by Positivism** [comment]
Is the download block count increasing?

**Comment by lsbforever** [comment]
I don't know well but some error messages are shown.

:AskFor tx b66c3f098dd6a5c8de10   1522920322000000 (09:25:22)
CNode::AskFor tx 5452eea279a09a81cc30   1522919365000000 (09:09:25)
CNode::AskFor tx 3752e0e6c9093bde6630   1522919724000000 (09:15:24)
CNode::AskFor tx 1ef6bfed7c70d9db6692   1522919724000000 (09:15:24)
ProcessMessages(23422 bytes)
CNode::AskFor tx d4c7d3dafe5c205228a1   1522918769000000 (08:59:29)
ERROR: FetchInputs() : 1e9bf58b8a mempool Tx prev not found ed877942d4
ignoring large orphan tx (size: 5249, hash: 1e9bf58b8a)
CNode::AskFor tx ef6a784532ac7243bc4c   1522918650000000 (08:57:30)
ProcessMessages(23270 bytes)
ERROR: FetchInputs() : b66c3f098d mempool Tx prev not found 52917d4bc3
stored orphan tx b66c3f098d (mapsz 1175)
CNode::AskFor tx ba685792547c362e9d34   1522920441000000 (09:27:21)
CNode::AskFor tx 1ef6bfed7c70d9db6692   1522919844000000 (09:17:24)
CNode::AskFor tx 3752e0e6c9093bde6630   1522919844000000 (09:17:24)
CNode::AskFor tx 5452eea279a09a81cc30   1522919485000000 (09:11:25)
ProcessMessages(36625 bytes)
![2018-04-05 5 58 37](https://user-images.githubusercontent.com/38093626/38356557-02ca1d66-38fb-11e8-92ac-c638bbf5906d.png)

**Comment by Positivism** [comment]
Hover over the progress bar and move your mouse back and forth to see if the Downloaded: is increasing.

**Comment by lsbforever** [comment]
do you mean this hop message? you can refer to the below pic.
If it is , then not increasing I think so.

![2018-04-05 6 30 09](https://user-images.githubusercontent.com/38093626/38358121-65a05032-38ff-11e8-9136-1e71a66aae8e.png)

**Comment by Positivism** [comment]
Or go back to the debug window and check if it increases.
https://i.gyazo.com/023c5004515f6f871da87a1cf476d5ef.mp4

**Comment by Positivism** [comment]
https://i.gyazo.com/b15772e5a85d220d75f5530a020052ac.mp4
Like this

**Comment by lsbforever** [comment]
no. it is still 1851783. Something is wrong ?

**Comment by Positivism** [comment]
Quite odd, you have no shortage of active connections.
Have you considered downloading the blockchain manually?
Though if it stops syncing this issue needs to remain open.

**Comment by lsbforever** [comment]
I'm sorry but I don't know well how to download the blockchain manually

Could you explain or show me the way how to do, please?

**Comment by lsbforever** [comment]
here you go, Positivism. 
![2018-04-05 7 01 28](https://user-images.githubusercontent.com/38093626/38359603-ceef02c8-3903-11e8-9e1a-f1998d4f877a.png)

**Comment by Positivism** [comment]
Exit Verge.
Grab the blockchain from one of these mirrors.
https://verge-blockchain.com/down
When it's done downloading unzip it.
Open finder and click Go at the top macbar.
Hold down Option and click Library.
From there go to application\ support -> VERGE
Unzip the blockchain contents there.

**Comment by lsbforever** [comment]
this page is right?

 and another question is, what if i use this, my wallet address will be changed?
![2018-04-05 7 06 13](https://user-images.githubusercontent.com/38093626/38360063-7177bc88-3904-11e8-852a-ead7f756725b.png)

**Comment by lsbforever** [comment]
or this is ?
![2018-04-05 7 08 17](https://user-images.githubusercontent.com/38093626/38360297-b7a6a3fe-3904-11e8-8eb2-ab62f33bfb3c.png)

**Comment by Positivism** [comment]
The latter, download server 1, 2, or torrent it.

**Comment by Positivism** [comment]
No your wallet will not be changed.

**Comment by Positivism** [comment]
The one you see on the github is the same one on vergecurrency.com

**Comment by lsbforever** [comment]
OK. Thanks. I am downloading it. Are you one of Verge DEVs?

**Comment by Positivism** [comment]
I mostly complain, find issues, give suggestions, and help whenever possible. 🥇

**Comment by lsbforever** [comment]
Thanks a lot positivism, in positive way. :)

**Comment by Positivism** [comment]
Looks like the correct folder already. Unzip the blockchain into there.

**Comment by Positivism** [comment]
https://i.gyazo.com/ab587c2eb418a93889a9fe1f3833b870.mp4

**Comment by lsbforever** [comment]
OK I've just overwrote now.

**Comment by Positivism** [comment]
Great, now just start up verge as normal.

**Comment by lsbforever** [comment]
Oh. my dear, The wallet has come! Thanks a LOT!

verge forever!!! 

The price will be getting higer and higer!
![Uploading 스크린샷 2018-04-05 오후 7.41.04.png…]()

**Comment by Positivism** [comment]
Yep, if you have any questions feel free to ask.

**Comment by lsbforever** [comment]
I am sorry but may I ask how to turn on and off wraith mode on OsX Tor wallet. I can't find out that option

**Comment by Positivism** [comment]
There is no 'wraith mode', only stealth and non-stealth addresses, when you send to a stealth address a "proxy" address is generated.

**Comment by lsbforever** [comment]
OK. how to use 'stealth and non-stealth" May I know?

**Comment by Positivism** [comment]
Give your stealth address or send to a stealth address, the verge client automatically detects and sends as stealth.

You can not send stealth to a non-stealth address.

**Comment by lsbforever** [comment]
oh.. I got that . Am I right?
![2018-04-05 8 10 57](https://user-images.githubusercontent.com/38093626/38362911-80b64e18-390d-11e8-9e48-d5337c87f021.png)

**Comment by Positivism** [comment]
Right, that's how you generate a stealth address.

**Comment by lsbforever** [comment]
I've just created but I can't recognize which one is stealth address if I don't input the LAbel. Is there any way to check that out?
![2018-04-05 8 14 47](https://user-images.githubusercontent.com/38093626/38363057-26fd4a10-390e-11e8-870d-b5f5f80285d6.png)

**Comment by Positivism** [comment]
stealth->non stealth: It will take funds from your stealth account but it will not send as a stealth transaction, just a normal one.

non-stealth->stealth: Will send as a stealth transaction

stealth->stealth: Will send as a stealth transaction.

**Comment by lsbforever** [comment]
Could you tell me what the "stealth account" is. Is it different from just normal XVG wallet?

**Comment by Positivism** [comment]
Stealth account is the same as a stealth address.

**Comment by lsbforever** [comment]
OK. It will take funds more than non-stealth mode?

**Comment by Positivism** [comment]
No. All are the same.

**Comment by lsbforever** [comment]
I am doing a test with a guy who has the android wallet. but can't send . 
![2018-04-05 8 38 55](https://user-images.githubusercontent.com/38093626/38363929-761a77dc-3911-11e8-8723-34b3fb010264.png)

**Comment by Positivism** [comment]
I've never tried the android wallet, they may or may not support stealth transactions yet. You'll have to ask @justinvforvendetta

**Comment by lsbforever** [comment]
I don't know well how to use DM in this gibhub place. May I ?

**Comment by justinvforvendetta** [comment]
the android wallet has not been updated to support stealth yet, only regular right now. soon we will update it.

**Comment by jrsikors** [comment]
thanks @Positivism for helping him out !

**Comment by lsbforever** [comment]
@justinvforvendetta Thanks for your help me out. Verge Forever!

@Positivism Thanks A LOT!. It couldn't be solved without you.

**Comment by Positivism** [comment]
Yep, don't mention it.
