### ISSUE TITLE
Commit: change AcceptBlock() rules at 2040000

### ISSUE THREAD

**Issue by oliverw** [vergecurrency/VERGE#683]
Does applying this fix require the daemon to resync from scratch or will they carry on with whatever state they had before being shutdown while the attack was going on?

**Comment by jrsikors** [comment]
is your question answered in #679  ?

**Comment by justinvforvendetta** [comment]
you do not need to resync from scratch.

**Comment by coinsmith** [comment]
With the new compile, I'm getting a whole bunch of these, sure this client will sync?

ProcessBlock: ORPHAN BLOCK, prev=000000000033bf18014a
CNode::AskFor block 000000000033bf18014a   0 (00:00:00)
ProcessMessages(319 bytes)
received block 000000000033bf18014a
ProcessBlock: ORPHAN BLOCK, prev=0000000001dea3db597e
CNode::AskFor block 0000000001dea3db597e   0 (00:00:00)
ProcessMessages(55 bytes)
ProcessMessages(320 bytes)
received block 0000000001dea3db597e
ProcessBlock: ORPHAN BLOCK, prev=000000000038f2429bdd
CNode::AskFor block 000000000038f2429bdd   0 (00:00:00)
ProcessMessages(55 bytes)
ProcessMessages(318 bytes)
received block 000000000038f2429bdd
ProcessBlock: ORPHAN BLOCK, prev=0000000001a473b6f104
CNode::AskFor block 0000000001a473b6f104   0 (00:00:00)
