### ISSUE TITLE
Latest compile closing error

### ISSUE THREAD

**Issue by coinsmith** [vergecurrency/VERGE#684]
./VERGEd stop
VERGE server stopping
*********$ VERGEd: /usr/include/boost/thread/pthread/recursive_mutex.hpp:104: boost::recursive_mutex::~recursive_mutex(): Assertion `!pthread_mutex_destroy(&m)' failed.

Repeatable: yes.

Debug seems to close al right.

wallet.dat closed
DBFlush(false) ended              37ms
StopNode()
Flushed 7386 addresses to peers.dat  62ms
Flush(true)
DBFlush(true) ended               0ms
VERGE exited

edit: ubuntu 16.04 64bit amd processor

**Comment by Positivism** [comment]
Replicated this. Same warning upon termination.

**Comment by justinvforvendetta** [comment]
looks like we need to switch some boost code around. will do that next

**Comment by coinsmith** [comment]
Latest ubuntu compile doesn't give the error anymore, I think we can close this. Congrads on the update.
