### ISSUE TITLE
maxdrift fix / fork is implemented wrong

### ISSUE THREAD

**Issue by ocminer** [vergecurrency/VERGE#685]
Your second "fix".. Is still not working at all, the edit you have here:

https://github.com/vergecurrency/VERGE/blob/master/src/main.cpp#L2306-L2321

You also need here:

https://github.com/vergecurrency/VERGE/blob/master/src/main.cpp#L2219

One is for reading blocks from disk e.g. resyncing and the other is for accepting blocks via peers...

**Comment by justinvforvendetta** [comment]
they shouldn't make it to disk if it isn't accepted from peers though

**Comment by justinvforvendetta** [comment]
I'm on my phone right now but I'll look in a minute

**Comment by ocminer** [comment]
but you still need to go through the old blockchain...

**Comment by justinvforvendetta** [comment]
i see what you mean, thanks for the heads up. we're implementing more verifications, like making sure one algo cant be submitted too many times in a row, etc.. few more hardening features

**Comment by mlp** [comment]
What is the multi-algo strategy supposed to be? Is is supposed to rotate algos between blocks?
