### ISSUE TITLE
Verge coin did not show up in Verge wallet from Binance.com

### ISSUE THREAD

**Issue by jnovakgh1** [vergecurrency/VERGE#688]
In February, 2018 I transferred some of my Verge coin from Binance.com to a Verge Wallet (web based wallet).  The URL of the wallet I was using is https://www.wallet-verge.info/wallet/login.aspx and I'm hoping this wasn't a fake site.

At any rate....I waited a week or so for the coin to transfer after it showed up as a successful transfer from Binance but it never showed.  Unfortunately I didn't have a lot of time to research until a couple weeks ago and I come to find out that the above URL no longer exists.

I have the address I transferred to...as well as the Txid from Binance....but is there any way I can retrieve my Verge coin at this point?

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ X] support request 
  - [ ] translation request 

BTW...this site was suggested to me by another person so hopefully I'm posting in the correct forum.

Thanks,
Jeff

**Comment by justinvforvendetta** [comment]
I believe that was a fake site. we never posted it on our site. check the name registration and call them maybe?

**Comment by justinvforvendetta** [comment]
what was the address you transferred to?

**Comment by jnovakgh1** [comment]
Yeh….the more digging and research I do I’m finding out that it may be a fake site.

The receiving address I used for my Verge Wallet was DKBoJpXgdgHp4NzjJB5oKcikneGK1CxtTN <https://verge-blockchain.info/address/DKBoJpXgdgHp4NzjJB5oKcikneGK1CxtTN> 

Thanks,

Jeff

**Comment by justinvforvendetta** [comment]
looks like it was moved to an exchange. i will call the registrar and get the persons info

**Comment by jrsikors** [comment]
Yeah every transaction that goes in to DKBoJpXgdgHp4NzjJB5oKcikneGK1CxtTN  goes out within an hour.

Definitely scammy, sorry man.. you gotta be careful in crypto !

**Comment by justinvforvendetta** [comment]
664017 Irkutsk
RUSSIAN FEDERATION
phone:   +74956681264
fax:  +73952525096
e-mail:  noc@ispsystem.com

the servers ip was 213.159.211.56

call them, file a report, something along those lines.

**Comment by jnovakgh1** [comment]
Thanks….I tried pinging their website awhile ago and got “unknown host”….so I must have been doing something wrong (or you’re using some other method).

I’ll reach out to them to see if I can retrieve it and I appreciate your help and time.

Jeff

**Comment by Positivism** [comment]
They don't block ICMP, must be you.

**Comment by Positivism** [comment]
HTTP going through too.
