### ISSUE TITLE
beginner's question - all about mining Verge

### ISSUE THREAD

**Issue by Tset-Noitamotua** [vergecurrency/VERGE#69]
Hey guys! Hope you don't mind me asking here :)

I would like to start mining Verge with a GPU. Can you point me to a step-by-step guide on how to start?
Assume that I don't know anything so I'd really appreciate baby steps.

After a very quick research it seems that a lot information is distributed over many different places. So in case there isn't a step-by-step guide existing yet point me to the right places and I'll love to sum things up in a noob-friendly tutorial.

- what's better to go with Linux (desktop or server?), Mac or Windows?
- which GPU would you recommend?
- what software do I need to install, how to configure?
- etc. etc. etc.

Cheers
Tset

**Comment by justinvforvendetta** [comment]
any amd/nvidia card will work. what you spend is up to you. once you get a gpu (or two, or three, or four) you should join our discord server and go into the #mining-discussion channel. there's always people there that can help.
