### ISSUE TITLE
there will be makeover of  wallet?

### ISSUE THREAD

**Issue by Exteroqs** [vergecurrency/VERGE#691]
Hi.
Have you planned to update the graphical interface of the wallet?, On the home page has some very nice presentation designs for both desktop and Android but it looks nothing like the current wallet. The current android gui is very seedy I think it would be interesting that they could include TOR in the app and not download an external app.

**Comment by Positivism** [comment]
A new interface is certainly on the list, many more important things are simple ahead of it.
(Multi-Algo Patch, RingCT, any current bugs, ...)

**Comment by Exteroqs** [comment]
I understand, I suppose that after implementing and fix everything that is missing in the code, they will worry about adapting the interface.
thanks for answering.
I close this :)

**Comment by Exteroqs** [comment]
Thank you. 
I think it would be interesting to implement an official wiki, to know more about the characteristics of the project (how it works) and how to use the qt wallet (private address and public address), this is something new for many people.
