### ISSUE TITLE
i get warning of compiling in the las update

### ISSUE THREAD

**Issue by Exteroqs** [vergecurrency/VERGE#692]
It is possible that it is not a bug, but I leave evidence in the same way.
I compiling in Linux 64 bits (kde neon).

I followed the following procedure:
$export CXXFLAGS=-std=c++11(without this QT throws me an error)
$git clone --recurse-submodules https://github.com/vergecurrency/verge && cd verge && ./autogen.sh && ./configure && make

I get this warning:
`main.cpp:1980:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("Postponing %"PRIszu" reconnects\n", vpindexSecondary.size());
                    ^
main.cpp: In function ‘bool ProcessMessages(CNode*)’:
main.cpp:4000:55: warning: format ‘%u’ expects argument of type ‘unsigned int’, but argument 2 has type ‘CDataStream::size_type {aka long unsigned int}’ [-Wformat=]
     printf("ProcessMessages(%u bytes)\n", vRecv.size());
                                                       ^
main.cpp: In function ‘CBlock* CreateNewBlock(CWallet*, bool, int)’:
main.cpp:4387:5: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
     auto_ptr<CBlock> pblock(new CBlock());

/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
main.cpp: In function ‘void VERGEMiner(CWallet*, bool)’:
main.cpp:4841:9: warning: ‘template<class> class std::auto_ptr’ is deprecated [-Wdeprecated-declarations]
         auto_ptr<CBlock> pblock(CreateNewBlock(pwallet, fProofOfStake, fProofOfStake ? ALGO_SCRYPT : miningAlgo));
         ^
/usr/include/c++/5/bits/unique_ptr.h:49:28: note: declared here
   template<typename> class auto_ptr;
                            ^
rpcsmessage.cpp:808:46: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 snprintf(cbuf, sizeof(cbuf), "%"PRIszu, tokenSet.size());
                                              ^
smessage.cpp:197:16: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         printf("Hashed %"PRIszu" messages, hash %u\n", setTokens.size(), hash);
                ^
smessage.cpp:615:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("SecureMsgThread %"PRId64" \n", now);
                    ^
smessage.cpp:631:32: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                         printf("Removing bucket %"PRId64" \n", it->first);
                                ^
smessage.cpp:672:40: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                                 printf("Lock on bucket %"PRId64" for peer %u timed out.\n", it->first, nPeerId);
                                        ^
smessage.cpp:688:44: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                                     printf("This node will ignore peer %u until %"PRId64".\n", nPeerId, ignoreUntil);
                                            ^
smessage.cpp:816:42: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         snprintf(buffer, sizeof(buffer), "%"PRIu64" bytes", nBytes);
                                          ^
smessage.cpp:952:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("Bucket %"PRId64" contains %"PRIszu" messages.\n", fileTime, tokenSet.size());
                    ^
smessage.cpp:952:36: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("Bucket %"PRId64" contains %"PRIszu" messages.\n", fileTime, tokenSet.size());
                                    ^
smessage.cpp:955:12: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     printf("Processed %u files, loaded %"PRIszu" buckets containing %u messages.\n", nFiles, smsgBuckets.size(), nMessages);
            ^
smessage.cpp:1069:12: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     printf("Loaded %"PRIszu" addresses.\n", smsgAddresses.size());
            ^
smessage.cpp:1360:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("Node is ignoring peer %u until %"PRId64".\n", pfrom->smsgData.nPeerId, pfrom->smsgData.ignoreUntil);
                        ^
smessage.cpp:1408:28: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                     printf("Not interested in peer bucket %"PRId64", has expired.\n", time);
                            ^
smessage.cpp:1417:28: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                     printf("Not interested in peer bucket %"PRId64", in the future.\n", time);
                            ^
smessage.cpp:1425:28: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                     printf("Peer sent empty bucket, ignore %"PRId64" %u %u.\n", time, ncontent, hash);
                            ^
smessage.cpp:1431:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("peer bucket %"PRId64" %u %u.\n", time, ncontent, hash);
                        ^
smessage.cpp:1432:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("this bucket %"PRId64" %"PRIszu" %u.\n", time, smsgBuckets[time].setTokens.size(), smsgBuckets[time].hash);
                        ^
smessage.cpp:1432:45: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("this bucket %"PRId64" %"PRIszu" %u.\n", time, smsgBuckets[time].setTokens.size(), smsgBuckets[time].hash);
                                             ^
smessage.cpp:1450:28: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                     printf("Requesting contents of bucket %"PRId64".\n", time);
                            ^
smessage.cpp:1474:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("Sending smsgMatch, %"PRId64".\n", now);
                        ^
smessage.cpp:1509:28: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                     printf("Don't have bucket %"PRId64".\n", time);
                            ^
smessage.cpp:1518:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("vchDataOut.resize %"PRIszu" threw: %s.\n", 8 + 16 * tokenSet.size(), e.what());
                        ^
smessage.cpp:1555:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("Not interested in peer bucket %"PRId64", has expired.\n", time);
                        ^
smessage.cpp:1561:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("Not interested in peer bucket %"PRId64", in the future.\n", time);
                        ^
smessage.cpp:1569:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("Bucket %"PRId64" lock count %u, waiting for message data from peer %u.\n", time, smsgBuckets[time].nLockCount, smsgBuckets[time].nLockPeerId);
                        ^
smessage.cpp:1574:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("Sifting through bucket %"PRId64".\n", time);
                    ^
smessage.cpp:1611:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("Asking peer for  %"PRIszu" messages.\n", (vchDataOut.size() - 8) / 16);
                        ^
smessage.cpp:1612:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("Locking bucket %"PRIszu" for peer %u.\n", time, pfrom->smsgData.nPeerId);
                        ^
smessage.cpp:1643:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("Don't have bucket %"PRId64".\n", time);
                        ^
smessage.cpp:1660:28: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                     printf("Don't have wanted message %"PRId64".\n", token.timestamp);
                            ^
smessage.cpp:1674:28: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                     printf("SecureMsgRetrieve failed %"PRId64".\n", token.timestamp);
                            ^
smessage.cpp:1681:32: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                         printf("Break bunch %u, %"PRIszu".\n", nBunch, vchBunch.size());
                                ^
smessage.cpp:1691:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("Sending block of %u messages for bucket %"PRId64".\n", nBunch, time);
                        ^
smessage.cpp:1704:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("smsgMsg vchData.size() %"PRIszu".\n", vchData.size());
                    ^
smessage.cpp:1716:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("smsgMatch, not enough data %"PRIszu".\n", vchData.size());
                    ^
smessage.cpp:1727:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("Warning: Peer buckets matched in the future: %"PRId64".\nEither this node or the peer node has the incorrect time set.\n", time);
                    ^
smessage.cpp:1736:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("Peer buckets matched at %"PRId64".\n", time);
                    ^
smessage.cpp:1770:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("smsgIgnore, not enough data %"PRIszu".\n", vchData.size());
                    ^
smessage.cpp:1781:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("Peer %u is ignoring this node until %"PRId64", ignore peer too.\n", pfrom->smsgData.nPeerId, time);
                    ^
smessage.cpp:1830:13: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             "Now %"PRId64" next wake counter %u\n", pto->addrName.c_str(), now, pto->smsgData.nWakeCounter);
             ^
smessage.cpp:1865:28: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                     printf("vchData.resize %"PRIszu" threw: %s.\n", vchData.size() + 16, e.what());
                            ^
smessage.cpp:2140:12: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     printf("Took %"PRId64" ms\n", GetTimeMillis() - nStart);
            ^
smessage.cpp:2319:12: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     printf("Took %"PRId64" ms\n", GetTimeMillis() - mStart);
            ^
smessage.cpp:2766:16: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         printf("SecureMsgRetrieve() %"PRId64".\n", token.timestamp);
                ^
smessage.cpp:2868:16: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         printf("Error: Invalid no. messages received in bunch %u, for bucket %"PRId64".\n", nBunch, bktTime);
                ^
smessage.cpp:2924:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("Don't have bucket %"PRId64".\n", bktTime);
                    ^
smessage.cpp:3057:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("bucket: %"PRId64"\n", bucket);
                        ^
smessage.cpp:3059:24: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 printf("message ts: %"PRId64, token.timestamp);
                        ^
smessage.cpp:3120:12: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
     printf("SecureMsg added to bucket %"PRId64".\n", bucket);
            ^
smessage.cpp:3295:20: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
             printf("SecureMsgSetHash() failed, took %"PRId64" ms, nonse %u\n", GetTimeMillis() - nStart, nonse);
                    ^
smessage.cpp:3303:16: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         printf("SecureMsgSetHash() took %"PRId64" ms, nonse %u\n", GetTimeMillis() - nStart, nonse);
                ^
smessage.cpp:3339:16: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         printf("Message is too long, %"PRIszu".\n", message.size());
                ^
smessage.cpp:3606:16: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         printf("Message is too long, %"PRIszu".\n", message.size());
                ^
smessage.cpp: In function ‘bool SecureMsgReceiveData(CNode*, std::__cxx11::string, CDataStream&)’:
smessage.cpp:1360:123: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘int64 {aka long long int}’ [-Wformat=]
                 printf("Node is ignoring peer %u until %"PRId64".\n", pfrom->smsgData.nPeerId, pfrom->smsgData.ignoreUntil);
                                                                                                                           ^
smessage.cpp: In function ‘bool ScanChainForPublicKeys(CBlockIndex*)’:
smessage.cpp:2140:59: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
     printf("Took %"PRId64" ms\n", GetTimeMillis() - nStart);
                                                           ^
smessage.cpp: In function ‘bool SecureMsgScanBuckets()’:
smessage.cpp:2319:59: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
     printf("Took %"PRId64" ms\n", GetTimeMillis() - mStart);
                                                           ^
smessage.cpp: In function ‘int SecureMsgSetHash(unsigned char*, unsigned char*, uint32_t)’:
smessage.cpp:3295:111: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
             printf("SecureMsgSetHash() failed, took %"PRId64" ms, nonse %u\n", GetTimeMillis() - nStart, nonse);
                                                                                                               ^
smessage.cpp:3303:99: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘long long int’ [-Wformat=]
         printf("SecureMsgSetHash() took %"PRId64" ms, nonse %u\n", GetTimeMillis() - nStart, nonse);
                                                                                                   ^
rpcsmessage.cpp:808:46: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
                 snprintf(cbuf, sizeof(cbuf), "%"PRIszu, tokenSet.size());
                                              ^
  CXX      libbitcoin_wallet_a-wallet.o
wallet.cpp:2072:16: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         printf("Stealth send to generated pubkey %"PRIszu": %s\n", pkSendTo.size(), HexStr(pkSendTo).c_str());
                ^
wallet.cpp:2074:16: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
         printf("ephem_pubkey %"PRIszu": %s\n", ephem_pubkey.size(), HexStr(ephem_pubkey).c_str());
                ^
`

**Comment by jrsikors** [comment]
Mr @positivism .. any thoughts? :smile:

**Comment by Positivism** [comment]
From a glance it looks like the normal warnings when compiling.
Did it fail to compile? @Exteroqs

**Comment by Exteroqs** [comment]
Yes, it is compiled and it works. I was reading, I think it's because the syntax changed in c ++ 11, so it throws the "warning: invalid suffix on literal; C ++ 11 requires a space between literal and string". the same happens with std :: auto_ptr 'in C ++ 11 this was changed to "unique_ptr" (http://www.cplusplus.com/reference/memory/auto_ptr/).

**Comment by Exteroqs** [comment]
All Right.
