### ISSUE TITLE
NO Connection on Verge Tor Wallet

### ISSUE THREAD

**Issue by soulrific** [vergecurrency/VERGE#693]
I havnt been able to get a connection on my Verge Tor Wallet for 2 days now.  I'm using a Samsung S8.  I tried toggling the VPN, nothing.  I'd like to switch over to a pc Verge Wallet.  I know this was an issue for some others in the past.  Are the Android servers down?

**Comment by karanpatel863** [comment]
please wait new updated android wallet is going to be uploaded soon. this might solve the problem.

**Comment by justinvforvendetta** [comment]
one of the android servers is back online now. the rest should be back up within 1-2 hours at most. they are being updated to the latest changes now.

**Comment by soulrific** [comment]
Thank you for the quick response.

-nic

**Comment by soulrific** [comment]
So Thanks, I got the mobile app to finally connect.
Can I simply convert my seedphrase from verge tor mobile wallet into a
privatekey and restore my Verge funds  onto the new pc Electrum Wallet?  If
so, how?
 Or should i just open a new pc Electrum wallet, then send my mobile Verge
wallet funds to it?  Which is more efficient?  I'd like to finally store my
Verge on a pc instead of my mobile.
Thanks,
Nic

**Comment by Positivism** [comment]
Eliminate stress and just send it over.

**Comment by soulrific** [comment]
Got it.
Thx.
