### ISSUE TITLE
Rejected blocks no matter [all details included, please review]

### ISSUE THREAD

**Issue by goodthebest** [vergecurrency/VERGE#694]
hi VERGE dev team @justinvforvendetta could you please review these and suggest, what's causing reject blocks issue. I've tried numerous experiments but all goes to 'reject blocks'. I've included all settings, conf and debug log for you to kind review and help me solve this issue, thanks in advance.

**VERGE.conf**
![image](https://user-images.githubusercontent.com/1715740/38460112-ccf85c86-3ac4-11e8-881a-17c44504a4be.png)

**Pool Settings tab**
![image](https://user-images.githubusercontent.com/1715740/38460116-06f77f7a-3ac5-11e8-9132-c070aa85777a.png)

**Pool Daemon tab**
![image](https://user-images.githubusercontent.com/1715740/38460130-43a6c7fa-3ac5-11e8-9c5f-a8e7bbceb7bf.png)

**Getinfo output**
![image](https://user-images.githubusercontent.com/1715740/38460140-6b670ade-3ac5-11e8-9a61-4d04a8d1ab47.png)

**Getmininginfo out**
![image](https://user-images.githubusercontent.com/1715740/38460153-8a99ad44-3ac5-11e8-8e17-e20fc84b8ae1.png)

**debug.log file**
[verge-debuglog.zip](https://github.com/vergecurrency/VERGE/files/1886716/verge-debuglog.zip)

**Reject log**
![image](https://user-images.githubusercontent.com/1715740/38460193-1c11f2c2-3ac6-11e8-8b01-74f8d2ba11e1.png)

**Comment by jrsikors** [comment]
Did you update to the latest commits? 

https://twitter.com/vergecurrency/status/982399457508646912

**Comment by Positivism** [comment]
Affirmative @jrsikors

**Comment by goodthebest** [comment]
@jrsikors what is the right version please advise link to download linux daemon?

**Comment by jrsikors** [comment]
it looks like you got the latest commit, was my mistake, i didn't read the version fully :disappointed:

**Comment by goodthebest** [comment]
@jrsikors could you please review VERGE.conf, Settings tab and Daemon Tab configuration I've posted earlier screenshots, if everything is alright or I need to add or subtract anything?

**Comment by jrsikors** [comment]
would suggest hopping on Discord
https://discord.gg/vergecurrency

to the Verge-Mining-Discussion channel

If you need immediate answers.. Justin unavailable right now

**Comment by justinvforvendetta** [comment]
are you using clearnet or master branch? no other pool is having that issue, so im not sure whats going on..
https://umine.org/site/block?id=561
https://nlpool.nl/site/block?id=561
http://yiimp.eu/site/block?id=562
http://antminepool.com/site/block?id=561
https://luckypool.xyz/site/block?id=1

**Comment by justinvforvendetta** [comment]
btw, if  you're running on tor, which it looks like you are, the latency probably isnt helping since you are submitting blocks a few milliseconds slower than the other pools.

**Comment by goodthebest** [comment]
@justinvforvendetta yes running on tor. could you please guide me, how can I compile VERGE without tor?

**Comment by jrsikors** [comment]
https://github.com/vergecurrency/VERGE/issues/487

**Comment by justinvforvendetta** [comment]
no, clone the 4.0clearnet branch if you want to mine and submit blocks as fast as the other pools

**Comment by justinvforvendetta** [comment]
you can do git checkout 4.0clearnet too, if you don't want to directly clone the 4.0 branch

**Comment by goodthebest** [comment]
My question is
I'm at https://github.com/vergecurrency/VERGE/tree/4.0clearnet

When I try to clone I get exactly the same clone url as I get in master, 
https://github.com/vergecurrency/VERGE.git

can you please give me command line to clone clearnet 4.0

is it?
> git clone https://github.com/vergecurrency/VERGE.git

or 

> git checkout 4.0clearnet https://github.com/vergecurrency/VERGE.git

**Comment by goodthebest** [comment]
@justinvforvendetta @jrsikors 
I ran commands this way

` git checkout 4.0clearnet`
> Branch 4.0clearnet set up to track remote branch 4.0clearnet from origin.

`git clone https://github.com/vergecurrency/VERGE.git`

after git clone, cd VERGE
`./autogen.sh`

but it again installs with TOR

![image](https://user-images.githubusercontent.com/1715740/38460975-5c905bb2-3ad6-11e8-8e17-85b08fbf756d.png)

**Comment by justinvforvendetta** [comment]
you should have done git checkout after cloning.
do this:
git clone https://github.com/vergecurrency/VERGE/tree/4.0clearnet

and then compile =]

**Comment by goodthebest** [comment]
@justinvforvendetta 

Cloning into '4.0clearnet'...
remote: Not Found
fatal: repository 'https://github.com/vergecurrency/VERGE/tree/4.0clearnet/' not found

![image](https://user-images.githubusercontent.com/1715740/38461032-6937cdea-3ad7-11e8-9c5d-3bfb3a07bc4d.png)

**Comment by justinvforvendetta** [comment]
ok clone normal and the  git checkout 4.0clearnet and then compile. don't clone again

**Comment by goodthebest** [comment]
@justinvforvendetta 
fatal: Not a git repository (or any of the parent directories): .git

![image](https://user-images.githubusercontent.com/1715740/38461083-7049556c-3ad8-11e8-8d59-a4d8e0630608.png)

**Comment by justinvforvendetta** [comment]
you need to be in the new verge directory

**Comment by goodthebest** [comment]
Alright, should I compile standard way or I need to add some flags with './configure' ?

`./autogen.sh`
`./configure`
`make`

**Comment by justinvforvendetta** [comment]
should work just like that

**Comment by goodthebest** [comment]
thanks alot guys @justinvforvendetta @jrsikors

**Comment by goodthebest** [comment]
I managed to compile 4.0clearnet, it is the correct version, as I see BETA there?

![image](https://user-images.githubusercontent.com/1715740/38461548-b8a9793e-3ae4-11e8-9143-d3962b75fb46.png)

**Comment by jrsikors** [comment]
Yep you are good to go .. you can see the commit number in the version

https://github.com/vergecurrency/VERGE/commit/c66e16d2f3b63519b97b33a403866a80e4e340dc

**Comment by goodthebest** [comment]
@jrsikors blocks are stuck at 2039377, not moving forward, even though I have restarted with -reindex ?

**Comment by justinvforvendetta** [comment]
it should finish syncing, but please come back here if it does not.

**Comment by goodthebest** [comment]
sync went smooth, however in debug.log I'm noticing this, is it normal or something not right?

![image](https://user-images.githubusercontent.com/1715740/38462305-d15dec2e-3af5-11e8-8a43-f158a4921df2.png)

**Comment by goodthebest** [comment]
@justinvforvendetta @jrsikors Even after installing non tor version, 4.0clearnet,  I'm still getting rejected blocks, what could be the possible reasons? 
here's decode error
![image](https://user-images.githubusercontent.com/1715740/38470732-2f752f98-3b78-11e8-8a43-a75c952f22ec.png)

![image](https://user-images.githubusercontent.com/1715740/38470724-1a3ca642-3b78-11e8-92d1-f45bb7c19a49.png)

**Comment by goodthebest** [comment]
@jrsikors @justinvforvendetta 
and pool settings are

![image](https://user-images.githubusercontent.com/1715740/38470892-84a0dfa6-3b7a-11e8-8ea2-dd7c70b40bb2.png)

**Comment by jrsikors** [comment]
I'm about at the extent of my mining knowledge unfortunately.

Again -- I would **_highly_** recommend hopping on the Discord channel
https://discord.gg/vergecurrency

There is an entire "room" in the channel devoted to "Verge-Mining-Discussion" where I think you would find more help from experienced verge miners.

Otherwise i have to defer to justin if/when he finds time.

**Comment by goodthebest** [comment]
@jrsikors I've been to that discord channel and unfortunately there isn't any help at all as they are mere 'miners', none pool owners I could see there.

It's very technical issue I'm sure with your little help it can be nabbed. I'll appreciate if you can refer to Justin to look into this, I can provide as much as infor / details needed.

**Comment by justinvforvendetta** [comment]
maybe it's because we have ntime in our headers, so you need to select pos/pow hybrid in the config?

**Comment by goodthebest** [comment]
Yes, POW, please advise?

![image](https://user-images.githubusercontent.com/1715740/38499723-875c6a18-3c19-11e8-8e89-9789e04cf2bc.png)

**Comment by goodthebest** [comment]
@jrsikors @justinvforvendetta 
![image](https://user-images.githubusercontent.com/1715740/38506717-b43211d4-3c2b-11e8-9393-0d8d860032d6.png)

getinfo 
![image](https://user-images.githubusercontent.com/1715740/38506768-d2b227a2-3c2b-11e8-960b-4745099796ea.png)

**Comment by justinvforvendetta** [comment]
do you understand what I mean when i say ntime is in the header? you would want to select pos+pow if possible, or change the software to recognize ntime

**Comment by goodthebest** [comment]
@justinvforvendetta @jrsikors 
can I just use POS?

**Comment by justinvforvendetta** [comment]
do you understand what I mean when I say that verge is pow, with ntime in the header

**Comment by goodthebest** [comment]
Trying to get your point.
I can pool set software to pow/pos. 
OR is there anything to add to VERGE.conf file for ntime param?

**Comment by goodthebest** [comment]
does that mean instead of just pow, I should use 'pow/pos'

![image](https://user-images.githubusercontent.com/1715740/38509287-8911c628-3c32-11e8-8034-c71080e0f441.png)

**Comment by goodthebest** [comment]
in VERGE.conf, do I need to add `staking=0`

**Comment by justinvforvendetta** [comment]
no, because it will not stake anyway.

**Comment by goodthebest** [comment]
It's been weeks going after VERGE mining with rejected blcoks, I have spoke to at least more than half a dozen pools they are running other coins successfully except XVG rejected block that includes me as well.

I've a notion that you guys are manipulating and not allowing everyone else to run pools with XVG only select pools are able to do so. 

What the heck it is that I cannot setup my pool right and several others whom I personally talk to but only few select pools are running XVG.

It's horrible process to get  help from you Dev guys, I'll take it forward and bring it in front of the community as far as I can reach this is absolutely corrupt at the end of XVG Dev who are being secretive of mining which is apparently a community project but only select folks are getting benefit. Mind it if you guys do not spill the beans fairly then rest of people will bring the attention more rigorously.

**Comment by justinvforvendetta** [comment]
it is not secretive at all. pool admins have not even needed our help. you just need to clone the 4.0clearnet branch.
