### ISSUE TITLE
Updating from Verge Wallet 3.0 to newest release 7 april 2018

### ISSUE THREAD

**Issue by vergelover** [vergecurrency/VERGE#695]
I downloaded my verge wallet 3.0 wraith in early December. It was syncing perfectly until early March. I didnt update it to the wallet 4.0 wraith or update after the fork.

Now in april 7th the wallet is not syncing properly and I want to update the wallet to latest version. I am on a macbook pro with high Sierra 10.13.4

* Verge Release:  Verge Wallet 3.0 wraith

Do I need to download all the updates since Verge 3.0 wraith e.g. verge wallet 4.0 and the updates or can I skip to the most recent and download the update?

How do I ensure my old wallet and coins are in the latest download?

Thanks,

**Comment by Positivism** [comment]
Skip to the most recent, backup your wallet.dat.

**Comment by jrsikors** [comment]
You need to back up your wallet.dat .. make sure you copy it off computer to another jump drive.

You don't need to download any previous versions ... download the latest one VERGE-Qt-4-7-2018.dmg .. install it .. run it .. and you will be good to go.  

You don't need to uninstall the older version -- you can install the new one side by side just as a precaution.

Your new version will reference your data directory (which includes your wallet.dat)

**Comment by vergelover** [comment]
Thank you so much guys.  So when I install the new release it will automatically reference my dat file from the original version?
Do i have to manually copy the back up wallet.dat from the old directory to the new version?

**Comment by Positivism** [comment]
No, the wallet file is still in the same directory. Just run the new bin/executable.

**Comment by vergelover** [comment]
Excellent thank you so much

**Comment by Positivism** [comment]
👍

**Comment by vergelover** [comment]
Hi Guys I received the following error when trying to open the latest release.

Please let me know how to solve this if you can? 
I dont have my old verge wallet running. I closed it down.
![screen shot 2018-04-07 at 22 52 10](https://user-images.githubusercontent.com/38167212/38460673-8bcd32f8-3ab6-11e8-8435-31d2a59227ef.png)


Thanks,

**Comment by Positivism** [comment]
Press command option esc and kill any instances of verge that may be currently running. Looks like you have the old one running still.

**Comment by Positivism** [comment]
You can grab the latest upload from http://verge-blockchain.com/

**Comment by vergelover** [comment]
Thank you positivism !!! 🤗

**Comment by vergelover** [comment]
Thanks jrsikors

**Comment by Positivism** [comment]
No problem.

**Comment by vergelover** [comment]
The link above didn't seem to work but I found it at:

https://verge-blockchain.com/down

I have chosen the top one - out of curiosity is there any reason there are two links?

Do I have to put the blockchain anyway in the verge folder or will it automatically link to my wallet?

Many thanks,

**Comment by vergelover** [comment]
Blockchain download

Is it possible to download the blockchain and store it on an external hard drive?  
I have an external hard drive and has nothing on it, so can I use that to store the blockchain download.
As each time will take up a lot of space on my laptop.

Thanks,
Sunil

**Comment by Positivism** [comment]
Not currently, as far as I'm aware you cannot change the blockchain path.

**Comment by jrsikors** [comment]
You can run verge-qt.exe (speaking windows here) with a parameter.

I personally run something like  **_verge-qt.exe -datadir=C:\MyCryptoStuff\Verge\Data_**

That sets the data directory there.

I don't know what it would be like doing blockchain sync on an external hard drive.  It seems like a bad idea for many reasons... but you could give it a shot.  If you start running into a lot of problems (constant freezing, etc) , it's probably an I/O issue.

**Comment by Alex1121B** [comment]
Hello guys!
Do you know how can I recover my wallet if I’ve lost my password, but still have my recovery key?
I've tried today to access my wallet and to send my funds to Binance, but apparently I have a password.
I don't know it, but I still have my recovery key.

I have an old Electrum XVG 2.4.1 wallet. 
Do you have any kind of advice?

Thanks in advance!

**Comment by justinvforvendetta** [comment]
@Alex1121B delete the old wallet data and re install, and use the restore option, then use your seed to recover.
