### ISSUE TITLE
Unverified status in macosx electrum-xvg (2.4 version) wallet

### ISSUE THREAD

**Issue by levon89** [vergecurrency/VERGE#696]
I have **_successfully_** sent my verges  to my electure-xvg (version 2.4) wallet . **_Blockchain shows me that  transactions confirmed._** **_Exchange_** shows that all is _**success**_ . _**Electrum-xvg show amount of coins**_ , which I have already **_sent_** ,   **_but status is unverified_** . _**It passed a week , but I've still see same status (unverified).**_ My os is macosx .

**Comment by jrsikors** [comment]
It's just a cosmetic bug.. the funds should be available for spending:
https://github.com/vergecurrency/VERGE/issues/112

https://www.reddit.com/r/vergecurrency/comments/7q3oah/xvg_received_on_electrumxvg_29th_december_date/
