### ISSUE TITLE
You should explain this in detail

### ISSUE THREAD

**Issue by mtompkins** [vergecurrency/VERGE#697]
One can only wonder what you are trying to do with your installation.

```
find: ‘/usr/local/lib/rkhunter’: Permission denied
find: ‘/usr/local/var/run/watchman/root-state’: Permission denied
find: ‘/usr/local/etc/sav’: Permission denied
```

**Comment by justinvforvendetta** [comment]
one can see the answer to that by reading the source code since it's right here.

looks like it doesn't have permission to compile the libs? it's open source so you can read the go.sh file

**Comment by justinvforvendetta** [comment]
you need to be a super user or have sudo privs in order to install the dependencies. are you new to linux?

**Comment by mtompkins** [comment]
I've been using linux for 30 years - I'm quite aware of the purpose of sudo - are you?

**Comment by justinvforvendetta** [comment]
well fyi the script you are running is open source and readable here in this repository. whether you compile it or not is up to you. it is not trying to disable anything. it's just not allowed to install the dependencies it needs because you aren't a super user.

**Comment by Positivism** [comment]
"You can't properly derive intent from code unfortunately" It appears you're trying to be cautious about what's being installed but have no idea what to be cautious for.

**Comment by mtompkins** [comment]
The script was run as a sudo enabled user. 

While I appreciate you taking the time to respond to some degree, nothing you've said provides any clarity, justification, or explanation for trying to detect or otherwise interact with known malware and antivirus protections like Symantec or RootKit Hunter. Repeating "it's there for you to see" is a terrible non-answer.

Look it's clear you aren't going to answer the question. I'm not going to waste more time on this than I already have.

**Comment by justinvforvendetta** [comment]
it's the other way around. they are trying to interact with it. you can see in the not so lengthy bash script you are running, that it's not looking for Symantec or rkhunter.

**Comment by justinvforvendetta** [comment]
instead of opening an issue you can have just opened the hash script and looked at it, since I see you have some in your repository as well.
