### ISSUE TITLE
[Feature Request] Shortcuts

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#698]
If we add keyboard shortcuts to each page I can create an interface for vergeQt for the touchbar.
Example Ctrl+S To access the send page.

**Comment by Positivism** [comment]
Or menubar items could also work.

**Comment by Positivism** [comment]
@jrsikors You are personally responsible for making this pull-request now. :)

**Comment by jrsikors** [comment]
NOPE

**Comment by Positivism** [comment]
: )

**Comment by jrsikors** [comment]
hey @Positivism e-mail me at jeffsikorski@gmx.com  .. in case we want to chat outside of here !

**Comment by marpme** [comment]
There are already Shortkeys for each page. 

`ALT` + `1-6` for each page

**Comment by Positivism** [comment]
Nice find.

**Comment by Positivism** [comment]
For the record, the shortcut on mac is Option+#
