### ISSUE TITLE
TX rejected

### ISSUE THREAD

**Issue by VirtualVal** [vergecurrency/VERGE#701]
* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [X] support request 
  - [ ] translation request 

I have an Electrum XVG 2.4.1 wallet and I'm trying to send some coins to binance. I keep getting the error: TX rejected.
I've tried to change the fee manually and not, first to 0.1, then 1, then 2 XVG. I'm been able to make only 1 transaction of 100 XVG with a fee of 1 XVG. Does that mean that the fee is 1%?

I've also tried different servers, different amounts... nothing work. What should I do?

**Comment by marpme** [comment]
So the transaction fee for each transaction is always 0.1 XVG (by design) 
See here: https://vergecurrency.com/faq/

And besides that, whats the current amount of XVG you have on your wallet. 
I assume that you have 100 XVG, then you have to send 99.9XVG to binance as 0.1 XVG will be processed as transaction fees.

**Comment by VirtualVal** [comment]
I have 1385 and trying to send 500 with 2 fee fails

**Comment by VirtualVal** [comment]
if I try to use a 0.1 fee (sending 500) I get the message "this transaction requires a higher fee...)

**Comment by VirtualVal** [comment]
I've successfully sent 500 XVG using a 2 XVG fee, but now even like this downs't work. Still getting "TX rejected"

**Comment by VirtualVal** [comment]
now it's just stuck in the broadcast (I've waited a very long time)

![electrum screen](https://user-images.githubusercontent.com/38240831/38552808-8f8396de-3ce7-11e8-869e-4da717d8e873.jpg)

**Comment by jrsikors** [comment]
Did these finally go through ?

I see the 100 and a couple 500's here:
https://verge-blockchain.info/address/DMNY4uyrVYxKQwcPY6NGkWqc7LVk8Lo5KQ

I did notice it said "synchronizing" in the bottom left of electrum client and not 'connected' .. probably had something to do with it ?

**Comment by VirtualVal** [comment]
yes I've made 3 transactions, 100,500,500. With 1,2,2 fee. Now even that doesn't work anymore. Maybe the problem is the synchronization, but how to solve that?

**Comment by VirtualVal** [comment]
Isn't this supposed to work?

![electrum screen 2](https://user-images.githubusercontent.com/38240831/38560307-8c4b3b8a-3cff-11e8-8c4b-2558841e5fda.jpg)

**Comment by VirtualVal** [comment]
Even with smaller amount and larger fee, it doesn't work

![electrum screen 3](https://user-images.githubusercontent.com/38240831/38561174-8a57de44-3d01-11e8-99c8-4b0d8f1306e9.jpg)

**Comment by jrsikors** [comment]
I'm not an Electrum guru unfortunately, hopefully someone else chimes in.

I think you just need a higher fee.  Just keep bumping it up by 1 until it goes through.  Unfortunately I can't speak to the formula in Electrum as to why:
https://www.reddit.com/r/vergecurrency/comments/82fi42/why_the_transaction_fee_of_electrum_wallet_is_so/

I mean I definitely would stop at like 5-10 if it's still being rejected

An alternate solution, although a lot different than a lightweight electrum wallet, is to use the QT wallet.  .01 fees all the time.

**Comment by VirtualVal** [comment]
thank you for your help, I'll try rising the fee

**Comment by VirtualVal** [comment]
Using 10 XVG as fee finally worked! I really would like to know why so much

**Comment by justinvforvendetta** [comment]
was your balance made by alot of deposits? say your balance is 100 coins. it can be from depositing 1 coin 100 times, or depositing 50 coins twice. when you go to send, if it were from alot of small deposits, then the transaction is bigger because of all the inputs. the 2 50 transactions would be smaller because only 2 inputs. the more inputs, the higher the fee

**Comment by VirtualVal** [comment]
Definitely! I've had many many small deposits. Thank you Justin for the explanation!
