### ISSUE TITLE
Electrum doesn't recognize seed! will tip xvg

### ISSUE THREAD

**Issue by oustaz** [vergecurrency/VERGE#703]
Hello I downloaded the latest version of electrum in dec 2017, when i created wallet it gave me seed asked me to enter it and activated the wallet. I made sure to make two hand written copies of the seed and stored them somewhere safe, last week I tried to recover my wallet but when I type the seed the next button is still grayed out, I downloaded the latest and older version for windows but none of them worked even tried tor version of the wallet.I was told that as long you have the seed you can recover your wallet that's why I'm kinda lost.For anyone asking I made sure I didn't make any mistakes writing down the seed so that shouldn't be the issue. One thing I remember is I switched servers while using the wallet could it be the reason? I am willing to tip 1000xvg to anyone who can provide helpful info Thanks

**Comment by jrsikors** [comment]
how many words is your seed?

**Comment by jrsikors** [comment]
and your issue isn't the seed is rejected... the main issue right now is the button is greyed out when you type in the seed?

Are you typing or copying/pasting ?

**Comment by oustaz** [comment]
Im typing

**Comment by jrsikors** [comment]
I'm not at home so I can't play around with it -- but also I think I remember that

Electrum Tor uses an 8 word seed
Electrum non-Tor uses a 9 word seed

So if you have an 8 word seed, and using Electrum NON tor -- it might explain why the button is greyed out. To test the theory, you could type in another word to make it 9 words, and see if the option becomes un-greyed out.

**Comment by oustaz** [comment]
Ok will try that

**Comment by oustaz** [comment]
I try the tor version but it’s still greyed out Do you think that the fact I once changed server might be the reason ?

**Comment by jrsikors** [comment]
I just tried it on both electrum-XVG and Electrum-TOR-XVG.  I was able to generate a new seed on one, and import it to the other.

If the option is greyed out -- it means your seed isn't correct.

~Are you sure you didn't change any letters or words when you wrote it down on paper?

~There are 3 other versions of electrum XVG you can download here:
 https://github.com/vergecurrency/electrum-xvg/releases
I would try them all

~Do you have any backups of this directory:
C:\Users\YOU\AppData\Roaming\Electrum-XVG

~Did you export the private keys?

Other than that it's supposed to be pretty simple.  The seed recovery ability seems to function fine.  You must have written it down incorrectly , either on purpose or accident?

**Comment by oustaz** [comment]
Thanks for your help! I’m 100% positive I wrote the seed correctly I didn’t forget anything ! Unfortunately didn’t make any back up I tought the seed would be enough my only hope is the second step you advised will try it when I get home...one question I have one of adresses in the wallet can you check the wallet balance with that ?

**Comment by jrsikors** [comment]
When you say "address" -- i'm assuming you mean the public 'address' like you can find on the blockchain www.verge-blockchain.info ?

Knowing ONLY that public address probably won't help much.  You need the private key to access the funds... and to get the private key we either need to find a way to restore your wallet from a backup, or get the seed to work.

**Comment by jrsikors** [comment]
This is part of my suggestions earlier that you should try -- but i did see on a bitcoin electrum forum someone post:

> I managed to recover everything without needing a seed at all. I simply went to \AppData\Roaming\Electrum, and replaced the files with the copy of my original Electrum installation (which included my wallet file), and then opened up Electrum. Voila! All of my BTC and information was there.

In your case it would be Roaming\Electrum-XVG instead of Roaming\Electrum .. but same concept

**Comment by oustaz** [comment]
Is there an xvg electrum word dictionary where I could look up the words and for your question I meant adresss not private key

**Comment by jrsikors** [comment]
for the non-tor:
https://github.com/vergecurrency/electrum-xvg/blob/master/lib/wordlist/

for the tor:
https://github.com/vergecurrency/electrum-xvg-tor/tree/master/lib/wordlist

Unsure which one you initially generated with.  They might be the same

**Comment by oustaz** [comment]
Found it!!!! Thanks, so grateful for your help, what happened was  I made a mistake on  one word, forgot one small letter and I was hundred percent positive that I was right!!!!!! now I got the wallet but I don't see any funds It says offline when I click the red button nothing happens

**Comment by jrsikors** [comment]
What servers are in your drop down list under the Network?  Try selecting the e3.electrum one.  The servers are pretty overloaded so keep trying.

Can you post a screenshot of your Network screen?

**Comment by oustaz** [comment]
Oh got it to work with e1.verge-electrum.com on 50001 everything is fine now please send your xvg adress I don't have a lot but I'll happily send 1000 coins your way!!!

**Comment by jrsikors** [comment]
donate to the team .  no need to do all 1,000 , i won't hold ya to it!  I would have helped you the same if you didn't offer any XVG :smile: 

Do what you can if you want:
http://vergecurrency.com/donate/
DLv25ww5CipJngsKMYemBTBWH14CUpucxX

**Comment by jrsikors** [comment]
glad we got ya sorted out though, i hate seeing people lose coins because of password / seed issues .

**Comment by oustaz** [comment]
I know you would, I was reading around here and saw you helping people, I had this issue for two weeks now resolved I'll keep my word and send the coins to the team as you said...Good luck

**Comment by oliver-gomes** [comment]
@oustaz @jrsikors  I am in the same problem and thanks to you guys, I was able to find my missing word from the dictionary above but when i get in it says not connected (i am offline) and no coin appears. Let me know how i can retrieve my coins any help appreciated?

**Comment by oliver-gomes** [comment]
just fyi i have 9 keyword seed and I was able to find my words from non-tor list, i downloaded 2.4.1. Before this the button was greyed out cause i miss spelled 1 word
