### ISSUE TITLE
Error Synchronising Verge qt wallet. 

### ISSUE THREAD

**Issue by kentaur1** [vergecurrency/VERGE#705]
Mac user here. 
Installed 3.0 Verge-qt around new years. 
I have updated last Verge-Qt wallet two months ago. 
Every other update worked great. 

Yesterday I have downloaded the latest blockchain from https://verge-blockchain.com/
server1_QT-Wallet_v4.x_Verge-Blockchain_2018-April-10.zip.

Before updating the files, I have backed up the wallet. 

What is obvious, there are now two blockchain files in the folder- blk0001 and blk0002. 

It took several attempts (was crashing 5 times), and an hour to load the blockchain. 
It's been on for hours and still not synchronised. 
Wonder what is going on? 
Would appreciate any help, because I cannot receive or transfer any XVG at the moment. 
![verge core](https://user-images.githubusercontent.com/38282997/38612688-6a1650a6-3d7f-11e8-977e-bfd8f7bbaac2.jpeg)

**Comment by jrsikors** [comment]
Your screenshot says you are on version 2.  You aren’t on the latest version .. 4.0.2

**Comment by kentaur1** [comment]
Thank you @jrsikors. 
I updated to version 4, still out of sync. 
![image](https://user-images.githubusercontent.com/38282997/38618644-31958ef0-3d92-11e8-91aa-30e4b0254a9f.png)

Should I maintain both blk0001 and blk0002 files?

**Comment by jrsikors** [comment]
You need both blk files.  Are you in a country that blocks TOR?  Or an app or ISP?

I would close down QT, delete peers.dat, re-open.. and give it a good 30 mins to try to find connections

**Comment by kentaur1** [comment]
Thank you Jeff. I am in the UK, so far it worked fine. 
I'll follow your advice.

**Comment by noobihodl** [comment]
I have the same issue. I went onto Telegram XVG-Wallet-Support and had communication with XVGMonk over the last couple of days. We could not work out why it was happening. I followed his instructions at https://medium.com/@xvgmonk/how-to-install-the-latest-verge-qt-wallet-mac-high-sierra-5b5b1f9f46c8 and still did't work. It keeps crashing when I open the app.

My Mac is

![image](https://user-images.githubusercontent.com/38291926/38628561-feb60452-3df4-11e8-9dda-b39dd63bdf74.png)
 Will try your suggestion.

**Comment by noobihodl** [comment]
This issue was also raised at https://github.com/vergecurrency/VERGE/issues/704

**Comment by noobihodl** [comment]
This is the crash report people seem to be getting on their Mac (this is from mine)

![image](https://user-images.githubusercontent.com/38291926/38628758-80f3c08a-3df5-11e8-8073-50dde77d9b21.png)

**Comment by jrsikors** [comment]
I'm confused -- are you having problems synchronizing or crashing?  If you are having problems with crashing, then please post under #704 

@kentaur1 doesn't seem to have issues with crashing.  He's just getting 0 connections... completely different issue i think ?

**Comment by jrsikors** [comment]
I see now he did initially mention it crashed a few times, but that could be because he was trying to use an older version.

@noobihodl  , please post your latest screenshot on the #704  since you are specifically having issues with Mac OS crashing.

Let's keep this separate as a "syncing issue" for now

Not all Mac users are having problems.

**Comment by noobihodl** [comment]
Ok thanks. Will do.

**Comment by jrsikors** [comment]
@kentaur1  let us know how it's going over there, if you ever got any connections.  I know it's late in the UK, so whenever !

**Comment by jrsikors** [comment]
will close for now -- feel free to hollar and re-open if you still have problems @kentaur1  .. but i will see all comments on this issue if you post

**Comment by kentaur1** [comment]
Hi Jeff, just wanted to update you and check whether this is normal. 
I managed to get 16 connections, however I have been uploading the blockchain from scratch for the past two days and only have reached early 2017. The last time I've updated the wallet was two months ago, wasn't expecting I would have to reload blockchain from the beginning. 
![image](https://user-images.githubusercontent.com/38282997/38745899-d8633f14-3f3d-11e8-87ea-df03099e3abe.png)

**Comment by kentaur1** [comment]
And apologies for not replying before :)

**Comment by jrsikors** [comment]
You mentioned in your initial post you downloaded
Yesterday I have downloaded the latest blockchain from https://verge-blockchain.com/
server1_QT-Wallet_v4.x_Verge-Blockchain_2018-April-10.zip.

that would work fine ... just close down verge-qt , unzip it into your data directory (Application Support/Verge)  , dont overwrite peers.dat , and re-open verge-qt

**Comment by jrsikors** [comment]
check out:
https://verge-blockchain.com/howto
(but my special instructions .. dont overwrite your existing peers.dat)

**Comment by kentaur1** [comment]
Thanks a lot!
I'll give it a shot. 
:)

**Comment by jrsikors** [comment]
@kentaur1  just curious -- but how did you end up getting connections?  

Did you just leave the wallet open for hours?
Did you just do as i suggested, deleted the peers.dat , and it magically worked?

**Comment by kentaur1** [comment]
Hi Jeff, it worked perfectly in the end!! :))
Replaced all the files but peers as you suggested, reopened, left it for an hour to get up to the speed on the blockchain and finally managed to get full sync!
Thanks a lot for your help, I really appreciate it mate!!
