### ISSUE TITLE
walletpassphrase missing from 'help' console command

### ISSUE THREAD

**Issue by buzztiaan** [vergecurrency/VERGE#71]
as description :)

**Comment by justinvforvendetta** [comment]
ill fix that today mr buzz ;]

**Comment by buzztiaan** [comment]
also, pose for a picture like this ; https://twitter.com/brucefenton/status/905026961633882112

**Comment by justinvforvendetta** [comment]
@buzztiaan Verge is unprofessional until there is a black and white picture of me holding a cat on the website. something like this: https://i.pinimg.com/736x/d1/68/0d/d1680d5e8f4e0e857bcd681b52c21067--cat-people-vintage-cat.jpg

**Comment by buzztiaan** [comment]
but pose like the parishilton20170904 post that killed all ICOs!

**Comment by mjanveaux** [comment]
This issue should be closed.
