### ISSUE TITLE
QT-Wallet 4.0.2 Windows 10: 'loading block index' takes very long

### ISSUE THREAD

**Issue by swat69** [vergecurrency/VERGE#710]
Using a Core-i7, 3.3GHz:
block index         4108117ms = 68 min
--------------------------------------------------

VERGE version v4.0.2.0-c3a04c0-funky-beta (2018-04-12 06:06:47 +0000)
Using OpenSSL version OpenSSL 1.0.2k  26 Jan 2017
Startup time: 04/13/18 06:49:57
Default data directory C:\Users\xx\AppData\Roaming\VERGE
Default mining hash algorithm: scrypt
Used data directory C:\Users\xxt\AppData\Roaming\VERGE
scrypt: using scrypt-sse2 as detected.
dbenv.open LogDir=C:\Users\xx\AppData\Roaming\VERGE\database ErrorFile=C:\Users\xx\AppData\Roaming\VERGE\db.log
Bound to 127.0.0.1:21102
TOR thread started.
AddLocal(rqpwgoz3f2fxhyd2.onion:21102,4)
Loading block index...
Opening LevelDB in C:\Users\xx\AppData\Roaming\VERGE\txleveldb
Transaction index version is 70509
Opened LevelDB successfully
No OBFS4 found, not using it.
LoadBlockIndex(): hashBestChain=baf03e33c5950b6eb817686ac0ce0d931a8be8d54be990787c228857b41b7310  height=2054071  trust=2054072  date=04/12/18 16:16:53
LoadBlockIndex(): synchronized checkpoint 00000fc63692467faeb20cdb3b53200dc601d75bdfa1001463304cc790d77278
Verifying last 2500 blocks at level 1
 block index         4108117ms
Loading wallet...
nFileVersion = 4000200
 wallet                  405ms
Loading addresses...
Loaded 6278 addresses from peers.dat  58ms

**Comment by justinvforvendetta** [comment]
did it do this the second time too? or just the first?

**Comment by swat69** [comment]
not faster at the 2nd or 3rd time

**Comment by jrsikors** [comment]
I concur.  I assumed it would get faster the 2nd time... I wasn't watching exactly but it's definitely 20+ mins where it used to be maybe 10

**Comment by swat69** [comment]
4.0.2 is 32bit !?

**Comment by marpme** [comment]
Well it usually takes very long, I have researched a bit for a better solution but couldn't find any. So if anyone has any idea I would be pleased to try it out.

**Comment by jrsikors** [comment]
It was reasonable on 4.0.1 (about 10 minutes tops)... but 4.0.2 it seems like it almost doubled.

I'm testing again -- if I can keep an eye on it.. I fired it off at 2:30pm central..

**Comment by marpme** [comment]
but as far as I know, there weren't that much changes within the indexing code part. (besides the status update message)

I will run it as well ... started it at 9:36 PM CEST

**Comment by jrsikors** [comment]
Looking at debug log..
Startup time:  4/12/2018 20:33:07
block index     4080079ms

Startup time:  4/13/2018 14:04:46
block index     4009686ms

**Comment by marpme** [comment]
Okay it's definitely slower than before. :(

**Comment by jrsikors** [comment]
CPU / Memory usage isn't pegged or anything.  I'm sittin at 30% CPU and 37% mem usage right now total for the whole PC.

35 minutes and I'm at 50% loading block index

**Comment by marpme** [comment]
haha, nice try @jrsikors, but I actually had a look at the last commits since 4.0.1 and I just saw the "hotfix" from @justinvforvendetta which could have some impact some how. Otherwise there's just some off-topic commits like update readme etc.

**Comment by marpme** [comment]
I honestly cannot confirm this issue on Ubuntu 16.04 LTS (25% after ~3mins) 
Fresh compiled at 80de5df (tag 4.0.2) with full database included.

**Comment by jrsikors** [comment]
3rd attempt included

Looking at debug log..
Startup time: 4/12/2018 20:33:07
block index 4080079ms

Startup time: 4/13/2018 14:04:46
block index 4009686ms

Startup time: 4/13/2018 19:30:56
block index 4012169ms

**Comment by Exteroqs** [comment]
The same thing happens to me, I thought it was normal haha, as nobody complained. Now for example I have a block index of 65% in 28 minutes.
I use Linux 64 (kde neon) with a quad-core i7 processor, apparently only works with a core (emulated)

![screenshot_20180414_023432](https://user-images.githubusercontent.com/37254547/38764952-5d6ca88e-3f8f-11e8-83cf-a006222d5f68.png)

**Comment by justinvforvendetta** [comment]
yeah I noticed this compile is slower on loading the block index as well. I'm really busy and won't have time to look into it until wed or thurs.

**Comment by Positivism** [comment]
Both build and load times are faster on mac with the latest commit.

**Comment by nickscrypto08** [comment]
Hi,

I have recently followed instructions and download as said here https://github.com/vergecurrency/VERGE/wiki/Windows-Verge-QT-Wallet-Beginner's-Guide

everytime i run the Verge-qt it loads the index. though my last block updated to the recent. am i missing anything here ?

**Comment by jrsikors** [comment]
Unfortunately at this point -- it's pretty normal and painful.  Best advice is not to shut it down if you can avoid it... once it loads it's not really too resource intensive to leave running.

We are working on a whole new codebase and whole new wallet... I'd just give an ETA of "sooner rather than later".  

The "loading block index" takes longer the closer to full sync you are.

IE:  
If you have none of the blockchain downloaded, it opens up after a few seconds, because you have no "block index" to load.
If you have the full blockchain downloaded, your "block index" will take an hour or so to validate

It's definitely an issue, and something we definitely are aware of, but there's no fix available at this point.  Just sit tight, we'll fix it soon !

**Comment by mckenzieja** [comment]
Is there a torrent to download the block index?

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
