### ISSUE TITLE
High Sierra — Not Syncing 

### ISSUE THREAD

**Issue by DrFaust3** [vergecurrency/VERGE#712]
Hi folks!

I have just downloaded the new 4.0.2 wallet for Mac High Sierra, and dowloaded +2gb April Blockchain...

Although the wallet opens, it does not begin syncing. It's been open for hours and hours but not a bit of signal and also says "out of sync".(Attached a photo)

Would be glad if you guys could help and thanks a lot! 

<img width="993" alt="screen shot 2018-04-13 at 7 56 50 pm" src="https://user-images.githubusercontent.com/34993541/38748087-a7dc88ec-3f55-11e8-898f-96be6c39997a.png">

**Comment by jrsikors** [comment]
go to help -> debug  .. and post a screenshot of that information screen please

**Comment by jrsikors** [comment]
I'm assuming you have 0 connections in that help -> debug screen

I just assisted another Mac user with the EXACT same problem:
https://github.com/vergecurrency/VERGE/issues/705

give that a read and try those suggestions

**Comment by DrFaust3** [comment]
Thanks a lot for your help man!

**Comment by jrsikors** [comment]
If you go that route, download / unzip electrum, but don't open yet

go here:
https://github.com/vergecurrency/electrum-xvg/blob/master/lib/network.py

right click on the "raw" button , save link as .. and save the network.py file.  

If you unzipped Electrum to like:
C:\electrum-xvg
you want to go to
C:\electrum-xvg\lib
and replace the network.py in that folder with the network.py you downloaded above

**Comment by jrsikors** [comment]
no problem, good luck to ya sorry about Tor !

**Comment by jrsikors** [comment]
i closed the issue but feel free to comment on it -- i will get an e-mail notification if you have any follow up questions

**Comment by DrFaust3** [comment]
I could wait a week and update it when I go back home. And looking forward to the ios app. :)

**Comment by justinvforvendetta** [comment]
@DrFaust3 our qt wallet will still work, you just need to use the obfs4 bridges

**Comment by DrFaust3** [comment]
Thank you so much!
