### ISSUE TITLE
Trojan Virus Identified in New Release - Unable to load VERGEd file

### ISSUE THREAD

**Issue by IndyFix1406** [vergecurrency/VERGE#716]
# Issue Template

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by jrsikors** [comment]
Can you please post a screenshot or post what "type" or Trojan it was labeled as?

**Comment by jrsikors** [comment]
And where did you get the "release" from?

If you got it from this place and this place only:
https://github.com/vergecurrency/VERGE/releases

You are fine and can ignore / exclude the error.

If you downloaded it elsewhere, please let us know immediately where you got it from.

We still want to know what TYPE of Trojan virus your anti virus thinks it is.

**Comment by IndyFix1406** [comment]
Just double checked --- that is exactly where I got the release from.  The only issue with ignoring / excluding the error is that my virus software will not let me replace the VERGEd file without disabling it.  Not sold on doing that.

Here is a screenshot of the trojan files it identified: 

![verge trojan 4 14 2018](https://user-images.githubusercontent.com/38382342/38770592-f4b4f476-3fda-11e8-8591-477863c415b0.JPG)

**Comment by jrsikors** [comment]
Similar issue here that justin posted on:
https://github.com/vergecurrency/VERGE/issues/649

This is a Fuerboos.A!cl:
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Fuerboos.A!cl

What Windows is saying is "We don't know exactly what this is , but we are overly concerned about it".  

Verged has mining capability -- so Windows Defender doesn't like it.

**Comment by justinvforvendetta** [comment]
https://github.com/arangodb/arangodb/issues/4170

it happens all the time. it's a false positive

**Comment by IndyFix1406** [comment]
Thanks for the help --- appreciate it.

**Comment by IndyFix1406** [comment]
Any recommendations about how to get around the windows security --- I've told it to allow, will not.  I checked the link provided above on a similar issue, but does not seem to be leading me in the right direction.  Also, my wallet is up and functional, but I have an April Verge-QT, and a January VERGEd file - whats the consequences of that?

![verge 4 14 2018](https://user-images.githubusercontent.com/38382342/38772267-50a25716-3ff8-11e8-968f-e09b2f806d8e.JPG)

**Comment by justinvforvendetta** [comment]
if you tell it to allow the file, it actually will. i tried it on my windows 10 machine the other day.

**Comment by IndyFix1406** [comment]
had to allow in two different location --- once in where the files were quarantined, the other in the history.  Bizarre redundancy.  Thanks for the help.  Fingers crossed for the 17th.
