### ISSUE TITLE
[BUG] Compiling fails for Windows

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#717]
## Prerequisites

* lastest master branch
* windows 10

## User Story:

* "I'm submitting a ... "
  - [x] bug report

## Compiling log

```shell
...
checking whether we are using the GNU Objective C++ compiler... no
checking whether g++ accepts -g... no
checking dependency style of g++... gcc3
checking for a sed that does not truncate output... /bin/sed
checking for i686-w64-mingw32.static-ar... no
checking for ar... /usr/bin/ar
checking for i686-w64-mingw32.static-ranlib... no
checking for ranlib... /usr/bin/ranlib
checking for i686-w64-mingw32.static-strip... no
checking for strip... /usr/bin/strip
checking for i686-w64-mingw32.static-gcov... no
checking for gcov... /usr/bin/gcov
checking for lcov... no
checking for java... /usr/bin/java
checking for genhtml... no
checking for git... /usr/bin/git
checking for ccache... /usr/bin/ccache
checking for xgettext... /usr/bin/xgettext
checking for hexdump... /usr/bin/hexdump
checking for i686-w64-mingw32.static-pkg-config... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for main in -lmingwthrd... no
configure: error: lib missing
make: *** No rule to make target `check'.  Stop.
cat: src/test-suite.log: No such file or directory
done
```

I think somethings are completely broken in the requirements scripts, but I don't know how to fix them.
But I would love to get them running, because I have to test all sorts of things on windows on well.

Like the `loadingBlockIndex` thingy -> referring to #710 
Either someone explains it to me, or gives me a quick hint to get into it.

**Comment by jrsikors** [comment]
dunno if this helps:
https://github.com/bitcoin/bitcoin/issues/3617

**Comment by justinvforvendetta** [comment]
msys toolchain is the best way to compile verge qt for windows

**Comment by jrsikors** [comment]
@marpme  were you able to to try to compile with what Justin suggested?

**Comment by marpme** [comment]
Still found no way to do it, sorry.

**Comment by jrsikors** [comment]
no worries, just checking !  will leave it open and see if justin has any other thoughts/ideas.

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
