### ISSUE TITLE
v4.0.2.0-c3a04c0-funky-beta not syncring in China

### ISSUE THREAD

**Issue by paulodtna12** [vergecurrency/VERGE#719]
How to sync the wallet in places where the tor is blocked? the wallet version is v4.0.2.0-c3a04c0-funky-beta, windows and linux they are both not working either.
the log file said
"Apr 15 14:08:54.000 [notice] Tor 0.3.2.8-rc-dev opening new log file.
Apr 15 14:08:54.311 [notice] Tor 0.3.2.8-rc-dev running on Windows 8 with Libevent 2.0.21-stable, OpenSSL 1.0.2k, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
Apr 15 14:08:54.311 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Apr 15 14:08:54.311 [notice] Configuration file "C:\Users\paulo\AppData\Roaming\VERGE\tor\torrc" not present, using reasonable defaults.
Apr 15 14:08:54.314 [warn] Path for GeoIPFile (<default>) is relative and will resolve to C:\Users\paulo\Desktop\verge\<default>. Is this what you wanted?
Apr 15 14:08:54.314 [warn] Path for GeoIPv6File (<default>) is relative and will resolve to C:\Users\paulo\Desktop\verge\<default>. Is this what you wanted?
Apr 15 14:08:54.430 [notice] Scheduler type KISTLite has been enabled.
Apr 15 14:08:54.430 [notice] Opening Socks listener on 127.0.0.1:9089
Apr 15 14:08:55.000 [notice] Bootstrapped 0%: Starting
Apr 15 14:08:55.000 [notice] Starting with guard context "default"
Apr 15 14:09:10.000 [notice] Bootstrapped 5%: Connecting to directory server
Apr 15 14:09:10.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Apr 15 14:09:10.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Apr 15 14:09:30.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Apr 15 14:09:30.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Apr 15 14:09:51.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Apr 15 14:09:51.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Apr 15 14:10:11.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations."
tnks a lot!

**Comment by jrsikors** [comment]
could be related to the issue i posted on #718 

in the meantime -- you should be ok to go back and use 4.0.1.  

Keep an eye on both issues in case someone has any advice

**Comment by jrsikors** [comment]
Can you please elaborate on the "obfs4 bridges" for me plz :grin: 

Tor is bundled into the QT.  So are you suggesting running Tor browser separately, set up bridges, keep Tor browser running, and then launch QT?

Or do you just need to install Tor browser, configure it, close down Tor browser, and now the QT will pick up the settings?

**Comment by jrsikors** [comment]
Also @paulodtna12  -- Is 4.0.2 the very first Verge-QT wallet you ever tried?

Or did you have success with previous versions and this is a new problem in 4.0.2 ?

**Comment by paulodtna12** [comment]
all qt wallets have the same problem.

**Comment by paulodtna12** [comment]
@justinvforvendetta how to bild obfs4 bridges?

**Comment by manfire** [comment]
obfs4 174.128.247.178:443 818AAAC5F85DE83BF63779E578CA32E5AEC2115E cert=ApWvCPD2uhjeAgaeS4Lem5PudwHLkmeQfEMMGoOkDJqZoeCq9bzLf/q/oGIggvB0b0VObg iat-mode=0
obfs4 52.14.181.66:9443 978EF73CE5EFB0820415DF4F58769C6681DC7C54 cert=3OFwL8ExFrL4w4jgaRs2Zw3mqhCLYJCgkpmrYWhXrRWcc8apoifG8t0aliu3mWRN/1uYfQ iat-mode=0
obfs4 52.15.115.35:9443 54288F3E4311A75035F4F9A7FA4E4F71EA747400 cert=iwQUV2nwapwb4ycMkj4HZu+lP3yFxCLTDfLNPF9gnQUgmlKzy0hlc2Q+0MxXqlY1l5hDfg iat-mode=0

**Comment by Exteroqs** [comment]
It would be good if that function were integrated into the wallet in case some places restrict the tor networks . Now with the new partner hahaha, I'm sorry, I still do not recover from the impression haha, (it's a good partner but it was not what I expected as a large payment processor haha), well, the Asian country is one of the biggest consumers in that beautiful sector. it would be good to consider it.

**Comment by Exteroqs** [comment]
hi @paulodtna12 if you have debian/ubuntu, you can install the obfs4proxy package. then you have to edit the torrc file that is in /home/user/.VERGE/tor/, if it does not exist you have to create it, you can try this configuration.

BridgeRelay 1
ExtORPort auto
SocksPort 0
ORPort auto
Exitpolicy reject *:*

I do not know if it works, I'm still looking for a configuration that works for me, but I'm a little busy to keep trying, you can look for information on the official website of tor.

**Comment by jrsikors** [comment]
in windows you would want to put the torrc file in:
C:\Users\paulo\AppData\Roaming\VERGE\tor\torrc

**_Apr 15 14:08:54.311 [notice] Configuration file "C:\Users\paulo\AppData\Roaming\VERGE\tor\torrc" not present, using reasonable defaults._**

**Comment by jrsikors** [comment]
What i think you should do ... if possible ... go download the Tor browser.  Install it, configure it to use bridges, get it working.  Then close it down.

Then go find the torrc file from Tor Browser app, and copy it over to:
C:\Users\paulo\AppData\Roaming\VERGE\tor\torrc

I think? :man_shrugging:

**Comment by ryc617** [comment]
After install Tor Browser and it connect to it's network, thren copy torrc from brower app to  C:\Users\paulo\AppData\Roaming\VERGE\tor. There is 0 active,why? 


![tor](https://user-images.githubusercontent.com/38489277/39134590-86e7af9e-4749-11e8-85f2-623610c8d669.png)
[debug.log](https://github.com/vergecurrency/VERGE/files/1938778/debug.log)
[tor.log](https://github.com/vergecurrency/VERGE/files/1938779/tor.log)

**Comment by jrsikors** [comment]
Can you post your torrc file contents please?  Hide or change up anything you think might be sensitive information.

This one said it was fixed because of timezone issue:
https://www.reddit.com/r/TOR/comments/723loa/tor_stuck_connecting_at_85/

Their computer had the right time, but the timezone was not correct ?

**Comment by ryc617** [comment]
This is my torrc contets:
Bridge obfs4 38.229.33.135:41337 8CF38F8AC7CA1ACF6051CACE5C84F3E5B3832CD1 cert=Tt0nbRkCo1IOmLJ37k0pMKbAggNemiGBvfx5I+F7I6t8K1pN9DChK84ZwJSn7KS/9vkJUQ iat-mode=1
Bridge obfs4 192.36.31.71:33930 34A4C60CBE17DA0EBEB87F877BFECD43FE9A20FD cert=YGgV7W0QVO1Ksr51YHBKPL2XKoYvI0gFcwUkQbNSP+iA4T7YWeCf9ELxt4iM0RR74/QYSA iat-mode=0
Bridge obfs4 51.255.44.9:9443 0B75B03C2D54AAC897A854B3AEE9F603D2AE25FB cert=nRBuK0zN6O1F2X/jaDEyEyu17bCB+xiDaUoPRJop/UJBzKC2KjUWKTsIoLIhgYk9iZdAVQ iat-mode=0
DataDirectory C:\Users\sigma\Desktop\Tor Browser\Browser\TorBrowser\Data\Tor
GeoIPFile C:\Users\sigma\Desktop\Tor Browser\Browser\TorBrowser\Data\Tor\geoip
GeoIPv6File C:\Users\sigma\Desktop\Tor Browser\Browser\TorBrowser\Data\Tor\geoip6
Socks5Proxy  *********
UseBridges 1

**Comment by jrsikors** [comment]
and also you can try the ones that @manfire posted, i'm assuming he was posting good bridges you can use:

obfs4 174.128.247.178:443 818AAAC5F85DE83BF63779E578CA32E5AEC2115E cert=ApWvCPD2uhjeAgaeS4Lem5PudwHLkmeQfEMMGoOkDJqZoeCq9bzLf/q/oGIggvB0b0VObg iat-mode=0
obfs4 52.14.181.66:9443 978EF73CE5EFB0820415DF4F58769C6681DC7C54 cert=3OFwL8ExFrL4w4jgaRs2Zw3mqhCLYJCgkpmrYWhXrRWcc8apoifG8t0aliu3mWRN/1uYfQ iat-mode=0
obfs4 52.15.115.35:9443 54288F3E4311A75035F4F9A7FA4E4F71EA747400 cert=iwQUV2nwapwb4ycMkj4HZu+lP3yFxCLTDfLNPF9gnQUgmlKzy0hlc2Q+0MxXqlY1l5hDfg iat-mode=0

**Comment by jrsikors** [comment]
I don't think this would help, but just in case .. make sure you actually close out of the Tor browser once you get your settings.  so the steps would be:

Step 1)  Open Tor browser
Step 2)  Configure, make sure you can get connected
**Step 3)  CLOSE Tor Browser**
Step 4)  Copy torrc to %appdata%\verge\tor
Step 5)  Open QT

Also -- for troubleshooting purposes .. it might be easier to start with a fresh %appdata%/verge directory.

Verge-QT will open up in under 1 minute if you don't have the whole blockchain downloaded.

So consider renaming your %appdata%\verge  folder to like verge_old
then launch qt
then close qt
then copy the torrc to the new %appdata%\verge\tor
then launch qt

**Comment by jrsikors** [comment]
I was able to duplicate problems with your torrc file.  I was also able to successfully connect with this torrc file... nothing more nothing less.

So put this in your torrc file, only these 4 lines, and give it a shot:

```
Bridge obfs4 24.19.127.194:9001 2887B74C6EA7D08AE94141F99DABCD1237900C44
Bridge obfs4 185.22.52.223:443 BA3AACD41D8F7EE69350CC3769BC0C9730049AEB
Bridge obfs4 120.75.38.16:443 A86B9351233A7B903C97C8F9FEB0676A38228804
UseBridges 1
```

**Comment by jrsikors** [comment]
if those don't work -- all i did was go to:
https://bridges.torproject.org/options

and click 'just give me bridges' .. and copy/paste the 3 they give you

I added this before each line:
**_Bridge obfs4_**

and obviously last line should be:
**_UseBridges 1_**

**Comment by ryc617** [comment]
I use your bridges and can connect to network, thank you very much!

**Comment by jrsikors** [comment]
nice!  I'll update the wiki soon with steps, but here they are basically:

Step 1)  close down verge-qt if running
Step 2)  Create a file called torrc and put it in C:\Users\YOU\AppData\Roaming\VERGE\Tor
Step 3)  Find bridges to use, I used https://bridges.torproject.org/options  , it will give you 3 like this:
```
95.105.66.10:9001 906A80FFA1558653CCDD18EF2B2B4B4FB2FC12C8
46.50.174.182:555 7EA650C7CD20527DBC5BA39E0EFECB9CC6FB561C
104.131.154.63:8443 B4AB17DADC1867D61F598658554A4DBEDFCD1548
```
Step 4)  edit torrc in notepad or something similar and put in the 3 lines from step 3.  Add the words "Bridge" and "obfs4" just like below, and don't forget UseBridges 1
```
Bridge obfs4 95.105.66.10:9001 906A80FFA1558653CCDD18EF2B2B4B4FB2FC12C8
Bridge obfs4 46.50.174.182:555 7EA650C7CD20527DBC5BA39E0EFECB9CC6FB561C
Bridge obfs4 104.131.154.63:8443 B4AB17DADC1867D61F598658554A4DBEDFCD1548
UseBridges 1
```

Step 5)  Run Verge-QT

**Comment by liang55** [comment]
I live beijing,not open https://bridges.torproject.org/options，don't get bridge option. use 

Bridge obfs4 24.19.127.194:9001 2887B74C6EA7D08AE94141F99DABCD1237900C44
Bridge obfs4 185.22.52.223:443 BA3AACD41D8F7EE69350CC3769BC0C9730049AEB
Bridge obfs4 120.75.38.16:443 A86B9351233A7B903C97C8F9FEB0676A38228804
UseBridges 1

---------------------------------------------------------------------------------------------------------
xyl@ubuntu:~$ tail -f .VERGE/tor/tor.log 
Jun 28 10:47:54.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:47:54.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:48:00.000 [warn] We were supposed to connect to bridge '24.19.127.194:9001' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running.
Jun 28 10:48:00.000 [warn] Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 50; recommendation warn; host 2887B74C6EA7D08AE94141F99DABCD1237900C44 at 24.19.127.194:9001)
Jun 28 10:48:13.000 [warn] We were supposed to connect to bridge '24.19.127.194:9001' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running.
Jun 28 10:48:13.000 [warn] Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 51; recommendation warn; host 2887B74C6EA7D08AE94141F99DABCD1237900C44 at 24.19.127.194:9001)
Jun 28 10:48:14.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:48:14.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:48:16.000 [warn] We were supposed to connect to bridge '185.22.52.223:443' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running.
Jun 28 10:48:16.000 [warn] Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 52; recommendation warn; host BA3AACD41D8F7EE69350CC3769BC0C9730049AEB at 185.22.52.223:443)
-----------------------------------------------------------------------------------------------------------

xyl@ubuntu:~$ tail -f .VERGE/debug.log 
SOCKS5 connecting n5ln6ke2vc47glpl.onion
ERROR: Error reading proxy response
trying connection 5n4gl3kvntyanp63.onion:21102 lastseen=87.4hrs
SOCKS5 connecting 5n4gl3kvntyanp63.onion
ERROR: Error reading proxy response
trying connection kw5bdikypbbxaf2g.onion:21102 lastseen=125.2hrs
SOCKS5 connecting kw5bdikypbbxaf2g.onion
ERROR: Error reading proxy response
trying connection 5n4gl3kvntyanp63.onion:21102 lastseen=87.4hrs
SOCKS5 connecting 5n4gl3kvntyanp63.onion

**Comment by liang55** [comment]
I live beijing,not open https://bridges.torproject.org/options，don't get bridge option. use

Bridge obfs4 24.19.127.194:9001 2887B74C6EA7D08AE94141F99DABCD1237900C44
Bridge obfs4 185.22.52.223:443 BA3AACD41D8F7EE69350CC3769BC0C9730049AEB
Bridge obfs4 120.75.38.16:443 A86B9351233A7B903C97C8F9FEB0676A38228804
UseBridges 1

xyl@ubuntu:~$ tail -f .VERGE/tor/tor.log
Jun 28 10:47:54.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:47:54.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:48:00.000 [warn] We were supposed to connect to bridge '24.19.127.194:9001' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running.
Jun 28 10:48:00.000 [warn] Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 50; recommendation warn; host 2887B74C6EA7D08AE94141F99DABCD1237900C44 at 24.19.127.194:9001)
Jun 28 10:48:13.000 [warn] We were supposed to connect to bridge '24.19.127.194:9001' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running.
Jun 28 10:48:13.000 [warn] Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 51; recommendation warn; host 2887B74C6EA7D08AE94141F99DABCD1237900C44 at 24.19.127.194:9001)
Jun 28 10:48:14.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:48:14.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:48:16.000 [warn] We were supposed to connect to bridge '185.22.52.223:443' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running.
Jun 28 10:48:16.000 [warn] Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 52; recommendation warn; host BA3AACD41D8F7EE69350CC3769BC0C9730049AEB at 185.22.52.223:443)
xyl@ubuntu:~$ tail -f .VERGE/debug.log
SOCKS5 connecting n5ln6ke2vc47glpl.onion
ERROR: Error reading proxy response
trying connection 5n4gl3kvntyanp63.onion:21102 lastseen=87.4hrs
SOCKS5 connecting 5n4gl3kvntyanp63.onion
ERROR: Error reading proxy response
trying connection kw5bdikypbbxaf2g.onion:21102 lastseen=125.2hrs
SOCKS5 connecting kw5bdikypbbxaf2g.onion
ERROR: Error reading proxy response
trying connection 5n4gl3kvntyanp63.onion:21102 lastseen=87.4hrs
SOCKS5 connecting 5n4gl3kvntyanp63.onion

**Comment by liang55** [comment]
I live beijing,not open https://bridges.torproject.org/options，don't get bridge option. use
```
Bridge obfs4 24.19.127.194:9001 2887B74C6EA7D08AE94141F99DABCD1237900C44
Bridge obfs4 185.22.52.223:443 BA3AACD41D8F7EE69350CC3769BC0C9730049AEB
Bridge obfs4 120.75.38.16:443 A86B9351233A7B903C97C8F9FEB0676A38228804
UseBridges 1
```
tor.log
```
xyl@ubuntu:~$ tail -f .VERGE/tor/tor.log
Jun 28 10:47:54.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:47:54.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:48:00.000 [warn] We were supposed to connect to bridge '24.19.127.194:9001' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running.
Jun 28 10:48:00.000 [warn] Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 50; recommendation warn; host 2887B74C6EA7D08AE94141F99DABCD1237900C44 at 24.19.127.194:9001)
Jun 28 10:48:13.000 [warn] We were supposed to connect to bridge '24.19.127.194:9001' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running.
Jun 28 10:48:13.000 [warn] Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 51; recommendation warn; host 2887B74C6EA7D08AE94141F99DABCD1237900C44 at 24.19.127.194:9001)
Jun 28 10:48:14.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:48:14.000 [warn] We don't have a consensus, so we can't perform v2 rendezvous operations.
Jun 28 10:48:16.000 [warn] We were supposed to connect to bridge '185.22.52.223:443' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running.
Jun 28 10:48:16.000 [warn] Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING; count 52; recommendation warn; host BA3AACD41D8F7EE69350CC3769BC0C9730049AEB at 185.22.52.223:443)
```
verge.log
```
xyl@ubuntu:~$ tail -f .VERGE/debug.log
SOCKS5 connecting n5ln6ke2vc47glpl.onion
ERROR: Error reading proxy response
trying connection 5n4gl3kvntyanp63.onion:21102 lastseen=87.4hrs
SOCKS5 connecting 5n4gl3kvntyanp63.onion
ERROR: Error reading proxy response
trying connection kw5bdikypbbxaf2g.onion:21102 lastseen=125.2hrs
SOCKS5 connecting kw5bdikypbbxaf2g.onion
ERROR: Error reading proxy response
trying connection 5n4gl3kvntyanp63.onion:21102 lastseen=87.4hrs
SOCKS5 connecting 5n4gl3kvntyanp63.onion
```
can you help me ？thanks
