### ISSUE TITLE
getblocktemplate call failed for daemon instance 0 with error {"code":-9,"message":"VERGE is not connected!"}

### ISSUE THREAD

**Issue by jaredthesovereign** [vergecurrency/VERGE#72]
Hi,

Attempting to start the pool via uNOMP and am receiving this error.  Shows as complied via web interface but miners show the pool as Dead. Is it just that I need to wait for the full blockchain to be DL and sync'd or is it something else causing this issue?

:~/VERGE/src$ sudo ./VERGEd
VERGE server starting
:~/VERGE/src$ sudo ./VERGEd getinfo
error: couldn't connect to server

:~$ cd unomp
:~/unomp$ sudo nodejs ./init.js

[2017-09-22 13:31:39.223] [DEBUG] [default] - Pool verge Thread 1 getblocktemplate call failed for daemon instance 0 with error {"code":-9,"message":"VERGE is not connected!"}
[2017-09-22 13:31:39.223] [DEBUG] [default] - Pool verge Thread 1 Error with getblocktemplate on creating first job, server cannot start
[2017-09-22 13:31:39.231] [DEBUG] [default] - Pool verge Thread 2 getblocktemplate call failed for daemon instance 0 with error {"code":-9,"message":"VERGE is not connected!"}
[2017-09-22 13:31:39.232] [DEBUG] [default] - Pool verge Thread 2 Error with getblocktemplate on creating first job, server cannot start

:~/VERGE/src$ sudo ./VERGEd getinfo
{
    "version" : "v2.1.0.0-249ec91-beta",
    "protocolversion" : 90001,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "newmint" : 0.00000000,
    "stake" : 0.00000000,
    "blocks" : 370210,
    "moneysupply" : 11102624999.99999619,
    "connections" : 0,
    "proxy" : "",
    "ip" : "redacted",
    "pow_algo_id" : 0,
    "pow_algo" : "scrypt",
    "difficulty" : 276.30949636,
    "difficulty_x17" : 0.00024414,
    "difficulty_scrypt" : 276.30949636,
    "difficulty_groestl" : 690.03140639,
    "difficulty_lyra2re" : 53.58390531,
    "difficulty_blake" : 0.00024414,
    "testnet" : false,
    "keypoololdest" : 1506054054,
    "keypoolsize" : 101,
    "paytxfee" : 0.10000000,
    "errors" : ""
}

.VERGE\VERGE.conf

rpcuser=redacted
rpcpassword=redacted
server=1
daemon=1
algo=scrypt
listen=0

[2017-09-22 13:16:48.273] [DEBUG] [default] - Pool verge Thread 2 getblocktemplate call failed for daemon instance 0 with error {"code":-9,"message":"VERGE is not connected!"}
[2017-09-22 13:16:48.273] [DEBUG] [default] - Pool verge Thread 2 Error with getblocktemplate on creating first job, server cannot start

*******************************************

unomp\coins\verge.json

{
    "name": "Verge",
    "symbol": "XVG",
    "algorithm": "scrypt"
}

********************************************

unomp\pool_configs\verge.json

{
    "enabled": true,
    "coin": "verge.json",

    "auxes": [    ],
    "address": "redacted",

    "rewardRecipients": {
        //"": 0.5, //0.5% is for pool operations
		
        
    },

    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 30,
        "minimumPayment": 0.1,
        "daemon": {
            "host": "127.0.0.1",
            "port": 20102,
            "user": "redacted",
            "password": "redacted"
        }
    },

    "ports": {
        "7008": {
            "diff": 8
        },
        "7032": {
            "diff": 32,
            "varDiff": {
                "minDiff": 8,
                "maxDiff": 512,
                "targetTime": 15,
                "retargetTime": 90,
                "variancePercent": 30
            }
        },
		"7128": {
            "diff": 128,
			"varDiff": {
                "minDiff": 8,
                "maxDiff": 50000,
                "targetTime": 15,
                "retargetTime": 90,
                "variancePercent": 30
            }
        },		
        "7256": {
            "diff": 256
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 20102,
            "user": "redacted",
            "password": "redacted"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 21102,
        "disableTransactions": false
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 7306,
        "user": "me",
        "password": "mypass",
        "database": "xvg",
        "checkPassword": false,
        "autoCreateWorker": false
    }

}

**Comment by justinvforvendetta** [comment]
yes of course. when you see "error: couldn't connect to server" that means its loading the block index. (cat ~/.VERGE/debug.log would show you that on the last line).

when it finishes loading the block index, it will respond to the getinfo command. give it a few.
