### ISSUE TITLE
4.0.2 Windows Cosmetic Issue thread

### ISSUE THREAD

**Issue by jrsikors** [vergecurrency/VERGE#720]
## Context

I have been losing sleep and contemplating whether or not life is worth living because of this issue.

### Issues

I don't see these issues on Ubuntu, only Windows that I know of...

Issue 1) Might only be for new wallet.dat's
When you first go into the Receiving Addresses, the column widths are pretty uneven.  Label field is way longer than the address field, which gets shrunk and receiving address not fully visible.

![ss3](https://user-images.githubusercontent.com/31370541/38781481-761da47e-40ab-11e8-8b18-2d0f69dbf8e5.PNG)

Issue 2) Basically just change the label on a device ....

![ss1](https://user-images.githubusercontent.com/31370541/38781440-45abfecc-40aa-11e8-8916-14c8c9119686.PNG)

.... and the column width shrinks

![ss2](https://user-images.githubusercontent.com/31370541/38781441-48b01856-40aa-11e8-9927-278a367a5d30.PNG)

**Comment by Positivism** [comment]
This happens on mac as well we can't resize column length, people use ubuntu desktop?

**Comment by jrsikors** [comment]
posting under #555
