### ISSUE TITLE
Balance in wallet doesn't show right amount

### ISSUE THREAD

**Issue by cyberki** [vergecurrency/VERGE#722]
Did send some Verge to my wraith wallet and it shows it was received but it did not updated the balance in my wallet.

Did do some other transaction today to test and that worked just fine balance was updated this time.

The balance in my wallet is now 950 Verge short of what came in on the wallet

How to fix

**Comment by jrsikors** [comment]
Check the https://github.com/vergecurrency/VERGE/wiki/Verge-QT-Wallet-FAQ-&-Common-Issues

There is a section with some steps to try:
https://github.com/vergecurrency/VERGE/wiki/Verge-QT-Wallet-FAQ-%26-Common-Issues#funds-arent-showing
