### ISSUE TITLE
Cannot move XVG from Electrum 2.4 Wallet

### ISSUE THREAD

**Issue by 13entley** [vergecurrency/VERGE#725]
# Issue Template

## Context

Verge stuck in Electrum 2.4 Wallet, cannot get wallet to sync and cannot update wallet

## Prerequisites

Are you running the latest version?
No

## User Story:

* "I'm submitting a ... "
  support request 

## Your Environment

* Verge Release: Electrum Wallet 2.4
* CPU:
* GPU:
* RAM:
* OS: macOS High Sierra

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If anyone can help, I left some XVG in the old Electrum wallet and cannot find anyway to get it to sync to the server in order to transfer it out.  What are my options in order to get the wallet to sync or to use the new Verge 4.0 wallet and move my XVG to there?  

Also, I think the Electrum wallet has an 8 word passphrase if I am correct which I did write down.  Could I use that at all?  

Any input would be appreciated.

Thanks

**Comment by jrsikors** [comment]
If you are on "regular clearnet" electrum, check out my common issues here:
https://github.com/vergecurrency/VERGE/wiki/Electrum-XVG-FAQ-&-Common-Issues

If you are on "Tor electrum" , check out this:
https://github.com/vergecurrency/VERGE/wiki/Electrum-XVG-Tor-FAQ-&-Common-Issues

The instructions are for Macs but you should be able to fairly easily apply them to Mac.
