### ISSUE TITLE
verge solo mining issue

### ISSUE THREAD

**Issue by aprenminer** [vergecurrency/VERGE#728]
verge can be mined alone or not to leave this my question is if verge no longer allows it because I have tried everything and this appears http request failed: failed to connect to 127.0.0.1 port 20102: connection refused [2018-04-08 08 : 12: 50] json_rpc_call failed, retry after 30 seconds I heard it was the firewall as you have to configure it
I'm new to this help my wallet is 4.0.1 funky beta

**Comment by jrsikors** [comment]
Problem 1)  you are on 4.0.1 ... that is not the latest version

Question:  Are you on Windows ?

**Comment by aprenminer** [comment]
can not help me with a complete tutorial that those who are very old
I want to learn

**Comment by aprenminer** [comment]
what localhost use I am using wampserver I do not know if it is correct

**Comment by jrsikors** [comment]
https://github.com/vergecurrency/VERGE#windows-wallet-usage

**Comment by aprenminer** [comment]
In the firewall I do not understand if you have to disable it or how you have to configure it on the Internet, nobody talks about it, it only talks about the configuration of the mining software.
I read something in a forum a topic of opening ports I do not understand

**Comment by aprenminer** [comment]
firewall tutorial please

**Comment by jrsikors** [comment]
you shouldn't need to configure firewall settings to mine XVG.

It should be fairly simple:
1) You install wallet
2) You create / configure verge.conf
3) You run it

**Comment by jrsikors** [comment]
If you have done the verge.conf

Open up VERGE-qt, go to help- > debug ->  console 
run:
**getinfo**
**_getmininginfo_**

and post results here

**Comment by aprenminer** [comment]
I did all that and the error appears
http request failed: failed to connect to 127.0.0.1 port 20102: connection refused [2018-04-08 08:12:50] json_rpc_call failed, retry after 30 seconds
first probe with a miner cpu mined.exe and the error appears and I search the internet I read a comment on this forum https://www.reddit.com/r/vergecurrency/comments/7l0paf/idiot_ahead_solo_mining_help/ about the same problem and someone I solve but I do not understand how to do it

**Comment by justinvforvendetta** [comment]
you have set a rpcuser and rpcpassword in your .conf?

**Comment by aprenminer** [comment]
I have done everything I have reviewed again and again the conf file without being able to connect, but in groups the mining software works is unfair. I want to have the possibility to see how it works just
in this forum https://www.reddit.com/r/vergecurrency/comments/7l0paf/idiot_ahead_solo_mining_help/ someone solved it but I do not understand how to do it
the user was sp3sh
I ask in that forum but they block my question, so I ask for help in this forum about the limit of mining alone. I do not have anyone else to ask for help.
i am new

**Comment by jrsikors** [comment]
Can you please go to your QT wallet, go to help -> debug -> console

and type:
**_getmininginfo_**

and copy/paste the results here.  please block out RPCUSER and RPCPASSWORD if it lists it

**Comment by jrsikors** [comment]
OK where are you on this?

Here's some tips I found:
1)  Make sure your VERGE.conf is named VERGE.conf and is REALLY VERGE.conf .  Windows, by default, has the "hide extension of known files" option on.  So even though it LOOKS like VERGE.conf -- it might be VERGE.conf.txt .   Easy way to check is to open a command prompt, cd over to the directory, and do a "dir"

2)  instead of running verge-qt, run verged

3)  give step 2 a few mins,  open a command prompt and run this command:
netstat -a | findstr 127 | findstr :2

You should be seeing both
127.0.0.1:21102
127.0.0.1:20102

**Comment by jrsikors** [comment]
Have you attempted the steps in my previous comment yet ?

**Comment by aprenminer** [comment]
if I did it the first time I made a mistake, I put VERGE.config and corregi now I put it that way VERGE.conf but it is not connected yet, now the mining software closes quickly in a comment that says the server can be badly configured
my local server runs the wampp server software
a question how to configure the localhost correctly
you have extracted only what are your configurations of your localhost
to test the same configurations.

**Comment by jrsikors** [comment]
Please post the EXACT contents of your latest VERGE.conf

block out the password

**Comment by aprenminer** [comment]
I already managed to connect
these are my settings in the file VERGE.conf
rpcuser = vergerpcusername
rpcpassword = vergecoinS10
rpcallowip = 127.0.0.1
rpcport = 20102
port = 21102
daemon = 1
something = groestl
thanks jrsikors
I discovered the error I had not written the rpcallowip and I was wrong in a rpcport number and in the mining software I had placed -o stratum + tcp: // and it is wrong
you have to place
-o http://127.0.0.1:20102 -u vergerpcusername -p vergecoinS10
the -u place their user of the file VERGE.conf
and in the -p they place their password in the file VERGE.conf

**Comment by aprenminer** [comment]
in the mining software I work with
-o http://127.0.0.1:20102 -u vergerpcusername -p vergecoinS10

**Comment by jrsikors** [comment]
Good to hear  and thank you for posting what worked / didn't work for others

So you are good to go now ?
