### ISSUE TITLE
Verge-qt 4.0.2.0 (mac) Wallet doesn't sync all the way. Wallet remains out of sync.

### ISSUE THREAD

**Issue by jpbuisson** [vergecurrency/VERGE#729]
# Issue Template

## Context

The new Verge-qt 4.0.2.0 (mac) Wallet doesn't sync fully and remains out of sync. The wallet does have many active connections to the VERGE network (16-20 connections) but the syncing abruptly stops after a little while. I have to shut down the wallet and relaunch the wallet for syncing to continue but it does so temporarily before it stops again. It seems like it starts downloading the blockchain at a very fast speed and the speed decreases drastically over time until the syncing stops completely.

## Prerequisites

* [ ] Are you running the latest version?
Yes I am running the latest version of the wallet (Verge-qt 4.0.2.0 mac)

## Your Environment

* Verge Release: v4.0.2.0-80de5df-funky-beta
* CPU: Mac Mini
* GPU: 2.3 Ghz Intel Core i7
* RAM: 4 GB 1600 MHz DDR3
* OS: macOS Sierra v10.12.6

**Comment by jrsikors** [comment]
Are you syncing from scratch or are you using the bootstrap ?

https://github.com/vergecurrency/VERGE/wiki/Verge-QT-Wallet-FAQ-%26-Common-Issues#syncing-is-slow--stuck--will-take-forever

**Comment by jpbuisson** [comment]
I'm not syncing from scratch. Not sure what you mean by syncing from bootstrap but I updated the wallet from an existing version, from the version 4.0. I deleted the existing Verge-qt app and replaced it with the latest 4.0.2. I had to restart the wallet like 10 times so it continue updating the blockchain temporarily before it stops syncing. I started syncing the wallet since yesterday morning before the major partnership announcement and I am still not done syncing. The syncing does happen but at a very slow rate until it stops. Now the last received block was generated 6 days ago compared to yesterday, the last block was generated 14 days ago. It's a very slow progress.

**Comment by jpbuisson** [comment]
The wallet finally synced. It says "wallet" instead of "out of sync". It took forever and many relaunching the wallet to continue the syncing. I think the problem is still there, hopefully it can be resolved.

**Comment by jrsikors** [comment]
Are you syncing your blockchain to an external hard drive or anything like that?  I haven't heard of this issue before.  It's definitely unique to you.

If you are happy, then let's go ahead and close the issue.  

I think you need to write this down and keep this in your back pocket if you continue to have issues.  This is what I would call a "data directory nuke":

Basically you browse to:
~/Library/Application Support/VERGE

You delete everything in there, except for wallet.dat (make sure you back up wallet.dat if you haven't)

Then you will want to download the latest bootstrap so you don't have to sync from scratch:
https://verge-blockchain.com/

Follow the instructions at:
https://verge-blockchain.com/howto

**Comment by jrsikors** [comment]
Can you please post a picture of what you mean by "it says wallet instead of out of sync"
