### ISSUE TITLE
Cannot Send Coins To Any Address (Core Wallet 4.0.2.0, Win 10 64 Bit) 

### ISSUE THREAD

**Issue by AbsolutePower** [vergecurrency/VERGE#730]
# Issue Template

## Context
Wallet synced. No unconfirmed coins. Everytime the transaction is cancelled even though i deduced the transaction fee of 0.10 XVG. Windows 10 64 Bit, Core Wallet 4.0.2.0. 

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by marpme** [comment]
We would need more information about your wallet.
Please fill them as you feel, thank you.

* How much you want to send? 
* To Where you want to send your XVG to? (stealth / normal address)
* How much XVG do you have **or** do you have enough money? 
* Have you tried using an older version (i.e. 4.0.1)?

**Comment by AbsolutePower** [comment]
Hi, please find below my responses inline:

How much you want to send?
Above 10K

To Where you want to send your XVG to? (stealth / normal address)
I assume an exchange (Binance) and an online wallet (Coinomi) would have a normal address? Sorry this my first time sending XVG, so don't really know the difference. 

How much XVG do you have or do you have enough money?
Have enough, yes. 

Have you tried using an older version (i.e. 4.0.1)?
No, because of the hardfork

**Comment by jrsikors** [comment]
I'm slightly confused what you mean by the "transaction is cancelled".  Can you include a screenshot ?

You could try using the 4.0.1 version to send .. even with the hardfork.  There has been confirmed success.

I'd rather not go that route though until we get some more information.

I'm still confused as to what your problem is.. I really need a picture please !

**Comment by jrsikors** [comment]
If you are getting a transaction flat out "**cancelled**" , it could be that you are trying to send XVG coins to a non-XVG address?

**Comment by jrsikors** [comment]
Also keep in mind that the fee is .01 XVG per "KB", NOT per Transaction.

So it's entirely possible you need a higher fee ?

Still thoguh -- I want a picture :smile:

**Comment by AbsolutePower** [comment]
I can provide you a screenshot later (at work now), but it's in German. Yes it says flat out cancelled. Could be transaction fee. Btw it says the minimum is 0.1 so deducted this amount, but if it's in fact more how would I be able to calculate hoe much KB my transaction would cause and thus how much fee i need to pay and deduct from the amount to transfer. Why does the core wallet fail to provide such crucial info in the transfer window? The usability seems a bit limited IMHO.

Also if I didn't consider enough fee why does the wallet not indicate this in an error message and gray out send button? If I don't deduce at least 0.10 XVG and send my whole balance (100% button selected) than it throws the fee error, but only there.

Thanks!

**Comment by jrsikors** [comment]
I agree that the fee calculation in QT and Electrum has room for improvement.  I'm not sure if this is something that can be remedied.  In my experience the fee portion of other QT wallets has similar behavior (or lack of behavior).

If it were ME in your situation and I just wanted to be done with it, I would just put a 1XVG fee, and try to send.

If that doesn't work, try 2 XVG

If that doesn't work, try 3 XVG

and continue on by increments of 1.

**Comment by AbsolutePower** [comment]
Alright, thanks, but where do I adjust the fee? I saw no option in the send window.

**Comment by jrsikors** [comment]
I’ll post a picture later.. it should be right up top underneath where you put the “recipient address.

**Comment by jrsikors** [comment]
Yeah I was way off on that one.

So you need to go to help -> debug -> console

do a:
settxfee 1

then do a:
getinfo

and 3 from the bottom it should have a "paytxfee" .. which should now show 1

so now go back to the UI and see if you can send

**Comment by jrsikors** [comment]
Where are we at on this one?  You figure it all out yet?

**Comment by jrsikors** [comment]
feel free to write comments or re-open if this is still an issue.  Am assuming you have resolved issue.
