### ISSUE TITLE
Android Wallet Verge Tordroid v1.1

### ISSUE THREAD

**Issue by wabalabadubdub** [vergecurrency/VERGE#731]
Support Request 
(maybe bug report)

1.  Verge Tordroid v1.1 shows "No connection".
2.  My first time using the Tordroid app (so I strongly suspect my own ignorance causing this issue)
3.  Sent 5 XVG from exchange to the above address (test amount of 5 XVG to confirm, so no panic).  https://verge-blockchain.info/address/DRmPE5Xrwf1ExKyTXX3zwaXfqkG4ktBckQ
Confirms transaction took place.  
4.  Using HTC ONE ME, Android 5.0.2, all software up to date.  
7.  Running Orbot (16.0.0-RC-2-multi-SDK16) and Verge Tordroid v1.1.  
8.  Verge app enabled in Orbot, followed all instructions as covered in this video here by VergeArmy:  
https://youtu.be/K26u9_Qg9_E
5.  Strongly doubt network connectivity issues.  I'm in ROC, but using a consistent and good quality 4G network, WiFi connection makes no difference to the issue.  

Very grateful for any suggestions on how to get this working.

**Comment by justinvforvendetta** [comment]
try bridges mode?

**Comment by wabalabadubdub** [comment]
Update, no solution yet.  

1.  I had already been using bridges, but yesterday I still spent faaaar too long playing around with different bridge options, all except the 4th one (input manually).  That last one is beyond my technical competence at present.  
2.  Decided to try trouble shooting a different way and find out where the process stops.  
3.  Ran other apps over Orbot and had same issue, no connection.  Apps (like Brave) give message that the browser is not running over Tor.  Orfox runs just fine.  
(Indicates Orbot config problem with external apps on my device.)
4.  Read that superuser access is not required for this version of Orbot.  I do not have root, but unsure if this could be an issue.  
5.  Unable to test XVG wallet without Orbot function so tested different electrum based wallet (Coinomi) and everything works fine, but again, not over Orbot.  My precious 3.5 XVG is safe.
(Indicates wallets should work fine if apps outside Orbot granted permission, I have indicated to Orbot which apps need permission, ie Verge, Brave.)
6.  Google play, I found many, many comments citing similar issues, most gave up.  I don't roll over that easy.  
7.  Goes without saying that I have tried full reboot, Orbot on boot, uninstalling and reinstalling in various combinations of apps and removing any apps that I think may have a "protective" nature like Comodo.
8.  If no more suggestions from VergeGithub, I'll look over at XDA once I get time. It may be something particular with my Android build

Will post back after I have more time to tinker, unless anyone has more suggestions.

**Comment by justinvforvendetta** [comment]
try selecting all apps in the vpn mode.

**Comment by jrsikors** [comment]
closing issue -- but feel free to post any further developments, me and @justinvforvendetta will receive emails

**Comment by wabalabadubdub** [comment]
Close OK.  

NB.  Current Orbot does not support "select all" as in previous versions.  Went through, selected all manually, no success.  

Close thread for now.  Exams loom.  I will continue by hunting Orbot issue on my device, not Tordroid issue.  Will post back here if I find any work around or solution.  Thanks for the help.
