### ISSUE TITLE
Vendor Logo Update

### ISSUE THREAD

**Issue by sunslimited** [vergecurrency/VERGE#733]
Vendor Logo Update

Hello Team I wanted to update my Business Name and Logo in the Vendor site.
Name: Suns Limited IT Solutions, LLC.

![sunslionshield](https://user-images.githubusercontent.com/20092197/39095105-bfdc7edc-4600-11e8-9ad1-d286656a0c04.png)

**Comment by jrsikors** [comment]
will be taken care of per:
https://github.com/vergecurrency/vergecurrency.com/pull/343

It's really not a big deal, but in the future you might want to post under this issues page (for the website) instead:
https://github.com/vergecurrency/vergecurrency.com/issues

Either way -- we'll get ya fixed up !

**Comment by sunslimited** [comment]
Thank you alot Jeff! Have a great day team!!

<https://sunslimited.com>
