### ISSUE TITLE
Sudo Required for Linux Ubuntu

### ISSUE THREAD

**Issue by BlueManRising** [vergecurrency/VERGE#737]
# Issue Template

## Prerequisites

* [X] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [X] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior
Ubuntu desktop link to open VERGE wallet.

## Current Behavior
Currently VERGE will cause error:

A fatal error occurred. VERGE can no longer continue safely and will quit.

EXCEPTION:
N5boost12interprocess22interprocess_exceptionE
Permission denied
VERGE in Runaway exception

## Screenshots

![screenshot from 2018-04-29 20-54-13](https://user-images.githubusercontent.com/34865074/39412930-260b7cbc-4bf1-11e8-8d7f-120766b46aee.png)

## Possible Solution

currently running in sudo from the Terminal fixes the issue, suggest if this is the way it needs to run, will have to update the desktop link to enter sudo.

## Steps to Reproduce (for bugs)

Install via go.sh 

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [x] I'm using Linux
    - [ ] I'm using Mac

**Comment by malt0se** [comment]
But why?

There surely will be a question "What exactly does this wallet need the sudo privileges for?"

Besides, gksu is deprecated (https://tracker.debian.org/pkg/gksu)

**Comment by malt0se** [comment]
As i understand, it is the 110-115 "Runaway exception" in src/qt/bitcoin.cpp

**Comment by malt0se** [comment]
So this user can do sudo, but he doesn't have 755 rights in his own $HOME?

So instead of this user doing "sudo chmod -R +rwx $HOME" (which is weird) or creating new user with required rights - 

instead of all this,

all users should run VERGE-qt with sudo rights? Is this correct?

**Comment by justinvforvendetta** [comment]
i couldn't replicate what you are talking about. i've ran go.sh on a fresh ubuntu install (versions 16, 17, and 18), and was able to run the daemon, and qt without needing any su privs. so, the answer to your question "all users should run VERGE-qt with sudo rights?" is absolutely not, unless their permissions are all screwy for some reason, (no longer default) and that's the only way they can get it running.

**Comment by malt0se** [comment]
All i meant is that if the "gksu" proposal would have been implemented in desktop icon, then all users would run VERGE-qt with sudo privileges, whether they like it or not.

**Comment by jrsikors** [comment]
We are primarily talking about the desktop icon...

I would agree with OP that creating an icon on the desktop that doesn't work when you click it right after a compile is something that needs to be addressed.... **if that's the case for all users**.

I will try to replicate later:
 step 1)  Fresh compile
 step 2)  double click icon on desktop

If it works for some, then it's not a problem we could fix IMO, and the problem resides on the impacted user's configurations.

Another solution would be to stop creating the desktop icon :smile:

**Comment by malt0se** [comment]
But if this problem involve the user permissions, then this issue have nothing to do neither with desktop icons nor with VERGE-qt.

Especially if this particular user have sudo. He should fix his permissions in his own $HOME or create new user altogether.

**Comment by BlueManRising** [comment]
Sorry guys, i was on my honeymoon when this was discussed last week.  I got it running, i had another project i was working on and never changed how my system applied permissions.  But lesson learned, don't do that again.  I have it compiling as is, sorry for any confusion.
