### ISSUE TITLE
js libs for offline sign

### ISSUE THREAD

**Issue by bitcodernull** [vergecurrency/VERGE#738]
# Issue Template

## Context
i want to create transaction and sign it offline with javascript

can i use bitcoin js libs to do it?

thanks

## Prerequisites

* [x] Are you running the latest version?
yes

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [*] support request 
  - [ ] translation request

**Comment by marpme** [comment]
you can find it here: https://www.npmjs.com/package/node-verge

**Comment by jrsikors** [comment]
I think that answered the question right?

**Comment by bitcodernull** [comment]
thanks for answers.

the answer is not my expect
i want to create transaction and sign it offline, not use api of verge node
i don't know if i can use bitcoinjs lib (https://github.com/bitcoinjs/bitcoinjs-lib) ?

**Comment by bitcodernull** [comment]
i use bitcoin js lib to create transaction and sign it
when i broadcast it to node ,i got the error "TX decode failed"
would you like to tell me the difference between verge and bitcoin on transcation-body
thanks

my signed transcation is:
"0100000001472e38f12d6f50f9a0290ee4e02b81b3d4e9f8f84b1bc8a5212381146aa284d6010000006b483045022100a830480e2ada12e19bfc4fa6a274ab9deac4abd3bdabc1ae40f13bc575b1470d022003f77c784ade79154ca07742d9506adae657604ac16a5d1a29b4afd8365b159501210224e066e48e80eca8e9320118c24566707857516fb5061c5e242bf183fd42f3c7ffffffff02e4e7907d510000001976a914996d21b621b2c64e6e10aa4ab6cb240633b1c88088ac40420f00000000001976a914a858c9f34fda8dcf691da6b69292de0c436bbe1188ac00000000"

**Comment by bitcodernull** [comment]
i found the reason 
the transaction body is different with bitcoin: nTIme
