### ISSUE TITLE
Out of Sync wallet 4.0.2 (MAC)

### ISSUE THREAD

**Issue by NiekCrypto** [vergecurrency/VERGE#739]
# Issue Template

I Updated my wallet recently to the new 4.0.2 wallet from a pre-wraith version of the QT wallet. After downloading the new blockchain, it still showed out of sync. I did the commands in the terminal but still my wallet stays "out of sync".
Any suggestions?
Debug Window;

![image](https://user-images.githubusercontent.com/38990824/39650026-42941452-4fac-11e8-8b3a-5abf67cf579e.png)

**Comment by jrsikors** [comment]
You have 0 connections.

Are you in a country that blocks Tor ?  Or any reason why Tor might be blocked?

You can try closing down your QT wallet... go to ~/Library/Application Support/VERGE  .. and delete the peers.dat , and re-open.

If you think it might be Tor related, check out:
https://github.com/vergecurrency/VERGE/wiki/Verge-QT-Wallet-FAQ-%26-Common-Issues#tor-blocked-by-countryisp

**Comment by NiekCrypto** [comment]
It worked, i got it to sync
