### ISSUE TITLE
Verge QT Wallet not accepting my correct Passphrase (code-14)!!

### ISSUE THREAD

**Issue by kimmimoto** [vergecurrency/VERGE#742]
I am currently on Verge QT Wallet 2.1.0.0 for Mac OS and trying to dump my private key before I update to the newer version.

I have looked at other issues on github regarding passphrase and have so far tried after walletlock
walletpassphrase 'my passphrase' 600
walletpassphrase 'my passphrase' 300
walletpassphrase 'my passphrase' 900

I've tried them with and without the ' and also with and without " and checked carefully by typing them out. I know my passphrase is correct because I can unlock my wallet right now. When I do dumpprivkey after unlocking the wallet without doing the walletpassphrase it gives me "wallet is unlocked for minting only" (code-13). Also my outdated qt wallet has not been syncing for nearly 2 weeks now which is why i want to dump my keys before updating. ANY HELP IS APPRECIATED!!!

**Comment by jrsikors** [comment]
What is the actual full error message you are getting when you do a **_walletpassphrase 'my passphrase' 600_**  ?

**Comment by jrsikors** [comment]
Have you made a couple good backups of your wallet.dat file?

What i would do if I was in your situation:
1) Make sure you got a couple good backups of your wallet.dat
2) Change your passphrase via the UI
3) Try again in the debug console using walletpassphrase ... with your new passphrase

I would advise changing it to something simple and straightforward, no crazy !@#$%^&*()"'; type characters.  Even though they are acceptable, they don't help when people start having issues like this.

**Comment by kimmimoto** [comment]
Hi thank you so much for the reply!!

The full error message comes out to "Error: The wallet passphrase entered was incorrect. (code-14)"

You mean go to file --> backup wallet and put it on a hard drive or usb drive correct? Is this okay to do while the wallet is still out of sync? And then settings --> change passphrase? 
Assuming this works, could I go ahead and change back the passphrase or will that do something to the private key? 

Also, in the case that this doesn't work, I had read one of your responses to another passphrase problem where I can use the back up wallet dat to transfer to another computer? I also have a windows desktop that I can download a windows qt wallet or electrum wallet.

**Comment by jrsikors** [comment]
When you do a **_dumpprivkey_** on an encrypted wallet... to do the **_importprivkey_** later, you actually don't need a passphrase.  So make sure you keep extra secure care of the private key.

To answer the other questions:
Yes do a file -> Backup wallet ... it doesn't matter if you are out of sync or not

Then yep do a settings -> change passphrase

You could try changing the passphrase back again to your original, no harm.  So assuming your passphrase now is **_123456_**

You would go to settings -> Change passphrase
Change it from **_123456_** **_abcdefgh_**

Before you change it back though -- at this point I would go to debug console , and try to unlock it with:
walletpassphrase 'abcdefgh' 600

If that works, i'd just do the dumpprivkey right then

You could absolutely 'give it a shot' on a windows machine, without trying any of this.  You would need to do the QT wallet though.  The Electrum wallet won't help unless you have the private key.

**Comment by kimmimoto** [comment]
Hello! It worked!!!!
Now I am two more questions:

1.) I have another wallet address within the same qt wallet that I have XVG in. Can I follow the same step for that address as well? So I will have two private keys?

2.) I plan to just update my outdated V2.1.0 qt wallet on my mac since I have my private keys. Do I just download and the new wallet will override my old wallet or do I need to import my private keys on the new updated qt wallet as well or delete my old wallet?

Thank you for the help!!

**Comment by kimmimoto** [comment]
As in I generated two public addresses within my qt wallet and divided my xvg to those addresses. Do I need to dumpprivkey for the other public address as well so I will have two private keys?

**Comment by kimmimoto** [comment]
thank youII I have figured out the problem.

**Comment by jrsikors** [comment]
:+1:

**Comment by RoX88** [comment]
Hello, i get the exact same error with my correct passphrase.
"Error: The wallet passphrase entered was incorrect. (code-14)" in QT Wallet

I have a backup of my wallet.dat file. How to import it in QT?

**Comment by justinvforvendetta** [comment]
@RoX88 shut down the wallet, then go into your data directory, rename the current wallet.dat file, and then copy the old one into its place. start the wallet up, let it resync with the new keys, and walla.

**Comment by RoX88** [comment]
Thanks for your support!!

I changed the wallet.dat file and now i get with command; **dumpprivkey**
Private key for address ...  is not known (code -4)

Does it mean it is the wrong wallet.dat file?

**Comment by justinvforvendetta** [comment]
if you entered the correct pubkey, then yes its probably the wrong one. youll need to find the wallet.dat that has that address/privkey in it

**Comment by jrsikors** [comment]
just checking...
shut down QT client
make a backup of existing wallet.dat
copy other backup of wallet.dat to directory .. **and make sure it's called exactly wallet.dat** .  When your QT launches, it looks for **wallet.dat** exactly.  If **wallet.dat** doesn't exist, it will just create you a new wallet.

So if you copied your backup wallet file and it's named like "Rox88_xvgbackupwallet.dat" , that wont work.  It has to be **_wallet.dat_** exactly.  

You can store the backups as whatever name you want, but when you want to restore them , copy to the verge data directory and then rename to wallet.dat

Just double checking that's what you did

~Jeff
