### ISSUE TITLE
can not connect the testnode 

### ISSUE THREAD

**Issue by sergiojiu** [vergecurrency/VERGE#744]
Hello,
When I run the verge -testnode .The debug.log in the /root/.VERGE/testnet2 told that "trying connection 188.120.246.137:7777  connect() failed after select(): No route to host ." could tell me how can I deal with it ? thank you very much !

**Comment by pcp1985** [comment]
Pls try checking if you got a server route to reach the ip: 188.120.246.137

**Comment by justinvforvendetta** [comment]
we will be posting new tor and clearnet testnet after the new update is up
