### ISSUE TITLE
Please rebase to newest bitcoin version

### ISSUE THREAD

**Issue by magmel48** [vergecurrency/VERGE#745]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version? Yes.

## User Story:

* "I'm submitting a ... "
  - [ ] feature request

importprivkey RPC command in most modern bitcoin based currencies can be run without rescan.

## Expected Behavior

No rescan if rescan=false specified.

## Current Behavior

Wallet is in rescan process after importprivkey command execution or error if rescan=false param specified.

**Comment by justinvforvendetta** [comment]
we're already doing that in another repository, stay tuned ;]

**Comment by jrsikors** [comment]
https://medium.com/@marpme/e82852b302b4
