### ISSUE TITLE
Block Reward Halving isn't Half original Reward

### ISSUE THREAD

**Issue by D3m0nKingx** [vergecurrency/VERGE#747]
The Block Reward Halving after block 2124000, is showing 730 / block when it should be 780 / block:

1560 / 2 = 780

**Comment by marpme** [comment]
![image](https://user-images.githubusercontent.com/7430964/39914000-01873e14-5504-11e8-9b0f-75fe66aca516.png)

Maybe it's a mistake, but from that point of view I don't think so. 
As it was originally designed to be 730 XVG per Block from the early days on.

**Comment by marpme** [comment]
That's every, there won't be a next halving anymore. The one from 1560 to 730 was the last one.

I think, that they had to drop the halving a bit more, to actually reach the aimed max. circulating supply of 16.555.000.000 XVG. If they would do the halving to 780, they would either:
* faster reach the max supply 
* end with a higher max. XVG supply

**Comment by D3m0nKingx** [comment]
Understood, thank you.

**Comment by D3m0nKingx** [comment]
Btw there should be someone from XVG team that can provide some PR to BitcoinTalk, when matters like this come up :)

**Comment by marpme** [comment]
@D3m0nKingx Going to forward this to our team, thank you for your feedback! 👍

**Comment by justinvforvendetta** [comment]
our schedule of coins has been posted since day 1. (1560 isnt half of 3125 either)
