### ISSUE TITLE
gettransaction returns txid twice, resulting in invalid json reply

### ISSUE THREAD

**Issue by 10thmtn** [vergecurrency/VERGE#749]
# Issue Template

## Context

Reply of rpc call of gettransaction returns invalid JSON reply because of a duplicate key "txid"

Providing context helps us come up with a solution that is most useful in the real world -->

## Prerequisites

* [x] Are you running the latest version?

YEs

## User Story:

* "I'm submitting a ... "
  - [x] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior

txid should only be returned once in the top level JSON

## Current Behavior

the txid key is being returned twice, once at the top of the reply, and again at the bottom

## Possible Solution

Remove the duplicate entry

## Steps to Reproduce (for bugs)

Make any gettransaction call to see the duplicate key

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:  Latest Git Repo
* CPU:  Quad i7
* GPU:  N/a
* RAM:  16gb
* OS:
    - [ ] I'm using Mac
    - [X] I'm using Linux
    - [ ] I'm using Mac

Ubuntu 16.04lts

**Comment by 10thmtn** [comment]
Removing two lines from rpcrawtransaction.cpp fixes this issue, but I'm unsure if it breaks something else:

void TxToJSON(const CTransaction& tx, const uint256 hashBlock, Object& entry)
{
    //entry.push_back(Pair("txid", tx.GetHash().GetHex()));
    entry.push_back(Pair("version", tx.nVersion));
    //entry.push_back(Pair("time", (boost::int64_t)tx.nTime));

**Comment by jrsikors** [comment]
Apologies for the delay.  We are currently going through a major rebasing with bitcoin core.  These types of issues will likely be resolved once complete.  If it's not resolved once completed -- we can re-open the issue to investigate.  

There isn't any desire to look into this at the moment though unfortunately.  

Just sit tight though, we'll get there.

**Comment by genesiszero** [comment]
Have been this bug fixed? Getting transaction is actually one of the core things, not understanding how it went to release without testing.

**Comment by jrsikors** [comment]
We are the first project ever in the history of computers to have bugs in the code.  It's crazy I know!!

You can always do a pull request to help fix the code.

OP had posted a potential workaround until new codebase is released if you are interested.

**Comment by jrsikors** [comment]
I think the dupe txid in the output comes from:
/src/rpcwallet.cpp

comment out line 1303:
`// entry.push_back(Pair("txid", hash.GetHex()));`

I'm not sure why OP commented out the time as well as txid on /src/rpcrawtransaction.cpp

But if you just need to get rid of one txid, either should work
