### ISSUE TITLE
Negative Wallet balance

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#750]
Is it usual that during stealth transactions you wallet account goes in a negative value
and redirects the rest of the value to a newly created account? 

1000 XVG, 100 sent => 
900 XVG back to you with a new address and the 100 XVG goes to an anonymous address
_Thats how I understood it_

<img width="312" alt="grafik" src="https://user-images.githubusercontent.com/7430964/40133310-a00b2a66-593f-11e8-9dc1-e28d68073d77.png">

Is this a bug or is it intended to be like that?

---

And I also did this and everything seems to be okay so far:

<img width="277" alt="grafik" src="https://user-images.githubusercontent.com/7430964/40133447-1b91224e-5940-11e8-8085-2f80d85e59e4.png">

and no, I haven't lost anything - I'm just asking out of curiousity.

**Comment by tokenpay** [comment]
yes accounting is delicate and can go negative. your actual balance can not.

**Comment by jrsikors** [comment]
Totally read that question wrong :laughing:  sorry.

**Comment by tokenpay** [comment]
yeah and your answer is related, the accounting section doesnt account for change or stealth

**Comment by Positivism** [comment]
No this is not normal, this is due to improper RPC use, what commands are you issuing specifically.

**Comment by Positivism** [comment]
@tokenpay Accounting works perfectly fine with stealth and change, unsure what you're referring to.

**Comment by Positivism** [comment]
@jrsikors Sendback(change) is accounted for as the sendback address is generated and assigned to the account.

**Comment by justinvforvendetta** [comment]
listaccounts, sendfromaccount, etc.. these accounts are not a direct representation of the wallet. this functionality was removed from bitcoin,  we use it because it can be accurate if used with precise rpc commands for bots, etc.. but for instance, and exchange would never use it

**Comment by Positivism** [comment]
"accurate if used with precise rpc commands" This.
Negative balance was simply a side-effect.

**Comment by Positivism** [comment]
If your '' account balance remained negative it's due to lack of account balance handling from non broadcasted transactions. As bitcoin both dropped support for accounting and, if I'm not mistaken, intends to remove such functionality; such handling is probably not present and results in false display.
