### ISSUE TITLE
Electrum Wallet - Issues

### ISSUE THREAD

**Issue by ykopeliovich** [vergecurrency/VERGE#751]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:Processor Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz, 4200 Mhz, 4 Core(s), 8 Logical Processor(s)
* GPU: NVIDIA GEFORCE GTX 1060 6GB
* RAM: 32GB
* OS: WIN 10 Pro - Version	10.0.16299 Build 16299
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

## Any extra information that might be useful in the debugging process.

Guys, 
Please help. I am not a programmer and I have no clue how to properly use GitHub. I looked for anyone from the Verge developers to help me out but to no avail. Here is the skinny: Back in Nov '17, i purchased a couple of hundred thousands of XVG coins in an exchange and then i brought the coins into my then newly installed Electrum wallet. I let it sit for over six months and i didn't touch it. I recently decided to check my coins when low and behold the balance shows zero. I doubt that i got hacked during this time duration. I tried to download a new version of the Electrum but nothing helps, i still see zero balance. Can anyone please help? I truly appreciate any assistance. Best regards,

**Comment by jrsikors** [comment]
Question 1)  Do you know which address on the blockchain has your coins?  Can you go to www.verge-blockchain.info .. search for the address .. and find the one with your coins?

Question 2)  Is that address an address in your wallet?

There's a couple FAQs / common issues I wrote up for electrum wallets here:
https://github.com/vergecurrency/VERGE/wiki/Electrum-XVG-FAQ-&-Common-Issues

**Comment by ykopeliovich** [comment]
Hi Jeff,

 

Thank you so much for following up.

 

I was able to find the address and the coins on the blockchain. I will try to see if your link helps out.

 

I will keep you posted.

 

Best regards,

 

Yoel

**Comment by jrsikors** [comment]
Any updates on this ?

**Comment by ykopeliovich** [comment]
Hi Jeff,

Thank you for following up. I was able to identify my coins on the blockchain. Additionally, I was able to restore my prior backed up wallet and now I can see the coins. All of them showing the word “Unverified”. Not sure if it’s ok. Also, it’s weird, when I open the old wallet it doesn’t even ask for a password. Surely, I am better off sending the coins somewhere else.

Thanks so much!

**Comment by jrsikors** [comment]
You only need a password, i believe, to perform certain functions.  I haven't played around enough with the Electrum.

One thing I would suggest ... is to get the private key of the address(es) that have your coins... and securely store them somewhere.

This way you can import the private key(s) later in any wallet you choose... Android, iPhone (soon), QT, Electrum, etc.

You never have to worry about losing your coins due to password / seed type issues if you have the private key for the address.

**Comment by ykopeliovich** [comment]
Got it. Thank you Jeff. I appreciate your help.

**Comment by jrsikors** [comment]
Anytime man !  Don't be shy if you have further questions / issues.  Open a new issue or comment under this one and i'll see an e-mail notification.

Lots of changes coming soon to Verge ... the new QT wallet is going to be S L I C K when it comes out (no ETA).  So keep your eyes open for that one.

**Comment by ykopeliovich** [comment]
Will do! Again, you’ve been more than a pleasure to deal with. Keep up the good work. It’s important to know that you guys care especially considering the challenging times that Verge is facing.

Have a great weekend.
