### ISSUE TITLE
Can not connect to testnet

### ISSUE THREAD

**Issue by mabbas1975** [vergecurrency/VERGE#752]
I am try to connect with testnet without any successful i am just add testnet=1 in config file, should i add
a specific test nodes if so what is it, kindly help

**Comment by jrsikors** [comment]
per @justinvforvendetta on 
https://github.com/vergecurrency/VERGE/issues/687

https://github.com/vergecurrency/VERGE/issues/744

Testnet isn't available at the moment, but will be shortly.
