### ISSUE TITLE
compile error Debian 8: undefined reference to `boost::filesystem::detail::copy_file

### ISSUE THREAD

**Issue by swat69** [vergecurrency/VERGE#759]
commit: #https://github.com/vergecurrency/VERGE/commit/4be6b5acc2e4ade2774bf3e3bc638924f39a7cbf

Debian 8, boost 1.55 (default)

libbitcoin_wallet.a(libbitcoin_wallet_a-walletdb.o): In function `copy_file':
/usr/include/boost/filesystem/operations.hpp:381: undefined reference to `boost::filesystem::detail::copy_file(boost::filesystem::path const&, boost::filesystem::path const&, boost::filesystem::copy_option, boost::system::error_code*)'
collect2: error: ld returned 1 exit status
Makefile:1880: recipe for target 'test_verge' failed

Workaround:
source: https://codeyarns.com/2017/09/20/undefined-reference-to-boost-copy_file/

Edit file db.h:
#define BOOST_NO_CXX11_SCOPED_ENUMS
#include <boost/filesystem.hpp>
#undef BOOST_NO_CXX11_SCOPED_ENUMS

**Comment by marpme** [comment]
@swat69 Shouldn't use Boost 1.60 instead of 1.55

**Comment by jrsikors** [comment]
you still need @justinvforvendetta to take a look at this @swat69 ?  Or you good now ?

**Comment by swat69** [comment]
I use the workaround, no further support for me necessary

**Comment by jrsikors** [comment]
:+1:
