### ISSUE TITLE
Could you start a testnet network?

### ISSUE THREAD

**Issue by designsters** [vergecurrency/VERGE#761]
Why you don't have a testnet network?

**Comment by marpme** [comment]
Testnet will be up when the new release is up and running.

**Comment by mabbas1975** [comment]
we eagerly waiting the testnet, now all my development is stopped and waiting for testnet, when the new
release will issued?

**Comment by Positivism** [comment]
When it's ready.
Luckily, coins are cheap enough to burn if development is pressing;
$1 gets you over 200 transactions.
0.1XVG miner fee sending the same 25 coins ($1) back and forth lasts quite a while

**Comment by justinvforvendetta** [comment]
@mabbas1975 what are you developing?

**Comment by mabbas1975** [comment]
i am working in a new VERGE pool, that supports Lyra2re2, we complete everything and waiting for test on
testnet, i am waiting from 20 days ago, so kindly anybody can help me, the regtest is not a good choice, testnet is better, i am just want to know when the testnet back

**Comment by jrsikors** [comment]
no ETA unfortunately.  We are still working on the rebased codebase.  Last update was 90%.  https://vergecurrency.com/roadmap/

**Comment by marpme** [comment]
@jrsikors Let's close this, there will be no testnet for the old codebase anymore.

**Comment by oliverw** [comment]
@marpme The latest comments where most likely related to the new codebase. At least mine was.

**Comment by justinvforvendetta** [comment]
itll be ready soon

**Comment by viettienbk** [comment]
> i am working in a new VERGE pool, that supports Lyra2re2, we complete everything and waiting for test on
> testnet, i am waiting from 20 days ago, so kindly anybody can help me, the regtest is not a good choice, testnet is better, i am just want to know when the testnet back

@mabbas1975 : how to set up VERSE in regtest mode?

**Comment by viettienbk** [comment]
@karanpatel863 : when will the new codebase release?

**Comment by karanpatel863** [comment]
Planned to be released anytime this month.

**Comment by viettienbk** [comment]
@karanpatel863 : thanks

**Comment by marpme** [comment]
We don't have any official ETA for the upcoming codebase. It's done when its done. Nevertheless we are on good way.

**Comment by karanpatel863** [comment]
Cool. thats why i said "PLANNED".
