### ISSUE TITLE
Local Tor+obfs4proxy and VERGE-qt's Tor thread conflict

### ISSUE THREAD

**Issue by malt0se** [vergecurrency/VERGE#762]
## Context

If Tor(+obfs4proxy) is already installed, then after compiling and launching VERGE-qt there is an error "Timed out waiting for onion hostname":

![timed out waiting for onion hostname](https://user-images.githubusercontent.com/39808902/40802230-b1fd36a8-651d-11e8-84ff-f891b2f6a28e.png)

$HOME/.VERGE/debug.log:
TOR thread started.
Onion thread exited.No onion hostname yet, will retry in 2 seconds... (1/8)
No onion hostname yet, will retry in 2 seconds... (2/8)
No onion hostname yet, will retry in 2 seconds... (3/8)
No onion hostname yet, will retry in 2 seconds... (4/8)
No onion hostname yet, will retry in 2 seconds... (5/8)
No onion hostname yet, will retry in 2 seconds... (6/8)
No onion hostname yet, will retry in 2 seconds... (7/8)
No onion hostname yet, will retry in 2 seconds... (8/8)

There is no tor log ("$HOME/.VERGE/tor/" is empty).

## Steps to Reproduce (for bugs)
* Steps :
1. Do
apt install tor obfs4proxy

2. Add to /etc/tor/torrc
UseBridges 1
ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy
and some "Bridge obfs4 ..." lines

3. Do
service tor restart

4. Back up
your .VERGE directory before rm -rf .VERGE, or just temporarily rename it

5. Run (freshly compiled)
VERGE-qt

* Verge Release: latest 4.0.2a

* OS:
    * Debian Stretch amd64
    * Debian Buster amd64
    * Ubuntu 16.04 amd64

**Comment by marpme** [comment]
Please uninstall/remove/purge your local `tor` client.
`sudo atp-get pruge tor`

and just start the qt-Verge without any `~/VERGE/tor.rc`

Behind the scenes: _The qt Wallet is already start a TOR connection in the background so there's no need to run a local client for that. Also is that one optimized for VERGE usage._

**Comment by malt0se** [comment]
There is a reason why i wrote that:
"Either Tor is not using "--DataDirectory $HOME/.VERGE/tor/" at VERGE-qt launch as it should, or, maybe, the problem is not the Tor DataDirectory at all."

Problem is, VERGE-qt doesn't start tor process during launch (as i said, $HOME/.VERGE/tor/onion is empty, no "hostname" file, no "private_key" file, nothing).
I understand that "The qt Wallet is already hosting a TOR connection internally, so there's no need to run a local client for that".
There is /usr/local/bin/tor, which is installed during VERGE-qt compilation, or are you saying that VERGE-qt doesn't use it?
Port should not be a problem as VERGE-qt should use 9089, so next thing that can cause troubles is DataDirectory. This was just my assumption, as each tor process needs specific DataDirectory. And new tor process (either "local" tor process or "internal" VEGE-qt tor process, whatever it means) will not start , if it uses the same DataDirectory that is already in use by another tor process. And it seems like tor process associated with VERGE-qt doesn't start.

As to "apt-get purge", it would be strange that i decided to write all this without trying "apt purge tor" first.

"apt purge" does not help. One thing that helps is compiling VERGE-qt on completely clean system.
Just in case: reboot dosn't help either, that is why i wrote that DataDirectory is also may not be the reason.

However there should be a possibility to not purge tor (which is in use by many apps on the system) every time i launch wallet, as i have no reason to purge tor every time i launch tor-browser. Otherwise it would be a bit extreme.

**Comment by jrsikors** [comment]
I think you might be getting a couple different problems mixed together into 1.

Even if you have Tor installed separately, that shouldn't matter.

Just don't have your "stand-alone" TOR running when you launch verge-qt.

This section:

> TOR thread started.
> Onion thread exited.No onion hostname yet, will retry in 2 seconds... (1/8)
> No onion hostname yet, will retry in 2 seconds... (2/8)
> No onion hostname yet, will retry in 2 seconds... (3/8)
> No onion hostname yet, will retry in 2 seconds... (4/8)
> No onion hostname yet, will retry in 2 seconds... (5/8)
> No onion hostname yet, will retry in 2 seconds... (6/8)
> No onion hostname yet, will retry in 2 seconds... (7/8)
> No onion hostname yet, will retry in 2 seconds... (8/8

Is where we need to target.

I've seen it in the past where people have had to run Verge-QT multiple times before this finally solves.  QT only tries 8 times... and sometimes 8 just isn't enough.  But if you keep firing it off -- it will eventually find one and you'll be golden.

However -- if you have "Standalone Tor" running while you are trying to do this -- it's possible the 2 TORs are conflicting and your 8x
> No onion hostname yet, 

are because of you trying to run 2 TORs (1 standalone 1 inside Verge-QT)

**Comment by malt0se** [comment]
Ok, i think, i've found the problem.
For the sake of experiment i purged tor again, compiled VERGE-qt, launched it in the console and got the same "Timed out waiting for onion hostname."

BUT

in debug.log i've found this:
...
Default data directory /home/.../.VERGE
Default mining hash algorithm: scrypt
Used data directory /home/.../.VERGE
scrypt: using scrypt-sse2 as built.
dbenv.open LogDir=/home/.../.VERGE/database ErrorFile=/home/.../.VERGE/db.log
Bound to 127.0.0.1:21102
TOR thread started.
Using OBFS4.				<---THIS
Onion thread exited.No onion hostname yet, will retry in 2 seconds... (1/8)
No onion hostname yet, will retry in 2 seconds... (2/8)
No onion hostname yet, will retry in 2 seconds... (3/8)
No onion hostname yet, will retry in 2 seconds... (4/8)
No onion hostname yet, will retry in 2 seconds... (5/8)
No onion hostname yet, will retry in 2 seconds... (6/8)
No onion hostname yet, will retry in 2 seconds... (7/8)
No onion hostname yet, will retry in 2 seconds... (8/8)

and in the console there was:

...
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
/usr/bin/obfs4proxy				<---THIS
... [notice] Tor 0.3.2.8-rc-dev running on Linux with Libevent 2.1.8-stable, OpenSSL 1.1.0h, Zlib 1.2.11, Liblzma N/A, and Libzstd N/A.
... [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
... [notice] Configuration file "/home/.../.VERGE/tor/torrc" not present, using reasonable defaults.
... [warn] Failed to parse/validate config: If you set UseBridges, you must specify at least one bridge.
... [err] Reading config failed--see warnings above.


So VERGE-qt doesn't like installed /usr/bin/obfs4proxy?
Indeed, if i "apt purge obfs4proxy", then VERGE-qt is finally start.
So, in fact, it is not tor DataDirectory conflict after all, it is obfs4proxy conflict. And how to solve this, i don't know. Doing "apt purge obfs4proxy" before launching the VERGE-qt - this is no-go.

**Comment by malt0se** [comment]
Btw, during VERGE-qt compilation there is also /usr/local/bin/tor compiled as a result, but why there is no Pluggable Transport binaries compiled (e.g. /usr/local/bin/obfs4proxy)?

**Comment by malt0se** [comment]
I tried another thing.

GOPATH=$(pwd)
apt -y install golang
go get git.torproject.org/pluggable-transports/obfs4.git/obfs4proxy
sudo cp $GOPATH/go/bin/obfs4proxy /usr/local/bin
VERGE_DATADIR=$HOME/.VERGE
VERGE_TOR_CONFIG=$VERGE_DATADIR/tor/torrc
mkdir -p $VERGE_DATADIR/tor
printf "ClientTransportPlugin obfs4 exec /usr/local/bin/obfs4proxy\n" > $VERGE_TOR_CONFIG

So i've compiled obfs4proxy and installed it to /usr/local/bin, then tried to point VERGE-qt to /usr/local/bin/obfs4proxy. But, alas, to no avail. VERGE-qt returns the same "Timed out waiting for onion hostname." error.
If i remove /usr/local/bin/obfs4proxy, VERGE-qt nonetheless discover that there is still system's /usr/bin/obfs4proxy and returns the same error.

It's strange that after fresh compilation there was "Failed to parse/validate config: If you set UseBridges, you must specify at least one bridge." in the console log.
But there was no Bridges in .VERGE/tor/torrc, moreover, there was no .VERGE directory after fresh compilation/installation.
And this error appears either with /usr/local/bin/obfs4proxy in .VERGE/tor/torrc or if there is no .VERGE directory at all, but there is local /usr/bin/obfs4proxy installed.

As if obfs4proxy being installed, gets VERGE-qt to wait for some bridges to be set, but if i write severeal bridges in .VERGE/tor/torrc, then in .VERGE/tor/tor.log:
"[warn] We were supposed to connect to bridge 'x.x.x.x:y' using pluggable transport 'obfs4', but we can't find a pluggable transport proxy supporting 'obfs4'. This can happen if you haven't provided a ClientTransportPlugin line, or if your pluggable transport proxy stopped running
[warn] Problem bootstrapping. Stuck at 5%: Connecting to directory server. (Can't connect to bridge; PT_MISSING;...)"
And this error message appears even if ClientTransportPlugin line is provided.

Apparently VERGE-qt just can't stand obfs4proxy either system's local or compiled.

I have no more ideas, as to how to get VERGE-qt to work simultaneously with system tor, when system tor is using obfs4proxy.

**Comment by malt0se** [comment]
As i understand correctrly, this part of VERGE/src/net.cpp:

if ((stat("obfs4proxy", &sb) == 0 && sb.st_mode & S_IXUSR) || !std::system("which obfs4proxy")) {
	clientTransportPlugin = "obfs4 exec obfs4proxy";
}

eventually finds out that there is either "/usr/bin/obfs4proxy" or compiled "/usr/local/bin/obfs4proxy" executable binary.

But, man page for Tor states:
ClientTransportPlugin transport socks4|socks5 IP:PORT, ClientTransportPlugin transport exec path-to-binary [options]

So, ClientTransportPlugin requires "path-to-binary" after "exec".
Can somebody tell, how to assign something like "obfs4 exec path-to-obfs4proxy" to "clientTransportPlugin" instead of just "obfs4 exec obfs4proxy"?
Or is this is a relevant thing at all?

**Comment by jrsikors** [comment]
I feel like you are getting ahead of yourself and overthinking this.

Let's try to get back to basics...

There is a difference between:
A)  standalone Tor browser *installed*, but **NOT** running
B)  standalone Tor browser *installed*, and running

Verge-QT should function fine in situation A.
Verge-QT will **NOT** function properly in situation B.

Verge-QT doesn't run a separate Tor process when launched.  It's running within the compiled verge-qt. 

In issue #563 , we determined:
> "The 'problem' is that the Verge-QT app literally exits after it 'times out waiting for onion hostname' ... so no tor logs get generated, no additional debug information available.
> 
> Verge-qt tries to find onion hostname 8 times... and if it can't .. it just quits out."

So we go back to the simpler / more basic situation:
Don't try to RUN a standalone Tor and Verge-QT at the same time, and you should be fine.  If this isn't the case, let's focus on that.

**Comment by jrsikors** [comment]
https://github.com/vergecurrency/VERGE/issues/648 

is another one with a similar issue.  Not much data in terms of what fixed it, but might give you some ideas

**Comment by malt0se** [comment]
i feel like you didn't read/understand what i wrote

**Comment by jrsikors** [comment]
Once I saw this ...

> GOPATH=$(pwd)
> apt -y install golang
> go get git.torproject.org/pluggable-transports/obfs4.git/obfs4proxy
> sudo cp $GOPATH/go/bin/obfs4proxy /usr/local/bin
> VERGE_DATADIR=$HOME/.VERGE
> VERGE_TOR_CONFIG=$VERGE_DATADIR/tor/torrc
> mkdir -p $VERGE_DATADIR/tor
> printf "ClientTransportPlugin obfs4 exec /usr/local/bin/obfs4proxy\n" > $VERGE_TOR_CONFIG
> 
> So i've compiled obfs4proxy and installed it to /usr/local/bin, then tried to point VERGE-qt to /usr/local/bin/obfs4proxy.

and looking at the net.cpp code...

... I realized you went too far off the path of what is supposed to happen.  This really isn't supposed to be that complicated.  I personally believe you are creating way more problems for yourself by doing what you are doing.  I know you are just trying to "fix it" -- but I also don't think there's anything to fix. 

The "preferred way" of installing Verge-QT on UNIX environments works for 99.99% of people just fine :smile:

**Comment by malt0se** [comment]
did you see, what i said about /usr/bin/obsf4proxy and how all works fine without it, even with runnig system tor? All works together: system Tor process, Tor-browser and VERGE-qt. Do you understand?
System Tor and VERGE-qt and even tor-browser works together perfectly fine, 
IF
i just purge system obfs4proxy (i.e. if i'm running system Tor without obfs4 bridges) and compile defaul VERGE-qt as it is, without script i mentioned in first post. OK? All defaults, just without system's /usr/bin/obfs4proxy

BTW. Do you understand, that runnig one app should not imply stoping some important and already working processes beforehand? Why are keep suggesting me that i should stop system Tor if i already said that it is not the issue.

**Comment by malt0se** [comment]
99.99% of people probably are not runnig system Tor process all the time

**Comment by malt0se** [comment]
So you are using Ubuntu?

Can you please do

1. apt install tor obfs4proxy

2.  add 
UseBridges 1
ClientTransportPlugin obfs4 exec /usr/bin/obfs4proxy
and some "Bridge obfs4 ..." lines
to /etc/tor/torrc

3. service tor restart

4. and try to launch VERGE-qt

**Comment by malt0se** [comment]
So, any ideas?
You said that: "This really isn't supposed to be that complicated".
So, please enlighten me as to how do i reconcile "system tor(+obfs4proxy)" and "VERGE-qt", without stopping some running processes or, God forbid, purging some programs?

**Comment by jrsikors** [comment]
Sorry I had a tough week -

I meant it's not supposed to be that complicated because you can just stop Tor, or spin up another instance that doesn't need Tor 24/7.  But I understand now this isn't an answer you are hoping for.

To date, there are no known workarounds.  Perhaps after the re-base, Justin will have time to look at think about this issue.  But it just is what it is at this point.  

Our suggested/known way of using the Verge-QT client on any system is to not have another Tor instance running, due to conflicts and issues.

**Comment by malt0se** [comment]
Because, i think, VERGE-qt finds local obfs4proxy (/usr/bin/obfs4proxy) and apparently is trying to use it.
Eventually, it cant use it, because, i think this parts:

//lines 1652-1654 of net.cpp
if ((stat("obfs4proxy", &sb) == 0 && sb.st_mode & S_IXUSR) || !std::system("which obfs4proxy")) {
	clientTransportPlugin = "obfs4 exec obfs4proxy";
}

//lines 1684-1693 of net.cpp
if (clientTransportPlugin) {
	printf("Using OBFS4.\n");
	argv.push_back("--ClientTransportPlugin");
	argv.push_back(*clientTransportPlugin);
	argv.push_back("--UseBridges");
	argv.push_back("1");
}

are designed for being used with VERGE-qt tor thread.

But first part also finds local obfs4proxy (/usr/bin/obfs4proxy) and trying to use that instead.
But local obfs4proxy (/usr/bin/obfs4proxy) eventually requires not just "obfs4 exec obfs4proxy" as "--ClientTransportPlugin" argument, it needs "path-to-binary" instead of just "obfs4proxy".

Maybe, it can somehow use something like clientTransportPlugin = "obfs4 exec /usr/bin/obfs4proxy" and then propagate it to "--ClientTransportPlugin" argument.

Or, maybe, local obfs4proxy (/usr/bin/obfs4proxy) or any local obfs4proxy instances should not be found at all

**Comment by malt0se** [comment]
Also did you know that VERGE-qt is not using bridges at all? You can write:

UseBridges 1
and some bridges

to $HOME/.VERGE/tor/torrc and VERGE-qt will not connect to these bridges.

VERGE-qt connects and syncing, but i do not see any connection to any of these bridge.

You should put an alert somewhere that if people who live in some dictatorships try to use obfs4 bridges they probably get killed if their dictator doesn't like Tor.

Since VEGE-qt will not use bridges if some is provided.

**Comment by malt0se** [comment]
Moreover, if i comment this part out:

//1652-1654 lines of of net.cpp
if ((stat("obfs4proxy", &sb) == 0 && sb.st_mode & S_IXUSR) || !std::system("which obfs4proxy")) {
	clientTransportPlugin = "obfs4 exec obfs4proxy";
}

then local obfs4proxy(/usr/bin/obfs4proxy) will not block VERGE-qt's tor thread.

So, since VERGE-qt requires obfs4proxy binary installation/compilation, and as obfs4proxy binary search is not implemented correctly, then, i think, there is no harm to comment out 1652-1654 lines of net.cpp and change 1655 line from:
"else if (stat("obfs4proxy.exe", &sb) == 0 && sb.st_mode & S_IXUSR) {"

to

"if (stat("obfs4proxy.exe", &sb) == 0 && sb.st_mode & S_IXUSR) {"

as i can't check wether windows obfs4proxy binary search (1655-1657 lines of net.cpp) is working properly. Maybe there is the same thing for windows, then all obfs4 parts and checks are meaningless.

So, before there is a properly implemented obfs4proxy binary search for linux, 1652-1654 part of net.cpp does not make any sense and it is just blocking VERGE-qt's tor thread for no reason.


PS.
If somebody, who reads this, lives in some dictatorship country and hopes to use VERGE-qt with some private obfs4 bridges and thinks that all he needs is just "stop local tor process" or "purge local obfs4proxy", then he should think again.

**Comment by justinvforvendetta** [comment]
we have bridges hardcoded.

**Comment by malt0se** [comment]
I've checked how Deeponion implements pluggable transport thing:

////////////////////////////////////////////////////////
std::string torPlugin = GetArg("-torplugin", "");
std::string torPluginPath = GetArg("-torpluginpath", "");
..
else if (torPlugin == "obfs4")
{
..
	if ((stat("obfs4proxy", sb) == 0 && (*sb).st_mode & S_IXUSR) || !std::system("which obfs4proxy"))
	{
		plugin = std::string("obfs4 exec ") + std::string(torPluginPath);
	}
..
}

Plus classic config configuration:

torplugin=obfs4
torpluginpath=OBFS4PROXY_PATH (e.g. c:\bin\obfs4proxy.exe or /usr/bin/obfs4proxy)
Bridge ..
Bridge ..
Bridge ..
////////////////////////////////////////////////////////

Obviously, these parts of code in tor related coins were meant to use local pluggable transports.

So, Deeponion devs also didn't bother to implement pluggable transport executable binaries search, but utilize manual pluggable_transport_path/bridges configuration instead.

So, these checks:

if (stat("obfs4proxy.exe", sb) == 0 && (*sb).st_mode & S_IXUSR)
if ((stat("obfs4proxy", sb) == 0 && (*sb).st_mode & S_IXUSR) || !std::system("which obfs4proxy"))

should, apparently, either be coupled

with manual pluggable_transport_path/bridges configuration

or

with pluggable transport executable binaries search

or they should not be used to prevent local Tor's pluggable transport and VERGE-qt's Tor thread conflict.
