### ISSUE TITLE
listaddressgroupings causes daemon to crash

### ISSUE THREAD

**Issue by underdarkskies** [vergecurrency/VERGE#763]
After manually importing private keys into the wallet.dat, attempting to run listaddressgroupings causes the daemon to immediately crash. this is repeatable. particle updated their code with the following commit to avoid this issue: https://github.com/particl/particl-core/commit/abef8bbd1a0b836efd622d66f183c0fde1dcdbb8

**Comment by jrsikors** [comment]
@justinvforvendetta and team are currently working on a complete rebase with bitcoin core 16.  I wouldn't be surprised if this gets taken care of.  

Thank you for pointing out the issue though and bringing it to our attention, we appreciate it!  I don't think there is any interest in putting out a fix for it at this point.  We will definitely take another look after the new codebase rolls out if it continues to be an issue.

**Comment by jrsikors** [comment]
I have made note of this issue and will have team take a look.. and re-open this one if it's NOT fixed after the rollout.  But keeping closed for now!

**Comment by underdarkskies** [comment]
sounds good
