### ISSUE TITLE
rpc call getnetworkinfo not in clearnet branch

### ISSUE THREAD

**Issue by Heraisu** [vergecurrency/VERGE#764]
## Context

Attempting to use a clearnet daemon build for pool, as recommended by another thread (for performance reasons).

## Prerequisites

git 4.0clearnet branch build - VERGEd

## User Story:

* I'm submitting a bug report

Repo:
Build git release on Ubuntu after a switch to 4.0clearnet branch as per instructions on main site.
Run VERGEd -daemon with all the normal config info for pooling.
Attempt to call  getnetworkinfo - fails with "command not recognized" or some variation depending on the RPC client used.

## Expected Behavior

rpc getnetworkinfo returns info just like the master (non-clearnet) is.

## Current Behavior

getnetworkinfo appears to not exist in the clearnet branch.  If I switch back to master and build in the same way, it works fine.

## Your Environment

Ubuntu 16.04

**Comment by Heraisu** [comment]
Added note- other rpc commands, like getinfo (deprecated), or getmininginfo were still responding with data just fine. But getnetworkinfo gets back:
error: {"code":-32601,"message":"Method not found"}

**Comment by marpme** [comment]
We are currently rebasing to the newest bitcoin version, so with that we are already fixing this kind of stuff automatically. Still thank you for the report.

And I honestly recommend you to try out the normal (tor) version. It's way more up to date at the moment.

**Comment by Heraisu** [comment]
I hear you... but of all my daemons, VERGEd uses a LOT more CPU and also is the only one so slow that I can often get blocknotify updates once per second via server query instead of via trigger script from the daemon end... which is sad.  I was hoping the clearnet one would resolve some of these issues, because right now VERGE sticks out like a sore thumb on every performance metric.

**Comment by Positivism** [comment]
With the rebase to the current version things the deprecated getinfo will be removed.
As @marpme said I also recommend using the latest tor branch (main branch).
The latency improvement of clearnet over tor is negligible to finding blocks if your pool is big enough to be a pool.

**Comment by Heraisu** [comment]
This is getting off topic from the issue, but @Positivism I was hoping that it would resolve the ~10% negative luck that pools are seeing from the poor performance. Alas, it looks like the clearnet branch is no better. It's still the only daemon I have that, for some reason, can't seem to keep up with block updates.

The performance is garbage. I see all kinds of strangeness, like how querying for block updates once per second still gets results that blocknotify scripts from the daemon do not, or vica-versa. Again, these are VERGE-specific problems that do not shine well on the platform as a whole.  Generic clones perform better.

**Comment by Positivism** [comment]
They're holding out for the rebase to address everything all at once.
I myself am looking to start a pool soon and await the rebase. Should such problems still exist after the rebase, specific attention will be allocated towards the matter as we love our miners and pool owners and refuse to deal with unreliability when it comes to verge.

Once the rebase is complete expect a perfectly functioning tor as well as clearnet version with all mentioned issues addressed.

**Comment by jrsikors** [comment]
will go ahead and close this up -- but all data noted.  After new codebase, we can reevaluate whether or not this is still an issue, and go from there.
