### ISSUE TITLE
Compile from source code stuck on ubuntu machine

### ISSUE THREAD

**Issue by mcb345** [vergecurrency/VERGE#766]
# Issue Template

## Context

I am trying to build from source on Linux:Ubuntu EC2 , with 8GB Ram but stuck somewhere when I ran these line of command as per guide : 

`sudo rm -Rf ~/VERGE  #(if you already have it)`
`sudo apt-get -y install git && cd ~ && \`
        ` git clone --recurse-submodules https://github.com/vergecurrency/VERGE \`
        ` && cd VERGE && sh go.sh`

on the console, it stuck at : 
`make  all-am`
`make[2]: Entering directory '/home/ubuntu/VERGE/src'`
`  CXX      libbitcoin_server_a-addrman.o`
 ` CXX      libbitcoin_server_a-alert.o`
`  CXX      libbitcoin_server_a-bloom.o`
 ` CXX      libbitcoin_server_a-checkpoints.o`

## Prerequisites

* [x] Are you running the latest version? **Yes, version as per 13/06/2018**

## User Story:

* "I'm submitting a ... "

  - [ ] support request 

## Expected Behavior
Successfully build from the source, and will produce verge daemon also wallet

## Current Behavior
Stuck while compiling

## Screenshots

![image](https://user-images.githubusercontent.com/9096394/41349767-2757cbee-6f3b-11e8-83ce-dee09c6d8089.png)

**Comment by marpme** [comment]
Well everything seems to be fine. Nothing wrong I could spot there, maybe amazon is denying that service somehow, as you are going to the limits of its CPUs. And also the RAM is getting full quite fast. 

Maybe just be more patient? Another problem could also be that your connection dropped, due to inactivity, but that should be the way.

**Comment by Positivism** [comment]
I've compiled verge on a single cpu vps with 2GB of ram before, not a specs issues, probably something with amazon.

**Comment by mcb345** [comment]
@marpme Im not sure whether this is the correct output or not
but as per [https://github.com/vergecurrency/VERGE](url)

I couldnt find step 2 which is : **The wallet GUI is in ./verge/src/qt and the daemon in ./verge/src**

![image](https://user-images.githubusercontent.com/9096394/41355404-a7536794-6f4b-11e8-9030-0745e2014e69.png)

**Comment by marpme** [comment]
@mcb345 start the `./go.sh` with sudo rights.

so you have to start it like that: `sudo ./go.sh`

**Comment by mcb345** [comment]
@marpme installation complete , closing this issue

**Comment by malt0se** [comment]
If he would not have had the required permissions, the error would have been looking something like this: "..: Permission denied"

**Comment by malt0se** [comment]
So, even if compilation in this particular case was successful, the problem is not solved.
