### ISSUE TITLE
EPIPE Socket Error.

### ISSUE THREAD

**Issue by jaredthesovereign** [vergecurrency/VERGE#768]
## Context

My uNOMP-based pool is throwing the following error and I can't seem to resolve it.  I've tried many different remedies such as increasing ulimit via https://stackoverflow.com/questions/21515463/how-to-increase-neo4js-maximum-file-open-limit-ulimit-in-ubuntu

[2018-06-15 14:54:44.837] [DEBUG] [default] - Pool verge Thread 1 Authorized [Address] [IP Address]
[2018-06-15 14:54:44.840] [DEBUG] [default] - Pool verge Thread 1 Socket error from [Address] [IP Address]: {"code":"EPIPE"}

## Your Environment

* Verge Release: 4.0.2a
Ubuntu 14.04.5

Any help or advisement is appreciated.

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
