### ISSUE TITLE
Incorrect help message (number of blocks for mining validation)  [Low priority]

### ISSUE THREAD

**Issue by Heraisu** [vergecurrency/VERGE#774]
[Low priority]
Verge-qt / QUI info message when double clicking on a mined coin transaction incorrectly displays the following help text:

> Generated coins must mature **25** blocks before they can be spent. When you generated this block, it was broadcast to the network to be added to the **block chain**. If it fails to get into the chain, its state will change to "not accepted" and it won't be spendable. This may occasionally happen if another node generates a block within a few seconds of yours.

It appears the actual confirmation block count is now 140. This text should be updated.

**Comment by jrsikors** [comment]
Thanks for the heads up -- pull req created !
