### ISSUE TITLE
Alert system in old bitcoin codebase verge is using.

### ISSUE THREAD

**Issue by karanpatel863** [vergecurrency/VERGE#776]
https://www.coindesk.com/long-secret-bitcoin-key-finally-revealed/amp/?__twitter_impression=true

I read this article which states bitcoin is revealing the key which enables alert system.
Presuming that Verge is using bitcoin's old codebase, has the alert system been deactivated or changed the alert key in verge codebase?

If not then by the time bitcoin reveals the key, anyone will be able to send alert on verge network.
Which does sounds dangerous according to abovementioned article link.

**Comment by marpme** [comment]
Well as we are currently rebasing to a new codebase, we'll have to check if this vulnerability is also applicable to the new one.

**Comment by justinvforvendetta** [comment]
we are moving to bitcoin .17 right now, so we should be fine, but we will double check.

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
