### ISSUE TITLE
VERGE: Error initializing database environment node/.xvg! To recover, BACKUP THAT DIRECTORY, then remove everything from it except for wallet.dat.

### ISSUE THREAD

**Issue by diveyez** [vergecurrency/VERGE#777]
# Issue Template

## Context

I am trying to build the verge wallet and install it. I expect it to work as it did two weeks ago.

## Prerequisites

* [YES] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [X] bug report

## Expected Behavior

libpng warning: iCCP: known incorrect sRGB profile

VERGE: Error initializing database environment /home/diveyez/BLOCKCHAIN/node/.xvg! To recover, BACKUP THAT DIRECTORY, then remove everything from it except for wallet.dat.

I am building on Debian 9 with the installation guide and continuously encounter this error.I did everything it said to do, and it still fails.

**Comment by justinvforvendetta** [comment]
is this a custom configured blockchain datadir? /home/diveyez/BLOCKCHAIN/node/.xvg! ?

did you run the qt with --datadir flag?  you successfully built the daemon and qt, correct?

**Comment by diveyez** [comment]
YES I DID. I have done this before, twice 2 weeks ago on the same OS and system.

**Comment by diveyez** [comment]
Also, it is -datadir=/path/to/.verge

**Comment by justinvforvendetta** [comment]
does that .xvg directory already exist?

**Comment by justinvforvendetta** [comment]
manufacturer wont matter, OS does though. and you tried wiping that directory and starting with an empty .datadir?

**Comment by diveyez** [comment]
Yes I have, is there a solution to this?

**Comment by justinvforvendetta** [comment]
and you did create that .datadir and its empty?

**Comment by justinvforvendetta** [comment]
it looks like you dont have that .datadir and the application doesnt have permission to create it

**Comment by diveyez** [comment]
Yes I do, and it can.
MY older client copy works, but not this newer one.

**Comment by jrsikors** [comment]
What version is your copy that works?

**Comment by jrsikors** [comment]
I looked over the previous commits.. nothing standing out.  But I would need to know how far back to go, based on your "working copy version".

Does it work if you remove the -datadir=xxxxx  and just use default launch?

I understand that's not a fix, but for troubleshooting purposes, it's always best to start from step 1.

**Comment by diveyez** [comment]
I removed everything built from scratch, same issue persists.
