### ISSUE TITLE
Starting verged doesn't open the rpc port

### ISSUE THREAD

**Issue by Darkmagister** [vergecurrency/VERGE#78]
i've have a linux machine that i want to use to min (not using this machine to mine buse using this machine as verged server), i've started verged but from the debug.log i can see that the rpc port is not opening, but the port is open, also if i try with nc to connect it doesn't reply and when i start stratum it can not connect;
so just to be clean i've this config:

rpcuser=vergeuser
rpcpassword=[removed]
rpcallowip=127.0.0.1
rpcport=20102
port=21102
gen=0
daemon=0 (i'm using another tool to start the process as daemon)
algo=x17

am i doing something wrong ?
so from this example only the port 21102 is open no the other one

**Comment by justinvforvendetta** [comment]
can you paste the debug log where it says the rpc port isn't opening? i've never heard of anything like this.

**Comment by Darkmagister** [comment]
i don't receive any error in the debug log just it say opening port 21102 , but not opening port 20102 (the one configured for rpc) also i get connection failed in the stratum process (running in the same machine as verged)

**Comment by justinvforvendetta** [comment]
i would remove daemon=0. also if that doesn't help, please paste some stratum error codes. could be something simple like a permission issue accessing the port when you run the stratum.

**Comment by Darkmagister** [comment]
ok, i've re checked the permission and i think ive made a mistake there, also i see that doesn't seems to write any log for opening the rpc port (also i took a lot of time to load the chain that maybe have created some problem)
so thanks for the support

**Comment by justinvforvendetta** [comment]
yeah  you wont be able to open a stratum until the chain is synced. if you're running a public mining pool feel free to make a pull request on the website and add it to the list of pools
