### ISSUE TITLE
configure: error: libprotobuf not found

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#780]
Protobuf error is back.
```
checking for PROTOBUF... no
configure: error: libprotobuf not found
```

Tried the usual:
```
brew install protobuf
brew upgrade protobuf
brew unlink protobuf
brew link protobuf
```

macOS HighSierra
Something in the latest few commits must've done it.

**Comment by justinvforvendetta** [comment]
hmm im looking around

**Comment by justinvforvendetta** [comment]
no changes have been made to the autoconf...

**Comment by Positivism** [comment]
Hmm, let me try with a previous commit.

**Comment by Positivism** [comment]
This is my first time compiling verge, bare with me.

**Comment by Positivism** [comment]
I did some voodoo magic and found out it was because port was installed.
Fix: Uninstall port. [](https://guide.macports.org/chunked/installing.macports.uninstalling.html)

**Comment by justinvforvendetta** [comment]
interesting that port conflicted with it

**Comment by Positivism** [comment]
I had both brew and port installed, that could possibly be the reason as well.

**Comment by Positivism** [comment]
It probably prioritized port and tried to detect protobuf via that when port was installed and linked via brew.
