### ISSUE TITLE
Connection Refused

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#781]
Latest TOR commit. High Sierra.

<img width="456" alt="screen shot 2018-07-07 at 4 14 34 pm" src="https://user-images.githubusercontent.com/35063339/42414317-0ae75b2c-8201-11e8-8742-5e407ae7c2e4.png">

It's been doing this for quite a while, I thought it was going through old peers.

**Comment by marpme** [comment]
Maybe deleting the “peers.dat” will help you to get rid of those bad quality peers a bit faster

**Comment by Positivism** [comment]
Tried that without luck @marpme

**Comment by marpme** [comment]
@Positivism Clearnet or TOR QT?
If it is on TOR net it seems like you can't connect at all. 
As you will receive an tor address nevertheless of your connection amount.

**Comment by justinvforvendetta** [comment]
hmm ill post a few peers in a few minutes and see if you are able to connect to them

**Comment by justinvforvendetta** [comment]
at first, it found a few bad peers and had a similar reaction, refusing connections and labeling them as misbehaving, but then within another 2-3 minutes it found peers and started syncing

757eh27nmlveq6kq.onion:21102
fsm6hqkr5vffr7mx.onion:21102
y27uvbruynbd2lax.onion:21102

and after i posted this, i now have about 20 peers and its syncing quickly.. this was on a fresh compile, with no datadirectory/peers.dat available before launching..

**Comment by Positivism** [comment]
Forgot to comment here, I added those peers a few minutes after you posted to no avail. It's had this list going for a few hours now non-stop.

**Comment by Positivism** [comment]
`Application Support/VERGE/tor/onion is not owned by this user (root, 0) but by *user* (501). Perhaps you are running Tor as the wrong user?

**Comment by justinvforvendetta** [comment]
so maybe give permissions to the tor datadir or run the daemon without su privs

**Comment by Positivism** [comment]
Chmod is a lot of work to type.

**Comment by Positivism** [comment]
<img width="1085" alt="screen shot 2018-07-08 at 8 34 15 pm" src="https://user-images.githubusercontent.com/35063339/42425674-5c714ea6-82ee-11e8-9b5f-e6d18c30208a.png">
Getting connections, perms issue.

**Comment by Positivism** [comment]
In case someone reads this in the future only give read permissions to the required files&dirs to the user starting the daemon, don't actually 777 your /.

**Comment by pcp1985** [comment]
Would it be better to give a special permission with set-uid or set-gid to
those directory than managing individual files?
