### ISSUE TITLE
Why double fee charged? how it works?

### ISSUE THREAD

**Issue by skironDotNet** [vergecurrency/VERGE#783]
## Context

Tried to sent all shown 155.30 from Verge windows Client, I clicked use 100% button, and it put 155.30 into amount field. I click send button and client complaining not enough funds, so I put 155.20, and client ask if I want to pay 0.10 fee, sure I want, but the recipient got 155.10, so the fee was 0.20, considering millions of transactions who gets the the other 0.1 devs? I'm assuming 0.1 goes to miners?

Example proof from explorer:

![2018-07-12 21_57_03-verge block explorer xvg _ prohashing](https://user-images.githubusercontent.com/2981715/42670293-8593dc8e-861f-11e8-9db4-563760cfab5e.png)

**Comment by skironDotNet** [comment]
#UPDATE
I guess I really sent 155.20 because 0.1 still in my wallet, but why there is no option to indicate I want a fee subtracted from amount sent?

![2018-07-12 22_09_08-verge - wallet](https://user-images.githubusercontent.com/2981715/42670457-9f4d5bd6-8620-11e8-8123-6215df24dbc3.png)

Please try to recreate it by having some balance in the wallet and send everything, how to let the client know to subtract the fee from amount sent. I think it's a but you have to lower amount by 0.1 to be able to sent but then still 0.1 is subtracted from amount sent

**Comment by jrsikors** [comment]
This isn't something we can/would resolve in the current QT wallet.

However we have a lot of things in the works right now, re-basing all the code to one of the latest bitcoin core versions.

@marpme  -- is this option going to be in the new wallet?  "Send max amount" , which will include fee?

**Comment by marpme** [comment]
@jrsikors Took a look at the new wallet, everything is calculated with fee and properly shown how much you are really sending.

![image](https://user-images.githubusercontent.com/7430964/42703231-451e9d6c-86cc-11e8-9066-7e797cf797d4.png)

The max send value is already lowered by the fee and also the button says sending 13.69 XVG (plus a 0.1 XVG fee) and my balance is also shown (13.79 XVG). That's how it works in the new wallet, maybe we shorten the numbers to max of 6 and also text, but it won't change that much.

**Comment by skironDotNet** [comment]
Where is this "new wallet"? I downloaded latest from the vergecurrency website and it looks "old"

**Comment by jrsikors** [comment]
"is this option going to be in the new wallet" --- meaning it's coming soon

**Comment by Positivism** [comment]
@skironDotNet The new wallet has not been released and is still a work in progress inside a private repo. The one from the vergecurrency website is the latest release wallet.
