### ISSUE TITLE
PIN error

### ISSUE THREAD

**Issue by ChefSuziQ** [vergecurrency/VERGE#784]
# PIN code incorrect
## Installed in April 2018 my TOR Android wallet

Tried logging in today but says PIN error. I have tried multiple times using all the usual 4 digit pin combo I use

## Prerequisites

* Yes latest version
![20180718_095503](https://user-images.githubusercontent.com/36816026/42858580-e2b6f732-8a81-11e8-8cf5-62d004afd36e.jpg)

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by jrsikors** [comment]
This isn't really the best place for troubleshooting with Android App.  You will probably get better responses from Telegram / Discord.

But curious -- when is the last time you logged in successfully?
