### ISSUE TITLE
Is there a version with addressindex?

### ISSUE THREAD

**Issue by j4ys0n** [vergecurrency/VERGE#785]
# Issue Template

## Context

**Trying to set up a block explorer using insight**

Providing context helps us come up with a solution that is most useful in the real world -->

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [x] support request 
  - [ ] translation request

**Comment by marpme** [comment]
We do not support BitPay Insight standards at this very moment. 
Please wait for the upcoming release of the new codebase. This will include everything we need for supporting the insight API including further extensions.

**Comment by marpme** [comment]
There's **no real ETA** and we try to stay away from giving one. So please stay patient. It should be ready "quite soon".
