### ISSUE TITLE
Tordroid Connection Issue

### ISSUE THREAD

**Issue by theterribletoo** [vergecurrency/VERGE#797]
Hey someone brought this to my attention yesterday. They could not get the tordroid app to connect. I frequently help with this wallet and havent had much issues.....but this time he couldnt connect and i tried my own wallet and its not connecting. I am not sure anyone is aware yet. Please check it out.

**I am aware on how to connect to orbot and have tried creating a new wallet. No luck.

**Comment by justinvforvendetta** [comment]
it was up when i checked it. going to close this
