### ISSUE TITLE
ERROR: ConnectInputs() : tried to spend coinbase

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#803]
```
ERROR: mempool transaction missing input
ERROR: ConnectInputs() : tried to spend coinbase at depth 42
ERROR: ConnectInputs() : tried to spend coinbase at depth 57
ERROR: ConnectInputs() : tried to spend coinbase at depth 90
ERROR: ConnectInputs() : tried to spend coinbase at depth 52
ERROR: ConnectInputs() : tried to spend coinbase at depth 101
ERROR: ConnectInputs() : tried to spend coinbase at depth 104
ERROR: ConnectInputs() : tried to spend coinbase at depth 61
ERROR: ConnectInputs() : tried to spend coinbase at depth 111
ERROR: ConnectInputs() : tried to spend coinbase at depth 62
ERROR: ConnectInputs() : tried to spend coinbase at depth 34
ERROR: ConnectInputs() : tried to spend coinbase at depth 64
ERROR: ConnectInputs() : tried to spend coinbase at depth 12
ERROR: ConnectInputs() : tried to spend coinbase at depth 58
ERROR: ConnectInputs() : tried to spend coinbase at depth 53
ERROR: ConnectInputs() : tried to spend coinbase at depth 37
ERROR: ConnectInputs() : tried to spend coinbase at depth 112
ERROR: ConnectInputs() : tried to spend coinbase at depth 108
ERROR: ConnectInputs() : tried to spend coinbase at depth 82
```

Did a new clearnet installation on ubuntu 18.04 (Normally I use 16, unsure if it's related) and I'm getting spammed with these in the debug.log

"blocks" : 2449786

Seems to be stuck here.

**Comment by malt0se** [comment]
i didn't touch main.cpp yet, so it has nothing to do with instsllation process, i think.

**Comment by jrsikors** [comment]
You can try to revert this commit I did:
https://github.com/vergecurrency/VERGE/commit/04d41754146319692079e353a61e706c170cc441

When I tested the commit on 14.04 , I don't see similar errors in debug.log

I spun up a Ubuntu 18.04 and had nothing but problems from the get-go.  Really had to battle to get Verge to compile, and even then it never felt 100% right.  I get errors in the debug.log on 18.04 as well like:
`ERROR: FetchInputs() : mempool Tx prev not found`

**Comment by jrsikors** [comment]
Did the commit revert fix it?  I might need to look at it again if that's the case... or at least the clearnet branch.

**Comment by Positivism** [comment]
Installed 16 again instead ages ago, clearnet commit is already quite behind, not worth going back further. Never got to test if the previous commit worked.
