### ISSUE TITLE
[Question] Submitblock

### ISSUE THREAD

**Issue by Positivism** [vergecurrency/VERGE#807]
main.h
```
static const int SAME_ALGO_MAX_COUNT = 5;
```

main.cpp
```
bool CBlock::CheckPrevAlgo(CBlockIndex* pIndex)
{
    unsigned checkedBlocks = 0;
    unsigned sameAlgoBlocks = 0;

    while (pIndex && checkedBlocks != 2*SAME_ALGO_MAX_COUNT)
    {
        if (::GetAlgo(pIndex->nVersion) == GetAlgo())
            ++sameAlgoBlocks;
        
        ++checkedBlocks;
        pIndex = pIndex->pprev;
    }

    if (sameAlgoBlocks > SAME_ALGO_MAX_COUNT)
        return false;

    return true;
}
```

```
// 2*SAME_ALGO_MAX_COUNT = 10 blocks
checkedBlocks != 2*SAME_ALGO_MAX_COUNT)
```

Can we get some clarification on the same algorithm rejection rules for submit block?
It looks like It can take 5 of the same algorithm for every 10 blocks, shouldn't it be 5 of the same algorithm for every 6 which forces the algo to change every max+1.

```
while (pIndex && checkedBlocks != SAME_ALGO_MAX_COUNT+1
``` 

Why not this instead?

**Comment by Positivism** [comment]
@justinvforvendetta @marpme

**Comment by marpme** [comment]
Well to clarify this. In the first `while` iteration you specified the **max searched blocks**. That means we iterate backwards through each block, but we don't want want to search through the entire blockchain until we reach the end, so we specified a max of `2 * MAX_SAME_ALGO_COUNT` as the max search field.

That means `lastBlock; lastBlock - 1; lastBlock - 2; ...; lastBlock - 10; end` and within those ten blocks we should not have more than 6 of the current Algorithm that we are using. And this check is approving this:

```
 if (sameAlgoBlocks > SAME_ALGO_MAX_COUNT)
        return false;
```

Just to clean that up in the best case you should have the same algo 2 time each ten blocks, but sometimes they can skip or replay algos for various reasons, that's why it can most likely vary within 2-3 times per ten blocks.

**Comment by Positivism** [comment]
"in the best case you should have the same algo 2 time each ten blocks" What do you mean?

**Comment by marpme** [comment]
In the meaning that for various reasons blocks can have the same algorithm over and over again.

x17 -> scrypt -> mygrostl-> etc
(Non repetitive) - mentioned case 

x17 -> scrypt -> scrypt -> scrypt -> mygrostl-> etc
(repetitive) - also a normal case

x17 -> scrypt -> scrypt -> scrypt -> scrypt -> scrypt -> scrypt -> mygrostl-> etc
(Simply invalid) 

Both, the first and second structures, are  accepted by our blockchain as it is valid to have max of 5 repeating blocks within. The third one tho is simply invalid due to the six repetitive scrypt blocks.

**Comment by Positivism** [comment]
So it searches the last 10 blocks for a chain of more than 5.
blake -> blake -> blake -> blake -> blake -> scrypt -> blake -> blake -> blake -> blake

Is a valid chain then?

**Comment by marpme** [comment]
Okay let's make another example as yours wouldn't work

Let's say you are checking the current block on the chain, which is using **blake as current algorithm**
and that's your previous chain:

1. Block: x17 _// oldest block of the chain piece_
2. Block: scrypt 
3. Block: mygrostl
4. Block: blake
5. Block: blake
6. Block: scrypt
7. Block: blake
8. Block: blake
9. Block: blake
10. Block: blake _// the most recent block_

**next incoming block: blake** - then the count would go as follows:

10. Block = blake ✅ `=> 1 sameAlgoBlocks`
9. Block = blake ✅`=> 2 sameAlgoBlocks`
8. Block = blake ✅ `=> 3 sameAlgoBlocks`
7. Block = blake ✅ `=> 4 sameAlgoBlocks` _// seems fair until now_
6. Block = scrypt ❌ `=> 4 sameAlgoBlocks` _// still the same, doesn't reset here_
5. Block = blake ✅ `=> 5 sameAlgoBlocks`
4. Block = blake ✅ `=> 6 sameAlgoBlocks`_// done. here we reached the 6th block of the same algo_

... no need to check the rest, but it would never the less return a false as we have more than 6 Blocks of the same algorithm with the last 10 blocks.

**Comment by Positivism** [comment]
So that 11th incoming blake block would get approved?

Why does it count 10 backwards looking for a chain of 5 instead of 6 backwards for consecutive blocks?

And thanks for your help Marpme

**Comment by malt0se** [comment]
So, this sequence would be allowed?
..
.. blake -> scrypt -> blake -> scrypt -> blake -> scrypt -> blake -> scrypt -> blake -> scrypt ..
.. blake -> scrypt -> blake -> scrypt -> blake -> scrypt -> blake -> scrypt -> blake -> scrypt ..
..
etc
..

Wouldn't it be better to have no more than("<=") 20% occurance probability for any algorithm in the span of 10 blocks?

**Comment by Positivism** [comment]
We want block finding to be easier not harder.

**Comment by Positivism** [comment]
The only reason the cap on algorithms was implemented was due to the attack.

**Comment by malt0se** [comment]
Oh, ok. I thought forcing diversity is the main reson.

**Comment by Positivism** [comment]
No, difficulty is adjusted for 'diversity'.

**Comment by malt0se** [comment]
So, in your original question you meant whether it is suffice to check 5 blocks out of 6, to reduce amount of blocks being checked?

I.e. in case of this sequence ".. x, x, x, x, x, y, z, z, z, z, z, i,.."?

That would be:

```shell
..
static const int SAME_ALGO_MAX_COUNT = 5;
..
while (pIndex && checkedBlocks < SAME_ALGO_MAX_COUNT+1)
..
```
This would check only 6 blocks (0, 1, 2, 3, 4, 5) for whether 5 of them have the same algo.

**Comment by malt0se** [comment]
That would be legal?

**Comment by Positivism** [comment]
Now that I think about it why not just check if the last 5 blocks are the same algo rather than checking the last 6/10 then for block succession?

**Comment by malt0se** [comment]
That would discard the ".. x, x, x, x, x, y, z, z, z, z, z, i,.." sequence?

**Comment by malt0se** [comment]
As i understand you correctly, any probability (except 100%) would be suffice

**Comment by malt0se** [comment]
So your proposal would allow up to ~83.3% probability

**Comment by malt0se** [comment]
But is it efficient to have so small blocks sample?

**Comment by Positivism** [comment]
Why would we need a larger sample? Disorganized blocks?

**Comment by malt0se** [comment]
I meant performancewise.
There would be less iterations in the "while" block,
But "5/6 same algo check" would allow up to this sequence:
".. x, x, x, x, x, y, x, x, x, x, x, y, x, x, x, x, x, y, ..",
while "5/10 same algo check" would allow only up to this:
".. a, a, a, a, a, b, b, b, b, b, a, a, a, a, a, .."

Also, to reduce iterations (in case of 6 consecutive blocks with the same algorithm) wouldn't it be better to have
```shell
if (sameAlgoBlocks > SAME_ALGO_MAX_COUNT)
```
incide the "while" block?

**Comment by Positivism** [comment]
Pretty much what I just suggested maltose.

Just grab the last 5 blocks in the chain.
```
If (every algo in array is equal) {
    don't accept that algo in the next block.
}
```

or if you're looping through the index, throw a counter and if any algo count > 5, don't accept that into next block.

**Comment by marpme** [comment]
@malt0se @Positivism those kinds of 10 iterations are like ~100 nanoseconds, due to compiler optimizations and integer comparison. 

As far as I've followed your discussion I can't see the point why we would ever reduce the block iteration size anyway. For me everything seems fine at this point.

**Comment by Positivism** [comment]
@marpme it's not about latency, if it's checking 10 blocks and theres 5 blocks.
x x x x x y z y z x // (I believe) last x is rejected

**Comment by marpme** [comment]
@Positivism Yeah it would reject it and where's the problem now? There have been too many `x`'s within the last 10 blocks. I don't see any leak/performance issue nor a blockchain or a mining issue.

**Comment by Positivism** [comment]
@marpme Block rejection was to mitigate attacks, not make it impossible to profitably mine verge.
Occasionally, the difficulty for an algorithm will spike and when it finally comes back to closer to the nethash more blocks for that algorithm are mined to even it out (hence the difficulty is lowered considerably), when this happens many block rejections happen even when we've had different algorithms in between the 5 consecutive blocks and the next block (or next 5 rather).

Having an algorithm switch is surely important, however, after a block with a new algorithm surfaces the check should be 'reset'.

// accepts a c d e
// denys b
a a a a a b b b b b

// accepts any
a b c d e a b c d e

// accepts b c d e
a a a a a 

// accepts any
b a a a a 

// accepts any
a a a a a b c d e a

Point should have been made. Checks last 5 blocks for the same algorithm, if the last 5 blocks are the same algorithm, force change. 

// 5 detected only accept b c d e 
a a a a a

// b accepted, next block can now be anything including a
a a a a a b

**Comment by malt0se** [comment]
"x x x x x y z y z x // (I believe) last x is rejected"

Maybe to cover this particular situation, increasing probability would be acceptable:
1. "6 out of 10". But that would also allow "x x x x x x y z y z" sequence.
2. "5 out of 9". That would allow your example "x x x x x y z y z x", without additional checks.

**Comment by malt0se** [comment]
Btw, am i missing something, or current code without 
```shell
if (sameAlgoBlocks > SAME_ALGO_MAX_COUNT)
```
inside the "while" block, allows even this sequence "x x x x x x x x y y" or "y y x x x x x x x x", to be precise.

Now, it is just check ALL 10 blocks, preserve the count of the LAST sequence of consecutive blocks with the same algorithm and doesn't interrupt immediately after such sequence is found.

**Comment by malt0se** [comment]
Sorry, mixed up things.
But still "5 out of 9" should do for "x x x x x y z y z x" sequence.

**Comment by Positivism** [comment]
@justinvforvendetta @marpme Thoughts?

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
