### ISSUE TITLE
Passphrase doesnt work anymore

### ISSUE THREAD

**Issue by fangschuss** [vergecurrency/VERGE#809]
Hello,
I am using the Wraith 3.0 wallet, cause i did not send my verge to the 4.0, because i am not able to. The Passphrase i type in is wrong. I am 100% sure, it is the correct one. All the other issue reports did not work for me. i do not know what to do anymore.

thanks for helping

**Comment by jrsikors** [comment]
Go to Help -> Debug -> Console
  a) type walletlock just to check it's locked
  b) type walletpassphrase 'your pass phrase in between single quotes' 600

I wouldn't ever say 100%.  I've seen quite a few people post here saying "I am 100%", and then it ends up being they wrote it down wrong, or purposely wrote it down wrong.  

So please consider that as well and don't settle on "I know this is right".  Think about how it might be slightly different than what you remember.  Passphrases don't just work one day and then not the other.

**Comment by fangschuss** [comment]
i did all that. and it is incorrect. but i copied it out from a word program. can i do anything with those 8 words the wallet gave me?

**Comment by jrsikors** [comment]
The 8 word seed is from the ELECTRUM wallet.. not the QT wallet
