### ISSUE TITLE
#Verge implementation proposal (VIP) - brainstorming on Verge backed Stable coin & offshore Storage as a concept.

### ISSUE THREAD

**Issue by karanpatel863** [vergecurrency/VERGE#810]
Brainstorming.

hello @justinvforvendetta 

i have encountered a project who has implemented this feature. It is a very young project which was forked from Monero inheriting all the features including its privacy features as well as its supply mechanism.
their dev has implemented a very Genius idea of anonymous stable coin with offshore storage. it is currently being tested by closed group of individuals & it is working under testnet environment which will be available for public to test later this month.

the cryptocurrency project i am talking about is a mix of standard market pricing and stable fiat value storage. This is achieved without an unsustainable peg or asset backing. It achieves this with a dual coin blockchain. Users can mint and burn their crypto lets say XVG for the equivalent USD value worth of Verge Dollars XVGD.

They achieve it by their unknown supply. Unknown supply is used to facilitate the fluctuations in the total supply when users burn their crypto to create the stable value other asset like Dollars, while allowing XVG to be exposed to the natural price movements of the market.

the project is named as "HAVEN PROTOCOL" and their main feature is OFFSHORE STORAGE. which is my proposal to implemented in Verge if we can overcome the challenge in implementing it i.e Deflationary nature of Verge VS unknown supply of Haven Protocol. Please dont take me wrong as I still very much support Finite Supply Mechanism. what i am asking is if you think this idea is great for Verge, then is there any way to implement the feature using dual coin blockchain or sidechain in case of Verge while still retaining Verge´s Finite supply mechanism. one of the discussed solution is Freezing that amount of Supply as proposed by Alex.

Offshore Storage is Haven Protocol’s core concept that powers the minting and burning of Haven [XHV] for Haven Dollars [XHVD] and vice versa. In short, sending Haven [XHV] to offshore storage (burning), mints the equivalent USD value worth of the burnt Haven [XHV] in Haven Dollars [XHVD].

Each Haven Dollar [XHVD] is a representation of $1 USD ‘worth of Haven’ which can be transferred to other Haven wallets. Users can also burn their Haven Dollars [XHVD] to mint back the amount of Haven [XHV] of equivalent value.

THE CONVERSION TO & FRO IS ACHIEVED BY USING ORACLE.

An oracle is how a blockchain interacts with the wider internet i.e. an API. We will need to call an API in order to retrieve the current price of coin. the Oracle can be baked into the code. having strict rules in place to ensure that any tampering must be a cost of breaking said rules and thus everyone’s daemons will reject the invalid result. Which solves the Security issue.

When a user burns Haven and mints it back at a later date, they will net a different amount of Haven [XHV] if the price of Haven has changed. If Haven’s [XHV] price increases, they will net less Haven [XHV]. If the price decreases, they will net more Haven [XHV]. In both cases they will have the same amount of USD worth of Haven.

**The key use cases for offshore storage are:**

Point of sales/payment gateway systems where goods can be bought with Haven and stores can immediately lock the USD/fiat value in to protect from price fluctuations. This has the added benefit of keeping the stores'' business and income completely hidden on the blockchain as neither their wallet address or amounts are revealed.

Storing large amount of money outside of the traditional banking system. Privacy focused cryptos are perfect for this but without a reliable way to maintain value through fluctuations the process of holding could be costly. Sending Haven offshore quite literally creates cryptographically untraceable US Dollars.

with the help of uses ring signatures, ring confidential transactions and stealth addresses meaning payments cannot be tracked or linked back to any user.

Wallet addresses and transaction amounts are completely obfuscated on the blockchain making all activity invisible.

it could be decentralized and open source meaning no central control over the network. Nothing is censored.

with this i end my proposal to consider the idea.

Credits go to Haven Protocol Developers as their Documentation has been used in this proposal as well as their IDEA !

DISCLAIMER: AT THE TIME OF WRITING I OWN BOTH VERGE & HAVEN PROTOCOL.

**Comment by justinvforvendetta** [comment]
that honestly makes no sense at all though

**Comment by justinvforvendetta** [comment]
with tor nodes there is no such thing as offshore and you are still pegging the coins value even though you say you arent lol

**Comment by karanpatel863** [comment]
In offshore system you are storing the converted funds lets say XVG to XVGD
in blockchain using dual coin blockchain system. Which interacts with each
other using an Oracle. The proposed idea is currently under testnet and its
working very well in other project. Please have a look at it.

**Comment by karanpatel863** [comment]
I am linking following articles so that you get the idea.

https://medium.com/@havencurrency/haven-protocol-testnet-community-update-a7123b6e0e72

https://medium.com/@havencurrency/our-vision-for-offshore-storage-d4d8bfed9b73

Thanks.

**Comment by justinvforvendetta** [comment]
I wouldn't do anything like this. this is a faith based system that just doesnt make sense. too many outside factors that make it weak :/

**Comment by karanpatel863** [comment]
Cool. Thanks anyway
