### ISSUE TITLE
[Installing] Insufficient permissions for go.sh after cloning git repo

### ISSUE THREAD

**Issue by taahamahdi** [vergecurrency/VERGE#814]
## Context
Using the workaround described at the start of `build-verge-linux.md`, I cannot successfully do `./go.sh` without first changing the permissions of `go.sh` with `chmod u+x go.sh` (at least on Debian).

## Prerequisites
* [X] Are you running the latest version?

## User Story:
* "I'm submitting a ... "
  - [X] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior
`go.sh` should begin execution.

## Current Behavior
`go.sh` does not execute since it is missing the execute bit.

## Possible Solution
`chmod u+x go.sh`

## Your Environment

* Verge Release:
* CPU: Intel Core i5 4690k
* GPU: NVIDIA GTX 1080
* RAM: 16GB DDR3
* OS:
    - [ ] I'm using Mac
    - [x] I'm using Linux
    - [ ] I'm using Mac

Using Debian Stretch running the 4.18 Linux kernel.

### Additional Comments
There are some small issues with the manual Debian building instructions in `build-verge-linux.md` as well (need to use `sudo rm` to remove the boost folder, the `cd` command is a bit off there too), is it alright if I make a PR fixing them?

**Comment by Positivism** [comment]
I believe I saw a 744 permissions merge around here somewhere.

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
