### ISSUE TITLE
Transaction format differences?

### ISSUE THREAD

**Issue by redred77** [vergecurrency/VERGE#822]
I want to create and sign transaction from offline using bitcoinjs-lib (or maybe other libraries)
When I try to send this transaction data to verge daemon, it fails with "TX decode failed" error message.

I've found that verge transaction data is little bit different than general bitcoin format which makes things not compatible.
for example, when I call "bitcoin-cli decoderawtransaction {hex from verge transaction}", output is somewhat strange. Verge also can't decode bitcoin transaction data correctly but outputs "TX decode failed"

I've also found similar issue from below link saying that it's because of "nTime" but there's no clear explaination about it.
https://github.com/vergecurrency/VERGE/issues/738

Can you provide some link or info about what you changed from bitcoin?
What happened with nTime?

**Comment by marpme** [comment]
Yeah that just doesn't work that way, sorry for that. The least complicated solution would be to wait for the new codebase release and additionally for the upcoming https://github.com/vergecurrency/xvg-bitcore-lib

_disclaimer: the named lib above is not functional as of now ..._

**Comment by redred77** [comment]
@marpme 
Can you tell me briefly what things changed for tx format? I think I can tweak libraries if there's some explanation or spec document.
Maybe some hints why verge dev team changed transaction format?

**Comment by justinvforvendetta** [comment]
@redred77 well we have stealth transactions, which is different than a standard transaction, for one..

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
