### ISSUE TITLE
[build fail] ubuntu build VERGE-4.0.2a

### ISSUE THREAD

**Issue by chengmiaook** [vergecurrency/VERGE#825]
# Issue Template

## Context

i download the lastest wallet(https://github.com/vergecurrency/VERGE/releases) ,i download VERGE-4.0.2a.zip,and i unzip it in ubuntu, then i run go.sh,  it buliding,but it fail ,the error is ,help please

Cloning into '/root/VERGE/tor/src/ext/rust'...
fatal: unable to access 'https://git.torproject.org/user/sebastian/tor-rust-dependencies/': Failed to connect to git.torproject.org port 443: Connection refused
fatal: clone of 'https://git.torproject.org/user/sebastian/tor-rust-dependencies' into submodule path '/root/VERGE/tor/src/ext/rust' failed
Failed to clone 'src/ext/rust'. Retry scheduled
Cloning into '/root/VERGE/tor/src/ext/rust'...
fatal: unable to access 'https://git.torproject.org/user/sebastian/tor-rust-dependencies/': Failed to connect to git.torproject.org port 443: Connection timed out
fatal: clone of 'https://git.torproject.org/user/sebastian/tor-rust-dependencies' into submodule path '/root/VERGE/tor/src/ext/rust' failed
Failed to clone 'src/ext/rust' a second time, aborting
Failed to recurse into submodule path 'tor'
/usr/include/boost/version.hpp:#define BOOST_LIB_VERSION "1_65_1"
rm: cannot remove 'wrd01.txt': No such file or directory
rm: cannot remove 'wrd00.txt': No such file or directory
rm: cannot remove 'words': No such file or directory
There is only 1 libboost library present. We choose for you 0
You have choosen 0
./go.sh: line 175: ./configure: No such file or directory
Using default system Berkeley...
make: *** No targets specified and no makefile found.  Stop.
Compile fail not VERGE-qt present

## Prerequisites

* [1 ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [1 ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by chengmiaook** [comment]
i find the https://git.torproject.org/user/sebastian/tor-rust-dependencies/ url not found ,but  https://gitweb.torproject.org/user/sebastian/tor-rust-dependencies/ can found ,how to build sucess

**Comment by justinvforvendetta** [comment]
what country are you in?

**Comment by justinvforvendetta** [comment]
also, dont download the .zip, git clone the repository

**Comment by chengmiaook** [comment]
i use git clone --recurse-submodules https://github.com/vergecurrency/verge,it also fail, it will find the invalid url  https://git.torproject.org/user/sebastian/tor-rust-dependencies/

**Comment by chengmiaook** [comment]
Cloning into '/home/ubuntu/wallet/xvgcoin/verge/tor/src/ext/rust'...
fatal: unable to access 'https://git.torproject.org/user/sebastian/tor-rust-dependencies/': Failed to connect to git.torproject.org port 443: Connection timed out
fatal: clone of 'https://git.torproject.org/user/sebastian/tor-rust-dependencies' into submodule path '/home/ubuntu/wallet/xvgcoin/verge/tor/src/ext/rust' failed
Failed to clone 'src/ext/rust'. Retry scheduled

**Comment by justinvforvendetta** [comment]
just do this:

git clone https://github.com/vergecurrency/verge && cd verge && ./autogen.sh && 
./configure --with-gui=qt5 && make && sudo make install

**Comment by malt0se** [comment]
Can you do

1. apt -y install obfs4proxy
2. Add some bridges (you get some more obfs4 bridges from https://bridges.torproject.org) to "$HOME/.VERGE/tor/torrc" file, like this:

Bridge obfs4 89.36.217.205:39687 F9460ED82B584D74A4A14886D5AF30C3FD9CFC69 cert=sTzusyyMco8GZ5wWm/AfDjfincyPSBGVeROTGE8fx3qi3TNicSwQJOgeWXe0IQx1tRdgTg iat-mode=0
Bridge obfs4 192.99.246.158:443 BEBBB856925F6AB15F993F7EFABC0161658DB0A3 cert=fb3/X7U7Tet2klmeJPBrtTPb0AzoI6WuNlI8Ho+/TdA6P1Tiy/odE0dhAf2ikIg2S7zYJA iat-mode=0
Bridge obfs4 80.44.48.88:62011 01878F1B89B4C7FC3F64A788D93134E8F8D388A3 cert=v9K1t5Qzjd1Gi8xJ+DNY6scuJI0KgPr33+BiYJL2Y482M7eOpvWU3QiO1XcXnDvDiJUcXQ iat-mode=0

**Comment by pcp1985** [comment]
Hi Team

Please could we document these steps... I noticed many times we have
informed users about these steps... Appreciate verge team patience in this
regard.  :)

**Comment by marpme** [comment]
Just create a PR @pcp1985 and we will make sure to check against it 👍

**Comment by chengmiaook** [comment]
i have intall the obfs4proxy,then i run : 

./VERGEd --datadir=/mnt/chainblock/xvg
the output:
Dec 19 10:09:35.525 [notice] Tor 0.3.2.8-rc-dev running on Linux with Libevent 2.0.21-stable, OpenSSL 1.0.2g, Zlib 1.2.8, Liblzma N/A, and Libzstd N/A.
Dec 19 10:09:35.525 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Dec 19 10:09:35.525 [notice] Read configuration file "/mnt/chainblock/xvg/tor/torrc".
Dec 19 10:09:35.528 [notice] Scheduler type KIST has been enabled.
Dec 19 10:09:35.528 [notice] Opening Socks listener on 127.0.0.1:9089

debug.log:
ERROR: Error reading proxy response
trying connection 5n4gl3kvntyanp63.onion:21102 lastseen=104.1hrs
SOCKS5 connecting 5n4gl3kvntyanp63.onion
ERROR: Error reading proxy response
trying connection n5ln6ke2vc47glpl.onion:21102 lastseen=90.3hrs
SOCKS5 connecting n5ln6ke2vc47glpl.onion
ERROR: Error reading proxy response
trying connection 7sfrhwc6l4oohb5h.onion:21102 lastseen=119.8hrs
SOCKS5 connecting 7sfrhwc6l4oohb5h.onion
ERROR: Error reading proxy response
trying connection qjncc5qvylqxqimt.onion:21102 lastseen=101.9hrs
SOCKS5 connecting qjncc5qvylqxqimt.onion

VERGE.conf:
rpcuser=aa
rpcpassword=123456
rpcport=20102
port=21102
daemon=1
algo=groestl

i also find it connection 0,I hung and ran for one night.it also syn error
root@iZt4n9xdp34gs7wuvnZ:/mnt/wallet/xvg/verge/src# ./VERGEd --datadir=/mnt/chainblock/xvg getinfo
{
    "version" : "v4.0.2.0-92ed1c0-funky-beta",
    "protocolversion" : 90001,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "newmint" : 0.00000000,
    "stake" : 0.00000000,
    "blocks" : 11000,
    "moneysupply" : 2200000000.00000000,
    "connections" : 0,
    "proxy" : "",
    "ip" : "0.0.0.0",
    "pow_algo_id" : 4,
    "pow_algo" : "groestl",
    "difficulty" : 0.00024414,
    "difficulty_x17" : 0.00024414,
    "difficulty_scrypt" : 61.34463430,
    "difficulty_groestl" : 0.00024414,
    "difficulty_lyra2re" : 0.00024414,
    "difficulty_blake" : 0.00024414,
    "testnet" : false,
    "keypoololdest" : 1545132030,
    "keypoolsize" : 101,
    "paytxfee" : 0.10000000,
    "isunlocked" : true,
    "errors" : ""
}
What else do I need to do to sync it please

**Comment by zychappy** [comment]
the same problem to me ,
I have to say the docs are not friendly enough to new guys.
not enough info about
the basic guide about install and run ,further guide about test in local,or test in privatenet

**Comment by zychappy** [comment]
or supply  a compiled released version that can run immediately :)

**Comment by justinvforvendetta** [comment]
@zychappy there is a compiled version, on our website and here on this github. how did you miss it?

**Comment by zychappy** [comment]
> @zychappy there is a compiled version, on our website and here on this github. how did you miss it?

I need a node can provide RPC server, not just a wallt

**Comment by marpme** [comment]
you can also use the mac executable and start it as a server by setting in the `VERGE.conf`

**Comment by chengmiaook** [comment]
i install it but is still not syn it @zychappy

**Comment by chengmiaook** [comment]
i counld install it ,and syn it  four day, but it not syn it , it still
 ERROR: Proxy error: connection refused
my server ip is in Singapore;
help me  thanks  ,@justinvforvendetta

**Comment by justinvforvendetta** [comment]
whats your proxy set to? whats netstat lookin like on that port?

**Comment by chengmiaook** [comment]
my proxy is this
Bridge obfs4 89.36.217.205:39687 F9460ED82B584D74A4A14886D5AF30C3FD9CFC69 cert=sTzusyyMco8GZ5wWm/AfDjfincyPSBGVeROTGE8fx3qi3TNicSwQJOgeWXe0IQx1tRdgTg iat-mode=0
Bridge obfs4 192.99.246.158:443 BEBBB856925F6AB15F993F7EFABC0161658DB0A3 cert=fb3/X7U7Tet2klmeJPBrtTPb0AzoI6WuNlI8Ho+/TdA6P1Tiy/odE0dhAf2ikIg2S7zYJA iat-mode=0
Bridge obfs4 80.44.48.88:62011 01878F1B89B4C7FC3F64A788D93134E8F8D388A3 cert=v9K1t5Qzjd1Gi8xJ+DNY6scuJI0KgPr33+BiYJL2Y482M7eOpvWU3QiO1XcXnDvDiJUcXQ iat-mode=0
Bridge obfs4 174.128.247.178:443 818AAAC5F85DE83BF63779E578CA32E5AEC2115E cert=ApWvCPD2uhjeAgaeS4Lem5PudwHLkmeQfEMMGoOkDJqZoeCq9bzLf/q/oGIggvB0b0VObg iat-mode=0
Bridge obfs4 52.14.181.66:9443 978EF73CE5EFB0820415DF4F58769C6681DC7C54 cert=3OFwL8ExFrL4w4jgaRs2Zw3mqhCLYJCgkpmrYWhXrRWcc8apoifG8t0aliu3mWRN/1uYfQ iat-mode=0
Bridge obfs4 52.15.115.35:9443 54288F3E4311A75035F4F9A7FA4E4F71EA747400 cert=iwQUV2nwapwb4ycMkj4HZu+lP3yFxCLTDfLNPF9gnQUgmlKzy0hlc2Q+0MxXqlY1l5hDfg iat-mode=0
Bridge obfs4 38.229.33.135:41337 8CF38F8AC7CA1ACF6051CACE5C84F3E5B3832CD1 cert=Tt0nbRkCo1IOmLJ37k0pMKbAggNemiGBvfx5I+F7I6t8K1pN9DChK84ZwJSn7KS/9vkJUQ iat-mode=1
Bridge obfs4 192.36.31.71:33930 34A4C60CBE17DA0EBEB87F877BFECD43FE9A20FD cert=YGgV7W0QVO1Ksr51YHBKPL2XKoYvI0gFcwUkQbNSP+iA4T7YWeCf9ELxt4iM0RR74/QYSA iat-mode=0
Bridge obfs4 51.255.44.9:9443 0B75B03C2D54AAC897A854B3AEE9F603D2AE25FB cert=nRBuK0zN6O1F2X/jaDEyEyu17bCB+xiDaUoPRJop/UJBzKC2KjUWKTsIoLIhgYk9iZdAVQ iat-mode=0

**Comment by chengmiaook** [comment]
it start info 
root@iZt4n9xdppyk4n3gs7wuvnZ:/mnt/wallet/xvg/verge/src# Dec 24 14:14:37.477 [notice] Tor 0.3.2.8-rc-dev running on Linux with Libevent 2.0.21-stable, OpenSSL 1.0.2g, Zlib 1.2.8, Liblzma N/A, and Libzstd N/A.
Dec 24 14:14:37.477 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Dec 24 14:14:37.478 [notice] Read configuration file "/mnt/chainblock/xvg/tor/torrc".
Dec 24 14:14:37.485 [notice] Scheduler type KIST has been enabled.
Dec 24 14:14:37.485 [notice] Opening Socks listener on 127.0.0.1:9089
@justinvforvendetta

**Comment by chengmiaook** [comment]
the start info 
root@AA:/mnt/wallet/xvg/verge/src# ./VERGEd --datadir=/mnt/chainblock/xvg
VERGE server starting
root@AA:/mnt/wallet/xvg/verge/src# Dec 24 14:14:37.477 [notice] Tor 0.3.2.8-rc-dev running on Linux with Libevent 2.0.21-stable, OpenSSL 1.0.2g, Zlib 1.2.8, Liblzma N/A, and Libzstd N/A.
Dec 24 14:14:37.477 [notice] Tor can't help you if you use it wrong! Learn how to be safe at https://www.torproject.org/download/download#warning
Dec 24 14:14:37.478 [notice] Read configuration file "/mnt/chainblock/xvg/tor/torrc".
Dec 24 14:14:37.485 [notice] Scheduler type KIST has been enabled.
Dec 24 14:14:37.485 [notice] Opening Socks listener on 127.0.0.1:9089

**Comment by chengmiaook** [comment]
@justinvforvendetta

**Comment by chengmiaook** [comment]
it connections zero
oot@AA:/mnt/wallet/xvg/verge/src# ./VERGEd --datadir=/mnt/chainblock/xvg getinfo
{
    "version" : "v4.0.2.0-92ed1c0-funky-beta",
    "protocolversion" : 90001,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "newmint" : 0.00000000,
    "stake" : 0.00000000,
    "blocks" : 69879,
    "moneysupply" : 5596975000.00000000,
    "connections" : 0,
    "proxy" : "",
    "ip" : "0.0.0.0",
    "pow_algo_id" : 4,
    "pow_algo" : "groestl",
    "difficulty" : 0.00024414,
    "difficulty_x17" : 0.00024414,
    "difficulty_scrypt" : 2.82667395,
    "difficulty_groestl" : 0.00024414,
    "difficulty_lyra2re" : 0.00024414,
    "difficulty_blake" : 0.00024414,
    "testnet" : false,
    "keypoololdest" : 1545132030,
    "keypoolsize" : 101,
    "paytxfee" : 0.10000000,
    "isunlocked" : true,
    "errors" : ""
}

**Comment by malt0se** [comment]
@chengmiaook 

Ok, i have finally tested all steps. VERGE-qt is successfully using obfs4proxy.

However, i have similar results:

"ERROR: Error reading proxy response" and "0 active connection to VERGE network"

Don't know what is going on.

**Comment by malt0se** [comment]
@chengmiaook 

Can you do

grep Bootstrapped $HOME/.VERGE/tor/tor.log

**Comment by malt0se** [comment]
@chengmiaook 

Nevermind, it works ok for me. Starts syncing instantly

**Comment by malt0se** [comment]
Do you have another tor process running on the same system?

If you have, please do:

service tor stop

It was the reason in my case

**Comment by malt0se** [comment]
Ok, now it is working regardless of the local tor service.

**Comment by chengmiaook** [comment]
my tor.log is this
Dec 24 23:14:48.000 [notice] new bridge descriptor 'cymrubridge35' (fresh): $8CF38F8AC7CA1ACF6051CACE5C84F3E5B3832CD1~cymrubridge35 at 38.229.33.135
Dec 24 23:14:48.000 [notice] new bridge descriptor 'hobbingwighted' (fresh): $54288F3E4311A75035F4F9A7FA4E4F71EA747400~hobbingwighted at 52.15.115.35
Dec 24 23:14:48.000 [notice] new bridge descriptor 'holinessesOscars' (fresh): $978EF73CE5EFB0820415DF4F58769C6681DC7C54~holinessesOscars at 52.14.181.66
Dec 24 23:49:02.000 [warn] Proxy Client: unable to connect to 51.255.44.9:9443 ("general SOCKS server failure")
Dec 25 01:31:08.000 [warn] Proxy Client: unable to connect to 192.36.31.71:33930 ("general SOCKS server failure")
Dec 25 02:14:38.000 [notice] Heartbeat: Tor's uptime is 11:59 hours, with 21 circuits open. I've sent 5.84 MB and received 16.01 MB.
Dec 25 02:14:38.000 [notice] Average packaged cell fullness: 60.213%. TLS write overhead: 4%
Dec 25 02:14:46.000 [notice] new bridge descriptor 'Unnamed' (fresh): $F9460ED82B584D74A4A14886D5AF30C3FD9CFC69~Unnamed at 89.36.217.205
Dec 25 02:14:48.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 02:14:50.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 02:14:50.000 [notice] new bridge descriptor 'Unnamed' (fresh): $818AAAC5F85DE83BF63779E578CA32E5AEC2115E~Unnamed at 174.128.247.178
Dec 25 02:14:50.000 [notice] new bridge descriptor 'cymrubridge35' (fresh): $8CF38F8AC7CA1ACF6051CACE5C84F3E5B3832CD1~cymrubridge35 at 38.229.33.135
Dec 25 02:14:50.000 [notice] new bridge descriptor 'hobbingwighted' (fresh): $54288F3E4311A75035F4F9A7FA4E4F71EA747400~hobbingwighted at 52.15.115.35
Dec 25 02:14:50.000 [notice] new bridge descriptor 'holinessesOscars' (fresh): $978EF73CE5EFB0820415DF4F58769C6681DC7C54~holinessesOscars at 52.14.181.66
Dec 25 04:36:05.000 [warn] Proxy Client: unable to connect to 192.99.246.158:443 ("general SOCKS server failure")
Dec 25 04:36:06.000 [warn] Proxy Client: unable to connect to 192.99.246.158:443 ("general SOCKS server failure")
Dec 25 05:14:47.000 [notice] new bridge descriptor 'Unnamed' (fresh): $F9460ED82B584D74A4A14886D5AF30C3FD9CFC69~Unnamed at 89.36.217.205
Dec 25 05:14:50.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 05:14:52.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 05:14:52.000 [notice] new bridge descriptor 'Unnamed' (fresh): $818AAAC5F85DE83BF63779E578CA32E5AEC2115E~Unnamed at 174.128.247.178
Dec 25 05:14:52.000 [notice] new bridge descriptor 'cymrubridge35' (fresh): $8CF38F8AC7CA1ACF6051CACE5C84F3E5B3832CD1~cymrubridge35 at 38.229.33.135
Dec 25 05:14:52.000 [notice] new bridge descriptor 'holinessesOscars' (fresh): $978EF73CE5EFB0820415DF4F58769C6681DC7C54~holinessesOscars at 52.14.181.66
Dec 25 05:14:52.000 [notice] new bridge descriptor 'hobbingwighted' (fresh): $54288F3E4311A75035F4F9A7FA4E4F71EA747400~hobbingwighted at 52.15.115.35
Dec 25 06:40:57.000 [warn] Proxy Client: unable to connect to 80.44.48.88:62011 ("general SOCKS server failure")
Dec 25 08:06:33.000 [warn] Proxy Client: unable to connect to 192.36.31.71:33930 ("general SOCKS server failure")
Dec 25 08:14:38.000 [notice] Heartbeat: Tor's uptime is 17:59 hours, with 29 circuits open. I've sent 8.41 MB and received 19.79 MB.
Dec 25 08:14:38.000 [notice] Average packaged cell fullness: 56.182%. TLS write overhead: 4%
Dec 25 08:14:48.000 [notice] new bridge descriptor 'Unnamed' (fresh): $F9460ED82B584D74A4A14886D5AF30C3FD9CFC69~Unnamed at 89.36.217.205
Dec 25 08:14:52.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 08:14:54.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 08:14:54.000 [notice] new bridge descriptor 'Unnamed' (fresh): $818AAAC5F85DE83BF63779E578CA32E5AEC2115E~Unnamed at 174.128.247.178
Dec 25 08:14:54.000 [notice] new bridge descriptor 'cymrubridge35' (fresh): $8CF38F8AC7CA1ACF6051CACE5C84F3E5B3832CD1~cymrubridge35 at 38.229.33.135
Dec 25 08:14:54.000 [notice] new bridge descriptor 'hobbingwighted' (fresh): $54288F3E4311A75035F4F9A7FA4E4F71EA747400~hobbingwighted at 52.15.115.35
Dec 25 08:14:54.000 [notice] new bridge descriptor 'holinessesOscars' (fresh): $978EF73CE5EFB0820415DF4F58769C6681DC7C54~holinessesOscars at 52.14.181.66
@malt0se

**Comment by chengmiaook** [comment]
my tor.log is this @malt0se
Dec 24 23:14:48.000 [notice] new bridge descriptor 'cymrubridge35' (fresh): $8CF38F8AC7CA1ACF6051CACE5C84F3E5B3832CD1~cymrubridge35 at 38.229.33.135
Dec 24 23:14:48.000 [notice] new bridge descriptor 'hobbingwighted' (fresh): $54288F3E4311A75035F4F9A7FA4E4F71EA747400~hobbingwighted at 52.15.115.35
Dec 24 23:14:48.000 [notice] new bridge descriptor 'holinessesOscars' (fresh): $978EF73CE5EFB0820415DF4F58769C6681DC7C54~holinessesOscars at 52.14.181.66
Dec 24 23:49:02.000 [warn] Proxy Client: unable to connect to 51.255.44.9:9443 ("general SOCKS server failure")
Dec 25 01:31:08.000 [warn] Proxy Client: unable to connect to 192.36.31.71:33930 ("general SOCKS server failure")
Dec 25 02:14:38.000 [notice] Heartbeat: Tor's uptime is 11:59 hours, with 21 circuits open. I've sent 5.84 MB and received 16.01 MB.
Dec 25 02:14:38.000 [notice] Average packaged cell fullness: 60.213%. TLS write overhead: 4%
Dec 25 02:14:46.000 [notice] new bridge descriptor 'Unnamed' (fresh): $F9460ED82B584D74A4A14886D5AF30C3FD9CFC69~Unnamed at 89.36.217.205
Dec 25 02:14:48.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 02:14:50.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 02:14:50.000 [notice] new bridge descriptor 'Unnamed' (fresh): $818AAAC5F85DE83BF63779E578CA32E5AEC2115E~Unnamed at 174.128.247.178
Dec 25 02:14:50.000 [notice] new bridge descriptor 'cymrubridge35' (fresh): $8CF38F8AC7CA1ACF6051CACE5C84F3E5B3832CD1~cymrubridge35 at 38.229.33.135
Dec 25 02:14:50.000 [notice] new bridge descriptor 'hobbingwighted' (fresh): $54288F3E4311A75035F4F9A7FA4E4F71EA747400~hobbingwighted at 52.15.115.35
Dec 25 02:14:50.000 [notice] new bridge descriptor 'holinessesOscars' (fresh): $978EF73CE5EFB0820415DF4F58769C6681DC7C54~holinessesOscars at 52.14.181.66
Dec 25 04:36:05.000 [warn] Proxy Client: unable to connect to 192.99.246.158:443 ("general SOCKS server failure")
Dec 25 04:36:06.000 [warn] Proxy Client: unable to connect to 192.99.246.158:443 ("general SOCKS server failure")
Dec 25 05:14:47.000 [notice] new bridge descriptor 'Unnamed' (fresh): $F9460ED82B584D74A4A14886D5AF30C3FD9CFC69~Unnamed at 89.36.217.205
Dec 25 05:14:50.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 05:14:52.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 05:14:52.000 [notice] new bridge descriptor 'Unnamed' (fresh): $818AAAC5F85DE83BF63779E578CA32E5AEC2115E~Unnamed at 174.128.247.178
Dec 25 05:14:52.000 [notice] new bridge descriptor 'cymrubridge35' (fresh): $8CF38F8AC7CA1ACF6051CACE5C84F3E5B3832CD1~cymrubridge35 at 38.229.33.135
Dec 25 05:14:52.000 [notice] new bridge descriptor 'holinessesOscars' (fresh): $978EF73CE5EFB0820415DF4F58769C6681DC7C54~holinessesOscars at 52.14.181.66
Dec 25 05:14:52.000 [notice] new bridge descriptor 'hobbingwighted' (fresh): $54288F3E4311A75035F4F9A7FA4E4F71EA747400~hobbingwighted at 52.15.115.35
Dec 25 06:40:57.000 [warn] Proxy Client: unable to connect to 80.44.48.88:62011 ("general SOCKS server failure")
Dec 25 08:06:33.000 [warn] Proxy Client: unable to connect to 192.36.31.71:33930 ("general SOCKS server failure")
Dec 25 08:14:38.000 [notice] Heartbeat: Tor's uptime is 17:59 hours, with 29 circuits open. I've sent 8.41 MB and received 19.79 MB.
Dec 25 08:14:38.000 [notice] Average packaged cell fullness: 56.182%. TLS write overhead: 4%
Dec 25 08:14:48.000 [notice] new bridge descriptor 'Unnamed' (fresh): $F9460ED82B584D74A4A14886D5AF30C3FD9CFC69~Unnamed at 89.36.217.205
Dec 25 08:14:52.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 08:14:54.000 [notice] Bridge 'Unnamed' has both an IPv4 and an IPv6 address.  Will prefer using its IPv4 address (174.128.247.178:443) based on the configured Bridge address.
Dec 25 08:14:54.000 [notice] new bridge descriptor 'Unnamed' (fresh): $818AAAC5F85DE83BF63779E578CA32E5AEC2115E~Unnamed at 174.128.247.178
Dec 25 08:14:54.000 [notice] new bridge descriptor 'cymrubridge35' (fresh): $8CF38F8AC7CA1ACF6051CACE5C84F3E5B3832CD1~cymrubridge35 at 38.229.33.135
Dec 25 08:14:54.000 [notice] new bridge descriptor 'hobbingwighted' (fresh): $54288F3E4311A75035F4F9A7FA4E4F71EA747400~hobbingwighted at 52.15.115.35
Dec 25 08:14:54.000 [notice] new bridge descriptor 'holinessesOscars' (fresh): $978EF73CE5EFB0820415DF4F58769C6681DC7C54~holinessesOscars at 52.14.181.66

**Comment by malt0se** [comment]
@chengmiaook why do you think would i ask you specifically about "Bootstrapped" lines?

**Comment by malt0se** [comment]
Ok,

You are saying that you have zero connections and have a problem with sync.

So, to deduce if you are connected to the tor network, it would be great to know if you have 

Dec 00 00:00:39.000 [notice] Bootstrapped 0%: Starting
Dec 00 00:00:40.000 [notice] Bootstrapped 5%: Connecting to directory server
Dec 00 00:00:40.000 [notice] Bootstrapped 10%: Finishing handshake with directory server
Dec 00 00:00:40.000 [notice] Bootstrapped 15%: Establishing an encrypted directory connection
Dec 00 00:00:40.000 [notice] Bootstrapped 20%: Asking for networkstatus consensus
Dec 00 00:00:41.000 [notice] Bootstrapped 50%: Loading relay descriptors
Dec 00 00:00:41.000 [notice] Bootstrapped 80%: Connecting to the Tor network
Dec 00 00:00:41.000 [notice] Bootstrapped 85%: Finishing handshake with first hop
Dec 00 00:00:42.000 [notice] Bootstrapped 90%: Establishing a Tor circuit
Dec 00 00:00:44.000 [notice] Bootstrapped 100%: Done

lines in your /path/to/.VERGE/tor/tor.log

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
