### ISSUE TITLE
How to set up the VERGE private network?

### ISSUE THREAD

**Issue by viettienbk** [vergecurrency/VERGE#826]
# Issue Template

## Context

I want to set up the VERGE private network.

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [x] support request 
  - [ ] translation request 

## Current Behavior
I started a VERGE node on ubuntu machine to set up the VERGE private network,  but no blocks were created.
My VERGE.conf:
> server=1
> rpcuser=user
> rpcpassword=pass
> rpcallowip=0.0.0.0
> rpcport=20102
> port=21102
> gen=1
> onionseed=0
> printtoconsole=1

My command: `VERGEd -conf=<path_to_config_file>`

## Screenshots
![verge](https://user-images.githubusercontent.com/13216663/50206495-2c08c880-039e-11e9-827a-b21070cc8c6a.png)

## Your Environment

* Verge Release: 4.0.2a
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [x] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
that debug log looks fine. what is the problem?

**Comment by marpme** [comment]
Can you please define what you are trying to archive or what you mean by having a „private network“. Just want to make sure we aren’t talking about different things here.

**Comment by viettienbk** [comment]
I want to test functions of VERGE, include: create new address, transfer coin, get blockchain infor... So, I created a "private network" with 1 node to test. But when the node runs, it cannot create new block, I dont have  XVG coins to test "transfer" function.

**Comment by viettienbk** [comment]
> that debug log looks fine. what is the problem?
It cannot create new block and no new coin created.

**Comment by justinvforvendetta** [comment]
you are going to need to mine one of the 5 algorithms. your cpu is not going to be enough to earn you coins. you will need a gpu, and should join a mining pool.

**Comment by viettienbk** [comment]
> you are going to need to mine one of the 5 algorithms. your cpu is not going to be enough to earn you coins. you will need a gpu, and should join a mining pool.

I dont run mainnet node. I want to create my own Blockchain based on Verge.

**Comment by justinvforvendetta** [comment]
haha, unfortunately we are not here to help you do that

**Comment by viettienbk** [comment]
@justinvforvendetta: It is similar to regtest mode on bitcoin, or own blockchain on Komodo (https://github.com/KomodoPlatform/komodo#create-your-own-blockchain-based-on-komodo). I need VXG to test the functions.

**Comment by marpme** [comment]
There's no such functionality on this certain codebase to create a reg-test blockchain, which you can use to bother with it.

**Comment by viettienbk** [comment]
@marpme @justinvforvendetta: thanks for supporting me.

**Comment by marpme** [comment]
You are welcome, nevertheless it will be included in the new codebase. So if it's possible you can wait for it to be published :)
