### ISSUE TITLE
can't connect testnet

### ISSUE THREAD

**Issue by zychappy** [vergecurrency/VERGE#827]
can't connect testnet http://ddvnucmtvyiemiuk.onion/
is there another one ?
or could anybody tell me how to set up a private net please?
what I want is to do some tests smoothly with VERGE

**Comment by marpme** [comment]
Currently not possible. See:

https://github.com/vergecurrency/VERGE/issues/826#issuecomment-448668412

**Comment by zychappy** [comment]
![image](https://user-images.githubusercontent.com/9582529/50396056-5265a400-07a2-11e9-9c46-07cd1c2bcc16.png)
so it is not work?

**Comment by marpme** [comment]
you can do it, but there are no nodes which are syncing you on the testnet, neither are there any faucets who can supply you with some fake XVG's

**Comment by viettienbk** [comment]
You can run 2 nodes on 2 machines:
Node 1: VERGEd -rpcuser=user -rpcpassword=pass -gen -server -testnet -printtoconsole
Node2: VERGEd -rpcuser=user -rpcpassword=pass -gen -server -testnet -printtoconsole -connect=Node1_AddLocal
