### ISSUE TITLE
Is it possible to move the default directory of Verge blockchain files in C:Drive to another disk???

### ISSUE THREAD

**Issue by Jupiterss** [vergecurrency/VERGE#832]
It's getting tighter and tighter on my local C drive space every time I keep the verge blockchain files up to date.

**Comment by justinvforvendetta** [comment]
yep! move everything to a new folder, and when you start it up, use --datadir=X:\this\new\folder

**Comment by Jupiterss** [comment]
> 
> 
> yep! move everything to a new folder, and when you start it up, use --datadir=X:\this\new\folder

Thank you for the reply,Sir! I'll try it out right now. I hope it would work out like a charm^^.

**Comment by Jupiterss** [comment]
> 
> 
> yep! move everything to a new folder, and when you start it up, use --datadir=X:\this\new\folder

Well....How do i do with this "--datadir=xx" before opening it up? I'm a newbie to this ,sorry...

**Comment by marpme** [comment]
Like so:
![image](https://user-images.githubusercontent.com/7430964/50785598-7c928800-12b1-11e9-9e31-59ba5c029531.png)
