### ISSUE TITLE
1 local server to mine different algo in the same time ...

### ISSUE THREAD

**Issue by sktechnology** [vergecurrency/VERGE#833]
# Issue Template

## Context

Dedicated linux server with ubuntu 

2 kind of miner ...
scripts and lyra2rev2

mining the 2 algo in the same time with 2 kind of asic

## Prerequisites

* [ ] Are you running the latest version?
yes
## User Story:

* "I'm submitting a ... "
  - [X] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

<
## Possible Solution
if is not possible ... It possible to start 2 node on the same server different port ?

**Comment by justinvforvendetta** [comment]
it is not possible to mine on 2 algorithms using one instance of verge, however you can run 2 nodes on the same machine. the second one, you will want to compile in a different name directory, and then use the --datadir= flag, for instance:

node 1 is in ~/verge, and you start it with ./verged -daemon

node 2 is in ~/verge2, and you start it with ./verged -daemon -datadir=~/.VERGE2

**Comment by sktechnology** [comment]
thx justinvforvendetta, just for be sure, at this developpement time, is not possible to connect directely to the node with the stratum protocol, we need to use third party software to convert rpc to stratum protocol, witch one you have tested and worked well with the verge node ?

**Comment by justinvforvendetta** [comment]
I have set up verge on unomp, mpos, but obviously other pools that run yiimp and others all work as well, as you can see on the website.

**Comment by sktechnology** [comment]
Fast reply, good answer, great + value for cryptocurrency. thank you for your answer.

**Comment by Positivism** [comment]
While you can rum multiple daemon instances simultaneously as Justin pointed out, my personal suggestion is to run multiple smaller servers each with their own protocol.

**Comment by sktechnology** [comment]
I have try to setup 2 instance in the same time with 2 datadir ... 

the problem is the tor socket port is allready used so we try to start the second instance with

./VERGEd -datadir=/root/.VERGE2/ -tor=127.0.0.1:9051 -port=9999 -rpcport=8888  a different tor port ... we sync working and after 100% 

all connexion is refused for the second instance the first 1 is ok

connect() failed after select(): Connection refused
trying connection 5onui2lfl3iwdhrf.onion:21102 lastseen=141.7hrs
connect() failed after select(): Connection refused
trying connection plxs66tqlzbnh3ua.onion:21102 lastseen=107.6hrs
connect() failed after select(): Connection refused
trying connection plxs66tqlzbnh3ua.onion:21102 lastseen=107.6hrs
connect() failed after select(): Connection refused
trying connection n5ln6ke2vc47glpl.onion:21102 lastseen=152.9hrs
connect() failed after select(): Connection refused
trying connection kw5bdikypbbxaf2g.onion:21102 lastseen=78.7hrs
connect() failed after select(): Connection refused
trying connection 7sfrhwc6l4oohb5h.onion:21102 lastseen=96.1hrs
connect() failed after select(): Connection refused
trying connection ie4vffvggaz6xhbj.onion:21102 lastseen=84.3hrs
connect() failed after select(): Connection refused
trying connection n5ln6ke2vc47glpl.onion:21102 lastseen=152.9hrs
connect() failed after select(): Connection refused
trying connection kw5bdikypbbxaf2g.onion:21102 lastseen=78.7hrs
connect() failed after select(): Connection refused
trying connection kw5bdikypbbxaf2g.onion:21102 lastseen=78.7hrs
connect() failed after select(): Connection refused
trying connection 5onui2lfl3iwdhrf.onion:21102 lastseen=141.7hrs
connect() failed after select(): Connection refused
trying connection plxs66tqlzbnh3ua.onion:21102 lastseen=107.6hrs
connect() failed after select(): Connection refused
trying connection qjncc5qvylqxqimt.onion:21102 lastseen=120.6hrs
connect() failed after select(): Connection refused
trying connection 5n4gl3kvntyanp63.onion:21102 lastseen=72.8hrs
connect() failed after select(): Connection refused

**Comment by jrsikors** [comment]
We have released a completely new  codebase since you last posted 12 days ago... so I have to ask:

Have you tried on new codebase?

**Comment by jrsikors** [comment]
also, not suggesting this as a fix, but as a workaround if you just want to be done with it, as of new codebase you can run verged with `-without-tor` argument.  So you could do 1 or both -without-tor to avoid tor conflicts?

**Comment by sktechnology** [comment]
nop ... what is the easyway to upgrade node 

VVraith:4.0.2 to 5. ..

**Comment by sktechnology** [comment]
-without-tor i going to try now thx you

**Comment by jrsikors** [comment]
you have to be on 5 for -without-tor  ... but 5 is in **alpha** right now -- so i don't want you to mess up anything if you are running a production mining pool

**Comment by sktechnology** [comment]
jrsikors in 24 hours yesterday we find 24 block ... this morning 5 block in 12 hours it just luck or the update is possible issue for old pool core version ?

**Comment by sktechnology** [comment]
we going to make 12 hours more with the version 4.0.2 and we reopen the ticket if look like issue ! 

do you know if the version 5 is working with mpos + stratum for scrypt ?  and do you have a stratum-mining file for myriam-groestl or we just need to use zone117x/node-stratum-pool thx again

**Comment by marpme** [comment]
You can try to mine via the new codebase, but I guess it's very unstable as we haven't tested it, yet.

**Comment by sktechnology** [comment]
error submit block with core

error: [rpc error with daemon instance 0 when submitting block with submitblock {"code":-22,"message":"Block decode failed"}] undefined

any idea ? algo scrypt ?

**Comment by justinvforvendetta** [comment]
you have your daemon set to scrypt and found a scrypt block while mining, and submitted it, and received this error?

**Comment by sktechnology** [comment]
yes

**Comment by sktechnology** [comment]
pool software "echo this error"  but no credit on my wallet ... it look like the block submitted is not "accept" by the node deamon core 5.0"

**Comment by sktechnology** [comment]
The pool software with the node version  4.2 work fine but i have 50% orphan block, so I try to upgrade to 5.0 to have more non orphan block and i have this return error ... so at this moment i have no choice to mine another cryptocurrency for have better day to day generate but we convert to verge after. if you have any kind of idea to stop orphan block, i am ready to mine again verge. You have a very great unique tor product...

**Comment by sktechnology** [comment]
I already told you, that mining is kinda unstable/incompatible.  ...

bro no streesss about this .... I allready know this is not workng at this moment, we have a research team and we are allready waring about the non working beta version. it ok for me.. no more issue going to be opening ... I going to integrtating 5.0. if you need hardcore free php corder i am here thx for your comment and this issue is close for me right dont stop your good job. thx bro

**Comment by marpme** [comment]
@sktechnology do you have a share/block in a hex-decimal format, that got rejected by the network for us to test with?
