### ISSUE TITLE
LOST COINS

### ISSUE THREAD

**Issue by Cryptoveil** [vergecurrency/VERGE#834]
I misplaced my seed recovery phrases thought they were lost so I created a new wallet and new seed phase. Now the coins I bought are not showing up. I recently found my orginal seed phrase to my old wallet . The question is how do I get back my coins from the blockchain?

**Comment by marpme** [comment]
I'm not quite sure what kind of wallet you were using but there's definitely a way to import your found wallet seed. Just make sure to have a deeper look, if you can't find it please tell us what wallet your were/are using.

**Comment by Cryptoveil** [comment]
It is not accepting my old seed only new. My desktop verge icon says
Electrum so I assume that what it is as oppose to QT.Please advise.

**Comment by jrsikors** [comment]
https://verge.zendesk.com/hc/en-us/articles/360016162451--TOR-Seed-restore-not-working

**Comment by justinvforvendetta** [comment]
are you sure it's not a seedphrase from an android wallet?

**Comment by Cryptoveil** [comment]
100 percent sure. Wallet is on my Desktop.

**Comment by Cryptoveil** [comment]
I am drilling deeper here because I have two versions of the Verge Wallet:
Electrum and Qt. I am trying to sync Qt right now. Its is a long haul stuck
on 90 percent for hours, but patience is virtue.. I will try again tomorrow
morning if there is no sync by tommorrow early AM. I am optimistic this
will be a happy ending.  Thank you all for your feedback!

**Comment by justinvforvendetta** [comment]
@Cryptoveil how about just downloading the chain from verge-blockchain.com

**Comment by jrsikors** [comment]
We are closing ALL issues to get a clean slate after the major codebase update.  Please re-submit issue with details if this is still an issue moving forward.
