### ISSUE TITLE
Maximum supply 

### ISSUE THREAD

**Issue by sktechnology** [vergecurrency/VERGE#835]
Hi,

today the current supply from the verge blockchain is 15,172,086,051 XVG

it possible to know when the maximum supply going to be reach (average date) ? 16,555,000,000 **XVG**

thank you.

**Comment by justinvforvendetta** [comment]
yes it's possible. use 30 second block times and the reward table to calculate it :)

**Comment by justinvforvendetta** [comment]
a block every 30 seconds (Averaged) 

2880 blocks per day.
