### ISSUE TITLE
getrawtransaction() slow response if txid is invalid

### ISSUE THREAD

**Issue by JayMaree** [vergecurrency/verge#837]
https://github.com/vergecurrency/VERGE/blob/9d0cd61f8d2a45a90cba5a2ad4d0167f4b85d240/src/rpcrawtransaction.cpp#L122

The getrawtransaction method has two different responses:
- it returns a message if the txid is valid
- it returns a message if the txid is invalid

The response time against a **valid** txid is very fast, as it should be. But when I request the same method against a **invalid** txid (I use this method to verify the txid) it takes a very long time to return the response.

The method
```
if (!GetTransaction(hash, tx, hashBlock))
        throw JSONRPCError(RPC_INVALID_ADDRESS_OR_KEY, "No information available about transaction");
```
produces the delay somehow. I can't figure out which method/class delays the response because I haven't checked the code completely.

A screenshot of the response delays:
![image](https://user-images.githubusercontent.com/4375944/51312307-412f5080-1a4b-11e9-8b1e-15d8ddb49a4e.png)
The high peaks are the delays in responses of invalid txid's

Is it a known issue? Thanks in advance.

**Comment by marpme** [comment]
Thank you for reporting this issue, I will have a look into that.

Gotta build the txindex on the new core and check if the error is happening there too. If it does, then we are definitely fixing it on the new codebase.

**Comment by marpme** [comment]
Just a recommendation for the meantime, until the new core is finally released: 

I highly recommend you to proxy-cache requests like that, as they may ask very often for the same resource over and over again. The codebase does a lot of security checks before actually sending the tx, you actually don't want to bother him every single time someone asks for a resource of that kind. 

Hence just add a caching layer in between with a 60 min validation time and you should at least get rid of such **very high** delays.

**Comment by marpme** [comment]
From what I can tell now: This issue doesn't exist on the new core.

**Comment by JayMaree** [comment]
> From what I can tell now: This issue doesn't exist on the new core.

Because it is fixed?

**Comment by marpme** [comment]
I don't experience any performance issues when either submitting valid or invalid txid's. 
I will try to build a more in-depth test, but yeah it seems to be fixed.

**Comment by justinvforvendetta** [comment]
@jaymaree ery soon, and thanks for your detailed report!

**Comment by JayMaree** [comment]
@justinvforvendetta np. Thanks for the comment.
