### ISSUE TITLE
Compilation failes due to undefined code

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#838]
trying to make on ubuntu 18

```
CXXLD    bench/bench_verge
libverge_server.a(libverge_server_a-init.o): In function SetupServerArgs()&apos;:
/home/verge/VERGE/src/init.cpp:446: undefined reference tog_wallet_init_interface&apos;
libverge_server.a(libverge_server_a-init.o): In function AppInitParameterInteraction()&apos;:
/home/verge/VERGE/src/init.cpp:1120: undefined reference tog_wallet_init_interface&apos;
libverge_server.a(libverge_server_a-init.o): In function Shutdown()&apos;:
/home/verge/VERGE/src/init.cpp:211: undefined reference tog_wallet_init_interface&apos;
libverge_server.a(libverge_server_a-init.o): In function AppInitMain()&apos;:
/home/verge/VERGE/src/init.cpp:1288: undefined reference tog_wallet_init_interface&apos;
/home/verge/VERGE/src/init.cpp:1288: undefined reference to g_wallet_init_interface&apos;
libverge_server.a(libverge_server_a-init.o):/home/verge/VERGE/src/init.cpp:1305: more undefined references tog_wallet_init_interface&apos; follow
libverge_server.a(libverge_server_a-misc.o): In function `getinfo(JSONRPCRequest const&amp;)&apos;:
</pre>
/home/verge/VERGE/src/rpc/misc.cpp:551: undefined reference to GetWalletForJSONRPCRequest(JSONRPCRequest const&amp;)&apos;
libverge_server.a(libverge_server_a-misc.o): In functionvalidateaddress(JSONRPCRequest const&amp;)&apos;:
/home/verge/VERGE/src/rpc/misc.cpp:66: undefined reference to GetWalletForJSONRPCRequest(JSONRPCRequest const&amp;)&apos;
libverge_server.a(libverge_server_a-rawtransaction.o): In functionsignrawtransaction(JSONRPCRequest const&amp;)&apos;:
/home/verge/VERGE/src/rpc/rawtransaction.cpp:992: undefined reference to GetWalletForJSONRPCRequest(JSONRPCRequest const&amp;)&apos;
/home/verge/VERGE/src/rpc/rawtransaction.cpp:1005: undefined reference toHelpRequiringPassphrase[abi:cxx11](CWallet)&apos;
/home/verge/VERGE/src/rpc/rawtransaction.cpp:1081: undefined reference to `signrawtransactionwithwallet(JSONRPCRequest const&amp;)

collect2: error: ld returned 1 exit status

Makefile:4106: recipe for target &apos;bench/bench_verge failed
make[2]: ** [bench/bench_verge] Error 1
make[2]: Leaving directory &apos;/home/verge/VERGE/src
Makefile:10837: recipe for target &apos;all-recursive; failed
make[1]:  [all-recursive] Error 1
make[1]: Leaving directory &apos;/home/verge/VERGE/src
Makefile:768: recipe for target all-recursive failed
make:  [all-recursive] Error 1
```

**Temporary Solution:**

`./configure --disable-bench && make`

**Comment by alexiv732** [comment]
Hello! What version of the wallet is installed on ubuntu-16.04.5-server-amd64? Without TOR and GUI.

**Comment by justinvforvendetta** [comment]
a daemon running 5.0 alpha

**Comment by alexiv732** [comment]
In tags only 4.0.3b and current version 5.0beta. 
Where is the version 5.0 alpha?

**Comment by justinvforvendetta** [comment]
current is actually alpha.

**Comment by alexiv732** [comment]
Thank you very much! Setup continues ....

**Comment by alexiv732** [comment]
Sorry again. What option to disable internal mining? For example, other wallets option gen = 0 ...

**Comment by marpme** [comment]
Mining is no longer part of the core. So you don't have to disable mining anymore.
Besides that you can disable tor, when start a node by passing it `-without-tor`

**Comment by alexiv732** [comment]
Thanks I got it.

**Comment by paradoxicalNL** [comment]
I can confirm same for ubuntu 18.04.
Disabling bench as suggested and going to retry!

**Comment by BlueManRising** [comment]
confirmed for 16.04, Same issue.

**Comment by JasonGaoG** [comment]
confirmed for 16.04, Same issue.

**Comment by JasonGaoG** [comment]
just want to know， is there any update? thanks a lot

**Comment by marpme** [comment]
Run this as a current workaround: `./configure --disable-bench && make -j4`

**Comment by marpme** [comment]
@justinvforvendetta any update on this compiling issue? 🥺

**Comment by justinvforvendetta** [comment]
im working on this atm, in the bench_tests branch.

**Comment by karanpatel863** [comment]
Has this issue been resolved?

**Comment by marpme** [comment]
@karanpatel863 nope and I will stay like that until it's closed :P

**Comment by karanpatel863** [comment]
https://www.google.com/amp/s/latedev.wordpress.com/2014/04/22/common-c-error-messages-2-unresolved-reference/amp/

This will help you for sure

**Comment by marpme** [comment]
@karanpatel863 I respect your good intentions here and we already figured out the problem here already, but it's nothing which is fixable with 1-2 lines of code. It needs some more rebasing of the codebase. 

We'll definitely look into it, but it's also not a showstopper for us : )

**Comment by karanpatel863** [comment]
Np 👍. Felt to share as i was reading about few other errors and found this
article, then i suddenly remembered that "undefined reference" issue was
open

**Comment by justinvforvendetta** [comment]
iiim still working on it. its a big change ;]

**Comment by marpme** [comment]
I would support the idea of closing down this by removing the compilation of bench by default.

**Comment by justinvforvendetta** [comment]
you know I wont argue that lol
