### ISSUE TITLE
p2p value?

### ISSUE THREAD

**Issue by jaredthesovereign** [vergecurrency/VERGE#84]
Is there a specific p2p port to use and peermagic value for the conf file?  using uNOMP.

**Comment by justinvforvendetta** [comment]
the p2p port can be defined in the .conf, but by default its 21102

**Comment by jaredthesovereign** [comment]
I do use 21102 but uNOMP still throws:

Pool verge Thread # p2p connection failed - likely incorrect host or port

My pool configuration is:

"p2p": {
        "enabled": true,
        "host": "127.0.0.1",
        "port": 21102,
        "disableTransactions": false
    },


Thoughts?

**Comment by justinvforvendetta** [comment]
have you tried getting rpc calls back from the daemon?

**Comment by justinvforvendetta** [comment]
ive definitely set up a unomp for verge before and didnt have an issue. daemon not connected is what id guess

**Comment by jaredthesovereign** [comment]
uNOMP shows rpc calls back from the daemon.  It is active and connected as I can mine on the pool.  It's just not connecting to the p2p. Weird.

Going to check to see if there are any firewall issues.

**Comment by justinvforvendetta** [comment]
are you using ipv4 or 6? how many peers is the daemon connected to?

**Comment by jaredthesovereign** [comment]
Currently re-downloading the blockchain in case there was some corruption somewhere.  It should take a while.  Will let you know.
IPv4

**Comment by justinvforvendetta** [comment]
well p2p is working or you wouldnt have connections or be able to sync, so im going to close this. issue must be unomp side.
