### ISSUE TITLE
Compile issue at libvergeconsensus_la-scrypt-sse2.lo

### ISSUE THREAD

**Issue by BlueManRising** [vergecurrency/VERGE#843]
# Issue Template

## Context

Compile issue on Ubuntu 16.04 32bit

## Prerequisites

* [ x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Current Behavior

CC       crypto/pow/libvergeconsensus_la-hamsi.lo
  CC       crypto/pow/libvergeconsensus_la-haval.lo
  CC       crypto/pow/libvergeconsensus_la-jh.lo
  CC       crypto/pow/libvergeconsensus_la-keccak.lo
  CC       crypto/pow/libvergeconsensus_la-luffa.lo
  CC       crypto/pow/libvergeconsensus_la-Lyra2.lo
  CC       crypto/pow/libvergeconsensus_la-Lyra2RE.lo
  CXX      crypto/pow/libvergeconsensus_la-scrypt.lo
  CXX      crypto/pow/libvergeconsensus_la-scrypt-sse2.lo
crypto/pow/scrypt-sse2.cpp: In function ‘void scrypt_1024_1_1_256_sp_sse2(const char*, char*, char*)’:
crypto/pow/scrypt-sse2.cpp:130:50: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
    X.i128[k] = _mm_xor_si128(X.i128[k], V[j + k]);
                                                  ^

## Steps to Reproduce (for bugs)

* Steps :
1. Ubuntu 16.04 32 bit
2 . Boost Version 1.58
3. ./configure
4. Error (as stated above)

## Your Environment

* Verge Release:
* CPU: Atom Processor
* GPU:
* RAM: 1gb
* OS:
    - [ ] I'm using Mac
    - [ X] I'm using Linux
    - [ ] I'm using Mac

**Comment by marpme** [comment]
This just shows a warning, could you please upload the full log as txt file, that would be really appreciated:

```
crypto/pow/scrypt-sse2.cpp: In function ‘void scrypt_1024_1_1_256_sp_sse2(const char*, char*, char*)’:
crypto/pow/scrypt-sse2.cpp:130:50: warning: SSE vector return without SSE enabled changes the ABI [-Wpsabi]
X.i128[k] = _mm_xor_si128(X.i128[k], V[j + k]);
```

**Comment by justinvforvendetta** [comment]
^
Makefile:9128: recipe for target 'crypto/pow/libvergeconsensus_la-scrypt-sse2.lo' failed
make[2]: *** [crypto/pow/libvergeconsensus_la-scrypt-sse2.lo] Error 1
make[2]: Leaving directory '/home/bluemanrising/VERGE/src'
Makefile:10837: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/bluemanrising/VERGE/src'
Makefile:768: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by justinvforvendetta** [comment]
were you trying to compile for windows or linux, or cross compile?

**Comment by jeepman4403** [comment]
windows

Sent from Mail for Windows 10

**Comment by marpme** [comment]
Seems to be related to this issue, probably a missing compiler flag @justinvforvendetta 

https://github.com/dropbox/lepton/issues/27#issuecomment-233190814

**Comment by BlueManRising** [comment]
Linux compiling

**Comment by justinvforvendetta** [comment]
that was the first issue I saw too. prob sse2

**Comment by BlueManRising** [comment]
@justinvforvendetta compile to Linux for the same machine, realized you guys were right sse2, though compatible with Atom Processors, they cannot handle building.  I rebuilt on my other Ubuntu 16.04 with a i7 and it is compiling  just fine.  So lesson learned, death to the old Atom Processor.
