### ISSUE TITLE
Cosmetic Issue QT 5.0

### ISSUE THREAD

**Issue by BlueManRising** [vergecurrency/VERGE#844]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [X] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior

Verge Drop down Menu to show same as 4.0 QT in Linux.  (see screen shot)

## Current Behavior

Currently Drop Down Menu is empty.

## Screenshots

![cosmetic issue](https://user-images.githubusercontent.com/34865074/51447319-d00dc880-1cea-11e9-8013-17b89ed37d9f.png)

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by justinvforvendetta** [comment]
menu is there
