### ISSUE TITLE
Access wallet in Shell through cli

### ISSUE THREAD

**Issue by roecks** [vergecurrency/VERGE#845]
All dependencies are running, codebase forked and cloned, verge-config file (RPC) is there. Installed the new Verge 5.0 alpha codebase on Mac (High Sierra 10.13.2) and am running **verged** in Terminal. Few warnings, nothing that worried me. Killer job!

Wallet creation with `verge-cli createwallet  "walletname"` works. Builds wallet in `Application Support/VERGE`. After rebooting **verged** in Terminal, I can also load wallets through `verge-cli loadwallet "walletname"`.

But, when running other commands such as `verge-cli getbalance "walletname"` or `verge-cli getwalletinfo "walletname"` it throws an error (can't find wallet/file). Asking me to include `-rpcwallet` argument. Even then it's not finding/recognizing the wallet.

As `loadwallet` works **and** the "walletname" is recognized when trying to create a wallet under the same name (throws error), I'd expect commands like `getbalance` and `getwalletinfo` (etc) would work similarly?

## Prerequisites

* [v] Are you running the latest version?

* "I'm submitting a ... "
  - [v ] bug report
  - [ ] feature request
  - [v ] support request 
  - [ ] translation request 

_One of the two. Either I hope you can help me out, or maybe we should fix the problem (if there is one)._

* Verge Release: 5.0 alpha
* CPU: 1.86
* RAM: 4Gb
* OS:
    - [v] I'm using Mac, High Sierra 10.13.2
    - [ ] I'm using Linux
    - [x] I'm using Mac

**Comment by justinvforvendetta** [comment]
did you try with single quotes like 'this' instead of "this"?

**Comment by roecks** [comment]
> did you try with single quotes like 'this' instead of "this"?

Yea. I did. Still error code -19.

**Comment by marpme** [comment]
In the client, you have the option to choose the wallet over there, but I will also check out how to get the same results in the cli/rpc calls. 

![image](https://user-images.githubusercontent.com/7430964/51488570-2e4bb180-1da6-11e9-8fb8-c75b1cf02470.png)

**Comment by marpme** [comment]
Works perfectly fine here:

➜  VERGE git:(bugfix-841-fix-tor-connection-issues) ./src/verge-cli -rpcuser=test -rpcpassword=test -rpcwallet=mywallet getwalletinfo
{
  "walletname": "mywallet",
  "walletversion": 169900,
  "balance": 0.000000,
  "unconfirmed_balance": 0.000000,
  "immature_balance": 0.000000,
  "txcount": 0,
  "keypoololdest": 1548089494,
  "keypoolsize": 1000,
  "keypoolsize_hd_internal": 1000,
  "paytxfee": 0.100000,
  "hdseedid": "3a73cec6d99c3ad8faa4b85cd35fe5a6a2d25082",
  "hdmasterkeyid": "3a73cec6d99c3ad8faa4b85cd35fe5a6a2d25082"
}

Can't confirm this as a bug

**Comment by justinvforvendetta** [comment]
@roecks we can definitely do that in the documentation

**Comment by marpme** [comment]
Documentation is still open afaik, @jrsikors would you like to take care of this?
