### ISSUE TITLE
Bitcore doesn't sync when v2.1 or lower peers are connected

### ISSUE THREAD

**Issue by SwenVanZanten** [vergecurrency/VERGE#854]
# Issue Template

## Context

Bitcore stops syncing blocks when a v2.1 or lower peer is connected.
When disconnecting these peers the syncing immediately proceeds.

Maybe build in an option to not connect to these nodes.

**Comment by justinvforvendetta** [comment]
somewhere in the middle of net_processing, under ~1643ish, we can just block that specific peer from connecting, problem solved. whatcha think @marpme 

```
if (!vRecv.empty())
{
vRecv >> pfrom->strSubVer;
printf("bad peer: peer's connecting subver is %s , which is too old!",pfrom->strSubVer.c_str());
std::size_t iFoundPosition = pfrom->strSubVer.find("VERGE2");
            if(iFoundPosition != std::string::npos)
            {
                printf("  -  disconnecting .....\n");
                pfrom->fDisconnect = true;
                return false;
            }
printf("\n");

}
```

**Comment by justinvforvendetta** [comment]
no, I dont think it looked like that back then.. ask swen for a paste of the subver he saw when he was connected

**Comment by marpme** [comment]
5dd14fe2e73425beff64c8c2cf69a98b1131e67e fixed this
