### ISSUE TITLE
autogen.sh

### ISSUE THREAD

**Issue by alexiv732** [vergecurrency/VERGE#856]
./autogen.sh
`Cloning into 'src/ext/rust'...
fatal: unable to access 'https://git.torproject.org/tor-rust-dependencies/': Failed to connect to git.torproject.org port 443: Connection timed out
fatal: clone of 'https://git.torproject.org/tor-rust-dependencies' into submodule path 'src/ext/rust' failed
Failed to recurse into submodule path 'src/tor'`

**Comment by justinvforvendetta** [comment]
I cant reproduce this.

**Comment by JasonGaoG** [comment]
got the same error . have you resoved it?

**Comment by justinvforvendetta** [comment]
can  you list the distro you are using, along with what version of autotools you have? and the version of git as well...

**Comment by justinvforvendetta** [comment]
we might be able to just remove rust, ill check. im pretty sure we used to do that.

**Comment by JasonGaoG** [comment]
@jrsikors  Hi， thank you， seems I could access the websites https://gitweb.torproject.org/ .without vpn. the site git.tor** was redirect to gitweb.tor**.

**Comment by JasonGaoG** [comment]
could I know where I can change the git.tor** to gitweb.tor**. seems gitweb is working for me .

**Comment by marpme** [comment]
Maybe a pure wipe of the repository + a fresh clone resolves the problem? 

Because we are using the GitHub clone of tor instead of “git.torpeoject.com”

**Comment by JasonGaoG** [comment]
resolved it via VPN.~

**Comment by marpme** [comment]
@alexiv732 does this also solve your problem ^

**Comment by marpme** [comment]
nope, we'll require at least the installation of tor. 
but the usage is up to you when you first compiled it and run it
you can add a parameter to disable tor within the runtime: `-without-tor`
