### ISSUE TITLE
Remove illegitimate copyright notices 

### ISSUE THREAD

**Issue by kewde** [vergecurrency/verge#857]
Hi,

There seems to be a lot of files that were copied from `particl-core` which were not modified by your team.
Please remove all copyright notices from files that did not receive a single change by Verge.

You are free to use our source code but that does not allow you to claim a copyright without a single change.

Thanks.

**Comment by kewde** [comment]
> we are free to have them in here as long as the original copyright is there.

You can not claim copyright to file which you've made no substantial change to.

> also files on particl that have only the bitcoin copyright and have been modified by particl without adding a copyright

That's the reverse scenario. We're not forced to add a copyright notice. When we do minor changes, we don't add them

**Comment by kewde** [comment]
@justinvforvendetta 

https://github.com/vergecurrency/VERGE/tree/master/src/smsg

Many files in there have +1 line which is only the added copyright notice.

**Comment by kewde** [comment]
https://github.com/vergecurrencya/VERGE/blob/master/src/smsg/crypter.cpp

What code are you claiming copyright to there?
I can't find it.

**Comment by justinvforvendetta** [comment]
dont worry, it will be modified. I'll go thru and remove them, and then add them again when needed if it makes you feel better. you do the same on the particl repo with bitcoin, thanks

**Comment by kewde** [comment]
Could you open the issue again until it is resolved?

**Comment by justinvforvendetta** [comment]
I'll just toss them back in tonight without the extra verge copyright
