### ISSUE TITLE
4.0clearnet

### ISSUE THREAD

**Issue by goodthebest** [vergecurrency/VERGE#859]
Hey Devs,
I'm trying to get Verge on a mining, pool, however clearnet version doesn't seem  to connect at all. Previously (few months ago) I could see 4.0clearnet when I run **getinfo** but with recent git clone it doesn't seem to get right. Here it is what I did

>git clone https://github.com/vergecurrency/VERGE.git
cd VERGE
git checkout 4.0clearnet
Branch 4.0clearnet set up to track remote branch 4.0clearnet from origin.
Switched to a new branch '4.0clearnet'
./autogen.sh
./configure 
make

running **getinfo** I get this output, apparently there isn't any **4.0clearnet** rather it's **beta**.  Could you please help me figure this out?
![image](https://user-images.githubusercontent.com/1715740/51867592-50749f00-2365-11e9-95e1-e58cf629cc98.png)

**Comment by justinvforvendetta** [comment]
that version just takes a long time to load. also you dont have the pool software already using port 21102 do you?

**Comment by jrsikors** [comment]
I wouldn't worry about the version.  You are on 4.0 clearnet.  You can see the **_29c7021_** in the version.. which is the last commit for 4.0 clearnet branch.

**Comment by justinvforvendetta** [comment]
he isnt getting connections though.

**Comment by goodthebest** [comment]
yes, I'm not getting any connections at all, port 21102 is already in use by VERGE. Are there any addnodes I can put in the .conf?

![image](https://user-images.githubusercontent.com/1715740/51957503-61a4d500-2465-11e9-87dd-74102398306e.png)

**Comment by goodthebest** [comment]
Thanks in advance, I'll wait here

**Comment by goodthebest** [comment]
@justinvforvendetta still waiting!!!

**Comment by marpme** [comment]
I think you already have some valid peers, but there are corrupted messages being send over the network:

```
******* exception encountered *******
ProcessMessages(block, 193 bytes) : Exception 'CDataStream::read() : end of data: unspecified iostream_category error' caught, normally caused by a message being shorter than its stated length
ProcessMessage(block, 193 bytes) FAILED
```

**Comment by goodthebest** [comment]
Where did you get this **exception encountered**? My log doesn't show anything like that at all? If you notice I do not have any connections at all.

**Comment by marpme** [comment]
Well I started one 5.0 node and one 4.0clearnet node and forced to connect to each other. 
And then I had a look into the 4.0clearnet node and that's where I found the error.

**Comment by goodthebest** [comment]
oh I see, how to get it fixed ?

**Comment by marpme** [comment]
Oh I thought you were on 5.0, there's nothing to be fixed on 4.0clearnet. It should just work fine. 
As I will fix a bug on the 5.0, I will compile some node addresses together

**Comment by goodthebest** [comment]
why I'm not getting any connections on **4.0clearnet.** ?

**Comment by marpme** [comment]
Because there are less peers these days, most of them moved to tor anyways. 
maybe those one going to help you, if not let me know: 

https://github.com/vergecurrency/VERGE/blob/master/doc/peers.txt

**Comment by goodthebest** [comment]
Can we mine on TOR, previously blocks were rejected on Tor based wallets ?

**Comment by marpme** [comment]
Well make sure to checkout 4.0.3b tag (9d0cd61f8d2a45a90cba5a2ad4d0167f4b85d240) instead of latest master as there's some alpha stuff in master
