### ISSUE TITLE
Cant compile Ubuntu 14.04...

### ISSUE THREAD

**Issue by Romeo01234** [vergecurrency/VERGE#864]
The LIBCAP-DEV is installed, but the error i receive is below:

...
checking for LIBEVENT... yes
checking for ZLIB... yes
checking for LIBSECCOMP... yes
checking for LIBCAP... no
configure: error: libcap not found
...

How do I rectify?

Thanks.

**Comment by marpme** [comment]
Ubuntu 14.04 is not longer supported from our side, please upgrade to either Ubuntu 16.04/18.04.

**Comment by marpme** [comment]
Ubuntu's release cycle: https://www.ubuntu.com/about/release-cycle
