### ISSUE TITLE
peers dont connect to new build.....

### ISSUE THREAD

**Issue by Romeo01234** [vergecurrency/VERGE#865]
Compiled on Ubuntu 16.04, ran verge-qt. GUI loads fine, peers do not connect and noticed database blockchain restarts at 4 years. 

Reran with TOR disabled but still unable to connect to peers.

How to fix issue?

**Comment by jrsikors** [comment]
you can run verge-qt or verged with **_-debug_**  flag

**Comment by justinvforvendetta** [comment]
please delete your peers.dat while the wallet is shut down.

**Comment by jrsikors** [comment]
also -- when you first open -- do you get ANY blocks and then it stops?  Or are you getting 0 blocks.

I came across a situation where I get 1 peer for about 30 seconds, get some blocks, then it disconnects.  I'm wondering if you are having same problem or if you are straight up 0 peers.

**Comment by Romeo01234** [comment]
> also -- when you first open -- do you get ANY blocks and then it stops? Or are you getting 0 blocks.
> 
> I came across a situation where I get 1 peer for about 30 seconds, get some blocks, then it disconnects. I'm wondering if you are having same problem or if you are straight up 0 peers.

Initially 0 blocks, I noticed the 1 peer then a permanent disconnect.
I will try justinvforvendetta above and see if that rectifies the problem. I also compiled without bench, since compilation stopped.

Thanks.

**Comment by Romeo01234** [comment]
> please delete your peers.dat while the wallet is shut down.

Justin, I will give it a try.

**Comment by justinvforvendetta** [comment]
@Romeo01234 did that work?

**Comment by Romeo01234** [comment]
> @Romeo01234 did that work?

I will try in an 1hr, but will let you know if problem is rectified or persists.

Thanks for responding.

**Comment by Romeo01234** [comment]
> @Romeo01234 did that work?

Just tried it, removing the peers.dat, peers.dat.1139, peers.dat.1c51, peers.dat.afb6. 

command issued.
./verge-qt --without-tor

peers connected got 1, syncing headers 0.2%. lost peer, and nothing else happens.

**Comment by Romeo01234** [comment]
is there a node list of peers to connect to?

**Comment by justinvforvendetta** [comment]
try waiting a few minutes with it open. also if you switch between tor and without tor, you need to delete the peers dat, because it will have tor peers in it still, and vice versa

**Comment by Romeo01234** [comment]
> try waiting a few minutes with it open. also if you switch between tor and without tor, you need to delete the peers dat, because it will have tor peers in it still, and vice versa

i did that again, deleted everything except wallet.dat.
I am at 0.4%, 0 peers.

I'll try with tor, then without. 

Ill see how it goes. Ill leave it on for a few hours, and let you know if the results are favorable or much of the same.

Does the compilation with bench removed effect proper functionality? 

Thanks.

**Comment by Romeo01234** [comment]
I noticed when trying to use TOR it states the following:
    TOR thread started.
    No OBFS4 found, not using it.

I guess this explains why I am unable to connect through TOR proxy.

I keep losing peers, sometime I get 3 peer connects. Headers Synced up to 42000 in 42min.

**Comment by marpme** [comment]
@Romeo01234 No that doesn't explain anything, can you please post your full debug log.

Additionally could you tell me what openssl version you are on?

**Comment by Romeo01234** [comment]
> @Romeo01234 No that doesn't explain anything, can you please post your full debug log.
> 
> Additionally could you tell me what openssl version you are on?

please provide me a full debug command line entry; i am not a programmer; I have left core wallet running overnight and didnt move from "124000"(syncing Headers).

I am running openssl 1.1.1a, zlib 1.2.8, libevent 2.0.21-stable.

Thanks.

**Comment by Romeo01234** [comment]
> `./verge-qt -without-tor -debug`
> 
> note that it should be -without-tor , 1 dash not 2.

File for download, end of debug dump.


[verge-debug[ubuntu_16.04].log](https://github.com/vergecurrency/VERGE/files/2824551/verge-debug.ubuntu_16.04.log)

**Comment by jrsikors** [comment]
and can you please give us a quick run-down of what happened this time.  Did you open it -- get 1 peer for a few minutes -- then disconnect to 0 peers and it stopped?

did you open it, get 0 peers for 5 minutes, etc.

**Comment by Romeo01234** [comment]
> and can you please give us a quick run-down of what happened this time. Did you open it -- get 1 peer for a few minutes -- then disconnect to 0 peers and it stopped?
> 
> did you open it, get 0 peers for 5 minutes, etc.

I open and close verge-qt, i see a connection to peers then the peers drop off. I keep doing that and eventually get some headers downloaded.

I deleted the debug.log and tried the same technique. on the 7th try I got some headers again.
Debug file below is much smaller, last entry should display headers downloaded.

[verge-debug[ubuntu_16.04].log](https://github.com/vergecurrency/VERGE/files/2824582/verge-debug.ubuntu_16.04.log)

Hope this helps you.

**Comment by Romeo01234** [comment]
> @Romeo01234 btw openssl has a incompatibility with tor, thus tor shutdown automagically because of a openssl bug :(

Ia there a work around or future fix?

**Comment by justinvforvendetta** [comment]
you can try downgrading to openssl 1.1.0g

**Comment by marpme** [comment]
Afaik 1.1.0g should be stable enough, but 1.1.1 isn’t. So you would have to manually downgrade OpenSSL for that repo

**Comment by swat69** [comment]
using Debian 9.6/OpenSSL 1.1.0j, this is the result after running 24h,
blocks/headers are increasing very slow:
  "version": 5000000,
  "protocolversion": 90007,
  "blocks": 23919,
  "headers": 1248000,
  "timeoffset": -511,
  "connections": 8,
  "proxy": "127.0.0.1:9089",

**Comment by justinvforvendetta** [comment]
that's a very high timeoffset

**Comment by Romeo01234** [comment]
> you can try downgrading to openssl 1.1.0g, which is the current version in ubuntu 18.04

Hey Justin, I wish my programming skills were better. I will compile with the older openssl series 1.1.0, but just so you know openssl 1.1.1 series is the new stable version. Openssl 1.1.0 series is only receiving security fix updates and support for that version will end "September 2019".

                                        https://www.openssl.org/source/

I encourage you and other developers to read the "Note:"
I am a huge supporter of your project, it would be more conducive if your source code has openssl security patches upgraded.

Thanks.

**Comment by marpme** [comment]
Well I also had a `-409` timeoffset, seems to be normal due to tor.

**Comment by Romeo01234** [comment]
> using Debian 9.6/OpenSSL 1.1.0j, this is the result after running 24h,
> blocks/headers are increasing very slow:
> "version": 5000000,
> "protocolversion": 90007,
> "blocks": 23919,
> "headers": 1248000,
> "timeoffset": -511,
> "connections": 8,
> "proxy": "127.0.0.1:9089",

check if you have ntp installed.
if you are using a linux variant, try:
sudo apt-get install ntp 

maybe this will help.

**Comment by Romeo01234** [comment]
> you can try downgrading to openssl 1.1.0g, which is the current version in ubuntu 18.04

Good news and strange behavior under Ubuntu 16.04.

Compiled with Openssl 1.1.0j, downloaded Blockchain Jan 24, 2019.

Ran ./verge-qt -without-tor, ran into same problem as previously indicated. 1 peer connects then disconnects.

Ran ./verge-qt, blockchains are downloading. looks good.

Still much work needs to get done, but looking good.

Congrates.

**Comment by Romeo01234** [comment]
> A few new blocks after a restart:
> [debug.log](https://github.com/vergecurrency/VERGE/files/2831306/debug.log)

swat69, to make things easier for yourself download the Codebase-5.0 blockchain use link below:
                       https://vergecurrency.com/developers/wallet-setup-instructions/
scroll up to where is says "Nightly snapshot".

I got to fully sync on Debian kernel-4.9.0-8-amd64 using openssl-1.1.0j.

applying "./verge-qt -without-tor" provides me the same peer connect issue as with Ubuntu 16.04 previously mentioned.

**Comment by marpme** [comment]
Should be fixed, closing issue. If you still have the problem please open it up again.
