### ISSUE TITLE
Recommended wallet for pools

### ISSUE THREAD

**Issue by pool2mine** [vergecurrency/VERGE#868]
Hello, my pool luck had a sudden drop, i have installed the new wallet using clearnet branch, now my yiimp shows  v4.0.2.0-29c7021-bet, im i using the right wallet version?

**Comment by marpme** [comment]
If unsure:

git fetch && git checkout 4.0.3b 

And then build based on that tag, although your version looks good to me as long as you aren’t on 5.0.x

**Comment by JasonGaoG** [comment]
@marpme ，hi，I want to know the yiimp pool could work well with the VERGE 5.0 ?  should I run verge without-tor?

**Comment by marpme** [comment]
Well VERGE-5.0 alpha is not stable enough to offer its services for a pool mining like yiimp. 
Please wait for the beta release, as we have to fix some stuff (like mining issues etc)

**Comment by JasonGaoG** [comment]
hi  @marpme, thank you. another question, does the 4.0clearnet support algo blake2s?  or I can only set algo= blake? I  set algo=blake2s .  when I run VERGEd getinfo. I get  "pow_algo" : "scrypt",  so I want to know how to set algo=blake2s.

**Comment by JasonGaoG** [comment]
algo=blake2s works well on wallet 5.0 version.
