### ISSUE TITLE
Tor port change from VERGE.conf

### ISSUE THREAD

**Issue by goodthebest** [vergecurrency/VERGE#871]
Hey Devs, is there any flag we can use to change tor port from VERGE.conf? I tried **torport=** in VERGE.conf but VERGEd doesn't seem to honor it.

**Comment by justinvforvendetta** [comment]
which version

**Comment by justinvforvendetta** [comment]
try -torsocksport

**Comment by goodthebest** [comment]
thanks I'll try

**Comment by justinvforvendetta** [comment]
should work my man =]
`https://github.com/vergecurrency/VERGE/blob/e48aa8ec0684d19bf3c988821b10bf1a46042296/src/torcontroller.cpp#L63`
