### ISSUE TITLE
Flyclient

### ISSUE THREAD

**Issue by karanpatel863** [vergecurrency/VERGE#884]
"I'm submitting a ... "
 - [x] feature request

Check out @benediktbuenz’s Tweet: https://twitter.com/benediktbuenz/status/1101241113262776321?s=09

What do you guys think of better version of SPV clients known as flyclient which is super light client for all PoW blockchains. One only needs to download O(log(n)) block headers. Please read the paper I've attached it's already working in two projects.

"In this paper, we introduce Flyclient, a novel transaction verification protocol for light clients that is efficient both asymptotically and practically. Our protocol requires to download only a logarithmic number of block headers to synchronize and verify transactions while storing only a single block header between executions. We formally prove that Flyclient is optimal for this class of protocols. For Ethereum, our protocol achieves a proof size of only less than 500 KB. This is achieved by utilizing a simple design based on Merkle Mountain Range (MMR) commitments and a probabilistic block sampling protocol. Flyclient overcomes the limitations of NIPoPoWs and generates shorter proofs over all measured parameters. We also discuss how Flyclient can be implemented via a soft fork in Bitcoin/Ethereum."

**Comment by marpme** [comment]
We really appreciate your contribution, but unfortunately those clients are independent from our current codebase (afaik). In the end they would result in a completely new client, which has to be developed and maintained. Thus I think it would make more sense to first establish a client with some developers as we don’t have any open resources and then we can talk about a possible integration into our codebase (if any changes are needed)

**Comment by karanpatel863** [comment]
Thanks & ya you are right it is independendent of verge codebase but Afaik
it can be soft forked into verge codebase as told by its dev. There are
couple of projects who did so and saw the results which is impressive as
their flyclients are already live. In the meantime if you find some time
please give the paper a read.

**Comment by pcp1985** [comment]
Let's keep a note of the same and don't miss this... Looks a value addition
to us if gets integrated, whilst am continous about our developers time as
well.

**Comment by marpme** [comment]
Seems like interest is gone unless someone wants to actively develop this

**Comment by justinvforvendetta** [comment]
also we have the option of adding electrum server to the core, which could be a great value to our existing spv wallets
