### ISSUE TITLE
Block signatures couldn't be created 5.0.0-beta

### ISSUE THREAD

**Issue by cod3gen** [vergecurrency/VERGE#885]
## Context

Was giving 5.0.0-beta a spin, but i keep bumping into failed block signatures when trying to submit a block. Any ideas why that would be?

## Prerequisites

* Latest 5.0.0-beta on github. Ubuntu 18.04, Yiimp stratum

## User Story:

Bug Report, or support.

Verge daemon log;

> 2019-03-02T09:34:30Z Sign failed

## Expected Behavior

Accepted block..

## Current Behavior

While trying out the latest master of verge core, i get following error while submitting block:

> 09:34:30: ERROR VERGE Scrypt Block signatures couldn't be created **(Error reponse from RPC cli)**
> 09:34:30: *** REJECTED :( VERGE Scrypt block 2939061 1 txs
> 09:34:30: REJECTED XVG block 2939061

**Comment by marpme** [comment]
a Block requires at least one transaction to a public key source (outgoing). 
I've updated `nomp` to work with our requirements.

https://github.com/marpme/node-stratum-pool

If you don't want to switch the pool software, you have to make sure that the requirement is given.
I personally solved it to statically add pool fees to a pubkey instead of an address.

We plan to fully get rid of the block signature as it is only necessary for POS systems.

**Comment by justinvforvendetta** [comment]
ps: @cod3gen ill throw some x17 on your pool if you add verge to it. i dont own a scrypt asic =\

**Comment by justinvforvendetta** [comment]
also @marpme alot of pool software used to have a "hybrid" option that would work by default for verge. strange they dont do that anymore, but then again, it was strange to be a hybrid, with pow only lol

**Comment by cod3gen** [comment]
@marpme Does the pubkey have to be script? Looking at your code i see;

> return util.pubkeyToScript(

Are there any testnet nodes available?

**Comment by cod3gen** [comment]
@justinvforvendetta Will add X17 once the new daemon is up and stable :-)

Also, Yiimp has this "hybrid" option, setting rpc encoding to POS in yiimp coin settings, but it kinda does not work for 5.0.0 - it does work on clearnet though

**Comment by marpme** [comment]
@cod3gen Well have a look at this piece of code: 

https://github.com/marpme/node-stratum-pool/blob/12673c137d97d949d8c9b3536a6b731d8331c0fa/lib/util.js#L240-L253

I didn't touch it, but it's basically generating an valid script based on your given 33-bytes-long pubkey
Maybe you get it working with this information.

I will try to bring up an running scrypt testnet pool based on nomp.

**Comment by cod3gen** [comment]
Did a "nasty" fix to overcome the block signature similiar to your solution 😄 ; creating a 1% charity for the pool mining address, which seems to overcome this particular issue. Next in line is 🥁🥁🥁 :

> 2019-03-03T13:59:48Z CreateNewBlock(): block weight: 796 txs: 0 fees: 0 sigops 400
> 2019-03-03T14:00:07Z BlockSign successfully done with: TX_PUBKEY
> 2019-03-03T14:00:07Z CBlock(hash=000000000002672e7a1f401b9b12041c3e6413e1716cd57f4c21176b4350c7aa, algo=scrypt, ver=0x00000002, hashPrevBlock=092cd511919aca03103ebf4c4cf038454b9818064256c509576c7599223730a0, hashMerkleRoot=5c0d7675527d91$
>   CTransaction(hash=5c0d767552, nTime=1551621587, ver=1, vin.size=1, vout.size=2, nLockTime=0)
>     CTxIn(COutPoint(0000000000, 4294967295), coinbase 0380e42c04d4dd7b5c0881000016d30f00007969696d7000, nSequence=0)
>     CScriptWitness()
>     CTxOut(nValue=722.00700000, scriptPubKey=2103ffba84fe92f160298a5213f612)
>     CTxOut(nValue=7.00300000, scriptPubKey=76a914edd4b7e8dee8ccb9290eb9fa)
> 
> 2019-03-03T14:00:07Z ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: 000000000002672e7a1f401b9b12041c3e6413e1716cd57f4c21176b4350c7aa, bad-version(0x00000002), rejected nVersion=0x00000002 block (code 17)
> 2019-03-03T14:00:07Z ERROR: ProcessNewBlock: AcceptBlock FAILED (bad-version(0x00000002), rejected nVersion=0x00000002 block (code 17))

**Comment by karanpatel863** [comment]
In your source code have you set charity_address already?

**Comment by karanpatel863** [comment]
Maybe you are using two different versions in the code? (Ver=1 &
ver=0x00000...2 )

**Comment by cod3gen** [comment]
It seems that 5.0.0beta is reporting wrong version.. for scrypt atleast, it reports version "2" in blocktemplate, while 4.0.3clearnet reports "2052" which is consistent with scrypt generated blocks

**Comment by cod3gen** [comment]
Forcing version 2052 in stratum also results in a rejected block, with ver=0x00002052 daemon thinks its a blake block?

**Comment by marpme** [comment]
What height is your blockchain at? Cause we had version 2 until 3.4X million blocks

**Comment by cod3gen** [comment]
verge-cli getblockcount
2942260

**Comment by marpme** [comment]
Well, okay. I guess you should sync first and in the mean time you have to push a fix for the versioning as it only decides between version 2 and version 4. Depending on your current algorithm you also have to add the block version.

So basically:

```cpp
block.version = nHeight > 3,400,000 ? 4 : 2;
block.version |= USED_BLOCK_ALGO;
```

See algo ids here: 

https://github.com/vergecurrency/VERGE/blob/96e1b3cb5737a344c8503988761a7c8d83372865/src/primitives/block.h#L31-L45

**Comment by cod3gen** [comment]
Think i hit "jackpot" on blocks 2942265 2942267

**Comment by marpme** [comment]
I guess this will help you to easier integrate the multiple hashing algo's for verge

![image](https://user-images.githubusercontent.com/7430964/53698336-8f21cd00-3ddb-11e9-9d9b-0aa83785d30d.png)

Just leave me a short feedback on this if needed @cod3gen @justinvforvendetta

**Comment by cod3gen** [comment]
Wheys;

>  verge-cli getbalance
> 1460.420850
> verged --version
> Verge Core Daemon version v5.0.0.0

> **I guess this will help you to easier integrate the multiple hashing algo's for verge**

Yeah, that would be a great solution! This would actually make it possible to run only one daemon for 5 different algos... In theory?

To temporary fix this in Yiimp i just replaced
`sprintf(templ->version, "%08x", (unsigned int)json_get_int(json_result, "version"));` in coind_template.cpp with:
```
if (strcmp(coind->symbol, "XVG") == 0 || strcmp(coind->symbol2, "XVG") == 0) {
		if (!strcmp(coind->algo, "lyra2v2"))
			sprintf(templ->version, "%08x", (unsigned int)20484);
		else if (!strcmp(coind->algo, "x17"))
			sprintf(templ->version, "%08x", (unsigned int)6148);
		else if (!strcmp(coind->algo, "blake"))
			sprintf(templ->version, "%08x", (unsigned int)8196);
		else if (!strcmp(coind->algo, "myr-gr"))
			sprintf(templ->version, "%08x", (unsigned int)4100);
		else
			sprintf(templ->version, "%08x", (unsigned int)2052);
	}
	else
		sprintf(templ->version, "%08x", (unsigned int)json_get_int(json_result, "version"));
```

Additionally adding charity address and percentage to make sure its signed as expected by daemon.

**Comment by marpme** [comment]
@cod3gen see c5957d371158be0fdee6dc20e47b4464c8d4b715 on develop branch

**Comment by cod3gen** [comment]
Nice!

> :~/coins/VERGE# verge-cli getblocktemplate "{\"algo\": \"x17\"}"
> {
>   "capabilities": [
>     "proposal"
>   ],
>   "version": 6148,

**Comment by marpme** [comment]
Glad to help you out

**Comment by cod3gen** [comment]
Not so nice 😁 

> verge-cli getblocktemplate
> {
>   "capabilities": [
>     "proposal"
>   ],
>   "version": 4,

Should default to whatever algo is default.. scrypt if none is defined in config? or what is defined in config. 

Current develop build fails btw, "algo" is not defined, and typo; result.pushKV("version", version**)**);

**Comment by marpme** [comment]
Yep already fixed that, just adding the default version to scrypt and then I will push it to develop

**Comment by marpme** [comment]
I think we can close this issue for now. Maybe we should consider writing a short mining guide to explain certain specialties :) let me know what you think.
