### ISSUE TITLE
Sending stealth transaction

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#887]
# Issue

## Context 

When sending a stealth transaction with the normal user interface the transaction internally is falsely produced and propagated into the network.

## Solution

It should create a transaction with two outputs, where one consists of a OP_RETURN with your PubKey (Receivers) attached and one output to a normal pubkeyhash. Reference see: Dual-Key Stealth addressing (or V4 of our Verge Core)

**Comment by marpme** [comment]
#892

**Comment by justinvforvendetta** [comment]
animal.
