### ISSUE TITLE
rpcbind required for remote connections?

### ISSUE THREAD

**Issue by cod3gen** [vergecurrency/VERGE#888]
# Issue Template

## Context

Unable to connect to the daemon, unless daemon is binded to network card ip address. rpcallow does not work.

## Prerequisites

5.0.0 develop
Ubuntu 18.04

## User Story:

  **MAYBE**: [ ] bug report 😄 

The daemons looks like its bound to 0.0.0.0 which should allow access across all network devices, right? (Assuming remote device IP address is allowed in config)
```
tcp        0      0 0.0.0.0:15556      0.0.0.0:*               LISTEN      26544/verged
tcp        0      0 0.0.0.0:15559           0.0.0.0:*               LISTEN      26544/verged
tcp6       0      0 :::15559                :::*                    LISTEN      26544/verged
```
This works on other daemons at least. However i was not able to communicate with the new verge daemon using this method, however by starting the daemon with a specified `--rpcbind=192.168.1.50` - i can access the daemon remotely with a computer on the same network:
```
tcp        0      192.168.1.50:15556      0.0.0.0:*               LISTEN      30664/verged
tcp        0      0 0.0.0.0:15559           0.0.0.0:*               LISTEN      30664/verged
tcp6       0      0 :::15559                :::*                    LISTEN      30664/verged
```

Not really a problem since it can be binded to a specific IP, and heck its even safer, but i though is should put some light on this.

**Comment by marpme** [comment]
I quote stackoverflow for this one: [127.0.0.1 vs 0.0.0.0](https://serverfault.com/a/78058)

> 0.0.0.0, in this context, means "all IP addresses on the local machine" (in fact probably, "all IPv4 
> addresses on the local machine"). So, if your webserver machine has two IP addresses, 192.168.1.1
> and 10.1.2.1, and you allow a webserver daemon like apache to listen on 0.0.0.0, it will be reachable at both of those IP addresses. But only to what can contact those IP addresses and the web port(s). 

So I guess everything is working as expected as you are probably not on the same machine, thus you have to explicitly bind a specific IP interface.

**Comment by justinvforvendetta** [comment]
binding to 0.0.0.0 is never recommended

**Comment by cod3gen** [comment]
Binding to 0.0.0.0 is by default on all daemons i think, but binding to a
specific adapter is safer👍

Den man. 4. mar. 2019, 21:33 skrev sunerok <notifications@github.com>:

**Comment by justinvforvendetta** [comment]
see https://github.com/bitcoin/bitcoin/issues/8502#issuecomment-239621457

**Comment by cod3gen** [comment]
Yeah, the test daemon was missing server=1 in config, which was the reason for the result i had.
- If there is no instances of rpcallowip, the daemon will bind to 127.0.0.1 allowing only localhost access
- If there is instances of rpcallowip, and server= is not set or false, it seems that the daemon will bind to 0.0.0.0 but not allow remote connection(undependent of defined rpcallowip's)??
- If there is instances of rpcallowip, and server=1 daemon will bind to 0.0.0.0 and allow access from all rpcallowip's

**Comment by pcp1985** [comment]
- portmapper on RHEL-5 could be secured by having it listen on localhost
   only. rpcbind does not offer this option. tcpwrappers and firewall can be
   used for securing both portmapper and rpcbind.
   - To secure rpcbind with tcpwrappers use something like:

Raw <https://access.redhat.com/solutions/106563#>

# cat /etc/hosts.allow
rpcbind: 127.0.0.1

# cat /etc/hosts.deny
rpcbind: ALL
