### ISSUE TITLE
Release: V5.2.1

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#895]
### Checklist Pre-release:

 - [ ] Test are enabled and green
 - [ ] Test runs are completed. 
 - [ ] Binaries are created (win 32/64bit, macos)
 - [ ] Signature are valid
 - [ ] change notes are prepared
 - [ ] No obstacles, no showstoppers or 

Release-tag: `v5.0.0-rc1`
Release-date: `12th May 2019`
production-ready: `yes`

Required/Open PR(s)/Issue(s):

clean up,
Images etc 

Feel free to add further information or inform about certain problems about the release within this thread.

**Comment by marpme** [comment]
Re-dated to 12.04.

**Comment by marpme** [comment]
Release outputs:

* tag v5.0.0-beta1 
* Windows binaries (QT and Daemon)
* Linux (Ubuntu 18.04) binaries (QT and Daemon) 
* macOS binaries (10.14) binaries (QT only)
* Docker Release V5.0.0-beta1

**Comment by marpme** [comment]
We did it ... two weeks ago! 

Next release is release candidate before the final release.
Updating the original ticket

**Comment by Turtus** [comment]
Hi @marpme, maybe you could remove branches that are not used anymore - as there are a lot of not used or already merged ones, thanks in advance

**Comment by marpme** [comment]
This is blocked by: #903 & #902
