### ISSUE TITLE
not able to get getallnetworkhashps and getnetworkhashps properly

### ISSUE THREAD

**Issue by cod3gen** [vergecurrency/VERGE#897]
# Issue Template

## Context

Not able to get getallnetworkhashps and getnetworkhashps properly

Providing context helps us come up with a solution that is most useful in the real world -->

## Prerequisites

v5.0.0Beta

## User Story:
  - [x] bug report

getallnetworkhashps returns;
```
{
  "scrypt": 0,
  "groestl": 0,
  "lyra2re": 0,
  "x17": 0,
  "blake2s": 0
}
```

And getnetworkhashps return 0.

## Expected Behavior

Expect to get network hashrate on each algo by using getallnetworkhashps, and network hashrate on daemons algo by getnetworkhashps

## Current Behavior

Return 0 on all.

* Verge Release: 5.0.0Beta
* OS: Ubuntu 18.04

**Comment by marpme** [comment]
Well, we can probably try to estimate hash power via difficulty, but it will never be as precise as counted hash power

**Comment by marpme** [comment]
The mathematical approach could be to use this Formular and restructure it to solve the hashrate: 

time = difficulty * 2**32 / hashrate

This is a very broad estimation and would be done based on the last known blocks.

So we would have to reverse iterate over the  blocks until we found the last block of each algorithm available.

And then we can use this Formular to kinda estimate the latest hashrate

**Comment by cod3gen** [comment]
Yeah, turn it around and the formula would be `difficulty * 2**32 / ttf`. For XVG and a couple other multialgo coins, i am reverse iterating from current block back 120 blocks to get a decent accurate current nethash speed. For other coins, that does support `getnetworkhashps` properly i use `getnetworkhashps 120 <current block height>` to get the same equation. 

The method of going back 120 blocks(even thought they are cached) consumes unnecessary stress on daemon, redis and other applications included in each call, instead of getting the result directly from VERGE daemon which would do the same task quicker.
