### ISSUE TITLE
Drop down menu(s) - Interface bug

### ISSUE THREAD

**Issue by CryptoSyndrome** [vergecurrency/VERGE#90]
Current bug was found with **Verge wallet version 3.0 (Wraith Release 1)** / **Windows OS**

**Download link**: [https://github.com/vergecurrency/VERGE/releases/download/3.0/verge-3.0.zip](url)

- The following bug occurs when you want to pick a value from the drop down menu.

- Located at **Settings\Options\** , following menus **(Main - Network - Display)** 

- Samples of this bug:

![2017-11-15_22-23-17](https://user-images.githubusercontent.com/33702499/32859558-86ad1d08-ca57-11e7-8451-f240d5e92f58.jpg)
![2017-11-15_22-28-42](https://user-images.githubusercontent.com/33702499/32859559-86d674dc-ca57-11e7-9945-5ac9cf06148c.jpg)

**Comment by justinvforvendetta** [comment]
we're working on revamping the ui =]
