### ISSUE TITLE
Error compiling v5.0.0-beta1.tar.gz

### ISSUE THREAD

**Issue by paradoxicalNL** [vergecurrency/VERGE#900]
autogen gives error on line 24, ./autogen.sh: line 24: ./autogen.sh: No such file or directory

`(cd "${srcdir}/src/tor" && ./autogen.sh)`

This dir is empty:

paradoxical@zod:~/git/VERGE-5.0.0-beta1/src$ cd tor
paradoxical@zod:~/git/VERGE-5.0.0-beta1/src/tor$ ls
paradoxical@zod:~/git/VERGE-5.0.0-beta1/src/tor$

**Comment by marpme** [comment]
Nice find, I probably have to extend the Makefile to also include this exact tor folder and its contents

**Comment by marpme** [comment]
*Workaround*: Use git and `git checkout v5.0.0-beta1`

**Comment by paradoxicalNL** [comment]
Downloaded from the linked ones using wget, I will give this a go asap, but easter stuff today :)

**Comment by paradoxicalNL** [comment]
This works, forgot to --disable-bench however. It takes a while on 1 core only!
