### ISSUE TITLE
New Wallet version.

### ISSUE THREAD

**Issue by Romeo01234** [vergecurrency/VERGE#905]
Hello everyone, I just wanted to confirm with you all that the new Version 5 release wallet is the one to use and Sending/Receiving coins will work ok.

Are Stealth Transactions working for this version as well.

Thanks, and good work. Keep it going.

**Comment by justinvforvendetta** [comment]
@Romeo01234 version 5 is a release candidate, meaning post beta, pre full release.

**Comment by marpme** [comment]
I have tested a lot of the wallet functionalities and couldn't find any errors anymore.
Just give it a try with low coin amounts to check if it really works and then you can go in with your full amounts too
