### ISSUE TITLE
error reading wallet.dat file: wallet can be read, but transaction data missing

### ISSUE THREAD

**Issue by Hefzibah** [vergecurrency/VERGE#907]
# Issue Template

Receiving an error when starting up Verge QT 4.0 “warning! Error reading Wallet.dat. All keys read correctly, but transaction data or address entries might be missing or incorrect

I hav tried already everything, from restoring an old wallet, trying older wallet.dat files,  I don't know what to do anymore.

I send coins from an old wallet that wasn't synked to another wallet. The wallet did not sync anymore, so I downloaded the blockchain, but it wouldn't sync then either. on telegram I was advised to upgrade the wallet, first saving the wallet.dat file. 
I did, and replaced the wallet.dat.
this went well, but again the wallet did not want to sync.
Then I tried to upload the blockchain to jumpstart the syncing. This did not work.
Then I removed the wallets completely, installed the Q4 wallet again, replaced the wallet.dat again. and now I get this error.

## Prerequisites

* [ ] Are you running the latest version? yes

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ x] support request 
  - [ ] translation request 

 Mac version 10.13.6

## Steps to Reproduce (for bugs)

 send coins from wallet when it isn't synced. Don't let it sync, but save the wallet.dat. Then reinstall wallet and see if this error occurs.
I can also send you the dat file.

Kind regards
Hefziba

**Comment by justinvforvendetta** [comment]
what happens when you say ok to the warning? are you able to get into the debug console of the wallet? in the blockchain data directory, you have a file called debug.log. can you pastebin it and give us a link to it? maybe delete it first, open the wallet for a while, and then paste it to us so we can see exactly why its having this issue..

**Comment by Hefzibah** [comment]
If I say ok the wallet force closes, so I can't get to the debut log
My first wallet.dat file I ever saved works , I can open the wallet and see the first transaction, but it is not syncing. In the debug file I get errors in this case. I tried to add the downloaded blockchain, and then it syncs  before opening the wallet, but after it says 100% the wallet freezes and is un-responsive.

**Comment by Hefzibah** [comment]
what I mean is that with the newest wallet.dat files I cannot get into the wallet, I only see this error. With the old wallet.dat I can get into the wallet, but I will not sync.

**Comment by justinvforvendetta** [comment]
ok, go back to the original wallet.dat that works but doesnt sync. the syncing is the problem. are you running other wallets at the same time, or in a country that blocks tor?

**Comment by jrsikors** [comment]
well justin beat me to it, but i'll post anyways 👍 

There are some guides here for troubleshooting QT issues:
https://verge.zendesk.com/hc/en-us/sections/360002295772-QT-Wallet

Are you in a country that blocks Tor like Iran, Turkey, or China? 

Just for troubleshooting purposes -- and to get your funds -- you could always try on a different computer.  Mac version of QT 4 seemed very unstable, and becomes unresponsive a lot.  

But if you had access to a Windows or UNIX machine, your wallet.dat , as long as it's not corrupt, would work fine on Mac, Windows, and/or UNIX.

**Comment by Hefzibah** [comment]
I am in the Netherlands, so I guess not, but could it be Sofos that is blocking it, a software I have installed myself?

**Comment by Hefzibah** [comment]
Thank you both. Ok I will have a look at my options.

1) windows computer
2) go through the zen desk

Just for my knowledge, does it matter if I have an old or recent backup wallet.dat?

**Comment by justinvforvendetta** [comment]
it should not, but it sounds like the copy you have that is giving you an error, is corrupt. please use the original one you have. the wallet.dat wont have an affect on syncing. the syncing problem is what we need to fix. port 21102 is the one verge qt uses, and tor is also running on it. if you have tor already running, that could be one problem.

**Comment by jrsikors** [comment]
each wallet.dat will have 1 or more "addresses".  If all of your coins are on addressXYZ, and your wallet.dat has addressXYZ ... then it doesn't matter if it's recent or old.

If you make transactions, sometimes some of your coins move to a "change address", we'll call it addressABC.  So if that was the case, your older wallet.dat might not have addressABC.

But yeah as Justin said -- your new Mac not getting any connections/sync'd at all is weird and i would check out those articles to see if you can do that.

**Comment by Hefzibah** [comment]
This is more technical than i am used to. Where can I check if Tor is
already running or if port 21102 is already being used?
I need to go to sleep ( 3am here)  and will try to fix it tomorrow. But an
answer on above question is definitely appreciated.

**Comment by justinvforvendetta** [comment]
if you dont have tor installed, then its probably not running, which is good, because its built into the app. i meant are you running other crypto coin wallets at the same time?

**Comment by Hefzibah** [comment]
@jeff I might than have lost quite some coins. I made 3 backups of the
recent wallet, but all are corrupt.
And coins were send after the old wallet with an out of sync wallet. Coins
were out of my wallet, so probably send to an in between address.
We will see.

**Comment by Hefzibah** [comment]
Thank you both for helping. Actually got a friend to respond in telegram, that I have known for a long time, but did not know he was part of verge: Kaspar_NL.    He helped me solve it and you can close the issue.

For others that had the same issue: I cleaned my whole library from any reminiscent verge wallet files, that were there. and installed the latest wallet from the verge website.
My last saved Wallet.dat file responded again, without an error, and wasn't corrupted.  However, the wallet did not want to sync and I downloaded the blockchain, as described in many help sections.  The wallet again stopped responding, but I reopened it and gave it time. Finally it opened and synced. My last transaction that was still pending went through when the blockchain was synced. If this hadn't worked I would've tried the last wallet.dat file on windows.  Also I learned that you can encrypt the wallet.dat file to make sure it doesn't get stolen and prevent it from getting corrupted.
