### ISSUE TITLE
Truncate instead of erroring

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#908]
```cpp
if (!ParseFixedPoint(value.getValStr(), 6, &amount))
        throw JSONRPCError(RPC_TYPE_ERROR, "Invalid amount");
```

>can you just truncate or something?
>none of the other bitcoin forks we have does this
>and we dont support it right now

**Comment by justinvforvendetta** [comment]
**marpme [2:21 PM]**
maybe we can come together by then

**sunerok [2:21 PM]**
_*thats what she said*_

**Comment by justinvforvendetta** [comment]
this is still a prob

**Comment by marpme** [comment]
Seems like no one is caring.
