### ISSUE TITLE
GUI stealth transaction creation

### ISSUE THREAD

**Issue by cue108** [vergecurrency/VERGE#910]
If you have a locked wallet, you can create receiving addresses without any problems. They will end up in the list of addresses you created and the nice popup dialog box appears with the QR code.

NOW

try doing this with the checkmark on Stealth Address.
YOU DONT get an error message on the GUI except on the command-line interface (the bash shell I opened verge-qt with):
Error: CWallet::AddStealthAddress wallet must be unlocked.
On the GUI you get shown the dialog box with a generated QR code for nothing.

Happens on QT V5.1

* "I'm submitting a ... "
  - [x] bug report

* Verge Release: QT5.1
* OS:
    - [x] I'm using Linux

**Comment by cue108** [comment]
I have just inspected the latest version 5.1.1
I was thinking it would contain the fix already. I did a little unlisted video for you.
https://youtu.be/K-uRdM7Eu-g

**Comment by justinvforvendetta** [comment]
@cue108 thanks! ill look into this in an hour. we will leave it open for now.

**Comment by Desolatorbtc** [comment]
On windows, I have a similar issue. If the wallet is locked it won't generate any stealth address. If i try:

Help > Debug window > Console Tab
and write:
walletpassphrase "your pass phrase" 120

it unlocks the wallet for 2min and i can generate a stealth address. So it works but just question of convenience.

**Comment by justinvforvendetta** [comment]
@cue108 so the address shows up when you generate it, but it does not save, correct?

**Comment by cue108** [comment]
@justinvforvendetta  It does not create a stealth address but shows an error message in the terminal I started the wallet with.
When I unlock the wallet everything works just fine.

**Comment by justinvforvendetta** [comment]
@cue108 gotcha, thanks
