### ISSUE TITLE
Finding received stealth transaction (flaky)

### ISSUE THREAD

**Issue by cue108** [vergecurrency/VERGE#911]
I just made a stealth test transaction from my QT4 wallet to the QT5.1 Wallet.

The corresponding public transaction has meanwhile 169 confirmations and is done, but I do not see any funds arriving in the QT5.1 wallet yet.

Status: 169 confirmations, broadcast through 20 nodes
Date: 20.05.19 09:50
To: DD4HP7Y4KtKwcQogsRa6Rk8Hp324ftKATs
Debit: -1.00 XVG
To: 1Wh4bh
Debit: 0.00 XVG
Transaction fee: -0.123779 XVG
Net amount: -1.123779 XVG
Transaction ID: 30b67ff0ab3796dc488a9efc726f186c29ad68191a48d06aa56f66f3a1e05ecf

  - [x] bug report
  - [x] support request 

## Your Environment

* Verge Release: 
v4.0.1.0-7bd8de5-funky-beta Wallet sending to stealth address created under
Verge Lumos version v5.1.0.0 (64-bit)
* OS:
    - [x] I'm using Linux

**Comment by cue108** [comment]
I could fix it with the CLI command:
rescanblockchain fromblock toblock!
It's all there, so I guess this issue is kind of solved?

**Comment by karanpatel863** [comment]
Yeah. If your issue has been solved, Please close the issue. Thanks

**Comment by cue108** [comment]
Thank you for your responses so fast - you guys are awesome!

**Comment by marpme** [comment]
Let's keep it here as part of a new issue for us to slove the flaky'ness of the transaction finding process (for stealth addresses only)

**Comment by marpme** [comment]
Fixed in v5.3.1
