### ISSUE TITLE
incompatible: Electrum-Tor-Client -> Electrum-Server -> verged 5.1

### ISSUE THREAD

**Issue by swat69** [vergecurrency/VERGE#912]
A transaction with the Electrum-Tor-Client v2.4.1 is rejected when using verged 5.1

On the Electrum-Server: electrum.log:

[20/05/2019-12:04:41] error: Your client produced a transaction that is not accepted by the Bitcoin network any more. Please upgrade to Electrum 2.5.1 or newer

**Comment by justinvforvendetta** [comment]
you mean you are running the 5.1 daemon on your electrum server and the client isnt producing proper TX ?

**Comment by swat69** [comment]
exactly.
well, after the 3rd restart of everything it's working, transaction successfully.
I don't get it, I made a few test and all without success.

**Comment by justinvforvendetta** [comment]
we can keep this open for now then. if it happens again, please make a comment here..

**Comment by swat69** [comment]
After further tests:
I press send, get an error, wait 3 seconds press again, always rejected, this 4 times and suddenly the transaction is broadcasted successfully.
On the next try I can send 3 times without an error, weird.
And the error varies.

--------------------------------------------------------------------------------------------------
Error1:
verged 5.1, debug.log:
2019-05-22T20:43:37Z received: getdata (37 bytes) peer=7
2019-05-22T20:43:37Z received getdata (1 invsz) peer=7
2019-05-22T20:43:37Z received getdata for: tx 235c23cc2acf125f6656001750a891be83d7a7c9542d43f7cdcf6af82e9f1028 peer=7
2019-05-22T20:43:37Z sending tx (230 bytes) peer=7
2019-05-22T20:43:39Z sending inv (37 bytes) peer=0
2019-05-22T20:43:41Z Received a POST request for / from 127.0.0.1:60234
2019-05-22T20:43:41Z ThreadRPCServer method=sendrawtransaction user=elecX
2019-05-22T20:43:43Z Received a POST request for / from 127.0.0.1:60236
2019-05-22T20:43:43Z ThreadRPCServer method=getinfo user=elecX
2019-05-22T20:43:43Z Received a POST request for / from 127.0.0.1:60238


Electrum-Server
[22/05/2019-22:43:41] error: The transaction was rejected by network rules.(txn-mempool-conflict (code 18))

Client:
![image](https://user-images.githubusercontent.com/28594828/58209155-c7ec8680-7ce6-11e9-909d-bb6d11f66b45.png)
--------------------------------------------------------------------------------------------------------
Error2:
Electrum-Server:
[22/05/2019-22:38:42] bitcoind is responding
[22/05/2019-22:38:45] TCP        127.0.0.1:49700   28 2.4.1
[22/05/2019-22:38:45] TCP        127.0.0.1:49672   61 2.4.1
[22/05/2019-22:38:58] error: Your client produced a transaction that is not accepted by the Bitcoin network any more. Please upgrade to Electrum 2.5.1 or newer
[22/05/2019-22:39:19] SSL        127.0.0.1:49242    1 2.4.1

verged 5.1, debug.log:
2019-05-22T20:38:52Z Received a POST request for / from 127.0.0.1:59830
2019-05-22T20:38:52Z ThreadRPCServer method=getinfo user=elecX
2019-05-22T20:38:52Z Received a POST request for / from 127.0.0.1:59832
2019-05-22T20:38:52Z ThreadRPCServer method=getblockhash user=elecX
2019-05-22T20:38:52Z Received a POST request for / from 127.0.0.1:59834
2019-05-22T20:38:52Z ThreadRPCServer method=getblock user=elecX
2019-05-22T20:38:52Z Received a POST request for / from 127.0.0.1:59836
2019-05-22T20:38:52Z ThreadRPCServer method=getrawmempool user=elecX
2019-05-22T20:38:58Z Received a POST request for / from 127.0.0.1:59838
2019-05-22T20:38:58Z ThreadRPCServer method=sendrawtransaction user=elecX
2019-05-22T20:39:02Z Received a POST request for / from 127.0.0.1:59840
2019-05-22T20:39:02Z ThreadRPCServer method=getinfo user=elecX
2019-05-22T20:39:02Z Received a POST request for / from 127.0.0.1:59842
2019-05-22T20:39:02Z ThreadRPCServer method=getblockhash user=elecX
2019-05-22T20:39:02Z Received a POST request for / from 127.0.0.1:59844
 
Client
![image](https://user-images.githubusercontent.com/28594828/58209224-ea7e9f80-7ce6-11e9-826a-dafc8b229bdc.png)

**Comment by justinvforvendetta** [comment]
this is most likely a dust or tx fee issue, we can keep this open for now

**Comment by marpme** [comment]
electrumx in da pipeline. Chilly milly 💃

**Comment by justinvforvendetta** [comment]
this can be fixed in electrum 2.4.1 by lowering the fee from 1xvg to .1xvg

**Comment by ls-milkyway** [comment]
> this can be fixed in electrum 2.4.1 by lowering the fee from 1 xvg to .1 xvg, either in the .conf
> or with `--fee`

Plz state in detail...where is .conf file or full command with --fee option & where to run it?????

**Comment by justinvforvendetta** [comment]
@ls-milkyway you can change the fee in the applitcation settings, or in the electrum .conf file. the .conf file would be in the %appdata% electrum-xvg-tor directory

**Comment by ls-milkyway** [comment]
> @ls-milkyway you can change the fee in the applitcation settings, or in the electrum .conf file. the .conf file would be in the %appdata% electrum-xvg-tor directory

Its not working I have set 0.1 xvg for fee in the app...plz check the screenshot:
![app-settings](https://user-images.githubusercontent.com/55090624/83945809-c0811800-a82a-11ea-87ef-b7f0366f6b1a.PNG)

Moreover there is no fee settings in config file at C:\Users\<username>\AppData\Roaming\Electrum-XVG plz check screenshot:
![config](https://user-images.githubusercontent.com/55090624/83945865-04741d00-a82b-11ea-8e6a-59009a2689ba.PNG)

**Comment by justinvforvendetta** [comment]
try raising the fee to 1.0

**Comment by ls-milkyway** [comment]
tried raising fee ...by factor of 1 eg. 1 than 2 than 3 ...it's not working ...even downloaded latest network.py file as per their instructions @ [https://verge.zendesk.com/hc/en-us/categories/360000975931-Technical-Assistance](url)

It's same "error: Your client produced a transaction that is not accepted by the Bitcoin network any more. Please upgrade to Electrum 2.5.1 or newer"

**Comment by rances** [comment]
> 
> 
> tried raising fee ...by factor of 1 eg. 1 than 2 than 3 ...it's not working ...even downloaded latest network.py file as per their instructions @ [https://verge.zendesk.com/hc/en-us/categories/360000975931-Technical-Assistance](url)
> 
> It's same "error: Your client produced a transaction that is not accepted by the Bitcoin network any more. Please upgrade to Electrum 2.5.1 or newer"

Did you ever managed to solve this?

**Comment by eugeneccnp** [comment]
I am also having this issue, did anyone manage to solve this, my first test transaction went into binance fine, the subsequent transaction throw the above error

**Comment by justinvforvendetta** [comment]
@eugeneccnp  @rances  a few things need to be clarified here guys.  you are -definitely- using the newest electrum from 6 months-ish ago, and not the one from years and years ago, right? also, what server are you connected to?

**Comment by eugeneccnp** [comment]
> @eugeneccnp @rances a few things need to be clarified here guys. you are -definitely- using the newest electrum from 6 months-ish ago, and not the one from years and years ago, right? also, what server are you connected to?

I was able to get around this issue by brute forcing all xvg out of electrum-xvg using windows electron.exe 2.4.1 client + tor, it took many attempts, the amounts didn't matter, between each attempt I closed and opened the client, I messed around with the fee but I don't think that did anything, anyways it's all transferred successfully now.

**Comment by justinvforvendetta** [comment]
@eugeneccnp more appropriate would have just been to upgrade the wallet from a several year old version to the newest one, but ok! lol

**Comment by Jamany009** [comment]
Hi , just checked my electrum wallet 2.4.1 and I have same issue here, I ´m trying send XVG in to new Qt wallet Leviosa, but it still shows same message, I trying changing fee, it won´t work, any help ?

**Comment by eugeneccnp** [comment]
> Hi , just checked my electrum wallet 2.4.1 and I have same issue here, I ´m trying send XVG in to new Qt wallet Leviosa, but it still shows same message, I trying changing fee, it won´t work, any help ?
> 
> Server : qz6pnufyqjexudq6.onion 50001
> SOCKS5 127.0.0.1 9151

Just keep trying, I brute forced my way through by just trying, 1/10 times it went through for me.

**Comment by Jamany009** [comment]
Already 20 times still nothing , sitting here at least 1 hour , still stuck

**Comment by justinvforvendetta** [comment]
update:  electrum 2.4.1 is several years old. try using the new as i suggested above. [](https://github.com/vergecurrency/electrum/releases/tag/v4.0.0-beta3)

**Comment by justinvforvendetta** [comment]
https://github.com/vergecurrency/electrum/releases/tag/v4.0.0-beta3

**Comment by Jamany009** [comment]
Thanks for your answer.

This newer version show up this message:

Cannot load wallet (1):
InvalidMasterKeyVersionBytes('Invalid extended key format: 0x488b21e',)

**Comment by swat69** [comment]
the old wallet file is not compatible, use your seed to restore your coins

**Comment by Jamany009** [comment]
Strange but on different PC I'm in , thanks for your help guys , stay positive

**Comment by ZebbHB2** [comment]
So... I followed the steps you made... I downloaded "electrum-v4.0.0-beta3-6-g8717e963-setup.exe", installed it, I restored my coins using my seed. - So, I should be able to send a transaction, right?
No. I get this message:
"BestEffortRequestFailed('no interface to do request on... gave up.',)"

![Unb111enannt](https://user-images.githubusercontent.com/77075364/103814136-7f234600-5061-11eb-9515-d8c3b51ef4d9.jpg)

I didn't change the network or anything in the preferences of electrum. The coins I "sent" are pending now for minutes - I can't check the details, when I click on "pay" the "BestEffortRequestFailed('no interface to do request on... gave up.',)" message returns - i just can delete the transaction. 

I just want to transfer my coins! :(
Doesn't work with electrum 2.4.1 and doesn't work with electrum 4.0.0a0 too.

What do I have to do to send my coins to binance f.e.?

**Comment by justinvforvendetta** [comment]
@ZebbHB2 see that red circle at the bottom? that should be green. your tor controller says it is connected to the tor network?

**Comment by ZebbHB2** [comment]
Yes - Tor is running and connected to network - I check this in between by browsing arround, onion sites respond fast. But that circle wents from green to red to green every few seconds.

**Comment by justinvforvendetta** [comment]
that part is fine.  can you right click that transaction and show the information? also, did you restore this wallet using your seedphrase, or just open the old electrum wallet file with the new electrum .exe?

**Comment by ZebbHB2** [comment]
Yes, I restored it with my seedphrase.
When I right click that transaction, I can delete the transaction - this works... but if I click on details nothing happens, and when I click pay I get a new message wich I haven't seen before. "TypeError('string indices must be integers',) - before I got the message I mentioned in my first post. AND RIGHT NOW the transaction went trough... two times... I made 2 tx an hour or something before, but deleted one of them a few seconds later.... 

![121212](https://user-images.githubusercontent.com/77075364/103823778-0927da80-5073-11eb-8da9-8a3af7600288.jpg)

Was I just impatient? ... oh wait... 2 tx went trough, but one is still pending. 

![123123123](https://user-images.githubusercontent.com/77075364/103823811-1644c980-5073-11eb-8822-d8907483adb5.jpg)

The circle also doesn't switch from green to red and back anymore - stays green. :)
I don't know what happened, but something happened.

**Comment by justinvforvendetta** [comment]
interesting. well i am glad it is working, but i will definitely send some xvg to an electrum wallet tonight and do some testing to see.  maybe i will use the old electrum, send funds, and then restore it on the new one, so i can recreate your situation.

**Comment by ZebbHB2** [comment]
That's cool, even the best never stop learning. :D 1st class customer service. 
If something crazy happens again, I'll be back to inform you.

So, thank you very much for your quick response and help, Sunerok.
Have a good night and stay healthy.

**Comment by justinvforvendetta** [comment]
no problem, glad it worked out. i'm starting some testing on it right now.
