### ISSUE TITLE
unable to build clearnet version

### ISSUE THREAD

**Issue by pinpins** [vergecurrency/VERGE#913]
Downloaded
https://github.com/vergecurrency/VERGE/archive/v5.1.0.tar.gz

Ubuntu 16.04

`./configure --without-gui --disable-tests --without-tor 
`
make

```

make
Making all in src/tor
make[1]: Entering directory '/home/pool/VERGE-5.1.0/src/tor'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/home/pool/VERGE-5.1.0/src/tor'
Makefile:784: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by justinvforvendetta** [comment]
--without-tor is a flag for the binary, not the build process

**Comment by jrsikors** [comment]
fixed the documentation:
https://github.com/vergecurrency/VERGE/pull/914

**Comment by jrsikors** [comment]
Basically -- whether or not you want to use Tor.. you still have to compile and have the dependencies installed.

After compile.. you can run verged --without-tor

**Comment by justinvforvendetta** [comment]
wasnt a fail my man, just not clarified.. sometimes its hard to create documentation from an unfamiliar perspective, when you're very familiar with the subject matter.

**Comment by pinpins** [comment]
Thanks guys, we are good now
