### ISSUE TITLE
Breaking mining support for thrown error (bad-blk-algorithm)

### ISSUE THREAD

**Issue by pinpins** [vergecurrency/VERGE#915]
Hello,

New 5.1.1 wallet, while pool mining following error on getblocktemplate appears with certain frequency

`
error -1: createnewblock: testblockvalidity failed: bad-blk-algorithm, contextualcheckblock : reused a mining algorithm too often (code 16)`

**Comment by satonio** [comment]
happens with 5.1.2 too.
is it dangerous?

**Comment by justinvforvendetta** [comment]
@satonio no its not dangerous. we need to move that check to submit block instead of createnewblock. we can leave this open for now.

**Comment by satonio** [comment]
But can't we be mining a wrong block because of that if getblocktemplate
fails??

**Comment by justinvforvendetta** [comment]
this is too make sure one algorithm doesnt get too many blocks in a row

**Comment by marpme** [comment]
I mean for mining operations that could be a highly interesting thing for automatically switching algorithms for profitability. There was this discussion before that blocks became "invalid"/rejected as there were to many of the same block algos in a row. So why would you waste your time/hashpower then, now you know it's useless to keep on mining until another block is found with another algorithm

**Comment by tpfuemp** [comment]
rather than throwing errors, it would be better to include this information in getblocktemplate.
something like this [https://github.com/tpfuemp/VERGE/commit/a50de0a4cff73f4ac1575af8b24ca423ccaac44d](url)

**Comment by cod3gen** [comment]
I have also noticed this, and the stratums do not like it when getblocktemplate fails or gives errors.. Stratum will shutdown and if error is given on multiple checks, it will stay down on yiimp pools, until pool op activates it again. 👎

**Comment by Ur-Quan** [comment]
> I mean for mining operations that could be a highly interesting thing for automatically switching algorithms for profitability. There was this discussion before that blocks became "invalid"/rejected as there were too many of the same block algos in a row. So why would you waste your time/hash power then, now you know it's useless to keep on mining until another block is found with another algorithm

True, but as cod3gen stated, it breaks yiimps. There is a more appealing way to signal not to mine this algo till next block: raise diff for an algo in question. I guess GLT guys have this kind of mechanic.

**Comment by marpme** [comment]
So then we would return an empty block template and drop the error message into a error message like 

{
  error: “bad block algorithm”
}

**Comment by tpfuemp** [comment]
I'm currently using this method:
[https://github.com/tpfuemp/VERGE/commit/8d7d14da835f7f33f0d3fd18624aa14e47f9e61c](url) to disable check on template create (TestBlockValidity() is only called from GBT, so it can be used to flag)
[https://github.com/tpfuemp/VERGE/commit/a50de0a4cff73f4ac1575af8b24ca423ccaac44d](url) to give the poolsoftware the necessary information to avoid useless mining

**Comment by fairmine** [comment]
Hello,

New 5.2.1 wallet, some error:

error -1: createnewblock: testblockvalidity failed: bad-blk-algorithm, contextualcheckblock : reused a mining algorithm too often (code 16)

**Comment by diabloblack** [comment]
Has this been fixed yet? What is the current work-around? (tpfuemp's links don't go anywhere)

**Comment by tpfuemp** [comment]
for mining you should stay on v4 node version until next release, as current v5 release version has some bugs related to mining

**Comment by laakie** [comment]
> for mining you should stay on v4 node version until next release, as current v5 release version has some bugs related to mining

When can we expect 'next release' ?
V4 has it's own stability problems sadly.
