### ISSUE TITLE
compilation of 5.1.2

### ISSUE THREAD

**Issue by Romeo01234** [vergecurrency/VERGE#918]
Hello attempting to compile "Verge v5.1.2" in Ubuntu 16.04.

The error I receive is the following.

make[2]: Entering directory '/home/coinz/verge-5.1.2Stealth/src/tor'
  CC       src/lib/tls/src_lib_libtor_tls_a-tortls_openssl.o
  CC       src/lib/tls/src_lib_libtor_tls_a-x509_openssl.o
  CC       src/lib/tls/src_lib_libtor_tls_testing_a-buffers_tls.o
  CC       src/lib/tls/src_lib_libtor_tls_testing_a-tortls.o
In file included from src/lib/tls/tortls_openssl.c:61:0:
./src/lib/tls/tortls_internal.h:48:8: error: conflicting types for ‘SSL_SESSION_get_master_key’
 size_t SSL_SESSION_get_master_key(struct ssl_session_st *s,
        ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2007:15: note: previous declaration of ‘SSL_SESSION_get_master_key’ was here
 __owur size_t SSL_SESSION_get_master_key(const SSL_SESSION *sess,
               ^
  CC       src/lib/tls/src_lib_libtor_tls_testing_a-x509.o
src/lib/tls/tortls_openssl.c: In function ‘tor_tls_client_is_using_v2_ciphers’:
src/lib/tls/tortls_openssl.c:929:20: error: dereferencing pointer to incomplete type ‘SSL_SESSION {aka struct ssl_session_st}’
   ciphers = session->ciphers;
                    ^
src/lib/tls/tortls_openssl.c: At top level:
src/lib/tls/tortls_openssl.c:1577:1: error: conflicting types for ‘SSL_get_client_random’
 SSL_get_client_random(SSL *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2003:15: note: previous declaration of ‘SSL_get_client_random’ was here
 __owur size_t SSL_get_client_random(const SSL *ssl, unsigned char *out,
               ^
In file included from ./src/lib/crypt_ops/crypto_rand.h:16:0,
                 from src/lib/tls/tortls_openssl.c:31:
src/lib/tls/tortls_openssl.c: In function ‘SSL_get_client_random’:
src/lib/tls/tortls_openssl.c:1582:15: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
   tor_assert(s->s3);
               ^
./src/lib/cc/compat_compiler.h:141:49: note: in definition of macro ‘PREDICT_LIKELY’
 #define PREDICT_LIKELY(exp) __builtin_expect(!!(exp), 1)
                                                 ^
./src/lib/log/util_bug.h:99:7: note: in expansion of macro ‘ASSERT_PREDICT_LIKELY_’
   if (ASSERT_PREDICT_LIKELY_(expr)) {                                   \
       ^
src/lib/tls/tortls_openssl.c:1582:3: note: in expansion of macro ‘tor_assert’
   tor_assert(s->s3);
   ^
src/lib/tls/tortls_openssl.c: At top level:
src/lib/tls/tortls_openssl.c:1590:1: error: conflicting types for ‘SSL_get_server_random’
 SSL_get_server_random(SSL *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2005:15: note: previous declaration of ‘SSL_get_server_random’ was here
 __owur size_t SSL_get_server_random(const SSL *ssl, unsigned char *out,
               ^
src/lib/tls/tortls_openssl.c:1603:1: error: conflicting types for ‘SSL_SESSION_get_master_key’
 SSL_SESSION_get_master_key(SSL_SESSION *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2007:15: note: previous declaration of ‘SSL_SESSION_get_master_key’ was here
 __owur size_t SSL_SESSION_get_master_key(const SSL_SESSION *sess,
               ^
Makefile:13764: recipe for target 'src/lib/tls/src_lib_libtor_tls_a-tortls_openssl.o' failed
make[2]: *** [src/lib/tls/src_lib_libtor_tls_a-tortls_openssl.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/home/coinz/verge-5.1.2Stealth/src/tor'
Makefile:5001: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/coinz/verge-5.1.2Stealth/src/tor'
Makefile:784: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

Let me know how to rectify?  OpenSSL version is 1.1.1b installed.

Thanks.

**Comment by justinvforvendetta** [comment]
yeah I believe tor has some issues with 1.1.1, we can leave this open for now

**Comment by cod3gen** [comment]
You could maybe try to install dependencies and use them.. Not sure how it affects tor dependencies

```
cd depends
make
cd ..
./autogen.sh && ./configure --prefix=VERGEDIR/depends/x86_64-pc-linux-gnu/ --disable-bench && make
```

**Comment by justinvforvendetta** [comment]
@cod3gen i think the issue here is he is using bleeding edge openssl, and tor just cant compile with it

@Romeo01234 can you try updating to 1.1.1c and let us know if the problem still occurs? 

(also run a make clean before making again, thanks!)

**Comment by Romeo01234** [comment]
Im in the process of compiling now. Will send another post on result.
Busy with work.

**Comment by Romeo01234** [comment]
Hello Justin, results below. Still fails with new openssl version 1.1.1c

Making all in src/tor
make[1]: Entering directory '/home/coinz/verge-5.1.2Stealth/src/tor'
make  all-am
make[2]: Entering directory '/home/coinz/verge-5.1.2Stealth/src/tor'
  CC       src/lib/tls/src_lib_libtor_tls_a-tortls_openssl.o
  CC       src/lib/tls/src_lib_libtor_tls_a-x509_openssl.o
  CC       src/lib/tls/src_lib_libtor_tls_testing_a-buffers_tls.o
  CC       src/lib/tls/src_lib_libtor_tls_testing_a-tortls.o
  CC       src/lib/tls/src_lib_libtor_tls_testing_a-x509.o
In file included from src/lib/tls/tortls_openssl.c:61:0:
./src/lib/tls/tortls_internal.h:48:8: error: conflicting types for ‘SSL_SESSION_get_master_key’
 size_t SSL_SESSION_get_master_key(struct ssl_session_st *s,
        ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2007:15: note: previous declaration of ‘SSL_SESSION_get_master_key’ was here
 __owur size_t SSL_SESSION_get_master_key(const SSL_SESSION *sess,
               ^
  CC       src/lib/tls/src_lib_libtor_tls_testing_a-tortls_openssl.o
src/lib/tls/tortls_openssl.c: In function ‘tor_tls_client_is_using_v2_ciphers’:
src/lib/tls/tortls_openssl.c:929:20: error: dereferencing pointer to incomplete type ‘SSL_SESSION {aka struct ssl_session_st}’
   ciphers = session->ciphers;
                    ^
src/lib/tls/tortls_openssl.c: At top level:
src/lib/tls/tortls_openssl.c:1577:1: error: conflicting types for ‘SSL_get_client_random’
 SSL_get_client_random(SSL *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2003:15: note: previous declaration of ‘SSL_get_client_random’ was here
 __owur size_t SSL_get_client_random(const SSL *ssl, unsigned char *out,
               ^
In file included from ./src/lib/crypt_ops/crypto_rand.h:16:0,
                 from src/lib/tls/tortls_openssl.c:31:
src/lib/tls/tortls_openssl.c: In function ‘SSL_get_client_random’:
src/lib/tls/tortls_openssl.c:1582:15: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
   tor_assert(s->s3);
               ^
./src/lib/cc/compat_compiler.h:141:49: note: in definition of macro ‘PREDICT_LIKELY’
 #define PREDICT_LIKELY(exp) __builtin_expect(!!(exp), 1)
                                                 ^
./src/lib/log/util_bug.h:99:7: note: in expansion of macro ‘ASSERT_PREDICT_LIKELY_’
   if (ASSERT_PREDICT_LIKELY_(expr)) {                                   \
       ^
src/lib/tls/tortls_openssl.c:1582:3: note: in expansion of macro ‘tor_assert’
   tor_assert(s->s3);
   ^
src/lib/tls/tortls_openssl.c: At top level:
src/lib/tls/tortls_openssl.c:1590:1: error: conflicting types for ‘SSL_get_server_random’
 SSL_get_server_random(SSL *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2005:15: note: previous declaration of ‘SSL_get_server_random’ was here
 __owur size_t SSL_get_server_random(const SSL *ssl, unsigned char *out,
               ^
src/lib/tls/tortls_openssl.c:1603:1: error: conflicting types for ‘SSL_SESSION_get_master_key’
 SSL_SESSION_get_master_key(SSL_SESSION *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2007:15: note: previous declaration of ‘SSL_SESSION_get_master_key’ was here
 __owur size_t SSL_SESSION_get_master_key(const SSL_SESSION *sess,
               ^
Makefile:13764: recipe for target 'src/lib/tls/src_lib_libtor_tls_a-tortls_openssl.o' failed
make[2]: *** [src/lib/tls/src_lib_libtor_tls_a-tortls_openssl.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from src/lib/tls/tortls_openssl.c:61:0:
./src/lib/tls/tortls_internal.h:48:8: error: conflicting types for ‘SSL_SESSION_get_master_key’
 size_t SSL_SESSION_get_master_key(struct ssl_session_st *s,
        ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2007:15: note: previous declaration of ‘SSL_SESSION_get_master_key’ was here
 __owur size_t SSL_SESSION_get_master_key(const SSL_SESSION *sess,
               ^
src/lib/tls/tortls_openssl.c: In function ‘tor_tls_client_is_using_v2_ciphers’:
src/lib/tls/tortls_openssl.c:929:20: error: dereferencing pointer to incomplete type ‘SSL_SESSION {aka struct ssl_session_st}’
   ciphers = session->ciphers;
                    ^
src/lib/tls/tortls_openssl.c: At top level:
src/lib/tls/tortls_openssl.c:1577:1: error: conflicting types for ‘SSL_get_client_random’
 SSL_get_client_random(SSL *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2003:15: note: previous declaration of ‘SSL_get_client_random’ was here
 __owur size_t SSL_get_client_random(const SSL *ssl, unsigned char *out,
               ^
In file included from src/lib/tls/tortls_openssl.c:63:0:
src/lib/tls/tortls_openssl.c: In function ‘SSL_get_client_random’:
src/lib/tls/tortls_openssl.c:1582:15: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
   tor_assert(s->s3);
               ^
./src/lib/log/util_bug.h:76:9: note: in definition of macro ‘ASSERT_PREDICT_UNLIKELY_’
     if (e)                                      \
         ^
./src/lib/log/util_bug.h:99:7: note: in expansion of macro ‘ASSERT_PREDICT_LIKELY_’
   if (ASSERT_PREDICT_LIKELY_(expr)) {                                   \
       ^
src/lib/tls/tortls_openssl.c:1582:3: note: in expansion of macro ‘tor_assert’
   tor_assert(s->s3);
   ^
src/lib/tls/tortls_openssl.c: At top level:
src/lib/tls/tortls_openssl.c:1590:1: error: conflicting types for ‘SSL_get_server_random’
 SSL_get_server_random(SSL *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2005:15: note: previous declaration of ‘SSL_get_server_random’ was here
 __owur size_t SSL_get_server_random(const SSL *ssl, unsigned char *out,
               ^
src/lib/tls/tortls_openssl.c:1603:1: error: conflicting types for ‘SSL_SESSION_get_master_key’
 SSL_SESSION_get_master_key(SSL_SESSION *s, uint8_t *out, size_t len)
 ^
In file included from src/lib/tls/tortls_openssl.c:48:0:
/usr/local/include/openssl/ssl.h:2007:15: note: previous declaration of ‘SSL_SESSION_get_master_key’ was here
 __owur size_t SSL_SESSION_get_master_key(const SSL_SESSION *sess,
               ^
Makefile:13652: recipe for target 'src/lib/tls/src_lib_libtor_tls_testing_a-tortls_openssl.o' failed
make[2]: *** [src/lib/tls/src_lib_libtor_tls_testing_a-tortls_openssl.o] Error 1
make[2]: Leaving directory '/home/coinz/verge-5.1.2Stealth/src/tor'
Makefile:5001: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/coinz/verge-5.1.2Stealth/src/tor'
Makefile:784: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1



Hope this result can assist in fixing code.

Regards,
Romeo01234

**Comment by Romeo01234** [comment]
This is strange because I am running a TOR access point on a raspberry pi with openssl version 1.1.1b.
Just to let you know it isn't the current openssl version.

Hope this extra info helps with your bug issue.

**Comment by justinvforvendetta** [comment]
@Romeo01234 you are running tor access point on a raspi, that you compiled? or a binary? if its a binary, it isnt using the openssl version you have on your machine, its using the one it was compiled with

**Comment by Romeo01234** [comment]
I compiled the openssl-1.1.1c.tar.gz just now on the RaspPi. It was not a pre-compiled ".deb" binary.
Just tested access point. works.
Everything is the same as previous post, except now running openssl-1.1.1c on it.

Hope this new info helps your bug issue.

**Comment by paradoxicalNL** [comment]
I stumbled upon this earlier; https://patchwork.ozlabs.org/patch/1039250/
Instead downloaded pre-compiled binary's, but maybe it can help you.

**Comment by Romeo01234** [comment]
I should also mentioned I also use the same RasPi as an VPN portal to connect to my home. Using OpenVPN.

Wireless Tor Access Point at home and OpenVPN portal to connect from the other wireless access points.
This is off topic. Anyway. Hope My posts and others on this thread offer you a solution to the VERGE wallet tor bug.

**Comment by marpme** [comment]
Duplication of #987
