### ISSUE TITLE
win wallet slow to load

### ISSUE THREAD

**Issue by CryptoKaku** [vergecurrency/VERGE#92]
Greetings.

I finally had an opportunity to install the Windows wallet to see how it runs and thought I'd post my experience:

1. I first confirmed the wallet completed the blockchain sync.
2. I then sent XVG to it as a test. 
3. I saw I still had a 0 balance so I restarted it. 
4. Post restart, it seems to get stuck on the Wraith splash screen for about 8 minutes.
5. Once it finally launched I confirmed receipt of my initial test.

Thanks and awesome work! I can't wait to see what's in store for XVG over the next couple of months.

~ CK

**Comment by Technophant** [comment]
Having an animated gif would be nice along with a message that it will take a while. I found a gif of a green V that fills up slowly and it could be adapted.
