### ISSUE TITLE
getblocktemplate - algo based

### ISSUE THREAD

**Issue by cod3gen** [vergecurrency/VERGE#920]
# Issue Template

## Context

Since XVG and some other multialgo coins have started to support getblocktemplate by algo, I have been preparing my mining pool to handle only one daemon for all algorithms, instead of todays solution of one daemon each algo.

During first test run mining on XVG scrypt, through a x17 daemon (`getblocktemplate '{"algo":"scrypt"}'`) i got only rejected block with this error; `ERROR: ProcessNewBlock: AcceptBlock FAILED (bad-diffbits, incorrect proof of work (code 16))`. From this error it was logical that something was wrong with getblocktemplate, so i run a comparation:

![xvg_compare](https://user-images.githubusercontent.com/14929298/58433901-61d27b80-80b9-11e9-95a7-4e29e3fc1ee8.png)

Not all fields are matched based on algo here. "version" is changed as its supposed too, however longpollid, target and bits are incorrect.

## Prerequisites

Latest master from github, Ubuntu 18.04

## User Story:

* "I'm submitting a ... "
  - [X] bug report

**Comment by marpme** [comment]
I've unified the way you can create block templates, as it rather seems to be the case that you had the same also version although the block was initially created for scrypt.

So when you don't set anything it will fallback to `scrypt`, if set in verge.conf then it takes this one.
And finally, if you want to overwrite it via the getblocktemplate params then this will be used. 

`getblocktemplate` params > `setalgo` > verge.conf

You may want to try it via https://github.com/vergecurrency/VERGE/tree/bugfix-blocktemplate-creation-for-different-algos and leave some feedback if this is working in regards to the bits etc.

**Comment by cod3gen** [comment]
hi @marpme!

This partially works, we are getting there :-D  I'm still processing tests on a x17 daemon;
After starting daemon i run getblocktemplate '{"algo":"scrypt"}':
```
"version": 2052
"longpollid": "331f10f9a1f787f7192a3cfea60f10bc28e320d3ba61c82d2d4cd2fbc4fec2dc9",
  "target": "0000000000022ca5000000000000000000000000000000000000000000000000",
"bits": "1b022ca5",
  "height": 3164512
```

Which is or at least seems to be correct, however if i submit a different algo, say blake before new TX have been added/appended on network, i still get blocktemplate for scrypt, and then on next block i get blake. Seems like there is some caching involved that does not care about which algo have been requested: 

```
getblocktemplate '{"algo":"scrypt"}'
{
  "version": 2052,
  "coinbasevalue": 730000000,
  "longpollid": "106118ca0c7a3f55cf98f56ec63a12e2dda701d4816b79f368353b2fcd662b5e20",
  "target": "0000000000022ca5000000000000000000000000000000000000000000000000",
  "mintime": 1559067845,
  "noncerange": "00000000ffffffff",
  "curtime": 1559067845,
  "bits": "1b022ca5",
  "height": 3164516
}

getblocktemplate '{"algo":"blake"}'
{
  "version": 2052,
  "coinbasevalue": 730000000,
  "longpollid": "106118ca0c7a3f55cf98f56ec63a12e2dda701d4816b79f368353b2fcd662b5e20",
  "target": "0000000000022ca5000000000000000000000000000000000000000000000000",
  "mintime": 1559067845,
  "noncerange": "00000000ffffffff",
  "curtime": 1559067845,
  "bits": "1b022ca5",
  "height": 3164516
}

getblocktemplate '{"algo":"blake"}' (!! At this time, there have been added 1 TX to the template)
{
  "version": 8196,
  "coinbasevalue": 730100000,
  "longpollid": "106118ca0c7a3f55cf98f56ec63a12e2dda701d4816b79f368353b2fcd662b5e21",
  "target": "0000000000000090f30000000000000000000000000000000000000000000000",
  "mintime": 1559067845,
  "noncerange": "00000000ffffffff",
  "curtime": 1559067845,
  "bits": "1a0090f3",
  "height": 3164516
}

```

"curtime" is also cached it seems, and cache of this is between blocks and not depending on txs, this field should be updated on every request according to documentation; (numeric) current timestamp in seconds since epoch (Jan 1 1970 GMT). This field is also in use on stratums, but probably have not been an issue due to short time between blocks on XVG

**Comment by marpme** [comment]
@cod3gen I'm still not able to reproduce this behaviour
Could you please checkout the following branch: `bugfix-fork-inconsistencies` and check if you still be able to reproduce this behaviour. For me the curtime is change constantly (with each second) and the version number keeps being the same with the same parameter.
