### ISSUE TITLE
undefined reference to `boost::this_thread::hidden::sleep_for(timespec const&)'

### ISSUE THREAD

**Issue by finexbit** [vergecurrency/VERGE#924]
CXXLD    verged
libverge_util.a(libverge_util_a-time.o): In function `boost::this_thread::sleep_for(boost::chrono::duration<long, boost::ratio<1l, 1000000000l> > const&)':
/usr/local/include/boost/thread/pthread/thread_data.hpp:252: undefined reference to `boost::this_thread::hidden::sleep_for(timespec const&)'
collect2: error: ld returned 1 exit status
Makefile:4428: recipe for target 'verged' failed
make[2]: *** [verged] Error 1
make[2]: Leaving directory '/alidata/VERGE/src'
Makefile:10919: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/alidata/VERGE/src'
Makefile:784: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

**Comment by justinvforvendetta** [comment]
@finexbit can you give us some more insight? what distribution are you using? what version of boost? 

thanks

**Comment by justinvforvendetta** [comment]
@finexbit let us know if this is still a problem on your machine, and post more information if it happens again. we are all unable to reproduce this issue on mac or linux. we'd need to know more info about what boost version you have and such. 

thanks
