### ISSUE TITLE
Unable to send transactions 5.1.2

### ISSUE THREAD

**Issue by nefroti** [vergecurrency/VERGE#939]
Hi, I've been trying to send transaction to exchange through out all day, none of them went out from the wallet...
I am using 5.1.2 version for PC Windows
To sync the wallet I downloaded the blockchain for 5+ version, and added nodes for connections, maybe there is a problem?

My wallet is fully synced + connected to 10+ peers
However, the transactions is unconfirmed and can't find it on blockchain...

My wallet is encrypted and locked, I got the passphrase, because its locked it may not work properly? If yes how to unlock the wallet ? 

![c0e327d700fca9e24594cd13001a38ca](https://user-images.githubusercontent.com/35645141/58988985-d359aa80-87da-11e9-8929-8ec9c69b4f37.png)

**Comment by nefroti** [comment]
I unlocked the wallet via command but shit is the the same... I am slowly give up on this really
![1951e21b729eb9c088f2e30af475d9ea](https://user-images.githubusercontent.com/35645141/59030739-b617f100-8859-11e9-9b5c-f4070ddfbaab.png)
![36284b91ae4151306d397dc01af00924](https://user-images.githubusercontent.com/35645141/59030746-b912e180-8859-11e9-9cf3-3e4c93e1c70b.png)

**Comment by marpme** [comment]
one issue is enough :)
