### ISSUE TITLE
Lack behind of new blocks [v5 <-> v4]

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#940]
With above commit version, following errors, also causing delay in blockchain sync in 2-5sec. Like XVG versions 4 XVG already 5 blocks ahead than 5th version, when below error occur in debug.log

2019-06-08T06:27:42Z ERROR: ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0)
2019-06-08T06:27:47Z ERROR: ReadBlockFromDisk: OpenBlockFile failed for FlatFilePos(nFile=-1, nPos=0)

Reported by @pinpins

**Comment by marpme** [comment]
@pinpins I couldn't reproduce that behaviour at all.
A short log from a custom script checking the block count (mine vs peers)

```
[1560058686598] Highest: 3193994, Ours: 3193994 - difference 0 Block(s)
[1560058716584] Highest: 3193996, Ours: 3193996 - difference 0 Block(s)
[1560058746586] Highest: 3193997, Ours: 3193997 - difference 0 Block(s)
[1560058776587] Highest: 3193997, Ours: 3193997 - difference 0 Block(s)
[1560058806592] Highest: 3193998, Ours: 3193998 - difference 0 Block(s)
[1560058836593] Highest: 3193999, Ours: 3193999 - difference 0 Block(s)
[1560058866598] Highest: 3194000, Ours: 3194000 - difference 0 Block(s)
[1560058896601] Highest: 3194000, Ours: 3194000 - difference 0 Block(s)
[1560058926605] Highest: 3194002, Ours: 3194002 - difference 0 Block(s)
[1560058956611] Highest: 3194002, Ours: 3194002 - difference 0 Block(s)
[1560058986617] Highest: 3194003, Ours: 3194003 - difference 0 Block(s)
[1560059016613] Highest: 3194003, Ours: 3194003 - difference 0 Block(s)
```

And my peer info:

```
[
  {
    "id": 63,
    "addr": "149.56.182.120:21102",
    "addrlocal": "95.91.209.14:62321",
    "addrbind": "192.168.0.24:64961",
    "services": "0000000000000003",
    "relaytxes": true,
    "lastsend": 1560059107,
    "lastrecv": 1560059118,
    "bytessent": 44587,
    "bytesrecv": 370329,
    "conntime": 1560058232,
    "timeoffset": -18,
    "pingtime": 0.307106,
    "minping": 0.24893,
    "version": 90001,
    "subver": "/VVraith:4.0.2/",
    "inbound": false,
    "addnode": true,
    "startingheight": 3193982,
    "banscore": 0,
    "synced_headers": 3194007,
    "synced_blocks": 3194007,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 55,
      "getaddr": 24,
      "getdata": 15929,
      "getheaders": 26808,
      "inv": 122,
      "ping": 224,
      "reject": 1270,
      "verack": 24,
      "version": 131
    },
    "bytesrecv_per_msg": {
      "addr": 75081,
      "block": 267227,
      "getblocks": 2234,
      "headers": 5848,
      "inv": 2060,
      "notfound": 1141,
      "pong": 224,
      "tx": 16358,
      "verack": 24,
      "version": 132
    }
  },
  {
    "id": 66,
    "addr": "176.9.25.79:21102",
    "addrlocal": "95.91.209.14:53832",
    "addrbind": "192.168.0.24:65024",
    "services": "0000000000000407",
    "relaytxes": true,
    "lastsend": 1560059103,
    "lastrecv": 1560059111,
    "bytessent": 3978,
    "bytesrecv": 13143,
    "conntime": 1560058617,
    "timeoffset": -4,
    "pingtime": 0.026616,
    "minping": 0.026616,
    "version": 90007,
    "subver": "/verge:5.1.0/",
    "inbound": false,
    "addnode": true,
    "startingheight": 3193992,
    "banscore": 0,
    "synced_headers": 3194007,
    "synced_blocks": 3194007,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 80,
      "block": 720,
      "feefilter": 32,
      "getaddr": 24,
      "getdata": 194,
      "getheaders": 1117,
      "headers": 1152,
      "inv": 61,
      "ping": 160,
      "pong": 160,
      "sendcmpct": 99,
      "sendheaders": 24,
      "verack": 24,
      "version": 131
    },
    "bytesrecv_per_msg": {
      "addr": 7035,
      "block": 1924,
      "cmpctblock": 1608,
      "feefilter": 32,
      "getdata": 122,
      "getheaders": 1117,
      "headers": 674,
      "ping": 160,
      "pong": 160,
      "sendcmpct": 132,
      "sendheaders": 24,
      "verack": 24,
      "version": 131
    }
  },
  {
    "id": 77,
    "addr": "207.180.208.204:21102",
    "addrlocal": "95.91.209.14:62295",
    "addrbind": "192.168.0.24:65181",
    "services": "0000000000000003",
    "relaytxes": true,
    "lastsend": 1560059111,
    "lastrecv": 1560059039,
    "bytessent": 1842,
    "bytesrecv": 532,
    "conntime": 1560058847,
    "timeoffset": -10,
    "pingtime": 30.130352,
    "minping": 30.130352,
    "version": 90001,
    "subver": "/VVraith:4.0.2/",
    "inbound": false,
    "addnode": true,
    "startingheight": 3193995,
    "banscore": 0,
    "synced_headers": 3194000,
    "synced_blocks": -1,
    "inflight": [
    ],
    "whitelisted": false,
    "bytessent_per_msg": {
      "addr": 55,
      "getaddr": 24,
      "getheaders": 1117,
      "inv": 427,
      "ping": 64,
      "verack": 24,
      "version": 131
    },
    "bytesrecv_per_msg": {
      "headers": 107,
      "inv": 205,
      "pong": 64,
      "verack": 24,
      "version": 132
    }
  }
]
```

**Comment by pinpins** [comment]
I was running both v4 and v5 on the same internet IP. Just checking using getinfo time to time, easy to catch v5 lagging behind

**Comment by cod3gen** [comment]
Was not aware of this, @pinpins - I see this behavior too!

http://prntscr.com/nzlhl4

**Comment by cod3gen** [comment]
However, i do not see any ReadBlockFromDisk errors in my log.. Only node disconnections.

**Comment by marpme** [comment]
I see that there are blockheader "rejections" due to "blk-time-too-new" maybe that could be the cause that it rejects the "too new" blocks.

**Comment by tpfuemp** [comment]
it seems to have something to do, how the client resolve block-collisions
watch the TipUpdates in log:
[debug.log](https://github.com/vergecurrency/VERGE/files/3269879/debug.log)
3195390 - hash:0000000000015c1bac016ed302764a20ae2407f7b2f6cfcfc2d3642782d95447
3195391 - hash:000000000000a54e89668972cfa7b847fc8d99a7daa3f02498383fcf47f941a7
3195392 - hash:00000000000236562bf67cb80fdd572733834f73881c76f45573f1bcf368b701
then again 
3195391 - hash:000000000000a54e89668972cfa7b847fc8d99a7daa3f02498383fcf47f941a7
3195390 - hash:0000000000015c1bac016ed302764a20ae2407f7b2f6cfcfc2d3642782d95447
the with other hash
3195391 - hash:7bc52fc3a416611db6eaad536ae03a6f31876481a3a82a236ed257c2fe7f3e49
then the communication got stuck until timeout and disconnect of offending node

**Comment by marpme** [comment]
That's what I see here @tpfuemp 

```
1eb0787 height=3195389 version=0x00002004 last known
2d95447 height=3195390 version=0x00000804 << scrypt
7f941a7 height=3195391 version=0x00000804 xx scrypt
...
2d95447 height=3195390 version=0x00000804 << probably an inflight block
e7f3e49 height=3195391 version=0x00001804 xx collision -> scrpyt versus x17
...
2d95447 height=3195390 version=0x00000804 << scrypt
7f941a7 height=3195391 version=0x00000804 xx collision -> x17 versus scrypt
```

**Comment by tpfuemp** [comment]
ok, after doing some more test a can see, that this is only a symptom , not the real reason.

in v5 must be something wrong with connection handling on non-tor nodes.

I started with 9 active connections (added via addnode), after 30 minutes it dropped to 1!
even my own other 3 nodes (v4 clearnet) have been kicked

**Comment by pinpins** [comment]
@tpfuemp Yes, I can only confirm this behavior, for pool it means we bravely mine on blockchain behind(v5), and all those found blocks  appear to be rejected in a while obivously.

**Comment by tpfuemp** [comment]
doing again more test some more facts and a warning: **do not use v5 mining**! - in simple case only orphan blocks, in worst case blockchain can be damaged by chainsplit between v4 and v5.

there is a serious incompatibility between v4 and v5 related to how chain reorgs been done. all v5 client behave the same, it doesn't matter how they are connect.
I have running 5 fullnodes: 2x v4 clearnet , 3x v5 - 1 all networks (tor, ipv4, ipv6), 1 tor+ipv4, 1 only ipv4

see picture, that all v5 stuck on same height

![XVG-problem](https://user-images.githubusercontent.com/26894102/59568910-44724b00-9082-11e9-8413-6eed12fb9dd2.png)

chaintips info shows me, that the node knows about the other blocks but do not change active chain like v4 nodes do.

![XVG-chaintips](https://user-images.githubusercontent.com/26894102/59568917-59e77500-9082-11e9-947d-a6f3108edcca.png)

after about 20 minutes the reorg triggers until the problem occurs again

**Comment by tpfuemp** [comment]
@marpme the errors about blockheader "rejections" due to "blk-time-too-new" is an other logic bug, which leads to delay in accepting blocks, but not the stale chain.

it only occurs if connected to tor.
if new node connects, there is a timeoffset calculated and added to the **local** timeoffset.
which is wrong, my local offset should always be zero and on clearnet it is 0.

temp. disabled timeoffset -> blocks accepted in tor like clearnet
```
diff --git a/src/net_processing.cpp b/src/net_processing.cpp
index eed2e046..1e58e681 100644
--- a/src/net_processing.cpp
+++ b/src/net_processing.cpp
@@ -1805,7 +1805,7 @@ bool static ProcessMessage(CNode* pfrom, const std::string& strCommand, CDataStr

         int64_t nTimeOffset = nTime - GetTime();
         pfrom->nTimeOffset = nTimeOffset;
-        AddTimeData(pfrom->addr, nTimeOffset);
+        //AddTimeData(pfrom->addr, nTimeOffset);

         // If the peer is old enough to have the old alert system, send it the final alert.
         if (pfrom->nVersion <= 70012) {

```

**Comment by marpme** [comment]
I think regarding the unintentional chainsplit, it could be related to that logic over here

https://github.com/vergecurrency/VERGE/blob/603654beef9b60823d0aa30481de25448a0c5e43/src/validation.cpp#L2578

Can't do much atm rather than saying go for mining @ v4 but that was clear as it isn't stable enough for mining as of now

**Comment by pinpins** [comment]
Problem is that blockchain size and the way v4 daemon is designed making also v4 more and more difficuly and heavy to operate, RPC calls getting timeouts occasionally there too. From this perspective v5 is good aid to situation, but you need to fix sync issues.

**Comment by Ur-Quan** [comment]
In times of war I'd consider increasing MAX_OUTBOUND_CONNECTIONS in net.cpp manually.

**Comment by tpfuemp** [comment]
simply increasing connections won't fit, as the old v4 clients are constantly dropping connections to v5 clients, so after some hours you will only have v5 clients left in connection list. there must be some incompatibility in communication between v4 and v5, so old wallet is tagging new wallet as malicious.

**Comment by justinvforvendetta** [comment]
my v5 has mostly v3 peers

**Comment by marpme** [comment]
Had yet again a look into the blockchain data and as it seems the v4 node does the same as the v5 node. 

```
2019-06-22T12:22:08Z UpdateTip: new best=f5936be64a725c4a0cd3589b08975dedea53c4ecacff6d0055b554ab70b5d48d height=3227819 version=0x00005004 log2_work=85.40751 tx=7305875 date='2019-06-22T12:21:04Z' progress=0.999991 cache=0.0MiB(91txo)
2019-06-22T12:22:20Z UpdateTip: new best=db90c87d6dfda93679c7153be6c9f762ea148cd3285f25239e765fd37ca35ce8 height=3227820 version=0x00005004 log2_work=85.407514 tx=7305876 date='2019-06-22T12:21:33Z' progress=0.999994 cache=0.0MiB(92txo)
2019-06-22T12:23:02Z UpdateTip: new best=f5936be64a725c4a0cd3589b08975dedea53c4ecacff6d0055b554ab70b5d48d height=3227819 version=0x00005004 log2_work=85.40751 tx=7305875 date='2019-06-22T12:21:04Z' progress=0.999984 cache=0.0MiB(93txo)
2019-06-22T12:23:02Z UpdateTip: new best=d94c2bb093cae58fa11bb785c360b99862cd46d67591bf38cab7532fe98ad286 height=3227820 version=0x00005004 log2_work=85.407514 tx=7305876 date='2019-06-22T12:22:10Z' progress=0.999993 cache=0.0MiB(94txo)
2019-06-22T12:23:02Z UpdateTip: new best=ef8ffcea3765f17079fa85e995f116db1a5e7bad7c0dbc8248e382418e4b913f height=3227821 version=0x00005004 log2_work=85.407517 tx=7305877 date='2019-06-22T12:22:21Z' progress=0.999994 cache=0.0MiB(95txo)
```

So it "re-orgs" to the longest most recent chain here and the same happens on a v4 according to the verge explorer.

https://verge-blockchain.info/block/db90c87d6dfda93679c7153be6c9f762ea148cd3285f25239e765fd37ca35ce8

https://verge-blockchain.info/block/d94c2bb093cae58fa11bb785c360b99862cd46d67591bf38cab7532fe98ad286

**Comment by marpme** [comment]
So the only problem is that we reject "too new" blocks, right?

**Comment by tpfuemp** [comment]
short: nothing changed, the problem still exists
long:
there are a couple of problems or logic changes, which leads to delay of chainsync between v4 and v5

the related problem to the named "too new" blocks I described 6 days ago. It only happens to tor-connected clients. the resulting delay is about 5 to 30 sec. , depends on the accumulated timeoffets of the connected clients. when only clearnet used, timeoffest is 0, the warning will not happen.

the bigger problem is the incompatibility of the reorg-code between v4 and v5.
you are right, the re-orgs are done on both versions, but on some circumstances with a delay of up to **20 min**. as all minnng nodes are currently running v4 , after some time the codeversion of v4 wins. if more v5 clients were mining, the chain will get in trouble.
after searching in source code, i found a difference in logic to explain the behavior.
v4 reorg-code depends simply on blockheight - the greater height wins, the node switchs to longer chain.
v5 reorg-code changed this to chainwork value!
on single algo coins this would nearly give the same result. on multi-algo coins the result differs as chainwork is derived from diffculty and nethash.
thats why the v5 node knows the longer chain from v4 nodes, but will not use it until the chainwork conditions match.
You should really adapt the v5 reorg part to the v4 behaviour!

the third problem is related to connectivity to v4 nodes. new clients are permantly dropped/banned from v4 nodes. sometimes there are only v5 nodes in connection list, but mining is done by v4 nodes only.
so sometimes a network-split occur. v4 nodes are going forward, v5 are locked out from active chain until one node get connection back.
I will do some more debugging on this issue later.

**Comment by Ur-Quan** [comment]
Make a v5 cleannet branch/release? Talk pool ops to upgrade?

**Comment by marpme** [comment]
_Here's an update on the current situation:_ I've been following along the current situation and checked the problems you mentioned @tpfuemp. I think I kinda got the idea what was the problem here. Could you just make sure that this solution is working for you, I've had no problems with it so far.

https://github.com/vergecurrency/VERGE/tree/bugfix-fork-inconsistencies

Thank you in advance

**Comment by marpme** [comment]
So I monitored the entire situation a bit more and I can definitely see that a lot of new valid forks are being created but meanwhile this happens we always stay with highest chain as the active one. So definitely switched a way from monitoring the most work here instead we use the nHeight for comparing blocks for preciousness.

**Comment by tpfuemp** [comment]
the good news first:
- blk-to-new messages are gone
- fee-rate bugfix helps to prevent create malformed transactions - after cleaning mempool wrong tx's do not reappear

the bad-news:
the sync-problem still exist - i think it got better, but it still happens

first we should keep an eye on the communication problem between client versions. maybe this interfere the syncing. on v5 clients I get only stable connections to v5 clients - v4 clients keep on dropping/banning.
you should also release a new version with version number increased, so we can differentiate fixed clients from unfixed - if node is connected only to v5 pre-fixed, the sync will not be done correctly.

**Comment by tpfuemp** [comment]
some pictures to illustrate:

block-height on v4 vs v5

![XVG1](https://user-images.githubusercontent.com/26894102/60432401-7519bf00-9c02-11e9-9d8e-c3cd156da960.png)

chaintips-info on v5-node

![XVG2](https://user-images.githubusercontent.com/26894102/60432438-9084ca00-9c02-11e9-8eb9-f0a4b2130a48.png)

connectionlist on v5-node (my own v4 nodes are in addnode-section, but connections are not stable)

![XVG3](https://user-images.githubusercontent.com/26894102/60432499-be6a0e80-9c02-11e9-80ef-1ff67abbb0dc.png)

**Comment by marpme** [comment]
Okay will have a further look into the communication of the two node version (v4 and v5) and will try to figure out how it could happen that there's such a huge difference. There must be big differences while syncing so blocks are rejected. As it seems to me that the "highest" chain for the v5 is the valid one. But I guess it just doesn't know the others. 

One question tho is there anyone mining onto the V5 nodes as it could have an impact, if new blocks are being release on the block chain via V5 maybe they "divide" into two chains cause the created blocks aren't accepted by the v4 network. 

Just a wild guess: maybe there's a difference in signing the block or whatever, but as far as I can recall everything went well in a local setup with a v4 and v5 node where I mined on both. And both silently accepted the blocks without any trouble.

**Comment by tpfuemp** [comment]
I think you are guessing right - from log of v4 - node against v5 node (latest version 5.2.0.1)

received: block (236 bytes)
received block 89772d60c57357f8116e
ERROR: CheckBlock() : bad block signature
ERROR: ProcessBlock() : CheckBlock FAILED
Misbehaving: 188.40.78.31:50970 (0 -> 100) DISCONNECTING

**Comment by marpme** [comment]
@tpfuemp I had a look into the code and it seems like there's no issue so far, *but* one of the coinbase transaction outputs *MUST* include a pubkey as their script for being able to sign this very block. May you can check your mining scripts for that?

V5 is conceptionally build to already ignore and swallow the block signature as we want to have to most clean PoW approach possible.

Thus this signature has no real use within the case of verge as it would be required for using POS, but as v4 has a block check which includes the signature then we have to provide it, otherwise, we would need a hard/softfork for this.

**Comment by tpfuemp** [comment]
I'm currently do not mine with v5 node. The incriminating block is relayed from other node, so I have no control over this.

**Comment by marpme** [comment]
Do you have somehow access to the block that he tries to send to you?

Acutally it should be known to your V5 nodes and I think I have to reintroduce the block check again for "wrongly" signed blocks :^( Otherwise all v5's are just blocked off because one broadcasted a "bad" block into the v5 network.

**Comment by tpfuemp** [comment]
here we go: log on v4 node:
`received: block (264 bytes)
received block d8018981fdfe6aaf5c93
ERROR: CheckBlock() : bad block signature
ERROR: ProcessBlock() : CheckBlock FAILED
Misbehaving: 188.40.78.31:44690 (0 -> 100) DISCONNECTING
disconnecting node 188.40.78.31:44690`

corresponding data from v5 node:
`2019-07-02T20:34:01Z received: getdata (73 bytes) peer=37
2019-07-02T20:34:01Z received getdata (2 invsz) peer=37
2019-07-02T20:34:01Z received getdata for: block d8018981fdfe6aaf5c935ae3e3d185e66b0a970c965df20f3dad7e1306d48e44 peer=37
2019-07-02T20:34:01Z sending block (264 bytes) peer=37
2019-07-02T20:34:01Z sending block (334 bytes) peer=37
2019-07-02T20:34:01Z socket closed
2019-07-02T20:34:01Z disconnecting peer=37`

blockdata with getblock "d8018981fdfe6aaf5c935ae3e3d185e66b0a970c965df20f3dad7e1306d48e44" true
`{
    "hash": "d8018981fdfe6aaf5c935ae3e3d185e66b0a970c965df20f3dad7e1306d48e44",
    "pow_hash": "0000000000015eac61c7677933ff268c9370ea2de0687cf01247aa95d85cbb91",
    "algo": "lyra2re",
    "confirmations": -1,
    "strippedsize": 264,
    "size": 264,
    "weight": 1056,
    "height": 3254334,
    "version": 20484,
    "versionHex": "00005004",
    "merkleroot": "dbc1297d1495caeda6e4283c21dc0228e65d8bd6490a7fa3194fa7ab8a7f64f6",
    "tx": [
        "dbc1297d1495caeda6e4283c21dc0228e65d8bd6490a7fa3194fa7ab8a7f64f6"
    ],
    "time": "2019-07-02 20:32:06 +0000",
    "mediantime": "2019-07-02 20:19:58 +0000",
    "nonce": 3140392199,
    "bits": "1b02079f",
    "difficulty": 32286.910985318,
    "chainwork": "0000000000000000000000000000000000000000002b35abb4d773fb6d0188af",
    "nTx": 1,
    "previousblockhash": "7308e2865f56c5b0e77b9cc571a4538a6544dce86700c37eaa426f6e92d0dd65"
}`

rawdata:
0450000065ddd0926e6f42aa7ec30067e8dc44658a53a471c59c7be7b0c5565f86e20873f6647f8aaba74f19a37f0a49d68b5de62802dc213c28e4a6edca95147d29c1db46bf1b5d9f07021b07952ebb010100000046bf1b5d010000000000000000000000000000000000000000000000000000000000000000ffffffff53033ea831062f503253482f046abf1b5d08fabe6d6dbfa6857f854a39ce229ba43e864f8826c34555d5f5339cca17fa55d08512f6140100000000000000780024de36f901000d2f6e6f64655374726174756d2f000000000180ea822b00000000232102d4473baeb75dccc8477abe84400860fca2b175a6c8fe6c83f156045f7eb6d512ac0000000000

**Comment by badbrainIRC** [comment]
why would you want block 5 compatible with block 4? update asap your wallets and thats it. Everyone on same page?

**Comment by marpme** [comment]
@badbrainIRC that would just split the network for no reason. It would just remove just the capability to remove the block signature. And that’s definitely not worth to risk a fork. IMO

**Comment by marpme** [comment]
@tpfuemp Pushed a commit with checking those blocks (for signatures again) and raised to version to 5.2.0.2 for comparability. **Now as this effects your current data structure (you received and stored blocks which shouldn't be in there) you might have to reindex or rebuild the structure.**

I'm currently running a sync progress with one of my nodes, I will let you know as soon as I got a real download for that (zip of blockchain) :)

**Comment by tpfuemp** [comment]
I think, we are on the right way, but the sig-check leads to new problems:

getblocktemplate is currently broken - new block has no valid signatures
-> returns always
error -1: createnewblock: testblockvalidity failed: bad-blk-signature, could not check the validity of the block signature (code 16)

once completed this must be a mandatory release - all current v5-node are permanently banned as they relay malformed blocks

**Comment by marpme** [comment]
Sure all v5 nodes needs to upgrade to v5.2.0.2 or higher in order to connect to the network again. It might be also necessary to reminded block remove some but well :/ 
But that should fix the communication issues with v5-v4 overall.

I gonna check the block template creation :/

**Comment by pinpins** [comment]
Any plans to rollout v5.2.0.2 somewhat soon?

**Comment by marpme** [comment]
@pinpins Well I’m mostly going to roll out the fee fix today, but the blockchain fix has to be verified to at least be working for one miner on mainnet. 

That will take until I have time again to look into the block signature again, quite busy the last days

**Comment by pinpins** [comment]
Okay, it just version v4 is very unstable for mining also, many orphans. And daemon very heavy. So really looking forward fixed v5 :) thanks

**Comment by marpme** [comment]
I will probably have a look into the getBlocktemplate stuff this evening, let’s see if it turns out to be easy but I couldn’t think of any difficulties

**Comment by marpme** [comment]
Updated the branch with ignoring checking block signatures when not necessary (i.e. while getting a blocktemplate) @tpfuemp

**Comment by tpfuemp** [comment]
there seems to be a bug/difference in signature validation between v4 and v5, so the client stuck sync
(logfile: 
[XVG-debug.log](https://github.com/vergecurrency/VERGE/files/3380755/XVG-debug.log)
)

problem occured on block 3275194 (6174c1c56eaf4d27716fbf068b7b646014bf28f1eddeaf3982f43c66aa69ea3f)
client switches between possible chains, but is unable to get back on right chain

![XVG-chaintip](https://user-images.githubusercontent.com/26894102/61031867-a479ba00-a3c0-11e9-8990-4f04dc494dd0.PNG)

**Comment by marpme** [comment]
Could it be that your block have invalid block stored, which the nodes still refers as valid ones? 
Maybe a fresh download of the block files would help you out there, as I can't reproduce that behaviour after syncing beyond this point. Thank you for the support 👍

**Comment by tpfuemp** [comment]
no, without fresh sync client won't start.

I did a complete fresh sync before and saved a snapshot on block 3256948 for faster testing.

2nd. try: client synced up to current height
3rd try: client stopped at 3259053

it depends not on a single block.
the differences between 2nd and 3rd try are the connected nodes - only v4 vs v5 (5.2) nodes involved.

maybe there is a check missing and broken block slip through

**Comment by marpme** [comment]
hmm weird, for me every single (unusable block) is being rejected immediately. V5 nodes were build to totally ignore the block signature anyways. So that we have a slightly chance to get rid of it soon. 

but now as we have added those checks again on the newest v5 the older v5 are sharing "bad" blocks with us. So that's why nearly all v5 are being banned atm.

**Comment by tpfuemp** [comment]
now i can see two different problems:
1. is "temporary" - if a v5 node is used to fetch new blocks, it can lead to an endless loop
(fetched blocks are invalid and not accepted, but node is not banned/disconnected correctly and will be used to fetch more data again). after client restart sync will continue

2. is more annoying:
on some conditions invalid block is silently accepted and written to disk. after that chain on disk is corrupted and client won't start anymore.


2019-07-13T23:45:20Z Loaded best chain: hashBestChain=7dd153e7283541af40fdf6fb5ece342092c885c379f623090586afdfa0c1ad50 height=3283012 date=2019-07-13T23:41:16Z progress=0.999967
2019-07-13T23:45:20Z init message: Rewinding blocks...
2019-07-13T23:45:32Z init message: Verifying blocks...
2019-07-13T23:45:32Z Verifying last 6 blocks at level 3
2019-07-13T23:45:32Z [0%]...Checking Block Signature: 1ERROR: VerifyDB: *** found bad block at 3283012, hash=7dd153e7283541af40fdf6fb5ece342092c885c379f623090586afdfa0c1ad50 (bad-blk-signature, Could not check the validity of the block signature (code 16))
2019-07-13T23:45:32Z : Corrupted block database detected. Please restart with -reindex or -reindex-chainstate to recover.
2019-07-13T23:45:32Z Aborted block database rebuild. Exiting.

**Comment by marpme** [comment]
@tpfuemp 

1. The first point might be valid in a case that you explicitly `addnode=YYY.XXX.ZZZ.VVV` or `connect=XXX.XXX.XXX.XXX`, then the node won't be banned even when it's sending you "bad"/invalid blocks. This is normal and should stay the way it is. So my wild guess that you exactly do this and end in this annoying loop. 

2. This is a **requirement** as we now require the block signatures to be there we have to force every V5 node to either resync or redownload a valid blockchain data from a verified source of truth, for that we could sync a node a prepare a zip for downloading the data with cleanup blocks.
Beforehand the node just accepted every block without even checking the block signature, but now we get to mining problems due to this, so we have to _"revert"_ the change anyway.

**Comment by marpme** [comment]
So the clear way to go here is to clean up all the checks, which we've done as of now.
And now we go for the hard upgrade, where everyone has to download the new version **and** also redownload the blocks otherwise, we'll probably struggle with this issue for even longer.

**Comment by marpme** [comment]
I'm also currently testing against a fresh V4 node starting at height: 3295000.

I'm forcing the V4 to only connect to the V5 (which has new checks) and the V5 is connected to more V4's and V5's fetching blocks and sending them to the new local V4. 

With this test, I want to make sure the new V5 rejects all invalid blocks and is able to sync the v4 until the very end.

**Comment by tpfuemp** [comment]
ok, didn't realized, that addnode prevents malfunction node from banning.
will do some more testing to see, if i could reproduce problem 2 (corrupted chain on disk)

**Comment by tpfuemp** [comment]
next problem: stuck on chain-reorg - client detects block 85290a1d5f5874141dc7994f6ce7cc7e7d21b1ea35610dbafd986934dafa19d6 as invalid, but it's valid on v4-node

2019-07-21T21:03:46Z UpdateTip: new best=ed4ea7cf76eb3da2b08ccecda633ffe36ff3e5cab965a130e5a347a8c497018b height=3303221 version=0x00002004 log2_work=85.478271 tx=7438012 date='2019-07-21T21:00:58Z' progress=0.999977 cache=0.8MiB(33txo)
2019-07-21T21:03:46Z ERROR: ConnectBlock: Consensus::CheckBlock: bad-blk-signature, Could not check the validity of the block signature (code 16)
2019-07-21T21:03:46Z InvalidChainFound: invalid block=85290a1d5f5874141dc7994f6ce7cc7e7d21b1ea35610dbafd986934dafa19d6  height=3303222  log2_work=85.478271  date=2019-07-21T21:01:48Z
2019-07-21T21:03:46Z InvalidChainFound:  current best=ed4ea7cf76eb3da2b08ccecda633ffe36ff3e5cab965a130e5a347a8c497018b  height=3303221  log2_work=85.478271  date=2019-07-21T21:00:58Z
2019-07-21T21:03:46Z ERROR: ConnectTip(): ConnectBlock 85290a1d5f5874141dc7994f6ce7cc7e7d21b1ea35610dbafd986934dafa19d6 failed
2019-07-21T21:03:46Z InvalidChainFound: invalid block=b4f51b8bf04b7a65bd11eb0f54218506fd0e75d426f10b58277e91e8c3f7bd12  height=3303223  log2_work=85.478271  date=2019-07-21T21:03:02Z
2019-07-21T21:03:46Z InvalidChainFound:  current best=ed4ea7cf76eb3da2b08ccecda633ffe36ff3e5cab965a130e5a347a8c497018b  height=3303221  log2_work=85.478271  date=2019-07-21T21:00:58Z
2019-07-21T21:03:46Z UpdateTip: new best=de40d4953720ffb0440b22853b70a77964130974aafe662e470ea057258546ed height=3303222 version=0x00001004 log2_work=85.478271 tx=7438014 date='2019-07-21T21:02:47Z' progress=0.999992 cache=0.8MiB(35txo)
2019-07-21T21:03:46Z ERROR: AcceptBlockHeader: block b4f51b8bf04b7a65bd11eb0f54218506fd0e75d426f10b58277e91e8c3f7bd12 is marked invalid
2019-07-21T21:04:13Z New outbound peer connected: version: 90001, blocks=3303223, peer=15
2019-07-21T21:04:13Z ERROR: AcceptBlockHeader: block b4f51b8bf04b7a65bd11eb0f54218506fd0e75d426f10b58277e91e8c3f7bd12 is marked invalid
2019-07-21T21:05:41Z ERROR: AcceptBlockHeader: prev block invalid
2019-07-21T21:05:42Z ERROR: AcceptBlockHeader: prev block invalid

**Comment by badbrainIRC** [comment]
scan your disk to see if the problem is your disk first.

**Comment by marpme** [comment]
@badbrainIRC that would be my best guess too since nothing has changed code wise. The problem might be your corrupt disk state

**Comment by tpfuemp** [comment]
no, definitively no disk problem.

happens on 2 different servers. other block, same behaviour - during chain reorg.

**Comment by marpme** [comment]
@tpfuemp As I understood the previous log, you received a block which is valid and stored inside a V4 node but got correctly rejected by the V5 since he received a block without a valid block signature. This can only be V5 nodes transmitting blocks which have been stored without the block signatures beforehand.


so it seems the node does a reliable job at rejecting incorrect blocks overall. But I think there’s only one way to go here. Raising the network protocol version by one due to the major changes and black list all nodes between V4 and new protocol. Since they are causing the chain splits.

**Comment by marpme** [comment]
Would be funny if the V5 is still getting synced because he will just reject the block coming from this node, but if someone else like a V4 sends the block then it should work properly. Since he arguably has check the block and set it as valid chain.

**Comment by tpfuemp** [comment]
@badbrainIRC: chkdsk? really, this is your hint after this long history of issue discussion? 

@marpme : let me guess too: maybe there is a logic problem in sync of blocks. as I read the code right, alternate chains are transfered with headers only, but only headers without tx-set are not enough to check signature. before activating such chain, blocks have to be retrived as full blocks. so maybe there is a logic path where this "empty" blocks are written to disk.

**Comment by marpme** [comment]
So yeah you are totally right with your statement. Once headers are received we are doing a lot of consistency checks against them but obviously, we can't check the signature of it since we neither have the signature nor the transaction used to sign it. 

And after checking through it will be written as CBlockIndex which gets persisted to the disk, but I couldn't find any evidence where a header "alone" can be the new active chain. The codebase will fetch the connected blocks after checking them it's going to land @ `ActivateBestChain` which will, in the end, connect the tip to the active chain if possible.

So I can't see this happening that headers are saved which will lead to broken blocks but then they are "orphan" and furthermore the rest of the chain is just moving on with the "most" work chain :)

**Comment by pinpins** [comment]
Just wondering as if there is decent understand of issue, can we expect some fix or at least plan for it

**Comment by marpme** [comment]
It's rather trial and error since this like huge pain in the ass to debug those kind of issues. Sorry for not giving any plan out here since I can't really.

**Comment by justinvforvendetta** [comment]
@pinpins why do you think this issue is remaining open? lol

**Comment by pinpins** [comment]
> @pinpins why do you think this issue is remaining open? lol

I have no idea, you tell me... lol
