### ISSUE TITLE
Block 3199511 timetraveled?

### ISSUE THREAD

**Issue by Ur-Quan** [vergecurrency/VERGE#941]
Say, should blocktime for the new block always be higher than previous? If it should, I see some weird things. 3198660 and 3198661 for ex.

Ed: not some. A lot of. For lyra in past 24 hrs:

| height  | height  | from_unixtime(a.blocktime) | from_unixtime(b.blocktime) | diff_in_secs |
+---------+---------+----------------------------+----------------------------+--------------+
| 3197363 | 3197364 | 2019-06-10 15:04:26        | 2019-06-10 15:02:24        |          122 |
| 3197424 | 3197425 | 2019-06-10 15:43:19        | 2019-06-10 15:43:11        |            8 |
| 3197636 | 3197637 | 2019-06-10 17:37:23        | 2019-06-10 17:34:27        |          176 |
| 3197861 | 3197862 | 2019-06-10 19:48:10        | 2019-06-10 19:47:58        |           12 |
| 3198025 | 3198026 | 2019-06-10 21:21:00        | 2019-06-10 21:20:51        |            9 |
| 3198286 | 3198287 | 2019-06-10 23:44:57        | 2019-06-10 23:44:45        |           12 |
| 3198364 | 3198365 | 2019-06-11 00:27:45        | 2019-06-11 00:25:26        |          139 |
| 3198414 | 3198415 | 2019-06-11 00:53:27        | 2019-06-11 00:53:18        |            9 |
| 3198540 | 3198541 | 2019-06-11 02:03:46        | 2019-06-11 02:03:21        |           25 |
| 3198660 | 3198661 | 2019-06-11 03:12:02        | 2019-06-11 03:09:03        |          179 |
| 3198923 | 3198924 | 2019-06-11 05:32:34        | 2019-06-11 05:32:19        |           15 |
| 3199002 | 3199003 | 2019-06-11 06:23:27        | 2019-06-11 06:23:13        |           14 |
| 3199005 | 3199006 | 2019-06-11 06:24:26        | 2019-06-11 06:24:14        |           12 |
| 3199442 | 3199443 | 2019-06-11 10:30:00        | 2019-06-11 10:29:50        |           10 |
| 3199506 | 3199507 | 2019-06-11 11:07:36        | 2019-06-11 11:07:21        |           15 |
| 3199510 | 3199511 | 2019-06-11 11:08:44        | 2019-06-11 11:08:15        |           29 |
| 3199570 | 3199571 | 2019-06-11 11:34:39        | 2019-06-11 11:34:11        |           28 |
| 3199704 | 3199705 | 2019-06-11 12:50:52        | 2019-06-11 12:48:16        |          156 |
| 3199760 | 3199761 | 2019-06-11 13:22:06        | 2019-06-11 13:21:38        |           28 |

Ed2: I know some coins tolerate 60 secs of time diff. But there are almost 180...

**Comment by marpme** [comment]
That’s known and it’s nothing bad tho :)

**Comment by Ur-Quan** [comment]
Okay, but how's getnetworkhashps calculated then? It zeroes negative time differences?
