### ISSUE TITLE
[V5] Win64 - Wallet connection issue 

### ISSUE THREAD

**Issue by kevintenda** [vergecurrency/VERGE#942]
The new wallet still doesn't connect to the peers, whereas the old wallet, after downloaded the newly updated blockchain, now sync faster, but after synced the (old) wallet doesn't open as expected and it says 'rescanning...'

I can't use both wallets

The OS is Windows 64 bit.

P.S. @marpme Why have you closed the issue that I opened a couple of hours ago, when:

1) No one answered it nor solved it.
2) Why you closed it without say anything?!

Show some respect.

**Comment by jrsikors** [comment]
The old 4.x and new 5.x create different types of files/structure locally on your computer  in your *datadir*. 

Unless you are running each verge-qt.exe with a different *datadir* for each different version, you will probably run into weird problems having both versions in the same datadir.

I would focus on 1 problem..
 -get 4.0 to work
 -get 5.0 to work

Either way the first step would probably be the same .. wipe out everything in *datadir* except wallet.dat would be a good start, and re-load the correct bootstrap.

**Comment by kevintenda** [comment]
I am the average Joe.

Where is datadir located? I went to User/Name of the User/AppData/Roaming/Verge. 
Have not found it there. Though I found wallet.dat

what does re-load the correct bootstrap mean?

**Comment by 2lazy2debug** [comment]
Well, 

First, there's no issue that you opened a couple of hours ago from your username in this repository, if you opened in another repository, sorry that you didn't get feedback on it but we got to filter the issues and when you open up a repository it clearly describes what's about. **So I'd leave an apology to @marpme here.** 

@jrsikors suggested that you have at least one wallet to work. Let's start out with the v5 which looks like is giving you a headache. 

Start by downloading a copy of the blockchain from here : https://verge-blockchain.com/

While downloading, let's continue

If we assume you want to run both wallet versions, you'll have to create a different datadir for the v5 wallet, you just can't have v4 and v5 run on the same data directory. Let's keep the v4 as is. 

I suggest you to create a datadir named Verge5 in the same directory where Verge is, and change the shortcut to the wallet (on your Desktop I suppose) by adding the following parameter : 
```c:\users\kevin\Desktop\verge-qt.exe -datadir=C:\Users\Kevin\AppData\Roaming\Verge5 ``` 

You can have more instructions here about that point  : https://bitzuma.com/posts/moving-the-bitcoin-core-data-directory/

Try opening up the wallet, you'll have a first launch experience. When done close it. Now, extract the blockchain archive that you downloaded earlier to a folder, and copy-paste the whole content in the Verge5 directory, ensuring that you overwrite what's already there (besides the wallet.dat). 

Open up the wallet again, and it 10 minutes you should be done. 

If you're not getting connections, you can copy-paste the list of servers from this file : 
https://github.com/vergecurrency/VERGE/blob/0d669aab902c12c97cd8beabe8151b3e26f3f3b8/doc/peers.txt 

--

Please be aware that our community and core team is volunteer-based. Nobody is paid, nor works full time with Verge. Consider being respectful and polite while opening an issue. No need to use CAPS LOCK TO WRITE A TITLE, neither being rude to the team members. 

We will help you, we're here for that. 

If this answer helped you, consider donating to the team : https://vergecurrency.com/donate/

**Comment by jrsikors** [comment]
if you have coins in your wallet .. make sure you have a backup of your wallet.dat on a USB drive or another computer before doing any of this (you should already have one anyways 💯 ) from User/Name of the User/AppData/Roaming/Verge

**Comment by jrsikors** [comment]
and for QT 101... inside your data directory:
User/Name of the User/AppData/Roaming/Verge

You should see a bunch of files and folders.  There are a few key ones:
-wallet.dat = your wallet
-peers.dat = file containing other peers in the verge network
-debug.log = debug log
some folders like /chainstate/ /blocks/ , maybe a blkindex.dat ... this is the blockchain you've downloaded.

so essentially to nuke it and start over, you just want to delete everything inside your User/Name of the User/AppData/Roaming/Verge folder EXCEPT wallet.dat.

the next time you start verge-qt , it will re-create all the files needed and start re-downloading the blockchain.

Manuel's method is the exact same (new/empty data directory), but it's safer because you aren't "deleting" anything.  But i like to live life on the edge 😀 

once you get to that point -- and you run 5.x verge-qt --  if you still have peers issues -- we should be able to help easily with that... but need to see if you even need help after doing that stuff

**Comment by 2lazy2debug** [comment]
Jeez bro you on fire @jrsikors

**Comment by kevintenda** [comment]
I deleted all the files expect the Wallet.dat.

I started Verge-qt and the deleted files came back.

Still blockchain is stuck with no connection to peers.

**Comment by jrsikors** [comment]
go to Help -> debug -> console

type:
addnode add "otcwkocmpptqadjc.onion"
hit enter
addnode add "vav7wo53kmlmxm4b.onion"
hit enter

give it a few minutes and see if they show up.  I'm not in front of QT right now but I think that's the right command to add a node.

**Comment by 2lazy2debug** [comment]
> I deleted all the files expect the Wallet.dat.
> 
> I started Verge-qt and the deleted files came back.
> 
> Still blockchain is stuck with no connection to peers.

Have you done the whole process I suggested ?

**Comment by kevintenda** [comment]
This is the result from adding nodes:
 |   | otcwkocmpptqadjc.onion
| Method not found (code -32601)

 | vav7wo53kmlmxm4b.onion
Method not found (code -32601)

**Comment by jrsikors** [comment]
Maybe put add in quotes as well: “add”

-Jeff

**Comment by kevintenda** [comment]
@2lazy2debug  I tried but couldn't finish it.

Thinking of delete all the blockchains and wallets and start over.  What do you think? I just need one running wallet.

Already have the backup. Money are safe.

**Comment by kevintenda** [comment]
I tried this way

 "add otcwkocmpptqadjc.onion"

And this  "add" "otcwkocmpptqadjc.onion"

Same code error

**Comment by cod3gen** [comment]
Set add after node.. < addnode NODE add >

**Comment by cod3gen** [comment]
Should give an empty reply, or error if already added

**Comment by jrsikors** [comment]
thanks, @cod3gen , sorry not at my computer and didn't have time to google yet.. was about to.  that's what i was missing
so

addnode node "otcwkocmpptqadjc.onion" add
addnode node "vav7wo53kmlmxm4b.onion" add

**Comment by 2lazy2debug** [comment]
@kevintenda did you copy paste the values I linked before? you should have your VERGE.conf file filled with "addnode=mynode.onion"

**Comment by kevintenda** [comment]
@cod3gen 
You means like this:  "otcwkocmpptqadjc.onion" "add"?

**Comment by kevintenda** [comment]
@2lazy2debug I'll try that now. 

I have not done it cause I didn't know how to.

I do it now.

**Comment by jrsikors** [comment]
you can do this in console as well with these commands:
addnode node "otcwkocmpptqadjc.onion" add
addnode node "vav7wo53kmlmxm4b.onion" add

**Comment by kevintenda** [comment]
Doesn't work neither that those peers in the link

**Comment by kevintenda** [comment]
> 
> 
> you can do this in console as well with these commands:
> addnode node "otcwkocmpptqadjc.onion" add
> addnode node "vav7wo53kmlmxm4b.onion" add

The response

  | addnode "node" "add\|remove\|onetry"  Attempts to add or remove a node from the addnode list. Or try a connection to a node once. Nodes added using addnode (or -connect) are protected from DoS disconnection and are not required to be full nodes/support SegWit as other outbound peers are (though such peers will not be synced from).  Arguments: 1. "node"     (string, required) The node (see getpeerinfo for nodes) 2. "command"  (string, required) 'add' to add a node to the list, 'remove' to remove a node from the list, 'onetry' to try a connection to the node once  Examples: > verge-cli addnode "192.168.0.6:21103" "onetry" > curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "addnode", "params": ["192.168.0.6:21103", "onetry"] }' -H 'content-type: text/plain;' http://127.0.0.1:20103/  (code -1)
-- | --

**Comment by cod3gen** [comment]
Not addnode node...

addnode otcwkocmpptqadjc.onion add
addnode vav7wo53kmlmxm4b.onion add

**Comment by jrsikors** [comment]
oh it's just the ordering? 🤕  💩   my bad

**Comment by kevintenda** [comment]
> 
> 
> Not addnode node...
> 
> addnode otcwkocmpptqadjc.onion add
> addnode vav7wo53kmlmxm4b.onion add

Now it says null

**Comment by jrsikors** [comment]
null is good, just give it a few mins now and see if the peers start connecting / increasing on their own

**Comment by cod3gen** [comment]
That means they are now added 👍 try doing the commands again and you should get error instead

**Comment by kevintenda** [comment]
Sync Header is moving. Up to 5%

**Comment by jrsikors** [comment]
It will take a while to download the whole blockchain,, many hours , so just let it go for a bit.  Manuel earlier suggested downloading the 'bootstrap':
> Start by downloading a copy of the blockchain from here : https://verge-blockchain.com/

Basically you can download a zip of the whole blockchain, close down QT client, unzip it to your data directory (overwrite existing files/folders), and then open QT , and you will pretty much be sync'd.  

Both ways work, it just depends on whether or not you are feeling patient.  Sometimes downloading the blockchain zip can take hours, so it's easier to just let the chain download 'naturally' like you are doing.

**Comment by kevintenda** [comment]
Up to 55%

I got time. Finger cross everything will go smooth.

**Comment by kevintenda** [comment]
Last night the wallet has finished to download all the blocks. I launched it today and this is the result:


-It took half an hour to load the blocks and get to the wallet. 

-Waited for over an hour for the wallet to connect to the nodes. But nothing.

-I had to add the nodes manually, like I did yesterday, and successfully download the last few blocks.

- I might be wrong but I noted that this node - addnode otcwkocmpptqadjc.onion add - might be dead.


 I believe the wallet should always connect automatically to the nodes without my intervention. How can we fix this?

**Comment by 2lazy2debug** [comment]
Generally peers info are stored into the peers.dat file. however you can be sure to always have an online peer by adding some nodes to the verge.conf file in the datadir folder, as I told you already twice. 
just copy paste them from the sample file I provided earlier. at least 10-15 of those nodes are always active.

**Comment by kevintenda** [comment]
> 
> 
> Generally peers info are stored into the peers.dat file. however you can be sure to always have an online peer by adding some nodes to the verge.conf file in the datadir folder, as I told you already twice.
> just copy paste them from the sample file I provided earlier. at least 10-15 of those nodes are always active.

To be more precise the first time you dropped a link with a list of servers and that's it. Haven't really explained it what should I do with it. How to use it. Where to, and so on.

Later on you asked if I added that list on verge.conf... But obviously I haven't done it since your instructions were incomplete, make it hard for me to follow it.

Now, I am looking at datadir folder but there is no verge.conf file. This could explain why I have no nodes.

**Comment by 2lazy2debug** [comment]
> To be more precise the first time you dropped a link with a list of servers and that's it. Haven't really explained it what should I do with it. How to use it. Where to, and so on.
> 
> Later on you asked if I added that list on verge.conf... But obviously I haven't done it since your instructions were incomplete, make it hard for me to follow it.

Didn't notice sorry, could've mentioned earlier. 
Instruction on how to create and use the verge.conf file are on the readme in front page of the repo, thus I assumed you knew what I was talking about : 

https://github.com/vergecurrency/VERGE#wallets  

Create a verge.conf file and just paste the whole addnode=somehting list. You can even use the example file given, just change username and password.

**Comment by jrsikors** [comment]
The nodes all disappearing isn't abnormal for Tor.. i always check:
https://verge-blockchain.info/network
and grab a couple of those to add manually.

Not finding any peers happens to me as well, but Marvin and Justin and many many people haven't been able to duplicate the issue.. so it comes down to probably our ISPs.

As for the blocks taking forever to load, that almost sounds computer related.  Either your computer is old/slow, you have too many things running, your computer is struggling with this type of app, or maybe your virus scan is overly protective.

**Comment by kevintenda** [comment]
> 
> 
> > To be more precise the first time you dropped a link with a list of servers and that's it. Haven't really explained it what should I do with it. How to use it. Where to, and so on.
> > Later on you asked if I added that list on verge.conf... But obviously I haven't done it since your instructions were incomplete, make it hard for me to follow it.
> 
> Didn't notice sorry, could've mentioned earlier.
> Instruction on how to create and use the verge.conf file are on the readme in front page of the repo, thus I assumed you knew what I was talking about :
> 
> https://github.com/vergecurrency/VERGE#wallets
> 
> Create a verge.conf file and just paste the whole addnode=somehting list. You can even use the example file given, just change username and password.

Like I said earlier, in my second post on this page, I am the average Joe, I'll try my best to follow it. 

Correct me if I am wrong:

1) **Download the pre-compiled software** - I assume download the wallet !?

2) **Install** - If it meant the wallet then it's done already

3) **In windows file explorer, open c:\Users\XXX\AppData\Roaming\VERGE (be sure to change XXX to your windows user)** - OK

4) **Right click and create a new file verge.txt** - I right clicked and then clicked on Text Document and I named it verge.txt

5) **Edit the file to have the following contents (be sure to change the password)** - I edited the file as per instruction and gave a random password.

6) **Save and close the file** - OK

7) **Rename the file to verge.conf** - OK I noted that now I have two files one called verge.txt and the other called verge.conf. Is that right?

8) **Start the VERGE-qt program**. OK

9) **Open up VERGE-qt console and run getinfo (or getmininginfo) to verify settings** - I am assume after the wallet is open, got to find somewhere a getinfo to verify settings which should be the ones I wrote  on verge.conf.

And finally add the list of the nodes in verge.conf.

Waiting for the wallet to open for the 9th instruction.

**Comment by kevintenda** [comment]
Can't find getinfo nor getmininginfo. What is it? Where to find?

**Comment by kevintenda** [comment]
> 
> 
> The nodes all disappearing isn't abnormal for Tor.. i always check:
> https://verge-blockchain.info/network
> and grab a couple of those to add manually.
> 
> Not finding any peers happens to me as well, but Marvin and Justin and many many people haven't been able to duplicate the issue.. so it comes down to probably our ISPs.
> 
I doubt the issue is the ISP. In my case I can tell that I've been using the wallets for about two years and never had a problem with the nodes. I started to have the problem with this new wallet. At the same time I have another XVG wallet, in my MAC and I don't have any problem with the nodes. 

I woldn't say the nodes disappear because this implies they were already there. As I understand my problem was just the lack of nodes, since the day one. That's why blockchain couldn't start. 

> As for the blocks taking forever to load, that almost sounds computer related. Either your computer is old/slow, you have too many things running, your computer is struggling with this type of app, or maybe your virus scan is overly protective.

I mentioned it takes thirty mins to open just to check whether or not that was normal. This pc is old, indeed.

**Comment by kevintenda** [comment]
UPDATE:

Since last time I wrote you here I noted two improvements in the wallet:

1) Now to launch the wallet takes 3-4 mins and not 30 mins as I said before. (no joking)
2) The wallet is automatically connecting to the nodes, despite the fact I have not added the list of nodes into verge.conf. (not even sure if the way I create verge.conf file is correct, therefore I haven't continued, waiting for a feedback from verge devs).

Can't figure out how that was sorted.

At this point I think the issue is solved and can be closed.


Thanks to @jrsikors @2lazy2debug @cod3gen

**Comment by marpme** [comment]
Thank you for your valueable feedback, if there’s anything we can help you with. Let us know. Have a great day :)
