### ISSUE TITLE
importstealthaddress missing

### ISSUE THREAD

**Issue by zenmagg0t** [vergecurrency/VERGE#943]
# Missing functionality

## Prerequisites

* Running version 5.1.2.0 (64-bit) on Mac OS v10.14.5

## User Story:

* "I'm submitting a ... "
  - [ ] feature request

## Expected Behavior

Used to have exportstealthaddress and importstealthaddress from within the debug console inside the wallet. 

## Current Behavior
Today I tried to import my stealth address and this functionality no longer exists. From the QT wallet v 5.1.2.0 Method not found (code -32601)

## Possible Solution

Add back in, document any replacement functions better.

## Steps to Reproduce (for bugs)

* Steps :
1. Go to `Help` --> `Debug-window`
2. Type `importstealthaddress` or `exportstealthaddress`
3. See "Method not found (code -32601)"

## Your Environment

* Verge Release: 5.1.2.0 (64-bit)
* OS: 
    - Mac OS v10.14.5

**Comment by justinvforvendetta** [comment]
yeah I'll dig it up from the old rpc wallet code and implement it again. we can leave this open for now

**Comment by justinvforvendetta** [comment]
fixed in https://github.com/vergecurrency/VERGE/pull/966
