### ISSUE TITLE
Verge Testnet

### ISSUE THREAD

**Issue by uurcm16** [vergecurrency/VERGE#945]
## Context

Trying to build a pool and I need a **low-diff testnet** to check the pool software. testnet=1 is set in the config file.
But, Verge-qt cannot connect or find any peers.

And I've added testnet node ddvnucmtvyiemiuk.onion (sunerok)

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [x] support request 
  - [ ] translation request 

## Expected Behavior

Find peer and sync the testnet.

## Current Behavior

Cannot find peers for hours.

## Your Environment

* Verge Release: 5.2
* CPU: 2x Xeon
* GPU: -
* RAM: 128 GB
* OS:
    - [ ] I'm using Mac
    - [x] I'm using Linux
    - [x] I'm using Windows

I've added testnet node ddvnucmtvyiemiuk.onion (sunerok),
I've added testnet=1 parameter to the config file.

**Comment by justinvforvendetta** [comment]
I'll check this and get back to you, I'm pretty sure there are a few testnet nodes running, I'll document them as well

**Comment by uurcm16** [comment]
> I'll check this and get back to you, I'm pretty sure there are a few testnet nodes running, I'll document them as well

Hi there. It has been 1.5 days and still no peers for the testnet. 
Waiting for your reply :)

**Comment by marpme** [comment]
I’m currently also deploying a new server with a testnet node. ETA: 1-3 hrs

**Comment by marpme** [comment]
Mine is: `y45ndakzeplwwzzvvvfh4z52o56exsedy3p6tpo2ulvfk4k4eozucvqd.onion:21104`

**Comment by uurcm16** [comment]
> y45ndakzeplwwzzvvvfh4z52o56exsedy3p6tpo2ulvfk4k4eozucvqd.onion:21104

Hi there.
I've added your node about 3 days ago. And still nothing :S

**Comment by marpme** [comment]
Yes what do you expect, new blocks? I don't get what the problem is here :) 

You are now connected to the network feel free to mine, spam, test or whatever you like.

**Comment by uurcm16** [comment]
> Yes what do you expect, new blocks? I don't get what the problem is here :)
> 
> You are now connected to the network feel free to mine, spam, test or whatever you like.

What do I expect? As I mentioned in the first lines of the issue, verge testnet cant find any peers to sync. Daemon must be synced to mine, spam or test. It has been 3 days after adding your node, and still => http://prntscr.com/o6ayoj

**Comment by marpme** [comment]
Just move over to the console and type in `generate 1` and then you will be able to do everything you want I guess.
