### ISSUE TITLE
5.2.0.0 | 0/unconfirmed, in memory pool

### ISSUE THREAD

**Issue by Woutoud** [vergecurrency/VERGE#946]
# Issue Template

## Context

I tried to sent an amount of XVG from my Lumos wallet to my Binance wallet. Now it's stuck at "Uncomfirmed" and within the details of the transaction it gives me the following information:
Status: 0/unconfirmed, in memory pool
Date: 26-6-2019 20:21
[.....]
Transaction fee: -4.900000 XVG
Net amount: -39 995.424197 XVG
Transaction ID: 7d926080268110718d858a35458b9c3df8c83acaeae2361494ea0f63446d3c5d
Transaction total size: 49151 bytes
Transaction virtual size: 49151 bytes
Output index: 0

## Prerequisites

* [x] Are you running the latest version?
Yes, I just installed 5.2.0.0 64-bit

## User Story:

I'm submitting a support request 

## Expected Behavior

I expected the transaction to go through to Binance.

## Current Behavior

The transaction is stuck in limbo somehow.

## Your Environment

* Verge Release: 5.2.0.0
* CPU: Intel Core i5-6600K
* GPU: nVidia GTX1070
* RAM: 16GB DDR4 G-Skill
* OS: Windows 10 64-bit version 1903, build 18362.175

**Comment by marpme** [comment]
Yep it's a known issue and is currently under development. See also #853 
With the current solution to restore your tx like: https://github.com/vergecurrency/VERGE/issues/853#issuecomment-501172547
