### ISSUE TITLE
mac os wallet: error loading blkindex.dat

### ISSUE THREAD

**Issue by CryptoKaku** [vergecurrency/VERGE#95]
Greetings.

I downloaded the blockchain and moved the contents of the zip into Library/Application Support/VERGE overwriting what was there.  

At launch I get a popup which reads "error loading blkindex.dat".

**Comment by CryptoKaku** [comment]
Update:  I started from scratch and now it's "catching up".  It still looks like it will take a considerable amount of time.

Can I move the same files included in the blockchain zip from a fully synced windows wallet over to the Mac wallet?

**Comment by justinvforvendetta** [comment]
we recommend syncing from scratch.
