### ISSUE TITLE
how to from address to utxo use rpc?

### ISSUE THREAD

**Issue by zdyszm** [vergecurrency/VERGE#950]
I try addressindex=1 in VERGE.conf.  but start node.. show : Error reading configuration file: Invalid configuration value addressindex
How to establish address index?

**Comment by badbrainIRC** [comment]
index=1

**Comment by lloydwoods** [comment]
Did this fix your issue?

**Comment by zdyszm** [comment]
my VERGE.conf is:
server=1
txindex=1
index=1
deprecatedrpc=estimatefee
rpcbind=0.0.0.0
rpcuser=xxxxxx
rpcpassword=xxxxx

when is run   ./verged -datadir=. -daemon  . 
show:  Error reading configuration file: Invalid configuration value index

why?

**Comment by badbrainIRC** [comment]
oh sorry it txindex=1 yep you got it. not index

**Comment by badbrainIRC** [comment]
remove index=1

**Comment by zdyszm** [comment]
i add  txindex=1 ..buf i can't find getaddressutxos...
on other coin , if my add addressindex=1.. i can see getaddressutxos interface.
why.

**Comment by marpme** [comment]
@zdyszm Hey there, I did a quick research on bitcoins decision regarding this address tracking stuff. Unfortunately there is no such a functionality nor can you enable it somehow. So you would have to use our “bitcore” software to keep tracking all addresses, which manually scans all blocks and keeps a log of the addresses ever used.

We won’t support this within the core node.
