### ISSUE TITLE
Blockchain not installing

### ISSUE THREAD

**Issue by GotuJiren** [vergecurrency/VERGE#952]
# Issue Template

## Context

Hi I am trying to install the new Verge lumos wallet and want to apply the blockchain.
When I open my terminal on my mac and put in the line as stated in the introduction, I get the following message:
<img width="845" alt="Screenshot 2019-07-05 at 20 27 51" src="https://user-images.githubusercontent.com/52580821/60823465-e24fc600-a1a7-11e9-88d2-fc896bd1a3c6.png">

## Prerequisites

* [x] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [x] support request 

## Expected Behavior

installing the blockchain to the new wallet

## Current Behavior

Invalid syntax in the terminal

## Steps to Reproduce (for bugs)

* Steps :
1. download latest version
2. Download blockchain
3. Install version
4. Use the commands in the terminal

## Your Environment

* Verge Release: Latest
<img width="247" alt="Screenshot 2019-07-08 at 17 44 42" src="https://user-images.githubusercontent.com/52580821/60823572-16c38200-a1a8-11e9-9fa6-8db3d85797de.png">
    - [ ] I'm using Mac

**Comment by marpme** [comment]
Seems to be a python error, have you tried using `python3`

**Comment by GotuJiren** [comment]
omg @marpme I like you a lot its working now thanks! 👍 😄❤️
