### ISSUE TITLE
RPC not listen in Docker

### ISSUE THREAD

**Issue by forkocean-com** [vergecurrency/VERGE#958]
HI! 
Docker container building from your repository.

My config file:
printtoconsole=1
listen=1
daemon=1
server=1
txindex=1
algo=scrypt
port=21102
rpcport=20102
rpcallowip=0.0.0.0/0
rpcuser=verge-rpcuser
rpcpassword=<secret>

And errors:
#<Faraday::ConnectionFailed wrapped=#<Errno::ECONNREFUSED: Failed to open TCP connection to verged:20102 (Connection refused - connect(2) for "verged" port 20102)>>

**Comment by marpme** [comment]
I also need ya docker-compose & Dockerfile in order to give you a hint. 
But `listen` is enabled by default afaik.

**Comment by forkocean-com** [comment]
Hi! Ok, me change start CMD to ./verge -conf=... 
Trouble new:

2019-08-09T16:55:39Z Using the 'sse4(1way+4way),avx2(8way)' SHA256 implementation
2019-08-09T16:55:39Z Using RdRand as an additional entropy source
2019-08-09T16:55:42Z Verge Lumos version v5.2.1.0 (release build)
2019-08-09T16:55:42Z Assuming ancestors of block c766387a2e0cd6af995ea432518614824fe313e988598ea8b26f58efb99ebcdc have valid signatures.
2019-08-09T16:55:42Z Setting nMinimumChainWork=000000000000000000000000000000000000000000000000000000222e000001

**Comment by justinvforvendetta** [comment]
what is the trouble? nothing here is showing a problem...

**Comment by tpfuemp** [comment]
regarding your main problem: you have to set the rpcbind-option in your config to bind rpc to other interface as localhost.
`rpcbind=0.0.0.0`

for the second problem - it depends on how your docker-environment was build. you can not simple start background daemons with docker - immediately after docker process was finished, all processes spawned in this session will be terminated - the config-option 'daemon' can not be used this way in docker.

one possible solution is to start verge-daemon in foreground and move the docker-session in background by using the right command options.
`docker run -dt -it`

to stop the process you have send the INT-signal to the process (grep the PID of the process and use 'kill -INT <PID>')

**Comment by forkocean-com** [comment]
Yes, thanks, I already figured out the listing and demonization myself.
