### ISSUE TITLE
Anti-Orphaning mechanisms 

### ISSUE THREAD

**Issue by marpme** [vergecurrency/VERGE#963]
### Issue 

This might happen due to the following reasons:

* blocks simply didn’t meet the requirements for the blockchain, specifically spoken: 
  - bad block algorithm
  - bad timing
  - outdated chainstate
* minimum chainwork fits 
* bits are aligning with your PoW 
* ...

Any of those requirements are dead criteria for any block at any point in time. This mostly means that a switch or change within those criteria would require a hard fork.

### Problem solutions:

1. Add a different difficulty algorithm that wouldn’t require a hard block of >5 blocks of the same algo in a row. 

2. adding a blocktemplate indicator if it would make sense to currently invest resources to mine this certain kind of blocks. 

3. a dynamic blocktemplate which automatically switches to the lowest effort algo and offers it to mine while respecting all other criteria’s.

**Comment by pinpins** [comment]
Perhaps, meanwhile we arrive to decent/permanent solution. Good workaround would be to introduce mining_disabled flag in getblocktemplate.

You can refer to this commit for an example of particular change.

https://github.com/tpfuemp/VERGE/commit/c75637ea3fead8c1ad8052a85066384c7a26889d

It is backward compatible, so will not affect any other pools/users.
