### ISSUE TITLE
on ios device i have only two mode feather and moon but no mars mood

### ISSUE THREAD

**Issue by riad-star** [vergecurrency/VERGE#979]
# Issue Template

## Prerequisites

* [ ] Are you running the latest version?

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [ ] feature request
  - [ ] support request 
  - [ ] translation request 

## Steps to Reproduce (for bugs)

* Steps :
1.
2.
3.
4.

## Your Environment

* Verge Release:
* CPU:
* GPU:
* RAM:
* OS:
    - [ ] I'm using Mac
    - [ ] I'm using Linux
    - [ ] I'm using Mac

**Comment by marpme** [comment]
Have you updated your app to the latest version?

**Comment by riad-star** [comment]
No which one

**Comment by marpme** [comment]
This one, download the latest release and enjoy the new mars mode: https://apps.apple.com/us/app/verge-currency-tor-wallet/id1459928869

**Comment by riad-star** [comment]
Ok thanks
