### ISSUE TITLE
Signature of wallet

### ISSUE THREAD

**Issue by SecTec** [vergecurrency/VERGE#988]
## Context

I want to check the integrity of the new release 5.3.1

## User Story:

* "I'm submitting a ... "
  - [ ] bug report
  - [x] feature request
  - [ ] support request 
  - [ ] translation request 

## Expected Behavior

- Download and import a PGP key.
- Check the hashes with PGP
- Check the files against the corresponding hash

## Current Behavior

Can not import PGP public key from [https://keys.openpgp.org/](https://keys.openpgp.org/).

For version 5.3.1 no hashes are given to verify.

## Possible Solution

Upload the PGP public key to the repository or attach as asset.

create and sign hashes for the version 5.3.1 files and optionally store as asset.

## Steps to Reproduce (for bugs)

* Steps :
Do with a clean GPG keyring:
1. go to [https://keys.openpgp.org/search?q=7028B24D2265AA276664B078BA2F0EF99AF2355B](https://keys.openpgp.org/search?q=7028B24D2265AA276664B078BA2F0EF99AF2355B)
2. download key
3. do `gpg --import 7028B24D2265AA276664B078BA2F0EF99AF2355B.asc`

According to [https://keys.openpgp.org/about/faq#older-gnupg](https://keys.openpgp.org/about/faq#older-gnupg) the behaviour is normal at the moment. This keyserver is not suitable to distribute keys initially.

## Your Environment

gpg (GnuPG) 2.2.17

**Comment by marpme** [comment]
You are totally right here, it's inevitable to have a proper release check for our public releases. It would be cool to have this integrated inside of the CircleCI build, but that would require that the CI has the privkey. 

Currently, I do it all manually, but it could definitely be automized. 
I would be really glad if you would support me with integrating this.

**Comment by marpme** [comment]
Done for example on: v6.0.0-alpha release

![image](https://user-images.githubusercontent.com/7430964/66242663-53990980-e702-11e9-9eb0-a88371ef2cd6.png)

![image](https://user-images.githubusercontent.com/7430964/66242683-614e8f00-e702-11e9-92aa-f63c42468631.png)

![image](https://user-images.githubusercontent.com/7430964/66242688-67447000-e702-11e9-97a3-bc4d6786f7a0.png)

**Comment by SecTec** [comment]
Hi,

thanks for signing the new release, but...

... where do I get your public key for verification?

**Comment by marpme** [comment]
Hey @SecTec, the fingerprint is inside the release notes. with the fingerprint you should be able to download my public key from the common key servers. Let me know if you aren’t able to get it. I will see if I can find it on one key server of mine.

**Comment by SecTec** [comment]
Yes, I should be able.  ;)

[keyserver.ubuntu.com](https://keyserver.ubuntu.com/pks/lookup?search=7028B24D2265AA276664B078BA2F0EF99AF2355B&op=vindex&fingerprint=on)
[keys.gnupg.net](http://keys.gnupg.net/pks/lookup?search=7028B24D2265AA276664B078BA2F0EF99AF2355B&fingerprint=on&op=index)
[pgp.key-server.io](http://pgp.key-server.io/pks/lookup?search=7028B24D2265AA276664B078BA2F0EF99AF2355B&fingerprint=on&op=vindex)

Links are only prove of concept.I could only find your key at openpgp.org. But they have a bug that prohibits a key from being freshly imported. Read my first post for that.
