### ISSUE TITLE
WALLET NUMBER OF BLOCK STUCK

### ISSUE THREAD

**Issue by kevintenda** [vergecurrency/VERGE#993]
Hi there,

I upgraded my Verge wallet to the new version that came out last month, on my Win7 64 bit.

After I downloaded the upgraded version, I received a message that told me something (don't remember what) was corrupted. Pretty sure nothing was corrupted as the previous version was working just fine, but because of that, it has to download all the blocks back from 2014.

Now, it's like two days the block is stuck on May 26th 2019, at 19 weeks to be completed.

How do we solve this problem?

P.S. If I posted the issue in the wrong section then let me know where is the proper section for this issue.

Thanks

**Comment by marpme** [comment]
Hey @kevintenda, could you be so kind and tell me which version of Verge you are currently running?

Also, you can speed up your syncing by just downloading the correct block data from here: 
https://verge-blockchain.com/
Please make sure to download the correct data for your version.

**Comment by justinvforvendetta** [comment]
you need a new binary, not to just delete the blockchain data. check the releases tab here and get the newest executable for your operating system

**Comment by kevintenda** [comment]
@marpme Verge 5.3.1 

I already had previous one Lumos, and upgraded to this new release of mid-Sept. 

I don't think it's a problem of speed up the chain because I already have the fast speed downloaded along with Lumos wallet. In fact the speed was pretty fast even when I upgraded to 5.3.1.

However, it got stuck for 2 days on 26th May 2019.

**Comment by marpme** [comment]
Have you deleted your blockchain since you upgraded to v5.3.1.?
That's what you should do, re-index isn't solving the problem.

I think otherwise many other people (like miners etc) would have complaint way earlier.
Hopefully this helps you out.

**Comment by kevintenda** [comment]
By tomorrow I should be able to tell if that worked.
