### ISSUE TITLE
Mining issues

### ISSUE THREAD

**Issue by Coinomatron** [vergecurrency/verge#995]
Hi, I tried solo mining on the 4.0.2 client as well as the 5.3.0, but all I got was errors in nomp when submitting a block. Is nomp working at all with verge or is there some special software required? Also, what verge version should be used for mining? Thanks.

**Comment by marpme** [comment]
Hardfork coming with 6.0.0 

- nomp is definitely compatible
I would need a log or something to help you.

**Comment by Coinomatron** [comment]
Yea, I knew about the hardfork. So what client works best with mining? Last nomp error was this one. Wallet was unlocked.

Daemon returned unexpected return code 500, data = "{\"result\":null,\"error\":{\"code\":-22,\"message\":\"Block signatures couldn't be created\"},\"id\":1572131121324}\n"

**Comment by marpme** [comment]
Do you have at least one output as a P2PK, because this is required

**Comment by Coinomatron** [comment]
Hm, that's not anywhere in the debug file, so maybe this error doesn't pertain to submitted blocks?

**Comment by marpme** [comment]
It even says: _"Block signatures couldn't be created"_ 

There are two reasons for this either your not using a publickey output within your coinbase transaction or your wallet isn't locked.
```
Coinbase {
 outputs {
   PubKey -> 0 XVG
   PubKeyHash -> 730 XVG
 }
}
```
that's how your transaction could look like, maybe you can just activate the POS mode for verge and it will work eventually

**Comment by Coinomatron** [comment]
Uhm, pos 'mode' ? Does that mean in the coin.conf I should add "Reward": "POS" ?

**Comment by justinvforvendetta** [comment]
is there a hybrid option?

**Comment by Coinomatron** [comment]
Yea, I guess I can put that in the coin conf. I'll fiddle some more with it, or just use a pool. On a side note, the 4.0.2 client, after I created a new wallet.dat for mining, keeps rescanning the blockchain, which takes ages on a restart. Any idea how to fix that?

**Comment by justinvforvendetta** [comment]
doesn't it have a hybrid option?

**Comment by justinvforvendetta** [comment]
ah, POS if using ver 4, but you should use 6

**Comment by Coinomatron** [comment]
Version 4 does submit blocks (algo lyra2rev2), but they're all orphaned (10 in a row). Haven't seen any block submission on 6, just the above error about not being able to sign blocks. Had that too with the 'hybrid' option in the coin.conf. Not really sure what to do about it anymore.

**Comment by justinvforvendetta** [comment]
@Coinomatron are you on v6 and ready to go?

**Comment by Coinomatron** [comment]
Thanks for the heads up, I upgraded a few days ago. Closing this, might re-open if I feel like experimenting with mining again and run into things.

**Comment by Widi92** [comment]
Hello there, I've got the same Problem with my nomp solo pool. I'm using the newest version of the coin daemon but everytime when there's a block found the this error occures in nomp:

rpc error with daemon instance 0 when submitting block with submitblock {"code":-22,"message":"Block signatures couldn't be created"}

This is my VERGE.conf

> rpcuser=vergerpc
rpcpassword=test12345
rpcport=20102
port=21102
daemon=1
server=1
listen=1
listenonion=0
maxconnections=38
rpcallowip=127.0.0.1
algo=scrypt

**Comment by marpme** [comment]
> that's how your transaction could look like, maybe you can just activate the POS mode for verge and it will work eventually

@Widi92 ^

**Comment by marpme** [comment]
@Widi92 https://github.com/vergecurrency/verge/issues/995#issuecomment-546699693

**Comment by Widi92** [comment]
Idk how changing reward type in nomp's coin.conf can fix the problem. When I do that nomp still tells me after startup:

> Detected Reward Type:   POW

**Comment by justinvforvendetta** [comment]
is there a hybrid option? are u signing the block? whats ur debug on the verge dameon say?

**Comment by Widi92** [comment]
I don't know if there is a hybrid option. As far as I know Verge is only pow right now. I even don't know how to sign a block, so I guess not.
Time code of nomp error compared with timecode of debug.log doesn't show any suspicious error message.

**Comment by justinvforvendetta** [comment]
what version of the xvg daemon are you running? @Widi92

**Comment by Widi92** [comment]
I'm using v6.0.2

**Comment by justinvforvendetta** [comment]
try switching nomp conf to pos.

**Comment by Widi92** [comment]
Already tried that before, still not working.

**Comment by justinvforvendetta** [comment]
@Widi92 https://github.com/marpme/node-stratum-pool/commit/12673c137d97d949d8c9b3536a6b731d8331c0fa

**Comment by Widi92** [comment]
@justinvforvendetta Thanks a lot, it's working now!

**Comment by justinvforvendetta** [comment]
hellz yeah
