### ISSUE TITLE
SHA256 hashes shown for 6.0.0 release downloads, not SHA512 as indicated

### ISSUE THREAD

**Issue by todw1fd** [vergecurrency/VERGE#999]
Issue:
For 6.0.0 Release, Hashes shown are SHA256, yet are referenced as SHA512.  

-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

86513d8c8721ab868b49d53a9c05f29f52d1692e13276223d2036b803bc3e6dd  verge-6.0.0-osx-unsigned.dmg
093720a14755f21737975bc8e3ac5ed901f03ac84737c499fd5956404e66c76f  verge-6.0.0-osx64.tar.gz
d10c48f5f01c1eb0c43c727417af61062f6033d59aa3ffb603ba06a7c8cb363d  verge-6.0.0-win64-debug.zip
b9e9bede576378e469e3a78071237ba0791ea90c102c1003e31d9931eaadcb5c  verge-6.0.0-win64-setup-unsigned.exe
87506181a1a9d8823ccffdc51cc72199084a63c6fc1053eea6e8ab4e20849a8f  verge-6.0.0-win64.zip
d1f560355d301c249d0afb9c0c7ff57e29fd15bf6033e38778462fbddfdf2e43  verge-6.0.0-x86_64-linux-gnu-debug.tar.gz
c9d3fbce999a88d8a484248fa67df9b0e566aa79e57c05a5a7dae4e4443544dd  verge-6.0.0-x86_64-linux-gnu.tar.gz
d85806ff3f89b436b6b2933a74fe64b2c6499364d5a68fa6811a81f850bbe056  verge-6.0.0.tar.gz
-----BEGIN PGP SIGNATURE-----

**Comment by marpme** [comment]
Oh sorry, replaced the hash function manually for now. I will try to update the hash procedure later on.
